### ISSUE TITLE
Privacy Badger should work even if the user blocks [some] cookies

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadger#1]
Currently if you block 3rd party cookies PB won't do anything.  We can watch incoming cookie headers to work around this.

**Comment by yieldman** [comment]
Disabling 3rd party cookies renders Privacy Badger ineffective. PB can only be trained if you keep 3rd party cookies enabled. This issue should still be open.

**Comment by yieldman** [comment]
@cooperq your insight?

**Comment by cooperq** [comment]
@yieldman privacy badger should still see the 'set-cookie' headers and use those in it's heuristic even if they aren't honored by the browser.

**Comment by yieldman** [comment]
We should reopen this issue then . I can reproduce this issue by :-
1. Starting with a fresh profile.
2. Installing unmodified PB from chrome store.
3. Disabling third party cookies.

**Comment by yieldman** [comment]
My apologies. I made a mistake . This isn't a bug but a false report.
