### ISSUE TITLE
no-cache.hubspot.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1000]
https://www.paytrail.com/

`no-cache.hubspot.com` blocks these images:
https://no-cache.hubspot.com/cta/default/335946/7cede0df-e423-4922-bbb4-60e385bfde5a.png
https://no-cache.hubspot.com/cta/default/335946/f8fcc8f1-73c1-4f57-aaa4-7cabbc7661e1.png
https://no-cache.hubspot.com/cta/default/335946/c51e1fb8-a837-406c-a7a5-57aa7fdb95c8.png
https://no-cache.hubspot.com/cta/default/335946/f8fcc8f1-73c1-4f57-aaa4-7cabbc7661e1.png

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.
