### ISSUE TITLE
Overhaul of User Filter Settings page

### ISSUE THREAD

**Issue by ralish** [EFForg/privacybadger#1005]
The **User Filter Settings** tab in **Privacy Badger Options** can become barely functional after extended usage of the extension as the number of *tracking domains* continues to increase. Testing on Chrome 64-bit v54.0.2840.99 m on Windows 10.

Major concerns include:

**Performance**
The number of *tracking domains* continues to grow and at the time of writing is 3694 on my system. These are all loaded at once into the UI, which results in a slow page load, and noticeably "laggy" page interaction. Conducting a very unscientific test via the Chrome Task Manager shows simply loading the page costs in excess of 400MB of RAM.

**Usability**
Navigating such a huge list of domains via the scrollbar is difficult. The list should probably be paginated, but with such a large list, you have to wonder how useful it is to show all the *tracking domains* at all if they're on the default setting? Being able to toggle only showing the domains that have non-default settings would presumably drastically cut-down the number of domains to display and be more useful to the majority of users?

**Comment by terrorist96** [comment]
I fully agree. My page shows over 7000 domains. It's unbearable.

**Comment by alexristich** [comment]
Thanks for the report of this. You're right, it does get quite slow with a lot of domains. I'm going to start taking a closer look into this to see where the major performance hits are occurring, and will see if there are any minor tweaks we can make for the Privacy Badger 2.0 that would improve this. If not, I'm sure we can squeeze it in to the 2.1 release!

**Comment by cowlicks** [comment]
I would prefer infinite-load-on-scroll to pagination. This would also avoid the performance hit from loading every blocked resource right when you open the page.

**Comment by cooperq** [comment]
That was my suggestion as well! @cowlicks is this something you can whip
out?

**Comment by cowlicks** [comment]
@cooperq I can take a look tomorrow if that is okay with @alexristich

**Comment by alexristich** [comment]
@cowlicks Totally! I'm looking to be a little strapped for time over the next several days, so if you have some time to look into this as well (and possibly even make some progress on it) that'd be awesome :)

**Comment by alexristich** [comment]
Load on scroll seems to be doing wonders so far. It brings the load time to a consistent margin for users regardless of how many items are present in their `action_map`. Still, I think we can make further improvements for the 2.1 release. I did a bit of profiling, and `Parse HTML` for a single `<div>` tracker element takes around 15ms (though in some instances up to 30ms) and `Recalculate Style` takes around 20ms, with a total of around 60ms being devoted to the loading of each additional element.

![image](https://cloud.githubusercontent.com/assets/11308076/20904440/651c0d8e-baf4-11e6-8d91-7f144c46543e.png)

This amounts to a pretty big chunk of the overall loading, the majority of which is in parsing the HTML and rendering it to the screen. If we can improve this, we can then (a) improve the load time of the options page further, (b) show more elements by default, and (c) load elements in larger batches without the visible lag.

I'm going to start by looking at the HTML itself and seeing what is contributing the most to the parsing/rendering and will post back here with some results.
