### ISSUE TITLE
Run selenium tests in firefox and chrome

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadger#1009]
Right now the selenium tests run only in chrome, all of the tests should run in firefox as well so we can make sure we are not breaking either browser.

**Comment by ghostwords** [comment]
Would be good to verify that test would catch Chrome-only `src/fingerprinting.js` getting re-added in the manifest (via something breaking). We probably want to add a canvas fingerprinting detection functional test regardless ...

Should test on Firefox Beta channel too.

**Comment by cowlicks** [comment]
@ghostwords you suggesting wasn't included in #1168, can you make a separate issue?
