### ISSUE TITLE
Option to cookieblock trackers by default

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadger#1011]
It might be a nice feature to be able to have the default setting for detected trackers to cookie block them instead of allowing them until we see them three times. 

This should be off by default but have a setting in the options menu.

**Comment by cooperq** [comment]
This might be a fun but more complicated task for @zebesta if you are interested. or @alexristich if you are interested.

**Comment by ghostwords** [comment]
Please see https://github.com/EFForg/privacybadger/pull/1016#issuecomment-264542309. This is most likely out of scope for Privacy Badger.

**Comment by paoletto** [comment]
I wonder what the scope of privacy badger is, then, if not protecting user's privacy..

**Comment by ghostwords** [comment]
Our aim for Privacy Badger is to create an install-and-forget, no-configuration-necessary non-consensual tracking protection tool. "Protecting users' privacy" is a way to describe Privacy Badger's mission, not Privacy Badger's scope. Adding optional features that change how Privacy Badger works is probably out of scope.

**Comment by paoletto** [comment]
Is this your description of privacy badger scope, or is it actually written somewhere? And if this is not written anywhere, are you the sponsor of this project, or based on what are you forcing your opinion of what the project is, rejecting a contribution that would affect in no way the default behavior of the software?

**Comment by ghostwords** [comment]
It's my professional judgement exercised as part of my capacity as Privacy Badger project lead.

**Comment by ghostwords** [comment]
All features impose maintenance and complexity costs. Reviewing potential features always involves making tradeoffs and exercising judgement regarding whether the benefits outweigh the costs.

**Comment by ghostwords** [comment]
I think it makes sense to reopen and rephrase https://github.com/EFForg/privacybadger/issues/1514#issuecomment-318605709 as a potential change to the heuristic for all Privacy Badger users. We are not likely to implement it soon, but it's an interesting idea to investigate in the future.
