### ISSUE TITLE
toledoblade.com slideshow broken

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1014]
http://www.toledoblade.com/State/2016/11/30/Calls-renewed-for-concealed-carry-on-campuses-after-Ohio-State-attack.html

The following need to be moved to yellow to fix the slideshow images at top:
`securepubads.g.doubleclick.net`, `www.googletagservices.com`, and `api.youneeq.ca`

**Comment by cooperq** [comment]
Wontfix. thanks!

**Comment by terrorist96** [comment]
#400 ?

**Comment by ghostwords** [comment]
Fixed by #1039 (Youneeq).

**Comment by terrorist96** [comment]
@ghostwords same situation here.

**Comment by ghostwords** [comment]
@terrorist96 Is this still an issue, or was it resolved when we released surrogates? [Previously](https://github.com/EFForg/privacybadger/issues/823#issuecomment-266750354).

**Comment by terrorist96** [comment]
It's fixed.

**Comment by ghostwords** [comment]
OK, thanks for confirming!
