### ISSUE TITLE
amazonaws.com breaks elements

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1015]
http://www.patheos.com/

`css.patheos.com.s3.amazonaws.com` blocks banner logo and drop down arrow images.
`js.patheos.com.s3.amazonaws.com` breaks slideshow element.

**Comment by ghostwords** [comment]
Hello! How do you come across incorrectly blocked CDNs? Could you provide the steps needed to reproduce the problem?

**Comment by terrorist96** [comment]
Hi! Are you asking how I found this problem? Simply by visiting the site and noticing some elements were broken/not loading. Then I disable some extensions to pinpoint the problem. The two mentioned "trackers" are blocked by default (red) on my machine. Moving them to yellow fixes the problem.

**Comment by ghostwords** [comment]
I'm just wondering how PB decided to block `amazonaws.com`, what the sequence of pages was.

If it's not too much trouble, could you visit `chrome://extensions/`, enable "Developer mode", click on "Inspect views: background page" for Privacy Badger, input the following into the console, and share what gets output, if it's not sensitive:
```javascript
chrome.storage.local.get(['snitch_map'], r => { for (const key in r.snitch_map) { if (key.indexOf('amazonaws.com') != -1) { console.log(key, ":", r.snitch_map[key].join(', ') ); } } } );
```

**Comment by terrorist96** [comment]
I'm willing to email it to you, but not post it here publicly.

**Comment by ghostwords** [comment]
You can find it here:  https://api.github.com/repos/EFForg/privacybadgerchrome/git/commits/68a8f6a3bb21b76a1af482e45041d4d75332f747

**Comment by terrorist96** [comment]
Got it, thanks!

**Comment by ghostwords** [comment]
If you visit Privacy Badger's options page, and search domains for "s3.amazonaws.com", is "s3.amazonaws.com" itself marked to be blocked?

**Comment by terrorist96** [comment]
It is set to yellow.
Side note: the options page is incredibly sluggish for me. There's over 7000 listings and trying to do anything on that page is torturous.

Here's a screenshot:
![capture](https://cloud.githubusercontent.com/assets/12802056/20842022/fc03084c-b883-11e6-9334-ab05622f5934.PNG)

**Comment by terrorist96** [comment]
Also, if a domain is too long, hovering over it will not display the full name. For example, the last one in that list, `static.politifact.com.s3.am...`

**Comment by ghostwords** [comment]
Please see https://github.com/EFForg/privacybadgerchrome/issues/1005 for options page performance issues.

**Comment by cooperq** [comment]
I think that the issue here is that com.s3.amazonaws.org needs to be added to the public suffix list

**Comment by terrorist96** [comment]
http://www.penguinmagic.com/p/S9252
US flag image next to "FREE" blocked.

**Comment by terrorist96** [comment]
http://www.weeklystandard.com/gunning-for-hillary/article/2006969
`assets.weeklystandard.com.s...` breaks image at bottom

**Comment by terrorist96** [comment]
http://www.nowinstock.net/

`s3.amazonaws.com` is set to yellow by default, which breaks the site's layout. Moving to green fixes it.
