### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ghajini** [EFForg/privacybadger#1018]
www.chicagotribune.com
each time i load this website ,this site loads different ads,though logger doesn't show ad trackers...but ads are loaded..
go to chicagotribune.com
after loading reload website,ad will appear  on upper side
go to story of website,again it loads ads,,,when hovered over ads ,it show these are from googleadservices.com, doublleclick,net but slider doesn't show these entries.....but looking at logger,each time new ad tracker entry is found and ads are loaded....
chrome shows dialogue site trying to load unauthonticated scripts from unknown source

**Comment by alexristich** [comment]
I took a quick look into this though haven't been able to reproduce this one. I see the ads you're referring to when I turn Privacy Badger off, though when I turn it on they're prevented from loading (as the third parties that are serving them have been blocked). What is your current setting for doubleclick.net? Also, can you still reproduce this? If so, it would be interesting to see a screenshot of the Developer Console (Control+Shift+J).

**Comment by cooperq** [comment]
also can't reproduce.

**Comment by ghajini** [comment]
@alexristich 
same issue happen here also...here googleadservices.com ads are loaded though they are blocked as per pb log
http://news.nationalpost.com/news/canada/canadian-politics/unheralded-committee-seeks-monumental-change-to-the-way-first-nations-get-billions-in-federal-funds

here also googleadservices.com is blocked by pb as per logger of pb
![screenshot 75](https://cloud.githubusercontent.com/assets/20338483/21083009/7646040c-c00d-11e6-85fe-7f2eb6cc1df5.png)

but ads are still loaded
![screenshot 72](https://cloud.githubusercontent.com/assets/20338483/21083037/c8f250fc-c00d-11e6-80a1-23dee7773a97.png)
![screenshot 73](https://cloud.githubusercontent.com/assets/20338483/21083038/c8f58b28-c00d-11e6-8939-d48b86465ce3.png)
![screenshot 74](https://cloud.githubusercontent.com/assets/20338483/21083039/c8f90f3c-c00d-11e6-9fc5-ba86041dc27c.png)

trackers are slipping through privacy badger

**Comment by ghajini** [comment]
Pb not working properly anymore, uninstalling
Breaking websites😢
