### ISSUE TITLE
Add heuristic effectiveness tests

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1019]
Would be really good to start collecting metrics on Privacy Badger's effectiveness to help verify any changes to the heuristic.

Proposal: Use Selenium to statefully drive Privacy Badger across thousands of websites, collect the findings. Create a reporting UI to compare one set of findings to another set.

**Comment by jawz101** [comment]
Would this include Firefox for Android?

**Comment by ghostwords** [comment]
Not initially ... this is to appraise tweaks to the heuristic, to start with. Cross-browser differences don't seem like a priority, at least in the beginning.

**Comment by jawz101** [comment]
Ah.  I think I was reading two of your Selenium-related enhancement tickets at the same time :/

**Comment by zero77** [comment]
To collect data you could add an optional anonymous reporting feature into privacy badger, that collects data on metrics on Privacy Badger's effectiveness. 

Whilst keeping users anonymous and keeping there privacy intact.
