### ISSUE TITLE
api.tegna-tv.com breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1023]
http://www.wusa9.com/news/local/dc/suspect-carrying-assault-rifle-arrested-near-comet-ping-pong/362524922

`api.tegna-tv.com` breaks video.

**Comment by cooperq** [comment]
fixed, thanks!

**Comment by terrorist96** [comment]
@cooperq I got the new update. `api.tegna-tv.com` is still defaulting to red for me on the above site.

**Comment by terrorist96** [comment]
Looking at the cookieblocklist file, you added `tegna-media.com` not `tegna-tv.com`

**Comment by terrorist96** [comment]
#952

**Comment by terrorist96** [comment]
@cooperq

**Comment by terrorist96** [comment]
http://www.12news.com/news/local/arizona/good-samaritan-shoots-kills-suspect-beating-wounded-dps-trooper-on-i-10/385436931

**Comment by terrorist96** [comment]
http://www.abc10.com/news/local/california/california-bill-would-require-warnings-update-on-guns/438857567

**Comment by terrorist96** [comment]
@ghostwords this seems like it should be a simple yellowlist fix, no? since `tegna-media.com` was added but not `api.tegna-tv.com`
http://www.abc10.com/news/local/are-gun-raffles-legal/460332822

**Comment by ghostwords** [comment]
I don't see any tracking from `api.tegna-tv.com` ... Could you run our debugging code for "tegna-tv.com"? Do you have any cookies or localStorage for `tegna-tv.com`?

**Comment by terrorist96** [comment]
![image](https://user-images.githubusercontent.com/12802056/28841355-f45da680-76c7-11e7-82e5-1e5926b13aba.png)

**Comment by ghostwords** [comment]
And no localStorage or cookies if you search under `chrome://settings/content/cookies`?

**Comment by ghostwords** [comment]
I see a few broken video reports with blocked `api.tegna-tv.com`:

- http://www.9news.com/news/education/metro-state-student-interns-on-campus-lands-full-time-engineering-job-with-local-company/448586370 (broken video from 2017-06-13)
- http://www.wfmynews2.com/weather (broken weather radar animation from 2017-03-10)
- http://www.wbir.com/news/traffic/all-lanes-of-alcoa-highway-open-after-sinkhole/391305574 (broken video from 2017-01-23)
- http://www.kvue.com/news/local/population-study-people-leaving-austin/379918957 (broken video from 2017-01-03)
- http://www.khou.com/news/crime/man-facing-assault-charges-after-outburst-at-pool/254046445 (broken video from 2016-06-25)
- http://www.12news.com/news/local/valley/arizona-coyotes-focusing-on-east-valley-site/251669892 (broken video from 2016-06-22)
- http://www.king5.com/news/local/viaduct-news/nb-i-5-bears-bulk-of-gridlock-first-day-of-viaduct-closure/160002854 (broken video from 2016-05-01)
- http://www.12news.com/news/local/arizona/lawmakers-to-hold-special-hearing-monday-on-az-primary-disaster/105996651 (broken video from 2016-03-28)

**Comment by terrorist96** [comment]
> And no localStorage or cookies if you search for "tegna-tv" on chrome://settings/content/cookies?

Correct.

**Comment by terrorist96** [comment]
http://www.wusa9.com/opinion/editorials/off-script/dc-political-comedian-robbed-at-gunpoint-changes-stance-on-guns/509608926
