### ISSUE TITLE
anvato.net breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1025]
http://wwlp.com/2016/07/21/gun-rights-groups-protesting-healeys-crackdown-on-copycat-weapons/

`mcp-media10.cdn.anvato.net` and `mcp-media11.cdn.anvato.net` break the video and thumbnail respectively. Can `*.cdn.anvato.net` be added to the cookieblock list?

**Comment by cooperq** [comment]
fixed, thanks!
