### ISSUE TITLE
error reporting popup test fails mysteriously

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadger#1026]
[test_error_button in the selenium popup tests](https://github.com/EFForg/privacybadgerchrome/blob/df3a7a567b5ee94511d77172130b66e74ad214eb/tests/selenium/popup_test.py#L179) fails for mysterious, race conditiony reasons starting with this commit: https://github.com/EFForg/privacybadgerchrome/commit/8b5e5259d6fdf41ec3c6402308227e6e1b9eb012. This test is disabled for now but it should instead be fixed!

**Comment by ghostwords** [comment]
This was done as part of f471b5ca6782f1b49d3f538616060cd536f2b4f4.
