### ISSUE TITLE
ssl.google-analytics.com breaks functionality

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1041]
https://www.google.com/webmasters/tools/home?hl=en

`ssl.google-analytics.com` blocks the help button in the top right. You have to be signed in to reproduce.

**Comment by cooperq** [comment]
let me know if you still have this issue once you are upgraded to 2016.12.8

**Comment by terrorist96** [comment]
Has it been pushed out yet? Forcing an update still leaves me with the Sept version.

**Comment by cooperq** [comment]
You should get it some time tomorrow.

**Comment by terrorist96** [comment]
@cooperq still broken. :disappointed:

**Comment by terrorist96** [comment]
@ghostwords

**Comment by ghostwords** [comment]
Ah, this is `analytics.js`, not `ga.js`. I'll add `analytics.js` to fix.
