### ISSUE TITLE
Privacy Badger has crashed Click this balloon to reload the extension

### ISSUE THREAD

**Issue by m0lz** [EFForg/privacybadger#1047]
Privacy Badger Version 2016.12.8

Browser = http://chromium.woolyss.com/
Nik wpo cfg all-codecs stable 64-bit
No sync • No WebRTC • No Widevine • 55.0.2883.87 (423768) • Friday, 9 Dec 2016

Problem = Every time I click the Baloon to reload Privacy Badger it crashes again and again and again

I have uninstalled it in case of file corruption, then re-installed the latest version again .. No joy the same problem immediately starts again.

**Comment by groovecoder** [comment]
It looks like this version is built without WebRTC support which causes this.

**Comment by alexristich** [comment]
I gave this a quick try on version 55.0.2883.87 and it seems to work out of the box. It seems the most likely scenario is related to WebRTC being disabled, as @groovecoder notes above. Privacy Badger has built-in protections against WebRTC IP address leakage. There are four modes in the WebRTC specification (https://github.com/EFForg/privacybadger/pull/969#issuecomment-255614654); Privacy Badger uses the 3rd one as the default, and if a user enables goes to the Options page and enables the setting to prevent IP address leakage it will enable the 4th and most private mode.

Would you be willing to enable WebRTC and try again to see if you experience the same issue?

**Comment by qbit** [comment]
uBlock origin had a [similar issue](https://github.com/gorhill/uBlock/issues/533) to this. They fixed it by adding a check like this: https://github.com/gorhill/uBlock/blob/master/platform/chromium/is-webrtc-supported.js

**Comment by mauricecaaaaaben** [comment]
I also have this issue and of course don't have WebRTC.

**Comment by qbit** [comment]
I should also mention, some people are unable to enable webrtc - OpenBSD for example.

**Comment by JHamberg** [comment]
This issue can be replicated by running Chromium build 57.0.2959.0 (64-bit) with WebRTC functionalities disabled. The crash is caused by the method `cpn.webRTCIPHandlingPolicy.get` in [background.js#L183](https://github.com/EFForg/privacybadger/blob/master/src/background.js#L183) and can be mitigated by checking if `cpn.webRTCIPHandlingPolicy.get` is `undefined` when enabling IP leakage protection or checking its state for options. I will now create a pull request for this.

**Comment by qbit** [comment]
@JHamberg  this is from my OpenBSD box. WebRTC is disabled at build time (`enable_webrtc=false`):

```
cpn.webRTCIPHandlingPolicy.get
function (details, callback) {
    var getSchema = getFunctionParameters('get');
    validate([details, callback], getSchema);
    return sendRequest('types.ChromeSetting.get',
```

I have created PR #1097 for this issue already.

**Comment by JHamberg** [comment]
@qbit Your solution seems fine and successfully prevents the extension from crashing on load. There is also an an issue with WebRTC setting in the options menu. There are two more methods which need this check `isWebRTCIPProtectionEnabled` in [background.js#L583](https://github.com/EFForg/privacybadger/blob/master/src/background.js#L583) and `toggleWebRTCIPProtection` in [options.js#L472](https://github.com/EFForg/privacybadger/blob/master/src/options.js#L472). 

WebRTC availability should probably be checked and flagged when creating the badger object.

**Comment by m0lz** [comment]
@JHamberg thanks for the fix, I wondered why I could no longer use PB on the Chromium forks here http://chromium.woolyss.com/ ( typically I use the Stable Installer • Archive • No sync • No WebRTC • No Widevine )
