### ISSUE TITLE
Version 2016.12.8’s panel gets cut off in Firefox menu

### ISSUE THREAD

**Issue by charakterziffer** [EFForg/privacybadger#1048]
I placed the privacy badger amongst the icons in my Firefox menu on the top right. When I click it there the other icons slide to left and a panel opens. Since the update today this panel does no longer fit into the given space but is cut on the right side. It’s not possible to operate the sliders then.

![pb-fixed-width](https://cloud.githubusercontent.com/assets/7194876/21144158/e8a4cae6-c149-11e6-8146-5dfd11589d83.png)

The earlier version had a flexible width and adapted to its container.

BTW: The new panel also seems to be very confusing and untidy. I think the font size of the domains and the buttons are now smaller, the domains have a grey background, buttons have become frames and there’s a misplaced white space under each domain – probably to reserve space for the almost information-free tool tips. I’m a little bit disappointed.

**Comment by groovecoder** [comment]
I'll look into this to see if we can do something to improve the display in the tiny space of the settings pop-up.

**Comment by tl87** [comment]
![privacy badger is acting strange](https://cloud.githubusercontent.com/assets/5989314/21156168/177be518-c175-11e6-8ef2-3b47f82ac371.png)
@charakterziffer, you can atleast see more then I can :-(
