### ISSUE TITLE
suggestions for src/multiDomainFirstParties.js 

### ISSUE THREAD

**Issue by jawz101** [EFForg/privacybadger#1052]
Taken from Lastpass Equivalent Domains and formatted for PrivacyBadger, fyi

["ameritrade.com","tdameritrade.com"]
["bankofamerica.com","bofa.com","mbna.com","usecfo.com"]
["sprint.com","sprintpcs.com","nextel.com"]
["youtube.com","google.com","gmail.com"]
["apple.com","icloud.com"]
["wellsfargo.com","wf.com"]
["southerncompany.com","southernco.com"]
["mymerrill.com","ml.com","merrilledge.com"]
["accountonline.com","citi.com","citibank.com","citicards.com","citibankonline.com"]
["cnet.com","cnettv.com","com.com","download.com","news.com","search.com","upload.com"]
["bananarepublic.com","gap.com","oldnavy.com","piperlime.com"]
["bing.com","hotmail.com","live.com","microsoft.com","msn.com","passport.net","windows.com"]
["ua2go.com","ual.com","united.com","unitedwifi.com"]
["overture.com","yahoo.com","flickr.com"]
["zonealarm.com","zonelabs.com"]
["paypal.com","paypal-search.com"]
["avon.com","youravon.com"]
["diapers.com","soap.com","wag.com","yoyo.com","beautybar.com","casa.com","afterschool.com","vine.com","bookworm.com","look.com","vinemarket.com"]
["1800contacts.com","800contacts.com"]
["amazon.com","amazon.co.uk","amazon.ca","amazon.de","amazon.fr","amazon.es","amazon.it","amazon.com.au"]
["express-scripts.com","medcohealth.com"]
["mynortonaccount.com","norton.com"]
["verizon.com","verizon.net"]
["logmein.com","logme.in"]
["rakuten.com","buy.com"]
["siriusxm.com","sirius.com"]
["ea.com","origin.com","play4free.com","tiberiumalliance.com"]
["37signals.com","basecamp.com","basecamphq.com","highrisehq.com"]
["steampowered.com","steamcommunity.com"]
["chart.io","chartio.com"]
["gotomeeting.com","citrixonline.com"]
["gogoair.com","gogoinflight.com"]
["mysql.com","oracle.com"]
["discover.com","discovercard.com"]
["dcu.org","dcu-online.org"]
["nefcuonline.com","nefcu.com"]
["pepco.com","pepcoholdings.com"]
["century21.com","21online.com"]
["comcast.com","comcast.net","xfinity.com"]
["cricketwireless.com","aiowireless.com"]
["mandtbank.com","mtb.com"]
["dropbox.com","getdropbox.com"]
["snapfish.com","snapfish.ca"]
["alibaba.com","aliexpress.com","aliyun.com","net.cn","www.net.cn"]
["mercadolivre.com","mercadolivre.com.br","mercadolibre.com","mercadolibre.com.ar","mercadolibre.com.mx"]
["taobao.com","tmall.com","alimama.com","1688.com"]
["zendesk.com","zopim.com"]
["telekom.com","t-online.de"]
["healthfusion.com","healthfusionclaims.com"]
["autodesk.com","tinkercad.com"]
["railnation.ru","railnation.de","rail-nation.com","railnation.gr","railnation.us","trucknation.de","traviangames.com"]
["wpcu.coop","wpcuonline.com"]
["mathletics.com","mathletics.com.au","mathletics.co.uk"]
["discountbank.co.il","telebank.co.il"]
["mi.com","xiaomi.com"]
["postepay.it","poste.it"]
["facebook.com","messenger.com"]
["skysports.com","skybet.com","skyvegas.com"]
["disneymoviesanywhere.com","go.com","disney.com","dadt.com"]
["soundcu.com","netteller.com"]
["pokemon-gl.com","pokemon.com"]
["myuv.com","uvvu.com"]
["bank-yahav.co.il","bankhapoalim.co.il"]
["mdsol.com","imedidata.com"]
["volvooceanrace.com","virtualregatta.com"]
["mycanal.fr","canal-plus.com"]
["sanguosha.com","bianfeng.com"]
["sears.com","shld.net"]
["trsretire.com","divinvest.com"]
["norsk-tipping.no","buypass.no"]
["my-bookings.org","my-bookings.cc"]
["skygo.co.nz","skytv.co.nz"]
["altra.org","altraonline.org"]
["xiami.com","alipay.com"]
["belkin.com","seedonk.com"]
["mysmartedu.com","mysmartabc.com"]
["applefcu.org","applefcuonline.org"
["bancomer.com","bancomer.com.mx","bbvanet.com.mx"]
["turbotax.com","intuit.com"]
["shopify.com","myshopify.com"]
["onlineatnsb.com","norwaysavingsbank.com"]
["concur.com","concursolutions.com"]
["ebay.com","ebay.de","ebay.ca","ebay.in","ebay.co.uk","ebay.com.au"]
["techdata.com","techdata.ch"]
["schwab.com","schwabplan.com"]
["hvfcu.org","hvfcuonline.org"]
["firefox.com","mozilla.org"]
["tesla.com","teslamotors.com"]
["morganstanley.com","morganstanleyclientserv.com","stockplanconnect.com","ms.com"]
["cox.com","cox.net"]
["androidcentral.com","mobilenations.com"]
["playstation.com","sonyentertainmentnetwork.com"]
["capitalone.com","capitalone360.com"]
["sony.com","sonyrewards.com"]
["allstate.com","myallstate.com"]

**Comment by jawz101** [comment]
I also don't know why redditenhancementsuite.com and reddit.com are equivalent on your list but maybe I'm missing something.  And redditmedia has never needed to know anything about me.  I just block scripts for that domain with NoScript so I don't know why it's an equivalent.

Regardless, these should be good, I would imagine, considering Lastpass uses this to drive login credentials amongst single signon sites.

**Comment by cooperq** [comment]
Thanks! Probably some stuff worth adding in here, will look into it.

**Comment by jawz101** [comment]
@cooperq I made a little commit in a Fork with the proposed additions.  I didn't address the redditenhancementsuite.com thing but the rest of them are in there.

My other head scratcher is on the alibaba domains because it seems like they own a bunch of similar domains which share logins but I guess that's probably how they do things.

**Comment by cooperq** [comment]
@jawz101 are you going to make a pull request against privacy badger then?

**Comment by jawz101** [comment]
Well I didn't know if it looks good or not.  Plus, I've been doing this through the website and I can't remember how I've done them in the past.  I think you guys wanted pull requests created in a certain way?  Or can you just cherry pick?

**Comment by jawz101** [comment]
I think it's because this nice little info isn't in this new repo :)

https://github.com/EFForg/privacybadgerfirefox-legacy/blob/master/CONTRIBUTING.md
