### ISSUE TITLE
Extension is "corrupted" and can't be repaired on Chrome

### ISSUE THREAD

**Issue by etremel** [EFForg/privacybadger#1057]
I'm using Google Chrome 53.0.2785.101 on Ubuntu. Sometime last night, the Privacy Badger extension quietly stopped working, and today I saw that in chrome://extensions it is disabled (grayed out) with the red error text "This extension may have been corrupted." There's a "repair" button I can click, but it appears to do nothing; the extensions page refreshes and then Privacy Badger is displayed with the "corrupted" text again. 

Uninstalling and reinstalling the extension, both before and after restarting Chrome, does not fix this problem. (After installing the extension, it is immediately disabled and marked as corrupted). Based on earlier bug reports on this extension (and HTTPS Everywhere), I tried setting my "Extension Content Verification" flag to a less strict setting, but that didn't help either.

**Comment by aceat64** [comment]
I'm on version 55.0.2883.75 (64-bit) on Ubuntu 16.04.1 and having the same issue.

**Comment by cbarnsdale** [comment]
Seeing the same thing here, Windows version "Version 55.0.2883.87 m (64-bit)"

**Comment by qxz17** [comment]
I'm having the same problem on Windows version 55.0.2883.87 m (64-bit), and it's also happening the same way with the HTTPS Everywhere extension.

**Comment by qxz17** [comment]
Apparently this is a known issue. There's a previous thread here: https://github.com/EFForg/privacybadger/issues/911. And there's a Chrome developers' thread about it here: https://bugs.chromium.org/p/chromium/issues/detail?id=643814. 

FWIW, even though previously this hadn't worked, I just tried uninstalling and reinstalling both extensions again, and it seems to have worked this time. I don't know why.

**Comment by alexristich** [comment]
This does look like it's the same issue originally reported to the Chromium team back in September. Looking at the progression of the bug report on their bug tracker (kindly linked to by @qxz17), it appears it still hasn't yet been confirmed as fixed. Please try uninstalling and reinstalling the extension again; that appears to help in some cases. Another tip was also posted to #911 saying the following:
```I was able to fix it by visiting the extensions page on the chrome web store - there was a message at the top of the screen saying the extension was disabled and there was a link to re-enable it.```

Here's the link: https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp?hl=en-US

Perhaps see if this helps?

**Comment by jvopelak** [comment]
I have the same issue on  Version 55.0.2883.95 (64-bit) running on a mac.  Tried the solution in the link, it doesn't seem to work.

**Comment by josh-berry** [comment]
+1, Chrome beta 56.0.2924.21 (64-bit), Mac. Reinstalling does not work for me either, nor does repairing or re-enabling through the Chrome Web Store.

**Comment by Scott123456** [comment]
Same issue. Chrome version 55.0.2883.87 m, Windows 7. All proposed solutions fail to work (reinstall, repair, and re-enable from the store page header).

**Comment by etremel** [comment]
@alexristich's suggested method worked for me: Upon visiting the extension's detail page, I got a yellow pop-up message at the top of the page saying "this extension has been disabled" (for some unspecified reason) and giving me a link to re-enable it. Clicking the link successfully re-enabled the extension and the Privacy Badger welcome page opened. However, this doesn't seem to have worked for other people.

**Comment by wjkendall** [comment]
Same issue here on Chrome Version 55.0.2883.87 m (64-bit)
This extension may have been corrupted.
![capture](https://cloud.githubusercontent.com/assets/7632482/21232941/08025024-c2b3-11e6-8b73-9b5be39c3a66.PNG)

**Comment by cooperq** [comment]
This should be fixed by the latest update 2016.12.15.1  let me know if it is still not fixed for any of you.

**Comment by wjkendall** [comment]
yes it is fixed now...thank you very much!

BK
