### ISSUE TITLE
Badger's popup broken in Firefox Private Browsing (Incognito) windows

### ISSUE THREAD

**Issue by NihilNon** [EFForg/privacybadger#1060]
I am not able to see any sliders when I am using a private window, a.k.a. incognito mode, in Firefox.
I have tested multiple sites to verify.
Firefox 50.1.0 (I just updated from 49 and the issue is still present.)
Add-ons: HTTPS Everywhere, NoScript, uBlock Origin, Stylish, Reddit Enhancement Suite, Privacy Badger.
I don't believe this was an issue yesterday and I haven't made any changes beyond updating after discovering the error.
I appreciate any assistance you may be able to provide.

**Comment by groovecoder** [comment]
Now that PB is using WebExtension code-base for Firefox, the checks for `tab.incognito` are working. @cooperq - it looks like PB code has some checks for `tab.incognito`. Could those checks be hiding the sliders UI elements?

**Comment by KidPluto** [comment]
I see this issue also.  Thanks.

**Comment by cooperq** [comment]
I will look into this. Thanks. @ghostwords any ideas?

**Comment by ghostwords** [comment]
@NihilNon @KidPluto Do you have JavaScript disabled in Firefox by any chance? Could this be a conflict with NoScript?

**Comment by ghostwords** [comment]
Ah, looks like this is a browser popup-specific issue: `TypeError: backgroundPage is null` thrown by [popup.js:22:5](https://github.com/EFForg/privacybadger/blob/6f0745bb9af0d3b4fa78a7217e8c17b3ccf32763/src/popup.js#L22). @groovecoder Does this seem like a Firefox Private Mode issue?

**Comment by ghostwords** [comment]
I filed a [Mozilla Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1329304).

**Comment by cooperq** [comment]
According to mozilla:

> This is intentional. Private browsing windows can't access the contents of non-private windows, so you'll need to communicate with your background page in some other way.

So we need to re-architect to use `chrome.extensions.sendRequest()` perhaps to communicate with the background page. This might have the side effect of fixing some other bugs as well.

**Comment by ghostwords** [comment]
This definitely needs more exploration by us, but I updated the Mozilla ticket with some things to look into. Not sure this isn't indeed a Firefox bug.

**Comment by voidstarstar** [comment]
I can confirm this issue.  Additionally the 3 buttons at the bottom (to disable, report a broken site, and donate) do not work, but the help and settings buttons do work.  Clicking does nothing, but they change from gray to black on mouse over.  These symptoms seem similar to #1163.  This occurs on all websites.  Just like the sliders, the buttons only exhibit this behavior in Private Browsing mode and everything works normally in the normal browsing mode.

**Comment by Larsie13** [comment]
I would like to add that when using the Firefox add-on [Private Tab](https://addons.mozilla.org/en-US/firefox/addon/private-tab/), Privacy Badger works like normal when in a private tab within a regular window. A private tab in a private window exhibits the same behavior as a normal tab in a private window.
