### ISSUE TITLE
PB blocking extensions

### ISSUE THREAD

**Issue by 7ranceaddic7** [EFForg/privacybadger#1062]
PB occasionally blocks Blue extension.

[I'll provide extension error when it occurs again.]

(p.s. I know you can't act on this until more info is provided)

**Comment by 7ranceaddic7** [comment]
Update:

Warning:
This extension failed to redirect a network request to data:application/javascript;base64,dmFyIGFiUHJtPXt9O3ZhciBhYk5vT3A9ZnVuY3Rpb24oaSxhKXtyZXR1cm4gKGEmJmEubGVuZ3RoP2FbMF06bnVsbCl8fHRydWU7fSxhYlNDPWZ1bmN0aW9uKG4sdil7ZG9jdW1lbnQuY29va2llPW4rJz0nK3YrJztwYXRoPS87ZXhwaXJlcz0nKyhuZXcgRGF0ZSgobmV3IERhdGUoKSkuZ2V0VGltZSgpKygzMDAwMCo2MCo2MCoyNCkpKS50b0dNVFN0cmluZygpO30sYWJHQz1mdW5jdGlvbihuKXtyZXR1cm4gZG9jdW1lbnQuY29va2llLmluZGV4T2YobisnPScpIT0tMTt9LGFiQWRkTm9PcE1ldGhvZHM9ZnVuY3Rpb24obyxtKXttPW0uc3BsaXQoJywnKTtmb3IodmFyIGk9MDtpPG0ubGVuZ3RoO2krKyl7aWYobVtpXS5tYXRjaCgvXiMvKSl7b1snZ2V0JyttW2ldLnN1YnN0cigxKV09b1snc2V0JyttW2ldLnN1YnN0cigxKV09YWJOb09wO31lbHNle29bbVtpXV09YWJOb09wO319fTt2YXIgYWJDbGlja0V2ZW50PWZ1bmN0aW9uKG4pe2lmKG4uY2xpY2spe24uY2xpY2soKTt9ZWxzZXt2YXIgZT1uLm93bmVyRG9jdW1lbnQuY3JlYXRlRXZlbnQoJ01vdXNlRXZlbnRzJyk7ZS5pbml0TW91c2VFdmVudCgnY2xpY2snLHRydWUsIHRydWUsIG4ub3duZXJEb2N1bWVudC5kZWZhdWx0VmlldywgMSwwLDAsMCwwLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLDAsbnVsbCk7bi5kaXNwYXRjaEV2ZW50KGUpO319O0NPTVNDT1JFPXtCZWFjb246e30sYmVhY29uOmFiTm9PcCxwdXJnZTphYk5vT3B9LF9jb21zY29yZT1bXTs= because another extension (Privacy Badger) redirected it to data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJd2luZG93LkNPTVNDT1JFID0gewoJCXB1cmdlOiBmdW5jdGlvbigpIHsKCQkJX2NvbXNjb3JlID0gW107CgkJfSwKCQliZWFjb246IGZ1bmN0aW9uKCkgewoJCQk7CgkJfQoJfTsKfSkoKTs=.
ID: epanfjkfahimkgomnigadpkobaefekcd

**Comment by ghostwords** [comment]
Please see https://github.com/EFForg/privacybadger/issues/1032#issuecomment-265774776.

**Comment by ghostwords** [comment]
Duplicate of #1134.
