### ISSUE TITLE
Connection to IP on Firefox startup

### ISSUE THREAD

**Issue by martinfischer** [EFForg/privacybadger#1065]
Privacy Badger seems to connect to 151.101.16.201 (currently) on port 443 every time Firefox is started.

I could not find any documentation what this connection is for.

Please explain.

In relation with this issue: https://github.com/EFForg/privacybadger/issues/1064 (Privacy Badger maintains a separate, plain-text list of every domain you've ever visited) it's all a bit weird.

**Comment by Sebb767** [comment]
This seems to resolve to www.eff.org. If you call the IP directly, you get the following:

> <html>
> <head>
> <title>Fastly error: unknown domain 151.101.16.201</title>
> </head>
> <body>
> Fastly error: unknown domain: 151.101.16.201. Please check that this domain has been added to a service.</body></html>

But if you overwrite the host header to www.eff.org and use https you get the EFF page:

`curl --header 'Host: www.eff.org' -k 'https://151.101.16.201'`

Doesn't make this any less shady, but at least it's probably not some unknown third party.

**Comment by jamescooke** [comment]
Definitely not documented - but could be:

* Checking for updates?
* Checking either of these URLs from the `constants.js`? https://github.com/EFForg/privacybadger/blob/6509b89b1015a16ba4cd3139f7e9c468e4e1cf2f/src/constants.js#L33-L34

**Comment by ghostwords** [comment]
Please see https://github.com/EFForg/privacybadgerfirefox-legacy/issues/816 for previous discussion.

**Comment by cooperq** [comment]
@jamescooke this is a call to get the latest version of the two files listed in `constants.js`. One of them is the list of acceptable DNT policies, the other is the yellow list (cookie block list). Both are needed for privacy badger to operate. 

A question for you all is where would you want to see this documented? Like if you were looking for documentation about this, where would you look?

**Comment by jamescooke** [comment]
@cooperq Thanks for the explanation of these calls.

I would like to see these documented as part of the FAQs on the Privacy Badger page: https://www.eff.org/privacybadger - this has some detailed explanation of the blocking algo (under "How does Privacy Badger work?"), so why not have additional information about any phoning home?

In addition, it would be reassuring to know that no tracking or stats are collected as a result of these calls.

**Comment by cooperq** [comment]
Thanks we will add this to the docs. I can assure you that no tracking or identifying information are collected or stored as a result of these calls.

**Comment by cowlicks** [comment]
Would anyone like to add this to `docs/IMPLEMENTATION.md`?

**Comment by ghostwords** [comment]
This is finally up on the website:
https://www.eff.org/privacybadger#faq-Why-does-my-browser-connect-to-fastly.com-IP-addresses-on-startup-after-installing-Privacy-Badger?
