### ISSUE TITLE
Domains not displaying.

### ISSUE THREAD

**Issue by AndyBay** [EFForg/privacybadger#1066]
- Windows 10 64 bit

- Firefox 50.1.0

- Addons: Privacy Badger, uBlock Origin, Reddit Enhancement Suite

- Using new installations and profiles

Using the old version of Privacy Badger, 1.9.2, this is the result when going to reddit.com
![red_50_old](https://cloud.githubusercontent.com/assets/1170184/21178194/afba223a-c1ee-11e6-881b-05da7aedcc3b.png)

Using the new version, 2016.12.8.1, no domains are displaying at all. When clicking on an imgur link, nothing happens, but if I click on a gfycat link, it displays that domain normally.

Using Firefox developer edition 52.0a2 (2016-12-13), Privacy Badger displays one domain.
![red_52_new](https://cloud.githubusercontent.com/assets/1170184/21178349/689351c8-c1ef-11e6-98bf-61779d6e28c9.png)

Also here it doesn't display all the domains, and it has yet to move any sliders on its own. Using the new Privacy Badger in 50.1.0 it also has problems moving sliders on its own, so far only domains from google has turned yellow.

Not sure if it's just not showing the moved sliders or not functioning at all. I am able to move them myself. I've also noticed it does find the imgur domains eventually when I check the settings page, but they are all green. Using the old Privacy Badger version, the imgur links turns yellow instantly.

**Comment by alexristich** [comment]
Regarding only one domain showing up, what's likely happening here is uBlock Origin and Privacy Badger are fighting over domains. If uBlock Origin sees a request first and cancels it, Privacy Badger won't see it. It works the same way if Privacy Badger sees it first. If you disable uBlock Origin temporarily you should see Privacy Badger's list of detected trackers go up. Fortunately the two extensions do work together nicely.

If you go to the options page for Privacy Badger, how many tracking domains are listed? In this list, do you see any that are set to 'block'?

**Comment by AndyBay** [comment]
If I disable ublock Origin, one domain do appear, s.zkcdn.net, which I believe is an ad that ublock blocked. In the options page there are now 50 "potential tracking domains" which I believe should be a higher number? Right now none have been set to block, though previously, before using a new profile, some google domains managed to turn yellow.

I also downloaded chrome to test this, and after viewing maybe three sites, the option page lists over 300 domains. Some of these has turned yellow and red like normal.

**Comment by AndyBay** [comment]
After searching around here a bit I found the reason I didn't get any domains listed when visiting reddit.com. It seems that "reddit enhancement suite" and "imgur.com" are both listed as first party domains under src/multiDomainFirstParties.js. I removed the line with reddit domains, and all the domains I got listed in 1.9.2 reappeared.

The problem still existing is Privacy Badger not blocking any domains on its own.

**Comment by alexristich** [comment]
If you visit a few news sites, say nyt.com, latimes.com, etc., do you eventually see any trackers being moved to the red `block` status?

**Comment by AndyBay** [comment]
Browsing those sites with Privacy Badger and uBlock eventually results in PB blocking (red) google.com, and some other (yellow) goggle domains, so that's good. Using only PB, without any ad blocker, a lot of other domains gets blocked on those sites as well.

Using the old PB version, other domains (e.g. disqus, schibsted) gets blocked, this is not happening in the new version. Using the new PB version with uBlock present results in nothing getting blocked except for a few google domains that did not trigger before I visited those American news sites.

Testing with google chrome, these specific domains also doesn't get blocked. When creating a new profile in Firefox and using PB 1.9.2 the disqus domains instantly turns yellow. Not sure if the new PB handles the disqus domains correctly or if the old, 1.9.2, should not have turned them yellow instantly.

**Comment by ghostwords** [comment]
I think this is a difference between Addon SDK- and WebExtensions-based Privacy Badgers. It seems that the WebExtensions-based Badger works differently in combination with privacy/ad blocking extensions. Now, with WebExtensions, if uBlock blocks a domain, Privacy Badger never gets to learn from that domain. Let me know if this makes sense. Not sure there is anything to do here.
