### ISSUE TITLE
Unable to edit Etherpads with latest version of PrivacyBader on Firefox

### ISSUE THREAD

**Issue by otetard** [EFForg/privacybadger#1067]
Hi,

With the latest version (2.0) of PrivacyBadger on Firefox (51b4; e10s disabled; Debian), I can’t edit Etherpad documents, connexion is reseted when typing.

How to reproduce:
- enable PrivacyBader on Firefox;
- open a random pad (for example: https://beta.etherpad.org/p/iYQsFi22Gl)
- try to edit that pad.

The only solution is to completely disable PrivacyBadger in the addons list.

Thanks for your work.

Olivier;

**Comment by ghostwords** [comment]
Fixed by #1053?

**Comment by KidPluto** [comment]
Windows 7 & PB v2016.12.8 | Firefix 50.1.0 and Chrome 54.0.2840.99

I get this error when attempting to edit, with PB enabled **or** disabled.

> Server is unreachable.
> Couldn't connect to the synchronisation server.
> This is probably due to a problem with your browser or your internet connection.

And also get an error which flashes by when that page is being loaded.  Regardless of PB.

Thanks

**Comment by cooperq** [comment]
This should be fixed by version 2016.12.15.1 please re-open if not.
