### ISSUE TITLE
Latest version breaks Google Spreadsheets

### ISSUE THREAD

**Issue by TheMeddlingMonk** [EFForg/privacybadger#1068]
The latest update to Privacy Badger in Firefox 50 has broken Google Spreadsheets. Drive and Docs still work, but I can no longer access any spreadsheets - it returns an error asking me to reload the spreadsheet every time.

Rolling back to the previous version of Privacy Badger or removing it solves the problem.

**Comment by ghostwords** [comment]
Fixed by #1053?

**Comment by cschramm** [comment]
I experience the same issue and #1053 sounds like it should fix it (as I'm seeing that `ERROR.captureStackTrace` message). It also affects some other pages, e.g. http://radio.garden/.

**Comment by cooperq** [comment]
This should be fixed by version 2016.12.15.1 please re-open if not.

**Comment by TheMeddlingMonk** [comment]
This is now reoccuring for me as well. It seems the latest update has broken this again.

PrivacyBadger: 2017.1.24.1
Firefox: 50.1.0

**Comment by ghostwords** [comment]
This should be fixed again with Privacy Badger version 2017.1.26.1, released a few minutes ago.
