### ISSUE TITLE
zazzle.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1070]
http://digitalblasphemy.com/

The image for the link to the calendar is blocked. Moving from red to yellow fixes it.

**Comment by KidPluto** [comment]
I think this is the use case:
Goto zazzle.com, search for "calendar digital blasphemy"

On Windows 7 | Firefix 50.1.0 - I see image for the calendar with PB enabled
On Windows 7 | Chrome 54.0.2840.99 - I see image for the calendar with PB enabled

Not able to recreate the issue.

**Comment by terrorist96** [comment]
![a](https://cloud.githubusercontent.com/assets/12802056/21203561/06790cd0-c221-11e6-8dac-36fe5bf0686f.PNG)

**Comment by KidPluto** [comment]
Ok, so why is the issue labeled "zazzle.com"?  What is your use case?  Thanks.

**Comment by terrorist96** [comment]
![capture](https://cloud.githubusercontent.com/assets/12802056/21203716/be1912cc-c221-11e6-8748-93fcdb38f274.PNG)

**Comment by KidPluto** [comment]
I see this image with PB enabled on both Firefox & Chrome.  Chrome doesn't list zazzle.com.  Firefox listed it, but comes up with the slider on green.

**Comment by terrorist96** [comment]
It's listed as green for you because PB hasn't noticed it to be "tracking" you yet. It defaults to red for me.

**Comment by terrorist96** [comment]
http://www.schillingshow.com/2010/11/15/ignoring-is-bliss-why-virginians-can-safely-discard-red-light-camera-tickets/

Zazzle on the right blocked.
