### ISSUE TITLE
Version 2016.12.8.1 broke Piwik graphics

### ISSUE THREAD

**Issue by Fabiensk** [EFForg/privacybadger#1071]
On Firefox 50.0.2 and 52.0a2, after having upgraded from version 1.9.2 to version Version 2016.12.8.1, the diagrams in the [MediaWiki Pageviews](https://tools.wmflabs.org/pageviews/) and [Piwik](https://piwik.org/) in the administrator pages are not displayed properly any more. Reverting back to version 1.9.2. Disabling the add-on also fix the problem. If I disabling it only for this web site, the problems are still there.

In the debugger console, I can see:
`TypeError: ERROR.captureStackTrace is not a function /  index.php:81:7`
For Mediawiki Pageviews, it does not correspond to anything useful according to the Firefox dev tools (a closing `</ul>` tag), and for Piwik it is linked to this code at the beginning of the body of the page:

    <script type="text/javascript">
        $(function () {
        $('body').css("display", "none"); // <= here
        if (self == top) {
            var theBody = document.getElementsByTagName('body')[0];
            theBody.style.display = 'block';
        } else { top.location = self.location; }
    });
    </script>

**Comment by ghostwords** [comment]
To be fixed by #1053.

**Comment by cooperq** [comment]
This should be fixed by version 2016.12.15.1 please re-open if not.

**Comment by Fabiensk** [comment]
The new version fixed this problems, thanks a lot.
