### ISSUE TITLE
The trackers documentation page still has link to the Firefox legacy git

### ISSUE THREAD

**Issue by KidPluto** [EFForg/privacybadger#1073]
https://www.eff.org/privacybadger#trackers
For the "I found a bug"

> First, please make sure the bug hasn't already been reported by checking the current bug list for Firefox or for Chrome/Opera. If the bug hasn't yet been reported you can report the bug here for Privacy Badger for Firefox or here for Privacy Badger for Chrome/Opera. ...

Since I just figured out that the firefox code base is not longer being used, I assume this needs a little rewrite.

Thanks.

**Comment by cooperq** [comment]
Thanks, fixed
