### ISSUE TITLE
[firefox] Privacy Badger appears to trigger openx client certificate dialog

### ISSUE THREAD

**Issue by ccoenen** [EFForg/privacybadger#1076]
When I open Firefox, I get this client certificate dialog, wanting me to authenticate to openx.net.

I'm raising it here, because it seems to be caused by the privacy badger extension. I deactivated all extensions and re-activated them one-by-one to find out.

I guess to get this dialog (to reproduce my issue) at all, you'd need to have client certs installed in your browser. Mine is from StartSSL, but probably any will do.

I find this highly disconcerting. An unexpected dialog to log in to a site that does not ring a bell. My first reaction was shutting down my machine and rebooting to a separate system check/virus check linux. I thought my PC got infected with some kind of ad-ware or encryption trojan or something.

![openx-client-cert-dialog](https://cloud.githubusercontent.com/assets/124909/21216217/d52ab202-c2a5-11e6-98d9-896a05a9bffc.jpg)

**Comment by ccoenen** [comment]
This is privacy badger on firefox / windows. Version 2016.12.8 updated on 14.12.2016. My second computer also shows this behaviour.

**Comment by ccoenen** [comment]
When the extension is *active* this happens on every single start of firefox (directly without further doing)

When the extension is *inactive*, go to the extensions tab, and at the very instant when you hit the "activate" button, the same dialog will pop up.

**Comment by ccoenen** [comment]
I can't seem to recreate the problem any more. But I did record a little bit of traffic before the issue stopped:

![grafik](https://cloud.githubusercontent.com/assets/124909/21216936/d6392c6a-c2a9-11e6-9e12-8463dacf3327.png)

These are TCP-SYN packets to port 443, all of those happen within two or three seconds. For some reason, my firefox tried to connect to all those domains (and more!) after activating privacy badger. Is this expected behaviour? Am I confusing this with something else?

**Comment by ccoenen** [comment]
In the second computer I just had the very same thing once again (hundreds of TCP SYNs to various high-profile domains).

**Comment by alexristich** [comment]
@ccoenen It seems the most likely explanation for this is twofold: (1) Privacy Badger checks a list of sites for DNT-compliance (https://en.wikipedia.org/wiki/Do_Not_Track) at a regular interval, verifying whether sites that claimed compliance are continuing to do so. (2) It appears that on migration from the old version of Privacy Badger for Firefox to the new one, the importing of the `snitch_map` object seems to be checking for DNT compliance for all domains present in one batch.

A patch just merged in #1082 should space out these checks, and some additional longer term solutions have been suggested in that issue as well. For now I'll go ahead and close this issue, and the fix will be in the next version of Privacy Badger released to Firefox. If there are any other issues with this please post here, and with any other issues please feel free to create a new issue.

**Comment by ccoenen** [comment]
So basically upon installing Privacy Badger, I just lit up a beacon "HEY GUYS I DON'T WANNA BE TRACKED, K THX BYE" to a few hundred companies? Isn't there a better way to do this, than having each client do the check (giving up a bit of information in the process)?

I don't know about other people, but I find this highly counter-intuitive. I can't put my finger on it, but I don't fell good about this.

**Comment by ccoenen** [comment]
Regardless of that: thank you for looking into it and taking the time to explain it. It _is_ helpful information, and I can sleep a lot better knowing that this is not a fault or virus or something on my machine.

**Comment by alexristich** [comment]
I hear your concern. What it is actually doing is checking for a specific resource in a well-defined location. Here's a document that talks about Do Not Track: https://github.com/EFForg/privacybadger/blob/master/doc/DESIGN-AND-ROADMAP.md

Basically, Privacy Badger will form and send an XMLHttpRequest (https://en.wikipedia.org/wiki/XMLHttpRequest) to each of the domains it knows of to try and locate the DNT compliance document. If it doesn't find this document, it determines the domain has opted to not abide by DNT. In the case where a domain does abide by DNT, it is given exemption status. However, it may not abide forever and as a result Privacy Badger will periodically recheck that the document remains posted at that URI.

@cooperq will correct me if I'm wrong, but the XMLHttpRequest calls made in Privacy Badger do not include calls to set the request header, meaning potentially identifying information like cookies are not included in these requests.

**Comment by ccoenen** [comment]
I consider my IP-address, browser language and user agent (including operating system and version) to be pretty identifying. I can't know for sure (all those requests are TLS), but It's the default for regular XMLHttpRequests to send those along.

**Comment by cooperq** [comment]
Correct the only thing leaking on the DNT recheck is your IP address which I guess lets someone know that this IP is using privacy badger, but it's necessary otherwise if a site posts a DNT policy (or takes one down) that change would never get reflected in privacy badger!

**Comment by ccoenen** [comment]
(openx-stuff happened again, today)

I don't understand why this compliance list isn't built centrally and part of the privacy-badger extension? Update Privacy badger every few weeks and be done with it.

Am I missing something obvious, here?

**Comment by ghostwords** [comment]
Good question! @cooperq, is checking DNT policies in each client a policy mandate like client-side tracker discovery?

**Comment by cooperq** [comment]
I don't think there is any reason it couldn't be (we should ask @pde). It would certainly solve a lot of problems.
