### ISSUE TITLE
Badger popup UI is cut off on the bottom in some locales

### ISSUE THREAD

**Issue by pvsomebody** [EFForg/privacybadger#1077]
Hi. The issue can be considered aesthetic now, since the button can still be clicked, and is now clipped only a little, and only on the domains that have a lot of trackers, but you asked to repost it if it happens after the update, so here.

![screenshot2](https://cloud.githubusercontent.com/assets/13513395/21222649/a02d3d88-c2cb-11e6-898d-25577dbfc4c7.png)

**Comment by cooperq** [comment]
Thank you for bringing this to our attention!

**Comment by airone506** [comment]
This issue does not seem to be limited to RU localization. See attached screenshot please.

Using Firefox 50.1.0 on Ubuntu. The Privacy Badger version is 2016.12.15.1.

![pb-01](https://cloud.githubusercontent.com/assets/22847930/21295505/cd69a394-c556-11e6-830a-62236728f0f8.png)

**Comment by Urides** [comment]
Hi,

It's even worse in the french version of PB. The donate text doesn't even appear when there are too much trackers listed (PB 2017.3.28 with Firefox 52.0.2 on Linux Mint).

![uipb](https://cloud.githubusercontent.com/assets/24555008/25285912/37f08a72-26bc-11e7-8ac7-d0c859a8e95e.png)

Thanks for reading.

**Comment by boxer4** [comment]
I believe I'm seeing the same thing in the en/US locale too after auto downloading the 5/9/2017 update.  The popup window size does not increase beyond the size of the three buttons normally seen for me, so the buttons and everything else beyond does not show up.  Bug #1252 has examples of what I see in en/US except the location is correct (like the ones in these other locales).  I reverted back to the 3/22/2017 as I had a backup of this version which restored proper operation.  Firefox 45.8.0/Linux.

**Comment by MTco** [comment]
En/US here.

![2017-06-05_privacy-badger_2017 5 9](https://cloud.githubusercontent.com/assets/8866895/26786607/0cb3f326-49bc-11e7-81e4-f16efffe73e6.png)

**Comment by ghostwords** [comment]
@MTco Which version of Firefox do you have?

@MTco @boxer4 Does the problem go away if you upgrade Firefox?

**Comment by boxer4** [comment]
New Firefox ESR recently available from OS packager, PB 5.9.2017 seems to work properly with Firefox 52.1. Assuming there was an api change in Firefox between the ESRs.

**Comment by ghostwords** [comment]
Yep, there are a number of Firefox WebExtensions-related bugs in the older ESR.

**Comment by MTco** [comment]
@ghostwords Firefox 47 on lubuntu x86.  Currently unable to upgrade.

**Comment by raspi** [comment]
Buttons are cut off. You can barely click "disable for this site" button edge.

Windows 10 Pro

Chrome 59.0.3071.86
Zoom: 125%
Font: Big

![hidden_buttons_bug](https://user-images.githubusercontent.com/132441/27287594-e14951e8-550c-11e7-84f7-76c508d11775.png)

**Comment by ghostwords** [comment]
Hi @raspi, as your issue is with Chrome and non-default zoom settings, you should follow #1113 instead.

**Comment by lemnis** [comment]
This should not happen anymore since #1516, it should now add a scrollbar to the popup.  Can people that had this particular issue confirm this?

**Comment by Urides** [comment]
I guess it's a way of solving the problem. It's not really aesthetic, but at least you can access all buttons. It would've probably been prettier to diminish the maximum number of tracker displayed by one (since that part already have a scrollbar) and have the three buttons in one piece.

Anyway, thank you ;-)

![image](https://user-images.githubusercontent.com/24555008/32118088-c9687d1a-bb50-11e7-82ce-0e283d454320.png)

**Comment by lemnis** [comment]
@Urides I agree, eventually #1445 will do that

**Comment by ghostwords** [comment]
This should no longer be an issue following #2479 and #2563.

**Comment by pvsomebody** [comment]
Hello, Alexei. This is indeed no longer an issue. Thank you!

вт, 19 трав. 2020 о 18:49 Alexei <notifications@github.com> пише:
