### ISSUE TITLE
[Firefox] canvas.toDataURL() no longer working

### ISSUE THREAD

**Issue by davidbehler** [EFForg/privacybadger#1079]
OS: Mac OSX 10.11.6
Firefox: 50.1.0
Privacy Badger: Latest

When the Privacy Badger plugin is active, the call to `toDataURL()` on an object representing a canvas element leads to the following error 

> TypeError: ERROR.captureStackTrace is not a function

Here is a JSFiddle to reproduce the issue: http://jsfiddle.net/xqcfoucs/
Just select an image using the right hand file input. A cropped version of the image will be displayed below the file input along with the corresponding data url and a download link to download the cropped version of the image.

At least that's how it should be. If you have activated the Privacy Badger Plugin, then the cropped image shows up but neither the data url nor the download link do.

**Comment by ghostwords** [comment]
To be fixed by #1053.

**Comment by cooperq** [comment]
This should be fixed by version 2016.12.15.1 please re-open if not.
