### ISSUE TITLE
[Chrome] Interface does not fit in pop-up when default zoom settings are bigger than 100%

### ISSUE THREAD

**Issue by JobLeonard** [EFForg/privacybadger#1081]
This is what it looks like in my browser with default 150% zoom:
![image](https://cloud.githubusercontent.com/assets/259840/21234893/d47cf956-c2f4-11e6-850b-12b798dcbc3b.png)

Note that zooming out on the page *does not resize the pop-up*, so unless I change the zoom settings I can't reach some parts of the interface.

**Comment by cooperq** [comment]
Thanks for bringing this to our attention! We will look into it!
