### ISSUE TITLE
PB is giving me problems with Google Docs

### ISSUE THREAD

**Issue by Zalexard** [EFForg/privacybadger#1087]
My Google Docs suddenly started giving me errors, during my troubleshooting I found that it was PB doing it, it's weird since there's only one slider regarding that page and it's green (fonts.googleapis.com). Also, disabling PB for that site seems to do nothing, I have to manually disable the extra to not have an error. I tried whitelisting the domain (docs.google.com) and it did nothing. Tried also reinstalling to no avail, not sure what happened since this was working well, I could edit my docs 5 days ago, not sure when it happened but I haven't been able since yesterday (at least). I'm currently using FF version 50.1.0.

PS: I couldn't send an error report either, it kept giving me errors (ironic, huh?).

**Comment by ghostwords** [comment]
Probably the issue discussed in #1053. Fix should get released soon ...

**Comment by Zalexard** [comment]
I guess I'm just glad it's not only me, since this was making me crazy. Thanks for the reply! :)

**Comment by cooperq** [comment]
This should be fixed as of version 2016.12.15.1, please re-open if it is not.
