### ISSUE TITLE
Suggestion - Show Version of Privacy Badger in dropdown

### ISSUE THREAD

**Issue by BradfordBenn** [EFForg/privacybadger#1088]
With the update to Privacy Badger 2.0 I am getting confused what machines I have updated and what ones I have not. I think a good enhancement would be to include text indicating the version or build in the text included in the drop down area. Perhaps right after the title "Privacy Badger" I have included a marked up screen shot.

This request is an enhancement in my opinion but figure having an easy way to tell what version is being used is always good, especially for troubleshooting purposes.

Thanks

Bradford

![privacybadgerversionindicator](https://cloud.githubusercontent.com/assets/24612200/21274397/056a88e8-c396-11e6-899e-db0182e18c4d.png)

**Comment by cooperq** [comment]
Thank you, we will consider this feature.
