### ISSUE TITLE
openload.co blocks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1093]
http://fmovies.se/film/life.0n95/z1z4zp

`openload.co` blocks video.

**Comment by terrorist96** [comment]
http://123movies.net/watch/dmZKbrgv-the-fate-of-the-furious/openload.html

**Comment by terrorist96** [comment]
http://www.alluc.ee/l/Win-It-All-2017-720p-WEB-DL-x264-AAC-WAVE-mp4/54ok3lvk

**Comment by terrorist96** [comment]
https://solarmoviez.ru/movie/the-kings-choice-23230/1176111-14/watching.html

**Comment by ghostwords** [comment]
Yes, I'll take a look tomorrow.
