### ISSUE TITLE
Get what looks like a paper hat for drop-down

### ISSUE THREAD

**Issue by BillHarris9** [EFForg/privacybadger#1095]
Something is preventing my drop-down.
Firefox 50.1.0 without any other addons.
Have tried re-install both.
Attached is a pic of a click on the icon response.

![img_2217](https://cloud.githubusercontent.com/assets/24637966/21295274/8a0fc5ee-c50e-11e6-9143-28fde15c3a36.JPG)

**Comment by BillHarris9** [comment]
Also other icons have drop-downs on the same tool bar.

**Comment by cooperq** [comment]
Can reproduce. May be related to #1101. For me the popup usually comes up eventually so this may be something super inefficient about drawing the popup. Should confirm if this exists on dev edition or is fixed.

**Comment by BillHarris9** [comment]
Have updated to Firefox 51.0.1 (64bit) and Privacy Badger 2017.1.26.1 and still have same issue.
Also notice that Ghostery 7.1.1.5 shows the same when clicked.

**Comment by cowlicks** [comment]
@BillHarris9 do you have javascript disabled? This could be related #1058 in that case.

**Comment by BillHarris9** [comment]
Thanks cowlicks,
Same result with javascript enabled or disabled.
Somehow though over the last few weeks the 'dropdown' has become rounded, bubble shaped although the same general size and shape.

**Comment by cooperq** [comment]
I think this is a general issue with the popup being slow to load in firefox.
