### ISSUE TITLE
Allow user to turn off WebRTC IP protection [was: WebRTC IP address hiding happens even when turned off]

### ISSUE THREAD

**Issue by interfect** [EFForg/privacybadger#1099]
It looks like Privacy Badger in Chrome is hiding my IP local IP address from WebRTC even when that setting is turned off.

Steps to test:

1. Turn on Privacy Badger in Chrome Incognito Mode.
2. Make sure the Privacy Badger "Prevent WebRTC from leaking local IP address" box is unchecked.
3. Visit https://browserleaks.com/webrtc in an incognito window
4. Notice the local IP address does not show up.
5. Turn Privacy Badger in incognito mode off again.
6. Refresh the browserleaks page.
7. Notice that the local IP address is now visible.

This effect seems to occur whether or not Privacy Badger is enabled for the given site or not. If the "Prevent WebRTC from leaking local IP address" box is checked, the browserleaks page can't even show the *public* IP address.

I think that something is badly wrong with Privacy Badger's interactions with WebRTC. I don't think it used to do this, because I used to be able to get WebRTC working between Chrome instances with Privacy Badger installed on my local network.

Potentially related to the changes that led to #1047.

**Comment by interfect** [comment]
@alexristich you seem to have written the WebRTC feature; is this the intended behavior?

**Comment by alexristich** [comment]
The WebRTC feature in Privacy Badger toggles the internal policy in Chrome which corresponds with the 4 standard modes denoted in the WebRTC specification. Here's a list of these modes:

```
Mode 1 Enumerate all addresses: WebRTC will bind to all interfaces
individually and use them all to ping STUN servers or peers.
This will converge on the best media path, and is ideal when
media performance is the highest priority, but it discloses
the most information. As such, this should only be performed
when the user has explicitly given consent for local media
access, as indicated in design idea #3 above.

Mode 2 Default route + the single associated local address: By
binding solely to the "any" address, media packets will flow
through the same route as normal HTTP traffic. In addition,
the associated private address is discovered through
getsockname, as mentioned above. This ensures that direct
connections can still be established even when local media
access is not granted, e.g. for data channel applications.

Mode 3 Default route only: This is the the same as Mode 2, except
that the associated private address is not provided, which
may cause traffic to hairpin through NAT or fall back to the
application TURN server, with resulting quality implications.

Mode 4 Force TCP and proxy: This is disables any use of UDP and
forces use of TCP to connect to the TURN server or peer. If
a proxy server is configured, the TCP traffic will be sent
through the proxy, with resulting quality implications.
```

Privacy Badger's default is Mode 3, and with protection enabled it is Mode 4. These correspond to internal settings of `default_public_interface_only` and `disable_non_proxied_udp`, respectively.

You can see the current Chrome setting by going to a background page (such as the Options page for Privacy Badger) and pasting the following in the developer console:

`chrome.privacy.network.webRTCIPHandlingPolicy.get({}, function(result) { console.log(result)})`

I understand this can be an inconvenience when using WebRTC on a local network, and my original approach was to have the default setting be Mode 2. After some discussion, we thought it would be better to up the default mode to something more private (naturally, less performant), as the assumption is that most users won't ever navigate to the Options page. We still wanted to offer a good level of privacy to the general user without requiring any action on their part.

I can recommend two solutions for your use case. The first is to disable Privacy Badger while using WebRTC locally. This is perhaps not your preferred solution, though, so another approach is this:

Privacy Badger only sets/updates the WebRTC policy in two instances: on launch and on the setting being toggled. To manually override the setting, you can open up the Options page for Privacy Badger, and type into the console the following:

`chrome.privacy.network.webRTCIPHandlingPolicy.set({value: "default_public_and_private_interfaces"})` (_for Mode 2_)

`chrome.privacy.network.webRTCIPHandlingPolicy.set({value: "default"})` (_for Mode 1_)

As long as you keep Chrome open on a given machine, this manual setting will persist.

I'll go ahead and close this issue for now, though I'd be happy to reopen it if you notice any other issues with this.

**Comment by interfect** [comment]
I don't think that tinkering with the Chrome console on every launch is a
good solution. I'm a bit biased, because I'm working on an app that expects
WebRTC on local networks to work on every browser launch for long periods.
But it's disturbing that there's no way to have the extension installed and
not have a way to tell it to not interfere with a particular feature,
especially for a trusted site.

Privacy Badger should have a toggle that turns off all WebRTC protection,
leaving it in whatever mode is the browser's default. It should also have a
way to trust particular sites with access to the lower modes: I'm willing
to reveal my local network topology to a videoconferencing app in exchange
for better VoIP performance at my office, but not to every random site I
visit on the Internet in exchange for nothing.

It's fine to have the default be mode 3, but that shouldn't be the lowest
setting possible through the UI with the extension enabled.

**Comment by alexristich** [comment]
I hear you. The option to turn it off altogether seems reasonable. On possibility would be to add a slider allowing for multiple states: "Off, Default, On" or something to that effect. @cooperq what are your thoughts on this?

Unfortunately it doesn't appear to be possible to trust only specific sites, as the WebRTC policy is a global setting in Chrome. Would be nice though!

I'm reopening this issue; let's wait to hear from Cooper.

**Comment by cooperq** [comment]
idk, the desire to turn off web rtc protection entirely seems pretty rare (@interfect excluded). That said I'm not opposed to exposing a way to turn this off entirely in the UI but it should be done very carefully so as not to introduce bad UI.

**Comment by ibc** [comment]
> Unfortunately it doesn't appear to be possible to trust only specific sites, as the WebRTC policy is a global setting in Chrome

Does it mean that Privacy Badger sets some kind of WebRTC global setting that affects any site? And is that a setting this one?:

`chrome.privacy.network.webRTCIPHandlingPolicy`

In the console of Chrome, after selecting "Privacy Badger", `chrome.privacy` is just `undefined`.

**Comment by ibc** [comment]
BTW this kind of "protection" is causing many problems to WebRTC guys (CC @danjenkins).

In fact, I was not aware about this behavior of Privacy Badger and recently opened an [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=721322) in Chromium.

**Comment by ghostwords** [comment]
Are you running this inside of Privacy Badger's background page console? Visit `chrome://extensions/`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, select the console tab.

**Comment by ibc** [comment]
Thanks. And sorry, I though it could be done by just selecting "Privacy Badger" in the main tab console.

**Comment by ghostwords** [comment]
I agree, we should replace the current checkbox setting with a select or radio control to allow users to disable this feature. Basically duplicate [Network Limiter](https://chrome.google.com/webstore/detail/webrtc-network-limiter/npeicpdbkakmehahjeeohfdhnlpdklia)'s functionality.
