### ISSUE TITLE
PB breaks duo login on FF 51 (beta) & 53 (nightly)

### ISSUE THREAD

**Issue by hwine** [EFForg/privacybadger#1102]
STR:
 1. enable PB (version 2016.12.15.1)
 2. go to https://login.mozilla.com/duo/ (will need moz account credentials - various folks here have that)
 3. observe "empty" space where duo 2fa options should appear

If you disable PB & reload, the content shows correctly.

Using Chrome 55.0.2883.95 (64-bit), with same PB version, everything works.

The chrome version shows "green" for all 4 URLs detected by PB, the FF version shows:
  red - api-4b043da5.duosecurity.com
  yellow - mozorg.cdn.mozilla.net
  yellow - support.cdn.mozilla.net

Since this isn't fixed by #1053, filing as new issue.

**Comment by ghostwords** [comment]
Seems similar to #1440.
