### ISSUE TITLE
libelektra.org screen wents black

### ISSUE THREAD

**Issue by markus2330** [EFForg/privacybadger#1103]
The website https://www.libelektra.org is completely destroyed on first load when Privacy Badger is enabled:

<img width="960" alt="destroyedpage" src="https://cloud.githubusercontent.com/assets/7949075/21404304/d26a5304-c7c0-11e6-9491-fcec920e7740.png">

Scrolling down and up is enough to fix the issue, but as I use the side very often I had to disable the plugin :cry: 

The web page is completely self-contained (no external content loaded), so Privacy Badger should actually do nothing on this page?

**Comment by markus2330** [comment]
System is Debian Jessie, firefox-esr 45.6.0, and Privacy Badger 1.9.2.

**Comment by ghostwords** [comment]
This no longer seems to be an issue with current versions of Privacy Badger and Firefox.
