### ISSUE TITLE
Privacy Badger crashes in Chromium

### ISSUE THREAD

**Issue by castor-troy** [EFForg/privacybadger#1105]
I use Ungoogled Chromium (fork on Ungoogle) Version 55.0.2883.87 (64-bit)
I downloaded privacy badger crx file and installed it manually through settings > extensions. However, it fails to load and crashes everytime within a second. I see that balloon message in chromium saying it crashed and to click on it. But it crashes again when I try to reload the extension.

Is there some log that I can submit for you to figure out and fix the issue?

**Comment by alexristich** [comment]
Thanks for the report. Took a quick look, and it appears this is due to the lack of WebRTC support in Ungoogled Chromium. There's an open issue at #1047 regarding this, and we hope to have a patch pushed after the holidays. Please keep an eye on #1047 for any updates regarding this!
