### ISSUE TITLE
Privacy Badger not working on Google Chrome

### ISSUE THREAD

**Issue by drakofrost** [EFForg/privacybadger#1106]
Privacy Badger is not blocking anything on Chrome, if I open the same site on Firefox, several domains appears as blocked, on Chrome everything is being allowed. The issue is reproducible in a clean install, without any other extensions.

OS: Ubuntu 16.04.1
Google Chrome: 55.0.2883.87
Firefox: 50.1.0

Privacy Badger on Chrome

![privacy badger - chrome](https://cloud.githubusercontent.com/assets/24446211/21434883/d0918bfe-c85d-11e6-89c5-9ae8418655b8.png)

Privacy Badger on Firefox

![privacy badger - firefox](https://cloud.githubusercontent.com/assets/24446211/21434884/d0952160-c85d-11e6-9403-dff985ce6e31.png)

**Comment by alexristich** [comment]
Each browser uses its own individual database of trackers, so it's likely that your database in Google Chrome doesn't have the context or history of your database in Firefox. Would you try exporting your user data from the Firefox instance and importing it into the Chrome instance? You can do this from the Options page (click the little gear cog in the Privacy Badger popup) from the `Manage Data` tab. Let me know if this works!

**Comment by drakofrost** [comment]
I was able to reproduce the issue on a clean install of Ubuntu, Privacy Badger works on Firefox, but does nothing on Chrome. The issue therefore, is not related to my browser history.

**Comment by alexristich** [comment]
Hmm, in that case if you export the data from the Firefox instance into the Chrome instance, does Chrome start correctly blocking certain trackers, or is it still not blocking any?

Privacy Badger by default doesn't block anything, so it's not surprising that the first time you visit a page nothing will be showing up as blocked. If you visit a series of different sites in sequence, such as `nyt.com`, `latimes.com`, `wsj.com` (news sites tend to be good candidates), you should begin to see some trackers appearing as blocked.

**Comment by drakofrost** [comment]
I clean my browsing history quite often, and I don't really use Firefox, I just have it because it's installed by default, so I gave the extension a try. But, yeah, importing the data from Firefox worked, even though the history was clean.

On a side note, Chrome says: "Not from Chrome Web Store", even though it was installed from there.

**Comment by alexristich** [comment]
Thanks for the additional information. The "Not from Chrome Web Store" notice is something that @cooperq will be looking into probably after the holiday season.

Would you try leaving the extension enabled for a couple of days while browsing and see if the list of trackers that are blocked grows any? Note that a third-party tracker will only be blocked once Privacy Badger has seen it on three separate domains (determined by the threshold that is currently set), so depending on how many unique domains you visit it can take some time to see the list grow.

**Comment by drakofrost** [comment]
I reinstalled Privacy Badger on Chrome and left it running, nothing so far. I will report back later.

**Comment by drakofrost** [comment]
I've been browsing the web for several hours, I visited a significant variety of sites, since I was researching a few things, and Privacy Badger didn't block anything.

**Comment by alexristich** [comment]
Thanks for the additional info. By chance do you have third party cookies disabled in Chrome? That's the only idea that comes to mind right now that might affect it, as you stated it persists even when other extensions are disabled.

Perhaps @cooperq or @ghostwords might have some ideas too?

**Comment by drakofrost** [comment]
It's disabled on my main computer, but on my test machine is enabled, and Privacy Badger didn't work in either cases. I also tested on Firefox, and Privacy Badger worked just fine with third-party cookies disabled.

**Comment by cooperq** [comment]
Can you open the debugging console for privacy badger (by clicking 'enable developer mode' and then 'inspect background page' in the chrome extensions page.) and tell me if you see any errors there? 
if you go to https://pbtest.org and run the tests there does privacy badger block anything? 
Are you using the version of chrome from google directly or a fork? I'm using privacy badger in chrome right now so you definitely have some sort of edge case going on.

**Comment by drakofrost** [comment]
Privacy Badger passed in all tests, but doesn't block anything in other sites.

I use Google Chrome, I have Google's repository on Ubuntu, which means that as soon as a new version is released, I receive the update. The current version is: 55.0.2883.87.

**Comment by cooperq** [comment]
hmm, very strange. In a fresh profile can you open as many different domains as possible (one good way to do this is via reddit) and see if anything starts to get blocked? I am completely unable to reproduce your issue and it sounds like privacy badger is  working correctly if the pbtest.org tests passed...

**Comment by DevbrosDevelopment** [comment]
Chrome Version 55.0.2883.87 (64-bit)
OS Ubuntu 16.04

I am having the same issue. I tried privacy badger for a few hours now and cannot get it working properly. It is blocking nothing. I disabled all other extensions and visited many sites from different domains. This is my developer console
![screenshot from 2017-01-11 18-42-19](https://cloud.githubusercontent.com/assets/15052050/21859766/40ed9cf0-d82e-11e6-8bd8-39e980d1d8b4.png)

**Comment by jeremyn** [comment]
I'm also seeing "Not from Chrome Web Store" at chrome://extensions/ for Privacy Badger , with v2017.4.19.1, Chrome 58.0.3029.81 (64-bit), Ubuntu 16.04. All the tests at https://pbtest.org show "Pass".

**Comment by ghostwords** [comment]
"Not from Chrome Web Store" is a known display issue that shouldn't cause any real problems.

**Comment by ghostwords** [comment]
I'm going to resolve this since we haven't seen any recent reports of this issue. Let me know if this is still an issue (potential conflict with HTTPS Everywhere in Chrome).

**Comment by jeremyn** [comment]
I still get this issue with PB v2017.7.24, Chrome v60.0.3112.101.

**Comment by cowlicks** [comment]
This is another issue where I think #1221 would be helpful

**Comment by ghostwords** [comment]
@cowlicks I would love if you discovered whether your proposals would indeed be helpful or not as part of resolving issues, instead speculatively claiming beforehand, which seems premature and counterproductive.

**Comment by ghostwords** [comment]
@jeremyn Just to confirm, are you talking about still experiencing "Not from Chrome Web Store" or the conflict with HTTPS Everywhere?

**Comment by jeremyn** [comment]
@ghostwords I'm seeing "Not from Chrome Web Store".

**Comment by ghostwords** [comment]
OK yeah, that's still an issue, but it's just a visual nit that shouldn't cause any real problems.

**Comment by jeremyn** [comment]
It's still a wrong thing. Is that being tracked somewhere else?

**Comment by ghostwords** [comment]
Yep, please subscribe to #1496 for updates.

**Comment by jfhorn** [comment]
SOLUTION / workaround: Per the Chromium forums, disable this flag in the browser/Chrome:
[chrome://flags/#enable-use-zoom-for-dsf
](chrome://flags/#enable-use-zoom-for-dsf)

This is a browser issue and in theory, the browser could auto-disable this flag/feature if it detected multiple monitors running at different DPIs (or is it resolutions?).  This did not break browser functionality for me.

**Comment by ghostwords** [comment]
@jfhorn I don't think this particular issue is a multi-monitor browser bug.
