### ISSUE TITLE
/skin/options.html#tab-pb-status instead of sorting as you scroll can you just provide a button for the user to sort the list and resave?

### ISSUE THREAD

**Issue by jawz101** [EFForg/privacybadger#1107]
I'm on fairly new machines and just scrolling through the list of hit sites is dog slow and I can hear my CPU fan fire up.  I'm guessing it's doing the sorting each and every time you open the page and scroll around which is kinda intense.

subdomain5.subdomain4.subdomain3.subdomain2.subdomain1.TopLevelDomain

sorting by subdomain1 > TopLevelDomain > subdomain2, 3, 4, etc. sounds like it'd be easier to do in a database or at least make it a manual operation.

... if it were me I would've gone with a little sqlite database or something so I could query, count hits, and all sorts of analytics

**Comment by alexristich** [comment]
Hi! The bottleneck here isn't actually the lookup, it's the manipulation of the DOM. I'm aiming to spend some time in January on improving this, at least marginally. 

For now, the quick workaround is to search for domains you're wanting to look at/modify; this will re-render the HTML with only the results present (limited by default to 50 domains, the rest of which will be loaded on scroll).

**Comment by jawz101** [comment]
gotcha.  Thanks mate!

**Comment by alexristich** [comment]
Happy to help!
