### ISSUE TITLE
 Possible to console.log blocked requests?

### ISSUE THREAD

**Issue by unhammer** [EFForg/privacybadger#1110]
(originally https://github.com/EFForg/privacybadgerfirefox-legacy/issues/823#event-887069784 – seems to be still relevant)

I've several times had Privacy Badger block things on pages I'm developing because I test from e.g. localhost and make server request, and each time it takes me quite a while to figure out why e.g. an xhr is giving status 0 and no error message, or a cdn script simply doesn't show up in the network requests. Is it possible to get Privacy Badger to console.log when it blocks something?

**Comment by mdaniel** [comment]
Please take this as a genuine suggestion, and not being glib: have you considered a separate FF profile for development than the one used for your day-to-day? Firefox will allow one to run with both profiles at the same time, it just creates two different instances (which can be good or bad, depending on ones perspective)

**Comment by cooperq** [comment]
we could probably add a log message under the debug flag for this.

**Comment by diffalot** [comment]
I really like this idea because inoculating web developers with a good experience when they need to address a local issue turns them into advocates of Privacy Badger over other ad/cookie blockers.

I began working on adding this to PB and quickly figured out that I'd need to add some sort of chrome message passing feature to push the log up from the background.html to the appropriate tab's console.

Is there an already existing message system from PB to the page?

Would building such a system, if it is not already in place, be beneficial, and what other function to intercept fingerprinting could that message bus be used?

**Comment by ghostwords** [comment]
If I understand this correctly, ideally we'd have something like [uBlock's request logger](https://github.com/gorhill/uBlock/wiki/The-logger). That could also be the place where Badger explains why each resource was blocked: #963. But console logging blocked requests is much lower effort and should be good enough for a while.

@unhammer @diffalot Could you talk a little about why Badger's popup as it is now isn't enough for debugging purposes?

**Comment by unhammer** [comment]
What do you mean by popup? If you mean the little icon in the browser toolbar, I get fairly "blind" about that – it's *always* showing some red number, so after a while I don't notice, and forget to look there (and it's just one of several extensions that I might have on, and might switch between). But when I'm developing on something, I'm very used to looking in console.log for failed network requests etc.

**Comment by ghostwords** [comment]
Yep, that's what I meant by Badger's popup. Good point about not realizing to look for the problem outside of the console for the page you are working on. This suggests logging to Privacy Badger's background page and/or having a dedicated logger page aren't so helpful in this scenario.

**Comment by diffalot** [comment]
@ghostwords I see this not as a request for better logging with `DEBUG=1` for PB developers, but as a request for pushing logs into the console of a tab where Privacy Badger is enabled for a domain.

Commonly, when using Privacy Badger and/or uBlock with the console open (on localhost while developing personal/client work or even on a website like cnn.com during reverse engineering), a front end web developer will see messages like "Failed to load resource: net::ERR_BLOCKED_BY_CLIENT"

It is enough that PB shows up in the toolbar and lists the blocked scripts when clicked to pull up the popup, and the developer can quickly disable PB for the site right there, but it would be nice if alongside the "Failed to load resource..." message PB could log something like "[Privacy Badger] blocked {url}" directly into the console of localhost or cnn.com to remind the developer to click on the toolbar icon and disable PB for the site under inspection.

This would also help developers who have multiple blockers installed to know which blocker they need to reconfigure when a resource is blocked.

I've taken a look through the source code, and thanks to the `fingerprinting.js` I think I see how to implement the message passing paired with a function like` window.consoleBroadcast(tab_id, message)` that could be added to `bootstrap.js` and then called from `webrequest.js` when blocking or replacing happens.

If that's a pull request that y'all would be willing to review and guide me on, I'm interested in adding it in.

**Comment by diffalot** [comment]
it turned out that implementing a working™ version of the console message passing from background to content_scripts was much simpler than the fingerprinting injection.

Here's what I'm thinking:  https://github.com/EFForg/privacybadger/compare/master...diffalot:log-blocks

I'll work this afternoon on making sure tests and linting pass, then move the discussion over to a pull request.

**Comment by ghostwords** [comment]
Thanks for explaining, makes sense to me.

I think the code flow would be something like:
1) Inject a script to perform console logging into all pages (or add code to do this into an existing injected script). Have this code listen for messages from the background page.
2) Whenever the rest of PB modifies a request, send a message to the injected script (probably asynchronously via `setTimeout(..., 0)`, to avoid blocking the browser in performance sensitive callbacks).
3) Log the received message in the injected script.

We might want to [_.debounce](http://underscorejs.org/#debounce) message sending ([for example](https://github.com/EFForg/privacybadger/blob/02d5d9d64f45b2b8bae72f621b4404ff607ee211/src/fingerprinting.js#L66-L86) to avoid spamming the communications channel when many requests are modified in rapid sequence.

Any (new) security concerns raised by this code?

**Comment by ghostwords** [comment]
I'm going to close this as "wontfix" for now. Does any other request blocking extension do anything like this?
