### ISSUE TITLE
Importing data to restore/migrate settings is slow

### ISSUE THREAD

**Issue by Calefornia** [EFForg/privacybadger#1111]
NEVERMIND! Sorry! It just took a while to load them! I was impatient. Waited about a minute, and then it worked.

------------
MacOS Sierra 10.12.1, Firefox 50.1.0

Trying to load .json preferences into a fresh install of Firefox 50.1.0, and there is an alert saying that it was successful, but it also freezes the browser, leaving the file selection box open and summoning the spinning beach ball of death.

I will screenshot this in a second.

**Comment by alexristich** [comment]
Sorry about that! It can be a little slow to load, and I noticed that while writing this feature. I haven't done any specific benchmarking, but I'm guessing it's related to the slowness in re-rendering the HTML to reflect the new state or due to the merge that is required for certain objects in order to check for collisions - not entirely sure. This is something I hope to have time to improve in the next month or so when I get a chance (though anyone else is also welcome to give it a shot!).

**Comment by ghostwords** [comment]
Yeah, this is a performance bug.

**Comment by alexristich** [comment]
@cooperq @ghostwords Maybe I should update the wording on this popup to say something like `Your imported data is now being processed. Depending on the size of your imported file, it may take a minute or two for your tracker list to fully update.` ? This might clarify the situation better, as the confirmation popup currently appears while the asynchronous calls to `storage` are being made.

**Comment by cooperq** [comment]
I would say put up a spinner or loading bar and wait for some condition to be met before dismissing the popup.

**Comment by alexristich** [comment]
That works. I was originally thinking of adding a loading spinner w/ jQuery to the page itself, though opted for the popup instead. I'll see what I can do to switch this over to something more UX friendly.

**Comment by ghostwords** [comment]
Also, when (lots of ...?) and why (DNT calls?) is it slow? Ideally wouldn't be slow reasonably ever at all, no need for extra UI then.

**Comment by ghostwords** [comment]
Making it never slow would be my preference. Otherwise, there are lots of techniques to avoid locking up the UI ... Putting up a message is good, but might still end up in an unresponsive page or even browser. Might also need to introduce delays into some overeager loop, or even use Web Workers.

**Comment by alexristich** [comment]
I haven't done any benchmarking yet, but my hunch is that it's related to the `recordPrevalence` call that is currently called for every item in `snitch_map`.

**Comment by ghostwords** [comment]
If that is it, it would be a great thing to optimize because `recordPrevalence` is called all the freaking time during normal operation!

**Comment by alexristich** [comment]
This should be fixed in #1145, which will be in the next release. If you notice any other issues here please feel free to follow up!
