### ISSUE TITLE
neimanmarcus.scene7.com breaks image

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1112]
http://www.neimanmarcus.com/David-Yurman-Spiritual-Bead-Bracelet/prod180470220_cat540734__/p.prod?icid=&searchType=EndecaDrivenCat&rte=%252Fcategory.service%253FitemId%253Dcat540734%2526pageSize%253D120%2526No%253D0%2526Ns%253Dcat540734%257C0%257C%257CTREE_SORT_VALUE2%257C1%257C%257CWEB1_SORT%257C%257CWEB2_SORT%257C%257CWEB3_SORT%257C%257CWEB4_SORT%257C%257CSELLABLE_DATE%257C1%2526refinements%253D73700044%252C73700045%252C73700046&eItemId=prod180470220&cmCat=product&childItemId=NMY2NU0_30

`neimanmarcus.scene7.com` breaks item image

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.

**Comment by ghostwords** [comment]
Now on the yellowlist: b4f91e451737dd6c2f30ea10db9c554cc2a618df
