### ISSUE TITLE
Use Firefox Sync to synchronize between browsers

### ISSUE THREAD

**Issue by jony0008** [EFForg/privacybadger#1115]
Would be great to use Firefox Sync to automatically sync Privacy Badger rules, it could be an option for users that are concern about sharing information to third parties. An other less user friendly option would be to merge rules from another browser with existing ones in your browser, if you use many computers, e.g. at home and work.

**Comment by cooperq** [comment]
You can already import and export your privacy badger settings. Import will merge the settings with any settings that already exist.

**Comment by linkp** [comment]
Export and import is not the same as an automated sync. The former requires an ongoing regimen where the latter lets the machines do the tedious work.

**Comment by cooperq** [comment]
We will consider adding support for chrome sync #645 and firefox sync.

**Comment by ghostwords** [comment]
According to https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync:
>The main use case of this API is to store preferences about your extension and allow the user to sync them to different profiles. You can store up to 100KB of data using this API. If you try to store more than this, the call will fail with an error message. The API is provided without any guarantees about uptime or performance.

Unfortunately, 100 KB is unlikely to be enough to store Privacy Badger's learning database. To check your database size, visit Badger's options page and export user data from the Manage Data tab.

**Comment by ghostwords** [comment]
Closing in favor of #2110.
