### ISSUE TITLE
allow scripts from *.perimeterx.net

### ISSUE THREAD

**Issue by safruti** [EFForg/privacybadger#1116]
PerimeterX offers a cyber security service, protecting websites from automated attacks.
Part of the solution involves a javascript that is loaded with the site's pages, that collects information to help identify if the user is a human or not. This information includes browser fingerprinting, browser attributes, and additional information that can help determine if the user is human.

PerimeterX doesn't collect or store personal information, and isn't offering the collected data to 3rd party for tracking of any kind. You can see the privacy policy here: https://www.perimeterx.com/privacy.

Websites using PerimeterX need the javascript to run. Preventing the javascript from running may cause users to be blocked on the site, as they won't pass the human challenges.

The script is typically loaded from client.perimeterx.net, and can send data to different hosts of the form *.perimeterx.net.

Best,
-Ido

**Comment by cooperq** [comment]
Thanks I will look into this but for now please consider whether you could adopt our DNT policy (https://eff.org/dnt-policy) for PerimiterX. 
If you adopt our DNT policy privacy badger will not block your scripts, but I'm not sure if that is possible for your company or not.

**Comment by safruti** [comment]
Checking up on the status of this issue.
we can't adopt the DNT policy as it is written, though we don't track users or share users data, and are using the collected information to identify malicious users only. 

Our customers and their end users are complaining that they are being blocked because of privacy badger. we will really appreciate if you can "whitelist" the domain *.perimeterx.net.

**Comment by augusto-herrmann** [comment]
From PerimeterX's privacy policy (linked above), it does not honor DNT:

> ## 6.5 “Do Not Track”
> 
> Do Not Track (“DNT”) is a privacy preference that users can set in certain web browsers. DNT is a way for users to inform websites and services that they do not want certain information about their webpage visits collected over time and across websites or online services. Please note that we do not respond to or honor DNT signals or similar mechanisms transmitted by web browsers.

Furthermore, it uses cookies, pixel tags, web beacons and other trackers to deliver interest-based advertising:

> * **Advertising or Targeting Related.** We may use first-party or Third-Party cookies and web beacons to deliver content, including ads relevant to your interests, on our Sites or on Third-Party sites. This includes using technologies to understand the usefulness to you of the advertisements and content that has been delivered to you, such as whether you have clicked on an advertisement.

As a user of Privacy Badger, I'd rather have it keep blocking the javascript from PerimeterX. If a site I'm visiting does not work without it, I simply abandon the site.

As a matter of fact, I found this issue by searching for perimeterx.net after a page I visited was not working properly. Thankfully, it was on a site where I had an account, and logging in removed the call to perimeterx.net and solved the problem. If, in the future, they start asking for PerimeterX's scripts also for logged in users, I will even cancel my paid subscription to that site.
