### ISSUE TITLE
img.washingtonpost.com blocks image

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1118]
http://www.nationalreview.com/corner/438960/study-vast-majority-gun-crime-isnt-committed-lawful-gun-owners

`img.washingtonpost.com` breaks image in article body.

**Comment by terrorist96** [comment]
https://feeds.feedburner.com/volokh/mainfeed

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.
