### ISSUE TITLE
Incorrect detection of non-existent server tracking

### ISSUE THREAD

**Issue by mpalmer** [EFForg/privacybadger#1121]
This is a follow-on to https://github.com/EFForg/privacybadgerfirefox-legacy/issues/490

We've just got another report of problems: https://twitter.com/flobin/status/816726049748910080

I cannot reproduce this issue myself: Privacy Badger considers `cdn-enterprise.discourse.org` to be quite well behaved on my system.

The CDN being blocked (`cdn-enterprise.discourse.org`) sets no cookies and does not modify local storage.  The site that reports the problems is https://discourse.mcneel.com; other sites that also use that same CDN domain include https://bbs.boingboing.net/, https://twittercommunity.com/, and https://forums.docker.com/, all of which are working fine for me.

I'd really appreciate some indication of what Privacy Badger is considering to be inappropriate about `cdn-enterprise.discourse.org`'s behaviour, so we can fix it.

**Comment by Flobin** [comment]
Hi everyone–this was indeed my screenshot. My browser is chrome 55.0.2883.95 on macOS Sierra 10.12.3. Other extensions include uBlock origin, WebRTC Leak Prevent, and HTTPS Everywhere. Here’s a cleaner screenshot that doesn’t include my email 😉 

![screenshot](https://i.imgur.com/SAInhqI.png)

**Comment by alexristich** [comment]
@Flobin In your second screenshot it looks like you have a manually overriden setting for this domain. If you click the arrow on the right to revert it, does it still revert to being blocked?

@cooperq I can't check at the moment, but I wonder if there's a way to manually run the DNT recheck in case it's out of date?

**Comment by cooperq** [comment]
There is but I want to see if @Flobin  clicks the arrow if that fixes the problem. I'm thinking it should. If not we will dig into storage and see when it is due to be rechecked.

**Comment by ghostwords** [comment]
I'm going to close this as I see Discourse's DNT policy get properly recognized:

![screenshot from 2017-04-18 16 13 16](https://cloud.githubusercontent.com/assets/794578/25151030/06766dc0-2452-11e7-891a-6ce6ff29e5e7.png)

Let me know if there is still an issue here.

**Comment by mpalmer** [comment]
@Flobin, as the original-reporter-via-proxy, is everything working OK for you now?

**Comment by Flobin** [comment]
@mpalmer Yep, looks like it works correctly now!

**Comment by mpalmer** [comment]
Yay!  Thanks for the confirmation.
