### ISSUE TITLE
Is there a way for non top-1000 sites to get on the DNT list?

### ISSUE THREAD

**Issue by dhowe** [EFForg/privacybadger#1124]

**Comment by alexristich** [comment]
Certainly; the list is "discovered" dynamically. The logic is basically such that if Privacy Badger sees a site, it will check for DNT compliance by looking for a file hosted at a defined location. A given instance of Privacy Badger doesn't have a huge list of DNT-compliant domains shipped with it.

Here's more info on DNT compliance: https://www.eff.org/dnt-policy

Hopefully this answers your question. If not please do follow up!

**Comment by cooperq** [comment]
I think @dhowe  is talking about the list that we are generating for third parties to consume. We actually scan the alexa to 1 million. But for domains not on that list they would have to notify us in some way for now. I think the ideal solution to this problem would be for privacy badger to notify us about any encountered DNT domains if the user opts-in to such reporting.

**Comment by dhowe** [comment]
Exactly, sorry for my lack of clarity above... Your suggestion sounds good, perhaps in combination with some form or email address (short-term) where over-eager domain admins (talking about myself here, for example) could get on board... 

Also would be great if there was a way for such domains to self-test (not sure exactly what this would involve, but some kind of spidering script that looks at cookies, generates a list of all 3rd parties contacted, etc.) . Might also help with adoption as sites would learn of 3rd-parties they maybe weren't aware of, then perhaps contact them to get them to comply

**Comment by cooperq** [comment]
Agreed I think an email address and a self reporting feature in privacy badger are the way to go . A self test tool is also not a bad idea. cc @pde

**Comment by dhowe** [comment]
Any progress on this? Still would love to get some of my domains on the list...

**Comment by ghostwords** [comment]
For now, the best way to get on https://www.eff.org/files/effdntlist.txt for domains not on the [Tranco list](https://tranco-list.eu/) (for example, specific subdomains or less popular domains) is to contact us at `dnt-policy` at `eff.org`.
