### ISSUE TITLE
causes conflict with AdNauseam: failed to modify the response header "set-cookie"

### ISSUE THREAD

**Issue by ericfont** [EFForg/privacybadger#1125]
I have had PrivacyBadger 2016.12.15.1 and now just installed AdNauseam 3.0.4 on Chrome Win 10 Home 1607. When I visit http://www.cnn.com/2017/01/05/us/chicago-facebook-live-beating/index.html Chrome reported extension error for PrivacyBadger:

"This extension failed to modify the response header "set-cookie" of a network request because the modification conflicted with another extension (AdNauseam)."

I reported this to AdNauseam https://github.com/dhowe/AdNauseam/issues/727 but am reposting here...since I don't know which one of you needs to be responsible for the fix....whoever is not at fault I suppose will close this issue.

**Comment by cooperq** [comment]
This is not an issue for either addon actually, just bad ui in chrome. both extensions are compatible and are working fine together despite this error.
