### ISSUE TITLE
Are there still privacy badger dev meetings?

### ISSUE THREAD

**Issue by groovecoder** [EFForg/privacybadger#1130]
I'm not sure where to find info about privacy badger dev meetings anymore. Are the meetings cancelled? Some additions to the README could help - mailing list, IRC channels, public meetings, etc.

**Comment by cooperq** [comment]
Sorry Luke! I posted something to the privacy badger list on friday are
you subscribed to that? We are now meeting on Mondays and Fridays at 11
Pacific. Same Channel.

Fixes #1130

**Comment by groovecoder** [comment]
Where is the privacy badger list? ;)

**Comment by cooperq** [comment]
https://lists.eff.org/mailman/listinfo/privacybadger

**Comment by ghostwords** [comment]
Should document all this (in the README?), as suggested.

**Comment by cooperq** [comment]
Added to readme.
