### ISSUE TITLE
breaks paypal.  report does not work

### ISSUE THREAD

**Issue by LargePrime** [EFForg/privacybadger#1132]
came to say this breaks paypal.  perhaps issue #1052 ?

tried to report, and get Oops, something went wrong.

**Comment by cooperq** [comment]
Thanks we will look into it.

**Comment by ghostwords** [comment]
Hi @LargePrime, what was broken on the PayPal site? Is Badger's issue reporting feature still broken for you?

**Comment by ghostwords** [comment]
Also, do you have NoScript (or some other addon like NoScript) installed?

**Comment by ghostwords** [comment]
Error reporting being broken is probably a duplicate of #1164.

**Comment by ghostwords** [comment]
PayPal being broken might be a duplicate of #1295 .

**Comment by ghostwords** [comment]
Is PayPal broken in a fresh profile with only Privacy Badger installed?
