### ISSUE TITLE
Allow an option to show placeholders for blocked elements if feasible

### ISSUE THREAD

**Issue by pvsomebody** [EFForg/privacybadger#1133]
It allows the web page to look more visually similar to how it was meant to by its designers before you turned up PrivacyBadger; for example, AdBlock and uBlock have an option do it and it works great.

**Comment by ghostwords** [comment]
Is this the opposite of #442?

**Comment by pvsomebody** [comment]
I would assume so! :) (Except the other but report is taking about default
behavior.)

31 бер. 2017 р. 3:41 пп "Alexei" <notifications@github.com> пише:

**Comment by cowlicks** [comment]
related to #688

**Comment by ghostwords** [comment]
Closing as a duplicate of #442.
