### ISSUE TITLE
what if we could maintain community rulesets?

### ISSUE THREAD

**Issue by jawz101** [EFForg/privacybadger#1136]
Take a look at another add-on, Karma Blocker.  It can pull in rulesets for his add-on by simply pasting in a Gitub Gist url.  If we had a curated ruleset it would be a pretty handy way to get updates for some things which are currently hardcoded.

https://addons.mozilla.org/en-US/firefox/addon/karma-blocker/

https://github.com/arantius/karma-blocker

![untitled](https://cloud.githubusercontent.com/assets/14151703/21943907/038bcd0c-d999-11e6-8cef-2acefd3ee734.png)

**Comment by cooperq** [comment]
You could do this right now with imports and exports if you have a good ruleset you would like to import. I am reluctant to canonicalize this in any other way since we have a "no blacklists" policy.
