### ISSUE TITLE
switch not reflecting choice in user filter settings

### ISSUE THREAD

**Issue by rinaldi6109** [EFForg/privacybadger#1137]
When I modify a setting for a potential tracker moving it from blocked to allowed or viceversa, and scrolling up and down, sometimes the switch icon is red and on the right or green and on the left.
See screenshot. http://imgur.com/a/uTanO

**Comment by Dropjeslover** [comment]
I have the same issue. No fix or comment yet?

**Comment by alexristich** [comment]
I started looking into this and was fairly easily able to reproduce the issue where a slider gets "reset" to its previous position when adjusting another slider, though I haven't yet been able to reproduce the issue where the colors change incorrectly. If either of you might be able to give me a set of steps to follow that seems to create this case that would be awesome.

What I might start doing here is looking at fixing the issue with the sliders being reset, and that will hopefully prevent the case where sliders can be in a position that doesn't match the color they are displaying.

**Comment by cooperq** [comment]
@alexristich is this fixed by your PR?

**Comment by alexristich** [comment]
Yup, looks to have been fixed with #1216 :)
