### ISSUE TITLE
PB causes long loading/ads to show

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1141]
`http://www.sun-sentinel.com/`

When PB is enabled, the site takes a lot longer to load and ads will be displayed.
The following rules will need to be added to your ad blocker:
```
@@||sun-sentinel.com^$generichide
@@*.ico$domain=sun-sentinel.com
@@*.gif$domain=sun-sentinel.com
@@*.png$domain=sun-sentinel.com
@@*.jpg$domain=sun-sentinel.com
```

I can't narrow it down to any specific rule. Just having PB enabled seems to be enough to cause it.
See here for details:
https://github.com/easylist/easylist/issues/242

**Comment by ghajini** [comment]
Related to #https://github.com/EFForg/privacybadger/issues/1044

**Comment by terrorist96** [comment]
Same with this:
http://www.deathandtaxesmag.com/

ABP blocks the ads. But if ABP and PB are active together, the ads will show.

**Comment by ghostwords** [comment]
Let me know if this is still an issue.
