### ISSUE TITLE
add *.philips.com to cookie blocklist

### ISSUE THREAD

**Issue by eogrul** [EFForg/privacybadger#1143]
Hi,

Is it possible to add *.philips.com to cookie blocklist? Privacy Badger is blocking the page content, images, products, forms which are coming from crsc.philips.com, images.philips.com and consumer.philips.com?

Thanks in advance!

Eren

**Comment by cooperq** [comment]
Can you give an example where these domains are being blocked?

**Comment by eogrul** [comment]
Hi Cooper, 

For example; philips.nl

You can check the attachment also.
![pb](https://cloud.githubusercontent.com/assets/7956002/22055633/6a737d6e-dd5c-11e6-9e8a-3318f9beb216.png)

Eren

**Comment by cooperq** [comment]
fixed in #1152
