### ISSUE TITLE
Unable to use Google Docs when Privacy Badger is active in Iceweasel/Firefox

### ISSUE THREAD

**Issue by austin987** [EFForg/privacybadger#1148]
I suspect this is a regression, as I usually have Privacy Badger installed, but can't guarantee I did in this browser  before.

Anyway, using Iceweasel (Firefox) 45.6.0 ESR on Debian Unstable amd64. I've noticed that if I open a Google Doc, I get an error, similar to that described here (https://productforums.google.com/forum/#!topic/docs/tQBnRham2T8)

"Unable to load file
Try to load it again or send an error report"

The same document worked in safe mode, so I tried disabling addons and re-enabling one at a time until I found it was Privacy Badger.

For reference, the doc was a very simple spreedsheet, no comments/long lines/etc. All Google Docs are affected AFAICT.

**Comment by ghostwords** [comment]
Same issue as #1087?

**Comment by cooperq** [comment]
Cutting a new release today 2017.1.24 please re-open if this release doesn't fix it. It could also be a bug in the Web Extensions support in firefox ESR.

**Comment by austin987** [comment]
@cooperq it's working now in 2017.1.26 for me, thanks
