### ISSUE TITLE
Cookies and Domains not blocked in Firefox when opening link in new tab

### ISSUE THREAD

**Issue by sgurnick** [EFForg/privacybadger#1149]
Using Firefox 50.1.0 on MacOS 10.12.2 (Privacy Badger 2016.12.15.1), when I right-click on a link and select "Open Link in New Tab" or when I simply use the middle-click feature on my mouse to open the link in a tab, Privacy Badger reports zero blocked cookies/domains. 

When I left-click on the link to open the URL in the same tab or when I right-click on the link and select "Open Link in New Window" Privacy Badger reports the expected number of cookies/domains blocked. 

Please see attached zip file that has a mp4 video for demonstration of behavior.

[privacy_badger_new_tab.zip](https://github.com/EFForg/privacybadger/files/724593/privacy_badger_new_tab.zip)

**Comment by ghostwords** [comment]
Should be fixed by #1131.
