### ISSUE TITLE
Chrome: Privacy Badger extension interfering with Instapaper extension

### ISSUE THREAD

**Issue by ghost** [EFForg/privacybadger#115]
I began noticing issues with the Instapaper extension not allowing me to save pages on specific sites after I first installed Privacy Badger yesterday. Because I also have ABP, Disconnect and HTTPS Everywhere installed I figured there might be some conflict, so I first disabled just Privacy Badger and the Instapaper extension began working. I then disabled every extension except Instapaper and Privacy Badger, and Instapaper still didn't work. Finally, I just enabled Instapaper and it worked fine. 

I am using Chrome Version 34.0.1847.131 and the following extensions:
- 1Password 4.1.1.90
- Adblock Plus 1.7.4
- Clip to DEVONthink 1.2.5
- Disconnect 5.18.5
- HTTPS Everywhere 2014.4.25
- Instapaper 1.2.2
- Pinboard Tools 1.0.0
- Privacy Badger 2014.5.1
- Reddit Enhancement Suite 4.3.2.1
- Referer Control 0.48

**Comment by hlship** [comment]
For Instapaper, I was still seeing this; the problem being that the Read Later link redirects to a new page on failure, preventing a chance to override the settings.  My solution was to use the options and explicitly add instapaper:

![privacy_badger_options](https://cloud.githubusercontent.com/assets/52660/26416797/f2b4befa-406b-11e7-9e1d-735d1cc4f31f.png)
