### ISSUE TITLE
technical info

### ISSUE THREAD

**Issue by stupidg1t** [EFForg/privacybadger#1150]
1. it would be helpful if it specified what method was used to identify each domain as tracking (image/cookie/fingerprint), though it doesn't appear to store.json that information.
2. since i block cookies, images, cross-domain iframes and scripts, is this (or any tracking blocker, e.g. ghostery) at all useful? for example, if i enable JS in Noscript for a domain which contains a tracking script (in addition to other scripts which are necessary), it seems like this won't do any good because it can only block all domain requests. similarly, it can't block specific cookies, only the entire domain (same as firefox itself)

i apologize if this is the wrong forum for this kind of discussion.

**Comment by ghostwords** [comment]
1. Good idea! Please subscribe to #963.

**Comment by ghostwords** [comment]
2. You could try using both addons together and then at some point see if Privacy Badger learned to block some trackers. If it did, you might want to keep it, and if it didn't, then your workflow probably makes it unnecessary.
