### ISSUE TITLE
googletagservices.com script surrogate breaks doodle.com

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadger#1151]
The script surrogate for googletagservices.com seems to break on doodle.com. It can be fixed by moving googletagservices.com to yellow but we should fix the surrogate instead. 

cc @ghostwords

**Comment by ghostwords** [comment]
Filed https://github.com/uBlockOrigin/uAssets/issues/277.

**Comment by cooperq** [comment]
Workaround in dc9013e7dcefabed9856860185edd1131b7fb20a
Should be reverted once this is properly fixed.

**Comment by ghostwords** [comment]
I'm not sure Google Tag Services is worth yellowlisting because of a single domain ...

**Comment by cooperq** [comment]
Looking through the broken sites list I actually expect that it breaks a
couple of other things as well.

**Comment by cowlicks** [comment]
I can no longer reproduce this on doodle.com. Closing.

**Comment by ghostwords** [comment]
This is a good candidate for removal from the yellowlist in #1593.
