### ISSUE TITLE
Under Firefox 45.7.0esr PrivacyBadger breaks the login to www.bhphotovideo.com

### ISSUE THREAD

**Issue by FixitMad** [EFForg/privacybadger#1156]
This is happening as of today. I upgraded Firefox to 45.7.0esr yesterday. Today when I tried to login to https://www.bhphotovideo.com/, I kept getting the Sorry!! Please try again soon. Chatting with Tech Support at https://www.bhphotovideo.com/, they indicated their site was working fine. I can log into this website using IE.  When I disable Privacy Badger under Firefox 45.7.0esr, I can then log into https://www.bhphotovideo.com/.
I was unable to click on anything under Privacybadger's slide bar when it was activated under https://www.bhphotovideo.com/. Please note that Privacybadger worked fine with https://www.bhphotovideo.com/ when I was using Firefox 45.6.0esr.

**Comment by fnielsen** [comment]
This may have been fixed in 2017.1.26.1 released some minutes ago. Try to update your PB to this version.

**Comment by cooperq** [comment]
^^ what he said.

**Comment by FixitMad** [comment]
Hello,

I can confirm that PB 2017.1.26.1 is now working properly with https://www.bhphotovideo.com.  Thanks for letting me know about the .1 update fix!
Thanks.
