### ISSUE TITLE
pb breaks ocrad.js library in firefox 52, disabling for site does not fix

### ISSUE THREAD

**Issue by aphid** [EFForg/privacybadger#1157]
fails in firefox 52 (linux), worked in previous versions.  Throws error: TypeError: ERROR.captureStackTrace is not a function in console on 
http://antimatter15.com/ocrad.js/demo.html and other sites that use the library.

I had to fully disable the addon for the site to work, turning it off for just that site didn't solve it.

**Comment by iGormilhit** [comment]
I encounter a similar problem (same error message) but using firefox 50.1.0. I also had to disable the addon.

**Comment by TheMeddlingMonk** [comment]
This issue has come up before (#1068) and was fixed for a short while.

**Comment by fnielsen** [comment]
This seems to originate in src/fingerprinting.js. There were some work around that file 2 days ago with 1471ba8229b63b0ef2863245c9e56fe4fbf497cc. Did that (re)introduce the problem?

**Comment by ghostwords** [comment]
This should be fixed with Privacy Badger version 2017.1.26.1, released a few minutes ago.
