### ISSUE TITLE
Restore canvas fingerprinting detection to Firefox

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1158]
This is the followup to #1053. We should make canvas fingerprinting detection cross-browser; [`src/fingerprinting.js`](https://github.com/EFForg/privacybadger/blob/f3585c3b9e0c908d90711bd3d12bd61ff2290126/src/fingerprinting.js) currently relies on some Chrome-specific APIs.

**Comment by fedde-s** [comment]
Are there short-term plans to release a bugfix update that disables the functionality on non-V8 browsers to make them usable again until the code is improved, as you seem to suggest in the closed pull request you linked? I believe it is currently making various web applications unusable while PB is running, also being mentioned in #1157 and several closed issues about previous occurrences of the same breakage.

**Comment by ghostwords** [comment]
Yes, absolutely, we should do that on Firefox ASAP. I would if I could.

**Comment by ghostwords** [comment]
Should also take care of #1268 at the same time.

**Comment by cowlicks** [comment]
In #1505 I have a cross-platform way to get the stacktrace and origin associated with some Javascript execution. This should fix this issue. ([link](https://github.com/cowlicks/privacybadgerchrome/blob/109205ac9c8ed0a79d31beb26a333d164bc5c5f4/src/js/injected/fingercounting.js#L113-L120)):

```javascript
function scriptOrigin() {
  try {
    yo = dog;  // eslint-disable-line
  } catch (e) {
    return e.stack.split('\n')[3].split('/')[2];
  }
}
```

**Comment by ghostwords** [comment]
@cowlicks I suggest reviewing OpenWPM's implementation here: https://github.com/citp/OpenWPM/blob/master/automation/Extension/firefox/data/content.js#L183

**Comment by ghostwords** [comment]
Also our original Firefox implementation here: https://github.com/EFForg/privacybadgerfirefox-legacy/blob/00d88bbf42649d31bba181b49a7886c8381682ae/data/fingerprinting.js#L101
