### ISSUE TITLE
Run regression tests on Firefox

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1159]
As pointed out by @groovecoder in https://github.com/EFForg/privacybadger/pull/1053#issuecomment-275418601.

I am not sure regression tests would have caught the issue in #1053 since we don't specifically test for canvas fingerprinting and not all sites break, just many. If this is true, let's also add a functional test for canvas fingerprinting detection.

**Comment by cooperq** [comment]
This might be a duplicate of #1009

**Comment by ghostwords** [comment]
Yep.
