### ISSUE TITLE
2017.1.24.1 breaks some/many PDFs

### ISSUE THREAD

**Issue by hungerburg** [EFForg/privacybadger#1161]
Since the recent update some/many PDFs do not render correctly or not at all with the firefox built in pdfjs.
For a sample see - https://xmlgraphics.apache.org/fop/fo/fonts.fo.pdf
Disable PB and they show neatly!

**Comment by ghostwords** [comment]
This should be fixed with Privacy Badger version 2017.1.26.1, released a few minutes ago.

**Comment by hungerburg** [comment]
Indeed - it is fixed

Thank You very much, I like the Badger!
