### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by darsie** [EFForg/privacybadger#1163]
Disable Privacy Badger for This Site?
Did Privacy Badger break this site? Let us know!
Donate to EFF

The button text is gray (black when mouse over) and clicking does nothing.

**Comment by HansHauge** [comment]
Is this happening on all pages, or one particular page?

**Comment by darsie** [comment]
On 02/06/2017 12:53 AM, Hans Hauge wrote:
> Is this happening on all pages, or one particular page?

It broke https://bitcoinity.org/markets/bitstamp/USD . The graphs were
missing. I tried again, now, and it works with the page and others, both
the graph and the buttons.



-- 
Encrypt emails.
GPG: https://sks-keyservers.net/pks/lookup?op=get&search=0xF732FBF3E4219D48

**Comment by HansHauge** [comment]
I'm seeing the Chrome privacy error on that page. That might be the cause.

<img width="795" alt="screen shot 2017-02-05 at 4 09 54 pm" src="https://cloud.githubusercontent.com/assets/3742367/22631252/ad62833a-ebbd-11e6-83ad-99f5b33d6fe1.png">

I tried going to that page in incognito mode with no extensions and the page looks like this:

<img width="1440" alt="screen shot 2017-02-05 at 4 12 21 pm" src="https://cloud.githubusercontent.com/assets/3742367/22631263/f778ec16-ebbd-11e6-9d4d-09ea73aadfc3.png">

My guess would be the site is having some issues.

**Comment by darsie** [comment]
On 02/06/2017 01:13 AM, Hans Hauge wrote:
> My guess would be the site is having some issues.

Works for me on iceweasel (debian's firefox). See attached screenshot.



-- 
Encrypt emails.
GPG: https://sks-keyservers.net/pks/lookup?op=get&search=0xF732FBF3E4219D48

**Comment by darsie** [comment]
![Uploading 2017-02-06-012247_1191x789_scrot.png…]()

**Comment by darsie** [comment]
https://imgur.com/ePBparc

**Comment by HansHauge** [comment]
Ok, thanks for the info. I was using OSX.

**Comment by ghostwords** [comment]
Hi, are the buttons still broken with the latest version of Privacy Badger (2017.3.28)? If so, could you report your browser version and what other extensions/addons you have installed?

**Comment by darsie** [comment]
'Disable Privacy Badger for This Site?' and 'Did Privacy Badger break this site? Let us know!' work. 'Donate to EFF' opens a new tab that closes before I can look at it. Maybe adblock+ closes it.

I have PB 2017.3.28
