### ISSUE TITLE
Privacy Badger is breaking a lot of sites all of a sudden

### ISSUE THREAD

**Issue by keybounce** [EFForg/privacybadger#1165]
I'm not sure why, but in the last few days a large number of sites that I have repeatedly gone to are being broken by P.B.

Examples of such "breakage": The curse CDN network used by a large number of gaming sites (minecraft related in my case). Youtube itself (including a number of the actual download domains). Google.com and accounts.google.com (which breaks trying to log into some google sites). video.google.com, googlevideo.com, and a bunch of *.googlevideo.com sites.

**Comment by ghostwords** [comment]
Hello, are you using Firefox? Updating to the latest Privacy Badger version, 2017.1.26.1, should be fix this issue. Let us know if it does not.
