### ISSUE TITLE
Sliders resetting or unable to slide/select

### ISSUE THREAD

**Issue by Dropjeslover** [EFForg/privacybadger#1167]
Hi,

I've downloaded the latest version and basically want to block everything. Unfortunately, there isn't a "block all" or selection by category option like in Ghostery (feature request!).

Anyway, I've visited several websites and now have 400+ trackers in the list. I want to block nearly all of them. 
The sliders for the domain dnxs.com and adscale.de refuse to slide to block domain/cookies. Some sub-domains remained their position, others are impossible to set: 
![image](https://cloud.githubusercontent.com/assets/25400008/22395378/e0576d96-e53c-11e6-91ea-2366c9db65bc.png)

Other sliders downright reset themselves, resulting in:
![image](https://cloud.githubusercontent.com/assets/25400008/22395383/327df0e0-e53d-11e6-8477-84e9e6827782.png)
![image](https://cloud.githubusercontent.com/assets/25400008/22395398/90e39784-e53d-11e6-9e7d-e9524181d8d7.png)

After reloading the options page:
![image](https://cloud.githubusercontent.com/assets/25400008/22395391/61530c66-e53d-11e6-8451-f0db68db59c0.png).
I want this advertising crap blocked.

I just switched from Ghostery to PrivacyBadger as Ghostery is often paid to not block things, but I'm very not happy with these things...

**Comment by ghostwords** [comment]
Same issue as #1137?

**Comment by Dropjeslover** [comment]
Yes, indeed. Hmm, I checked if there was a topic about this and must have overlooked that topic.
