### ISSUE TITLE
dictionary.com issues: static.sfdict.com blocks images, connect.facebook.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1171]
http://www.dictionary.com/browse/eudicot

`static.sfdict.com` blocks images. Yellowlist.
`connect.facebook.com` blocks Word of the Day, and the button at the top right of the definition to collapse/expand the definition.

**Comment by terrorist96** [comment]
http://www.thesaurus.com/error

**Comment by terrorist96** [comment]
http://www.thesaurus.com/browse/music
Breaks EXPAND link, highlighting, images, etc.

**Comment by terrorist96** [comment]
`static.sfdict.com` now breaks the entire layout of the homepage http://www.dictionary.com/

**Comment by ghostwords** [comment]
Seems like we should add `['sfdict.com', 'dictionary.com', 'thesaurus.com']` to [multi-domain first-parties](https://github.com/EFForg/privacybadger/issues/781).

**Comment by ghostwords** [comment]
`connect.facebook.com` should get a surrogate script; previously: #731.

**Comment by terrorist96** [comment]
Separate issue for connect.facebook.com issue: #862
