### ISSUE TITLE
PB is blocking auth0-lock

### ISSUE THREAD

**Issue by luisrudge** [EFForg/privacybadger#1175]
Hi. I'm Luis from auth0. Privacy Badger is blocking our CDN and we had a couple of users that brought that to our attention (https://github.com/auth0/lock/issues/362). How can we work together to fix this issue?

Thanks!

**Comment by mackenziejgoodwin** [comment]
+1 we are having the same issue

**Comment by ghostwords** [comment]
Hi @luisrudge, would Auth0 be able to adopt the [EFF Do Not Track policy](https://www.eff.org/dnt-policy)? If your company can and will abide by the policy's requirements, posting the policy on your domains will tell Privacy Badger to allow loading of resources from those domains. Let me know if you have any questions.

**Comment by luisrudge** [comment]
@ghostwords Thanks for the heads up. We'll add it to our backlog.

**Comment by LeeAtZoetik** [comment]
Same issue for me - *.auth0.com is very important for what we access

**Comment by excenter** [comment]
This is marked as closed, but I just spent a fun couple hours trying to figure out what was trapping me in a login loop, and the answer was that my-tenant.auth0.com was blocked by privacy badger. 
I'd love to get more people using PB, but I can't recommend it to any of my coworkers or application users without a mini-seminar on how to un-break our app.

**Comment by ghostwords** [comment]
@bcyphers Yellowlist PRs don't require a new release.

**Comment by ArturKlajnerok** [comment]
Thanks for resolving this @bcyphers & @ghostwords 🙇. Do you know when the yellowlist update is scheduled ?

**Comment by excenter** [comment]
Thanks all, excited to see progress!

**Comment by bcyphers** [comment]
This should be fixed now: https://www.eff.org/files/cookieblocklist.txt (ctrl-F "auth0")
