### ISSUE TITLE
One of the testing URL's is 404'ing.

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1176]
[This](https://github.com/EFForg/privacybadger/blob/master/tests/selenium/super_cookie_test.py#L36) selenium test uses [this](https://rawgit.com/gunesacar/gunesacar/6f0c39fb728a218ccd91215bfefbd4e0/raw/f438eb4e5ce10dc8623a8834b1298fd4a846c6fa/low_entropy_localstorage_from_third_party_script.html) to test. But it is returning a 404.

**Comment by cowlicks** [comment]
Is there a copy of the js source somewhere?

**Comment by alexristich** [comment]
I tried switching the domain and address pattern to that of the other tests and it seems to have worked :) Here's a link:
`https://gistcdn.githack.com/gunesacar/6f0c39fb728a218ccd91215bfefbd4e0/raw/f438eb4e5ce10dc8623a8834b1298fd4a846c6fa/low_entropy_localstorage_from_third_party_script.html`

**Comment by cowlicks** [comment]
Thanks @alexristich !!! I'll give this a shot tonight.
