### ISSUE TITLE
Google Custom Search blocked at stacksnippet.com

### ISSUE THREAD

**Issue by tripkin** [EFForg/privacybadger#1177]
I visited http://stacksnippet.com for the first time on Jan 31, and after testing found that PB was blocking the Google Custom Search and all search results selected by hyperlink as the search bar was not visible...
Disabling PB for this site let the site function normally. PB showed the site as not having any cookies. 

Additionally,  when I tried to submit this problem using PB's built in error reporting tool I could only get a message saying "Oops, something went wrong." when I hit the submit button.

**Comment by ghostwords** [comment]
Is this using Firefox with NoScript (or something like NoScript) by any chance?

**Comment by tripkin** [comment]
Yes, as a matter of fact I am using NoScript, as chance would have it. However I had allowed everything but google-analytics, as well.

**Comment by ghostwords** [comment]
Not being able to report problems because of NoScript is being tracked in #1164.

**Comment by ghostwords** [comment]
The NoScript issue should be fixed as of Firefox 54.

**Comment by ghostwords** [comment]
Google Custom Search (`cse.google.com`) should be on Privacy Badger's yellowlist ... I am unable to reproduce; here is what I see on `stacksnippet.com`:

![screenshot from 2017-06-21 15 32 40](https://user-images.githubusercontent.com/794578/27403028-e8f7c006-5696-11e7-8039-548d7f33e4f9.png)

**Comment by tripkin** [comment]
Thanks! It is working now on my system (Firefox 54 on Debian (Stretch) 9
