### ISSUE TITLE
en.wikipedia.org breaks page

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1178]
https://tools.wmflabs.org/pageviews/?project=en.wikipedia.org&platform=all-access&agent=user&range=latest-20&pages=

`en.wikipedia.org` breaks page.

**Comment by terrorist96** [comment]
https://tools.wmflabs.org/geohack/geohack.php?pagename=Panmunjom&params=37.956_N_126.677_E_

Breaks map on right. Says "JavaScript Disabled" (but it isn't)

**Comment by terrorist96** [comment]
https://www.wikiwand.com/en/Enzo_Ferrari_(automobile)

Can't click on images to enlarge.

**Comment by terrorist96** [comment]
#910 ?

**Comment by cowlicks** [comment]
Yep, tools.wfmlabs.org or wfmlabs.org should be added to the mdfp list
