### ISSUE TITLE
*.libsyn.com breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1180]
http://www.washingtonexaminer.com/pro-gun-groups-praise-gorsuch-pick-trump-has-kept-his-word/article/2613646

`*.libsyn.com` should be moved to the yellowlist; breaks video at the bottom.

**Comment by HansHauge** [comment]
Hmm, I'm not able to replicate the broken video on that page. Could this have something to do with browsing history? For example, perhaps the pages I've visited have not caused this to be flagged by my extension, but the pages you have browsed has caused it to be blocked for your extension?

**Comment by terrorist96** [comment]
Exactly.

**Comment by ghostwords** [comment]
Another `libsyn.com` issue: #1319.

**Comment by terrorist96** [comment]
http://tomwoods.com/ep-440-liberland-a-new-libertarian-country/

`traffic.libsyn.com` and `secure-hwcdn.libsyn.com` need to be moved from red to yellow; blocks podcast.

**Comment by terrorist96** [comment]
@ghostwords what can be done to speed-up fixing broken site issues?

**Comment by ghostwords** [comment]
Good question. Hmm. Posting the desired debugging information, for now as per https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b.

Sorry if it seems like we're not spending enough time on broken site issues. I think we're doing OK though, given our limited resources. For example, we've roughly halved the error report submission rate in the past six months.

**Comment by terrorist96** [comment]
![image](https://user-images.githubusercontent.com/12802056/29888056-7e930ab2-8d8d-11e7-8520-92e6e39883e0.png)

**Comment by ghostwords** [comment]
If you're interested, you could also pitch in by diagnosing what the situation is for certain high profile site breakages, for example, YouTube (#1555). How to you reproduce the issue? Is it browser dependent? Does it happen with Privacy Badger alone? Is it caused by blocking a certain set of domains?

**Comment by ghostwords** [comment]
Sorry I haven't gotten back to you on some issues and pull requests yet. I will, I'm just splitting my time working on other parts of Privacy Badger.

**Comment by terrorist96** [comment]
No problem. You guys really should have at least one person devoted to just fixing issues only and not coding the backend, though I can see it can be hard to separate the two. My thing is that the more PB breaks sites, and the longer it takes for those to be fixed, the more people will get fed up and uninstall PB because it's more hassle than it is help. That's why I (personally) think fixing broken site issues should always be priority 1, in order to retain and expand your user base. I've had people tell me in the past to uninstall PB cuz of too many false positives, for example. And I like to recommend PB to my friends, but many times they'll end up installing it due to issues and impatience to troubleshoot. This is why I'm motivated to report issues here, because I believe in the EFF's mission statement.

**Comment by ldexterldesign** [comment]
Hey all,

Hope you're well

Thanks for software

+1 for libsyn

https://player.fm/series/the-jimmy-dore-show - unable to play podcast episodes

<img width="1440" alt="screen shot 2018-03-31 at 11 56 01" src="https://user-images.githubusercontent.com/1715809/38162096-a6d37318-34db-11e8-9498-131a5fb7bdd7.png">
![Uploading Screen Shot 2018-03-31 at 11.56.28.png…]()

I just discovered https://github.com/EFForg/privacybadger/blob/master/CONTRIBUTING.md > https://github.com/EFForg/privacybadger/blob/master/doc/fixing-broken-sites.md so will review when I have time

In the meantime, and for future reference, if someone fixes this I would love to know how you did it and what libsyn are doing wrong?

Let me know if you have any issues - happy to help

Hope this is clear/useful and to hear back

Thanks (in advance)

**Comment by ldexterldesign** [comment]
audio.wnyc.org

<img width="1440" alt="screen shot 2018-04-01 at 13 47 48" src="https://user-images.githubusercontent.com/1715809/38172818-477deff0-35b3-11e8-9fa5-fdebd93c696b.png">

**Comment by ghostwords** [comment]
Hi @ldexterldesign! Could you open a new issue for each separate broken site problem? Here, this issue is about `libsyn.com` breaking different sites when blocked. PlayerFM being broken by blocking `audio.wnyc.org` seems like a separate problem.

**Comment by terrorist96** [comment]
@ghostwords can you provide an update? This issue is over a year old.

**Comment by ldexterldesign** [comment]
NO REPLY NECESSARY

Hey @ghostwords,

Thanks for reply

Sure, would have created a new issue but just testing the water first

I see you already created an issue since[0] so I dropped a little something there

Let me know if you have any issues - happy to help

Hope this is useful

Keep up the great work!

Cheers

[0] https://github.com/EFForg/privacybadger/issues/1946#issuecomment-379485397
