### ISSUE TITLE
Dates in nextUpdateTime are incorrect

### ISSUE THREAD

**Issue by alexristich** [EFForg/privacybadger#1181]
Looks like the dates aren't accurate, which is likely preventing the DNT policy from being rechecked for users and allowing traffic through to newly compliant domains.

**Comment by ghostwords** [comment]
`[2296, 2297, 2298, 2299]` is my set of years, returned by the following code run in Privacy Badger's background page context:

```javascript
chrome.storage.local.get(r => console.log(_.sortBy(_.unique(_.map(
  Object.keys(r.action_map), i => {
    return new Date(r.action_map[i].nextUpdateTime).getFullYear();
  }
)))));
```

**Comment by alexristich** [comment]
Lol, here's a hunch:
`badger.storage.touchDNTRecheckTime("doubleclick.net", utils.oneDayFromNow() * 7);`

AKA "Give me the time since epoch for this time tomorrow... then multiply that time by seven."

**Comment by cooperq** [comment]
:disappointed: yup, that is definitely the issue. okay well the fix is easy. I will submit a patch.

**Comment by ghostwords** [comment]
Yep, dividing existing `nextUpdateTime` values by 7 gets me, if I understand this situation correctly, the very first and only time we checked DNT policy for a domain.
