### ISSUE TITLE
Fix super_cookie_test.py.SuperCookieTests.test_should_detect_ls_of_third_party_frame

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1184]
[This test](https://github.com/EFForg/privacybadger/blob/master/tests/selenium/super_cookie_test.py#L20) fails intermittently as noted by the docstring. The docstring suggests that the cookie is being set before the pb content script runs. To test this I was tried adding a sleep to the javascript that sets the cookie. My replacement test is [here]( https://rawgit.com/cowlicks/e04533cacf5717cd2cae51e0452032c0/raw/548c8ba38a7c9c67bcb267c0c83a7eccd7b849bf/frame_ls.html). And the gists are [here](https://gist.github.com/cowlicks/e04533cacf5717cd2cae51e0452032c0) and [here](https://gist.github.com/cowlicks/7c6009a982ef3e8cf582b75e5bffb275). This wasn't working when I sidetracked it, but I don't remember why.

**Comment by cooperq** [comment]
This is fixed by your PR isn't it?

**Comment by cowlicks** [comment]
@cooperq no
