### ISSUE TITLE
Fix pbtest.org test: "Does privacy badger honor the Cookie Block List"

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1185]
This test fail intermittently.

**Comment by cooperq** [comment]
And often on firefox as well!

**Comment by ghostwords** [comment]
Currently [commented out on Firefox](https://github.com/EFForg/privacybadger/blob/02d5d9d64f45b2b8bae72f621b4404ff607ee211/tests/selenium/pbtest_org_test.py#L61) (https://github.com/EFForg/privacybadger/commit/3654568e2454f1ba2096dd40f2a97634af2c7b22?w=1), let's restore.

**Comment by ghostwords** [comment]
Blocked by #1829.
