### ISSUE TITLE
per site allow cookie

### ISSUE THREAD

**Issue by deepdad** [EFForg/privacybadger#1190]
Some sites require for example captchas and storage of the related cookie. Therefore a feature is to allow sites to store information and remove it when the session ends. This is how NoScript does it too.

**Comment by ghostwords** [comment]
Could you provide an example or two of this sort of problem? Page URL, what's broken, what needs to be allowed to load.

**Comment by deepdad** [comment]
Yesterday I used the export function, then gave all sites in the PB filter the blocking value. Internet didn't break, but, it does make a few sites dysfunction.

Currently you block a domain or you don't. It would be better if a domain can be blocked, except when visiting a certain website. So globally all G's domains would be blocked, except when I visit Youtube or Gmail.

(NoScript should do the same)

Thing is, trackers are behind many domains (e.g. googlesyndication is behind 50% of websites I visit). So I can't say (for example), oh googlesyndication is allright because I need when visiting Youtube. Because then it tracks everywhere. You understand? Site specific allow.

**Comment by ghostwords** [comment]
Privacy Badger keeps a [list of lists of domains that should be treated as first parties](https://github.com/EFForg/privacybadger/blob/master/src/multiDomainFirstParties.js) when encountered on any other domain within the same sub list. Does manually blocking domains override that list? If it does, we might want to change how that works.

Does this describe the issues you are running into? It would be helpful to have a specific example or two. What's broken where and by what.

**Comment by deepdad** [comment]
I don't know what you mean or how that works. 
AFAIK a cookie is set when a domain is allowed somewhere. Closing that tab doesn't delete it. When I reopen the same domain, the cookie is still there. So how does that prevent a new tab on a different domain from reading that cookie?

**Comment by ghostwords** [comment]
Privacy Badger has a number of approaches to fix site breakage. In my last comment, I was describing one such approach that could do things like allow GoogleSyndication across all Google properties.

I am trying to understand exactly what kind of issue you are running into, which is why I keep asking for specific examples. I hear that you would like to see a temporary unblock feature, but I am not sure it makes sense, given Privacy Badger's hands-off, no-configuration necessary goal. But I need more information.

**Comment by deepdad** [comment]
Sites are not broken. That's not what this is. This is a feature request.
You say, it is possible to "allow GoogleSyndication across all Google properties." I didn't know that. AFAIK, you cannot do that. The cookie remains in the browser until you clear it. And, you cannot set  "allow GoogleSyndication across all Google properties " and block GoogleSyndication across all non- Google properties at the same time. There are only sliders that allow or block, globally.

**Comment by ghostwords** [comment]
Yes, not possible through Privacy Badger UI, it's something we would do for all PB users via the [list I described earlier](https://github.com/EFForg/privacybadger/issues/1190#issuecomment-278784320).

If sites aren't broken, then what would per-site unblocking do for you?

**Comment by deepdad** [comment]
Some sites are broken without cookie. You then have to allow it in PB. Then the cookie is set. 

You asked for examples of sites that are broken, but that is irrelevant since it is a feature request. Not a bug.

**Comment by ghostwords** [comment]
Every feature comes with development, complexity and maintenance costs, so we shouldn't add features unless they are clearly worthwhile. I'm going to close this ticket, but feel free to provide more information to support your case.
