### ISSUE TITLE
advertisercommunity.com cannot move slider to "block"

### ISSUE THREAD

**Issue by catwirk** [EFForg/privacybadger#1192]
a few of my sliders will not move but this is the first one on the list.

**Comment by ghostwords** [comment]
Which browser do you use? What other addons or extensions do you have installed in your browser? Are the sliders stuck on all pages or only certain ones?

**Comment by catwirk** [comment]
I'm using Chrome 55. some of the sliders move just fine. I don't even remember what page I was on.  I'll take better notes next time.

**Comment by ghostwords** [comment]
Sounds good, I'll close this for now.
