### ISSUE TITLE
Slider UI slightly broken on Options page

### ISSUE THREAD

**Issue by alexristich** [EFForg/privacybadger#1197]
The slider that is present on the Options page doesn't directly reflect the underlying slider. This is viewable by changing `opacity` in the `ui-slider` CSS class from `popup.css` to 100:

![2017-02-10_1403](https://cloud.githubusercontent.com/assets/11308076/22845943/feef3ec0-ef99-11e6-99d7-6af797f2f5f4.png)

@ghostwords and I looked into this and found that this was broken in commit 4124c866b3f2d6959114b61ee18654e6934752bf. Still, it wasn't obvious what broke this and what exactly was changed in this commit.

I'll continue looking into this to see if I can track down exactly why this stopped working.

**Comment by ghostwords** [comment]
This misalignment causes the revert button to be partially obscured and thus hard to activate in the allow (green) state.

The popup is not affected.

**Comment by alexristich** [comment]
Undid a change from a while back to fix this. @ghostwords you can take a look into this if you like so we can better understand what's going on.

**Comment by ghostwords** [comment]
Aaah. It was a search-and-replace gone wrong, [here](https://github.com/EFForg/privacybadger/commit/4124c866b3f2d6959114b61ee18654e6934752bf?w=1#diff-763aa8deb604d725a74f8304903c1422L429) I think. The `create` callback needs `this`, not `element`.

**Comment by ghostwords** [comment]
The `this` inside the callbacks isn't the same `this` that's used in a couple of places in the outer function (what used to be `registerToggleHandlers`). Let me know if this makes sense or not.

**Comment by alexristich** [comment]
Super interesting! Yeah, that totally makes sense. Would not at all have questioned the scoping of `this` in this case. Good find 👍

**Comment by ghostwords** [comment]
Also, does your commit fix [this code](https://github.com/EFForg/privacybadger/commit/490cc5ae80fe89dae2347ae43caec5313d350520#diff-91ba5f4df12e1b6b0629662164b3f14eR321)? Wasn't `element` null at the time the `stop` callback was called?

**Comment by alexristich** [comment]
Good question; that fix was from before my time so I wasn't familiar with it. Even with that fix though, hasn't this issue persisted until recently as per #1137? 

I just checked and #1137 was fixed with this reversion, though I haven't yet reverted the fix in 490cc5ae80fe89dae2347ae43caec5313d350520 to see whether that code can be removed too. I'd be happy to give it a look if you like.
