### ISSUE TITLE
Privacy Badger 27.1.2016 does not allow to see the updated websites.

### ISSUE THREAD

**Issue by Nova6K0** [EFForg/privacybadger#1201]
Mozilla Firefox (Bugzilla report):

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0
Build ID: 20170212030213

Steps to reproduce:

Open any website (no matter how or from where).

Actual results:

The website is not updated until Privacy Badger is deactivated or Ctrl + F5 is pressed to bypass the cache (refresh).

Expected results:

The website should be updated without having to do anything else. Indicating that the add-in would work correctly

**Comment by ghostwords** [comment]
This sounds like #1101 ... Update to the latest Privacy Badger version to resolve.

**Comment by Nova6K0** [comment]
Thanks... And where is the link? Because Firefox tells me that the latest version is the 2017.1.26

Greetings.

**Comment by ghostwords** [comment]
Here you go: https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/

**Comment by ghostwords** [comment]
Oh, are you already using the latest version? My mistake, reopening.

**Comment by ghostwords** [comment]
Let me know if you still have the issue with the latest version.

**Comment by Nova6K0** [comment]
No ghostwords, thank you. The problem is that Firefox (Nightly 54.0a1 x64) where I had installed the 2017.1.26 version did not inform me of the new 2017.1.26.1. Sorry for the confusion. In any case any problem I will report. Since you do this great complement is the least I can do.

In principle the new version works correctly. ;-)

Greetings.

**Comment by Nova6K0** [comment]
No, the new version 2017.1.26.1 still fails :-(

**Comment by cooperq** [comment]
@ghostwords

**Comment by djmaze** [comment]
Since updating to Firefox 52, the browser crashes with SIGSEGV when loading certain pages. It does not happen when Privacy Badger is disabled.

Judging from a gdb output I got, this might be connected to the error mentioned by @Nova6K0. Note however I do not get this output on every crash:

```
[Thread 0x7fffc39cb700 (LWP 16115) exited]
Extension error: TypeError: badger.tabData[tabId] is undefined moz-extension://363e8b8a-2a94-4d71-96a4-60467b3b2bee/src/background.js 539
[[Exception stack
Badger.prototype.updateCount/<@moz-extension://363e8b8a-2a94-4d71-96a4-60467b3b2bee/src/background.js:539:11
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:73:129
runSafeSync@resource://gre/modules/ExtensionUtils.jsm:104:37
runSafe@resource://gre/modules/ExtensionCommon.jsm:123:32
wrapPromise/<@resource://gre/modules/ExtensionCommon.jsm:310:31

[...]

[New Thread 0x7fffc39cb700 (LWP 16437)]
[New Thread 0x7fff91eff700 (LWP 16438)]
[Thread 0x7fffbbdff700 (LWP 16144) exited]

Thread 1 "firefox" received signal SIGSEGV, Segmentation fault.
```

**Comment by ghostwords** [comment]
Hi @djmaze, your problem seems different (browser crash vs. needing to reload the page for Badger to see anything). Could you open a new issue please?

**Comment by ghostwords** [comment]
@djmaze `badger.tabData[tabId] is undefined` may or may not be the related; it certainly doesn't seem like Firefox should crash because of a JS error (or in fact anything a WebExtensions addon might do). In your issue, could you let us know how to reproduce the crash?

**Comment by Nova6K0** [comment]
It really can be the same issue.

I have discovered that trying to update the browser version can not and will fail (crash) if Privacy Badger is enabled. It is to deactivate it and everything returns to normal.

Greetings.

**Comment by ghostwords** [comment]
Could you let us know if this is still an issue with Privacy Badger version 2017.4.19.1?

**Comment by djmaze** [comment]
For me the problem disappeared when I reactivated Privacy Badger a few days later. Can't reproduce the crash anymore.

**Comment by ghostwords** [comment]
Is this still an issue using the latest stable Firefox release (55)?

**Comment by Nova6K0** [comment]
Hi ghostwords. The issue has disappeared, at least in the development version I'm testing Firefox (Nightly 57.0a1)

Greetings and thanks for your great work.

**Comment by ghostwords** [comment]
Ah, excellent news. Thanks for bearing with us!
