### ISSUE TITLE
Privacy Badger not blocking any potential trackers past 24 hours of browsing. Icon has remained with a 0 inside a green box for the entirety of its time.

### ISSUE THREAD

**Issue by 45Hedron** [EFForg/privacybadger#1202]
Hi there, I'm new to the community.

The settings are telling me there's about 299 potential tracking domains so far. None of them have been set out of the green area automatically. Throughout the entire time, iv'e been cleaning my cookies and browsing data thoroughly. Is PB responsible for automatically blocking these domains, or do I have to go through the list of all 299 domains and slide them manually? Because if so, that's... not very convenient, but at least a good way to burn calories.

Jokes aside, here is some information about my PC:

>Browser: Google Chrome, version 56.0.2924.87 - 64 bit
>OS: Windows 10 Home version 1607 - 64 bit
>Internet connection type: Ethernet

Thanks in advance if there's a quick and easy solution to this, i'm not very tech-savvy.

**Comment by cowlicks** [comment]
Welcome! And thank you for your bug report.

Your intuition is correct, you should not need to manually adjust the slider on each domain. But it is strange that Privacy Badger has not done this automatically and decided any of those potential tracking domains are actually tracking you.

I don't think cleaning cookies should effect, but it could be having some effect. If you are also cleaning "hosted app data" it could be a problem. What version of privacy badger do you have? This is in settings > extensions > privacy badger.

**Comment by 45Hedron** [comment]
Hi Cowlicks, thanks for your response.

The version in the extensions list seems to be 2017.1.26
If this is an out-dated version, is there a way I can update it? And also, is there a way to have it update itself automatically?

Just to make sure this isn't any of my several extensions affecting PB, here are a list of extentions I currently have other than PB:

>Adblock Plus version 1.12.4
>Tampermonkey version 4.2.7 (to activate Anti-Adblock Killer)
>And an extension that tells me ahead of time if a website has any malicious threats/scams, so far it has never misjudged any trusted websites yet. Unfortunately for security reasons I prefer not to state my antivirus software.

Hope to see you again. Thanks.

**Comment by DarthRubert** [comment]
Hi Hedron, 
     I've been using Badger in Mozilla for some time now and was able to confirm several sliders had defaulted to the disallow state in my browser although the extension does appear to be guilty of causing other page and button breaking dysfunctions on some other sites.  

     Regarding your concern about the AV extensions you're running, I remembered seeing this was included, here (https://www.eff.org/privacybadger) on the Privacy Badger FAQ:

     "The only extensions known to be incompatible with Privacy Badger is the Avast antivirus extension, which blocks the installation of Privacy Badger and other extensions."

**Comment by cooperq** [comment]
Hi @45Hedron 
I think your version of privacy badger is working just fine. It's possible that Adblock Plus is simply killing most of the trackers before privacy badger gets a chance to see if they are tracking. In this case privacy badger will serve as a good backup, catching anything that slips through the cracks. In short, I wouldn't worry about it!
