### ISSUE TITLE
2017.1.26 "Not from chrome webstore"

### ISSUE THREAD

**Issue by julian-klode** [EFForg/privacybadger#1204]
I installed 2017.1.26 from the Chrome webstore, but chrome shows me that it's not from the web store. I even uninstalled and reinstalled it to no avail.

Chrome: Version 56.0.2924.87 (64-bit)

**Comment by cowlicks** [comment]
I get the same thing on Chrome Version 56.0.2924.76 (64-bit) on GNU/linux. 
![screenshot from 2017-02-13 16-35-49](https://cloud.githubusercontent.com/assets/598099/22909642/1b327986-f20a-11e6-8212-2907a4c616ea.png)

This has happened before (see #911). It is probably another complication from the PB release process.

**Comment by cooperq** [comment]
This is a known issue. A workaround for #843
