### ISSUE TITLE
Option to disable first run page

### ISSUE THREAD

**Issue by allo-** [EFForg/privacybadger#1206]
Can you merge/adapt https://github.com/EFForg/privacybadgerfirefox-legacy/commit/1eca2cbe8472792dbf68278daf7261c4682710b9 for the new addon?

**Comment by cowlicks** [comment]
This would be useful for testing.

**Comment by cowlicks** [comment]
I'm not sure the best way to do this. Chrome doesn't have global extension preferences like firefox does, so you can't set a preference before installation to turn off the first run page. And I don't think firefox preferences api is exposed to WebExtensions.

@allo-  how are you installing Privacy Badger?

**Comment by allo-** [comment]
My usecase is preinstalling it in new profiles, which means i place it in the extension folder with the right name (as the installed extension has, not as the download from addons.mozilla.org has) and add in the new prefs.js ``user_pref("extensions.autoDisableScopes", 14);``. The the extensions gets installed on first run and should be updated as soon as possible.

**Comment by cooperq** [comment]
yea unfortunately I'm not sure there is any way to do this any more with the new web extensions API. Maybe you could add in a pre-configured storage.json that already has the first run page setting toggled and all of the other pre-seeded settings that would desire?

**Comment by allo-** [comment]
So the new api doesn't use about:config anymore at all? I think i need to look into the new SDK what it is doing and what would be possible to configure before installation.

Are you sure, its ``storage.json``? In my profile i only find a ``storage.sqlite``, which seems to be empty.

**Comment by cooperq** [comment]
yes that is it! I believe that setting is parsed every time, so that should do the trick. Good luck!

**Comment by cowlicks** [comment]
@allo- that should work except that name "`jid1-MnnxcxisBPnSXQ@jetpack`" might be unique for each user. Unlike chrome, it is based off the app developers' public key, so it is the same for each user.

If it is related to the extensions URL, then this code might be useful

**Comment by cowlicks** [comment]
@allo- Ah, that string actually comes from `package.json` ([here](https://github.com/EFForg/privacybadger/blob/master/manifest.json#L6)). So it is deterministic and should be easy to get.

**Comment by allo-** [comment]
seenComic seems not to be set, if you closed the tab, but the comic is not shown again. There is a ``isFirstRun`` setting, which seems to be set.

In theory this should work:

- Download the extension to ``extensions/jid1-MnnxcxisBPnSXQ@jetpack.xpi``
- add ``user_pref("extensions.autoDisableScopes", 14);`` to prefs.js
- create ``browser-extension-data/jid1-MnnxcxisBPnSXQ@jetpack/storage.js`` with content ``{'settings_map':{'isFirstRun': false}}``

currently this _does not_ work. I am still experimenting, if the installation of the addon overwrites the storage.js file or if am still missing something.

**Comment by cooperq** [comment]
were you not able to get storage.js working then?

**Comment by allo-** [comment]
I tried yesterday the steps described above without success. I need to test more before i know if i did something in the wrong order or if its not working and depends on other "is already installed" config options in the profile.

**Comment by allo-** [comment]
Single Quotes are invalid JSON.
It works, with: ``{"settings_map":{"isFirstRun": false}}``.

I corrected my post above, so you can use it if you want to build tests based on it.

**Comment by ghostwords** [comment]
This seems related to #914.
