### ISSUE TITLE
fusiontables.google.com blocks map

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1208]
http://www.wickedlocal.com/news/20170212/where-guns-are----licenses-surge-in-brockton-region

`fusiontables.google.com` blocks the interactive map.

**Comment by terrorist96** [comment]
http://www.daytondailynews.com/news/crime--law/guns-work-new-law-allows-handguns-private-property/zRM04JjmW4S7OKZiwEmMuM/
#1249

**Comment by ghostwords** [comment]
Should probably add `fusiontables.google.com` to the yellowlist, to join [other `google.com` domains](https://github.com/EFForg/privacybadger/blob/0760b82730fe06d229a9866b3c5e270e48f0fd18/doc/sample_cookieblocklist.txt#L201-L234).
