### ISSUE TITLE
Don't show "These sliders ..." text in popup when there are no sliders.

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1211]
When there are no third party resources, don't show this message. Here is an example from eff.org. Maybe instead it should say something nice like "wow such privacy".

![screenshot from 2017-02-16 11-57-09](https://cloud.githubusercontent.com/assets/598099/23038344/8cb3e190-f43e-11e6-90d2-40b6ba263f16.png)

**Comment by robaguilera** [comment]
Hola, first time open source contributor.  I'd like to tackle this if no one has called dibbs yet.

**Comment by ghostwords** [comment]
Hi Robert, welcome and go for it!

**Comment by cowlicks** [comment]
@robaguilera feel free to ping me if you have any questions. It'd be great to hear about any hiccups you run into along the way, we can use the feedback to make the process for new developers smoother.

**Comment by robaguilera** [comment]
@garrettr @cowlicks muchas gracias - I'll be working on this today.  I'll reach out if I run into any issues.  Thanks!

**Comment by schoen** [comment]
Hi @robaguilera,

I was looking to try contributing to Privacy Badger and thinking of addressing this issue. Have you made any progress on it that you'd like to share, or would you mind if I tried to solve it?

Thanks!

**Comment by robaguilera** [comment]
@schoen feel free to tackle it.  I was working on it and ended up picking up a side project that has been eating my time.  Thanks!

**Comment by ghostwords** [comment]
This issue overlaps with #1443. We could fix both in one go, or we could fix this one separately, probably by introducing a new translation string.
