### ISSUE TITLE
Should trackers that only track with cookies only be cookieblocked?

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1214]
If a third party is seen to only be tracking with cookies, then it is probably sufficient to cookieblock it, while still monitoring it for supercookie/fingerprinting.

If we do this, and if there are a lot of third party trackers that just do cookie tracking, but provide functionality to first parties, then we would avoid having to manually update the cookieblocklist for these trackers.

My understanding is that right now we have a simple score for every tracker, and we increment this score every time it does some tracking action, then once this score is above `TRACKING_THRESHOLD` we completely block it. We would have to change this to better account for each type of tracking individually.  Once the score for cookie tracking is above a threshold, we cookieblock. Once the combined score is above another threshold, we do a complete block.

This would also allow us to better track why we block certain trackers. So when someone does report a site bug, they can include much more informative debugging info. 

Thoughts?

**Comment by cooperq** [comment]
An interesting idea for sure. I would say that right now we don't check enough other kinds of tracking to make this worthwhile but it could be a good future enhancement.

**Comment by pde** [comment]
The big problem here is IP addresss. We take the cookie as a sign of poor behaviour, but IP addresses are a huge privacy problem.

A secondary problem is that there are a lot of kinds of supercookie that we just don't know how to detect.

**Comment by pde** [comment]
A third issue is incentives. We want to incentivise advertisers to honour users' privacy requests. If they have ads that track with cookies, blocking those ads creates a stonger incentive for them to start respecting DNT opt out requests from users.

**Comment by pde** [comment]
Between those three problems, I think the answer would be "no" for the foreseeable future.
