### ISSUE TITLE
Crash on startup with "ungoogled chromium"

### ISSUE THREAD

**Issue by gwerbin** [EFForg/privacybadger#1215]
When using [Ungoogled Chromium](https://github.com/Eloston/ungoogled-chromium), Privacy Badger crashes immediately on startup. Nothing comes up in the JS developer console; just the "Privacy Badger has crashed" notification.

Obviously this is an off-label usage, so I understand stuff will break. But getting Privacy Badger to work on Ungoogled Chromium is probably something other people might want.

What I'm wondering is:

1. How can I go about debugging this if the developer console is empty? I am not what you'd call a web development expert.
2. Is this a Privacy Badger issue or an Ungoogled Chromium issue?

**Comment by cowlicks** [comment]
Go to settings > extensions and look for Privacy Badger in the list of extensions. It might say something extra there. 

Then inspect the background view by clicking on "Inspect views: background page", while this is open reload the extension by pressing (Ctrl+R). Anything interesting?

**Comment by epgeroy** [comment]
I been trying to add the privacybadger to my ungoogled chromium
but the google store wont let me, I have added some other extensions using a "hackish" way

Is there a known way to add privacybadger to the ungoogled chromium.

on the other hand what is the status of this bug/crash

thanks in advance

**Comment by ghostwords** [comment]
I'm going to close this as an Ungoogled Chromium bug. Happy to review a PR if there is a simple workaround for Privacy Badger though.
