### ISSUE TITLE
Not displaying traditional Chinese correctly

### ISSUE THREAD

**Issue by alexvong1995** [EFForg/privacybadger#1222]
I am running Firefox on Debian Stretch.
```
$ firefox --version
Mozilla Firefox 45.7.0
```
```
$ uname -a
Linux debian 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux
```
![privacy-badger](https://cloud.githubusercontent.com/assets/10696787/23347253/b182874e-fc98-11e6-8f8b-1a927320733a.png)

**Comment by cooperq** [comment]
Thanks we will look into this.

**Comment by alexvong1995** [comment]
Cooper Quintin <notifications@github.com> writes:

> Thanks we will look into this.
>
Thanks for the quick reply!

**Comment by alexristich** [comment]
Hi there,

I gave this a try on a machine running Ubuntu 14.04 using Firefox 45.7.0 (the same version you noted in your original report) and was able to reproduce the issue not on the `about:addons` page, but in the popup itself. I then went ahead and grabbed this Firefox version for OSX and confirmed it's an issue in both 45.7.0 and 45.8.0. I checked a couple other extensions with translations (i.e. uBlock Origin) and they're working properly, so there's something specific to Privacy Badger's way of handling things that isn't working properly.

Immediately, my guess is that it might be related to the way translations are processed in the WebExtensions version of Privacy Badger (namely it uses `chrome.i18n` API).

@cooperq You're probably most familiar with the translations - any thoughts on how to best proceed here? Note that the translations _do_ work properly on more recent versions of Firefox, so it appears to only be an issue with 45 ESR.

**Comment by cooperq** [comment]
Is ublock origin using the web extensions API? At a first guess I would
say this is probably an bug with the webex implementation in ESR. We
should test other web extensions.

**Comment by alexristich** [comment]
Here's what uBlock Origin uses for Firefox:
https://github.com/gorhill/uBlock/blob/40a85f8c04840ae5f5875c1e8b5fa17578c5bd1a/platform/firefox/vapi-common.js#L103

And here's what it uses for Chrome:
https://github.com/gorhill/uBlock/blob/40a85f8c04840ae5f5875c1e8b5fa17578c5bd1a/platform/chromium/vapi-common.js#L74

I'm not really familiar with the Services.jsm module, but I seem to recall him having a lot of code built in that jumps past WebExtensions-dependent functions if not supported. I can give some other extensions a try perhaps tomorrow to see if I can reproduce this in other WebEx extensions.

**Comment by alexristich** [comment]
@alexvong1995 We talked more about this in today's Privacy Badger developer meeting, and since this works in Firefox version 52, which is the newest to-be ESR version of Firefox, we won't be taking any action here to fix this in Firefox 45. What I'd recommend is upgrading to Firefox 52 when it's most convenient for you so you'll be able to see the translations in the extension.

If you have any other issues to report please feel free to open a new issue!

**Comment by alexvong1995** [comment]
Alex Ristich <notifications@github.com> writes:

> @alexvong1995 We talked more about this in today's Privacy Badger developer meeting, and
> since this works in Firefox version 52, which is the newest to-be ESR version of Firefox, we
> won't be taking any action here to fix this in Firefox 45. What I'd recommend is upgrading to
> Firefox 52 when it's most convenient for you so you'll be able to see the translations in the
> extension.
>
That's fine. I didn't know the bug was specific to Firefox 45. I think I
will wait for my distro to upgrade instead since I mostly use tor
browser to browse the web anyway. Thanks for the investigating the
issue!

**Comment by ghostwords** [comment]
This should now be fixed on Debian: https://github.com/EFForg/privacybadger/issues/1412#issuecomment-310101058
