### ISSUE TITLE
Error message on start: Unknown permission "privacy"

### ISSUE THREAD

**Issue by LaurentBonnaud** [EFForg/privacybadger#1231]
Hi,

each time I start firefox I get the following error messages in my terminal:

```
$ /usr/local/firefox-64/firefox
1488546252855   addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack WARN    Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing permissions.9: Unknown permission "privacy"
1488546252857   addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack WARN    Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing author: An unexpected property was found in the WebExtension manifest.
1488546252857   addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack WARN    Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.
1488546252881   addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack WARN    Please specify whether you want browser_style or not in your browser_action options.
```

They seem harmless (I have seen them in other bug reports and privacy badger seems to work fine), but they are distracting when someone tries to debug more serious issues.

Version info:
Firefox 51.0.1 on Linux (same thing with beta, aurora and nightly)
Privacy Badger 2017.1.26.1

**Comment by alexristich** [comment]
You're right that these are harmless :)

It appears that Firefox is looking at the manifest and throwing warnings for things it doesn't recognize. The first one in particular is for the `privacy` API, which according to the original Bugzilla report @groovecoder filed should now be included in Firefox 54+ (https://bugzilla.mozilla.org/show_bug.cgi?id=1312802).

We do have logic in the code where `chrome.privacy` is used to detect support for this API first then act accordingly, so lack of browser support for `chrome.privacy` shouldn't break anything, it'll just result in WebRTC IP leak protection being disabled.

I'll go ahead and close this one - if you have any other thoughts or concerns about this please follow up here!

**Comment by LaurentBonnaud** [comment]
Thank for looking at this!
I am looking forward to Firefox 54 in order to get rid of this error message :>...
