### ISSUE TITLE
Error messages on Firefox exit: tabs.onRemoved event fired after context unloaded.

### ISSUE THREAD

**Issue by LaurentBonnaud** [EFForg/privacybadger#1232]
Hi,

each time I exit Firefox I see the following error messages in my terminal:

```
$ /usr/local/firefox-64/firefox
[...]
tabs.onRemoved event fired after context unloaded.
tabs.onRemoved event fired after context unloaded.
tabs.onRemoved event fired after context unloaded.
[...many more identical messages...]
```

They are caused by Privacy Badger because they do not appear when I uninstall Privacy Badger.

Version info:
Firefox 51.0.1 on Linux (same thing with beta, aurora and nightly)
Privacy Badger 2017.1.26.1

**Comment by ghostwords** [comment]
I am going to resolve this for now. Firefox is up to 56 by now, and we don't know if these messages led to any actual issues with the add-on.
