### ISSUE TITLE
Uninstalling Privacy Badger does not clean everything up

### ISSUE THREAD

**Issue by LaurentBonnaud** [EFForg/privacybadger#1233]
Hi,

when I try to uninstall Privacy Badger from a Firefox profile, I see the following error messages the next time I start Firefox:

```
$ /usr/local/firefox-64/firefox
1488546904035   addons.xpi      WARN    Failed to call uninstall for jid1-MnnxcxisBPnSXQ@jetpack: Error: Unknown add-on ID jid1-MnnxcxisBPnSXQ@jetpack (resource://gre/modules/addons/XPIProvider.jsm:8181:11) JS Stack trace: DirectoryInstallLocation.prototype.getLocationForID@XPIProvider.jsm:8181:11 < this.XPIProvider.processPendingFileChanges@XPIProvider.jsm:3412:31 < this.XPIProvider.checkForChanges@XPIProvider.jsm:3746:19 < this.XPIProvider.startup@XPIProvider.jsm:2813:25 < callProvider@AddonManager.jsm:235:12 < _startProvider@AddonManager.jsm:788:5 < AddonManagerInternal.startup@AddonManager.jsm:972:9 < this.AddonManagerPrivate.startup@AddonManager.jsm:3016:5 < amManager.prototype.observe@addonManager.js:71:9
1488546904036   addons.xpi      WARN    Attempted to remove jid1-MnnxcxisBPnSXQ@jetpack from app-profile but it was already gone
```

And indeed the following file remains in my test profile:

`./.mozilla/firefox/mgde85gg.dev-edition-default/browser-extension-data/jid1-MnnxcxisBPnSXQ@jetpack/storage.js`

Version info:
Firefox 51.0.1 on Linux (same thing with beta, aurora and nightly)
Privacy Badger 2017.1.26.1

**Comment by cooperq** [comment]
This seems like a firefox bug and not a privacy badger bug. There is no way for us to clean up this fiel on  uninstall.

**Comment by ghostwords** [comment]
I opened an issue with Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1350018

**Comment by ghostwords** [comment]
This should be fixed in Firefox at this point.
