### ISSUE TITLE
Unreadable characters only in linux

### ISSUE THREAD

**Issue by jony0008** [EFForg/privacybadger#1234]
Why are some characters unreadable when using Privacy Badger with firefox in Debian Stretch but not in Windows. I am using it in swedish. 

Example:
Privacy Badger detekterad 1 spanare pÃ¥ denna sida. Dessa reglage lÃ¥ter dig bestÃ¤mma hur Privacy Badger hanterar varje spanare.

**Comment by ghostwords** [comment]
Seems like a duplicate of #1222. Let me know if not the case.
