### ISSUE TITLE
domain serving static content (CSS, images) flagged as potential tracker

### ISSUE THREAD

**Issue by redemption** [EFForg/privacybadger#1235]
Hi there,

We received a complaint by a user recently where he could not receive CSS and other files from our site, thereby having a degraded experience.  After some investigation the user determined that Privacy Badger had started blocking the domain cdn.staticneo.com where we serve all our js, css, sprites, and some images.  

To my knowledge we don't serve any tracking from there, it is purely a CDN hosted static file serving domain behind CloudFlare's CDN.

I installed Privacy Badger 2017.26.1 on Firefox and it did not automatically block the domain, but it did falsely list it in the "potential trackers" list when I clicked on the plugin icon.

Is there some way for me to debug what signals the domain is sending that raise this red flag so we can correct the behaviour?

**Comment by ghostwords** [comment]
Linking to the feature request for explaining why something is considered a tracker: #963.

**Comment by ghostwords** [comment]
Hello! Could you provide an example site where you see cdn.staticneo.com resources show up marked as a (potential) tracker?

**Comment by cooperq** [comment]
I'm guessing that this has to do with cloudflare's __cfuid cookie. Linking to #1237

**Comment by redemption** [comment]
Looking at #1237 I think the __cfuid is exactly what is going on.  We have no option of turning off that cookie, as described here:

https://support.cloudflare.com/hc/en-us/articles/200170156-What-does-the-Cloudflare-cfduid-cookie-do-

Is there any chance Privacy Badger may implement the suggestion in #1237 to avoid false positives on Cloudflare hosted CDN files?

For example site please see

www.usaudiomart.com

I've attached a screenshot.  In my case the potential tracker is not blocked, but at least one user reported to us that it was blocked automatically for them, they had to remove the block.

![badger_potential_trackers](https://cloud.githubusercontent.com/assets/517273/23631410/3b4e1fe4-0273-11e7-8687-a86c459e05d3.png)

**Comment by ghostwords** [comment]
Fixed by #1361.
