### ISSUE TITLE
s0.2mdn.net breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1236]
https://www.thestreet.com/story/13462616/1/3-volatile-stocks-to-buy-for-potentially-big-gains.html

`s0.2mdn.net` breaks video

**Comment by terrorist96** [comment]
https://www.cnet.com/how-to/wikileaks-cia-hack-phone-tv-router-vault-7-year-zero-weeping-angel/

**Comment by terrorist96** [comment]
http://ellentube.com/videos/0-s56c3e0j/

**Comment by ghostwords** [comment]
Should `s0.2mdn.net` be [yellowlisted](https://github.com/EFForg/privacybadger/blob/0760b82730fe06d229a9866b3c5e270e48f0fd18/doc/yellowlist-criteria.md)?

**Comment by terrorist96** [comment]
http://www.politifact.com/truth-o-meter/statements/2017/feb/02/nancy-pelosi/pelosis-misleading-claim-gorsuch-sides-felons-over/

Yes, yellowlisting it will fix it. Whether or not it should be moved based on criteria, idk.

**Comment by terrorist96** [comment]
https://www.radiojavan.com/videos/video/mojan-yz-saman-pi-chalim-2-(ft-ho3ein)

`s0.2mdn.net` breaks video. Move to yellow.

**Comment by terrorist96** [comment]
https://www.usnews.com/news/best-states/tennessee/articles/2017-11-01/guns-to-be-allowed-at-new-tennessee-legislative-complex

Video at bottom of article won't play. (Takes a few seconds to appear)

**Comment by ghostwords** [comment]
I can't reproduce tracking ... Could you post your [debugging information](https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b) for `2mdn.net`?

My current thinking is that this is a domain we should have migrated when we fixed the attribution bug (#1428). We released those fixes with Privacy Badger version 2017.6.13. Here are the monthly error reports counts where `s0.2mdn.net` was blocked:
```
+---------+--------------+-------+
| ym      | blocked_fqdn | count |
+---------+--------------+-------+
| 2017-11 | s0.2mdn.net  |    12 |
| 2017-10 | s0.2mdn.net  |    56 |
| 2017-09 | s0.2mdn.net  |    61 |
| 2017-08 | s0.2mdn.net  |    79 |
| 2017-07 | s0.2mdn.net  |    60 |
| 2017-06 | s0.2mdn.net  |    90 |
| 2017-05 | s0.2mdn.net  |   107 |
| 2017-04 | s0.2mdn.net  |    74 |
| 2017-03 | s0.2mdn.net  |    98 |
| 2017-02 | s0.2mdn.net  |    81 |
| 2017-01 | s0.2mdn.net  |    89 |
| 2016-12 | s0.2mdn.net  |    69 |
| 2016-11 | s0.2mdn.net  |    33 |
| 2016-10 | s0.2mdn.net  |    19 |
| 2016-09 | s0.2mdn.net  |    16 |
| 2016-08 | s0.2mdn.net  |    11 |
| 2016-07 | s0.2mdn.net  |     8 |
| 2016-06 | s0.2mdn.net  |    13 |
| 2016-05 | s0.2mdn.net  |    17 |
| 2016-04 | s0.2mdn.net  |    22 |
| 2016-03 | s0.2mdn.net  |    32 |
| 2016-02 | s0.2mdn.net  |    32 |
| 2016-01 | s0.2mdn.net  |    44 |
| 2015-12 | s0.2mdn.net  |    25 |
| 2015-11 | s0.2mdn.net  |    31 |
| 2015-10 | s0.2mdn.net  |    43 |
| 2015-09 | s0.2mdn.net  |    34 |
| 2015-08 | s0.2mdn.net  |    19 |
+---------+--------------+-------+
```
Note that the peak was in May. (It would be nice to normalize these counts against Privacy Badger user numbers to make the picture more clear. Could then maybe discover other similar domains.)

**Comment by terrorist96** [comment]
```
**** ACTION_MAP for 2mdn
VM2533:5 2mdn.net {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1492896406234,
  "userAction": ""
}
VM2533:5 s0.2mdn.net {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1510325018869,
  "userAction": "user_cookieblock"
}
VM2533:5 s1.2mdn.net {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1510197983523,
  "userAction": ""
}
VM2533:5 gcdn.2mdn.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1510026616125
}
VM2533:5 r4---sn-p5qlsne6.c.2mdn.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1509445597001
}
VM2533:5 r13---sn-p5qlsnll.c.2mdn.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1509659587309
}
VM2533:5 r6---sn-p5qs7n7d.c.2mdn.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1509790729470
}
VM2533:5 r14---sn-p5qlsnly.c.2mdn.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1510193312010
}
VM2533:7 **** SNITCH_MAP for 2mdn
VM2533:9 2mdn.net [
  "politifact.com",
  "ign.com",
  "brobible.com"
]
```

**Comment by terrorist96** [comment]
http://www.nfl.com/videos/nfl-network-top-ten/0ap2000000113872/Top-Ten-Controversial-Calls-Holy-roller

**Comment by terrorist96** [comment]
https://www.funimation.com/shows/mobile-suit-gundam-iron-blooded-orphans/iron-and-blood/
