### ISSUE TITLE
Fix cloudflare based false positives

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadger#1237]
Sites which are behind cloudflare set a __cfuid cookie for cloudflare security purposes. While this could be used for tracking it is ostensibly not used for that and the effect is that it causes many false positives for tracking. We should probably do something like whitelist the __cfuid cookie in terms of tracking, or mark it low entropy. I think this would fix a number of broken sites, especially CDNs.

**Comment by cowlicks** [comment]
I think this is another example of a case where only cookie blocking where we see cookie tracking would be useful, like mentioned in #1214. We could whitelist the cookie, or marked it as low entropy, but nothing would stop cloudflare from using it for tracking later. So the cookie *should* be blocked, but the origin should *not* be. Since many of the origin's behind cloudflare are probably legitimate CDN's.

**Comment by cooperq** [comment]
another option might be to just always strip the __cfuid cookies from
any request before the accounting happens. I'm curious what other side
effects this might have though, e.g. would users get treated similarly
to a tor browser and have to solve captchas?

**Comment by cowlicks** [comment]
I think that is a great idea! There are probably other cases where being able to block individual cookies in a request would be valuable.

**Comment by alexristich** [comment]
Been fiddling around with this one this evening and here's what I've found so far:

1) Stripping the `__cfduid` from the cookie only explicitly affects domains when the Cloudflare setting is set to "I'm Under Attack!" Note that possible settings are `Off`, `Essentially Off`, `Low`, `Medium`, `High`, and `I'm Under Attack`. It hangs in an infinite loop that looks something like this:
![cloudflare_under_attack](https://cloud.githubusercontent.com/assets/11308076/23645305/5309634e-02c0-11e7-942a-4230cec88354.png)

2) There's another cookie property called `cf_clearance`; haven't looked up its purpose but it also has a long alphanumeric string.

3) With the Cloudflare security setting lower it seems to load pages OK.

Pushed my unsightly WIP here, so feel free to take a look and play around with it:
https://github.com/EFForg/privacybadger/commit/f956660eaaa155b11b62617faca26f4f89284f05

**Comment by cowlicks** [comment]
@alexristich awesome! I think stripping this cookie and not entirely cookie blocking the origin is the right thing to do.

It looks like your code is stripping this cookie only for 1st parties. I think we're interested in the third party case. Only stripping the cookies on third parties would probably fix seeing that "checking your browser" screen.

The ability to alter this behavior should be exposed to users, but if this is "critical" then adding a setting can probably wait.

**Comment by jawz101** [comment]
This is coming from a novice and probably off-topic, but I just hope Privacy Badger is neutral and assumes all sites using any particular CDN are collectively tracking me.
