### ISSUE TITLE
vidible.tv breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1238]
http://www.wxyz.com/news/see-two-masked-open-carry-activists-walk-in-dearborn-police-armed-with-ar-15-handguns

The following need to be moved to yellow to fix the video.
`cdn.vidible.tv`
`delivery.vidible.tv`

**Comment by terrorist96** [comment]
http://www.abc2news.com/news/region/baltimore-county/baltimore-co-leaders-repeal-ban-on-tasers-stun-guns

**Comment by ghostwords** [comment]
Should probably get [yellowlisted](https://github.com/EFForg/privacybadger/blob/0760b82730fe06d229a9866b3c5e270e48f0fd18/doc/yellowlist-criteria.md).

**Comment by terrorist96** [comment]
http://www.nydailynews.com/entertainment/music/mobb-deep-rapper-prodigy-dead-42-article-1.3262918

`cdn.vidible.tv`
`delivery.vidible.tv`
`trk.vidible.tv`

**Comment by ghostwords** [comment]
More examples:
- http://www.huffingtonpost.com/entry/who-run-the-westeros-world-girls_us_5978dbcae4b02a4ebb722c77
- http://www.huffingtonpost.com/entry/aleppo-syria-animals-rescued_us_597b7797e4b02a4ebb755433
- https://www.engadget.com/2017/07/25/tech-hunters-nintendo-gameboy/
- http://www.huffingtonpost.co.uk/entry/bill-browders-senate-judiciary-committee-hearing_uk_597ee55ce4b02a4ebb7675a6
- https://www.lifehacker.com.au/2015/03/top-10-smart-ways-to-save-money-on-clothes/ (vidible resources present, but no clear what's broken)
- https://www.gizmodo.com.au/2017/07/the-kids-stick-together-in-the-menacing-new-trailer-for-stephen-kings-it/ (ditto)

**Comment by terrorist96** [comment]
@ghostwords despite being on the yellow list....
![image](https://user-images.githubusercontent.com/12802056/31213893-c3c23c5c-a976-11e7-91c8-a1bf7f2f1b32.png)
What's going on here?
```
**** ACTION_MAP for vidible
VM857:5 cdn.vidible.tv {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1507765599450,
  "userAction": ""
}
VM857:5 delivery.vidible.tv {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1507349303674,
  "userAction": ""
}
VM857:5 img.vidible.tv {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1493075204123,
  "userAction": ""
}
VM857:5 newsy-vidible-ovp1.vemba.io {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1492949781791,
  "userAction": ""
}
VM857:5 trk.vidible.tv {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1507732697887,
  "userAction": ""
}
VM857:5 vidible.tv {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1492938167561,
  "userAction": ""
}
VM857:7 **** SNITCH_MAP for vidible
VM857:9 vidible.tv [
  "yibada.com",
  "huffingtonpost.com",
  "wistv.com"
]
```

**Comment by ghostwords** [comment]
`vidible.tv` was added to the yellowlist on August 21st; the most recent error report that blocks it is from August 22nd, which makes sense. But you are clearly running into some kind of yellowlist-related bug. Previously: https://github.com/EFForg/privacybadger/issues/1588#issuecomment-332410569. It seems like your issue would be related to the most recent Privacy Badger update, but maybe not. I'll keep looking ... We already found one [new bug](https://github.com/EFForg/privacybadger/issues/1699).

**Comment by terrorist96** [comment]
Yeah. And again, the reported issue here was fixed (vidible defaulted to yellow). But it reverted to red after some time.

**Comment by ghostwords** [comment]
Which domains do you see printed when you run the following on Badger's background page?
```javascript
(function () {
  let am = badger.storage.getBadgerStorageObject('action_map'),
    ylist = badger.storage.getBadgerStorageObject('cookieblock_list').getItemClones();
  for (let domain in ylist) {
    if (am.getItem(domain) && am.getItem(domain).heuristicAction == "block") {
      console.log(domain);
    }
  }
}());
```
This looks for all yellowlisted yet blocked domains.

**Comment by terrorist96** [comment]
```
VM896:6 content.jwplatform.com
VM896:6 play.google.com
VM896:6 sites.google.com
VM896:6 storage.googleapis.com
VM896:6 swiftype.com
VM896:6 unicornmedia.com
VM896:6 vidible.tv
VM896:6 wikipedia.org
```

**Comment by ghostwords** [comment]
I'm guessing your Badger ran out of [`chrome.storage.local` space](https://developer.chrome.com/apps/storage#property-local). Makes sense: we previously ran into space-related data export issues (https://github.com/EFForg/privacybadger/issues/1318#issuecomment-294939853). This means any changes you or Privacy Badger make at this point fail to survive browser/extension restarting. Which explains why you would see domains get cookieblocked and then reverted to their previous setting. Your Badger learns about new domains as you browse, but forgets all the new learning after getting restarted.

Do you see any relevant errors in the background page's console? If this is indeed the issue, I should be able to get it fixed with the next Badger update.

**Comment by terrorist96** [comment]
> Do you see any relevant errors in the background page's console? If this is indeed the issue, I should be able to get it fixed with the next Badger update.

I always see errors there. Here's a snippet:
![image](https://user-images.githubusercontent.com/12802056/31263421-0afc1458-aa30-11e7-8ed6-269e5d922360.png)

**Comment by ghostwords** [comment]
Ah yes, that's it, we got it! I'll open a ticket in a bit. Looks like your Badger ran out of storage sometime between df498dc646b8de516505ac2625dc885a203ea6c6 in February and 47bb1d639c23993f96e0f7d4cb718cb681e575e6 in June.

Any errors besides "Failed to load resource" errors (these are failed DNT policy checks, I don't think we can hide them unfortunately) are not expected.
