### ISSUE TITLE
It seems V 2017.1.26.1 does not have an entry of setting GUI in Firefox for Android

### ISSUE THREAD

**Issue by kcschan** [EFForg/privacybadger#1239]
It seems PB does not have an entry to both current site setting(drop-down-floating page when clicking at the PB button) and the setting page(by clicking the option button in the previous page).

Is it expected behavior currently?

Tested with:
privacybadger V 2017.1.26.1  installed from AMO
Firefox stable 51.0.0/51.0.1/51.0.2/51.0.3/52,0,0

**Comment by cooperq** [comment]
Correct, we currently do not support firefox on android because mozilla does not support it for web extensions. See #1084
