### ISSUE TITLE
Privacy Badger local CRX builds are broken

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1241]
While running `make` / `make travisbuild` locally successfully produces CRX builds, when used with Selenium, these builds end up hanging and timing out ChromeDriver (with an unhelpful error 104 message). The reason being the CRX archive ends up including your `.git` and `node_modules` folders and all the other things that should not go in the actual build, balooning the build to hundreds of megabytes. One workaround is to restore the zip exclusion list, removed in 54d3136:
```diff
diff --git a/scripts/makezip.sh b/scripts/makezip.sh
index eba596d..a7b33b0 100755
--- a/scripts/makezip.sh
+++ b/scripts/makezip.sh
@@ -1,3 +1,3 @@
 VERSION=`grep '"version":' manifest.json | cut -c14- | sed 's/[",[:space:]\n]//g'`
 PREFIX=privacy_badger
-zip -q -r $PREFIX-$VERSION.zip .
+zip -q -r $PREFIX-$VERSION.zip . -x@scripts/zip_exclude.lst
```
While the resulting CRX works with ChromeDriver, it can still include unwanted junk not yet covered by `zip_exclude.lst`.

The real solution I think is to move everything that goes into the actual (distributed or test) build into a dedicated folder. (We should check that git is smart about merging this big move into outstanding pull requests.)

Does Travis currently slurp the git folder into the build? Then resolving this might fix our ongoing sporadic Travis test failures.

This will also resolve (most) development warnings on the Chrome extensions page:
```
There were warnings when trying to install this extension:
Unrecognized manifest key 'applications'.
This extension includes the key file '/home/alexei/Projects/privacybadgerchrome/node_modules/web-ext/node_modules/sign-addon/node_modules/jsonwebtoken/test/rsa-public-key.pem'. You probably don't want to do that.
This extension includes the key file '/home/alexei/Projects/privacybadgerchrome/node_modules/web-ext/node_modules/sign-addon/node_modules/jsonwebtoken/test/priv.pem'. You probably don't want to do that.
This extension includes the key file '/home/alexei/Projects/privacybadgerchrome/node_modules/web-ext/node_modules/sign-addon/node_modules/jsonwebtoken/test/rsa-public.pem'. You probably don't want to do that.
This extension includes the key file '/home/alexei/Projects/privacybadgerchrome/node_modules/web-ext/node_modules/sign-addon/node_modules/jsonwebtoken/test/rsa-private.pem'. You probably don't want to do that.
This extension includes the key file '/home/alexei/Projects/privacybadgerchrome/scripts/dummy-chromium.pem'. You probably don't want to do that.
```

**Comment by cooperq** [comment]
:+1:

**Comment by cowlicks** [comment]
Couldn't we just give zip an explicit *inclusion* list? This works for me:

`zip -q -r $PREFIX-$VERSION.zip . -i "data/*" "lib/*" "src/*" "skin/*" "icons/*" "manifest.json" "_locales/*"
`

**Comment by ghostwords** [comment]
You can, which gets us roughly back to how it was with `zip_exclude.lst`. The problems with this approach include issues around blacklist maintenance, and unnecessarily large dev mode builds (and warnings). Seems much better to move everything that needs to be included (and nothing that doesn't) into a folder inside the main folder.

A similar problem is not mixing up your Web application's application and public folders, solved by making them distinct (and not via `.htaccess` blacklists). In our case we mix source and distribution folders.

**Comment by ghostwords** [comment]
Oh oops, I misread your comment, apologies!

An inclusion list solves the first part of this problem: distributing a good build, but does not solve problems associated with loading extraneous junk (`node_modules`, `.git`., key files, editor session files, ...) during development. The inclusion list is also another item to maintain: we might forget to add a new folder and then have a bad build of something that worked fine during development. Having a dedicated folder is an implicit inclusion list, with no maintenance and no discrepancies between dev and release builds.
