### ISSUE TITLE
Firefox v52.0 hiccup

### ISSUE THREAD

**Issue by frederick22** [EFForg/privacybadger#1243]
It ran 100% before I upgraded to v52.0.
Now whenever I start Firefox it opens with a blank page, that also happens with any shortcut/link saved on my PC.
Hitting "Reload current page" fixes it instantly but obviously I cannot do that forever. I've disabled Privacy Badger in the mean time, pity.

**Comment by ghostwords** [comment]
Could you share a screenshot of the blank page? Does Privacy Badger seem to function normally otherwise?

**Comment by cowlicks** [comment]
@ghostwords I think #1221 could be helpful for issues like this.

**Comment by cowlicks** [comment]
Probably related to #1101 and #1201

**Comment by ghostwords** [comment]
Needs more information, resolving for now.
