### ISSUE TITLE
move *.websimages.com to yellow

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1244]
http://www.nolimitmobilewindowtinting.com/
http://www.webs.com/

`*.websimages.com` blocks images.

**Comment by jawz101** [comment]
24% of the current open tickets are from one person posting every time they come across a site they want to see stuff that Privacy Badger blocks.  Is there an issue affecting everyone or can this one person manage their own toggles??  I mean, either there is a legitimate heuristic issue, there are one-off cases that they can manage themselves, or something else.  In the end, this is a heuristic blocker- not a blocker based on hard-coded whitelists and blacklists.

**Comment by terrorist96** [comment]
If I find an issue, I'm gonna report it. If I find an issue, I want it fixed for everyone, not selfishly fix it for myself and leave everyone else out. If I find an issue, I'm gonna report it irrespective of how many I report versus others. If I find an issue, chances are that it will impact others too, not just me. If you don't like me reporting issues, look away.

**Comment by ghostwords** [comment]
@terrorist96 I appreciate the reporting! There is much we can do to improve the heuristic; having many examples of breakage is helpful.

@jawz101 I agree that we could organize better. The solution is probably to triage problems faster. This should improve in the coming months. I am open to other suggestions!

**Comment by jawz101** [comment]
I understand but it's a heuristic engine meaning instead of a blocklist such as how adblock plus and ublock work, it blocks based on patterns.  Let's say you have 43 submitted site issues- is there enough at this point to discern a pattern which needs to be investigated to tweak a rule?  You're browsing habits are likely hitting the issues we will all experience eventually and I don't know how to collect that pattern.

**Comment by terrorist96** [comment]
> PB blocks based on patterns

I'm aware.

> is there enough at this point to discern a pattern which needs to be investigated to tweak a rule?

My solution is to add my reports to the cookie block list (which has happened many times in the past but seems like addressing reported issues has slowed down a bit recently) since they are either not actually trackers and blocking them break the page, or they are trackers but still break the page and would benefit from using script surrogates.

**Comment by jawz101** [comment]
I just wish there was an optional opt-in thing to aggregate those things we manually allow.  There is an Android XPosed module called XPrivacy which had a paid feature that aggregated everyone's security policies.  If a certain number of users blocked location access for a certain app there was a confidence threshold that basically meant "Nothing will break if you block this thing" and if you fetched the community rule it would apply that policy.

Like, if PB said "35% of users have xyz.com thing set to yellow, go ahead and set mine to yellow."

**Comment by jawz101** [comment]
Here's that [XPrivacy ](https://github.com/M66B/XPrivacy) app.  [Community Ruleset page](https://crowd.xprivacy.eu/) and an [example](https://crowd.xprivacy.eu/?package_name=com.facebook.katana) of the Facebook Android ruleset

**Comment by ghostwords** [comment]
@jawz101 That's a pretty cool idea and something I've been thinking about too. Could you open a feature request?

**Comment by jawz101** [comment]
@ghostwords will do.  I guess it's one of those wishlist things that'd at least be nice to throw out there.  I don't know if I should frame it as a complete "community ruleset engine" thing or an "opt-in mechanism to contribute to a dataset to improve engine heuristics and analyze current anti-privacy techniques."

So many buzzwords lol.  It could serve a few purposes so I'd like to frame the things it could be leveraged for.  Regardless, I'm not a fancy programmer but I'd like to write something out that communicates the idea sufficiently so it wouldn't become a short-lived topic.

The main thing is not to become a privacy concern in itself.

**Comment by terrorist96** [comment]
@ghostwords since you added the yellowlist tag, if I make a PR for this and #1140, will you merge it?

**Comment by ghostwords** [comment]
Yes, these two seem like good candidates for yellowlisting, but I would have to look into it a bit more before merging.
