### ISSUE TITLE
Fix test_cookie_tracker_detection in Firefox

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1245]
Currently [failing on master in Firefox](https://travis-ci.org/EFForg/privacybadger/jobs/210598442). Was disabled when [Selenium tests in Firefox were merged](https://github.com/EFForg/privacybadger/commit/e517a49), re-enabled as part of https://github.com/EFForg/privacybadger/pull/1205 (`git bisect` seemed to lead me to 936a1f8908a8ff2b3c784d8e6a86b05e4210eaaa), but isn't working still:
```
________________________________ CookieTest.test_cookie_tracker_detection ________________________________
...
>               window_utils.close_windows_with_url(self.driver, self.popup_url)
selenium/cookie_test.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

...
>       raise Exception("was not able to find window for url " + url)
E       Exception: was not able to find window for url moz-extension://37702c80-1338-4638-b07a-33e87fa5327d/skin/popup.html
selenium/window_utils.py:54: Exception

**Comment by cowlicks** [comment]
My fixes in #1205  were basically making it python3 compatible. So whatever is broken now is probably related to the original issue.

I've been pretty busy with work lately, but I'll probably have time to look at this next weekend. For now we could just use skip like we do [here](https://github.com/EFForg/privacybadger/blob/master/tests/selenium/options_test.py#L48).
