### ISSUE TITLE
play.google.com breaks image of playstore

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1246]
https://whispersystems.org/blog/

`play.google.com` breaks "Get it on Google Play" image.

**Comment by ghostwords** [comment]
Should probably add `play.google.com` to the yellowlist, to join [other `google.com` domains](https://github.com/EFForg/privacybadger/blob/0760b82730fe06d229a9866b3c5e270e48f0fd18/doc/sample_cookieblocklist.txt#L201-L234).
