### ISSUE TITLE
trends.google.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1254]
http://knowyourmeme.com/memes/based-stickman

`Search Interest` section
`Requests to the server have been blocked by an extension.`

Not sure if this would count as tracking. Good candidate for script surrogate?

**Comment by ghostwords** [comment]
Should probably add `trends.google.com` to the yellowlist, to join [other `google.com` domains](https://github.com/EFForg/privacybadger/blob/0760b82730fe06d229a9866b3c5e270e48f0fd18/doc/sample_cookieblocklist.txt#L201-L234).
