### ISSUE TITLE
The domain ciscospark.com appears to be "over-blocked"

### ISSUE THREAD

**Issue by stojnc** [EFForg/privacybadger#1255]
While running Privacy Badger we find that the login screen will present a blank page. I would like to file this github issue to ensure that the ciscospark.com domain isn't being overly blocked.

**Comment by ghostwords** [comment]
Could you tell us the URL of the page where this is happening?

Also, it would be great to learn where Privacy Badger saw `ciscospark.com` perform suspected tracking. Could you run the following in Badger's background page console, and share the results with us?

`badger.storage.snitch_map.getItem("ciscospark.com").`

Let me know if you need more information on how to do this (let me know then which browser you use).

**Comment by ghostwords** [comment]
Is `https://web.ciscospark.com/signin` the login page? What domains does Privacy Badger report as blocked on it?
