### ISSUE TITLE
static.wixstatic.com breaks images

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1263]
https://www.tennesseesilencer.com/

`static.wixstatic.com` breaks images.
`staticorigin.wixstatic.com` is also blocked, but can't tell if it's breaking anything.

**Comment by terrorist96** [comment]
http://www.gallery.lucidmotors.com/

**Comment by terrorist96** [comment]
https://www.elextracars.com/

**Comment by terrorist96** [comment]
https://www.xingmobility.com/

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.
