### ISSUE TITLE
Add automated tests for canvas fingerprinting

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1268]
Following up on https://github.com/EFForg/privacybadger/issues/1009#issuecomment-275499800 and https://github.com/EFForg/privacybadger/issues/1159#issue-203407525.

**Comment by cowlicks** [comment]
There is one canvas fingerprinting test already on pbtest.org

**Comment by cowlicks** [comment]
Here is a list of example sites that can be used for inspiration https://publicwww.com/websites/%22fingerprint2.min.js%22/

**Comment by ghostwords** [comment]
We can't depend on `pbtest.org` for this: Why was its fingerprint detection test passing with the development version of Privacy Badger on Firefox, the version that tried to use non-existent V8 stack trace APIs?
