### ISSUE TITLE
youtube comments

### ISSUE THREAD

**Issue by dolljoints** [EFForg/privacybadger#127]
privacy badger breaks the youtube comments something awful. you can't load reply chains, half the time hitting "read more" on a long comment doesn't work, and upvoting opens a new g+ tab which then immediately closes again, and nothing happens to the score.

**Comment by plato-cambrian** [comment]
Thanks @cooperq I had an issue in firefox where the 'Post' button remained disabled after entering text in the comment field.

For future reference: the `apis.google.com` slider was green before I clicked the comment field. After clicking the comment field (and presumably loading an async script) the `apis.google.com` slider was yellow again. Setting it green solved the issue.
