### ISSUE TITLE
Privacy Badger does not explain icons over social media buttons

### ISSUE THREAD

**Issue by KonomiKitten** [EFForg/privacybadger#1275]
I recently installed Privacy Badger went through the help tutorial payed attention to it and read it all, then while I am browsing I see these buttons.

![1](https://cloud.githubusercontent.com/assets/12713710/24336830/fe1f9d36-12e0-11e7-857a-c4bf7d86deb7.png)

These buttons aren't explained at all in the manual and I can't find anything about them in the settings for Privacy Badger either. This seems like an example of poor documentation that should be fixed.

**Comment by ghajini** [comment]
Go through documentation of privacy badger they explained nicely

**Comment by KonomiKitten** [comment]
@ghajini I cannot find any information in the First Run set of slides, I presume you mean digging through other documentation which would be not obvious to a new user of Privacy Badger?

**Comment by ghajini** [comment]
`https://www.eff.org/privacybadger#faq-How-does-Privacy-Badger-handle-social-media-widgets?`

**Comment by cowlicks** [comment]
@KonomiKitten did you notice the hover text "Privacy Badger has replaced this twitter button" ?

**Comment by ghostwords** [comment]
We could add some help text and/or imagery to the "Replace social widgets" setting on the options page, if this feature keeps confusing people.

**Comment by octref** [comment]
Is it possible to disable the small red icon only? Currently it's only possible to disable the feature altogether, or endure the jarring red icon.

**Comment by ghostwords** [comment]
Right. There is no reason for the Badger indicator to be red though. All we want is to make it clear what the button is for (Twitter, etc.) and that Privacy Badger replaced it.

**Comment by octref** [comment]
> that Privacy Badger replaced it.

I acknowledge that, but I want to have an option to see the original icon.
It's ok to default to show it, so people can learn what Privacy Badger is doing for them.
But once I learned this feature, I hope it can work in a way that doesn't interfere with my viewing experience of the website.

**Comment by ghostwords** [comment]
Closing for now as the original question was answered (there is a tooltip) and it's not clear we need to do anything else at this time.

@octref Feel free to open a new issue to request this functionality.
