### ISSUE TITLE
Privacy Badger can be installed on Android despite not being supported

### ISSUE THREAD

**Issue by KonomiKitten** [EFForg/privacybadger#1276]
I am able to install Privacy Badger for Firefox Android (via Add-ons for Firefox) despite #1239 where @cooperq says:

> Correct, we currently do not support firefox on android because mozilla does not support it for web extensions. See #1084

The compatibility setting should be changed for Privacy Badger on the Add-ons for Firefox Webpage so it cannot be installed on Android until it is supported.

**Comment by ghostwords** [comment]
@cooperq said he will mark the addon as Android-incompatible during the next Privacy Badger for Firefox update.

**Comment by ghostwords** [comment]
@cooperq, it looks like Badger is still available for Android: https://addons.mozilla.org/en-US/android/addon/privacy-badger17/

**Comment by cooperq** [comment]
Idk then.  I marked it as not available. 

On March 29, 2017 8:19:24 AM PDT, Alexei <notifications@github.com> wrote:
>@cooperq, it looks like Badger is still available for Android:
>https://addons.mozilla.org/en-US/android/addon/privacy-badger17/
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/privacybadger/issues/1276#issuecomment-290123858

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jawz101** [comment]
It'd be cooler if it did work :D

**Comment by ShapeShifter499** [comment]
I was reading through the issues. I would love to see this come to Firefox Mobile for Android,

**Comment by jawz101** [comment]
... as long as it is not a performance hog.  Firefox is slow enough on Android and I doubt it'll change anytime soon.

**Comment by cowlicks** [comment]
Well it seems like this means that Firefox for Android *does* now support webextensions. Initial tests are partially successful.

I visited panopticlick and pbtest.org on my phone, then installed PB and got improved results. It should be noted that PB cannot be installed from the eff's website, but it can be installed from the FF add-on store. 

It looks like we need to do further testing, and  we should start thinking about phone UI/UX. 

I'll post screenshots as soon as I figure out how to do that from my phone.

**Comment by jawz101** [comment]
@cowlicks are you on any particular version of FFox for Android?

**Comment by cowlicks** [comment]
Before
![screenshot_20170330-104022](https://cloud.githubusercontent.com/assets/598099/24518595/6082c838-1537-11e7-9d13-231805f59197.png)
After
![screenshot_20170330-104421](https://cloud.githubusercontent.com/assets/598099/24518583/55ebad40-1537-11e7-8a45-c06d3929f6c8.png)

Pbtest results remained the same
![screenshot_20170330-104333](https://cloud.githubusercontent.com/assets/598099/24518649/88602eea-1537-11e7-853f-f1325572d34e.png)

And some screenshots  of sites that are broken on mobile 
![screenshot_20170330-104130](https://cloud.githubusercontent.com/assets/598099/24518694/a81be382-1537-11e7-8153-d2efab9e701c.png)
Lol I like this one
![screenshot_20170330-103851](https://cloud.githubusercontent.com/assets/598099/24518717/b5074c1c-1537-11e7-9485-055d45c4bfd6.png)


I guess the panopticlick results could be a false positive, but if they are we should understand why.

**Comment by ghostwords** [comment]
Side note: As you can see, `pbtest.org` tests are currently at least partially broken, reporting success when you have no protection installed.

**Comment by cowlicks** [comment]
@ghostwords this happened before for some tests because chrome was blocking 3rd party cookies by default in selenium. It could be another browser feature like that interfering.

**Comment by ghostwords** [comment]
Oh, interesting, but try going there with a fresh profile, you should see what I mean.

Script to launch `google-chrome` in a new profile:
```bash
#!/usr/bin/env bash
PROFILEDIR=$(mktemp -d /tmp/tmp-chrome-profile.XXXXXX.d)
echo "$PROFILEDIR"
google-chrome --user-data-dir="$PROFILEDIR"
rm -rf "$PROFILEDIR"
```
Firefox version:
```bash
#!/usr/bin/env bash
PROFILEDIR=$(mktemp -d /tmp/tmp-fx-profile.XXXXXX.d)
echo "$PROFILEDIR"
firefox -profile "$PROFILEDIR" -no-remote -new-instance
rm -rf "$PROFILEDIR"
```

**Comment by ghostwords** [comment]
Resolving, as this is a [known AMO (`addons.mozilla.org`) bug](https://github.com/mozilla/addons/issues/348). See https://github.com/EFForg/privacybadger/issues/1084 for the "Privacy Badger on Android" discussion.

**Comment by Enigma0** [comment]
privacy badger on firefox on android is not working for me

**Comment by ghostwords** [comment]
We don't yet offer Privacy Badger for Android (we might relatively soon though). Mozilla has a bug in their addons gallery (https://github.com/mozilla/addons/issues/348) that shows all new add-ons as working on Android, regardless of their actual support. Sorry for the confusion!

**Comment by Enigma0** [comment]
@ghostwords you should probably leave this bug open then - until that issue is resolved - this one isn't.

**Comment by cowlicks** [comment]
Reopening, so people don't mistake this issue as "resolved" as in "privacy badger works on android".

@Enigma0 are you able to access the extension UI?

**Comment by Enigma0** [comment]
@cowlicks I am not, no. Not in Android.

**Comment by ghostwords** [comment]
Resolving as it sounds like AMO fixed their bug (https://github.com/EFForg/privacybadger/issues/1725#issue-265398173).
