### ISSUE TITLE
Chrome: scrollbar in tracker list obscures button to revert control back to Privacy Badger

### ISSUE THREAD

**Issue by dizzyMongoose** [EFForg/privacybadger#1281]
When viewing a site that has more trackers that can fit in the normal Privacy Badger dropdown window in Chrome, the scrollbar obscures the button that reverts control back to Privacy Badger. I've attached a screenshot where the revert button for odb.outbrain.com is obscured to the right of the slider, under the scrollbar.

![privacy badger scrollbar bug](https://cloud.githubusercontent.com/assets/26749854/24424007/436df5aa-13bc-11e7-9e39-9cd2f1c0fde8.png)

**Comment by ghostwords** [comment]
I believe this will be fixed by #1217, which should be getting released any day now.

**Comment by ghostwords** [comment]
This should be fixed as of Privacy Badger version 2017.3.28.
