### ISSUE TITLE
Stale version on Chrome Web Store

### ISSUE THREAD

**Issue by 4cm4k1** [EFForg/privacybadger#1284]
Hi there,

Just wondering, is it intentional that the extension hasn’t been updated with new releases in the Chrome Web Store since January 25? I’ve cloned this repo and loaded the extension manually, but I thought I’d bring this to someone’s attention.

Thanks!

Link: https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp?hl=en-US

**Comment by ghostwords** [comment]
We just did a release yesterday, so it should be version 2017.3.28, but apparently it's still under review. Thanks for bringing it up to our attention!

**Comment by 4cm4k1** [comment]
The updated version is now live in the Chrome App Store; however, Chrome still thinks it’s “Not from the Chrome Web Store.” I remember seeing that in the issue tracker somewhere…

**Comment by ghostwords** [comment]
Perhaps #1204?
