### ISSUE TITLE
*.kaltura.com breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1286]
http://ellentube.com/videos/0-s56c3e0j/

`cdnsecakmi.kaltura.com` and `cdnapisec.kaltura.com` and `s0.2mdn.net` (#1236) break video.
Related kaltura issues: #655, #743

**Comment by ghostwords** [comment]
Other `kaltura.com` domains are already [in the yellow list](https://github.com/EFForg/privacybadger/blob/0760b82730fe06d229a9866b3c5e270e48f0fd18/doc/sample_cookieblocklist.txt#L297-L300).

**Comment by ghostwords** [comment]
Should `s0.2mdn.net` be [yellowlisted](https://github.com/EFForg/privacybadger/blob/0760b82730fe06d229a9866b3c5e270e48f0fd18/doc/yellowlist-criteria.md)?

**Comment by terrorist96** [comment]
>Other kaltura.com domains are already in the yellow list.

Yes. So should we just change it to `*.kaltura.com` on the list and call it a day?

>Should s0.2mdn.net be yellowlisted?

Addressed in the dedicated issue (#1236)

**Comment by terrorist96** [comment]
https://www.clickorlando.com/news/seminole-county-tax-collector-will-allow-employees-to-carry-guns

`cdnapisec.kaltura.com`

**Comment by terrorist96** [comment]
https://nucleusvideo.astrazeneca.com/playlist/dedicated/68105791/1_w3hman32/0_aqufchxb

Need to be logged in.
`cdnapisec.kaltura.com` breaks site from loading properly.
`cdnsecakmi.kaltura.com` breaks some images.
@ghostwords

**Comment by terrorist96** [comment]
```
**** ACTION_MAP for kaltura
VM453:5 analytics.kaltura.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1522221043652,
  "userAction": ""
}
VM453:5 cdnapi.kaltura.com {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1514847401596,
  "userAction": ""
}
VM453:5 cdnapisec.kaltura.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1522031118664,
  "userAction": "user_cookieblock"
}
VM453:5 cdnbakmi.kaltura.com {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1492825641638,
  "userAction": ""
}
VM453:5 cfvod.kaltura.com {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1515700716168,
  "userAction": ""
}
VM453:5 kaltura.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1492821802246,
  "userAction": ""
}
VM453:5 stats.kaltura.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1522202808522,
  "userAction": ""
}
VM453:5 www.kaltura.com {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1513325194570,
  "userAction": ""
}
VM453:5 cdnsecakmi.kaltura.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1521910156637
}
VM453:7 **** SNITCH_MAP for kaltura
VM453:9 kaltura.com [
  "perezhilton.com",
  "elle.com",
  "cosmopolitan.com",
  "motortrend.com"
]
```

**Comment by terrorist96** [comment]
Also, why is `www.kaltura.com` on the yellowlist, but `kaltura.com` is not (and thus defaults to red)?

**Comment by ghostwords** [comment]
`www.kaltura.com` was added in #659.

**Comment by ghostwords** [comment]
I guess it's so we still block `analytics.kaltura.com` and `stats.kaltura.com` and any other `kaltura.com` domains that come up in the future? The tradeoff is us needing to keep updating the yellowlist.
