### ISSUE TITLE
Show where a domain was seen tracking

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1289]
Let's expose snitch map in the popup UI, to make debugging user issues (examples: [one](https://github.com/EFForg/privacybadger/pull/1251#issuecomment-287088320), [two](https://github.com/EFForg/privacybadger/issues/1287#issuecomment-290574721)) easier.

Suggested UI: Hidden by default, revealed by hovering over domain entries in the popup. Currently hovering reveals a tooltip. Let's add some version of "why was this blocked?" (just "why" next to blocked? probably need to redesign the tooltip), clicking which should reveal the snitch map entries.

To start addressing privacy concerns (https://github.com/EFForg/privacybadger/issues/266#issuecomment-267202566), let's at least be sure to clear already-used (>TRACKING_THRESHOLD) snitch map entries upon history clearing events.

This is phase one of implementing #963.

**Comment by ghostwords** [comment]
Note that currently [snitch map never gets cleaned up](https://github.com/EFForg/privacybadger/issues/990).

**Comment by ghostwords** [comment]
Let's ask for this info in the [CONTRIBUTING doc](https://github.com/EFForg/privacybadger/issues/1195), under how to report broken sites.

**Comment by jawz101** [comment]
I like this idea.  It'd be nice to see the prevalence of a tracker.  It'd also tie into [my opt-in idea.](https://github.com/EFForg/privacybadger/issues/1299)

**Comment by ghostwords** [comment]
I don't see a way to be notified of history-clearing events at this time without asking for the "history" permission, which will trigger a new permission warning, which seems unacceptable for Privacy Badger at this point (will lose a significant percentage of users in Chrome, and have a similar percentage stop upgrading in Firefox).

**Comment by jawz101** [comment]
Given my past experiences in IT support, people freak out when anything changes and then get over it.  It's clearly not intended to compromise privacy.  If anything, I might explain it in a blog post with an explanation and a bar napkin drawing visualizing how it would operate and remain local.


My only thought is that it would need to be a cool enough visualization to be worth seeing.
