### ISSUE TITLE
[Request] Show More Information

### ISSUE THREAD

**Issue by zero77** [EFForg/privacybadger#1292]
Can you please show more information either in the menu or in settings for instance, how the trackers are tracking you by fonts, canvas, cookies etcetera and where it is across sites or one domain only.

Also, I can’t seem to find anywhere what tracking methods are currently supported, can you please add this somewhere.

Thanks

**Comment by ghostwords** [comment]
I'll close as duplicate of #963. You can find more information regarding Badger's functionality in the docs folder here: [doc/DESIGN-AND-ROADMAP.md](doc/DESIGN-AND-ROADMAP.md). Let me know if this covers it.

**Comment by zero77** [comment]
Thanks, but this didn’t really cover what I mean. 

What I am meaning is a list of fingerprinting methods that privacy badger detects.

**Comment by ghostwords** [comment]
Right now it's just canvas fingerprinting (see [here](https://github.com/EFForg/privacybadger/blob/master/doc/DESIGN-AND-ROADMAP.md#fingerprinting-detection) in the doc).

**Comment by zero77** [comment]
Ok thanks, I see so only canvas fingerprinting is supported.
Do you know If there are any plans to support more.

**Comment by ghostwords** [comment]
Yep, check out our ["heuristic"-tagged issues](https://github.com/EFForg/privacybadger/labels/heuristic).

**Comment by zero77** [comment]
Thanks
