### ISSUE TITLE
[Request] Supporting More Fingerprinting Methods

### ISSUE THREAD

**Issue by zero77** [EFForg/privacybadger#1296]
When you get a chance can you look at supporting the detection of more tracker fingerprinting methods.

Such As, web beacons, audio, webgl, webrtc, navigation timing, Sniffly, hardware fingerprinting battery and gamepad api and others and browser pings, like fonts, add-ons or extensions, screen size, seen links and others demonstrated on browserleaks.com

**Comment by ghostwords** [comment]
We would like to make Privacy Badger detect more kinds of tracking. However, I'm going to close this as too generic. We won't be able to add all known tracking methods all at once. If you'd like to see a particular kind of tracking detected by Badger, and there isn't an already open issue, feel free to open a new issue.

**Comment by ghostwords** [comment]
Related to #1808.

**Comment by ghostwords** [comment]
#2114 is a concrete way we could get started on enhancing tracker detection.
