### ISSUE TITLE
sites.google.com breaks image

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1300]
https://devs-lab.com/how-to-unbrick-hard-soft-bricked-google-huawei-nexus-6p.html

The image under `fastboot devices` is blocked by `sites.google.com`

**Comment by ghostwords** [comment]
Should probably add `sites.google.com` to the yellowlist, to join [other `google.com` domains](https://github.com/EFForg/privacybadger/blob/0760b82730fe06d229a9866b3c5e270e48f0fd18/doc/sample_cookieblocklist.txt#L201-L234).
