### ISSUE TITLE
Privacy badger calling /.well-known/dnt-policy on sites not currently visited in Firefox

### ISSUE THREAD

**Issue by jpptinsley** [EFForg/privacybadger#1303]
This is causing firefox to basically crawl to unresponsiveness, and chew network and cpu resources. badger appears to be calling for every site I've ever visited, which is a lot.

Possibly this from -legacy? 
https://github.com/EFForg/privacybadgerfirefox-legacy/issues/225
Time  Sent    recv    Meth  resp  type                url
1.219	338	483	GET	403	application/xml	https://cdn.dynamicyield.com/.well-known/dnt-policy.txt
0.204	442	1283	POST	200	application/ocsp-response	http://rc.symcd.com/

Appears to also be causing ocsp checks.

**Comment by ghostwords** [comment]
What version of Privacy Badger do you have?

Yes, that looks like the right issue from the legacy repo. Since then, we fixed DNT policy rechecking (used to see if any non-compliant domains have become compliant) and introduced rate limiting (no more than one DNT check per second), both in #1182. It sounds like we may need to further optimize DNT checking.

Possibly related: #1297.

**Comment by jpptinsley** [comment]
"2017.3.28", assuming I'm reading this correctly. Did look for an option to turn off the rechecking entirely, but that doesn't appear to have been added. I visit a lot of sites I'm unlikely to visit again, or very frequently at all.

**Comment by ghostwords** [comment]
How frequently does this affect performance in your Firefox?

**Comment by jpptinsley** [comment]
Of late that I've noticed, daily. Typically though, I've just been killing/reopening firefox, thinking it was just a leak or bug. It was only yesterday that I happened to have a http trace tool running for something else and noticed the activity.

**Comment by tweber-cs** [comment]
Same for me.

#request# GET https://cbsnews4.cbsistatic.com/.well-known/dnt-policy.txt
#request# GET https://platform.tumblr.com/.well-known/dnt-policy.txt
#request# GET https://fpdl.vimeocdn.com/.well-known/dnt-policy.txt
etc.

OS: Windows 10
Browser: Firefox 52.0.2
Privacy Badger: 2017.3.28

**Comment by pera** [comment]
I have the exact same problem (usually after a long suspension). Unfortunately I had to disable this add-on for now.
