### ISSUE TITLE
*.secure.checkout.visa.com blocks visa checkout

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1305]
https://www.papajohns.com/order/checkout
https://www.papajohns.com/order/view-cart

`secure.checkout.visa.com`/`assets.secure.checkout.visa.com` break visa checkout option.
Add something to your cart to test.

![image](https://cloud.githubusercontent.com/assets/12802056/24841320/13c04d10-1d50-11e7-95e0-b05873657364.png)
vs
![image](https://cloud.githubusercontent.com/assets/12802056/24841321/204e4852-1d50-11e7-9b6e-8d2181b5deec.png)

and
![image](https://cloud.githubusercontent.com/assets/12802056/24841355/90d613e8-1d50-11e7-8247-37e2be7b66cb.png)
vs
![image](https://cloud.githubusercontent.com/assets/12802056/24841338/631e6a72-1d50-11e7-933c-96593b1c575a.png)

**Comment by ghostwords** [comment]
Would yellowlisting `visa.com` domains help, or does this need cookies to function?

**Comment by terrorist96** [comment]
I think it would fix it. I can't say for sure. I don't use Visa Checkout. I just noticed that it was blocked and yellowlisting it would allow it to load. Whether the payment would go through or not, I dunno.

**Comment by ghostwords** [comment]
Fixed by https://github.com/EFForg/privacybadger/commit/81b5a0d323c9cc4e4827bfb72b283f848dd74861 / #1672.
