### ISSUE TITLE
Privacy Badger menu unusable on Vimperator (Firefox) if located on the statusbar and navigationbar is disabled.

### ISSUE THREAD

**Issue by strudelkuchen** [EFForg/privacybadger#1308]
Linux
Firefox 52.*
[Vimperator](http://vimperator.org/vimperator) 3.16.*

Vimperator gives the user the option to display a statusbar on the bottom which functions a bit like in vim (showing INSERT mode etc). Extension menus/icons can also be placed there.

In this example you can see me clicking on the Privacy Badger icon and no menu appears (ONLY if the navigationbar is disabled). 
When I click on the HTTPS Everywhere icon the menu appears. 

![example](https://i.imgur.com/fPbaBSY.png)

Privacy Badger is not the only extension that has this issue, one prominent example is Ublock Origin, but most work as expected.

**Comment by strudelkuchen** [comment]
This seems to only apply if the navigation bar is disabled.

`<ESC>:set gui=nonavigationbar`

Known workaround for Ublock Origin: `<ESC>:style -name ublick * #nav-bar * { visibility: visible; }`

**Comment by ghostwords** [comment]
Thanks for documenting the workaround!
