### ISSUE TITLE
Sliders are blocked on PB's configuration window

### ISSUE THREAD

**Issue by pagod** [EFForg/privacybadger#1309]
Using PB on Firefox 52.0.2 on macOS Sierra 10.12.4
After clicking on the "Options" button in the PB pane that opens from the toolbar icon, the configuration window is displayed in FF, with the list of sites currently under scrutiny and the current behavior. For some reason, the sliders sometimes just stop working, i.e. I can't move them by hand from green to red, be it by dragging (in that case the slider shadow just follows the cursor but the slider never actually moves) or by clicking on the bar next to the slider (which doesn't react at all). This seems to happen rather randomly and sometimes starts working again after reloading this page, however even I've noticed that I'm never able to move the slider for some sites e.g. adscale.de, even after reloading the configuration window.

**Comment by pagod** [comment]
When that happens (slider blocked), it seems like the mouse cursor is taking the form of a hand (link cursor) when I hover over the slider bar, which gets highlighted, but nonetheless remains inactive. Sliders that do work show an arrow cursor instead.

**Comment by ghostwords** [comment]
Is this still an issue with the latest stable version of Firefox (55)? Is it also an issue on Privacy Badger's popup, or only on the options page?

**Comment by ghostwords** [comment]
Needs more information, resolving for now.
