### ISSUE TITLE
Clean up cookies from blocked sites

### ISSUE THREAD

**Issue by pagod** [EFForg/privacybadger#1310]
If possible, I would find it sensible and actually reassuring that cookies from sites that have been recognized as tracking or blocked by hand be completely removed from the browser. After using FirefoxF/PB for just about a day (I was using Safari and moved to FF only because Privacy Badger is not available there), I find myself, unsurprisingly, with apparently hundreds of cookies, most of which from ads/tracking sites. I realize that these cookies should be rendered useless if PB is effectively blocking the connection attempts, still it would feel much better if they simply disappeared from the list of cookies altogether.

**Comment by ghostwords** [comment]
Related: #114.

**Comment by ghostwords** [comment]
A related, more complex suggestion: #2023.

**Comment by ghostwords** [comment]
Closing as the benefit of removing existing cookies isn't clear. On the other hand, it seems good to get the cookies back when you allow a previously blocked domain. Privacy Badger does make mistakes; better that they remain reversible.
