### ISSUE TITLE
Manual slider changes are not saved in the configuration window

### ISSUE THREAD

**Issue by pagod** [EFForg/privacybadger#1311]
Using FireFox 52.0.2 on macOS Sierra 10.12.4
Sometimes when manually changing a slider in the configuration window, by clicking on the slider bar, the position/color of the slider effectively change (e.g. from right/green to middle/yellow to left/red), but then when scrolling down the position is set back to right (but the color remains red) and the tooltip for the server still says "blocked". Upon reloading the configuration window, however, the slider has moved back to its original left/green state.

**Comment by terrorist96** [comment]
I have this issue too. It only happens if you change a slider, causing the page to reload, then changing another slider thereafter. The sliders being displayed is still from the previous page load, so any changes made after the page reload is not saved.
