### ISSUE TITLE
books.google.com blocks images

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1313]
http://paulburneyministries.com/how-to-be-a-bawse-a-guide-to-conquering-life/

`books.google.com` blocks images halfway down the page

**Comment by ghostwords** [comment]
Should probably add `books.google.com` to the yellowlist, to join [other `google.com` domains](https://github.com/EFForg/privacybadger/blob/0760b82730fe06d229a9866b3c5e270e48f0fd18/doc/sample_cookieblocklist.txt#L201-L234).
