### ISSUE TITLE
Feature request: Option to set referer to defined value instead of blocking

### ISSUE THREAD

**Issue by tux2000** [EFForg/privacybadger#1314]
I would like to see an option to set the referer to a defined value instead of filtering it on a per site basis. Many newspapers have "login walls" but allow access when referred from for example google. Currently I use a separate plugin for this but Chromium produces an error since the referer header is modified by two plugins.

![screenshot from 2017-04-13 15-13-36](https://cloud.githubusercontent.com/assets/1639672/25006214/4cd8e724-205c-11e7-98e6-af4b045b4bd1.png)

**Comment by ghostwords** [comment]
Privacy Badger strips the referrer header from ["yellowlisted"](https://github.com/EFForg/privacybadger/blob/master/doc/yellowlist-criteria.md) domains. If two Chrome extensions try to modify the same header, only one will succeed. This particular scenario seems fine, as you probably want "Referer Control" to take precedence.

**Comment by ghostwords** [comment]
Related: #855.

**Comment by ghostwords** [comment]
The ability to configure the referrer header to a specific value in Privacy Badger seems to be out of scope. Privacy Badger is meant to be an install-and-forget, no-configuration-necessary privacy tool.
