### ISSUE TITLE
broken encoding in firefox 45.8.0

### ISSUE THREAD

**Issue by 3LwBcdopH** [EFForg/privacybadger#1316]
My locale is ru_RU.UTF-8. My OS is Debian 8.7 on Linux 3.16.0-4-amd64. Screenshots follow.

http://i89.fastpic.ru/big/2017/0415/16/8c849312bab3844e29cbac834c4da816.png
http://i89.fastpic.ru/big/2017/0415/b0/b5c89fa38426e9c723c5c1bb2d20cdb0.png
http://i89.fastpic.ru/big/2017/0415/2b/77b033fee25e7d7b8405a1fa751bef2b.png

**Comment by ghostwords** [comment]
I think this is a duplicate of #1222. If so, this is a Firefox bug that you can fix by upgrading Firefox. Please see https://github.com/EFForg/privacybadger/issues/1222#issuecomment-285542771 for more information.
