### ISSUE TITLE
a.optnmnstr.com blocks image

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1320]
http://tomwoods.com/ep-440-liberland-a-new-libertarian-country/

Visiting that page for the first time and scrolling down will trigger a popup. `a.optnmnstr.com` blocks image.

![image](https://cloud.githubusercontent.com/assets/12802056/25060737/b976986a-2172-11e7-9299-3191b37792df.png)

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.

**Comment by ghostwords** [comment]
Oh, I had a typo in the migration, oops. The underlying bug should be fixed, but you have to remove `optnmnstr.com` domains from Privacy Badger's list on the options page yourself.
