### ISSUE TITLE
Privacy Badger crashes Firefox when opening sites that use basic auth prompts

### ISSUE THREAD

**Issue by jorgegarciadev** [EFForg/privacybadger#1324]
As the title says, Privacy Badger crashes Firefox when opening sites that use basic auth prompts. I have tested it opening a router and an IP cam on Firefox for Linux and for macOS 52.0.2. The IP for the devices have been whitelisted, and even disabling Privacy Badger for the sites the crashes happen. Had to disable Privacy Badger on the Add-ons Manager to avoid the crashes. I can access both devices using Chromium and Privacy Badger.

**Comment by ghostwords** [comment]
Do the crashes still happen in Firefox with a new profile with Privacy Badger installed?

**Comment by jorgegarciadev** [comment]
No, I have making some tests and it seems that the crashes only happens when Privacy Badger and [PassIFox](https://addons.mozilla.org/en-US/firefox/addon/passifox/) are enabled at the same time.

**Comment by Bisaloo** [comment]
I have been having the same issue for quite some time now. It didn't occur to me it was caused by privacy badger.

You can use the following test url: https://repos.archlinux.org/

When I click `cancel` with privacy bager enabled, firefox crashes. This is quite annoying.

I can provide further info if needed.

**Comment by Bisaloo** [comment]
It's also worth noting that I don't use PassIFox.

**Comment by ghostwords** [comment]
Hi @Bisaloo, do the crashes still happen in a new profile of Firefox with Privacy Badger installed?

**Comment by Bisaloo** [comment]
No, it doesn't crash on a new profile with PB installed.

**Comment by ghostwords** [comment]
Hmm, that's good to know. I wonder if it's one of your other add-ons (or some non-default Firefox setting?) that, in combination with Privacy Badger, is responsible for the crash. You could try disabling the other add-ons one by one to identify the culprit.

**Comment by ghostwords** [comment]
Something else to check is whether the crashes are related to something in Privacy Badger's training data. We could test this possibility by seeing if importing Badger's data from your old profile into the new profile makes crashes happen in the new profile. To export/import Badger data, visit the Manage Data tab on Badger's options page.

**Comment by Bisaloo** [comment]
> Something else to check is whether the crashes are related to something in Privacy Badger's training data. We could test this possibility by seeing if importing Badger's data from your old profile into the new profile makes crashes happen in the new profile. To export/import Badger data, visit the Manage Data tab on Badger's options page.

Good idea! It doesn't crash on the new profile even when I import the data from my old profile.

> Hmm, that's good to know. I wonder if it's one of your other add-ons (or some non-default Firefox setting?) that, in combination with Privacy Badger, is responsible for the crash. You could try disabling the other add-ons one by one to identify the culprit.

I will try that but something I have noticed that might put us on the right track is that I always get the login popup a second time after clicking `cancel` on my old profile with Privacy Badger disabled. This doesn't happen on a fresh profile.

**Comment by Bisaloo** [comment]
Okay, in my case, the issue comes from the interaction between [FoxyProxy](https://getfoxyproxy.org/) and Privacy Badger.

When one or the other is disabled, the browser doesn't crash.

**Comment by Bisaloo** [comment]
I can somewhat reproduce this issue when installing FoxyProxy and Privacy Badger on a fresh profile.

You need to configure FoxyProxy to `Use proxies based on their pre-defined patterns and priorities` (no need to define any proxy or pattern).

Go to any page with a login popup like https://repos.archlinux.org/ and the browser should crash the second time you click `cancel`.

Quite strangely, it crashes when I click `cancel` for the first time on the usual profile.

**Comment by ghostwords** [comment]
Thanks for investigating @Bisaloo!

**Comment by loconox** [comment]
Having the same issue with PB + PassIFox. Thanks :)

**Comment by BenLand100** [comment]
I can independently confirm everything @Bisaloo found using Privacy Badger 2017.6.13.1, FoxyProxy Standard 4.6.5, and Firefox-54 on a fresh profile. I've noticed this issue for a few months now, but only recently was frustrated enough to narrow it down to some interaction between FoxyProxy and Privacy Badger.

**Comment by ghostwords** [comment]
We should get this filed in [Bugzilla@Mozilla](https://bugzilla.mozilla.org) if there isn't an issue for this already.

**Comment by loconox** [comment]
I've done it : https://bugzilla.mozilla.org/show_bug.cgi?id=1409378

**Comment by ygrange** [comment]
And it was marked as invalid :(. Is there a way to disable parts of PrivacyBadger (or run it in a debug mode) so I could see if I can isolate where the issue comes from?

**Comment by ghostwords** [comment]
Is this still an issue with Firefox 57?

My hunch is that this Firefox bug has to do with low-level WebExtensions APIs (like intercepting Web requests) that cannot be disabled without rendering Privacy Badger/uBlock (https://github.com/pfn/passifox/issues/620#issuecomment-325713997) pointless.

This might also be one of those Firefox bugs that happens when you have a WebExtensions add-on (Firefox 57 onwards only supports WebExtensions) and a legacy add-on installed together.

See [above](https://github.com/EFForg/privacybadger/issues/1324#issuecomment-305130414) for a workaround.

**Comment by ygrange** [comment]
heh, good point, thanks. I wasn't aware of FF 57 coming out. Technically I can't test since passifox is now legacy, but I now have a stable(r) system (at cost of losing half my addons, but that's not your probem :) ).

**Comment by loconox** [comment]
As PassiFox is not yet compatible with FF57, I switched to KeePassHttp-Connector. And not bug with Basic Auth.

**Comment by jorgegarciadev** [comment]
Since PassIFox seems abandoned, and have been forked to KeePassHttp-Connector and there are no crashes in the fork I'm going to close this issue. If PassIFox is updated for Firefox Quantum it can be opened again.

**Comment by ghostwords** [comment]
Thanks for the update!
