### ISSUE TITLE
*.staticworld.net breaks images

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1328]
http://www.computerworld.com/article/2704414/operating-systems/unix---tracking-disk-space-usage.html

`*.staticworld.net` breaks images

**Comment by terrorist96** [comment]
http://www.greenbot.com/article/2462430/cyber-dust-review-mark-cubans-private-messaging-app-is-just-too-inconvenient.html

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.
