### ISSUE TITLE
Cookies being set via DNT policy check requests

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1330]
They should not be!

Previously:
- https://github.com/EFForg/privacybadgerfirefox-legacy/issues/220
- https://github.com/EFForg/privacybadgerfirefox-legacy/compare/0.2.2...0.2.3

**Comment by cooperq** [comment]
This is actually a reversion, there used to be code specifically making  sure this was not the case.

**Comment by michael-oneill** [comment]
Actually in the case of the W3C TSR and if you rely on Out-of-Band-Consent (Tk: C) then you have to send the cookies (how else is the server going to know if the user has have given consent?)
Of course this is not necessary if the user agent supports the DNT API, as the presence of consent in indicated by the DNT header.

In all cases IMO the user agent should remove any Set-Cookie headers from any response (dnt-policy.txt as well)
