### ISSUE TITLE
test_cookie_tracker_detection still fails sometimes in Firefox

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1331]
For example: https://travis-ci.org/EFForg/privacybadger/jobs/224066314

Previously: #1245.

**Comment by cowlicks** [comment]
This may be resolved by #1437 if there are still issues later, these commits may be helpful in fixing the issue. https://github.com/EFForg/privacybadger/pull/1437/commits/e9208f6506503305c86fce689a2e2c9c65a11e49
https://github.com/EFForg/privacybadger/pull/1437/commits/26b5647f5b1f709661aa0d747d76522d87bbd14d

They try to handle tabs more gracefully

**Comment by cowlicks** [comment]
Haven't seen this in a while. Closing.
