### ISSUE TITLE
Should be able to black-list sites

### ISSUE THREAD

**Issue by mrphs** [EFForg/privacybadger#1332]
Just like how there's a tab to white-list sites, there should be a way to blacklist them. otherwise it's going to take a while for privacy badger to realize to block `*.google-analytics.com` or `*.doubleclick.*`.

**Comment by ghostwords** [comment]
You can click on the slider next to each domain to manually block it. Does that help?

**Comment by mrphs** [comment]
I know about the slider. That's gonna be after visiting that site or loading it. For instance, if I reinstall my browser and already know that I don't want anything from $known_trackers to ever load, I will have to find a website that uses them and remember to use the sliders to block them.

**Comment by ghostwords** [comment]
If you'd like to preserve/combine your Badger data, you can export and import from the options page, under the Manage Data tab.

**Comment by mrphs** [comment]
I'm well aware of that option but they're different things. My current data is too big and it reveals information about my browsing habits. I wouldn't want to put that on another computer. I just simply want to block some of the known trackers.

**Comment by ghostwords** [comment]
Are you looking for a way to manually teach Privacy Badger to block a list of domains it doesn't yet know about? Could you explain this scenario a bit more? (How do you know which domains to add?)

**Comment by 77Mugen** [comment]
Hi 
I just reinstallt my computer. Before Privacy Badger worked fine. But now It doesnt show me any pages or maybe one or two. So I jumped to the options were it says it has 125 pages. Some I can mark red but all Google once I cant chage. Some I can change red but if I scroll down or load the page new they are all back like before. Could someone give me a hint what to do. Want life in an internet without Privacy Badger ;) alone with all this data suckers.
Thanks in advance

**Comment by ghostwords** [comment]
Hi @77Mugen, since your Badger is starting from scratch, it just needs a little time to learn what to block. I wouldn't worry about the sliders unless something is broken on a page and you'd like to figure out what it is (instead of just disabling Privacy Badger on that site).

**Comment by mrphs** [comment]
@ghostwords well, for example I know that anything on `doubleclick.net` is a tracker, and even on the browser that I often use, it sometimes misses some of the subdomains of double click. With this feature, I could just go in and say blacklist `*.doubleclick.*` and be done with it.

**Comment by ghostwords** [comment]
The ability to manually add domains to Privacy Badger seems to be out of scope.

Privacy Badger is meant to be an install-and-forget, no-configuration-necessary privacy tool. If you seek a greater level of protection, I can recommend pairing Privacy Badger with uBlock Origin.
