### ISSUE TITLE
Different author in Firefox about:addons when installing from addons.mozilla.org vs. eff.org

### ISSUE THREAD

**Issue by jeremyn** [EFForg/privacybadger#1334]
When I install Privacy Badger for Firefox from https://addons.mozilla.org , the author for the add-on under about:addons is "EFF Technologists" like it is for HTTPS Everywhere. However when I install Privacy Badger from https://eff.org , the author is "eff.software.projects@gmail.com". The author should be the same no matter where I install it from.

**Comment by cooperq** [comment]
The authors are required to be different for the self hosted and amo hosted versions. This can not be fixed.

**Comment by jeremyn** [comment]
HTTPS Everywhere seems to have the same author ("EFF Technologists") whether it's installed from AMO or EFF.org.

**Comment by ghostwords** [comment]
Is that because Privacy Badger is WebExtensions and HTTPS Everywhere is still Addon SDK?
