### ISSUE TITLE
Weird bug when refreshing Twitter.

### ISSUE THREAD

**Issue by 0x747972** [EFForg/privacybadger#1337]
Hi,

I've encountered a weird bug when using twitter.com with Firefox (52.0.2) and Privacy Badger.
On every ~second manual refresh of the page a POST-request is send to https://twitter.com/i/jot.
When Privacy Badger is enabled this request never finishes and loads FOR EVAR, thus blocking the loading of the whole site.

Here's data that is posted to https://twitter.com/i/jot. Maybe it is helpful.

```
log=[{"product":"webclient","description":"stats:ajax:perf:swift_home_timeline:polling:success","duration_ms":417,"start_time_ms":1492808800438,"metadata":"{\"url\":\"/i/timeline\",\"browser\":{\"mozilla\":true,\"version\":\"52.0\",\"name\":\"mozilla\"},\"response_size\":59463}","_category_":"perftown"},{"product":"webclient","description":"stats:ajax:perf:swift_home_timeline:polling:success","duration_ms":836,"start_time_ms":1492808800438,"metadata":"{\"url\":\"/i/timeline\",\"browser\":{\"mozilla\":true,\"version\":\"52.0\",\"name\":\"mozilla\"},\"response_size\":126767}","_category_":"perftown"},{"product":"webclient","description":"stats:ajax:perf:swift_home_timeline:polling:success","duration_ms":644,"start_time_ms":1492808800438,"metadata":"{\"url\":\"/i/timeline\",\"browser\":{\"mozilla\":true,\"version\":\"52.0\",\"name\":\"mozilla\"},\"response_size\":236643}","_category_":"perftown"}]
lang=fr
```

cheers,

ryt

**Comment by ghostwords** [comment]
Is this still an issue with Firefox 55?

**Comment by ghostwords** [comment]
I'm going to close this for now.

**Comment by 0x747972** [comment]
Hi, this doesn't seem to be an issue anymore with FF 55.0.2, however in 55 the issue still persisted. I'm not sure it may have something to do with the other plugins/extensions I use.

**Comment by ghostwords** [comment]
Ah, good to know, thank you! This might be related to this Firefox bug, fixed somewhere between Firefox 55 going from beta to stable: https://bugzilla.mozilla.org/show_bug.cgi?id=1373776#c18.
