### ISSUE TITLE
Watching youtube video on Chrome, Windows 7 crashes computer, forces reboot.

### ISSUE THREAD

**Issue by Newgoods** [EFForg/privacybadger#1349]
Hi, I'm not at all sure what the proper form for opening an issue ticket is, so I'll just dump all information that might be relevant. 

Specs:
AMD RX 480 8GB,
i5-2500,
8 gigs of cheap, no-name RAM from 2012
Using Windows 7 Home Premium 64-bit.

My computer hung for about two seconds before rebooting twice before I uninstalled Privacy Badger, which solved the crashing issue. During the first crash, I was watching an hour-long Youtube video while also emulating a game on the Dolphin emulator. During the second, I was just watching the same video without using Dolphin. The computer just froze before rebooting without showing a blue screen.

**Comment by ghostwords** [comment]
Could you try reproducing it again, this time monitoring Chrome's and Privacy Badger's memory use? To watch Privacy Badger memory (and CPU) use, open Chrome's Task Manager (Shift + Esc).

What are the domains that Badger reports on the video page? Does the domain list keep growing?

**Comment by Newgoods** [comment]
That's weird, I can't seem to reproduce it! Memory usage floats around 32000K, CPU 0.0, no crashing after about 10 minutes of watching the video.
These are the trackers I get, which also don't change:

The domains below don't appear to be tracking you

googleads.g.doubleclick.net

pubads.g.doubleclick.net

static.doubleclick.net

www.googleadservices.com

www.googleapis.com

pagead2.googlesyndication.com

www.googletagservices.com

www.google.nl


I'll make another post if it does happen to crash again.

**Comment by ghostwords** [comment]
Sounds good, thank you!
