### ISSUE TITLE
Non existant trackers detected on local html (I think)

### ISSUE THREAD

**Issue by JammyGit** [EFForg/privacybadger#1355]
I'm learning web development so I might just not realize what's going on, but:

background:
I made a html file to go through some w3schools tutorials (htmlpractice2.html).
I'm using a css file for style, no links within either (csspractice.css)
After editing, I'm using firefox to open the files. 
The only addons are Dashlane and Privacy Badger. 

**_issue: Privacy Badger is detecting 12 trackers?_** 

(photo below, including of html file. part of css file is visible but its all text formatting stuff )

I assume its a bug, or else I'm extremely confused. I'm too new to this topic to know for sure. Battery life is also really bad today, draining in 4 hours instead of 10, not sure if related.

Sorry if this is a fake bug, like I said, I'm not sure how to interpret it

<img width="1219" alt="screen shot 2017-04-28 at 7 04 58 pm" src="https://cloud.githubusercontent.com/assets/25443990/25551700/ee7225c4-2c45-11e7-96b9-e4a9919b1440.png">

**Comment by cowlicks** [comment]
Hi @JammyGit from the included html and css, this does seem like a bug... But another possibility is malware, do you think that is possible?

**Comment by JammyGit** [comment]
It's not impossible but it's a macbook that I use almost only for school. I'll test it later today

**Comment by JammyGit** [comment]
Sorry to trouble everyone with a false positive - its a feature, not a bug. Wouldn't have known I had this otherwise.

It was something called Genieo, it apparently gets put inside installers on a few sites like downloaddotcom. This last semester I had to install something for a lab that used one of those sorts of sites to host its files. I wish I could remember what it was.

Sorry again.

**Comment by ghostwords** [comment]
Ah, interesting! Thanks for following up.

**Comment by cowlicks** [comment]
cc @cooperq you might find this interesting. PB inadvertently found some malware on this user's machine.

**Comment by cooperq** [comment]
huh, cool!
