### ISSUE TITLE
cdn.krxd.net blocks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1359]
http://foxbaltimore.com/news/local/federal-judge-agrees-to-repeal-stun-gun-ban-in-baltimore

`cdn.krxd.net` blocks video.

**Comment by terrorist96** [comment]
http://video.foxnews.com/v/5596966803001/?#sp=show-clips

**Comment by terrorist96** [comment]
http://video.foxbusiness.com/v/5627426074001/?#sp=show-clips

**Comment by terrorist96** [comment]
`cdn.krxd.net` still appears blocked (red) for me, but the videos work on the above linked sites.

**Comment by ghostwords** [comment]
That makes sense since I fixed this with a surrogate script: https://github.com/EFForg/privacybadger/blob/c88f2c7b5131175082b44cf2ca105584b1da0210/src/data/surrogates.js#L66
