### ISSUE TITLE
*.akamaized.net breaks stuff

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1360]
https://p.turkishairlines.com/

`www-turkishairlines.akamaized.net` breaks stylesheet

**Comment by terrorist96** [comment]
https://ifunny.co/

`ifwebsite.akamaized.net`

**Comment by ghostwords** [comment]
Are you able to reproduce `akamaized.net` getting counted as a tracker domain (not under "doesn't appear to be tracking you") in a new profile with Privacy Badger installed?

**Comment by terrorist96** [comment]
Yes. I just tried going to some sites noted in the snitch map and eventually *.akamaized.net moved from the `The domains below don't appear to be tracking you` section to the top section. But it is either green or yellow on those pages, not red (at least not yet).

**Comment by ghostwords** [comment]
OK, good to know. If you don't mind, send me the sites where Privacy Badger thinks `akamaized` is a tracker.

**Comment by terrorist96** [comment]
Well, in addition to the two I already posted above, the snitch map reported:
"tesla.com", (though it doesn't seem to be present anymore)
"sonichits.com",
"creditkarma.com"

**Comment by terrorist96** [comment]
https://www.expressvpn.com/

`xvp.akamaized.net`

**Comment by lcdss** [comment]
https://www.themarysue.com/

`21.akamaized.net`
`22.akamaized.net`
`23.akamaized.net`
`24.akamaized.net`

**Comment by terrorist96** [comment]
https://www.gamefaqs.com/

`gamefaqs.akamaized.net` breaks images

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1. Please let me know if you run into it again with the new version.
