### ISSUE TITLE
Pics blocked hosted on *.vinted.net 

### ISSUE THREAD

**Issue by ghost** [EFForg/privacybadger#1366]
Privacy Badger blocks all pics on:
kleiderkreisel.de
vinted.com
vinted.co.uk
vinted.fr
vinted.lt
vinted.pl
vinted.cz
vinted.nl
vinted.es

The pics hosted on vinted.net 
If you manually put this sources to "green" all pics are back.

This websites are broken without pics of the products.
Here is a screenshot
![bildschirmfoto vom 2017-05-05 00-06-48](https://cloud.githubusercontent.com/assets/28412759/25727036/4b470e6e-3127-11e7-93a1-d9e00b0f19ff.png)

**Comment by ghostwords** [comment]
Looks like a job for multi-domain first parties (#781) and another example where #1253 would help.

**Comment by wh1tebeard** [comment]
I have the same issue with images hosted on whitebeardscottage.com that are displayed on one of my other sites, freebeancash.com.  While these images are banner ads, they have no tracking associated with them in any way, and whitebeardscottage.com has the dnt-policy.txt posted in /.well-known/ as well.

**Comment by ghostwords** [comment]
Hi @wh1tebeard, sorry for not responding earlier. If this is still a problem, would you mind opening a new issue for it? It may be another multi-domain first party situation but since it's not about `vinted.net`, it doesn't belong here.
