### ISSUE TITLE
Old profile blocks a lot more trackers then fresh one

### ISSUE THREAD

**Issue by mirh** [EFForg/privacybadger#1369]
Say, if I open https://www.theguardian.com/international with a new profile, only doubleclick and scorecardresearch seems touched at all. 
In my older one instead, over 14 trackers 6 are yellow and 8 are red. 

This is with default settings (ie: no arrow to revert possible further changes is shown)

**Comment by ghostwords** [comment]
This is because Privacy Badger first needs to learn what is and isn't a tracker; the Badger in the older profile knows more than the Badger in the new profile.
