### ISSUE TITLE
static.parastorage.com breaks site

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1372]
https://www.elextracars.com/

`static.parastorage.com` blocks site from loading.

**Comment by terrorist96** [comment]
https://www.xingmobility.com/

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.

**Comment by Nireas01** [comment]
The bug has reappeared. Most sites made with wix.com are broken when static.parastorage.com is blocked completely.
