### ISSUE TITLE
PB triggers grammarly ads

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1373]
See: https://github.com/easylist/easylist/issues/249

ABP blocks the ads (but leaves a placeholder). But if PB is active, the ads will show.

**Comment by ghostwords** [comment]
If I understand correctly, those ABP rules disable "generic" rules and specifically allow a couple of scripts from `pagead2.googlesyndication.com`. Seems like a strange way to avoid seeing a couple of first-party hosted ads.

Privacy Badger doesn't block ads; it blocks tracking. I am not sure there is anything to do here.
