### ISSUE TITLE
*.ooyala.com breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1378]
https://www.dallasnews.com/news/arlington/2017/05/03/two-people-killed-third-wounded-arlington-restaurant-shooting-reports-say

`secure-cf-c.ooyala.com` breaks video.

**Comment by terrorist96** [comment]
http://www.10tv.com/article/mark-kelly-calls-gun-control-columbus

`103835-c.ooyala.com` breaks video.

**Comment by ghostwords** [comment]
We have some Ooyala domains yellowlisted, but not yet these.

**Comment by terrorist96** [comment]
Change it to `*.ooyala.com` on the list?

**Comment by terrorist96** [comment]
http://www.telegraph.co.uk/science/2017/10/13/extreme-horse-breeding-leaves-animals-looking-like-cartoons/

**Comment by terrorist96** [comment]
http://wtvr.com/2018/01/15/mass-shooting-survivor-helps-persuade-senate-panel-to-ban-bump-stocks/

**Comment by terrorist96** [comment]
@ghostwords if I make a PR to add ooyala.com to the yellowlist, will you approve it, since there is precedence for it?

**Comment by ghostwords** [comment]
Probably, I'll have to look into it first though. (I actually already had this issue open in a tab for near-term review.)
