### ISSUE TITLE
Huge PrivacyBadger Like icon

### ISSUE THREAD

**Issue by arieljannai** [EFForg/privacybadger#1379]
I came across [this site](http://www.clalit.co.il/he/your_health/family/cancer/Pages/watching_signs_of_cancer.aspx) and noticed that the social facebook buttons aren't being replace correctly

---

This is how it's being shown:
![image](https://cloud.githubusercontent.com/assets/3811594/25846240/c0250de0-34b9-11e7-9420-60248456064e.png)
---
---

Without PrivacyBadger:
![image](https://cloud.githubusercontent.com/assets/3811594/25846251/d0268430-34b9-11e7-8bbf-50211ebf932c.png)
---

**Comment by ghostwords** [comment]
I'll mark this as another example of #890.

**Comment by arieljannai** [comment]
Yep, looks similar 👍 
Haven't found that issue myself.
