### ISSUE TITLE
*.hgmsites.net breaks images

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1380]
http://www.motorauthority.com/news/1109906_mg-e-motion-electric-sports-car-concept-revealed-could-be-production-bound

`images.hgmsites.net` and `static.hgmsites.net` breaks images

**Comment by terrorist96** [comment]
http://www.greencarreports.com/news/1110599_nissan-electric-suv-to-be-shown-as-concept-car-this-year

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.
