### ISSUE TITLE
cdn2.editmysite.com & www.weebly.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1383]
http://grrrgraphics.com/index.html

Scroll down and click an image under the PayPal donate button.
`cdn2.editmysite.com` blocks image slideshow.

**Comment by terrorist96** [comment]
Also breaks store layout.
http://grrrgraphics.com/store.html

**Comment by ghostwords** [comment]
It looks like the website doesn't use Weebly at this point.

**Comment by terrorist96** [comment]
https://www.weebly.com/

@ghostwords reopen please.

**Comment by ghostwords** [comment]
`weebly.com` being broken (#704) will be fixed by #1831.

**Comment by terrorist96** [comment]
> http://www.douksnow.com/ `www.weebly.com` breaks the last video

This is still true. Reopen please.
