### ISSUE TITLE
Privacy Badger Download for Firefox Redirecting to Broken Link

### ISSUE THREAD

**Issue by naltun** [EFForg/privacybadger#1384]
When visiting the [Privacy Badger site](https://www.eff.org/privacybadger), I click on `Install Privacy Badger And Enable Do Not Track`, and get redirected to https://s.eff.org/files/privacy-badger-latest.xpi, a broken download link. I get a "Server Not Found" error.

I fixed this by removing the `s` subdomain from `eff.org`, and it worked, successfully installing Privacy Badger for Firefox.

Inspecting the download button element, I get this:
![image](https://cloud.githubusercontent.com/assets/7507990/26070035/f9b7dc5a-399a-11e7-9622-d49e8c535760.png)

I'm not sure if this issue can be reproduced, and/or why it redirects to a link that is not working for me.

**Comment by ghostwords** [comment]
Thanks for the report! We should get this fixed shortly.

**Comment by naltun** [comment]
I'd be interested in knowing what caused the issue, if possible. :) Just for educational reasons. Always something new to learn.

**Comment by ghostwords** [comment]
There was an `eff.org` redesign; looks like it introduced some bugs somehow.

**Comment by ghostwords** [comment]
This should be sorted by now.
