### ISSUE TITLE
img.shields.io blocked

### ISSUE THREAD

**Issue by strugee** [EFForg/privacybadger#1394]
Over in strugee/gplenforced.org#7 I have a user reporting that Privacy Badger is blocking `img.shields.io`. This seems like something that shouldn't be blocked, given that it's an image in the page.

I thought about sending a PR adding `img.shields.io` to the no-cookie whitelist, but maybe it's better for this to be determined heuristically.

**Comment by ghostwords** [comment]
@ian-kelling Which version of Privacy Badger do you have?

If you visit `chrome://settings/cookies`, and search for "shields.io", how many cookies does it show? For example, I have a single "__cfduid" cookie.

**Comment by ian-kelling** [comment]
I don't use chrome, in firefox I also have a single "__cfduid" cookie when searching for shields.io in the remove cookies dialog.

Privacy badger version in firefox is 2017.5.9

**Comment by ghostwords** [comment]
This should be fixed by #1237. I'm guessing your Badger learned to block `shields.io` before the fix was released. You should unblock it manually for yourself, if you haven't already. Let me know if you run into something like this again with Privacy Badger.
