### ISSUE TITLE
Privacy badger blocked domains before they could say they DNT

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/privacybadger#1397]
I will try to find simple steps to reproduce this issue but when I visited [this website](https://troisiemebaobab.com/), the layout was completely messed up.

I suspected it was due to privacy badger blocking `cdn-images-1.medium.com` and `cdn-static-1.medium.com`.

To test this hypothesis before filing an issue, I disabled privacy badger and everything looked fine.

But to my surprise, when I re-enabled privacy badger, the first party still looked fine and `cdn-images-1.medium.com` and `cdn-static-1.medium.com` were now tagged as `DNT`.

I am suspecting they were blocked before they could be contacted to see if they respect DNT. Is that possible?

**Comment by ghostwords** [comment]
Yep, that's what I think happened; Privacy Badger didn't know the domains were DNT-compliant and decided to block them without waiting for the DNT policy check to come back. We should handle this better at some point.

**Comment by terrorist96** [comment]
I can reproduce.

**Comment by cowlicks** [comment]
I could not reproduce this with the 2017.5.9 release :/

**Comment by Bisaloo** [comment]
Maybe it's actually a case of https://github.com/EFForg/privacybadger/issues/1398? I cannot say whether this domain was already blocked before visiting the test webpage or not.

Would that explain the fact that you can't reproduce?
