### ISSUE TITLE
Non-tracking DNT domains are shown as trackers in the popup

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1405]
For example, a third-party image sourced from `eff.org`:

![screenshot from 2017-05-31 17 33 00](https://cloud.githubusercontent.com/assets/794578/26655075/36de7268-4627-11e7-9775-237c2f66759f.png)

I expected the `eff.org` domain to be shown in the "The domains below don't appear to be tracking you" section instead, as it doesn't seem to conduct any actual tracking. DNT-declared domains that do seem to perform tracking should indeed be displayed in the "trackers" section.

**Comment by cowlicks** [comment]
I think the domains are ordered by: DNT first to promote DNT and make the user aware of it, next are the tracking domains, finally the domains where we haven't seen any tracking. 

I don't think we should reorder the domains, so maybe we should remove the "domains below here don't seem to be tracking". It is just confusing since there are also deliberately domains above it that "don't appear to be tracking".

**Comment by cowlicks** [comment]
Also, another bug show here eff.org should not be counted as a "potential tracker" in the popup.

**Comment by ghostwords** [comment]
I can look at this after we are done with next week's update.

**Comment by ghostwords** [comment]
>Also, another bug show here eff.org should not be counted as a "potential tracker" in the popup.

Yep, that's the title of this bug report.

**Comment by cowlicks** [comment]
Oh! Sorry, I just wanted to make the distinction: there are two bugs here.
* dnt domains are counted in the "PB detected X potential trackers" section
* dnt domains are shown above the "domains below here don't appear to be tracking you" div (a UI issuse).

#1421 fixes the first point. And it addresses the second point by removing div completely. I'm open to suggestions about a better way to fix the UI issue. Maybe better wording?

**Comment by ghostwords** [comment]
#1641 is a related DNT domain counting bug, this time with the badge.
