### ISSUE TITLE
storage.googleapis.com blocks images

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1409]
https://blog.google/topics/journalism-news/building-better-web-everyone/

`storage.googleapis.com` blocks images

**Comment by terrorist96** [comment]
https://support.google.com/chrome/answer/95426?visit_id=1-636325802803357469-2072857663&p=settings_omnibox&rd=1

**Comment by terrorist96** [comment]
http://allwomenstalk.com/

Breaks layout.

**Comment by ghostwords** [comment]
Should make sure `googleapis.com` and `google.com` are in [multi-domain first-parties](https://github.com/EFForg/privacybadger/issues/781).

**Comment by ghostwords** [comment]
Oh, [they are](https://github.com/EFForg/privacybadger/blob/0760b82730fe06d229a9866b3c5e270e48f0fd18/src/js/multiDomainFirstParties.js#L21)! I wonder why your Badger is blocking `googleapis.com` on `google.com` then.

**Comment by terrorist96** [comment]
Yeah. Just tested it with the latest version and it still defaults to red on the reported sites.

**Comment by ghostwords** [comment]
Oooh the first report is not on `google.com`, it's on `blog.google`. That's right, they bought their own TLD.

**Comment by ghostwords** [comment]
Should probably add `storage.googleapis.com` to the yellowlist, to join [other `google.com` domains](https://github.com/EFForg/privacybadger/blob/0760b82730fe06d229a9866b3c5e270e48f0fd18/doc/sample_cookieblocklist.txt#L201-L234).

**Comment by terrorist96** [comment]
https://www.google.com/maps/place/United+States+Postal+Service/@55.919151,-130.029778,3a,75y,90t/data=!3m8!1e2!3m6!1s132578867!2e1!3e10!6s%2F%2Flh4.googleusercontent.com%2Fproxy%2FIBWUtugWA7H6Rk5dsyVhrHBOxA4qX70KjVBJr8CXxJnlAnv01aeRiTnjrMlEaQSRHc6oui0_X4CEBF8-ujl2puCtQ7VuU0c%3Dw203-h134-k-no!7i1024!8i680!4m12!1m6!3m5!1s0x540bce365c701e45:0x40ad6983e4d64104!2sUnited+States+Postal+Service!8m2!3d55.9221194!4d-130.032719!3m4!1s0x540bce365c701e45:0x40ad6983e4d64104!8m2!3d55.9221194!4d-130.032719?hl=en-US

`static.panoramio.com.storage.googleapis.com` blocks image

**Comment by terrorist96** [comment]
https://code.google.com/archive/p/vlc-libcad/wikis/Installation.wiki
