### ISSUE TITLE
Strip __cfduid cookies from headers.

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1419]
Currently when we encounter a cookie with a `__cfduid` name we, we ignore it. We can't block these since they are coming from cloudflare and that would break everything.

Instead we should try stripping just the `__cfduid` cookie from the headers, leaving the others.

**Comment by ghostwords** [comment]
This seems like extra processing of headers (expensive) for questionable gain.

**Comment by cowlicks** [comment]
@ghostwords from cloudflare's [cookie policy](https://www.cloudflare.com/cookie-policy/) it seems like they are using them to track people. We already calculate the entropy of all 3rd party cookies, I don't think matching a cookie name will add much overhead. It should be O(1).

**Comment by cowlicks** [comment]
Actually we are already matching the `__cfduid` cookie, so the added work is just deleting it.

**Comment by ghostwords** [comment]
Cloudflare says `__cfduid` cookies are for security purposes only: https://support.cloudflare.com/hc/en-us/articles/200170156-What-does-the-Cloudflare-cfduid-cookie-do-.

Stripping the cookie from the headers would be extra work on every request.

**Comment by cowlicks** [comment]
I don't read that as cloudflare uses the cookie "for security purposes only", it reads to me like they use it for security, but there is nothing there that limits what they may do with the cookie.

**Comment by cowlicks** [comment]
Cloudflare no longer sets the `__cfduid` cookie on browsers who send the DNT header.

**Comment by cowlicks** [comment]
Reopening, I don't think we can remove this code because if the cookie is set before us, then then we will still detect it is as tracking.

**Comment by cowlicks** [comment]
We could clear them on startup with something like:
```javascript
chrome.cookies.getAll({'name': '__cfduid'}, cookies => {
    cookies.map(cookie => {
        chrome.cookies.remove({url: 'https://' + cookie.domain + cookie.path, name: '__cfduid'});
    });
});
```

**Comment by phishen** [comment]
Was this fixed by https://github.com/EFForg/privacybadger/commit/a88a1eb99f7d81613bad1c194c1d84f3e81ca17e ?

**Comment by ghostwords** [comment]
No, that was a migration to forget domains that Privacy Badger probably shouldn't have learned to block.

**Comment by ghostwords** [comment]
Removing Cloudflare security headers doesn't seem worthwhile at this time.
