### ISSUE TITLE
Don't access shared resources in a non-threadsafe way.

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1423]
We have the `badger.tabData` data structure that we use to conveniently access and store information about tabs. However we are accessing `tabData` without any guarantees of threadsafety, so the information in tabData may be missing or incorrect.

More info from another thread:
... about `badger.tabData`: we're using it to store and share information about tabs and frames. And we are doing all of this asynchronous stuff in webrequests that reads and writes to `tabData` without any guarantee of thread-safety. For example [here](https://github.com/EFForg/privacybadger/blob/5a3f4475204033c0f25ccdd89100c4262e19e474/src/js/webrequest.js#L377-L389) in `webrequest.recordFingerPrinting`, we call `getFrameUrl`, which calls `getFrameData` which checks `badger.tabData` for the URL. But between the time the request triggered `recordFingerPrinting`, the tab URL in `tabData` could have changed, or the tab could have been removed from `tabData`. This could possibly cause us to misattribute the fingerprinting to the wrong origin, or no origin at all.

To fix this, each webrequest action should be as [atomic](https://en.wikipedia.org/wiki/Linearizability) as possible, and depend on as little shared state as possible. Some shared state is unavoidable, like the score against a tracker. 

But there are plenty of low hanging fruit here. We could easily avoid accessing `tabData` in `recordSuperCookie` and `recordFingerPrinting` since the information we want (the url and frame id) are already in the `details` object that we get for every request. Once we do this, we could remove the `getFrameData` and `getFrameUrl` functions completely.

also follows up on #1408

**Comment by ghostwords** [comment]
This is following up on #1403.

**Comment by ghostwords** [comment]
If only per-tab data storage was an extension API! Here is an old crbug asking for this: https://crbug.com/37671.

**Comment by cowlicks** [comment]
This was investigated in #1425 

I found that the api through which we're accessing `tabData` is mostly safe. Closing.
