### ISSUE TITLE
Get a badger emoji added to Unicode

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1433]
http://unicode.org/emoji/selection.html
![privacy-badger-sq2](https://user-images.githubusercontent.com/598099/27110759-63e269ca-5060-11e7-8662-d34c7ec14156.png)

**Comment by ghostwords** [comment]
Here is the proposal guidelines doc: http://unicode.org/emoji/selection.html. I don't think this needs to be on the Privacy Badger issue tracker though.
