### ISSUE TITLE
static.geetest.com and api.geetest.com is blocked as an verification code service

### ISSUE THREAD

**Issue by l5h5t7** [EFForg/privacybadger#1440]
Page: https://passport.bilibili.com/login
Verification code can't be loaded.
Move their button to middle (block cookies) can load them, but can't pass the verification.

**Comment by ghostwords** [comment]
If I understand correctly, `geetest.com` is a CAPTCHA provider potentially used across many different domains, and "yellowlisting" their domain also breaks their service.

Would Geetest be able to adopt the [EFF Do Not Track policy](https://www.eff.org/dnt-policy)? If they can and will abide by the policy's requirements, posting the policy on their domains will tell Privacy Badger to allow loading of resources from those domains.

**Comment by ghostwords** [comment]
Seeing an uptick in blocked/userallowed/usercookieblocked "geetest" reports:
```
+---------+-------+
| ym      | count |
+---------+-------+
| 2019-02 |    15 |
| 2019-01 |    15 |
| 2018-12 |     4 |
| 2018-11 |     9 |
| 2018-10 |     8 |
| 2018-09 |     6 |
| 2018-08 |     5 |
| 2018-07 |     5 |
...
```
