### ISSUE TITLE
[Chrome] Options page unscrollable and links broken

### ISSUE THREAD

**Issue by lucky-guess** [EFForg/privacybadger#1441]
The "Options" page is unscrollable in chrome. Zooming in or out doesn't affect the problem. The links to User Filter Settings, Whitelisted domains, General Settings and Manage Data either do nothing or link to an unrelated place in the page.

**Comment by ghostwords** [comment]
Which versions of Chrome and Privacy Badger do you have? Is this is a new install or did this happen to a previously working Badger installation?

If you open the JavaScript console on Badger's options page, do you see any errors there? To open the JS console, click on Chrome's menu button, expand More Tools, click on Developer tools and then select the Console tab.

**Comment by ghostwords** [comment]
Closing for now. Let me know if this is still an issue.
