### ISSUE TITLE
Translation issues with "Privacy Badger detected X potential trackers"

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1443]
The `popup_instructions` message is problematic in a couple of ways right now:
- It doesn't handle languages that treat singular and plural words differently (such as English, for example ... "1 potential trackers").
- Since it translates the second half of a broken-up sentence ("Privacy Badger detected", "X potential trackers ..."), it doesn't handle languages that don't break down sentences the same way. `pb_detected` has the same issue as the first half of this sentence.

**Comment by ghostwords** [comment]
Related: #1329

**Comment by ghostwords** [comment]
While the message above concerns Badger's browser popup, a closely related issue exists on the options page, where "Privacy Badger has detected XXX potential tracking domains so far." is stitched together from five (!) separate messages:
```html
        <span class="i18n_options_pb_has_detected"></span>
        <span id='count'>0</span>
        <span class="i18n_options_potential"></span>
        <a target=_blank tabindex=-1 title="What is a tracker?" href="https://www.eff.org/privacybadger#faq-What-is-a-third-party-tracker?"><span class="i18n_options_tracking_domains"></span></a>
        <span class="i18n_options_so_far"></span>
```
The proper approach would be to replace all of these sentence fragments with a single message that uses placeholders to try to handle different grammatical sentence orders and pluralization.

**Comment by cowlicks** [comment]
I think we can avoid pluralization issues in this case and probably in the options page, by presenting the number as data, instead of as an adjective/quantifier thing. So instead of:

> Privacy Badger detected 0 potential trackers on this page. 

we can just say something like:

> detected trackers: 0

This reads better because it is not read as a grammatical/spoken sentence.
