### ISSUE TITLE
Stop recording no-tracking-detected third-party domains

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1446]
We currently record non-tracking third-parties in `action_map` (with `heuristicAction` of `""`). We should keep showing these third-party resources in the popup for now, but if that's the only place we actually use these entries, they don't need to be persisted. (The code might not use `action_map` directly in the popup, so removal might be easy.) Should do a migration to clean up existing entries.

Should help a little with performance, mitigate #1318, address part of #1064. Obsoletes #1339? Related earlier issue: #990. Might also take care of #888, at least for both known cases.

**Comment by ghostwords** [comment]
We should handle the case of a user deciding to block or cookieblock one of these domains in the popup. May already be fine, just noting.

**Comment by ghostwords** [comment]
Should non-tracking DNT-compliant domains be persisted?

**Comment by cowlicks** [comment]
@ghostwords Yes I think non-tracking DNT domains should be persisted.

Work on this is ongoing here https://github.com/EFForg/privacybadger/compare/master...cowlicks:stop-tracking-no-tracking-domains-lol
