### ISSUE TITLE
Blank domain on Badger's options page

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1447]
![screenshot from 2017-06-20 17 04 52](https://user-images.githubusercontent.com/794578/27356012-fa057706-55da-11e7-9cb4-44bc23cfb20b.png)

The blank domain appears to come from JavaScript writing "high entropy" localStorage inside an `about:blank` iframe on `sfgate.com`. When [`msg.docUrl` is "about:blank", `extractHostFromUrl` returns an empty string](https://github.com/EFForg/privacybadger/blob/0760b82730fe06d229a9866b3c5e270e48f0fd18/src/js/webrequest.js#L359), which is how we record an `action_map` entry for `""`.

According to `git bisect`, this was introduced in 4911760c15ce2bb54b2cae597ecd722e7cee40dc (localStorage tracking detection refactor).

Unable to reproduce in Chrome. Maybe because of differences in WebExtensions implementations, maybe because the website serves different content/does different stuff for different browsers.

**Comment by ghostwords** [comment]
Ah OK, before the refactor, we'd run into this `about:blank` localStorage thing and store `{"":true}` in `supercookie_domains`, but that would never match any `chrome.webRequest` request domains.

**Comment by ghostwords** [comment]
So if this is first-party storage (`about:blank` iframe on `sfgate.com` writing localStorage data for `sfgate.com`), we should be ignoring it.

**Comment by ghostwords** [comment]
According to the [MDN same-origin policy doc](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#Inherited_origins), `about:blank` (and `javascript:`) frames inherit the origin of the document that opened the URL. So, `about:blank` frames could be first-party and they could be third-party (when created by a third-party iframe).

It seems we need to special-case for `about:blank`, using the first non-`about:blank` parent frame's URL as/instead of `msg.docUrl`.

**Comment by Jsnhlbr5** [comment]
I'm not sure how to go about setting up a test page, particularly how to get multi-domain hosting set up.

I'm doing research into where in the code this would best be fixed; if it gets handled in onBeforeRequest, causing badger.recordFrame to record the parent url (or maybe just the host?), would that solve the problem?  It seems like the only place we'd run into this, and the easiest one to fix (we have the parent frame id handy), but I'm not 100% confident that I'm correct in this analysis.

**Comment by ghostwords** [comment]
Take a look at how the existing tests work in `super_cookie_test.py`. You should be able to adapt the fixture used for testing successful detection for our purposes (make it generate one or more nested `about:blank` frames).

Regarding code paths, cookie tracking detection and "super cookie" (HTML5 local storage) tracking detection work in different ways. I think you should start by looking at `recordSuperCookie()` and how we get there.
