### ISSUE TITLE
[Firefox] Privacy Badger breaks go-giteas "Assign user to issue" feature

### ISSUE THREAD

**Issue by schmittlauch** [EFForg/privacybadger#1448]
see also go-gitea/gitea#2021

## How to reproduce

**Preparation:**

1. Create a fresh Firefox profile (here: 54.0 64bit Linux)
1. Install PrivacyBadger (from https://www.eff.org/privacybadger , current version: 2017.6.13.1)
1. Create an account on https://try.gitea.io/ (or any other other gitea instance, currently v1.1.2)
1. Create a new repository and populate it with default files
1. Open a new issue

**Issue:**

1. Click on the *Assignee* gear and assign a user to this issue (probably yourself)
1. Disable Privacy Badger, restart Firefox and repeat

**Intended behaviour:** User gets assigned to the issue

**Actual behaviour:** After clicking on the user to assign, the website just reloads without assigning the user.

This happens even when PrivacyBadger is disabled for this particular page.
The same symptoms appear when the add-on *FoxyProxy Standard Edition* is active.

**Comment by ghostwords** [comment]
Is this an issue if you go through the steps in a fresh profile loaded with only the following test add-on? https://github.com/EFForg/privacybadger/files/1079120/firefox_webext_onunload_bug_demo.zip

To load the above add-on in Firefox, unzip the archive somewhere, visit about:debugging, click on Load Temporary Add-on, and pick the manifest.json file inside the unzipped folder.

**Comment by schmittlauch** [comment]
No, with this test add-on in a fresh browser profile the bug does not appear. Everything works as intended.

Btw, I discovered that the Disconnect add-on causes the same issue.

**Comment by ghostwords** [comment]
Ah OK, thanks for checking. Must be some other bug with WebExtensions. Sounds similar to #1295.

**Comment by schmittlauch** [comment]
I'm not really good with client-side javascript and events, but probably the gitea website is also just cooking up jquery for this feature.

**Comment by schmittlauch** [comment]
Skimming through #1295 these breakages aren't reproducible with a fresh FF profile and just PB installed. But this issue is reproducible in that way.

**Comment by schmittlauch** [comment]
Does PrivacyBadger do something against hidden input fields?

**Comment by ghostwords** [comment]
> Does PrivacyBadger do something against hidden input fields?

I don't think so, but I am not sure what you mean ... Could you explain?

**Comment by schmittlauch** [comment]
I'm not really good with front-end javascript stuff, but I noticed that gitea first writes the assignee into a hidden input form and that posts that. I thought maybe hidden input fields may be a commonly used tracking method and thus (sometimes) blocked.

I hope somebody from gitea can look into where the usual/ supposed control flow breaks. I guess this information can be helpful for debugging this issue.

**Comment by ghostwords** [comment]
Does this bug happen in Chrome as well, or only on Firefox?

**Comment by schmittlauch** [comment]
No, it works fine in Chromium with latest PrivacyBadger version.

My theory is laso flawed by the fact, that disabling PB in Firefox for this particular website didn't fix the issue.

**Comment by ghostwords** [comment]
OK, makes sense. Thanks for checking! This to me strongly seems like a Firefox WebExtensions bug. The next step would be to figure out which part of the add-on (maybe some part of listening to requests via `chrome.webRequest`) is responsible for triggering this issue, making a demo add-on to illustrate the issue, and filing a Mozilla Bugzilla bug. It would help to have a more easily reproducible website test case.

**Comment by schmittlauch** [comment]
I'll let you know when I have more information on where things go worng on the website.

**Comment by ghostwords** [comment]
This might be fixed now that Firefox 55 reached stable.

**Comment by ghostwords** [comment]
I'm going to close this for now; let me know if this is still an issue.

**Comment by schmittlauch** [comment]
> This might be fixed now that Firefox 55 reached stable.

The issue still exists when using FF 55, but gitea decided to fix this on their own side so it should be ok to close this.

It's still weird that the bug appeared only when PrivacyBadger was enabled, but didn't appear without it.
