### ISSUE TITLE
*.zendesk.com breaks site

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1449]
https://wikibuy.com/help

`wikibuy.zendesk.com` breaks search results

**Comment by ghostwords** [comment]
Could you include your `snitch_map` entries for the blocked third-party domain in these tickets, when you feel comfortable sharing them?

Here is the JavaScript to run on Badger's background page to get this info (just replace DOMAIN in the second line with the top-level portion of the third-party domain in question, "zendesk" in this case):
```javascript
(function () {
  const STR = "DOMAIN";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

**Comment by terrorist96** [comment]
What went wrong? Maybe the `_` at the beginning of `.each`? Tried both `zendesk.com` and `zendesk`
![image](https://user-images.githubusercontent.com/12802056/27415251-080d5860-56d4-11e7-8eb3-6b4da384fc6f.png)

Also, should I retain this code for the future and not use the previous ones:

>chrome.storage.local.get(['snitch_map'], r => { for (const key in r.snitch_map) { if (key.indexOf('amazonaws.com') != -1) { console.log(key, ":", r.snitch_map[key].join(', ') ); } } } );

>(function () {
  const STR = "pubnub.com";
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());

And do you want a snitch map for every issue from now on?

**Comment by ghostwords** [comment]
I think you ran the code somewhere else, not on Badger's background page. To get to the background page, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

**Comment by ghostwords** [comment]
> And do you want a snitch map for every issue from now on?

Yes please, whenever you are OK sharing it. Eventually we'll have this info available in Badger's UI (#1289).

**Comment by ghostwords** [comment]
The previous code snippets are just differently worded versions of the same thing. The latest code also prints out the "action map" (which may or may not be useful for debugging, not sure yet).

**Comment by terrorist96** [comment]
You're right, I had inputted it in the inspect popup screen instead of the background page, thinking they were the same thing.
![image](https://user-images.githubusercontent.com/12802056/27445587-45afc27e-5748-11e7-9a17-cc605c290324.png)

**Comment by StephenHinck** [comment]
FYI - looks like this issue is still ongoing.

**Comment by ghostwords** [comment]
Yep, sorry, I'll get back to site breakages soon. This one is high on my list.

**Comment by StephenHinck** [comment]
No problem! Completely understood and appreciated!


*Stephen Hinck*Sr. Technical Account Manager

I   C   E   B   R   G
Mobile  +1 858-444-7983
stephen@icebrg.io | https://icebrg.io

All information in this email, email string, or attached to this email is
intended, privileged and confidential for the named addressee(s) only. If
you recognize you were not the intended recipient of this message, please
notify the sender by phone or email and delete the original message and all
attachments.

**Comment by terrorist96** [comment]
https://www.xfinity.com/mobile/support/
`assets.zendesk.com` and `comcast.zendesk.com` blocks chat link at bottom.
