### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by ghost** [EFForg/privacybadger#1458]
We'll need to add a code of conduct when the EFF lawyers will finish writing one.

See also EFForg/https-everywhere#10724, certbot/certbot#4841.

**Comment by koops76** [comment]
@andresbase Any progress?

**Comment by andresbase** [comment]
Still in review, will update when it's confirmed.

**Comment by koops76** [comment]
@andresbase But, is it drafted? I would like to give comments to a draft.

**Comment by koops76** [comment]
@andresbase Is this still alive?

**Comment by andresbase** [comment]
Yes, still with the lawyers.

**Comment by koops76** [comment]
@andresbase I would ask the lawyers to make the code of conduct protect both the EFF and the contributors from legal liability in case of failure to follow and/or enforce the code of conduct. Also I would like the lawyers to create a public article on EFF website describing the problems with currently existing codes of conduct and why creating a new one was neccessary. Finally, I would like the code of conduct to be licensed under Creative Commons or similar license and be easily applicable to projects of any scale, from a personal project with a few external contributors to a large project with hundreds of contributors.

**Comment by koops76** [comment]
@andresbase Any updates?

**Comment by koops76** [comment]
@andresbase Hey?

**Comment by andresbase** [comment]
@koops76 sorry for that but it still in review. I would like to have it ASAP but we still have to wait.

**Comment by ghostwords** [comment]
Done in #2349.
