### ISSUE TITLE
How does blocking 3rd party cookies on the browser affect Privacy Badger?

### ISSUE THREAD

**Issue by jawz101** [EFForg/privacybadger#1460]
Sorry to put this as an issue.  I didn't know how to ask.  It would be nice if there was a wiki with FAQ's, but this seems like a fundamental question since all/most browsers let you block 3rd party cookies by default.  Like, I always change that setting and have never had any site break - ever.

Right now I still use PB along with other blocking apps as more of a catch-all to things I'm already blocking.  Consequently, PB doesn't really do much except let me see how the project is developing.

**Comment by ghostwords** [comment]
Great question! We do have an FAQ on [Badger's homepage](https://www.eff.org/privacybadger), but this isn't answered there yet.

Privacy Badger shouldn't be affected by blocking third-party cookies in your browser. Even though cookies from third-party domains get rejected, third parties still try to set cookies, which Privacy Badger gets to see and learn from.

**Comment by ghostwords** [comment]
Also note that cookies are one of many ways you can be tracked across the Web. For Privacy Badger, this means cookies are one of a few ways Badger learns which domains track you across the Web. At the moment, Privacy Badger also looks at localStorage-based tracking, and tries to detect canvas fingerprinting. This list should grow in the future.

**Comment by jawz101** [comment]
Thanks.  I guess my concern/question was if the 3rd cookie was being blocked at the browser level that the heuristics wouldn't get a chance to see at the Privacy Badger level.  From what you're saying, PB would still see that a 3rd party cookie did happen.

For some reason I remember an old version of BP that did say "Hey, it looks like you're blocking 3rd party cookies.  Turn that off so we can process them"  or something.

**Comment by ghostwords** [comment]
Yep, that sounds like an old feature of Privacy Badger for Firefox.

**Comment by ghostwords** [comment]
Let's see if this comes up again, may want to update the website then.

**Comment by jawz101** [comment]
Perhaps the github wiki could answer some of slightly more technical questions about the heuristic engine.

**Comment by ghostwords** [comment]
Sounds good, updated the wiki with a few Q&As: https://github.com/EFForg/privacybadger/wiki

**Comment by cowlicks** [comment]
@jawz101 Privacy Badger also replaces some social media buttons (widget replacement), and common tracking/analysis scripts (script surrogates). But this is currently pretty limited.

**Comment by jawz101** [comment]
Sweet!  Thanks, you two.  I find it admirable you all are so interested in sharing
