### ISSUE TITLE
ajax.googleapis.com breaks dropdown menu

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1464]
https://www.ebi.ac.uk/pdbe/entry/pdb/1YWH

`ajax.googleapis.com` breaks the dropdown menu when clicking "View" or "Downloads" links.

**Comment by terrorist96** [comment]
https://www.ebi.ac.uk/pdbe/entry/search/index?biological_cell_component:%22extrinsic%20component%20of%20membrane%22

Blocks search results.

**Comment by terrorist96** [comment]
https://www.ebi.ac.uk/pdbe/entry/pdb/1ywh/analysis#assembly_1

More images being blocked here as well.

**Comment by ghostwords** [comment]
Could you restart the browser and check if this is fixed? I made a [yellowlist update yesterday](231cd4ec7abef8109f142b93551aeb5be1660ef4) that had unintended consequences. I should have fixed it later in the day with [another update](e9e5c20cd84de0b3b44e27c8e4b63e0c64d2a807).

**Comment by terrorist96** [comment]
Looks to be fixed. Thanks!
