### ISSUE TITLE
UI broken (not everything is visible)

### ISSUE THREAD

**Issue by vi** [EFForg/privacybadger#1465]
![privui](https://user-images.githubusercontent.com/173219/27732826-d14beb88-5d9b-11e7-93ea-3a6efcf3a7b2.png)

UA: Firefox version 52.1.1 on Linux.

**Comment by wolf6243** [comment]
I've got the same problem with Firefox (x64) v54.0.1 and Waterfox (x64) v54.0.0.1. It's been like this for months, just wish they'd fix it.
![privacy badger - broken](https://user-images.githubusercontent.com/18146947/27734816-92d50260-5d94-11e7-9efb-9f43da9d69df.jpg)

**Comment by ghostwords** [comment]
@vi Your issue (using "Move to Menu" in Firefox) is being tracked in #1120. To work around the problem for now, restore Privacy Badger's icon to the toolbar.

**Comment by ghostwords** [comment]
@wolf6243 Could you open a new issue for your problem please? I would move your comment into an issue myself, but GitHub doesn't support that.
