### ISSUE TITLE
Investigate NULL block/cookieblock/... broken site/error report submissions

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1475]
Many error reports have NULL block/cookieblock/... domain state fields. Let's find and fix what's causing this to happen.

A related issue is that we get a lot of nonsense message ("test", "banana", ...) reports. Do the nonsense reports always have NULL domain state fields? Are NULL field reports always nonsense?

**Comment by cowlicks** [comment]
This is from user's reporting broken sites when the have the page disabled.
