### ISSUE TITLE
Privacy Badger breaks Duolingo

### ISSUE THREAD

**Issue by WandersFar** [EFForg/privacybadger#1476]
Privacy Badger breaks Duolingo, a popular language-learning site. Could you look into this please?

**Comment by PercussiveElbow** [comment]
What exactly do you mean by it being broken? I'm not seeing any immediate issues on my browser, the only domain being outright blocked for me is api.mixpanel.com and it does appear to be tracking.

**Comment by WandersFar** [comment]
I mean the page doesn’t load at all. I’ve had to whitelist the Duolingo domain to get the site working again.

**Comment by ghostwords** [comment]
Hello! What is the URL of the page you are running into issues on? Could you share the domains that Privacy Badger reports as blocked on the page? Feel free to post screenshots if that's easier.

**Comment by ghostwords** [comment]
I'm unable to reproduce Duolingo not loading at this time but I do see plenty of reports of users unable to sign in via Google. We're tracking that issue in #137.

To sign in via Google, you can move the slider for `accounts.google.com` to "green" and reload the page, or you can click on the "Disable for this site" button in Privacy Badger popup. Either one will let you sign in; the difference is between allowing all tracking on a single site vs. keeping Privacy Badger active on the site but allowing `accounts.google.com` to track you everywhere on the Web.
