### ISSUE TITLE
Ability to edit disabled site entries

### ISSUE THREAD

**Issue by plaguedemons** [EFForg/privacybadger#1484]
I should be able to edit an entry in the whitelist, instead of having to manually reenter it, and then delete the more specific one.

![image](https://user-images.githubusercontent.com/10558829/28093188-17175cda-664b-11e7-8972-68e92d1a677c.png)

**Comment by ghostwords** [comment]
Could you describe why you find yourself needing this? Like, what website were you on, and what made you realize you needed to whitelist something other than the (sub)domain you were on?

**Comment by plaguedemons** [comment]
When I click the button **Disable Privacy Badger for This Site**, Privacy Badger adds the specific domain to the Whitelist, like **specific.bankingsite.net**.  I want it to be more general and I want to change it to ***.bankingsite.net**.  Maybe I want to copy and paste part of another site name into the whitelist.  The whitelist needs to be more editable than it currently is.  It should not be difficult to edit the list.

**Comment by ghostwords** [comment]
Cool, could you expand on "I want it to be more general"? What circumstances led you to need to whitelist the parent domain, while not navigated to the parent domain?

**Comment by ghostwords** [comment]
This issue needs more information. I am going to close for it now, happy to reopen later.

**Comment by cowlicks** [comment]
@ghostwords would you mind if I re-opened this? I think I understand what they are asking for, and it seems reasonable to me.

**Comment by ghostwords** [comment]
Could you outline a scenario that necessitates this?

**Comment by cowlicks** [comment]
It sounds like this would be useful in the scenario @plaguedemons outlined above:
* They visit some origin `specific.bankingsite.net` and whitelist it.
* Then they want change `specific.bankingsite.net` to `*.bankingsite.net`

Currently they have to:
* select `specific.bankingsite.net` and remove it
* add `*.bankingsite.net`

I think they are asking for the ability to edit entries in-place.

**Comment by ghostwords** [comment]
What I'm missing, is why you would need to change "`specific.bankingsite.net` to `*.bankingsite.net`". As I asked above, what circumstances led you to need to whitelist the parent domain, while not navigated to the parent domain?

**Comment by plaguedemons** [comment]
Because I am a user of the software. If I need this functionality, you can bet a lot of other users will too. When I developed software, I found that users figured out ways to do things I had not anticipated. Now I am the user and I feel this functionality is needed. You may have a specific way you want me to use the software, but I am using it slightly differently than you have anticipated. It will be more functional and appeal more to others if you can accommodate this simple change.  Adguard allows me to edit my whitelist (see attached).

![adguard](https://user-images.githubusercontent.com/10558829/29583860-ad431cec-8736-11e7-8599-da4ba652a6d2.jpg)

**Comment by ghostwords** [comment]
I understand you would like to have this functionality.

The reason I ask to explain what circumstances led you to need to whitelist the parent domain, while not navigated to the parent domain is I need to understand what the problem is and how we may solve it. Without understanding the problem, I can't prioritize the solution. I can't even say it is a solution.

**Comment by plaguedemons** [comment]
Sometimes I don't think of Privacy Badger until I am deep into something on a website that I am on.  Then I think about it and I am not on the top level of the website. For instance, I may be in support.microsoft.com, but I am OK with all of Microsoft's web pages using trackers, so I may want to put *.microsoft.com into the whitelist.  The type of editing capability I am looking for would let me make my whitelist be what I want without having to do a lot of extra work to get *.microsoft.com into the list.

**Comment by ghostwords** [comment]
OK, thanks for explaining further.

**Comment by Jsnhlbr5** [comment]
@ghostwords do you have a suggested workflow for this?  In-line editing is not possible without re-doing the list as something other than a basic select element; maybe a "popup" using z-index manipulation similar to the report/share overlays on the addon popup?

**Comment by ghostwords** [comment]
There is a UI example above in https://github.com/EFForg/privacybadger/issues/1484#issuecomment-324129965. Right, we would either have to give up on the standard select element, or implement probably clumsy/buggy hacks (`<select>` works slightly differently on different platforms ... would our hacks be adequate across all platforms?) to work on top of it.

I also don't think this is worth doing (effort vs. reward), but I'm happy to change my mind if our users keep asking for this functionality.
