### ISSUE TITLE
PB blocks *.cloudfront.net

### ISSUE THREAD

**Issue by jeremyn** [EFForg/privacybadger#1494]
PB seems to block `*.cloudfront.net`, which many sites use as a CDN, so this problem breaks multiple sites. One example is the AWS console at https://console.aws.amazon.com which renders almost entirely blank for me.

**Comment by ghostwords** [comment]
@jeremyn Could you share the size of your yellowlist? Run the following in your Badger's background page console:
```javascript
console.log(Object.keys(badger.storage.getBadgerStorageObject('cookieblock_list')._store).length);
```
To get to the background page console in Chrome, visit chrome://extensions, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit about:debugging, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by ghostwords** [comment]
This seems related to #1473; `cloudfront.net` is already on the yellowlist.

**Comment by cowlicks** [comment]
Cloudfront should also be on the mdfp list for amazon. I don't recall how subdomains work with that though, we should document it.

**Comment by jeremyn** [comment]
@ghostwords The result of the `console.log` statement (in Firefox) is `606`.
