### ISSUE TITLE
*.bazaarvoice.com breaks rating image

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1498]
https://www.helzberg.com/category/jewelry/gemstones/moissanite.do?from=ac

`helzberg.ugc.bazaarvoice.com` rating stars under each item is broken.

Action map is too long.
![image](https://user-images.githubusercontent.com/12802056/28243597-d655f6c8-699e-11e7-85c8-35398c475bfc.png)

**Comment by terrorist96** [comment]
https://www.macys.com/shop/product/bar-iii-faux-wrap-shift-dress-only-at-macys?ID=4528825&CategoryID=70162#fn=sp%3D1%26spc%3D2846%26ruleId%3D2|BS|BA%26slotId%3D1

**Comment by terrorist96** [comment]
http://shop.nordstrom.com/s/chloe-mini-marcie-leather-crossbody-bag/3512333?origin=category-personalizedsort&fashioncolor=TAN%20GOLD%20HRDWRE

**Comment by terrorist96** [comment]
`api.bazaarvoice.com` also needs to be yellow for it to load here:

https://www.sigmabeauty.com/f80-flatkabuki/p/F80PARNT

**Comment by cowlicks** [comment]
@terrorist96 thanks for these reports! Do you think a feature where you could print this debug info would be useful? Maybe as an option in the "did privacybadger break this site" box in the popup.

I made #1221 and #1430 for this purpose but they don't expose those a UI yet.

**Comment by terrorist96** [comment]
Yeah, that would be nice. Would avoid me having to run the code each time.

**Comment by terrorist96** [comment]
https://www.costco.com/Kirkland-Signature-AA-Alkaline-Batteries-Two-72-pack.product.100344142.html

**Comment by terrorist96** [comment]
@ghostwords yellowlist?

**Comment by terrorist96** [comment]
https://www.verizonwireless.com/smartphones/asus-zenfone-ar/

What people are saying section blocked.

`display.ugc.bazaarvoice.com`
`api.bazaarvoice.com`

**Comment by terrorist96** [comment]
https://www.bestbuy.com/site/wahl-lithium-ion-all-in-one-trimmer-stainless-steel/3079128.p?skuId=3079128

![image](https://user-images.githubusercontent.com/12802056/36079529-f37743ac-0f51-11e8-91c9-e6ac23e1b89c.png)

**Comment by terrorist96** [comment]
https://www.target.com/p/philips-norelco-replacement-head-rq111-52/-/A-14644825

`photos-us.bazaarvoice.com`

![image](https://user-images.githubusercontent.com/12802056/36082751-41616cb4-0f7a-11e8-96fb-d7cc1af886aa.png)

**Comment by ghostwords** [comment]
Previously: #342.
