### ISSUE TITLE
productreviews.shopifycdn.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1499]
https://impressionsvanity.com/collections/hollywood-vanity-mirrors/products/hollywood-glamour-vanity-mirror?variant=34770708547

`productreviews.shopifycdn.com` breaks reviews at bottom.

![image](https://user-images.githubusercontent.com/12802056/28243660-00c269f8-69a1-11e7-8f77-02233b00e3d0.png)

**Comment by terrorist96** [comment]
https://www.jouercosmetics.com/collections/lips/products/high-pigment-lip-gloss

**Comment by ghostwords** [comment]
`shopify.com` is already on the yellowlist (536b7c67dc8c796848c57211dc07c9fc57d0f1a3).

**Comment by ghostwords** [comment]
Are you able to reproduce tracking from any `shopifycdn.com` domains in a fresh profile? Do you have any cookies or localStorage from any `shopifycdn.com` in your regular profile?

**Comment by terrorist96** [comment]
> Are you able to reproduce tracking from any shopifycdn.com domains in a fresh profile?

No
> Do you have any cookies or localStorage from shopifycdn.com domain in your regular profile?

This issue is on my girlfriend's laptop, so I don't have that info right now. (I can't reproduce on my main profile)

So, purge/migration issue?

**Comment by terrorist96** [comment]
@ghostwords this should also be a bit higher priority considering how popular shopify is for e-commerce.
