### ISSUE TITLE
static.missguided.co.uk

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1503]
https://www.missguidedus.com/

`static.missguided.co.uk` #910 ?

![image](https://user-images.githubusercontent.com/12802056/28244084-c2187630-69ae-11e7-8a9e-d532617f4bc1.png)

**Comment by ghostwords** [comment]
No reports in several years. Will revisit if we learn to block it in Badger Sett and/or start getting user error reports.
