### ISSUE TITLE
badger.isPrivacyBadgerEnabled is O(n) in the number of disabled sites a user has

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1507]
`badger.isPrivacyBadgerEnabled/Disabled` is called in at least 2 blocking webRequest listeners (`onBeforeRequest` and `onBeforeSendHeaders`), and every content script sends a message on every frame that hits this.

The method [iterates over every disabled site](https://github.com/EFForg/privacybadger/blob/fdf533cb07cd1a7e3be1e00a4b613e51228b440d/src/js/background.js#L553-L556) looking for a match. This could be causing significant performance issues for users with many disabled sites.

The disabled sites are stored as an array in `settings.disabledSites`, I think instead we should be using a suffix tree with the root as the disabled TLD's.

**Comment by cowlicks** [comment]
cc @terrorist96 @jeremyn or anyone else:

 I'm trying to figure out how severe this issue is, could tell me how many sites you have disabled? You can just tell me the output of:
```javascript
badger.storage.getBadgerStorageObject('settings_map').getItem('disabledSites').length
```

**Comment by terrorist96** [comment]
I have 0 disabled.

**Comment by cowlicks** [comment]
related to #1371

**Comment by ghostwords** [comment]
Closing until a more clear need for this arises.

Related to #2110.
