### ISSUE TITLE
*.unicornmedia.com blocks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1512]
https://www.vox.com/2016/5/19/11701976/rapping-deconstructed-best-rhymers-of-all-time

`onceux.unicornmedia.com`
`once-aws-us-west-2-lb.unicornmedia.com`

**Comment by terrorist96** [comment]
@ghostwords 
![image](https://user-images.githubusercontent.com/12802056/28907905-a55e9dc8-77ee-11e7-94c3-befb4e145c4d.png)

**Comment by ghostwords** [comment]
Seeing short-duration cookies being set by `onceux.unicornmedia.com` (#1545):
````
set-cookie: um_freq_cap_0aaa0a0a-a000-0a00-00a0-a000a000aa00=0___000000000000000000; expires=Fri, 04-Aug-2017 15:18:22 GMT; path=/.````

**Comment by ghostwords** [comment]
More examples:
- https://www.theverge.com/2017/7/29/16061490/elon-musk-tesla-model-3-handover
- https://www.sbnation.com/mlb/2017/7/27/16048596/adrian-beltre-ejected-relocating-on-deck-circle-my-god-he-is-the-best

**Comment by terrorist96** [comment]
http://hotair.com/archives/2017/08/14/charlottesville-victims-mother-trump-thank/

`once.unicornmedia.com`

See also #1577
