### ISSUE TITLE
Privacy Badger 2017.7.24 stopped blocking

### ISSUE THREAD

**Issue by TimK1987** [EFForg/privacybadger#1529]
I installed the new version and now Privacy Badger tells me there are 0 Tracker.
I uninstalled it, restart FF, installed again, restart FF just to be sure he had the chance to scan the loaded pages again. Now the counter shows 0 and the settings tell me an empty list of Trackers. I visited pages like Twitter, Amazon, aso. but still nothing happen.

**Comment by TimK1987** [comment]
Now it works, don't know why it stucked

**Comment by cowlicks** [comment]
@TimK1987 privacy badger uses a heuristic to learn which trackers to block, it takes 3 visits for the heuristic to recognize what is tracking.
