### ISSUE TITLE
dotsub.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1534]
https://liberland.org/en/news/president-at-the-alec-meeting-226.htm

`dotsub.com` blocks video.

![image](https://user-images.githubusercontent.com/12802056/28597318-405241ca-716b-11e7-9165-939c47c2fb6a.png)

**Comment by cowlicks** [comment]
dotsub.com is a video translation service, but it sets tracking cookies. Adding to the CBL.
