### ISSUE TITLE
Bug: breaks MailChimp mailing list signup form

### ISSUE THREAD

**Issue by elimisteve** [EFForg/privacybadger#1539]
When one has Privacy Badger installed and tries to submit our MailChimp-based signup form at https://pursuanceproject.org/ , nothing appears to happen.  But the form works when Privacy Badger is not being used.

Got any advice on how to fix this?  Anything we can do?  Thanks!

**Comment by elimisteve** [comment]
JS console output:

```

**Comment by ghostwords** [comment]
I see, Privacy Badger thinks an `_AVESTA_ENVIRONMENT=prod; path=/` session cookie set for `twitter.us15.list-manage.com` constitutes tracking.

**Comment by ghostwords** [comment]
Hello, could you run the following in Badger's background page console? This should print the decisions your Badger reached for all "list-manage.com" domains, and the site domains Badger saw "list-manage.com" domains perform tracking on.

```javascript
(function () {
  const STR = "list-manage.com";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row,  and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by cowlicks** [comment]
Hi @elimisteve !! Thanks for the report.

The cookie value is just "prod". I think that should be a low entropy cookie value (in `lowEntropyCookieValues`), since it clearly is not a tracking cookie.

Also, it is a session cookie, it would be nice if the cookie heuristic accounted for session cookies, by just ignoring them, unless they are super entropic.

**Comment by cowlicks** [comment]
Also, form submissions to third parties are probably a bad thing to block generally.

**Comment by elimisteve** [comment]
@ghostwords I see

```
list-manage.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1492738797800,
  "userAction": ""
}
```

and that `SNITCH_MAP for list-manage.com` does _not_ include `pursuanceproject.org`.

**Comment by elimisteve** [comment]
Hey @cowlicks :-). Your points sound good to me.

**Comment by ghostwords** [comment]
I'm interesting in seeing if it makes sense for Privacy Badger to ignore session cookies (no set expiration date, in-memory only, cleaned up when you close the browser), for now anyway. Of all the domains Privacy Badger sees perform "tracking" on the top X websites, which ones are there just because of session cookies? Session cookies are transient by definition. Do session cookies ever constitute tracking we should be concerned about?

> Also, form submissions to third parties are probably a bad thing to block generally.

Could you explain why?

**Comment by terrorist96** [comment]
https://www.rutherford.org/signup

`rutherford.us4.list-manage.com` prevents you from signing up.

```
**** ACTION_MAP for list-manage.com
VM1204:5 list-manage.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1492964312065,
  "userAction": ""
}
VM1204:5 mc.us11.list-manage.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1519748058015,
  "userAction": ""
}
VM1204:5 mc.us2.list-manage.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1524299470427,
  "userAction": ""
}
VM1204:5 mc.us5.list-manage.com {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1492757736615,
  "userAction": ""
}
VM1204:5 piryx.us1.list-manage.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1492696613153,
  "userAction": ""
}
VM1204:7 **** SNITCH_MAP for list-manage.com
VM1204:9 list-manage.com [
  "coinbase.com",
  "statenews.com",
  "piryx.com"
]
```

**Comment by terrorist96** [comment]
Yes.
