### ISSUE TITLE
Surrogate replacements for things like embedded content like tweets, reddit buttons etc.

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1552]
When these things load they don't interact much with other content. So in theory they could be loaded into a sandboxed iframe. The sandbox can block the content from sending cookies and from knowing the page it is hosted on.

For reddit buttons, the type of button is passed in the src URL in the script tag. We should be able to redirect this request to our own script. Our own script should make a sandboxed iframe, then re-load the original script inside it.

This strategy can be re-used for similar content. I think we might even be able to create a heuristic that does this kind of thing automatically. It could monitor script loads,

**Comment by ghostwords** [comment]
Previously: https://github.com/EFForg/privacybadger/issues/1393#issuecomment-304365350

**Comment by ghostwords** [comment]
I'm still not clear on whether sandboxed iframes, created to prevent some types of security issues associated with embedding third-party content on websites, are a good fit for protecting user privacy. While there is definite overlap, security and privacy are different objectives. Where do the goals of security and privacy diverge in this case? For example, it sounds like we'd still be making requests to original servers with every page visit, allowing tracking via IP + request headers.

Does this approach involve allowing scripts or anything else to load outside the sandbox? Sounds like "no", at least as described above, but this is something to watch out for.

If we have to write custom ("surrogate") scripts for each widget, why do we still need sandboxed iframes? Is it to minimize the customization we have to write?

**Comment by cowlicks** [comment]
@ghostwords Yeah, we would still leak ip to the 3rd party.

The privacy protections are:
* no referer header is sent from requests in the iframe
* no cookies from the browser are sent with the request
* the script in the iframe can't access the outside frame so it:
  - doesn't know what origin it is loaded from
  - can't monitor user activity

Other than privacy the gains are:
* content should look almost **exactly** the same (we should have a UI icon or something to indicate PB sandboxed it tho)
* surrogate content like this takes less effort, because we just need to figure out how to contain the content. We do not have to figure out how to re-implement it.

**Comment by cowlicks** [comment]
btw my strategy on how to do this has changed from what I described in https://github.com/EFForg/privacybadger/issues/1393#issuecomment-304365350
 and was implementing in #1404

**Comment by ghostwords** [comment]
We should focus on adding more ["click-to-play" widgets](https://github.com/EFForg/privacybadger/labels/widgets) instead. It seems to me that the problem here is we make a questionable privacy tradeoff while abusing a security-oriented HTML5 feature. We may come back to this if we run into problems with the existing widget replacement approach, but we should take more time developing what we already have first.
