### ISSUE TITLE
Advocate for/Investigate the "clear site data" w3c web app specification

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1559]
https://w3c.github.io/webappsec-clear-site-data/

I think this would give clients better control of data stored per origin.

**Comment by ghostwords** [comment]
This is available in [Chrome as of 61](https://www.chromestatus.com/feature/4713262029471744) and [Firefox as of 63](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data).
