### ISSUE TITLE
Can't Export Data

### ISSUE THREAD

**Issue by BlackRabbit22** [EFForg/privacybadger#1561]
I can't export my data due to it being too large. Is there a workaround for this?

**Comment by ghostwords** [comment]
This bug will be fixed in the next Privacy Badger release.

Duplicate of #1318.

**Comment by ghostwords** [comment]
Let me know if you're OK waiting for it to be fixed, or if you'd like to try an experimental workaround now.

**Comment by BlackRabbit22** [comment]
@ghostwords I'll wait. thank you for your answer.

**Comment by shapiro125** [comment]
I'm getting this issue as well using PB 2017.9.12.1 on Firefox 57.0b3. If i click the "download" button, nothing happens.

**Comment by ghostwords** [comment]
@shapiro125 Could you open a new issue please?
