### ISSUE TITLE
PB≠Persistant Bug?

### ISSUE THREAD

**Issue by br1n3dm1nd** [EFForg/privacybadger#1565]
Just installed latest version of PB into Firefox 54.0.1. 

PB icon immediately disappears (from both toolbar and tray), therefore unable to access menu, options, et al, or verify if PB is running. To clarify, there is a blank space on the toolbar that, when the pointer hovers over it, displays the "Privacy Badger" text box--but nothing happens when I right- or left-click on the space.

Problem persists despite multiple un- & re-installs, and disabling other plug-ins. 

Please help!

Thanx,

**ßµ**

**Comment by cowlicks** [comment]
Sorry to hear that! Are you able to see it in the `about:debugging` page? If you access the background context, can you see errors?

Re: #1221 would be useful here

**Comment by br1n3dm1nd** [comment]
Confession time: I prrrrobably shouldn't be on GitHub, as my programming aptitude is near zero. But I was able to determine that the debugger page is empty and that the Console, before exploding with toolkit.telemetry errors, looked like this:
![peanut butter](https://user-images.githubusercontent.com/30854781/29147375-ced8bdfc-7d23-11e7-9984-df2709eb8324.png)
Help you, this does, yes?

**Comment by cowlicks** [comment]
I'm not sure that is the correct page. Here are better insturctions:

* Try going to "`about:debugging`" (just put it in the url bar and press enter)
* click "enable add on debugging box"
*  find PB and click the "debug" button
* click "ok" on the scary prompt
* then it should show a console, post that here

**Comment by br1n3dm1nd** [comment]
Cowlicks,
Are you somehow unable to see the screenshot I posted? If so, the question then becomes "should YOU be here?"

**Comment by br1n3dm1nd** [comment]
(as in, yes. yes, that's _precisely_ what i did to generate the screen i posted the shot of...)

**Comment by ghostwords** [comment]
Is this still an issue with the latest stable Firefox release (55)?

Is this an issue when installing Privacy Badger into a [fresh profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles)?

**Comment by ghostwords** [comment]
I'm going to close this for now; let me know if you have any more information.
