### ISSUE TITLE
Document Android / mobile development process

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1578]
A good starting point is https://github.com/EFForg/privacybadger/pull/1516#issuecomment-316696890 and https://github.com/EFForg/privacybadger/pull/1516#issuecomment-316867140

**Comment by andresbase** [comment]
We also need to figure out how to test on mobile for different versions and screens that doesn't take too long. I'll ask E&D but any recommendations are welcome.

**Comment by cowlicks** [comment]
Right now, most of the code for mobile can be tested with unittests. We can probably test UI stuff just fine by forcing the window size to have mobile dimensions on travis-ci + mocking `firefoxandroid.isUsed`.

I don't think we need something as elaborate as saucelabs, at least not yet, since we are not testing a full mobile app.

**Comment by ghostwords** [comment]
`web-ext` now supports testing Firefox extensions for Android (https://github.com/mozilla/web-ext/issues/737#issuecomment-356170732, [demo video](https://www.youtube.com/watch?v=fs-mSrap6a8)).

We may not need to do anything beyond linking to https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext#Testing_in_Firefox_for_Android somewhere in our documentation.

**Comment by ghostwords** [comment]
Regarding testing, see #1624.
