### ISSUE TITLE
Toggling slider for a domain on options page resets scroll

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1581]
Causing you to lose your place. From a support email:

>When an entry is flipped from green to yellow or red it should not (yet) move and the display of the URLs not jump back to the beginning because this makes it very difficult to go through the whole list of maybe more than 1000 entries.

**Comment by DJCrashdummy** [comment]
as mentioned in #1664:
this also occurs when reverting some individual setting back to default or deleting an entry.

**Comment by neandrake** [comment]
This appears to happen when toggling on a base domain when there are other subdomain options present. Ex. when toggling `website.com` while there is also a `abc.website.com` item -- it looks like this preference page toggles both when toggling `website.com` (which is probably desired), however by toggling multiple the scroll jumps back to top of page. When toggling just a single/solo item that has no additional sub-domains the scroll-jumping does not appear to happen.

Firefox 57

**Comment by mijiturka** [comment]
For the domains generated on scroll (that have the issue described in #1706), changing slider positions does not cause this behaviour. Reverting to default does though.

**Comment by ghostwords** [comment]
Since the options page shows all tracking domains, not just the ones actually present on some page, it needs to handle what happens to subdomains of a domain when you toggle the slider for that domain. For example, toggling the slider (or clicking on the undo arrow) for `example.com`, should update the display of `api.example.com` and `www.example.com`.

We currently do this by redrawing the tracking domains list [in response to a domain slider being updated, for example](https://github.com/EFForg/privacybadger/blob/acd5ba79dadbc30e1f9170e0365868f275667f38/src/js/options.js#L601). The problem is that redrawing the entire list causes you to lose your place.
