### ISSUE TITLE
as-sec.casalemedia.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1587]
http://www.investopedia.com/terms/e/ema.asp

`as-sec.casalemedia.com` breaks video.

![image](https://user-images.githubusercontent.com/12802056/29472799-3bcf8822-8423-11e7-861d-31b56b6fac39.png)

**Comment by ghostwords** [comment]
Could you run the same debugging code for the base domain name portion, `casalemedia`?

**Comment by terrorist96** [comment]
Yeah, my bad. Forgot.

![image](https://user-images.githubusercontent.com/12802056/29475137-70b8eeee-842c-11e7-8330-001ffcd6a430.png)
![image](https://user-images.githubusercontent.com/12802056/29475148-7dd07502-842c-11e7-9a64-778918f0e084.png)

**Comment by terrorist96** [comment]
Here it is from the test profile, where I actually reproduced the issue; ^that was from my main profile; I don't even see `casalemedia` in my main profile:
![image](https://user-images.githubusercontent.com/12802056/29475192-a963f9be-842c-11e7-80fc-97582e7c9db1.png)
