### ISSUE TITLE
add a surrogate for bat.bing.com/bat.js

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1594]
Sometimes blocking it breaks websites, see #1411

**Comment by ghostwords** [comment]
Should check error reports to see if we get reports because of `bat.js` breaking stuff. Partially depends on #1475 to be fixed.

**Comment by ghostwords** [comment]
There is no uBlock surrogate for `bat.js`, and it seems it has only come up for them in the context of Airbnb:  https://github.com/uBlockOrigin/uAssets/search?q=bat&type=Code

**Comment by ghostwords** [comment]
I have found no evidence for `bat.js` causing any other breakage at this time.
