### ISSUE TITLE
Send, Trash "inline buttons" in Google's Inbox aren't working

### ISSUE THREAD

**Issue by HagaiHargil** [EFForg/privacybadger#1595]
I'm using Firefox Nightly, and when Privacy Badger is active I'm not able to send mails from Google Inbox's inline reply interface. When I try to reply to a mail straight from Inbox's main page, the Send button remains inactive even after I start typing in the mail. The Trash button doesn't work as well. 

This means that I have to pop out the mail correspondence and reply from it, instead of just pressing the "reply" button and type in my response. 

Disabling Badger (again, on Nightly) solves this issue.

Thanks!

**Comment by ghostwords** [comment]
Is this an issue on Firefox Beta (56) or stable (55)?

**Comment by HagaiHargil** [comment]
Neither - it's Firefox Nightly, which is currently on (the much anticipated) version 57.

**Comment by ghostwords** [comment]
Does disabling Privacy Badger just on Gmail solve the issue?

**Comment by ghostwords** [comment]
Is this still an issue? Does disabling Privacy Badger just on Gmail solve the issue? Does this happen with any other WebExtensions add-ons such as uBlock Origin?

**Comment by HagaiHargil** [comment]
Hi, sorry for not replying earlier.

I found a thread in bugzilla that mentioned this issue, and it seems that it's mostly resolved. It had to do with the new Servo engine they're using, I believe.

Hagai.

**Comment by ghostwords** [comment]
Ah! If you have the Bugzilla thread handy, could you link to it here?

**Comment by HagaiHargil** [comment]
[This](https://bugzilla.mozilla.org/show_bug.cgi?id=1379203) is it. As you can see, it was a mess to fix, and my short trial-and-error tests showed that the Badger had something to do with it, but I guess I was wrong :)
