### ISSUE TITLE
Tracking Domains options page tab only uses half the page

### ISSUE THREAD

**Issue by ghost** [EFForg/privacybadger#1599]
![skarmbild fran 2017-08-23 08-19-27](https://user-images.githubusercontent.com/23194385/29601537-5ab8e85c-87dc-11e7-9eb0-bb155e978cb1.png)

**Comment by DJCrashdummy** [comment]
it can be even worse...
![privacy_badger_optionen_](https://user-images.githubusercontent.com/26110463/30426710-53cf1106-994d-11e7-9733-80a0481c90cb.png)

**Comment by ghostwords** [comment]
Options page tabs getting squished on Firefox will be fixed as part of #1669 (in 4aaf33f415d3bae420a81b6ccd409b8bc7baf670).

**Comment by ghostwords** [comment]
The main challenge here is converting hardcoded positioned sliders to a fluid layout that sensibly scales with the width of the slider list.

The same slider list is used in the popup and the options page. The popup could be a bit narrower when moved to menu on Firefox, and significantly narrower when displayed on mobile devices (Firefox for Android) with smaller displays. (We currently use a display width breakpoint to adjust hardcoded positioning for smaller displays.) The options page is of course resizeable by the user.

We would also have to update the slider list header row (the block/cookieblock/allow icons that remain in place even as you scroll the table) to use the same approach.

This is related to #2776. As I wrote in that issue:

>We could fix this by ... reworking the [...]sliders to use a fluid layout (instead of hardcoded pixel positioning). This would also improve keyboard element ordering and fix RTL issues with sliders.

**Comment by Sotilrac** [comment]
Would something like this be the desired outcome (ignore the dark colour, only the positioning)?

![image](https://user-images.githubusercontent.com/483059/214937655-af58e496-edee-4240-b42c-dd76266f3bf0.png)

**Comment by ghostwords** [comment]
Yep, that seems good. Let me know if you have any questions about my notes inhttps://github.com/EFForg/privacybadger/issues/1599#issuecomment-927347122.

**Comment by Sotilrac** [comment]
I'd like to work on fixing this. And it makes indeed sense that this affects everywhere where the sliders are reused. Is the best approach to fork the repo and do a PR for you guys to review?

Also, idk how timely I can be with this. So I understand if someone else wants to fix it before I get to. I'm just trying to help out since this is a tool I use and love, and I'd like to give back.
