### ISSUE TITLE
Breaks eBay.co.uk

### ISSUE THREAD

**Issue by n-o-o-b** [EFForg/privacybadger#1600]
With Privacy Badger enabled for ebay.co.uk, nothing works. If I go to ebay.co.uk and search for something, the URL changes but the page does not.
If I disable Privacy Badger for ebay.co.uk, it allows me to search once, but then subsequently the same thing happens as above.
I have uBlock Origin, but everything is fine with the Privacy Badger add-on disabled, so I know it's Privacy Badger that breaks the site.

**Comment by ghostwords** [comment]
Are you using Firefox? Could you upgrade to Firefox 55 and see if that fixes the problem?

**Comment by n-o-o-b** [comment]
I'm on the current stable version of Firefox which is 55.0.2.

**Comment by ghostwords** [comment]
Could you (temporarily) disable all add-ons (including Privacy Badger), install [this test add-on](https://github.com/EFForg/privacybadger/files/1079120/firefox_webext_onunload_bug_demo.zip) I made, and see if the problem occurs with the add-on and goes away without it?

To load the above add-on in Firefox, unzip the archive somewhere, visit `about:debugging`, click on Load Temporary Add-on, and pick the manifest.json file inside the unzipped folder.

**Comment by n-o-o-b** [comment]
Okay, so I first tried ebay.co.uk with all add-ons disabled apart from Privacy Badger *before* I tried your test, and the site actually worked fine, both with Privacy Badger set to 'disable' and 'enable' for ebay.co.uk.
I then followed your instructions regarding the test add-on and the same thing happened.

**Comment by ghostwords** [comment]
So ... Privacy Badger alone: all good. Test add-on alone: all good. Privacy Badger in combination with something else: issue happens. Is that right? What is that something else then?

**Comment by n-o-o-b** [comment]
Test add-on alone & with Privacy Badger: good.

The other add-ons I currently have enabled are Dark Background and Light Text, uBlock, Decentraleyes, DisableBackspaceNavigation, KeeFox, Google search link fix, Google Translate in Menu (Right Click), Oxford English Dictionary, Session Manager, Take a Break, Urban Dictionary Tooltip, Wiktionary and Google Translate and Youtube Plus. So quite a lot to go through.

**Comment by ghostwords** [comment]
You could split you add-on list in half (probably best to go by the order in which the add-ons are listed) and disable the other half. If you still have the problem, great, let's split this half again. If you don't, switch halves.

**Comment by n-o-o-b** [comment]
Or start with just Privacy Badger and enable one by one?

**Comment by ghostwords** [comment]
That works too!

**Comment by n-o-o-b** [comment]
After disabling all of my add-ons apart from Privacy Badger and enabling them one by one, and then also enabling each one individually with Privacy Badger, I have worked out that these are the add-ons which seem to be causing problems:

[UrbanDictionaryTooltip](https://addons.mozilla.org/en-GB/firefox/addon/urbandictionarytooltip/?src=ss)
[Google Translate in Menu](https://addons.mozilla.org/en-GB/firefox/addon/google-translate-in-menu-right/?src=search)
[Wiktionary and Google Translate](https://addons.mozilla.org/en-GB/firefox/addon/google-dictionary-and-google-t/?src=ss)
[Take a Break](https://addons.mozilla.org/en-GB/firefox/addon/take-a-break/?src=ss)
[DisableBackspaceNavigation](https://addons.mozilla.org/en-GB/firefox/addon/disablebackspacenavigation/?src=ss)

**Comment by Stefal** [comment]
I have the same problem with ebay, and many other website. My enabled extensions on Firefox 55.0.3 (32 bits) are 
- Ublock Origin
- Keefox
- Sage ++ Higmmer's edition

**Comment by ghostwords** [comment]
This might be another Firefox WebExtensions bug, https://github.com/EFForg/privacybadger/issues/1295#issuecomment-327829964.

**Comment by ghostwords** [comment]
I'm going to close this for now. Let me know if this is still an issue.
