### ISSUE TITLE
res.wx.qq.com and login.weixin.qq.com break WeChat web app

### ISSUE THREAD

**Issue by tsekityam** [EFForg/privacybadger#1602]
I tried to use [WeChat web app](https://web.wechat.com/), and I noticed that the app is broken because of Privacy Badger.

Here are two reasons I could found:
1. Resources (i.e. css and image) files from `res.wx.qq.com` are blocked; and
2. QR code image for login from `login.weixin.qq.com` is blocked. (after I yellow listed `res.wx.qq.com` manually)

After putting these two domains to yellow list, then I can login to WeChat webapp normally.

P.S. I didn't check any other feature of the app after I logged in to it.

**Comment by ghostwords** [comment]
Since QQ and WeChat are both owned by Tencent, it seems like we should be able to solve it by marking the associated domains as same party with respect to each other (#781).
