### ISSUE TITLE
*.taleo.net

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1605]
https://www.veracyte.com/join-our-team/job-openings

`chk.tbe.taleo.net` blocks element. `staticchk.tbe.taleo.net` is blocked as well; unsure if it's essential.

![image](https://user-images.githubusercontent.com/12802056/29737613-dc8ada4e-89de-11e7-9017-67179bda2d2f.png)

**Comment by terrorist96** [comment]
https://corporate.virbac.com/home/career/career-opportunities.html

`virbac.taleo.net`

**Comment by ghostwords** [comment]
Also:
- `https://www.precisionmedicinegrp.com/careers/`
- `https://www.seracare.com/about-us/careers/career-opportunities/`
- `https://www.philadelphiafed.org/careers/job-openings`

**Comment by terrorist96** [comment]
Should I make a PR to add `taleo.net` to the yellowlist?

**Comment by ghostwords** [comment]
Yeah, this seems like a good case.
