### ISSUE TITLE
Consider combining error reporting & disable site in popup UI

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1622]
When PB breaks a site, people usually disable PB, or send an error report or both. We should probably combine these in the popup UI to make a flow for doing both that is more streamlined.

My initial thought, when a site gets disabled, we should prompt the user to also submit an error report.

**Comment by ghostwords** [comment]
Is one goal to encourage users to let us know when a site is broken?

And another to see if we can make the popup a bit less busy by remove a button (by somehow combining whitelisting and error reporting)? This one might be challenging; we don't want to make submitting error reports more difficult.

**Comment by cowlicks** [comment]
@ghostwords yes, those are both reasons to consider this.

**Comment by ghostwords** [comment]
Closing for now, may revisit later.
