### ISSUE TITLE
Consider enhancements to remotely updateable assets

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1623]
The yellowlist format and release process has cause several problems [edit: #1473], so we should discuss how we want to improve it in the future.

Some nice-to-haves:
* ~~one file - other files for old versions could be generated as a build/release step~~
* json formatted to avoid parsing issues
* cryptographically signed releases
* automatic updates from master
* add versioning in order to update only when we receive a version we know is newer than the existing version

We can put the new version of the yellowlist at a different url endpoint, so it does not interfere with the old ones.

**Comment by ghostwords** [comment]
Switched to a single yellowlist file in #1629 and e20f094beb59a0a0da8a168cdadb32886c6841c5.

**Comment by ghostwords** [comment]
Related to #795.

**Comment by ghostwords** [comment]
While these are all good ideas in theory, it's not clear any are important to implement. We may come back to some of this in the future as we better understand what needs improving, but it doesn't pay to work on improvements without understanding the need behind them. Closing as "wontfix" for now.
