### ISSUE TITLE
Add Firefox for Android tests

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1624]
We need unittests for [firefoxandroid.js](https://github.com/EFForg/privacybadger/blob/ae4cd82ad18a885e8f5e68a47ecc922f3de61c20/src/js/firefoxandroid.js)

We should also investigate adding selenium tests with `isFirefoxAndroid` mocked.

**Comment by ghostwords** [comment]
I'm not sure about the (Selenium-powered) functional tests. If we are not running on Android, what are we testing?

**Comment by cowlicks** [comment]
@ghostwords we would be testing that the layout and UI preforms as expected. Chrome and Firefox have modes where they emulate mobile devices for this purpose.

**Comment by ghostwords** [comment]
Closing for now, may revisit later when the need arises.
