### ISSUE TITLE
Don't show tracker message in popup on extension pages.

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1625]
I watched a user install privacy badger, they clicked on the icon on the first run page and read message. The text is incorrect and irrelevant on pages like this. It confused them. The text says:
>Privacy Badger detected potential trackers on this page. These sliders let you control how Privacy Badger handles each one. You shouldn't need to adjust them unless something is broken.

![pb-dont-show-on-nonpages](https://user-images.githubusercontent.com/598099/29952640-8bd70668-8e7f-11e7-94dc-85ea34eabe2e.png)

**Comment by ghostwords** [comment]
Also new tab pages, any other browser pages (settings), Chrome Web Store. Any special page Privacy Badger is unable to work with.

Should also avoid showing the badge on such pages.

**Comment by cowlicks** [comment]
@ghostwords I don't thin hiding the badge is necessary. No other extensions seem to do that.
