### ISSUE TITLE
3rd-party scripts

### ISSUE THREAD

**Issue by svnpenn** [EFForg/privacybadger#1630]
I use uBlock Origin, and it can block 3rd-party scripts:

http://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode

can Privacy Badger do this?

**Comment by ghostwords** [comment]
Privacy Badger does not offer NoScript-like features.

Privacy Badger aspires to be an install-and-forget extension, good for use either by itself or in combination with more technical privacy tools such as uBlock Origin or uMatrix.
