### ISSUE TITLE
Improve opening the popup in functional tests

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1634]
This function [`load_pb_ui`](https://github.com/EFForg/privacybadger/blob/7ff4206014665386c0fb2684ab769619be54d85f/tests/selenium/cookie_test.py#L151) does not actually load the popup for the url, it just runs `reloadTab`, which does not re-run the `init` function.

This is fixed in the [`open_url_and_popup`](https://github.com/EFForg/privacybadger/pull/1627/files#diff-83bc298085492f65cd02d79021b5361bR17) function added by #1627

**Comment by ghostwords** [comment]
Could you explain what the issue here is?

**Comment by cowlicks** [comment]
@ghostwords the issue with `load_pb_ui`? Since it does not run `init` it does not refresh the entire popup. Specifically stuff in `pbInstructions` isn't replaced.

**Comment by ghostwords** [comment]
Does this mean that `load_pb_ui` doesn't render the popup the same way the popup is rendered when opened by a user during regular browsing, meaning if your test code depends on bits of the popup that aren't covered by `load_pb_ui`, your test code won't work?

**Comment by cowlicks** [comment]
@ghostwords Yeah, I our test code would not work in that case.

**Comment by ghostwords** [comment]
Should restore enable/disable buttons test (removed in b6b1912ec8ae771d163c7e641a94b1f740d98732) and remove the workarounds in 92b9f05c206a8afa3acc871bcbbf986cb22eaecd once we have a proper way to open the popup for a given page in tests.
