### ISSUE TITLE
Block reddit "conversion pixel" tracking via web beacon

### ISSUE THREAD

**Issue by BrettDikeman** [EFForg/privacybadger#1635]
Reddit [now implements an embeddable tracker to track visitors coming from reddit ads](https://www.reddithelp.com/en/categories/advertising/advertising-101/installing-reddit-conversion-pixel) via a web beacon GIF. Does this fall within the scope of content PrivacyBadger blocks, and if so, can this be added?

Thanks!

**Comment by ghostwords** [comment]
If a Privacy Badger sees a domain perform tracking on three or more separate websites, Privacy Badger will start blocking that domain. Privacy Badger does not maintain lists of domains to block.

It would help to have an example or two of Reddit's Conversion Pixel in the wild to say how exactly Privacy Badger will handle it, and whether this will pose any problems for Privacy Badger users on Reddit itself.

**Comment by BrettDikeman** [comment]
I'm unclear on why you implied you wanted to see an example, stated it was
unclear how PB would handle it until you saw such an example, and then
closed the ticket.

Also, the link I provided includes example code...quite clearly and visibly.

**Comment by ghostwords** [comment]
I meant it would be good to see a live example of the pixel being used on a website somewhere.
