### ISSUE TITLE
Block specific cookies

### ISSUE THREAD

**Issue by svnpenn** [EFForg/privacybadger#1636]
Google sometimes uses a cookie named `NID` when it thinks you are a robot.

This is annoying and you have to delete the cookie before you can do any more
searches.

I would like to block this specific cookie, but not necessarily all Google
cookies. Can this be done?

**Comment by ghostwords** [comment]
Manual cookie management is outside of Privacy Badger's scope. It sounds like you are looking for something like [EditThisCookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg). I found it by searching for "block specific cookie"; I can't speak to its trustworthiness or reliability.

**Comment by svnpenn** [comment]
Workaround: Firefox can block cookies:

1. Options
2. Privacy
3. History
4. Firefox will: Use customer settings for history
5. Exceptions
6. Site: `https://www.google.com`, Status: Block
7. Save Changes

http://superuser.com/a/1248944

**Comment by ghostwords** [comment]
@svnpenn Wouldn't that block all Google cookies? As opposed to just the `NID` Google cookie.

**Comment by svnpenn** [comment]
It blocks www.google.com, but not mail.google.com etc. Good enough for my needs
