### ISSUE TITLE
T.co link questions

### ISSUE THREAD

**Issue by rugk** [EFForg/privacybadger#1637]
I used to use some other add-ons for cleaning the t.co links (https://github.com/idlewan/link_cleaner/issues/18 and https://github.com/gcp/twitter-link-expander), so I have a few questions:
* Other add-ons had big problems expanding the links in Twitter cards. Can PrivacyBadger finally do so?
* Is the full URL correctly shown on hover, or only when the short link is clicked?

**Comment by ghostwords** [comment]
Privacy Badger should handle card links on Twitter.

Since link URLs are periodically replaced without waiting for user interaction, hovering over links should reveal full URLs.

Let me know how this works for you.

**Comment by rugk** [comment]
Ah, indeed it does work. **However**, I had to disable all other add-ons doing the same (see links above) for it to work.

**Comment by ghostwords** [comment]
Cool, let us know if you run into any other issues.

**Comment by cowlicks** [comment]
@rugk what other addons are you using? I'd like to notify those developers to make them aware of the conflict.

**Comment by rugk** [comment]
At that time I wes using https://github.com/johnpbloch/de-t-co and https://github.com/gcp/twitter-link-expander. But I think it likely happens with https://github.com/albancrommer/skiptco, too.

**Comment by Eskuero** [comment]
It works fine for replacing links on twitter.com but it simply doesn't work on tweetdeck

**Comment by ghostwords** [comment]
By TweetDeck, do you mean `tweetdeck.twitter.com`? We were going to support it but then took it out to expedite releasing the feature (#1392). I opened #1651 to track adding TweetDeck support.
