### ISSUE TITLE
azureedge.net

### ISSUE THREAD

**Issue by tsekityam** [EFForg/privacybadger#1643]
_azureedge.net_ is used by Azure CDN. Marking it as red may break site.  https://www.join.me/ is one of the example.

I think we should put this domain in yellow list.

**Comment by ghostwords** [comment]
Hello, could you run the following JavaScript code in your Privacy Badger's background page console and let us know what it shows? Here are the instructions for getting to the background page: https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b.

```javascript
(function () {
  const STR = "azureedge";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

**Comment by ghostwords** [comment]
So far I noticed localStorage use by (and a session cookie from) `sdk.azureedge.net`.

Once Badgers see `sdk.azureedge.net` on three domains, they block it and its parent, `azureedge.net`, which means also blocking all other `azureedge.net` subdomains, which leads to lots of reports of sites with no images or styles.

**Comment by ghostwords** [comment]
Would be good to try setting up some error reporting queries that group by blocked domains (instead of site domains), to try to identify common problems (like this one seems to be) scattered across many different sites.

**Comment by ghostwords** [comment]
Examples:
- https://www.bourbonandboots.com/products/leather-satchel
- https://authenticity50.com/challenge
- https://www.voordeeltrends.nl/guerlain-guerlain-shalimar-woman-eau-de-parfum-spr.html
