### ISSUE TITLE
Consider removing sinon

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadger#1646]
Problems:

The dependency is 2.1 MB, including it **doubles** the size of the entire bundled extension.

It has several bugs we've encountered.

It is easy to replace. We only use it in 9 places.
```bash
tabData.js:35:        sinon.stub(chrome.browserAction, "setBadgeText");
tabData.js:232:        this.setBadgeText = sinon.stub(chrome.browserAction, "setBadgeText");
utils.js:38:    let server = sinon.fakeServer.create({
utils.js:137:    let clock = sinon.useFakeTimers(+new Date());
utils.js:139:    let callback = sinon.spy(function (password, i) {
yellowlist.js:17:      server = sinon.fakeServer.create({
background.js:25:        server = sinon.fakeServer.create({
background.js:35:        clock = sinon.useFakeTimers(+new Date());
background.js:43:      xhrSpy = sinon.spy(utils, "xhrRequest");
```
We don't even really need it for `fakeServer`, `spy`, and `stub`.  We can reproduce those with plain javascript easily.

`useFakeTimers` might be harder to reproduce, but if it is we can refactor the tests a bit to avoid needing it. I always have trouble with those tests, and in some cases we don't even need it, we can instead mock `constants.DNT_CHECK_POLICY_TIME` to a test value.

I also generally find it difficult to use.

**Comment by ghostwords** [comment]
I agree about the file size. To fix, let's stop shipping unit tests with the published extension. It's not unreasonable to have to get the developer version in order to run the tests.

**Comment by ghostwords** [comment]
As discussed in the meeting, let's not spend time reinventing the wheel.
