### ISSUE TITLE
Support t.co unwrapping on TweetDeck

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1651]
Following up on #1392. TweetDeck requires a slightly different query (b348e037dbd989e368640658ce8d74a5ff255ee0).

**Comment by Eskuero** [comment]
I had myself this small js code running to expand the links on tweetdeck.twitter.com but it's indeed not a convenient way of doing it.
setInterval(function(){
	var urls = document.getElementsByClassName("url-ext");
	for (i = 0; i < urls.length; i++) {
		urls[i].href = urls[i].getAttribute("data-full-url");
	}
}, 3000);
The extension https://github.com/jonsuh/fix-twitter/ work fine for this purpose too.
