### ISSUE TITLE
Plain images not shown on some (most) image servers.

### ISSUE THREAD

**Issue by Ianunaut** [EFForg/privacybadger#1653]
When I open plain images in Firefox with Privacy Badger active, they don't show. This is the case for most image servers, forcing me to download the image and view it from my local HDD. One notable example where it never works is Imgur, while one notable example where I don't have any issues is the Twitter image server. 

For some servers, it depends on how I open the images. When I open them through links from external applications (e.g. IRC clients, screenshot upload tool), they absolutely never show. When I open them through links on the same domain/server/site, they sometimes work. This is true for Tumblr images, for an instance.

Here's a screenshot I just made as an example for URLs that don't show the images: https://i.imgur.com/BNsl9Ei.png

Privacy Badger is deactivated for Imgur, of course, but it doesn't change anything. When I deactivate Privacy Badger as a whole, as a Firefox add-on that is, I have zero issues with displaying images in Firefox.

**Comment by WilliamAlan** [comment]
I've been having exactly the same issue in Firefox for some while now, and have tracked it down to PB. For example, the photos linked to the thumbnails on this site: http://www.davidtannenberg.com/Tannenberg_Moselem_Springs.htm will not load as long as PB is enabled. If PB is disabled, they load without issue, with one exception: I have a similar problem if Adguard AdBlocker 2.6.7 is enabled, no such problem with Adblock Plus. That's not your problem, obviously, but the info might help with troubleshooting/debugging.

**Comment by ghostwords** [comment]
This sounds like another Firefox bug with WebExtensions.

**Comment by ghostwords** [comment]
Which Firefox versions do you use? Does the same issue occur on Firefox Beta (56) or Nightly (57)?

**Comment by ghostwords** [comment]
It sounds like the new WebExtensions uBlock version runs into the same issue: https://github.com/gorhill/uBlock/issues/2930. See gorhill's release notes for suggested workarounds (see if disabling legacy add-ons helps): https://github.com/gorhill/uBlock/releases/tag/1.14.6.

**Comment by ghostwords** [comment]
See also https://github.com/greasemonkey/greasemonkey/issues/2524.

**Comment by Ianunaut** [comment]
I had that isse over the last few Firefox versions, but your last reference actually helped me fix my issue. I'm indeed using Greasemonkey with 3 scripts enabled, and one of them -- Anti-Adblock Killer by Reek --  seems to have had the @run-at document-start which created this problem. I disabled the script and loading images seems to be working fine now. 

Thank you very much!

**Comment by WilliamAlan** [comment]
Firefox 55.0.3 (64-bit). Had the same problem in ver. 54. I'm not about to
start fooling with the Beta or the Nightlies. I've enough complications in
my life already, thank you. But thanks for the attention.
 
WAG


  _____

**Comment by ghostwords** [comment]
Nice! So it sounds like this will be resolved as of Firefox 57, which no longer supports legacy add-ons.

**Comment by WilliamAlan** [comment]
Yup, it's the Anti-Adblock Killer script that's apparently the proximal
source of the problem. HOWEVER, ver. 57 will NOT be any solution for me, at
least for right now. All but 2 of the extensions that I use, and I use about
18 of them, are flagged as "Legacy." Break those extensions and it will
break Firefox AFAIC. Looks like I may be stuck @ 56 for some time to come.
Not happy.


  _____

**Comment by ghostwords** [comment]
Yeah, I wonder how this legacy add-on apocalypse will play out for Firefox. You could get in touch with your favorite legacy add-on authors and see where they stand with regard to WebExtensions.

**Comment by Ianunaut** [comment]
Same for me, Will. Losing the Classic Theme Restorer would hurt too much, and aris already said it can't be ported to WebExtensions. I'll either stick with FF56 or jump ship to Vivaldi. Too bad.
