### ISSUE TITLE
Google Sheets

### ISSUE THREAD

**Issue by william20111** [EFForg/privacybadger#1661]
Working with google sheets is broken right now with firefox. Safe mode works fine, and with PB disabled it works. 

- FF 55.0.3 (64-bit)
- PB version 2017.9.12

"Some fonts could not be loaded. Try again when your online" is the sheets error. 

The "disable on this site" doesn't change anything, but then disabling the addon completely then fixes the issue. Cant see anything weird in the console when loading the page. Need any more info I can provide it.

Cheers
Will

**Comment by ghostwords** [comment]
Hi, are you using the `eff.org`-hosted version? I'm sorry, we introduced a bug with the release that we hope to fix later today.

**Comment by ghostwords** [comment]
Looks like we've re-introduced broken-on-Firefox `fingerprinting.js` because I missed updating the release scripts when I reviewed 879a74f807999a2135e4d48bb5efbd8a1beff4f8. The proper fix is to make the file work with Firefox, something I can do before the next release: #1158. For now, let's fix the release script.

**Comment by william20111** [comment]
Yes i was using the version off firefox addons store. Looks like you got it sorted, sweet! :) 

Cheers
Will

**Comment by ghostwords** [comment]
@william20111 Could you visit `about:addons` in Firefox, click on the More link in Privacy Badger's entry and post a screenshot of that screen?

**Comment by william20111** [comment]
![eff](https://user-images.githubusercontent.com/3274971/30385260-89631434-989e-11e7-8091-ec80e4b9414d.png)

**Comment by ghostwords** [comment]
Yep, OK, you have the `eff.org`-hosted version. I'll update here when the fix is out.

**Comment by ghostwords** [comment]
Could you update to 2017.9.12.1 and see if that fixes the issue?

**Comment by celadevra** [comment]
I have encountered a similar issue with Google Spreadsheets. 2017.9.12.1 seems to have solved the problem for me.

**Comment by ghostwords** [comment]
Excellent! Sorry about the breakage.

**Comment by jcgoble3** [comment]
Just echoing celadevra: I too had this issue, and 2017.9.12.1 has fixed the issue on my end.
