### ISSUE TITLE
better navigation through and handling of domain-list

### ISSUE THREAD

**Issue by DJCrashdummy** [EFForg/privacybadger#1664]
- [ ] most important: please make the list stay at the scrolled items!
if you have to delete more than one domain (e.g. domain+subdomain) it quickly gets a pain in the ass, because after an operation it jumps immediately to the beginning. - and this even occurs when reverting some individual setting back to default.

- [ ] searching for domains which settings you have overridden is a tedious task... and so it is for all other groups of domains.
i would suggest to add some filters for the domain-list, like for _overridden settings_, _DNT-domains_ and all three kinds of statuses.
--> the easiest implementation into the GUI would be to simply make the symbols above the list clickable... and there is also enough space for the DNT-icon and so on.

- [ ] last but not least: an useful combination of these mentioned filters would be awesome.
--> maybe there is also enough space for a _"clear all filters (including text)"_-icon.

**Comment by ghostwords** [comment]
Please see #1581 for the first item. See #1422 for the second.

**Comment by ghostwords** [comment]
Also see #1603 for my thoughts regarding the domain list on the options page, which may be relevant here. Privacy Badger is meant to be a hands-off, no configuration required privacy tool. Could you talk about how you find yourself needing to use the domain list on Badger's options page?

**Comment by DJCrashdummy** [comment]
i have to confess i didn't research that much, but somehow i missed these (especially the first is an exact duplicate) completely... sorry for that!

> Privacy Badger is meant to be a hands-off, no configuration required privacy tool.

for sure, i got this. and i have to say kudos! i've never used an add-on for such a non-trivial task with the need of so few configuration... maybe just [Decentraleyes](https://addons.mozilla.org/firefox/addon/decentraleyes) and [HTTPS Everywhere](https://addons.mozilla.org/firefox/addon/https-everywhere) :wink: can comped.

> Could you talk about why you find yourself needing to use the domain list on Badger's options page?

i use Privacy Badger for more than a year now in production environments and also recommend it for others (i also tested it before it was available at the mozilla add-ons), and now i want to merge 4 or more instances and started thinking about export/import and managing of the data.
and in the course of which i recognized some interesting domain-entries like an completely empty one or 127.0.0.1 and so i had a closer look and thought about reviewing or deleting the allowed domains.

**Comment by ghostwords** [comment]
Re blank domain in the domains list on the options page: #1447.

**Comment by ghostwords** [comment]
Yep, your use case makes sense. We should both de-emphasize the options page domain list, and make it more usable. Thanks for the feedback!
