### ISSUE TITLE
Zimbra folder view not visible with PrivacyBadger installed (round 2)

### ISSUE THREAD

**Issue by KnuckleBob** [EFForg/privacybadger#1665]
In the Zimbra Webmail client, the folder view on the left side are not visible anymore when PrivacyBadger is installed and enabled. This appears to be a regression from the fix that was applied as noted in https://github.com/EFForg/privacybadger/issues/1050

    PrivacyBadger installed, but deactivated on the Firefox Extension page: OK. Folders are shown.
    PrivacyBadger installed and activated: Bad. Folders not visible.
    PrivacyBadger installed and activated, but deactivated for the current Zimbra site: Bad. Folders not visible. Deactivating PrivacyBadger only for this site dies not make a difference.

Occurs since the PrivacyBadger update to 2017.9.12 that was updated in my browser as of today.

Firefox: 55.0.3 (64-bit)
PrivacyBadger: 2017.9.12

**Comment by ghostwords** [comment]
Sorry about this slip up! Could you update to 2017.9.12.1 and see if that fixes the issue?

**Comment by KnuckleBob** [comment]
I updated to PrivacyBadger 2017.9.12.1 and it does indeed fix the issue.

**Comment by ghostwords** [comment]
Excellent, glad to hear.

**Comment by ghostwords** [comment]
The proper fix is tracked in #1158.
