### ISSUE TITLE
Problem with cryptocurrency exchange charts

### ISSUE THREAD

**Issue by haiqu** [EFForg/privacybadger#1666]
Latest update 2017.9.12 seems to be affecting the display of charts on both Bittrex and HitBTC exchanges.

Disbaling Privacy Badger fixes the issue.

**Comment by ghostwords** [comment]
Hi @haiqu, do you use Firefox? Does upgrading to 2017.9.12.1 fix the issue?

**Comment by haiqu** [comment]
Yes, Firefox. 2017.9.12.1 seems to work, thanks.

**Comment by ghostwords** [comment]
Excellent! Sorry for the trouble.

**Comment by ghostwords** [comment]
The proper fix is tracked in #1158.
