### ISSUE TITLE
hompage update

### ISSUE THREAD

**Issue by DJCrashdummy** [EFForg/privacybadger#1668]
in the [FAQs](https://www.eff.org/privacybadger#faq-Will-you-be-supporting-any-other-browsers-besides-Chrome-/-Firefox-/-Opera?) it is stated:

> At some point we may try to release Privacy Badger for Microsoft Edge and Firefox Mobile.

isn't it available for Firefox on Android for quite a while now?

**Comment by ghostwords** [comment]
It's not, [not yet](https://github.com/EFForg/privacybadger/issues/1276#issuecomment-327208851), although we've gotten closer to supporting it with the 2017.9.12 update (https://github.com/EFForg/privacybadger/pull/1516#issuecomment-323632263).

**Comment by DJCrashdummy** [comment]
what the heck... i missed this one again.
sorry for being blind the last day! :disappointed:

**Comment by ghostwords** [comment]
No need to apologize. Thanks for your thoughtful suggestions!
