### ISSUE TITLE
Extension doesn't work in FF android 57 (current alpha release)

### ISSUE THREAD

**Issue by lemnis** [EFForg/privacybadger#1671]
Bug report for everyone that encounters this bug, while I don't expect that someone will.

Quickly tested the extension, unfortunately, some new code within FF broke the extension. Probably the result of another bug report that I created. 😞  

Created a bug report https://bugzilla.mozilla.org/show_bug.cgi?id=1399954 . I expect that the Mozilla team will fix it in the near future, as result, I will not change our source code for a tempory fix.

**Comment by ghostwords** [comment]
Thanks for filing the issue, and letting us know!

**Comment by gorhill** [comment]
> `chrome.tabs.query({active: true, lastFocusedWindow: true}, callback);` should always return the current tab except when a popup is opened.

Shouldn't be the following instead?

> `chrome.tabs.query({active: true, currentWindow: true}, callback);`

**Comment by lemnis** [comment]
@gorhill Yes, it is a lazy copy-paste error, but both should. FF android can only have 1 window, still, I should update the code to the correct query.
