### ISSUE TITLE
Export user data doesn't open file download dialog in Firefox

### ISSUE THREAD

**Issue by jony0008** [EFForg/privacybadger#1674]
When clicking Export user data it opens an other tab with a long URL, no file will be downloaded.

**Comment by lemnis** [comment]
Which browser are you using and which version of privacy badger?

**Comment by jony0008** [comment]
FF ESR 52.3.0 and PB 2017.9.12.1

**Comment by lemnis** [comment]
Probably I should have asked you first if there is anything on that loaded page? 

If so, you just save that page with any name you want for example `privacy-badger.json` and then you can use that file for importing.
I don't know why you and I on a clean profile don't get a nice save dialog...

If my assumption is wrong, and you got a blank page, then I unfortunately do not know what is happening.

Let me know what is the correct answer 😉

**Comment by jony0008** [comment]
Yes, there is a string starting with {"action_map":{"fonts.googleapis.com":{"userAction":"","dnt":false,"heuristicAction":" etc.

Why doesn't it just download the file?

**Comment by lemnis** [comment]
It's a [browser bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1379960).

But I found out after some trial and error that you can 'fix' the issue by installing the lastpass addon.

@ghostwords You can probably close this issue

**Comment by ghostwords** [comment]
Thanks @lemnis for hunting down the Firefox bug! I'll keep this open until https://bugzilla.mozilla.org/show_bug.cgi?id=1379960 is resolved.

**Comment by ghostwords** [comment]
It sounds like there is a workaround, if we wanted to fix this ourselves:
>Placing the link inside an about:blank frame within the extension page allows working around this issue, downloading works for both data: and blob: URLs then.
