### ISSUE TITLE
NOT an issue, just a question regarding PB operating mode

### ISSUE THREAD

**Issue by marcelmfs** [EFForg/privacybadger#1680]
Hi,

I have PB installed in all Chrome browsers across all my PCs, and I love it even when it breaks some websites. But I have a question regarding how PB's backend works for URLs not found in your database.

Do you crawl new URLs? If so, what is the User Agent being used? What are the IP address pool being used to source the crawling? Couldn't find any information regarding these questions in your FAQ.

I'm asking this because recently I was developing a new api endpoint, while using chrome to test it, suddenly I started seeing requests being made from Japan, then after blocking those, from Amazon, and so on.

One piece of advice, if you're indeed crawling new URLs for the sake of ranking the site in your system, please do so with a User Agent signature that identify you.

Thank you.

**Comment by ghostwords** [comment]
[Privacy Badger does not come with a database](https://www.eff.org/privacybadger#faq-Does-Privacy-Badger-contain-a-"black-list"-of-blocked-sites?); it learns which domains to block by watching your browsing and discovering tracking as it happens. All this learning is local to each of your Privacy Badger installations. Privacy Badger does not share what it learns with us or anybody else, not yet anyway (#1299).

What did those requests look like? You might be seeing your own Privacy Badgers perform checks for the [EFF Do Not Track policy](https://www.eff.org/dnt-policy).

**Comment by marcelmfs** [comment]
As I've said, it was an isolated environment and the only explanation for requests coming from strange IPs was the usage of the extension. Using safari without PB wasn't generating any requests to newly developed URI's. Well, if there's no backend from EFF's crawling websites leaked by the extension I'll go ahead and close this issue.

**Comment by ghostwords** [comment]
Related: #1675.
