### ISSUE TITLE
Add validation to site whitelisting form on the options page

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1684]
The form should accept domain-like inputs only. URLs should be automatically corrected to domains.

Following up on https://github.com/EFForg/privacybadger/issues/1607#issuecomment-331289343.

**Comment by n-sayenko** [comment]
Hey I'm working on this right now, I've got domains validated and URLs automatically correcting to domains, but I'm not sure how to display a message to say "Please a valid domain or URL" when the user inputs something else. Is the message supposed to go into `src/_locales/en_US/messages.json` ? 

Apologies if I'm missing something really obvious, this is my first issue.
