### ISSUE TITLE
Does EFF reach out to doubleclick etc to abide by DNT?

### ISSUE THREAD

**Issue by zikalify** [EFForg/privacybadger#1686]
Sorry if this is the wrong place for it but the one thing I see blocked everywhere I go is Google's doubleclick. Does the EFF or volunteers attempt to reach out to the ad providers to get them onboard with DNT? If not how do websites which run these network's ads join DNT without changing their ad provider?

**Comment by koops76** [comment]
@zikalify They do not care (doubleclick, not EFF).

**Comment by alanton** [comment]
@zikalify Great question. Yes, we have reached out to Google/doubleclick but without success. We are also talking to other ad networks. For now the options are basically to serve first party ads from your own servers (and follow the DNT policy) or speak to Adzerk.

We will add to this soon, as it is a priority for us.

**Comment by dhowe** [comment]
I just wanted to chime in here that this seems an essential component of the DNT effort; that is, to have at least one agency, large or small, that we can recommend to sites who wants to serve ads responsibly (this had been Deck for us, but sadly no more). 

As the DNT list continues to grows, it will represent a growing economic opportunity for some small ad network/agency to support itself while still doing right by users and the net (almost makes me want to start an ad network myself...)

**Comment by koops76** [comment]
I can suggest [Project Wonderful](https://www.projectwonderful.com/). They claim they only collect anonymous usage data and they do not display targeted ads since the highest bidder's ad is displayed.

**Comment by andresbase** [comment]
@dhowe I agree and we are working on a set of recommendations that we hope to be able to add more companies in time. We'll keep you posted.

**Comment by zikalify** [comment]
Almost a year on, how are things coming along with ad networks @alanton @andresbase ?

**Comment by andresbase** [comment]
@zikalify with companies still figuring their way around GDPR it's hard to say. There's been little change, you can track adoption via the automated scan here https://www.eff.org/files/effdntlist.txt
We hope that the current changes in the EU will push some of these ad networks to comply with better practices but that's still a fight that we'll have to be doing for the next couple of years.

Some of these battles have already started for example: https://www.forbrukerradet.no/side/facebook-and-google-manipulate-users-into-sharing-personal-data/

We hope to be publishing more posts about it as things develop.
