### ISSUE TITLE
sites that set cookies via javascript are not added to the heuristic

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadger#169]
Currently if a 3rd party only ever sets cookies via JS it will never be detected by the heuristic. We should fix this.

**Comment by ghostwords** [comment]
Yes, but cookies set via JavaScript get a free pass when they are set (vs. cookies set headers which are detected as they are being set), right?

For example, when you first visit SITE1 in [this cookie test](https://github.com/EFForg/privacybadger/blob/02d5d9d64f45b2b8bae72f621b4404ff607ee211/tests/selenium/cookie_test.py#L31-L81), PB doesn't see any tracking and `snitch_map` is empty. (The rest of the test: Visiting SITE2 picks up tracking for the first time, SITE3 for the second, reloading SITE1 activates blocking.)
