### ISSUE TITLE
Allow disabling of individual heuristic detection methods

### ISSUE THREAD

**Issue by zero77** [EFForg/privacybadger#1691]
Can you please add an option for users to manually enable or disable each fingerprinting method individually.

For example, there would be no point in detecting cookie fingerprinting if you use an add on like “cookie auto delete” that removes all cookies from a domain, when you leave that domain. 

Also, if you have disabled canvas support.

Furthermore, this would then save system resources by not carrying out unnecessary tasks.

Thanks

**Comment by ghostwords** [comment]
Related to #740.

**Comment by ghostwords** [comment]
Closing as the potential performance benefits do not seem to justify the implementation/additional complexity/maintenance costs.
