### ISSUE TITLE
Export data button not working on Firefox 57

### ISSUE THREAD

**Issue by shapiro125** [EFForg/privacybadger#1697]
I know this was referenced as fixed in some other issues, but I'm continuing to have a problem where I can't export data in PB 2017.9.12.1 on Firefox 57.0b3.

If I click the "export data" button, nothing happens. It doesn't open a JSON code dump, it doesn't download a file, it's just unresponsive.

Thanks!

**Comment by ghostwords** [comment]
Confirm this is an issue on 57.0b3, but was not an issue on 57.0a1. (Firefox 57.0b3 in general seems to be a mess, at least with Privacy Badger. Pages take forever to load, Privacy Badger doesn't seem to be learning properly.)

**Comment by alexristich** [comment]
I checked in Firefox 57.0.3 and it looks like this might be working now.

That being said, I do find it a bit confusing that clicking this button displays the content in Firefox's built-in JSON viewer (https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer).

Certainly technical users will be more than capable of locating the "Save" icon that appears on this page, though I think it would be much better to have this button trigger a download dialogue. Thoughts?

**Comment by ghostwords** [comment]
Sounds like this got fixed by Firefox. Fixing the file download dialog is happening in #1807.

**Comment by alexristich** [comment]
Oi, I ought to spend a bit more time getting familiar with the state of affairs; thanks for the link!
