### ISSUE TITLE
Popup UI doesn't display if navigation bar is hidden

### ISSUE THREAD

**Issue by scarum44** [EFForg/privacybadger#1701]
I use Privacy Badger on Firefox with Vimperator, with the Privacy Badger button moved to the Liberator Statusline Toolbar, and the navigation toolbar hidden.  If I click or doubleclick the PB button, nothing happens.  However, if I un-hide the navigation bar with ":set gui=navigation", the PB button works normally.  I also have the NoScript button in the same configuration, and it doesn't seem to have this issue.

Thanks!

**Comment by ghostwords** [comment]
Ah, this came up previously, and there is a workaround: https://github.com/EFForg/privacybadger/issues/1308#issuecomment-293193927.
