### ISSUE TITLE
Privacy Badger is chewing up half of Firefox's CPU 

### ISSUE THREAD

**Issue by lsatenstein** [EFForg/privacybadger#1707]
Firefox version 56, Fedora Linux 27,  installed add-ons xmarks, PB, LastPass and 3 dictionaries.

Without PB, 5.5%, with PB 12.5% cpu, on quad core q9650CPU. 

System has 8gigs ram 64bit

**Comment by ghostwords** [comment]
Hello!

Have you used Badger in the past without running into this problem, or are you a new user?

Does Privacy Badger seem to use excessive CPU all the time, or only at certain times?

Does unchecking "Check if sites comply with EFF's Do Not Track policy" on Privacy Badger's options page (under the General Settings tab) make a difference?

**Comment by lsatenstein** [comment]
I use Fedora Linux.  I have been a Firefox user for over 10 years and a privacy badger since the day it was announced.  With Firefox 56, the cpu utilisation is 14% steady. 
Installed are:
3 dictionaries  English Canada, English USA and French 
Privacy Badger.
LastPass password manager.
Not installed any longer is xmarks

Using the Linux Top command... 
I disabled one by one to recognize the cpu problem my system is experiencing.  Privacy badger does not show in Top, only Firefox. There is something wrong.  Firefox is executing at "nice level 20"

**Comment by ghostwords** [comment]
Ah, it sounds like we might have introduced a performance issue with the latest (2017.9.12.1) release. It's also possible you are experiencing increased load because of a Firefox upgrade.

Do you notice any pattern to excessive CPU usage? Does it happen all the time, or only when loading pages?

Does unchecking "Check if sites comply with EFF's Do Not Track policy" on Privacy Badger's options page (under the General Settings tab) make a difference?

**Comment by ghostwords** [comment]
@lsatenstein Do you notice any improvements after updating to Privacy Badger version 2017.10.25.1?

**Comment by lsatenstein** [comment]
I am on 9 12 1  version, will upgrade and see what happens and get back to your
 Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

**Comment by lsatenstein** [comment]
Yes, its no longer a hog.  2017.9 12 1 version.  I have not seen the update.  If it is a heavy cpu user, post bug with mozilla.
 Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

**Comment by ghostwords** [comment]
You can get the update now by going to `about:addons` and clicking "Check for Updates" in the dropdown you get by clicking on the gear button next to the "Search all add-ons" input box.

**Comment by lsatenstein** [comment]
Your version (from the PB site) states that it is not for Firefox, but for chrome / chromium.  

Use Firefox add-ins to delete your existing version and install the FF compatible version (search add-ons)
 Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

**Comment by ghostwords** [comment]
I am not sure what you mean. Privacy Badger's latest version is 2017.10.25.1 on all browsers. Here is a screenshot of the `about:addons` page I was talking about in [my previous comment](https://github.com/EFForg/privacybadger/issues/1707#issuecomment-340021826):
![screenshot from 2017-11-08 12 58 40](https://user-images.githubusercontent.com/794578/32565286-a20630f4-c484-11e7-9fa8-06e73990ef99.png)

**Comment by groovecoder** [comment]
Note: we had a bugzilla bug come in a few months ago re: Privacy Badger performance too: https://bugzilla.mozilla.org/show_bug.cgi?id=1395625

**Comment by ghostwords** [comment]
If you are still experiencing performance problems with Privacy Badger, please open a new issue.
