### ISSUE TITLE
Block mining scripts

### ISSUE THREAD

**Issue by ricardo3m** [EFForg/privacybadger#1714]
Can you add an option to block mining scripts? Sites like the one below eat up 100% CPU because of digital currency mining scripts.

http://www.cristianoronaldo.com

**Comment by ghostwords** [comment]
Wow, this is so disrespectful of your visitors. `https://coinhive.com/lib/coinhive.min.js` seems to be the script. I can recommend [uBlock Origin](https://github.com/gorhill/uBlock)'s [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) to globally block resources from `coinhive.com`.

**Comment by ghostwords** [comment]
It looks like `coinhive.com` is already on their [resource-abuse.txt](https://github.com/uBlockOrigin/uAssets/blob/c277e5ed63f085fc5b110e419e25037ac046690f/filters/resource-abuse.txt) filter list. Not sure why that filter list isn't active in my default installation though.

**Comment by ricardo3m** [comment]
I don't want to use any other extension as having a lot of extensions increases the consumption of resources. It would be a nice feature if it was added to privacy badger. These type of scripts are an abuse and disrespect to the visitors.

**Comment by terrorist96** [comment]
>It looks like coinhive.com is already on uBlock Origin's resource-abuse.txt filter list. Not sure why that filter list isn't active in my default installation though.

It's rolling out slowly.

**Comment by terrorist96** [comment]
>I don't want to use any other extension as having a lot of extensions increases the consumption of resources. It would be a nice feature if it was added to privacy badger. These type of scripts are an abuse and disrespect to the visitors.

PB is only for combatting tracking though. These aren't tracking. You really should install uBlock Origin. If anything, it will speed up your browsing by blocking all ads/tracking/etc.

**Comment by mario-d-s** [comment]
Is this still a problem? I agree with @terrorist96 this is out of scope for privacy badger. Perhaps the issue should just be closed?

**Comment by ghostwords** [comment]
Sure, let's close this for now.
