### ISSUE TITLE
Fix DNT-compliant domain list endpoint updating

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1719]
Updating broke around January 1st: https://www.eff.org/files/effdntlist.txt.

Let's also see if we should replace the site list we use for checking: https://blog.majestic.com/development/alexa-top-1-million-sites-retired-heres-majestic-million/.

**Comment by ghostwords** [comment]
Related to #1124.

**Comment by bcyphers** [comment]
Closed. The updated script is up and running, and  https://www.eff.org/files/effdntlist.txt is up-to-date.

**Comment by ghostwords** [comment]
Did updating break again?
>! Last Scanned: Wed Jun 13 00:00:03 PDT 2018

-- https://www.eff.org/files/effdntlist.txt

The repo is getting updated though: https://github.com/EFForg/dntscan/commits/master

Should we set up some kind of simple monitoring? Something to mail us if a URL (https://www.eff.org/files/effdntlist.txt) didn't change after a day.

**Comment by bcyphers** [comment]
Found the issue. After we merged the git-pull branch of https://github.com/EFForg/dntscan into master, I forgot to checkout master on the machine that updates the public list. Fixed now.
