### ISSUE TITLE
Opera cannot connect to localhost with Privacy Badger enabled

### ISSUE THREAD

**Issue by hdasch** [EFForg/privacybadger#1722]
Using Opera, localhost URLs result in "connection refused".  This happens unless Privacy Badger is disabled.  If Privacy Badger is enabled, the issue exists even when localhost "disabled for this site". 

Further, `tcpdump -i lo port xxxx` does not report any network traffic, suggesting the "connection refused" error was generated internally.

Firefox, Chromium, and Vivaldi do not exhibit the same problem.

Sample server available at https://gist.github.com/hdasch/963e715864ddd0573a7709b6bc398f28

**Comment by ghostwords** [comment]
When this happens, does Privacy Badger report anything blocked on that page? Does clicking "Disable Privacy Badger for This Site" help?

**Comment by hdasch** [comment]
On Mon, Oct 16, 2017 at 2:46 PM, Alexei <notifications@github.com> wrote:

> When this happens, does Privacy Badger report anything blocked on that
> page? Does clicking "Disable Privacy Badger for This Site" help?
>
No, Privacy Badger does not report anything blocked.  The "Connection
refused" seems to prevent it from accessing the URL altogether.

Disabling Privacy Badger for the site still results in "Connection refused".

Disabling Privacy Badger globally (Managing Extensions settings) does
resolve the issue.

Hugh

**Comment by ghostwords** [comment]
Is this an issue with any other resource blocking extension (such as [uBlock Origin](https://addons.opera.com/en/extensions/details/ublock/))?

**Comment by hdasch** [comment]
On Mon, Oct 16, 2017 at 3:17 PM, Alexei <notifications@github.com> wrote:

> Is this an issue with any other resource blocking extension (such as uBlock
> Origin <https://addons.opera.com/en/extensions/details/ublock/>)?
>
Seems to be.  Privacy Badger was the only extension installed when I
reported the error.  So, I disabled Privacy Badger and installed uBlock
Origin.  When enabled globally, uBlock Origin produces the same "Connection
refused" error.

So it's a browser rather than an extension issue?

Hugh

**Comment by ghostwords** [comment]
Yes, I think so. I suggest reporting this to Opera. If you can, please link to the report from here.

**Comment by hdasch** [comment]
On Mon, Oct 16, 2017 at 3:46 PM, Alexei <notifications@github.com> wrote:

> Yes, I think so. I suggest reporting this to Opera. If you can, please
> link to the report from here.
>
Will do.  Thanks.

Hugh

**Comment by ghostwords** [comment]
Resolving for now as a browser bug.
