### ISSUE TITLE
privacybadger stopped running in chrome but cannot reinstall

### ISSUE THREAD

**Issue by simply-does-it** [EFForg/privacybadger#1723]
First, I'm not a techie, just a user on the advice of the younger generation (away on business).
I'm using Chrome 55.0.2883.75 m (64-bit).
Today, I opened Chrome showing some message about PB having stopped. 
There was a little window with the PB logo, but it disappeared before I worked out what its relevance might have been.
Looking in Extensions, the PB installed extension has disappeared.
So I went to Chrome web store and tried to download/reinstall the PB extension. However, the window indicates that PB is already installed.
Please would you advise how to sort this problem.
Thanking you in advance for your help.

**Comment by ghostwords** [comment]
Hello! Does restarting the browser help? Is Privacy Badger really nowhere to be found if you visit `chrome://extensions`?

By the way, Chrome 55 is a pretty old version; you should upgrade to the latest release (Chrome 61, I think).

**Comment by ghostwords** [comment]
I'm going to close this for now. Let me know if you have more information.
