### ISSUE TITLE
Can't install privacybadger on Firefox android

### ISSUE THREAD

**Issue by lemnis** [EFForg/privacybadger#1725]
The exact opposite of https://github.com/EFForg/privacybadger/issues/1276

I'm trying to install privacy badger from the Firefox add-on page, but got this message:

> This add-on is not available on your platform

It's should be possible I suppose because it's has been (beta) released.

Tested in FF 56, 57, 58

**Comment by ghostwords** [comment]
It sounds like AMO fixed https://github.com/mozilla/addons/issues/348 without updating the GitHub issue.

**Comment by ghostwords** [comment]
If we allow Android users to install from AMO, we should then also update Privacy Badger's homepage (#1668).

**Comment by ghostwords** [comment]
I can mark the next AMO release as Android-compatible and announce "beta" Android support in release notes. @andresbase How does this sound? Could you handle getting https://www.eff.org/pb updated to note beta support for and offer a download button on Firefox on Android?

**Comment by andresbase** [comment]
Sounds good, checking to make the changes in eff.org/pb

**Comment by ghostwords** [comment]
OK, you should be able to install Privacy Badger 2017.10.25.1 on Firefox on Android now. Still have to update https://www.eff.org/pb with new messaging regarding Badger being in Beta on Firefox on Android.

**Comment by jawz101** [comment]
You're doing the Lord's work @cowlicks @cooperq @ghostwords  and all :+1:

**Comment by ghostwords** [comment]
You should now see updated messaging that will let you install the eff.org-hosted Privacy Badger version when visiting [Privacy Badger's homepage](https://www.eff.org/privacybadger) on Firefox on Android.
