### ISSUE TITLE
PB breakes Pricerunner website

### ISSUE THREAD

**Issue by jony0008** [EFForg/privacybadger#1726]
PB breakes all pictures on Pricerunner.se, Pricerunner.co.uk etc.

**Comment by ghostwords** [comment]
Seems related to #1253.

**Comment by jony0008** [comment]
@ghostwords I got this:

**** ACTION_MAP for pricerunner 
images.pricerunner.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1508710690345
} 
www.pricerunner.se {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1508250240114
} 
pricerunner.se {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
} 
research.pricerunner.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1508502524646
} 
pricerunner.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
} 
www.pricerunner.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1508280212735
} 
adrunner.pricerunner.se {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1508495119798
} 
**** SNITCH_MAP for pricerunner 
pricerunner.se [
  "megashop.se",
  "brl.se",
  "buildor.se"
] 
pricerunner.com [
  "stayhome.se",
  "hembiobutiken.se",
  "apotea.se"
]
