### ISSUE TITLE
manifest author is not a string: "Expected string" error when developing on Firefox

### ISSUE THREAD

**Issue by numberMumbler** [EFForg/privacybadger#1728]
Firefox complains that the "author" in manifest.json is not a string. The [MDN page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/author) confirms that Firefox expects a string.

Is this something you want fixed? Submitting a PR

No complaints from Chrome, and the [documentation on manifest](https://developer.chrome.com/extensions/manifest) only shows an ellipsis (no type specification).

![image](https://user-images.githubusercontent.com/3464932/31624414-d73e44d2-b25f-11e7-9fe2-43f9345e15d7.png)

Firefox 56.0.1 (32-bit)
Windows 10

**Comment by ghostwords** [comment]
We currently fix this at release time: https://github.com/EFForg/privacybadger/blob/b654b487b3696e4a9c4f011ebceb06fe7182adb1/release-utils/make-signed-xpi.sh#L30-L32

**Comment by numberMumbler** [comment]
ok 👍 I'll close the issue

**Comment by ghostwords** [comment]
I wonder why we went with a release-time fix, instead of just changing the field to a string. Would an (altered to) string author field get rejected by Chrome Web Store?

**Comment by ghostwords** [comment]
If you'd like, you can test this scenario in Chrome Web Store. Something like:
1. Upload a test extension with an author field formatted to the current Privacy Badger format.
2. Upload an update with the author field changed to string.

If this works, it's better to simplify and get rid of the build step, as well as to fix the unsightly Firefox warning.

**Comment by ghostwords** [comment]
Ah, correction: We won't be able to get rid of the release step because we use different emails in Chrome and Firefox. But still, would be good to get rid of the (dev-only) warning in Firefox.

**Comment by ghostwords** [comment]
We should also file a [Bugzilla@Mozilla](https://bugzilla.mozilla.org) issue (Firefox should fix needless incompatibility in the manifest format) if there isn't an issue for this already.

**Comment by numberMumbler** [comment]
Didn't run into any problems in Chrome changing the author format. Published the extension (from _master_), then updated it from the branch with the modified manifest file.

**Comment by numberMumbler** [comment]
hmmm. the warning was noted by Firefox's QA team on a ticket a year ago. Seems to be the expected behavior.

Here's the bug (reported by the https-everywhere team?!):

[Bug 1313567: Accept an object as the "author" in manifest.json]https://bugzilla.mozilla.org/show_bug.cgi?id=1313567)

**Comment by ghostwords** [comment]
Implemented in 29669e0a940b438f314ce051393154fdbb94077e.

**Comment by ghostwords** [comment]
We had to revert this (9cd573d808383322a08e68cdb59872a42a354a48), unfortunately, as Chrome Web Store rejected the reformatted author field:

![screenshot from 2017-10-25 17 03 08](https://user-images.githubusercontent.com/794578/32026074-adeb49c4-b9b0-11e7-9ac2-c2cd0b589470.png)
