### ISSUE TITLE
Extension not from chrome webstore

### ISSUE THREAD

**Issue by gh0sti** [EFForg/privacybadger#1733]
Chrome keeps saying that Privacy Badger isn't from the Chrome Webstore even though I just installed again from the web store after it got corrupted recently

**Comment by ghostwords** [comment]
Duplicate of #1496.

**Comment by ghostwords** [comment]
> after it got corrupted recently

How did Privacy Badger get corrupted?

**Comment by gh0sti** [comment]
idk how had that with couple of my extensions saying they were corrupted they are working now.
