### ISSUE TITLE
Feature request: Google+ button replacement

### ISSUE THREAD

**Issue by jQrgen** [EFForg/privacybadger#1734]
Yellow!

Is it possible to use this extension to block Google+ trackers? 

The reason I am asking is that on the bottom of [this site](http://www.syntaxsuccess.com/viewarticle/caching-with-rxjs-observables-in-angular-2.0) most social buttons have been replace, but the Google+ del(share in Norwegian) has not been replaced. 

![screen shot 2017-10-17 at 14 11 26](https://user-images.githubusercontent.com/3964957/31664294-2cc55b26-b345-11e7-902e-b1a2eebf582b.png)

**Comment by ghostwords** [comment]
Hi! Looks like our Google+ button replacement definitions need updating.

**Comment by John-Nenniger** [comment]
Hey there! So i've made a small fix for this by adding a new selector in 'socialwidgets.json' as you've suggested.  But I'm not allowed to push to a new branch and make a PR because I've never contributed here before.  Do you mind advising me as to the best way forward?  Thanks!

**Comment by ghostwords** [comment]
Hello! I think what you want to do is [make a pull request from a fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

**Comment by John-Nenniger** [comment]
So I think the solution here will be to first fix the race condition described in this issue: #892 , after that's fixed I don't see a problem with re-adding this selector.  I'll look into the race condition issue, though it is a much more difficult problem to solve

**Comment by ghostwords** [comment]
It looks like the fix would be to stop yellowlisting and start blocking `apis.google.com` (#1593), and to add ".g-plus" to the selector list. Yellowlisting and widget replacement do not mix well (#2267).

Although, Google+ buttons will stop functioning soon: https://developers.google.com/+/integrations-shutdown

**Comment by jQrgen** [comment]
Issue solved.

[Google+ Integrations Shutdown](https://developers.google.com/+/integrations-shutdown)

> Google+ integrations for web and mobile apps have stopped functioning as of March 7, 2019. Specifically:
> 
> Web integrations, such as Plugins and Interactive Posts, have stopped serving. This has the potential to affect website layouts and/or functionality if no action is taken by website owners. Mobile app integrations, such as +1 buttons, sharing to Google+, and app activities, will cease to function.
> 
> Developers are strongly advised to remove related code from their websites and/or mobile apps as soon as possible. Google+ APIs and Google+ Sign-in have also been shut down. Please see this additional notice.
> 
> While we’re sunsetting Google+ for consumers, we’re investing in Google+ for enterprise organizations. They can expect a new look and new features -- more information is available in our blog post.
>
