### ISSUE TITLE
Bundle pb with firefox

### ISSUE THREAD

**Issue by zikalify** [EFForg/privacybadger#1740]
I've got a suggestion: EFF and Mozilla partner to include pb in all Firefox installs, pb instantly appears on 13% of desktop browsers (http://gs.statcounter.com/browser-market-share/desktop/worldwide) giving it much more leverage over advertisers and Mozilla gets something to add to its roster to boast about when it goes on about being interested in privacy.

**Comment by koops76** [comment]
@zikalify This is not going to work, including HTTPS Everywhere functionality with Firefox could though.

**Comment by koops76** [comment]
Maybe if PB functionality would only be active in private browsing mode.

**Comment by zikalify** [comment]
Why wouldn't it work? Pb runs fine in normal browsing mode.

**Comment by andresbase** [comment]
I would love to see this happen one day. 

[WARP](https://www.eff.org/deeplinks/2016/11/delivering-privacy-badger-and-https-everywhere-mobile-users-warp-speed) for example does this, but it's based on Chrome. 
Considering [Apple's ITP](https://webkit.org/blog/7675/intelligent-tracking-prevention/), the GDPR/ePrivacy and where the industry is going, it would make sense for Mozilla to do this by default.
Note that Firefox already has some tracking protection when you are in [Private Browsing](https://www.mozilla.org/en-US/firefox/features/private-browsing/)

I believe there are several things that need to happen for this to be possible.

* First and foremost is the user experience; few sites that break, easy to use and mostly hands-free. I feel like we are getting there, for sure if you look at the work from the team it's been focused on exactly that. And we've seen a good decrease in reported errors.

* Second mobile (Including a change in UI). We are getting amazing contributions from @lemnis, @ghinda, @koops76 just to mention a few, that are making this possible.

I hope that at least their tracking protection offered in Private Browsing will be offered by default whether you are browsing privately or not. But that's a question for Mozilla on how they see their users' privacy and the user experience.

**Comment by ghostwords** [comment]
Agreed! Perhaps one day.
