### ISSUE TITLE
Domain slider tooltip only appears when hovering over bottom section of slider

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1746]
On the Oct 25 release, if you hover your mouse over the sliders, the tooltip does not appear unless you move your mouse slightly below the slider itself (by changing your pointer from the clicker/4 directional arrows to the regular arrow).

**Comment by ghostwords** [comment]
This was a problem with the previous versions too, I believe (https://github.com/EFForg/privacybadger/pull/1704#issuecomment-333715682). Regardless, we should fix.

**Comment by ghostwords** [comment]
Some thoughts on this subject in #1821.

**Comment by alexristich** [comment]
To add to my thoughts from #1821, here's where I'm at with this one:

1) There's a bit of mixed messaging. The tooltips say `Click here...`, and these give no indication that the toggle is actually a draggable slider. This naturally leads to the question of how important the sliding behavior actually is.

2) I think I might have figured out a way to have the tooltips display, though it'd take some work to implement and verify it works as desired. The main idea is adding a `$().mousemove()` listener to the `switch-toggle` div, tracking the position of the mouse, doing a bit of math to find which third of the slider the mouse is currently in, then triggering that subsequent tooltip. We can find the relevant `actionToggle` element by referring to the `childNodes` property from the `mousemove()` event.
I've looked a bit and it seems like manually triggering the Tooltipster tooltip shouldn't be too difficult (see 'open' here: https://iamceege.github.io/tooltipster/#methods). A `$().mouseleave()` listener would also need to be added to close the relevant tooltip when the mouse leaves a given slider.

Thoughts on whether the proposed approach is worth pursuing further?

**Comment by ghostwords** [comment]
I think the tooltips' text is fine; the tooltips don't need to explain that the sliders are draggable control. Clicking is probably the primary way to interact here, dragging is secondary.

I don't recommend getting deep into a fix for this bug as the sliders should not be important for non-power users. Which means the sliders will keep getting de-emphasized, which means we shouldn't spend much time on this particular visual nit.

**Comment by alexristich** [comment]
As discussed, this is still an issue but a complex solution like that I suggested above is more work than this merits right now. It's probably easier to handle state with a UI framework like React, though perhaps someone else will have a better idea of how to accomplish the same thing without needing to introduce a new framework.
