### ISSUE TITLE
Add changelog to eff.org-hosted releases in Firefox

### ISSUE THREAD

**Issue by forteller** [EFForg/privacybadger#1749]
The recent update did not have any changelog attached. That makes me go look for it other places, like here, where I still couldn't find it. I'd appreciate it a lot if you'd add it to the next release. Thank you! :)

![screenshot from 2017-10-28 05-16-57](https://user-images.githubusercontent.com/343561/32130816-cb11f284-bb8e-11e7-9394-554e53993cae.png)

**Comment by ghostwords** [comment]
Are you looking at the recent updates tab on Firefox's `about:addons` page?

We do have a changelog, [here](https://github.com/EFForg/privacybadger/blob/master/doc/Changelog). You can also see the release notes under Version Information (on the bottom of the page) on [Privacy Badger's Firefox add-on listing](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/#detail-relnotes). We also email the notes upon releasing Privacy Badger updates to our [mailing list](https://lists.eff.org/mailman/listinfo/privacybadger).

**Comment by ghostwords** [comment]
Previously: https://github.com/EFForg/privacybadgerfirefox-legacy/issues/688.

**Comment by ghostwords** [comment]
Are [these](https://www.reddit.com/r/firefox/comments/74yoxz/read_extension_update_changelog_inside/) the steps to get to see the "Show Release Notes" link? I haven't yet been able to find any relevant developer documentation for this link.

**Comment by ghostwords** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1412528 to get some answers.

**Comment by forteller** [comment]
> Are you looking at the recent updates tab on Firefox's about:addons page?

Yes, that's exactly right. Sorry, I should've been more specific. Thank you for working on this! I'm afraid I can't help you as I've never made an addon myself.

**Comment by ghostwords** [comment]
@forteller Is your version of Privacy Badger from [AMO](addons.mozilla.org/en-US/firefox/addon/privacy-badger17/) or [eff.org](https://www.eff.org/privacybadger)? If you are not sure, what does it say when you click on the More link in its listing on `about:addons`?

**Comment by forteller** [comment]
Yeah, I'm not sure, so here's a screenshot:

![screenshot from 2017-11-01 20-14-18](https://user-images.githubusercontent.com/343561/32292743-eed01e3c-bf38-11e7-98c9-99f15927ce05.png)

**Comment by ghostwords** [comment]
Ah yes, you have the self-hosted version from eff.org.

According to https://bugzilla.mozilla.org/show_bug.cgi?id=1412528#c5, I should be able to set this up by adding `update_info_url` to https://www.eff.org/files/privacy-badger-updates.json and setting up the referenced update info file.

**Comment by ghostwords** [comment]
Confirmed, the AMO-hosted version already has this feature:
![screenshot from 2017-11-09 18 10 55](https://user-images.githubusercontent.com/794578/32634442-ab8e1006-c579-11e7-9855-f856354d1b61.png)

**Comment by forteller** [comment]
I see. Is there any reason for me not to switch? I guess the AMO version is also webextension now so I can use it in Nightly. Will I keep my settings? Thanks!

**Comment by ghostwords** [comment]
It's the same code, just installed and updated from two different servers (`addons.mozilla.org` and `eff.org`). When we do an update, we push the update to both places at approximately the same time. The two versions are technically distinct add-ons, so without manual exporting/importing, your settings will be lost.

**Comment by ghostwords** [comment]
This is unlikely to happen as the cost/benefit tradeoff does not appear favorable.
