### ISSUE TITLE
Adblocker wall over history.com videos

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1753]
https://www.history.com/news/history-lists/7-things-you-might-not-know-about-the-u-s-supreme-court

![image](https://user-images.githubusercontent.com/12802056/32197021-1b009528-bd99-11e7-95a1-393de01646c8.png)

**Comment by ghostwords** [comment]
Related to #1596.

**Comment by terrorist96** [comment]
https://www.nbcnewyork.com/news/local/Pedestrians-Struck-Hit-Manhattan-Liberty-Street-Broadway-Police-462585423.html

`mssl.fwmrm.net` breaks second video. Plus `cdn.krxd.net` needs to be moved to green (#1359 ).

**Comment by andresbase** [comment]
Added to emails sending to companies on why this is inaccurate. Thanks.

**Comment by terrorist96** [comment]
@ghostwords FYI the video link in the OP is still blocked for me.

**Comment by ghostwords** [comment]
OK, I see it, thanks.

It looks like you have to allow some combination of `amazon-adsystem.com` subdomains, `googleads.g.doubleclick.net`, `securepubads.g.doubleclick.net` and maybe `adservice.google.com`.

At this point this is a duplicate of #1596.

**Comment by ghostwords** [comment]
Whoops, and we already have an issue for this, #2053.
