### ISSUE TITLE
jQuery freezes PrivacyBadger

### ISSUE THREAD

**Issue by rugk** [EFForg/privacybadger#1763]
When clicking on the PrivacyBadger icon, the browser freezes. At some point the "JS is slowing down your browser pop-ups…"

It mentions this URL: ` moz-extension://48e8a53b-891a-…lib/vendor/jquery-2.2.4.min.js:4`

Firefox 56, 2017.10.25.1

**Comment by ghostwords** [comment]
Does this happen everywhere, or only on certain pages? (Does it happen on the `about:addons` page?)

**Comment by rugk** [comment]
Everywhere.

**Comment by ghostwords** [comment]
Do this happen if you install Privacy Badger into the same Firefox launched with a fresh profile?

**Comment by rugk** [comment]
I could not ecven reproduce it now with the normal profile. Maybe fixed itself, maybe just strange…

**Comment by ghostwords** [comment]
OK, thanks for letting us know. I haven't gotten any other reports of this, but clearly it happens under certain circumstances. Would be good to figure out what those circumstances are.

**Comment by ur-n1ghtmar3** [comment]
Hello! I've got the same problem. Happens on some sites, e.g. w3schools.com. On a clean profile Firefox just freezes to death (sites won't load, PB window won't open)

**Comment by rugk** [comment]
Yeah, could reproduce it on w3schools.com. This time, the line causing the freeze changed, however: ` moz-extension://0e936aff-a0a4-…lib/vendor/jquery-2.2.4.min.js:2`

**Comment by Bisaloo** [comment]
I had a similar issue a couple of days ago when I clicked the cog in privacy badger popup. I just restarted firefox and I haven't been able to reproduce since then.

**Comment by ghostwords** [comment]
My guess is this is somehow related to #1704, which was part of the 2017.10.25.1 update. I haven't yet been able to reproduce the issue though, which makes fixing it difficult.

**Comment by ghostwords** [comment]
Possibly related to this issue is needing to disable the tooltips added in #1704 on Firefox 52 (ESR): 2ae8d1e6be66236c5657e7543840c6032bcee724.

Triggering tooltips (by hovering over a tooltip-equipped element) in Privacy Badger's popup on Firefox 52 would freeze Firefox and eventually show an unresponsive script warning (screenshot follows), but only on pages with enough domains to produce a scrollbar in Privacy Badger's popup.

![screenshot from 2017-11-07 17 24 36](https://user-images.githubusercontent.com/794578/32521304-fee28c04-c3e0-11e7-8f23-1ba1e27d00f3.png)

**Comment by ghostwords** [comment]
However, the above problem was consistently reproducible under the right conditions, and was triggered by hovering over certain parts of the popup, not just by opening the popup.

**Comment by rugk** [comment]
But the error message is the same. BTW: Did someone try to click on the "debug script" button and at least take a screenshot?

**Comment by ghostwords** [comment]
I'm curious if this will still be an issue with Firefox 57.

**Comment by nekromoff** [comment]
![obrazok](https://user-images.githubusercontent.com/8550349/32694789-b8804bcc-c749-11e7-9469-84f7d8982d64.png)
Still an issue, definitely.

**Comment by sogood2know** [comment]
Same here

FF 56.0.2 (64-Bit) on OS X 10.10.5
Privacy Badger Version 2017.11.9 – updated 11. Nov. 2017

Error message: Skript: moz-extension://0ee6106a-eaf4-…lib/vendor/jquery-2.2.4.min.js:4

Happens on any website when clicking on the icon to open the badger. Sometimes it works for some seconds, then (or immediately) freezes, some seconds later the error message appears.

**Comment by ghostwords** [comment]
Could everyone try temporarily installing Privacy Badger from [privacy_badger-no-fancy-tooltips-in-firefox.zip](https://github.com/EFForg/privacybadger/files/1484260/privacy_badger-no-fancy-tooltips-in-firefox.zip) and using it a bit to see if it solves the problem?

To install, unpack the archive into a new folder, open Firefox, visit `about:debugging`, click the Load Temporary Add-on button, navigate to where you unpacked the archive, and select the `manifest.json` file there.

**Comment by Bisaloo** [comment]
@ghostwords, the only difference with the "normal" Privacy Badger is purely cosmetic right? This doesn't affect the security or the privacy in any way? If so, I will install it and test it.

**Comment by ghostwords** [comment]
What I posted above is the latest Privacy Badger codebase from GitHub, with a tweak to disable the new tooltips entirely in all versions of Firefox. It's not a new Privacy Badger release, it won't replace your existing Badger installation, it's just a test so that I can confirm it's what I think it is. The reason I have to do this is I still can't reproduce the problem locally.

**Comment by vaytane** [comment]
That temp fix worked great no lockups on my end whatsoever.

**Comment by Linux-cpp-lisp** [comment]
Experiencing this issue on Firefox 57 on Linux; can confirm that the changes in the zip posted above by @ghostwords resolves the problem.

**Comment by genewitch** [comment]
was there no checkin/trunk for the temporary fix? I'm curious what it was, too.

**Comment by ghostwords** [comment]
@genewitch Not yet. You could diff the contents of the zip against the `src` directory of this repository. The only change should be tweaking the following check that disables nicer tooltips to disable them in all versions of Firefox, not just Firefox 52:
https://github.com/EFForg/privacybadger/blob/b0ae6c0b8d0aa1161f39938626bac08e79254cb6/src/js/popup.js#L32-L42

**Comment by genewitch** [comment]
@ghostwords that's what i meant, i'm not really hip to the lingo. Thank you!

**Comment by ghostwords** [comment]
I've disabled custom tooltips in the popup on all versions of Firefox in the just-released 2017.11.20 update. We should restore nicer tooltips in the future, but for now this is the quickest way to resolve browser freezing without losing too much functionality (system-powered tooltips are still present).

**Comment by vaytane** [comment]
Excellent. Thank you very much.

**Comment by ghostwords** [comment]
I just updated the [eff.org-hosted](https://www.eff.org/files/privacy-badger-latest.xpi) version of Privacy Badger to version 2020.6.25. (The [AMO-hosted](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/) (`addons.mozilla.org`) version is still on 2020.6.2 until next week.)

The new version has fancy tooltips re-enabled in Firefox. Could you give the new version a try in Firefox and let me know if the hanging/freezing is back? Thank you!

(Note that if you already have Privacy Badger installed from Mozilla, installing from eff.org will give you two copies of Privacy Badger. There is no reason to have two copies of Privacy Badger.)
