### ISSUE TITLE
Blocking Google Analytics breaks flipagram

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1767]
https://flipagram.com/

Select any video. Then select any video on the right "related videos" section. Won't work unless you right click>open in new tab. (Or let the selected video finish and it won't auto-advance to the next video). Also breaks comments. Also can't click on the person's profile (bottom left of video). And heart button broken.

**Comment by LoganDark** [comment]
Sounds like their problem. If they decide to break the site when you don't want them tracking you, then the site is broken I guess.

**Comment by ghostwords** [comment]
Looks like this was "fixed" in uBlock Origin by allowing Google Analytics on `flipagram.com`: https://github.com/uBlockOrigin/uAssets/issues/820.

**Comment by LoganDark** [comment]
LOL

**Comment by ghostwords** [comment]
Site appears to be defunct at this point.
