### ISSUE TITLE
Aristocrat Pokies

### ISSUE THREAD

**Issue by Herefyrth** [EFForg/privacybadger#1769]
Please block www.drazens.com

**Comment by ghostwords** [comment]
What is it and where can we find examples of it?

Note that Privacy Badger [does not function via blacklists](https://www.eff.org/privacybadger#faq-Does-Privacy-Badger-contain-a-"black-list"-of-blocked-sites?).

**Comment by ghostwords** [comment]
I'm going to resolve this for. Let me know if you have more information.

**Comment by Herefyrth** [comment]
Thank you, Alexei. All I know is that that site hijacks me, usually from
Knaben.com
