### ISSUE TITLE
Crashes Android Firefox when signing into an improperly configured firewall

### ISSUE THREAD

**Issue by ghillebrand** [EFForg/privacybadger#1772]
When connecting through wifi that is behind a Fortigate firewall without a local certificate (ie no proper local secure connection),  with PB enabled, Android Firefox crashes. Disable PB, then log in to the firewall, then enable PB again, and everything works.

I would be happy with an error message about  secure connection issues (which is what FF itself reports when trying to establish a secure connection through the firewall before authentication), but I don't think it should crash.

Please contact me if this is not clear!
Grant H
Versions:
Firefox 56.0, Android 6.0.1 MMB29M, PB 2017.11.9

**Comment by ghostwords** [comment]
This sounds like a Firefox bug, perhaps related to #1324. Is this still a problem with Firefox 57?

**Comment by ghillebrand** [comment]
The latest FF I can see for my phone is 56
ito #1324 When I try https://repos.archlinux.org/ with the cancel option, I get to the 401 page, as expected - no crash.
Without PB enabled, and no validation at the firewall, the browser returns an improperly configured site security error. With PB, I get the crash. I'm at home at the moment, so can't test it, but could try to get screenshots in the morning.
Would it be helpful to test PB on Firefox under Windows10? I currently run NoScript on the Windows platform, so thought that PB would be redundant. But I can then run winshark and get the transaction details.

**Comment by ghillebrand** [comment]
FF 57 on my Android fixes this. 
The response is still ugly, but that is a badly configured web site, not FF or PB!
Thanks for all the efforts

**Comment by ghostwords** [comment]
Thank you for the update!
