### ISSUE TITLE
Unexpected property in manifest warning in Firefox about options_page

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/privacybadger#1774]
When visiting `about:debugging#addons`, there is a warning:

![screenshot from 2017-11-14 16-03-59](https://user-images.githubusercontent.com/10783929/32786899-768372a4-c955-11e7-8d71-de8fa4c04c66.png)

Text version of the warning:

> Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.

**Comment by Bisaloo** [comment]
This was already present in https://github.com/EFForg/privacybadger/issues/1728 but it focused on the issue about the author field and was closed before this warning got fixed.

**Comment by ghostwords** [comment]
You can learn more about `options_page` [here](https://developer.chrome.com/extensions/optionsV2#migration); the gist is that Chrome and Firefox want us to display options within their Manage Extensions pages instead having Privacy Badger options open their own separate page.

I tested replacing `options_page` with `options_ui` briefly in both browsers; at first glance it seemed like the options page worked in Chrome, but tab switching seemed broken in Firefox. We'll probably have to switch eventually, but as of now it seems like extra work for little gain.

**Comment by lemnis** [comment]
@cowlicks Didn't it work when you set the `open_in_tab` to true? It should be a fallback when an extension is migrating to the new key. https://developer.chrome.com/extensions/optionsV2

**Comment by ghostwords** [comment]
If we can switch to `options_ui` with `open_in_tab` set in all browsers (Firefox? Firefox on Android?), cool, I will be happy to review and merge a PR.

We could do the second phase now too (switch to options-within-Manage Extensions), if somebody is interested in testing and fixing the nested-in-Manage Extensions options page in all browsers. We'd want to get rid of the redundant "Privacy Badger" logo header then too.

**Comment by LinuxOnTheDesktop** [comment]
Cf.  the following from the console (shift-ctrl-j) in Firefox 65.0.2 x64 on Windows 8.1. At least some of these lines seem related to Privacy Badger:

```
1552678537758	addons.xpi-utils	WARN	Not uninstalling invalid item because it is a proxy file
1552678538227	addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack	WARN	Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing storage: An unexpected property was found in the WebExtension manifest.
1552678538227	addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack	WARN	Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing update_url: An unexpected property was found in the WebExtension manifest.
1552678538235	addons.webextension.{287dcf75-bec6-4eec-b4f6-71948a2eea29}	WARN	Loading extension '{287dcf75-bec6-4eec-b4f6-71948a2eea29}': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
```

**Comment by ghostwords** [comment]
Yeah, these are just harmless warnings from Firefox. We use the same extension manifest file for all browsers right now, and Firefox logs warnings about some of the values (that we need there for Chrome). There shouldn't be any practical downsides to having these in Firefox though.
