### ISSUE TITLE
Opening PB / changing sliders makes Firefox unusable

### ISSUE THREAD

**Issue by codeling** [EFForg/privacybadger#1778]
Just installed PB (for my first time) in the new Firefox 57; I like the idea and the introduction was great! At the moment, unfortunately, I have a issue whenever I click on the PB icon or modify some settings in its pop-up^ - my firefox is afterwards more or less completely broken:
- PB itself doesn't pop up on a click on the icon anymore (even though the tooltip is still shown)
- I cannot load any pages in Firefox - it behaves just as if it had no internet connection (it will just show the page loading animation, without any actual page being loaded or shown)
- any other extensions having pop-up notification areas, such as the u-Block origin extension, also don't open up anymore on a click on their icon.

^  It happened once with just clicking the PB icon; most of the times I have to click on some of the sliders shown in the PB pop-up before this behavior is shown; sometimes it doesn't happen on the the first pop-up opening, but it for sure happens at some point after the second or third time.

To restore Firefox to functionality, I have to restart it.

With a quick search here in the issue tracker I couldn't find any other reports of this, if I missed them I'd be glad if somebody could point me there!
I did try this with all other extensions disabled, still the same issue.
Is there any error logs I could check (I'm new to investigating extension problems, so please be patient)?
Maybe this is some newbie error I'm making?

Edit: Just tried with a fresh profile, also happened there (albeit only after opening the PB pop-up for the third time, and changing a slider the second time; when changing the slider in the third time, it got the appearance to be "stuck" during changing the slider, and showed above described behavior again).

**Comment by ghostwords** [comment]
This sounds a bit like #1763. Would you say you are experiencing a related issue?

**Comment by ghostwords** [comment]
Does this happen on all pages, or only on pages with enough third-party domains to produce a scrollbar (https://github.com/EFForg/privacybadger/issues/1763#issuecomment-342645171)?

**Comment by Torom** [comment]
I have the same bug. I just switched from Chrome to the new Fireforx 57. It happened sometimes without clicking on the privacy badger icon, but it ist reproducible by clicking on it and changing some settings.

There ist no "JS is slowing down your browser..." message like #1763.
Firefox cannot load any pages, not in in the internet neither in LAN.

But it seems only to happen on pages with enough third-party domains to produce a scrollbar.

**Comment by ghostwords** [comment]
Could you try temporarily installing Privacy Badger from [privacy_badger-no-fancy-tooltips-in-firefox.zip](https://github.com/EFForg/privacybadger/files/1484260/privacy_badger-no-fancy-tooltips-in-firefox.zip) and using it a bit to see if it solves the problem?

To install, unpack the archive into a new folder, open Firefox, visit `about:debugging`, click the Load Temporary Add-on button, navigate to where you unpacked the archive, and select the `manifest.json` file there.

**Comment by Torom** [comment]
It seems to solve the problem. No crashes and no connection problems.

**Comment by codeling** [comment]
Thanks for the quick feedback! Unfortunately I will be able to test this the earliest tomorrow evening.

**Comment by ghostwords** [comment]
@codeling No problem, do give it a go please and let us know if the problem goes away.

**Comment by codeling** [comment]
I tried the version linked above now, and also for me, this version works without problems!

**Comment by ghostwords** [comment]
I've disabled custom tooltips in the popup on all versions of Firefox in the just-released 2017.11.20 update. We should restore nicer tooltips in the future, but for now this is the quickest way to resolve browser freezing without losing too much functionality (system-powered tooltips are still present).

**Comment by ghostwords** [comment]
I just updated the [eff.org-hosted](https://www.eff.org/files/privacy-badger-latest.xpi) version of Privacy Badger to version 2020.6.25. (The [AMO-hosted](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/) (`addons.mozilla.org`) version is still on 2020.6.2 until next week.)

The new version has fancy tooltips re-enabled in Firefox. Could you give the new version a try in Firefox and let me know if the hanging/freezing is back? Thank you!

(Note that if you already have Privacy Badger installed from Mozilla, installing from eff.org will give you two copies of Privacy Badger. There is no reason to have two copies of Privacy Badger.)

**Comment by codeling** [comment]
I uninstalled the previous version and installed the eff.org-hosted version you linked to - it looks good to me, I encountered no freezes (though I do have to say I switched to a different PC in the meantime, so not sure if I even could reproduce it on this one)!

**Comment by ghostwords** [comment]
Yeah, I hear you. Thank you for checking it out!
