### ISSUE TITLE
reference add-on: WebAPI Manager- Consider API's for heuristic

### ISSUE THREAD

**Issue by jawz101** [EFForg/privacybadger#1779]
https://github.com/snyderp/web-api-manager
I've been playing around with this Firefox add-on for a while now and I like having the ability to block certain API's right off the bat.  I didn't know if any of their detection techniques might assist in creating newer heuristics?

maintainers - feel free to close this if you want.  Just wanted to put it out there.

Personally, I've added wiki entries on the github page to highlight what might or might not be necessary for typical web browsing.
https://github.com/snyderp/web-api-manager/wiki/API-Notes

It's both a [Chrome ](https://chrome.google.com/webstore/detail/webapi-manager/hojoljbhkebfjalcbnfmoiljfidcmcmj)and [Firefox ](https://addons.mozilla.org/en-US/firefox/addon/webapi-manager/)add-on.

**Comment by ghostwords** [comment]
Wow, this is really cool, thanks for the tip!

**Comment by jawz101** [comment]
You're welcome.  My only hangup is it feels like Firefox exhausts a lot of memory with it enabled.  It could be due to some sort of conflict with it and uBlock, PrivacyBadger, or Decentraleyes... or the add-on itself.  Regardless, it is pretty interesting.

I've also thought this one was interesting for blocking unreachable scripts, though I haven't played with it too much. https://addons.mozilla.org/en-US/firefox/addon/block-unreachable-scripts/

**Comment by ghostwords** [comment]
Related to #1808.
