### ISSUE TITLE
User Filter Settings "Discloses" History

### ISSUE THREAD

**Issue by ghost** [EFForg/privacybadger#1780]
A concern about the only thing I would change on Privacy Badger. By showing a list of tracking domains, user filter settings actually keeps and exposes your browsing history. I would suggest restructuring this section in order to avoid this, such as by showing a list of trackers instead of tracking domains for example.

**Comment by ghostwords** [comment]
Is is the same issue as #1064? We are going to start optimizing what Privacy Badger records in the near future.

**Comment by janus12345** [comment]
Thank you for the response and sorry for the duplicate post! Keep it up!

**Comment by ghostwords** [comment]
To clarify my previous comment, #1446 is the next issue we plan on working on in this area.
