### ISSUE TITLE
add "Return control of this tracker to Privacy Badger" section to options menu

### ISSUE THREAD

**Issue by dlfsjdfjodifjsodifjsdo** [EFForg/privacybadger#1783]
I would like to see which trackers I have changed in a separate menu to the "tracking domains" list. There are some I cannot find unless I scroll through every tracker I have encountered.

**Comment by ghostwords** [comment]
This seems like a duplicate of https://github.com/EFForg/privacybadger/issues/1422#issuecomment-329396546.
