### ISSUE TITLE
vidtech.cbsinteractive.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1784]
https://tv.xfinity.com/entity/8118784557012618112/5576818320550501112

Need to be logged in.
`vidtech.cbsinteractive.com` prevents video from loading.

```
**** ACTION_MAP for cbsinteractive
VM171:5 cbsinteractive.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1493061847908,
  "userAction": ""
}
VM171:5 vidtech.cbsinteractive.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1511408335941,
  "userAction": "user_cookieblock"
}
VM171:7 **** SNITCH_MAP for cbsinteractive
VM171:9 cbsinteractive.com [
  "cnet.com",
  "metacritic.com",
  "cbsnews.com"
]
```

**Comment by terrorist96** [comment]
http://www.zdnet.com/article/chrome-65-rolls-out-youre-getting-a-stronger-redirect-blocker-45-security-fixes/

**Comment by terrorist96** [comment]
https://www.cbsnews.com/news/kroger-hardens-stance-on-guns/

**Comment by terrorist96** [comment]
https://reason.com/blog/2016/09/19/watch-the-60-minutes-interview-with-gary

**Comment by terrorist96** [comment]
https://www.cbssports.com/olympics/news/2016-paralympics-in-worst-situation-ever-just-before-opening-ceremony/

**Comment by terrorist96** [comment]
https://www.cbsnews.com/news/vice-president-joe-biden-restrict-sale-of-armor-piercing-bullets-dallas-shooting/

**Comment by ghostwords** [comment]
The video doesn't load for me in the `reason.com` link with or without any extensions.

I don't see any tracking from `cbsinteractive.com`.

The remaining URLs (besides the `tv.xfinity.com` link, which I can't check) make this seem like a CBS Interactive Inc. MDFP list fix.

**Comment by terrorist96** [comment]
You need to allow flash for the reason link.

**Comment by terrorist96** [comment]
zdnet is owned by cbs?

**Comment by ghostwords** [comment]
Yep: https://en.wikipedia.org/wiki/ZDNet#The_CBS_years:_2008_to_present.

**Comment by terrorist96** [comment]
Hmm ok. Well we still got xfinity and reason, so such videos can be embedded on other sites, which MDFP won't address.

**Comment by ghostwords** [comment]
No already-addressed by previous MDFP update error reports. Will revisit if we learn to block this domain in Badger Sett and/or start getting user error reports.
