### ISSUE TITLE
DNT sites using Google analytics (medium.com)

### ISSUE THREAD

**Issue by dhowe** [EFForg/privacybadger#1786]
I notice that medium.com is on the EFF's DNT list, yet it makes 3rd-party requests to Google Analytics, which I'm pretty sure doesn't comply. Can someone clarify?

![image](https://user-images.githubusercontent.com/737638/33065482-5295e9c0-ceec-11e7-9a83-afabdc956278.png)

It also makes requests to lightstep.com (https://collector-medium.lightstep.com/api/v0/reports). I don't know what this site does or if it honors DNT, but I do see that the URL above is blocked on the [EasyPrivacy](https://easylist.to/index.html) anti-tracking list

**Comment by ghostwords** [comment]
I see Google Analytics when Privacy Badger and "Do Not Track" in the browser are both disabled. I do not see Google Analytics when either is enabled. Does that match your experience?

**Comment by dhowe** [comment]
Actually, this is a mistake on my part -- had the DNT-header disabled... thanks for the reply
