### ISSUE TITLE
cdn.rawgit.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1788]
https://www.emc2.foundation/
`cdn.rawgit.com` breaks layout. Can't click boxes to reveal progress. Instead it's overlapping.
![image](https://user-images.githubusercontent.com/12802056/33243957-ed4d6c44-d2bc-11e7-9c2e-eaabdb16764a.png)

```
**** ACTION_MAP for rawgit
VM256:5 cdn.rawgit.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1512177642322,
  "userAction": ""
}
VM256:5 rawgit.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1492843819131,
  "userAction": ""
}
VM256:5 rawgithub.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1493068117544,
  "userAction": ""
}
VM256:7 **** SNITCH_MAP for rawgit
VM256:9 rawgit.com [
  "techdirt.com",
  "xda-developers.com",
  "britannica.com"
]
```

**Comment by ghostwords** [comment]
Previously: https://github.com/rgrove/rawgit/issues/163#issuecomment-342539683. This is probably a Cloudflare issue, to be fixed by #1538.

**Comment by terrorist96** [comment]
http://vanced.azurewebsites.net/

Site looks horrible with `cdn.rawgit.com` blocked..

**Comment by ghostwords** [comment]
RawGit has been sunsetted in October 2018.

>RawGit has also become an attractive distribution mechanism for malware
