### ISSUE TITLE
Change tracking domain *.chabad.org to only block cookies

### ISSUE THREAD

**Issue by sylerner** [EFForg/privacybadger#1791]
There are several hundred websites for the worldwide network of Chabad Houses, all of which are powered by chabad.org.

Currently, all chabad.org domains are treated as tracking domains that are completely blocked.

This breaks all of the Chabad House websites, causing them to display an unformatted partial version of their pages.

For an example, view http://www.chabadgreensboro.com/templates/photogallery_cdo/aid/1699826/jewish/Morning-Minyan.htm

Setting the chabad.org tracking domains to only block cookies fixes this problem.

![site with chabad org blocked](https://user-images.githubusercontent.com/20540525/33286171-ad58af1a-d382-11e7-931d-c67cf2d91244.png)
![site with chabad org only cookies blocked](https://user-images.githubusercontent.com/20540525/33286172-ad69dd6c-d382-11e7-88af-8c791db53968.png)

**Comment by ghostwords** [comment]
Could you run the following JavaScript in your Privacy Badger's background page and let me know what it prints out? For more information and instructions for getting to the page, please see https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b.
```javascript
(function () {
  const STR = "chabad.org";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

**Comment by sylerner** [comment]
VM98:3 **** ACTION_MAP for chabad.org
VM98:5 chabad.org {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
VM98:5 mychabad.org {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 0,
  "userAction": ""
}
VM98:5 w1.chabad.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1492546284873,
  "userAction": ""
}
VM98:5 w2.beta.chabad.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1492382700254,
  "userAction": ""
}
VM98:5 w2.chabad.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1513335319809,
  "userAction": ""
}
VM98:5 w3.beta.chabad.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1492601764306,
  "userAction": ""
}
VM98:5 w3.chabad.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1513264340095,
  "userAction": ""
}
VM98:5 w4.chabad.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1513420620680,
  "userAction": ""
}
VM98:5 w5.chabad.org {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1513245729056,
  "userAction": ""
}
VM98:5 www.chabad.org {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1512705560914,
  "userAction": ""
}
VM98:5 www.mychabad.org {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1504218738980,
  "userAction": ""
}
VM98:7 **** SNITCH_MAP for chabad.org
VM98:9 chabad.org [
  "ohelchabad.org",
  "googleusercontent.com",
  "chabadgreensboro.com",
  "myshliach.com"
]
VM98:9 mychabad.org [
  "chabad.org"
]
undefined

**Comment by sylerner** [comment]
VM98:3 **** ACTION_MAP for chabad.org
VM98:5 chabad.org {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
VM98:5 mychabad.org {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 0,
  "userAction": ""
}
VM98:5 w1.chabad.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1492546284873,
  "userAction": ""
}
VM98:5 w2.beta.chabad.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1492382700254,
  "userAction": ""
}
VM98:5 w2.chabad.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1513335319809,
  "userAction": ""
}
VM98:5 w3.beta.chabad.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1492601764306,
  "userAction": ""
}
VM98:5 w3.chabad.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1513264340095,
  "userAction": ""
}
VM98:5 w4.chabad.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1513420620680,
  "userAction": ""
}
VM98:5 w5.chabad.org {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1513245729056,
  "userAction": ""
}
VM98:5 www.chabad.org {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1512705560914,
  "userAction": ""
}
VM98:5 www.mychabad.org {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1504218738980,
  "userAction": ""
}
VM98:7 **** SNITCH_MAP for chabad.org
VM98:9 chabad.org [
  "ohelchabad.org",
  "googleusercontent.com",
  "chabadgreensboro.com",
  "myshliach.com"
]
VM98:9 mychabad.org [
  "chabad.org"
]
undefined

**Comment by ghostwords** [comment]
My Privacy Badger doesn't learn to block `chabad.org` (or to even see it as a tracker) from visiting http://www.ohelchabad.org/?lang=en, http://myshliach.com and http://www.chabadgreensboro.com/templates/photogallery_cdo/aid/1699826/jewish/Morning-Minyan.htm.

Perhaps learning to block `chabad.org` has to do with login cookies, where you log into `chabad.org` and then those cookies are sent along with requests to static resources hosted on domains like `w5.chabad.org`.

If this is what's happening, then I suggest `chabad.org` should avoid having session cookies be associated with static resources, especially on other people's domains (by configuring a dedicated static resource (sub)domain).

If that's too complicated, if `chabad.org` is able and willing to abide by the [EFF Do Not Track policy](https://www.eff.org/dnt-policy)'s requirements, posting the policy on each compliant domain (`w5.chabad.org`) will tell Privacy Badger to always allow loading of resources from that domain.

Apologies for not replying earlier.

**Comment by ghostwords** [comment]
I'm going to resolve this for now. Let me know if you have any questions.
