### ISSUE TITLE
video.google.com keeps reverting from red to yellow

### ISSUE THREAD

**Issue by paulakreuzer** [EFForg/privacybadger#1797]
I block all G%§$e stuff every way I can, so I do with PB. I have a long list of G%§$e Domains on PB's blocklist, but no matter how many times I set it on "block entirely", video.G%§$e.com keeps reverting to only blocking cookies.

**Comment by ghostwords** [comment]
Could you run the following JavaScript in your Privacy Badger's background page and let me know what it prints out? For more information and instructions for getting to the page, please see https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b.
```javascript
(function () {
  const STR = "video.google.com";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

**Comment by paulakreuzer** [comment]
Thanks for the quick answer.
Here is what it prints out:

```
**** ACTION_MAP for video.G%§$e.com 
**** SNITCH_MAP for video.G%§$e.com 
undefined
```

**Comment by ghostwords** [comment]
Hmm, no data. What browser do you use, and which version of Privacy Badger do you have?

Could you also run the below JavaScript in your Privacy Badger's background page? It will print how much space your Privacy Badger data uses:
```javascript
chrome.storage.local.get(null, r=>console.log(
  parseFloat(JSON.stringify(r).length / 1024 / 1024).toFixed(2), "MB"));
```

**Comment by paulakreuzer** [comment]
Firefox 57.0.1
Privacy Badger 2017.11.20

And this prints out:

```
undefined
0.13 MB
```

**Comment by ghostwords** [comment]
Ah OK, the problem isn't you running out of storage space. I don't think these other messages are related either.

The first JavaScript you ran told us your Badger doesn't have any settings at all for `video.google.com`. How do you usually tell Badger to block `video.google.com`? Is it through Badger's options page?

**Comment by paulakreuzer** [comment]
I click on the gear symbol, go to "tracking domains", enter Google in the search field, scroll down until I see a slider that is set on yellow, move it to red and the next time I check on it it looks like this again (it only takes a few seconds to revert back):

![bildschirmfoto 2017-12-09 um 19 49 27](https://user-images.githubusercontent.com/10324371/33798529-86183a5a-dd1a-11e7-89e1-2962632ff79e.JPG)

**Comment by ghostwords** [comment]
What happens if you search directly for `video.google.com` and change the setting then?

**Comment by paulakreuzer** [comment]
Wow, that really makes a difference.
All the other Google domains I could block just searching for Google, but now this one is blocked too.

The JavaScript now also prints this:

```
**** ACTION_MAP for video.google.com 
video.google.com {
  "userAction": "user_block",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
} 
**** SNITCH_MAP for video.google.com
```

Thanks a lot. 👍

**Comment by ghostwords** [comment]
You're welcome! I think you were running into this bug: #1706.
