### ISSUE TITLE
Privacy Badger breaking Google Play Music

### ISSUE THREAD

**Issue by andromedastudios1** [EFForg/privacybadger#1800]
Hello All,
Found an issue with a website being broken. 
URL: https://www.play.google.com/music
Issue: Website can be accessed but media will not play. 
What is causing the issue: media not being allowed on https://imasdk.googleapis.com
How I resolved it: allowing media for the 1st entry of https://imasdk.googleapis.com

Thanks in advance, 
andromedastudios1

**Comment by ghostwords** [comment]
Could you run the following JavaScript in your Privacy Badger's background page and let me know what it prints out? For more information and instructions for getting to the page, please see https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b.
```javascript
(function () {
  const STR = "googleapis.com";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

**Comment by andromedastudios1** [comment]
Hi,
Just realized that NoScript was blocking it, please close this bug. 


--
Best, 
Dev Singh
