### ISSUE TITLE
Privacy Badger breaking comment editing on github.com

### ISSUE THREAD

**Issue by andromedastudios1** [EFForg/privacybadger#1802]
Hello all,
another issue I have found
URL: github.com/EFFord/privacybadger/issues/1800
the fix I found was to enable script on the URL https://assets-cdn.github.com
When script is not allowed, the comment editing and other functions do not work.

**Comment by ghostwords** [comment]
Could you run the following JavaScript in your Privacy Badger's background page and let me know what it prints out? For more information and instructions for getting to the page, please see https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b.
```javascript
(function () {
  const STR = "github.com";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

**Comment by andromedastudios1** [comment]
Hi,
Just realized that NoScript was blocking it, please close this bug.
