### ISSUE TITLE
LaunchDarkly urls getting blocked

### ISSUE THREAD

**Issue by Kerumen** [EFForg/privacybadger#1813]
Similar to https://github.com/easylist/easylist/issues/391, LaunchDarkly is getting blocked by the extension.

> LaunchDarkly is a third-party service the application authors (such as myself) opt-in to and pay for. It uses the concept of a user-id and attributes to return whether or not certain flags are enabled or not. We use it to roll out access to beta features in a controlled fashion before removal.

**Comment by ghostwords** [comment]
Could you run the following JavaScript in your (or an affected user's) Privacy Badger's background page and let me know what it prints out? For more information and instructions for getting to the page, please see https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b.
```javascript
(function () {
  const STR = "launchdarkly";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

**Comment by Kerumen** [comment]
```
**** ACTION_MAP for launchdarkly
VM98:5 app.launchdarkly.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1514102786330,
  "userAction": "user_block"
}
VM98:5 clientstream.launchdarkly.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1513681762690,
  "userAction": "user_block"
}
VM98:5 events.launchdarkly.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1513689940173,
  "userAction": "user_block"
}
VM98:5 launchdarkly.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
VM98:7 **** SNITCH_MAP for launchdarkly
VM98:9 launchdarkly.com [
  // my domains
]
```

**Comment by ghostwords** [comment]
Are there any example pages (one is good, three would be great) where I could see this service in action?

**Comment by ghostwords** [comment]
OK, no problem, I'll ask in https://github.com/launchdarkly/js-client/issues/62.

**Comment by ghostwords** [comment]
Resolving this for now, can continue in https://github.com/launchdarkly/js-client/issues/62#issuecomment-352834945.
