### ISSUE TITLE
Broken Firefox canvas rendering in certain conditions

### ISSUE THREAD

**Issue by Phennim** [EFForg/privacybadger#1820]
I'm getting some rendering errors on Firefox canvas:
![screenshot-2018-1-2 0 00008814trx ethbinance com](https://user-images.githubusercontent.com/495274/34493960-7dc0679c-efee-11e7-8171-b001cbc7a182.png)
[https://www.binance.com/trade.html?symbol=WABI_ETH](https://www.binance.com/trade.html?symbol=WABI_ETH)

The above screenshot is on Firefox with only privacybadger addon active.
White-listing the site does help. Only disabling the addon.

It is on a recent macbook, and if I attatch an external monitor the problem does not occur.

**Comment by alexristich** [comment]
I checked this with FF57 on my Mac and wasn't able to reproduce this. Are there any errors showing in the console? You can access it using Cmd+Option+K.

Judging from the network traffic, whitelisting shouldn't have any effect here, as there don't appear to be any third-party resources being loaded on this page.

Are you able to reproduce this on all pages on this domain when browsing without an external monitor?

**Comment by Phennim** [comment]
It happens on every chart on that site.
Also on the ones from bitfinex:
<img width="192" alt="screen shot 2018-01-03 at 09 11 33" src="https://user-images.githubusercontent.com/495274/34513035-619678cc-f066-11e7-97c8-a0f2712d7457.png">
[https://www.bitfinex.com/trading](url)

Both sites show "_Use of getPreventDefault() is deprecated.  Use defaultPrevented instead._" error in the console. Bitfinex also has a missing sourcemap and deprecated XMLHttpRequest warnings.

When the browser window is on the external monitor all charts are fine. When I move it to the laptop monitor and refresh the page it is broken again.

These are the Graphics/Display specs:

```
Intel HD Graphics 530:
  Chipset Model:	Intel HD Graphics 530
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x191b
  Revision ID:	0x0006
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.29 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v3
```

```
Radeon Pro 450:
  Chipset Model:	AMD Radeon Pro 450
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	2 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x67ef
  Revision ID:	0x00ef
  ROM Revision:	113-C980AF-908
  VBIOS Version:	113-C9801AL-028
  EFI Driver Version:	01.00.908
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.29 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v3
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2880 x 1800 Retina
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
DELL U2713HM:
  Resolution:	2560 x 1440 @ 59 Hz
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Display Serial Number:	7JNY5439137S
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	DisplayPort

```

**Comment by ghostwords** [comment]
To recap: When you have an external monitor connected, loading https://www.binance.com/trade.html?symbol=WABI_ETH on the external monitor works, but loading the same page on the laptop screen results in graphical glitches. Does that sound right?

What happens when you don't have an external monitor connected?

Which versions of Privacy Badger and Firefox do you have?

**Comment by Phennim** [comment]
Yes, also the charts from bitfinex. I have not seen it on any other sites yet.

It always happens on the laptop screen, if the external monitor is connected or not.
It does not happen on the external monitor.

It happens on latest FF 57.0.3 and on the latest Firefox Developer Edition 58.0b13
Badger version 2017.11.20

**Comment by ghostwords** [comment]
I haven't been able to reproduce yet.

Based on the fact that disabling Badger for the site does not help, this sounds like a Firefox bug, or, more likely, a side effect of the unconditional native JS object overloading we do as part of [canvas fingerprinting detection](https://github.com/EFForg/privacybadger/blob/f3cf6433935ec2c7750ed5c906981eb7c322c536/src/js/contentscripts/fingerprinting.js).

**Comment by Phennim** [comment]
Thanks for your response.

I disabled the call to [insertFpScript](https://github.com/EFForg/privacybadger/blob/f3cf6433935ec2c7750ed5c906981eb7c322c536/src/js/contentscripts/fingerprinting.js#L336) and that did fixed the glitch.

So would that mean it is a Firefox bug?
Is there anything more I can do to zoom in on the issue?

**Comment by Phennim** [comment]
Narrowed it down to [fillText](https://github.com/EFForg/privacybadger/blob/f3cf6433935ec2c7750ed5c906981eb7c322c536/src/js/contentscripts/fingerprinting.js#L242).
Removing that from the array also fixed it.

**Comment by ghostwords** [comment]
Thanks for confirming it's our canvas fingerprinting detection.

Besides fixing canvas fingerprinting detection to work properly on these sites (which is unlikely to happen until I can reproduce the problem), it would be good to have canvas fingerprinting detection be disabled when Privacy Badger is disabled on the page (when the site's been whitelisted).

**Comment by ghostwords** [comment]
Generally speaking, it's not good to have any situations where disabling Privacy Badger on the site doesn't actually disable parts of Privacy Badger, especially parts that are capable of breaking the site. See #740 and #1260 for more examples of this kind of problem.

Canvas fingerprinting detection gets unconditionally injected because there is currently no official way to conditionally inject a before-anything-else-happens-on-the-page content script (https://crbug.com/478183).

We may be able to work around this by using cookies (as inspired by [web-api-manager](https://github.com/snyderp/web-api-manager/blob/e20e5267147888854c521404695e0bd676e96c26/add-on/content_scripts/instrument.js#L17)); there are known downsides to this approach, however: additional complexity, not working in aggressive cookie clearing environments (https://github.com/snyderp/web-api-manager/issues/53), ...

**Comment by Phennim** [comment]
The glitch seems to be fixed on FF59.0b1 so I think this issue can be closed.

**Comment by ghostwords** [comment]
Thanks for the update!
