### ISSUE TITLE
PB broken in Firefox private window

### ISSUE THREAD

**Issue by scheinercc** [EFForg/privacybadger#1822]
Hi there,

When I am in a private window the list of domains is missing, therefore the settings per domain can't be changed (issue #1060?) and PB can't be switched off. Clicking "Disable Privacy Batcher for This Site" does not do anything - actually none of the three buttons at the bottom work.
I have tried with Firefox 57/Win and 59/macOS - same thing.

---

**Trackers for Github (issue 1060) in a normal window**

<img width="665" alt="image" src="https://user-images.githubusercontent.com/817856/34517354-c0ddb22e-f0ce-11e7-8d21-fb0d45d5e6c0.png">

---

**Trackers for Github (issue 1060) in a Private Window**

<img width="600" alt="image" src="https://user-images.githubusercontent.com/817856/34517312-a25ce630-f0ce-11e7-9668-ed629dcb6210.png">

**Comment by ghostwords** [comment]
Yep, this is the same issue as #1060. We'd like to get it fixed in the next few releases. I'll update #1060 with a more clear title.

**Comment by scheinercc** [comment]
Thanks
