### ISSUE TITLE
Privacy Badger does not set the doNotTrack variable in JavaScript's navigator object

### ISSUE THREAD

**Issue by tadatitam** [EFForg/privacybadger#1835]
It seems like Privacy Badger sends the Dnt header, but does not set the doNotTrack variable in JavaScript navigator object. This is different from Firefox's Tracking Protection (https://support.mozilla.org/en-US/kb/tracking-protection) and Chrome's Do Not Track (https://support.google.com/chrome/answer/2790761) behavior: they send the Dnt header in addition to setting the Javascript navigator doNotTrack variable. 

I was wondering why Privacy Badger does not set the doNotTrack variable. Could this have privacy consequences for Privacy Badger users (e.g., against a web service that only detects Do Not Track using JavaScript)? 

Attaching some screenshots displaying the doNotTrack variable using a small piece of code on w3schools.com. The screenshots show that Privacy Badger does not modify that variable, unlike Firefox's Tracking Protection and Chrome's Do Not Track features. 

Baseline Firefox:
<img width="905" alt="baseline firefox" src="https://user-images.githubusercontent.com/6851424/35015353-de9533a6-fac8-11e7-948d-3e51c7bb2e01.png">
Firefox with Privacy Badger:
<img width="828" alt="firefox privacy_badger" src="https://user-images.githubusercontent.com/6851424/35015354-df455182-fac8-11e7-8010-fc05ec43bb45.png">
Firefox with Tracking Protection enabled:
<img width="828" alt="firefox tracking_protection" src="https://user-images.githubusercontent.com/6851424/35015355-df67ef3a-fac8-11e7-9b0c-4ba64e991cf4.png">

Baseline Chrome:
<img width="788" alt="baseline chrome" src="https://user-images.githubusercontent.com/6851424/35015351-ddc762f0-fac8-11e7-883f-ea629367acf4.png">
Chrome with Privacy Badger:
<img width="909" alt="chrome privacy_badger" src="https://user-images.githubusercontent.com/6851424/35015352-dde5b1ec-fac8-11e7-9cb4-56a5029d9dea.png">
Chrome with Do Not Track enabled:
<img width="872" alt="chrome donottrack" src="https://user-images.githubusercontent.com/6851424/35015760-a8b32552-faca-11e7-89a1-64cb1886ff55.png">

Screenshots were produced on
Chrome version: 63.0.3239.132
Firefox version: 56.0
using
Chrome extension version: 2017.11.20
Firefox add-on version: 2017.11.20

**Comment by ghostwords** [comment]
We should be able to get this fixed by doing something like the following inside all pages (and frames?):
```javascript
Object.defineProperty(Object.getPrototypeOf(navigator), "doNotTrack", {
  get: () => {
    return "1";
  }
});
```
I [previously thought `navigator.doNotTrack` is protected from overwriting](https://bugs.chromium.org/p/chromium/issues/detail?id=455288#c6), but it looks like I just didn't do it right since the above code seems to work.

**Comment by ghostwords** [comment]
We should check if using the new `doNotTrackEnabled` capability of the `chrome.privacy` API (available as of Chrome 65) is a better fix (instead of injecting JS). If we go that route though, we may not be able to disable DNT=1 signals for pages where Privacy Badger is disabled (#1260).

**Comment by tadatitam** [comment]
@ghostwords Thanks for responding! 

> We should check if using the new doNotTrackEnabled capability of the chrome.privacy API (available as of Chrome 65) is a better fix (instead of injecting JS). If we go that route though, we may not be able to disable DNT=1 signals for pages where Privacy Badger is disabled (#1260).

One option is to let users make the choice. Privacy Badger (PB) can have both options: 
1. Send Do Not Track only on websites where PB is enabled, which can be implemented by 
JS injection. 
2. Always send Do Not Track, which can be implemented using the doNotTrackEnabled capability of the chrome.privacy API. 

That being said, this leaves open the hard question of determining which should be the default (since most users may not change settings). Personally, I am in favor of the former, since it provides users with finer-grained control: if someone is making the effort of disabling PB on a page, they should be able to remove all its effects. 

I suppose there is something analogous to the doNotTrackEnabled capability for Firefox too. So, this discussion pertains to both browsers.

**Comment by michael-oneill** [comment]
If PB implements the DNT consent API it will have to use the defineProperty method. The value of navigator.doNotTrack will depend on whether the storeTrackingException has been called, which could be web wide or site specific. Even if the implementation is not designed to immediately reflect the result of the call (the spec leaves that as an option) the correct value of navigator.doNotTrack must be available when any new browsing context is initiated (not just a 1st party i.e. top level context).
