### ISSUE TITLE
Protect against Local shared objects (LSOs) (aka Flash cookies)

### ISSUE THREAD

**Issue by davidhedlund** [EFForg/privacybadger#1836]
I'm using Privacy Badger 2017.11.20, do I need to use [Clear Flash Cookies](https://addons.mozilla.org/en-US/firefox/addon/clear-flash-cookies/) to protect myself from Flash cookies?

**Comment by ghostwords** [comment]
Correct, Privacy Badger does not do anything about [Local shared objects](https://en.wikipedia.org/wiki/Local_shared_object) at this time. Please see #360 for the related issue.

**Comment by davidhedlund** [comment]
@ghostwords Can you please re-open this issue, I submitted it specifically for flash cookies. The title of https://github.com/EFForg/privacybadger/issues/360 is "Prevent fingerprinting through plugins and flash" -- not flash cookies

**Comment by ghostwords** [comment]
#360 seems to be about protecting against Flash cookies being set in the first place by blocking Flash from running.

**Comment by davidhedlund** [comment]
@ghostwords Thank you.

**Comment by davidhedlund** [comment]
@ghostwords You can close this issue if you want, but only if you add something like "Local shared objects (LSOs) (aka flash cookies)" to the title in https://github.com/EFForg/privacybadger/issues/360 -- it should be more clear.

**Comment by davidhedlund** [comment]
@ghostwords Can you please implement [Clear Flash Cookies](https://addons.mozilla.org/en-US/firefox/addon/clear-flash-cookies/) in Privacy Badger?

**Comment by ghostwords** [comment]
Possibly, just not right away.

Looks like this mainly involves [calling `chrome.browsingData.removePluginData`](https://github.com/cpeterso/clear-flash-cookies/blob/d32d44c5fb057a8bfceffc5029923fb28f7eb145/src/background.js#L12) at appropriate times.

**Comment by davidhedlund** [comment]
@ghostwords Thank you for taking your time to investigate this.

**Comment by ghostwords** [comment]
Closing as Flash is close to its EOL (end of life).

- Click to activate in Firefox, to be removed in 2020 ([Firefox schedule](https://developer.mozilla.org/en-US/docs/Plugins/Roadmap#Schedule))
- Disabled by default in Chrome, to be removed in 2020 ([Chrome schedule](https://www.chromium.org/flash-roadmap#TOC-Flash-Disabled-by-Default-Target:-Chrome-76---July-2019-))
