### ISSUE TITLE
Privacy Badger Allowing all Trackers

### ISSUE THREAD

**Issue by yoavaviram** [EFForg/privacybadger#1837]
I've noticed that the Privacy Badger extension was flagged corrupted by Chrome with no repair button. I therefore removed and reinstalled it from the chrome store. Now all trackers an all websites are allowed by default. Any ideas? 

MacOS high Sierra  / Chrome 63.0.3239.132 (Official Build) (64-bit)

**Comment by ghostwords** [comment]
Is [this](https://github.com/EFForg/https-everywhere/issues/5874#issue-168483122) what your problem looked like, only without a Repair link?

This seems related to https://github.com/EFForg/privacybadger/issues/1496#issuecomment-355403456.

**Comment by ghostwords** [comment]
As for not blocking anything: when you first install Privacy Badger (uninstalling and re-installing in Chrome is the same as installing from scratch), Privacy Badger needs to first learn what the trackers are by observing which domains appear to track you as you browse the Web.

Privacy Badger should start blocking trackers once you visit a few websites (three or more news sites, for example). If you have other privacy extensions or ad blockers installed, [Privacy Badger will take longer to learn to block anything](https://github.com/EFForg/privacybadger/wiki#is-privacy-badger-compatible-with-other-privacy-extensions-andor-ad-blockers).

**Comment by yoavaviram** [comment]
Thanks for the quick reply.  Yes, the corruption issue is the same as in the other thread, however the main issue is with missing / allowed trackers. The reason might be the one you highlighted (PB still learning). To illustrate the issue further, I've open this page (the github issue page) with two different chrome users. With the user where I reinstalled the extension it reports no trackers trying to track me. On another user where the extension is installed for a long while now, it reports 7 such trackers. These trackers do not appear for the first user at all. 

I'm happy to wait for a bit to see if things get back to normal and report back.

**Comment by ghostwords** [comment]
Sounds good.

You can see how Privacy Badger is learns to block by installing Privacy Badger into a new browser profile all by itself (no other blockers), visiting two different news sites, checking Privacy Badger's list of tracking domains on the options page (nothing is blocked), and then visiting a third news site and checking that Privacy Badger decided to start blocking a number of domains.

**Comment by ghostwords** [comment]
We plan on making how Privacy Badger works by learning more clear in the future: #1374.

**Comment by ghostwords** [comment]
I'm going to resolve this for now. Let me know if you have any updates.
