### ISSUE TITLE
cdn.materialdesignicons.com blocked

### ISSUE THREAD

**Issue by MoritzBru** [EFForg/privacybadger#1838]
The (unofficial) extended material design icon font from `cdn.materialdesignicons.com` is blocked recently.
Can be observed here: [https://codepen.io/templarian/pen/vgmMdj](https://codepen.io/templarian/pen/vgmMdj)
This leads to display "problems" .

**Comment by ghostwords** [comment]
Could you run the following script in your Badger's background page console and share what it prints out?
```javascript
(function () {
  const STR = "materialdesignicons.com";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by MoritzBru** [comment]
```
**** ACTION_MAP for materialdesignicons.com 
cdn.materialdesignicons.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1516426387675
} 
materialdesignicons.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1516632198132
} 
**** SNITCH_MAP for materialdesignicons.com 
materialdesignicons.com [
  "twitter.com",
  "github.com",
  "moritz-brunnengraeber.de"
]
````
Ok, now what does that mean?

**Comment by MoritzBru** [comment]
```
**** ACTION_MAP for materialdesignicons.com 
cdn.materialdesignicons.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1516426387675
} 
materialdesignicons.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1516632198132
} 
**** SNITCH_MAP for materialdesignicons.com 
materialdesignicons.com [
  "twitter.com",
  "github.com",
  "moritz-brunnengraeber.de"
]
```

Ok and what does that mean?

**Comment by ghostwords** [comment]
This means that your Privacy Badger saw tracking from `cdn.materialdesignicons.com` somewhere on `twitter.com`, `github.com`, and `moritz-brunnengraeber.de`. Does that make sense? I mean, are there `cdn.materialdesignicons.com` resources on those domains?

**Comment by MoritzBru** [comment]
`moritz-brunnengraeber.de` is my own "play around" site where I used `cdn.materialdesignicons.com` but I removed it recently.
For `github.com`  maybe some github pages subdomain or something uses it I don't know and `twitter.com` I don't think so.

**Comment by ghostwords** [comment]
This seems like another Privacy Badger mis-attribution bug, maybe what I describe in https://github.com/EFForg/privacybadger/pull/1642#issuecomment-328681731.

**Comment by ghostwords** [comment]
Closing as a likely duplicate. No error reports with blocked "materialdesignicons" domains.
