### ISSUE TITLE
All of my *.azurewebsites.net domains are consistently blocked

### ISSUE THREAD

**Issue by lyptt** [EFForg/privacybadger#1840]
I've found that Privacy Badger consistently blocks all of my *.azurewebsites.net domains. I'm assuming this is a wider-reaching issue than just with what I'm hosting on Azure, since what I host doesn't set any cookies or do any tracking of users.

**Comment by ghostwords** [comment]
Could you run the following script in your Badger's background page console and share what it prints out?
```javascript
(function () {
  const STR = "azurewebsites.net";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by lyptt** [comment]
Sure, here's the result:

```
**** ACTION_MAP for azurewebsites.net 
pubcrawladminapi.azurewebsites.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1516702468061
} 
open-rating-prod.azurewebsites.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1516452500267
} 
lightboxapi2.azurewebsites.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1514718474988
} 
open-commenting.azurewebsites.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1516354332254
} 
lightboxanalyticscore2.azurewebsites.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1516958031522
} 
**** SNITCH_MAP for azurewebsites.net 
pubcrawladminapi.azurewebsites.net [
  "localhost",
  "pubcrawladminui.azurewebsites.net",
  "pubcrawlbarui.azurewebsites.net"
] 
open-rating-prod.azurewebsites.net [
  "microsoft.com"
] 
open-commenting.azurewebsites.net [
  "microsoft.com"
]
```

**Comment by lyptt** [comment]
The front-end code authenticates via oauth 2 against the admin API server and stores the token in localstorage. This is intended behaviour.

**Comment by lyptt** [comment]
There is no tracking in any part of the code, and no cookies are set.

**Comment by ghostwords** [comment]
Sure, it's just that Privacy Badger somehow thinks this is tracking (sounds like by seeing localStorage data). Is there a way for me to see how this works for myself? You could send anything sensitive directly to alexei at eff dot org.

**Comment by lyptt** [comment]
I can't send you login information to the system, but the mechanism is simple. We POST to api/auth/authorise, the result is stored in pcsession in local storage, and we use that value in every other API request.

**Comment by ghostwords** [comment]
Could you post a (redacted) screenshot of what your localStorage looks like? Something like this, only for your site and with the values redacted:
![screenshot from 2018-01-23 10 33 59](https://user-images.githubusercontent.com/794578/35284486-f4127440-0028-11e8-8c18-0da8937e36ad.png)

**Comment by lyptt** [comment]
Here you go:

![capture](https://user-images.githubusercontent.com/346710/35298984-c99baa30-007b-11e8-9292-c14f77529e5b.PNG)

**Comment by ghostwords** [comment]
And what is the domain these localStorage entries are set for?

**Comment by lyptt** [comment]
https://pubcrawladminui.azurewebsites.net/

**Comment by lyptt** [comment]
Is there some kind of definition file I can host on this API to say this is all kosher? I would've thought the CORS configuration would have been good enough.

**Comment by ghostwords** [comment]
If the affected domains are compliant with the [EFF Do Not Track policy](https://www.eff.org/dnt-policy), you could post the policy on each domain, which will tell Privacy Badger to always allow loading of resources from that domain.

**Comment by lyptt** [comment]
I've added .well-known/dnt-policy.txt to the affected API domains and they're still marked as blocked. Is this cached somehow?

See: http://pubcrawladminapi.azurewebsites.net/.well-known/dnt-policy.txt and http://pubcrawlmobileapi.azurewebsites.net/.well-known/dnt-policy.txt

**Comment by ghostwords** [comment]
Yes, try restarting Privacy Badger (or the entire browser), and visiting the site again, giving it a second or two and reloading.

**Comment by lyptt** [comment]
I've done that just one minute ago and it's still marked as blocked

**Comment by lyptt** [comment]
Here's another snitch map, I don't think there's anything different though:

```
**** ACTION_MAP for azurewebsites.net 
pubcrawladminapi.azurewebsites.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1517005547566
} 
open-rating-prod.azurewebsites.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1516740340838
} 
open-commenting.azurewebsites.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1516628337628
} 
**** SNITCH_MAP for azurewebsites.net 
pubcrawladminapi.azurewebsites.net [
  "localhost",
  "pubcrawladminui.azurewebsites.net",
  "pubcrawlbarui.azurewebsites.net"
] 
open-rating-prod.azurewebsites.net [
  "microsoft.com"
] 
open-commenting.azurewebsites.net [
  "microsoft.com"
]
```

**Comment by ghostwords** [comment]
Ah! It's a end-of-file newline problem:
```shell
$ diff <(curl -s "https://pubcrawladminapi.azurewebsites.net/.well-known/dnt-policy.txt") <(curl -s "https://raw.githubusercontent.com/EFForg/dnt-policy/master/dnt-policy-1.0.txt")
218c218
< opinions, interests or activities of the user.
\ No newline at end of file
---
> opinions, interests or activities of the user.
```

**Comment by lyptt** [comment]
I've added the new line at the end of the file and it still appears to be blocking the domains. The command you posted has no output so I assume the files are identical.

**Comment by ghostwords** [comment]
I'm sorry, I misremembered how the cache works in my [above comment](https://github.com/EFForg/privacybadger/issues/1840#issuecomment-359950607).

You could wait until it is past 17:25:47 EST on January 26 (the `nextUpdateTime` value), or you could run `badger.storage.touchDNTRecheckTime('pubcrawladminapi.azurewebsites.net', 0);` in your Badger's background page console to clear the cache for `pubcrawladminapi.azurewebsites.net`, and then visit the site again, give it a second or two and reload.

**Comment by lyptt** [comment]
That seems to have fixed it, Privacy Badger displays no trackers now. Thanks!

**Comment by ghostwords** [comment]
Related to #137.
