### ISSUE TITLE
Privacy badger disabled in Chrome Dev Windows

### ISSUE THREAD

**Issue by cpatrick08** [EFForg/privacybadger#1842]
I'm running Chrome Dev on Windows and it's disabled your extension. It sends me to this webpage [https://support.google.com/chrome_webstore/answer/2811969?visit_id=0-636524193162734281-3776717850&p=ui_remove_non_cws_extensions&rd=2](url) that says you need to add it to the Chrome store but I see your app is in the Chrome store.

**Comment by ghostwords** [comment]
Does your issue appear to be the same as #1186? Chrome's extensions page UI may have changed but the core issue might be the same.

**Comment by cpatrick08** [comment]
Yes it is, I checked and didn't see that bug

**Comment by User486375** [comment]
Chrome stable just updated to version Version 64.0.3282.119 and gave me the same error.
![chrome_2018-01-25_09-12-11](https://user-images.githubusercontent.com/30012923/35380143-54462ff4-01b0-11e8-9327-57d6c014362f.png)

**Comment by ghostwords** [comment]
Does re-enabling from Privacy Badger's Chrome Web Store page help?

Does uninstalling and reinstalling (https://github.com/EFForg/privacybadger/issues/1496#issuecomment-355403456) help?

We are going to do an update later today that should fix "Not from Chrome Web Store"-related issues.

**Comment by ghostwords** [comment]
This should be fixed as of [Privacy Badger version 2018.1.25](https://github.com/EFForg/privacybadger/releases/tag/release-2018.1.25).

Let me know if updating fixes your problem. You could try forcing an update by visiting `chrome://extensions` and clicking the "Update extensions now" button.

**Comment by User486375** [comment]
Uninstalling and reinstalling fixed the issue but re-enabling from the chrome web store did not. However I did this an hour before you released 2018.1.25 so I can no longer test if that fixes the issue without having to reinstall. I can at least say that with the latest version "not from chrome web-store" no longer appears in `chrome://extensions`
