### ISSUE TITLE
Error in chrome when unloaded from github repo

### ISSUE THREAD

**Issue by cpatrick08** [EFForg/privacybadger#1844]
See pdf for error message. I'm running Chrome Dev on Ubuntu.
[Privacy Badger error.pdf](https://github.com/EFForg/privacybadger/files/1664906/Privacy.Badger.error.pdf)

**Comment by ghostwords** [comment]
You can just drag and drop image screenshots into GitHub issue descriptions/comments.

The warning is:
>Unrecognized manifest key 'applications'.

This should be a cosmetic warning that stems from the fact we use the same manifest on both Chrome and Firefox. I wouldn't worry about it.
