### ISSUE TITLE
Privacy Badger now showing anything?

### ISSUE THREAD

**Issue by aydnmercan** [EFForg/privacybadger#1846]
Greetings,

Is it normal for privacy badger to break down and not show anything including version and tracker list. The problem is that this occurs at random and cannot be recreated consistently. It just becomes blank sometimes on a site. Reinstalling and using it on other browsers/OS did not change anything. This problem occurs more frequently in Ubuntu 17.10 running Firefox 58.0 however it was still observed in previous versions of Firefox (or nightly)

Best Regards.

![pb_problem](https://user-images.githubusercontent.com/35869523/35472539-fbc18dbe-0381-11e8-9ec6-d87da99e9764.png)

**Comment by ghostwords** [comment]
Hello! Is this in Private Browsing windows?

**Comment by ghostwords** [comment]
Privacy Badger's popup is currently broken in Private Browsing windows on Firefox: #1060.

I'm going to close this as a duplicate for now. Let me know if you have more information.
