### ISSUE TITLE
(Bug) Refusal to show some jpeg and png images via URLs

### ISSUE THREAD

**Issue by broukema** [EFForg/privacybadger#1847]
This bug occurs when Privacy Badger 2018.1.22
is  enabled in Firefox (firefox-esr 52.6.0esr-1~deb9u1).

REPRODUCE THE BUG:

(1)+(2) give one example of the bug's behaviour:

(1) With Privacy Badger (PB) DISabled in (or removed from) Firefox -
Tools - Add-ons - Disable:

Start at a URL such as:

https://commons.wikimedia.org/wiki/File:Cat_poster_1.jpg

and click on the cat poster image, or on one of the links to scaled
version:

 Other resolutions: 320 × 210 pixels | 640 × 420 pixels | 1,024 × 673
 pixels | 1,280 × 841 pixels ...

All of these work correctly.

(2) ENable Privacy Badger;

History - Clear recent history - Last hour - Cache - Clear now;

go to the same URL; the result of clicking
on either the cat poster image or any of the links to scaled versions
is nothing apparent to the user (except for the sound of the mouse
physically clicking).

(2b) Right-clicking on the main image or any individual "other
resolutions" link does *not* give any mouse menu;

(2c) Right-clicking fails *everywhere* (where I tried) in the panel in
which I attempted to click on an image URL. I can switch to another
panel, use the right-mouse-button normally, and when I return to
the panel with the problem, I still cannot obtain any response
from right-clicking.

* Restarting firefox between (1) and (2), in either order, does not
modify this behaviour - it seems to be impossible to display these
images on their own.

* Debug warning: Clear the recent history cache between experiments
in order to verify this behaviour in a reproducible way!!!!

(3) Another example: at this webpage:
https://bugs.debian.org/release-critical/

clicking on "Graph with all the history" modifies the URL in the
firefox browser bar to
https://bugs.debian.org/release-critical/graph.png
but the display remains unchanged; the graph with only 7 months of bug counts remains displayed. (The graph.png file itself can
be downloaded e.g. with wget, and clearly shows 15 years of bug
counts.)

Disabling PB and reloading correctly shows graph.png .

ABSENCE OF THE BUG:

(4) other image file examples: (png, svg): For the files linked from
these wikimedia commons pages, clicking works *correctly* with PB
ENabled:

https://commons.wikimedia.org/wiki/File:Brynmor.png
https://commons.wikimedia.org/wiki/File:Scheme_cat_anatomy.svg

Other web sites with images: some fall in category (4), some fall
in category (1)+(2) and (3).

NO EFFECT:

* no effect on behaviour: Clicking to open in the same tab versus
clicking to open in a new tab makes no difference to the above tests.

SYSTEM:

Debian GNU/Linux debian/stretch (stable) 9.3

ii  firefox-esr                            52.6.0esr-1~deb9u1                amd64        Mozilla Firefox web browser - Extended Support Release (ESR)

QUALITATIVE HISTORY:

I've noticed the above bug since a month or two ago, but
it's only yesterday that I traced this to PB.

**Comment by ghostwords** [comment]
This sounds like a legacy Firefox bug, fixed in Firefox 57 and later by virtue of Firefox 57 no longer supporting legacy add-ons. See https://github.com/EFForg/privacybadger/issues/1653#issuecomment-328556902 for more information.
