### ISSUE TITLE
Privacy Badger causing rendering issues with charts

### ISSUE THREAD

**Issue by PaulSpoerry** [EFForg/privacybadger#1854]
PrivacyBadger is causing rendering issues on Tradingview.com with Chrome version 64.0.3282.119 (Windows & Chrome OS). This occurs when "Disable Privacy Badger for This Site" as well as if the site is explicitly whitelisted in PB's options. 

Example of Privacy Badger running ( includes while whitelisted or disabled):
![image](https://user-images.githubusercontent.com/1054579/35698597-2d1e8298-0753-11e8-85b0-990283ce55c5.png)

Console output with Privacy Badger running:
![image](https://user-images.githubusercontent.com/1054579/35698833-dc800018-0753-11e8-873a-17ce2cb98ca8.png)

Example of Privacy Badger removed:
![image](https://user-images.githubusercontent.com/1054579/35698676-6ab2bba6-0753-11e8-90d6-896e4dbf4b1b.png)

Possibly related: https://github.com/EFForg/privacybadger/issues/1820

**Comment by ghostwords** [comment]
Yeah, I think this is the same issue as #1820, but in Chrome. Do you also have a multi-monitor setup?

**Comment by ghostwords** [comment]
To follow up on https://github.com/EFForg/privacybadger/issues/1820#issuecomment-356077521, it might make sense to trade the before-anything-else injection guarantee (until we get it back via improved browser APIs ([Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=478183), [Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contentScripts))) for ability to comply with whitelisting (reversing myself here ... [previously](https://github.com/EFForg/privacybadger/issues/1506#issuecomment-322344483)).

The other [`"content_start"` content scripts](https://github.com/EFForg/privacybadger/blob/c88f2c7b5131175082b44cf2ca105584b1da0210/src/manifest.json#L56-L67) already made this trade-off ([localStorage protection script](https://github.com/EFForg/privacybadger/blob/c88f2c7b5131175082b44cf2ca105584b1da0210/src/js/contentscripts/clobberlocalstorage.js#L40), [cookie protection script](https://github.com/EFForg/privacybadger/blob/c88f2c7b5131175082b44cf2ca105584b1da0210/src/js/contentscripts/clobbercookie.js#L35)).

**Comment by PaulSpoerry** [comment]
Single monitor Dell P2715Q (HDMI).

**Comment by ghostwords** [comment]
Reopening as the underlying rendering bug will still be a problem.

**Comment by rasved** [comment]
I have the same problem. 
I experienced, that the label moves further away from the colored background (the indicator) when the indicator moves further down the window. 
Take a look at https://imgur.com/a/wEQlD if my description doesn't make sense ...

**Comment by ghostwords** [comment]
Some https://www.tradingview.com/ examples:
- https://www.tradingview.com/x/tpEuLSDE (os": "windows", "browser": "Chrome")
- https://www.tradingview.com/x/Vuse3jSy ("os": "mac", "browser": "Chrome")
- https://www.tradingview.com/x/KhtsMFlq ("os": "linux", "browser": "Firefox")
- http://joxi.net/ZrJzEZ9t1K5PZr.jpg (os": "windows", "browser": "Firefox")

**Comment by rasved** [comment]
I still get the wrong rendering as well (win 10, Chrome, PB 2018.3.21)

**Comment by ghostwords** [comment]
@rasved Does disabling Privacy Badger for the page (by clicking on the "Disable Privacy Badger for This Site" button in Privacy Badger's popup while on the page) work around the issue?

**Comment by zrodrps** [comment]
@ghostwords I can confirm that disabling privacy badger for this site _does not_ work around the issue. Only disable of the chrome-extension (and then refresh browser) will help with this. PB 4.23.

**Comment by ghostwords** [comment]
@zrodrps I wonder if this is a WebRTC-related problem then ... Could you try running the following code in Privacy Badger background page console as a temporary (would have to do this every time you restart the browser) workaround?

```javascript
chrome.privacy.network.webRTCIPHandlingPolicy.clear({});
```

To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is enabled, click on the "background page" link in Privacy Badger's row, and select the Console tab.

**Comment by mrcybermac** [comment]
This is still an issue. I can confirm that the extension causes chart CSS to not render properly on tradingview.com. If you disable the extension the problem goes away. I can not find a way to disable just for the problem site specifically.

**Comment by ghostwords** [comment]
Hi @mrcybermac, try the "Disable Privacy Badger for This Site" button in Privacy Badger's popup.

**Comment by mrcybermac** [comment]
Ah thanks. I was only looking in the right-click context menu where I expected the disable option to be. Disabling for the site does workaround the issue.
