### ISSUE TITLE
Privacy Badger broken as of Vivaldi version 1.14

### ISSUE THREAD

**Issue by pdbits** [EFForg/privacybadger#1855]
I have tried reinstalling it several times from the web-store, as well as from the source itself(both 25.1.2018 and 30.1.2018). 
After installing, if you click the badger icon on any site, it just looks as if it was clicked on a new tab page(enabled but not active).
Disabling/Enabling makes it work on just the active opened sites. It stops working again on any newly opened sites. Importing previous user data also doesn't help.
Tried in incognito mode and even by disabling other add-ons, there is no change in behavior.
Worked seamlessly before the update.

Please assist.
Thank you.

**Comment by ghostwords** [comment]
@svandragt @pdbits When Privacy Badger isn't working on a page, do you see any errors in the console for Privacy Badger's popup?

To open the console for the popup, first enable "Developer mode" in `chrome://extensions/` (the extensions management page), and then, once you are on a page where Badger isn't working, right-click on Badger's toolbar button, select "Inspect popup" and make sure the Console tab is active.

**Comment by ghostwords** [comment]
Also, could you see if the problem goes away when you install an older version of Privacy Badger?

- https://www.eff.org/files/privacy_badger-2018.1.25.crx
- https://www.eff.org/files/privacy_badger-2018.1.22.crx
- https://www.eff.org/files/privacy_badger-2017.11.20.crx

To install, download and then drag and drop the CRX file into `chrome://extensions`. You should remove any existing copies of Privacy Badger before dragging and dropping.

**Comment by pdbits** [comment]
@ghostwords I'm getting the following errors.
![pbconsole](https://user-images.githubusercontent.com/2222607/35742051-4d338ca2-0831-11e8-86e3-e0892f9b18b2.jpg)

**Comment by svandragt** [comment]
failed: https://www.eff.org/files/privacy_badger-2018.1.25.crx
seems to have worked: https://www.eff.org/files/privacy_badger-2018.1.22.crx

The problem with the 2018.1.22.crx version is that the badge number is ever increasing, not sure if this is a side effect of anything.

**Comment by svandragt** [comment]
@ghostwords interestingly I got a different error
![cannot-read-property](https://user-images.githubusercontent.com/594871/35742386-2de33216-0832-11e8-963b-0b85ec86c00e.PNG)

**Comment by pdbits** [comment]
- https://www.eff.org/files/privacy_badger-2018.1.25.crx
- https://www.eff.org/files/privacy_badger-2018.1.22.crx
- https://www.eff.org/files/privacy_badger-2017.11.20.crx

None of these versions are working, including the latest.

@svandragt I got the same error earlier, but now am unable to reproduce it. Logging different errors now.

**Comment by ghostwords** [comment]
OK, thank you! It seems like something changed in Chrome/Vivaldi.

The errors you posted are from Badger's background page (I think). Do you see any errors on Badger's popup? To get to the popup console, right-click on Badger's toolbar button on a page where Badger isn't working and select "Inspect popup".

**Comment by ghostwords** [comment]
This looks like a Vivaldi-specific bug. Privacy Badger is broken in Vivaldi 1.14.1077.41 but seems to work fine in Vivaldi 1.13.1008.44 (and in Chrome 64).

On first glance, it appears that messaging between the extension's content scripts and the background page sporadically breaks where the message sender's tab information is missing.

I suggest [reporting this issue to Vivaldi](https://vivaldi.com/bugreport/).

**Comment by ghostwords** [comment]
It seems (and [sounds like](https://www.reddit.com/r/vivaldibrowser/comments/7s8mew/extensions_not_working_in_11410773/) this Vivaldi bug affects all extensions (that depend on the newly broken extension functionality).

**Comment by pdbits** [comment]
@ghostwords I checked and observed that certain extension functionality does seem to be broken with the vivaldi update. DuckDuckGo privacy essentials and ghostery aren't working properly for me as well. I'll try reporting it to Vivaldi, as you suggested.

Thanks for taking time out to resolve and troubleshoot this issue.

**Comment by ghostwords** [comment]
Sounds good! Thanks for reporting and for checking other extensions.

**Comment by pdbits** [comment]
@ghostwords Hi, I just reopened the issue to inform that the aforementioned issue has been fixed with the latest vivaldi stable update.
