### ISSUE TITLE
Changing blocking preferences in tracking options sometimes resets unrelated origins

### ISSUE THREAD

**Issue by mijiturka** [EFForg/privacybadger#1863]
On the Tracking Domains options tab, after making several changes to closely-displayed but unrelated domains, a change to one domain sometimes triggers one of the others to get reset to its most recent position.  

![release1](https://user-images.githubusercontent.com/1078993/36077175-295732f4-0f5f-11e8-835f-1613ad3b0a77.png)
![release2](https://user-images.githubusercontent.com/1078993/36077176-2be295f4-0f5f-11e8-84ea-e851eb1c2013.png)
![release3](https://user-images.githubusercontent.com/1078993/36077178-2f830176-0f5f-11e8-801d-d236636289a9.png)
If I set virgin.15gifts.com to cookieblock, and then set 1rx.io to block, virgin.15gifts.com goes back to allowed.

![1](https://user-images.githubusercontent.com/1078993/36077194-66be7576-0f5f-11e8-8bea-9f8d1b61a172.png)
![2](https://user-images.githubusercontent.com/1078993/36077196-69e8bd56-0f5f-11e8-871e-8b9ecd0f2861.png)
![3](https://user-images.githubusercontent.com/1078993/36077197-6be36bec-0f5f-11e8-9b72-ff2454cb1e4c.png)
If I set bat.bing.com to allow, then set bounceexchange.com to cookieblock, bat.bing.com goes back to cookieblock.

I have not seen this happen with origins that have not had their user preferences changed.

I cannot catch it reliably by hand, but I have this test case that always triggers it: I found this issue while writing tests for a somewhat related issue.
https://gist.github.com/mijiturka/989dc5958f62c8b2628efc1bf19fcc23

I managed to catch it a few times on the master branch in firefox-dev 59.0 and on the latest release in firefox 58.0.1. Have not tested in Chromium.

**Comment by ghostwords** [comment]
Related to #1581 and #1706.

**Comment by ghostwords** [comment]
Is this a problem with domains in the popup as well, or only with domains on the options page?

**Comment by mijiturka** [comment]
I have not seen it happen in the popup.
