### ISSUE TITLE
FILE_ERROR_NO_SPACE error

### ISSUE THREAD

**Issue by MarionGee** [EFForg/privacybadger#1866]
Have this error flagged I don't know what to do about it or how to close it:

IO error: .../003144.log: FILE_ERROR_NO_SPACE (ChromeMethodBFE: 3::WritableFileAppend::8)

**Comment by ghostwords** [comment]
Hello!

Where do you see this error? Feel free to drag and drop a screenshot here.

Is your drive running out of space?

**Comment by AndrewGatenbyVS** [comment]
I get the same warning showing on all sites. Only started showing today.  Hard drive still has space available (around 1Gb).

Chrome 63.0.3239.132
MacOS 10.12.6

![img](https://monosnap.com/file/O7xHj3h7cLhoXgupfvxsl1mNNGCiqt.png)

**Comment by ghostwords** [comment]
Hi @AndrewGatenbyVS, thanks for sharing a screenshot!

This looks like the error handling dialog I added as part of #1848. It catches errors that happen while trying to save Privacy Badger state (your Badger's knowledge of who the trackers are, basically) to disk. Before #1848, the errors would still happen, but you wouldn't be notified in the UI.

If this was a QUOTA_BYTES error, I would say your Badger ran out of allowed space, but this FILE_ERROR_NO_SPACE error suggests your Chrome profile disk is out of space. I am not yet sure though. Could you check if this is the case?

**Comment by ghostwords** [comment]
Ah, I see now that you wrote that you still have around a gigabyte free. That does seem relatively low ... It's possible Chrome starts running into `FILE_ERROR_NO_SPACE` errors close to the disk actually being full.

**Comment by ghostwords** [comment]
@MarionGee Is this still a problem? Have you checked if your disk is low on space?

**Comment by piquan** [comment]
(Different user): I saw this message today.  I had run out of space on my disk yesterday, and cleaned some up; I may have not noticed the message until today.  The precise message is:

**Comment by ghostwords** [comment]
@piquan As I wrote [above](https://github.com/EFForg/privacybadger/issues/1866#issuecomment-366294364), `FILE_ERROR_NO_SPACE` seems to be about your disk being out of space, not Privacy Badger.

What may be confusing here is that Privacy Badger's error message only goes away on Privacy Badger (browser) restart, not directly following freeing up disk space.

To see how much extension storage (which is what the 5,242,880 byte limit applies to) your Privacy Badger uses, see https://github.com/EFForg/privacybadger/issues/1902#issuecomment-369797768.

**Comment by piquan** [comment]
Yeah, I figured it was a disk space thing.  It sounded like you were somewhat unsure with the previous report, so I decided to get a little more information and see if it helped.  Thanks!

**Comment by ghostwords** [comment]
Yep, I wasn't sure earlier, but now it seems more clear. Thank you for helping clear it up!

**Comment by ghostwords** [comment]
We may want to change the error message to go away and stay away after being dismissed by the user.

The behavior would be the same as now except when the user is able to address the problem (such as by freeing up disk space), the message would no longer reappear during browsing after being dismissed once (until the error starts happening again).

**Comment by ghostwords** [comment]
We may also want to just hide these errors since they are not relevant to Privacy Badger. Or replace the raw `FILE_ERROR_NO_SPACE` output with a friendlier message, like "Your disk seems to be low on space"?
