### ISSUE TITLE
Attack of the clones!

### ISSUE THREAD

**Issue by jawz101** [EFForg/privacybadger#1867]
https://chrome.google.com/webstore/detail/privacy-badger/fcdhcakmnmghnplhnpaofbibddopehfe?hl=en-US

**Comment by ghostwords** [comment]
Thanks for letting us know!

I reported the [copycat Badger](https://chrome.google.com/webstore/detail/privacy-badger/fcdhcakmnmghnplhnpaofbibddopehfe) using the "Report Abuse" link (to the right of the screenshots and under the description). You could report it too; it might help to generate multiple reports.

I checked the contents of this extension, and it doesn't seem to do anything (at this time, they could update it to do something else later) beyond opening eff.org when its button gets clicked.

@andresbase This seems to be a recurring problem (I would think not just for Privacy Badger but for all popular extensions).

**Comment by jawz101** [comment]
reported as well.  Glad I could help

**Comment by andresbase** [comment]
I've reported it through the usual (TM complaint) form. Should take a day and will keep an eye. It is definitely getting more common and will have to talk to the Chrome Store team about it.

**Comment by andresbase** [comment]
This clone is now removed.
