### ISSUE TITLE
Privacy Badger breaks Instapaper Bookmarklet

### ISSUE THREAD

**Issue by QuantumDotter** [EFForg/privacybadger#1868]
It's not specifically this site, but rather all sites when used with the Instapaper Bookmarklet. I use the Bookmarklet to save articles to my Instapaper account, and with Privacy Badger enabled, it doesn't work. I tried whitelisting instapaper.com to no avail. The content of the Bookmarklet is
`javascript:function iprl5()%7Bvar d=document,z=d.createElement('scr'+'ipt'),b=d.body,l=d.location;try%7Bif(!b)throw(0);d.title='(Saving...) '+d.title;z.setAttribute('src',l.protocol+'//www.instapaper.com/j/bRp4nxDLAdTo?u='+encodeURIComponent(l.href)+'&t='+(new Date().getTime()));b.appendChild(z);%7Dcatch(e)%7Balert('Please wait until the page has loaded.');%7D%7Diprl5();void(0)`

It would be great if you could fix this, please, as I rely on Instapaper daily for saving articles I find interesting.

**Comment by ghostwords** [comment]
Just confirming, does [unblocking `instapaper.com` on the Tracking Domains tab of Badger's options page](https://github.com/EFForg/privacybadger/issues/115#issuecomment-303795317) not help as a workaround?

**Comment by QuantumDotter** [comment]
Ah.... yes, thank you, that works nicely. I hadn't found that thread (I did search, not sure why it didn't turn up). I'd whitelisted the *instapaper.com domain, but that didn't do it. I'll close this thread.

**Comment by ghostwords** [comment]
I wonder if there is a way we could proactively fix this for Instapaper users, since it's not at all obvious what you need to do to get Instapaper working. Privacy Badger users run into [similar issues with other bookmarklets/extensions](https://github.com/EFForg/privacybadger/issues?utf8=✓&q=label%3A"broken+app"+) too.

**Comment by QuantumDotter** [comment]
What about having a list of known domains that show up as tracking domains, but are actually safe? Basically a whitelist. Then PrivacyBadger could periodically download the latest "safe" whitelist, and the users could choose whether or not to enable it and thus flag anything on the list as OK.
