### ISSUE TITLE
Tracking domain list alphabetical issue

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#1874]
Going through the list, I changed it to `user-controlled`, and I noticed one domain was out of alphabetical order:

![image](https://user-images.githubusercontent.com/12802056/36345712-1d95bdde-13fe-11e8-9e51-3ac6487727f7.png)

**Comment by ghostwords** [comment]
This is a problem anywhere we display domains: in the popup and on the options page (in both whitelisted and tracking domain lists). Another related bug is how multi-component TLDs (`co.uk`, `amazonaws.com`) domains end up being sorted based on the next-to-last TLD component (`bbc.co.uk` is sorted with the Cs).
