### ISSUE TITLE
nextcloud app store previews blocked

### ISSUE THREAD

**Issue by jospoortvliet** [EFForg/privacybadger#1878]
When running Nextcloud (an open source, privacy protecting, self-hosted 'cloud' replacement) you can use our app store to install the various apps developed by our community. These apps are hosted on github, as are their screenshots. To avoid Github tracking our users, we proxy the screenshots through http://usercontent.apps.nextcloud.com - but PrivacyBadger considers that a tracking site and blocks the previews.

It isn't a huge deal - users just don't see previews... But it is a bit sad ;-)

I can't really figure out how to fix that - the URL would be called from any nextcloud install, which can be on any URL - I guess this needs yellow or white listing or something?

**Comment by ghostwords** [comment]
Could you run the following JavaScript code in your Privacy Badger's background page console and let us know what it shows? For more information and instructions for getting to the background page, see https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b.

```javascript
(function () {
  const STR = "nextcloud";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

**Comment by ghostwords** [comment]
I wonder if this is one of those cases where login/session cookies are being sent for static resources, but I need to see an example page or two to say what's going on.

**Comment by ghostwords** [comment]
I'm going to close this for now. Let me know if you have more information.

**Comment by pgera** [comment]
Still seeing this issue. Here's the output from the background page:
```
**** ACTION_MAP for nextcloud
VM326:5 help.nextcloud.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1537870623079,
  "userAction": ""
}
VM326:5 mautic.nextcloud.com {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1538202533614,
  "userAction": ""
}
VM326:5 nextcloud.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
VM326:5 usercontent.apps.nextcloud.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1538199564702,
  "userAction": "user_block"
}
VM326:7 **** SNITCH_MAP for nextcloud
VM326:9 nextcloud.com [
  "google.com",
  "mydomain.io",
  "fribeiro.org"
]
```

The blocked images are from usercontent.apps.nextcloud.com

**Comment by ghostwords** [comment]
Does setting `nextcloud.com` to "yellow" on Privacy Badger's options page resolve this issue?

**Comment by pgera** [comment]
Yes. This was getting blocked by by nginx content security policy too. I had to relax it to img-src 'self' https://usercontent.apps.nextcloud.com data:. Perhaps nextcloud ought to handle this differently.

**Comment by danielkesselberg** [comment]
```
**** ACTION_MAP for nextcloud.com
docs.nextcloud.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1549571850493
}
nextcloud.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
apps.nextcloud.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1549194828869
}
usercontent.apps.nextcloud.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1550058053368
}
**** SNITCH_MAP for nextcloud.com
nextcloud.com [
  "github.com",
  "readthedocs.io",
  "php.net"
]

```

**Comment by ghostwords** [comment]
@jospoortvliet If `usercontent.apps.nextcloud.com` doesn't actually track users and the service is able and willing to abide by the [EFF Do Not Track policy](https://www.eff.org/dnt-policy)'s requirements on that domain, you could post [the policy](https://raw.githubusercontent.com/EFForg/dnt-policy/master/dnt-policy-1.0.txt) on the domain (https://usercontent.apps.nextcloud.com/.well-known/dnt-policy.txt) to tell Privacy Badger to always allow loading of resources from the domain.

It looks like we (in addition?) run into a Service Workers bug in Firefox, which is being tracked in #1144.
