### ISSUE TITLE
Not replacing t.co links in the new Twitter UI (the logged in or the mobile.twitter.com experience)

### ISSUE THREAD

**Issue by rugk** [EFForg/privacybadger#1886]
You should also supports Twitter's Lite/mobile site on https://mobile.twitter.com/home. It is, BTW, alos the version that is used as a Progressive Web Application (PWA) when using Twitter, so in Firefox 58 (which now supports PWAs), AFAIK, PrivacyBadger would then also work in Twitter's PWA.

**Comment by ghostwords** [comment]
This follows up on #1392. Related to #1426 and #1651.

**Comment by rugk** [comment]
BTW, Twitter seems to plan to use the new mobile.twitter.com site as their new default GUI, so we are getting hard problems here… :no_mouth:

**Comment by ghostwords** [comment]
Unfortunately, at this time it does not seem possible to provide `t.co` replacement in the new Twitter UI.
