### ISSUE TITLE
Google Docs problems

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1889]
Privacy Badger is breaking images and fonts ("Some fonts could not be loaded") in Google Docs. Disabling for the site makes the issues go away.

It seems that Privacy Badger learns to block a blank tracking domain:

![screen shot 2018-02-21 at 5 44 21 pm](https://user-images.githubusercontent.com/794578/36551843-87dd774c-17c6-11e8-8785-1866cbb131bc.png)
<br>
<details><summary>Sample reports, all from this month:</summary>

From `https://docs.google.com/drawings/`
>Inserted image from GDrive would not show in Google Draw

From `https://docs.google.com/document/`
>Hi, in Google docs with privacy badger enabled, you can't cut and paste images into documents.  Instead of pasting the image, google docs shows a rectangle with a grey exclamation mark in the middle.  Turning off privacy badger allowed me to paste an image from the clipboard into the document ok.

>Could not upload picture

>Privacy Badger on Google Docs. Shows two cases of display errors: (1) Google Docs font select menu fails to display fonts. (2) Also fails to display images embedded in docs.

>Images and any inserted objects in the document do not show. Also, constant notification that not all fonts could be loaded.

>When enabled - fonts and pasting images while on results in broken links

>images missing linked from other sites

From `https://docs.google.com/spreadsheets/`
>included images in spreadsheet are broken

>didn't let pictures load

From `https://docs.google.com/presentation/`
>the png files were not loading

> On Google slides, all the images are missing and it throws up an error saying 'some fonts could not be loaded'. Fixed after I disabled Privacy badger.
</details>
<br>
<details><summary>User error report counts from `docs.google.com` by month:</summary>

```
+---------+----------+
| ym      | count(*) |
+---------+----------+
| 2018-02 |       15 |
| 2018-01 |       26 |
| 2017-12 |       14 |
| 2017-11 |       22 |
| 2017-10 |       15 |
| 2017-09 |       20 |
| 2017-08 |       14 |
| 2017-07 |        7 |
| 2017-06 |        8 |
| 2017-05 |        7 |
| 2017-04 |        8 |
...
```
</details>

**Comment by ghostwords** [comment]
A different blank domain issue: #1447.

**Comment by ghostwords** [comment]
This seems connected to [`filesystem:` resource URIs](https://stackoverflow.com/questions/41887013/what-does-filesystem-in-a-url-mean), which [URI](https://github.com/EFForg/privacybadger/blob/99452c3ae803febbb9c07c09ffb4b71b2aa9afe7/src/lib/basedomain.js#L239) fails to parse. Can we assume that stripping `filesystem:` from the start of these URIs produces the appropriate URL?

**Comment by Jsnhlbr5** [comment]
I am considering picking up this issue (and maybe #1447); is there any legitimate reason for PB to learn to block a blank domain?  If so, how would it differentiate between the blanks it should and shouldn't block?

**Comment by Jsnhlbr5** [comment]
To answer your question about stripping `filesystem:` from the URIs; it doesn't seem to be a useful path without it (it's a local path not a server path), but it does contain the "responsible" domain.

**Comment by ghostwords** [comment]
A blank domain is just an unhandled error somewhere, not a valid state. Here, when try to get the domain using `extractHostFromURL`, the `URI` constructor throws an exception and we ignore it, returning an empty string. We should probably add a special case to `URI` that handles `filesystem:` URIs. 

Is how these `filesystem:` URIs work documented anywhere? Will their domain always be the domain of the original http(s) resource request? We could just assume this is the case, but it would be nice to understand this better.

**Comment by Jsnhlbr5** [comment]
From what I can find, the specification is still in flux, but according to https://w3c.github.io/filesystem-api/#origin-of-a-filesystem-url the first part of the URL must be the Origin of the FileSystem, and cross-origin requests are not allowed.  Based on that, the domain in the URL must be the domain of the resource request.

**Comment by Jsnhlbr5** [comment]
To expand on my question about blank domains: Would it be reasonable to disallow `""` as a key in the `BadgerStorage` class?

**Comment by ghostwords** [comment]
We could do that but then we wouldn't hear about this sort of problem from users anymore. I think it's fine to just fix the various causes of blank domains as we get to them.

**Comment by ghostwords** [comment]
Alright! No more reports from `docs.google.com` as of 2018.9.20
