### ISSUE TITLE
Pre-train Badger on popular websites

### ISSUE THREAD

**Issue by bcyphers** [EFForg/privacybadger#1891]
There have been several suggestions that PB ship with a "blacklist" of sites that are known trackers (#1333). The team has avoided this in order to stay out of the business of deciding who is and isn't a tracker -- it's more fair to let the Badger learn on its own. Still, it would be great to have PB start blocking common trackers right out of the box. 

One way to achieve that without breaking our policy would be to have a "training set" of websites that PB visits before being installed. We could set a list of, say, 1000 web pages from the Alexa or Majestic top million, visit each one with Privacy Badger, and have users opt-in to using the pre-trained list of trackers. The training set would be public, auditable, and editable by pull requests. Hopefully, this would mitigate the "why isn't pb working?" FAQs that new users have.

**Comment by ghostwords** [comment]
Previously: https://github.com/EFForg/privacybadger/issues/1333#issuecomment-313216425.

Related to #1299, #1374.

**Comment by ghostwords** [comment]
Related to #1299, #1374.

**Comment by jawz101** [comment]
It should also be completely wiped and re-trained every year or so to account for techniques and domains that are either newer or no longer exist.
