### ISSUE TITLE
Should I keep working on "good first issue"s?

### ISSUE THREAD

**Issue by mijiturka** [EFForg/privacybadger#1892]
I've done a couple of PRs now but I still find things I'd like to work on with the label "good first issue". Should I? I'm not particularly familiar with PB yet but I wouldn't want to take away issues from others who might be wondering if/where to start.
These were a great resource for me when I was just starting and there aren't that many of them.

**Comment by ghostwords** [comment]
Seems fine to me, I don't think you should hold back.

I added a few more "[good first issue](https://github.com/EFForg/privacybadger/labels/good%20first%20issue)" issues just now. If you'd like to work on any of them, or on any "[help wanted](https://github.com/EFForg/privacybadger/labels/help%20wanted)" issues, excellent, please do! Let me know if you see anything that you think should be labeled "good first issue" but isn't yet.
