### ISSUE TITLE
Consider enabling additional chrome.privacy settings

### ISSUE THREAD

**Issue by Hainish** [EFForg/privacybadger#1897]
The pref `privacy.resistFingerprinting` has been exposed to WebExtensions via `browser.privacy.websites.resistFingerprinting` as of Firefox 58.  We may want to flip this preference to better protect users against browser fingerprinting.

**Comment by Hainish** [comment]
Ref: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy/websites

**Comment by ghostwords** [comment]
Some of these settings are also available in Chrome:
- hyperlinkAuditingEnabled
- referrersEnabled
- thirdPartyCookiesAllowed (Chrome only, managed via `browser.websites.cookieConfig` in Firefox)

**Comment by Hainish** [comment]
Looks like thre may already be code for `hyperlinkAuditingEnabled`:

```bash
user@docker ~/workspace/privacybadger (master) $ git grep -i privacy.websites
src/js/migrations.js:      if (chrome.privacy.websites && chrome.privacy.websites.hyperlinkAuditingEnabled) {
src/js/migrations.js:        chrome.privacy.websites.hyperlinkAuditingEnabled.set({'value': false, 'scope': 'regular'});
```

**Comment by ghostwords** [comment]
Ah yes, and we want to let users disable these settings too: #740.

**Comment by ghostwords** [comment]
Related Firefox blog post: [Improving privacy without breaking the web](https://blog.mozilla.org/data/2018/01/26/improving-privacy-without-breaking-the-web/).

**Comment by ghostwords** [comment]
uBlock Origin discussion: https://github.com/gorhill/uBlock/issues/2381.

**Comment by ghostwords** [comment]
`privacy.resistFingerprinting` GSOC2020 proposal: https://github.com/mozilla/GSOC2020/blob/master/proposals/resistfingerprinting.md

**Comment by ghostwords** [comment]
We should probably disable prefetching (networkPredictionEnabled) by default. This is blocked by #740.
