### ISSUE TITLE
Flip firstparty.isolate pref in Firefox

### ISSUE THREAD

**Issue by Hainish** [EFForg/privacybadger#1898]
The pref `privacy.firstparty.isolate` has been exposed to WebExtensions via `browser.privacy.websites.firstPartyIsolate` as of Firefox 58.  We may want to flip this preference to better protect users against trackers.

**Comment by Hainish** [comment]
Ref: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy/websites

**Comment by ghostwords** [comment]
Let's consider all of these `browser.privacy` flags together in the same ticket. Merging with #1897.
