### ISSUE TITLE
Send snitch_map with error reports 

### ISSUE THREAD

**Issue by bcyphers** [EFForg/privacybadger#1901]
Sometimes it's hard to tell from error reports alone which hosts are causing certain 3rd-party domains to be blocked (e.g. #1880, #1882, #1883). When a user reports that a page is broken, PB could include snitch maps for all blocked domains on the page.

**Comment by ghostwords** [comment]
This conflicts with protection from local/unsophisticated attackers goal of #266.

If we dropped `snitch_map` entries for domains that Privacy Badger already decided to block, we'd have no data to share.

If we obfuscated (one-way, per-user-salted hashes) the domains (leaving debugging aside, Privacy Badger just needs to know when it saw a domain track across three different website domains, not what those domains are), we'd have useless (don't know the user salt) data.

**Comment by ghostwords** [comment]
This is sort of related to #1299.

I think whenever it's a [mystery](https://github.com/EFForg/privacybadger/labels/mystery), it's probably one of our mis-attribution bugs (probably #1997).

Having `snitch_map` data would indeed be helpful, but I don't think we need it. We already mostly know what needs fixing, plus error reports continue to trend down. Closing for now.
