### ISSUE TITLE
Privacy Badger extension and DuckDuckGo extension are creating an error

### ISSUE THREAD

**Issue by NachiketaVadera** [EFForg/privacybadger#1904]
Error details (Google Chrome):

This extension failed to redirect a network request to data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIHA7CgkvLyBodHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9kb3VibGVjbGljay1ncHQvcmVmZXJlbmNlCgl2YXIgbm9vcGZuID0gZnVuY3Rpb24oKSB7CgkJOwoJfS5iaW5kKCk7Cgl2YXIgbm9vcHRoaXNmbiA9IGZ1bmN0aW9uKCkgewoJCXJldHVybiB0aGlzOwoJfTsKCXZhciBub29wbnVsbGZuID0gZnVuY3Rpb24oKSB7CgkJcmV0dXJuIG51bGw7Cgl9OwoJdmFyIG5vb3BhcnJheWZuID0gZnVuY3Rpb24oKSB7CgkJcmV0dXJuIFtdOwoJfTsKCXZhciBub29wc3RyZm4gPSBmdW5jdGlvbigpIHsKCQlyZXR1cm4gJyc7Cgl9OwoJLy8KCXZhciBjb21wYW5pb25BZHNTZXJ2aWNlID0gewoJCWFkZEV2ZW50TGlzdGVuZXI6IG5vb3B0aGlzZm4sCgkJZW5hYmxlU3luY0xvYWRpbmc6IG5vb3BmbiwKCQlzZXRSZWZyZXNoVW5maWxsZWRTbG90czogbm9vcGZuCgl9OwoJdmFyIGNvbnRlbnRTZXJ2aWNlID0gewoJCWFkZEV2ZW50TGlzdGVuZXI6IG5vb3B0aGlzZm4sCgkJc2V0Q29udGVudDogbm9vcGZuCgl9OwoJdmFyIFBhc3NiYWNrU2xvdCA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CglwID0gUGFzc2JhY2tTbG90LnByb3RvdHlwZTsKCXAuZGlzcGxheSA9IG5vb3BmbjsKCXAuZ2V0ID0gbm9vcG51bGxmbjsKCXAuc2V0ID0gbm9vcHRoaXNmbjsKCXAuc2V0Q2xpY2tVcmwgPSBub29wdGhpc2ZuOwoJcC5zZXRUYWdGb3JDaGlsZERpcmVjdGVkVHJlYXRtZW50ID0gbm9vcHRoaXNmbjsKCXAuc2V0VGFyZ2V0aW5nID0gbm9vcHRoaXNmbjsKCXAudXBkYXRlVGFyZ2V0aW5nRnJvbU1hcCA9IG5vb3B0aGlzZm47Cgl2YXIgcHViQWRzU2VydmljZSA9IHsKCQlhZGRFdmVudExpc3RlbmVyOiBub29wdGhpc2ZuLAoJCWNsZWFyOiBub29wZm4sCgkJY2xlYXJDYXRlZ29yeUV4Y2x1c2lvbnM6IG5vb3B0aGlzZm4sCgkJY2xlYXJUYWdGb3JDaGlsZERpcmVjdGVkVHJlYXRtZW50OiBub29wdGhpc2ZuLAoJCWNsZWFyVGFyZ2V0aW5nOiBub29wdGhpc2ZuLAoJCWNvbGxhcHNlRW1wdHlEaXZzOiBub29wZm4sCgkJZGVmaW5lT3V0T2ZQYWdlUGFzc2JhY2s6IGZ1bmN0aW9uKCkgeyByZXR1cm4gbmV3IFBhc3NiYWNrU2xvdCgpOyB9LAoJCWRlZmluZVBhc3NiYWNrOiBmdW5jdGlvbigpIHsgcmV0dXJuIG5ldyBQYXNzYmFja1Nsb3QoKTsgfSwKCQlkaXNhYmxlSW5pdGlhbExvYWQ6IG5vb3BmbiwKCQlkaXNwbGF5OiBub29wZm4sCgkJZW5hYmxlQXN5bmNSZW5kZXJpbmc6IG5vb3BmbiwKCQllbmFibGVTaW5nbGVSZXF1ZXN0OiBub29wZm4sCgkJZW5hYmxlU3luY1JlbmRlcmluZzogbm9vcGZuLAoJCWVuYWJsZVZpZGVvQWRzOiBub29wZm4sCgkJZ2V0OiBub29wbnVsbGZuLAoJCWdldEF0dHJpYnV0ZUtleXM6IG5vb3BhcnJheWZuLAoJCXJlZnJlc2g6IG5vb3BmbiwKCQlzZXQ6IG5vb3B0aGlzZm4sCgkJc2V0Q2F0ZWdvcnlFeGNsdXNpb246IG5vb3B0aGlzZm4sCgkJc2V0Q2VudGVyaW5nOiBub29wZm4sCgkJc2V0Q29va2llT3B0aW9uczogbm9vcHRoaXNmbiwKCQlzZXRMb2NhdGlvbjogbm9vcHRoaXNmbiwKCQlzZXRQdWJsaXNoZXJQcm92aWRlZElkOiBub29wdGhpc2ZuLAoJCXNldFRhZ0ZvckNoaWxkRGlyZWN0ZWRUcmVhdG1lbnQ6IG5vb3B0aGlzZm4sCgkJc2V0VGFyZ2V0aW5nOiBub29wdGhpc2ZuLAoJCXNldFZpZGVvQ29udGVudDogbm9vcHRoaXNmbiwKCQl1cGRhdGVDb3JyZWxhdG9yOiBub29wZm4KCX07Cgl2YXIgU2l6ZU1hcHBpbmdCdWlsZGVyID0gZnVuY3Rpb24oKSB7CgkJOwoJfTsKCXAgPSBTaXplTWFwcGluZ0J1aWxkZXIucHJvdG90eXBlOwoJcC5hZGRTaXplID0gbm9vcHRoaXNmbjsKCXAuYnVpbGQgPSBub29wbnVsbGZuOwoJdmFyIFNsb3QgPSBmdW5jdGlvbigpIHsKCQk7Cgl9OwoJcCA9IFNsb3QucHJvdG90eXBlOwoJcC5hZGRTZXJ2aWNlID0gbm9vcHRoaXNmbjsKCXAuY2xlYXJDYXRlZ29yeUV4Y2x1c2lvbnMgPSBub29wdGhpc2ZuOwoJcC5jbGVhclRhcmdldGluZyA9IG5vb3B0aGlzZm47CglwLmRlZmluZVNpemVNYXBwaW5nID0gbm9vcHRoaXNmbjsKCXAuZ2V0ID0gbm9vcG51bGxmbjsKCXAuZ2V0QWRVbml0UGF0aCA9IG5vb3BhcnJheWZuOwoJcC5nZXRBdHRyaWJ1dGVLZXlzID0gbm9vcGFycmF5Zm47CglwLmdldENhdGVnb3J5RXhjbHVzaW9ucyA9IG5vb3BhcnJheWZuOwoJcC5nZXREb21JZCA9IG5vb3BzdHJmbjsKCXAuZ2V0U2xvdEVsZW1lbnRJZCA9IG5vb3BzdHJmbjsKCXAuZ2V0U2xvdElkID0gbm9vcHRoaXNmbjsKCXAuZ2V0VGFyZ2V0aW5nID0gbm9vcGFycmF5Zm47CglwLmdldFRhcmdldGluZ0tleXMgPSBub29wYXJyYXlmbjsKCXAuc2V0ID0gbm9vcHRoaXNmbjsKCXAuc2V0Q2F0ZWdvcnlFeGNsdXNpb24gPSBub29wdGhpc2ZuOwoJcC5zZXRDbGlja1VybCA9IG5vb3B0aGlzZm47CglwLnNldENvbGxhcHNlRW1wdHlEaXYgPSBub29wdGhpc2ZuOwoJcC5zZXRUYXJnZXRpbmcgPSBub29wdGhpc2ZuOwoJLy8KCXZhciBncHQgPSB3aW5kb3cuZ29vZ2xldGFnIHx8IHt9OwoJdmFyIGNtZCA9IGdwdC5jbWQgfHwgW107CglncHQuYXBpUmVhZHkgPSB0cnVlOwoJZ3B0LmNtZCA9IFtdOwoJZ3B0LmNtZC5wdXNoID0gZnVuY3Rpb24oYSkgewoJCXRyeSB7CgkJCWEoKTsKCQl9IGNhdGNoIChleCkgewoJCX0KCQlyZXR1cm4gMTsKCX07CglncHQuY29tcGFuaW9uQWRzID0gZnVuY3Rpb24oKSB7IHJldHVybiBjb21wYW5pb25BZHNTZXJ2aWNlOyB9OwoJZ3B0LmNvbnRlbnQgPSBmdW5jdGlvbigpIHsgcmV0dXJuIGNvbnRlbnRTZXJ2aWNlOyB9OwoJZ3B0LmRlZmluZU91dE9mUGFnZVNsb3QgPSBmdW5jdGlvbigpIHsgcmV0dXJuIG5ldyBTbG90KCk7IH07CglncHQuZGVmaW5lU2xvdCA9IGZ1bmN0aW9uKCkgeyByZXR1cm4gbmV3IFNsb3QoKTsgfTsKCWdwdC5kZXN0cm95U2xvdHMgPSBub29wZm47CglncHQuZGlzYWJsZVB1Ymxpc2hlckNvbnNvbGUgPSBub29wZm47CglncHQuZGlzcGxheSA9IG5vb3BmbjsKCWdwdC5lbmFibGVTZXJ2aWNlcyA9IG5vb3BmbjsKCWdwdC5nZXRWZXJzaW9uID0gbm9vcHN0cmZuOwoJZ3B0LnB1YmFkcyA9IGZ1bmN0aW9uKCkgeyByZXR1cm4gcHViQWRzU2VydmljZTsgfTsKCWdwdC5wdWJhZHNSZWFkeSA9IHRydWU7CglncHQuc2V0QWRJZnJhbWVUaXRsZSA9IG5vb3BmbjsKCWdwdC5zaXplTWFwcGluZyA9IGZ1bmN0aW9uKCkgeyByZXR1cm4gbmV3IFNpemVNYXBwaW5nQnVpbGRlcigpOyB9OwoJd2luZG93Lmdvb2dsZXRhZyA9IGdwdDsKCXdoaWxlICggY21kLmxlbmd0aCAhPT0gMCApIHsKCQlncHQuY21kLnB1c2goY21kLnNoaWZ0KCkpOwoJfQp9KSgpOw== because another extension (DuckDuckGo Privacy Essentials) redirected it to data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIHA7CgkvLyBodHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9kb3VibGVjbGljay1ncHQvcmVmZXJlbmNlCgl2YXIgbm9vcGZuID0gZnVuY3Rpb24oKSB7CgkJOwoJfS5iaW5kKCk7Cgl2YXIgbm9vcHRoaXNmbiA9IGZ1bmN0aW9uKCkgewoJCXJldHVybiB0aGlzOwoJfTsKCXZhciBub29wbnVsbGZuID0gZnVuY3Rpb24oKSB7CgkJcmV0dXJuIG51bGw7Cgl9OwoJdmFyIG5vb3BhcnJheWZuID0gZnVuY3Rpb24oKSB7CgkJcmV0dXJuIFtdOwoJfTsKCXZhciBub29wc3RyZm4gPSBmdW5jdGlvbigpIHsKCQlyZXR1cm4gJyc7Cgl9OwoJLy8KCXZhciBjb21wYW5pb25BZHNTZXJ2aWNlID0gewoJCWFkZEV2ZW50TGlzdGVuZXI6IG5vb3B0aGlzZm4sCgkJZW5hYmxlU3luY0xvYWRpbmc6IG5vb3BmbiwKCQlzZXRSZWZyZXNoVW5maWxsZWRTbG90czogbm9vcGZuCgl9OwoJdmFyIGNvbnRlbnRTZXJ2aWNlID0gewoJCWFkZEV2ZW50TGlzdGVuZXI6IG5vb3B0aGlzZm4sCgkJc2V0Q29udGVudDogbm9vcGZuCgl9OwoJdmFyIFBhc3NiYWNrU2xvdCA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CglwID0gUGFzc2JhY2tTbG90LnByb3RvdHlwZTsKCXAuZGlzcGxheSA9IG5vb3BmbjsKCXAuZ2V0ID0gbm9vcG51bGxmbjsKCXAuc2V0ID0gbm9vcHRoaXNmbjsKCXAuc2V0Q2xpY2tVcmwgPSBub29wdGhpc2ZuOwoJcC5zZXRUYWdGb3JDaGlsZERpcmVjdGVkVHJlYXRtZW50ID0gbm9vcHRoaXNmbjsKCXAuc2V0VGFyZ2V0aW5nID0gbm9vcHRoaXNmbjsKCXAudXBkYXRlVGFyZ2V0aW5nRnJvbU1hcCA9IG5vb3B0aGlzZm47Cgl2YXIgcHViQWRzU2VydmljZSA9IHsKCQlhZGRFdmVudExpc3RlbmVyOiBub29wdGhpc2ZuLAoJCWNsZWFyOiBub29wZm4sCgkJY2xlYXJDYXRlZ29yeUV4Y2x1c2lvbnM6IG5vb3B0aGlzZm4sCgkJY2xlYXJUYWdGb3JDaGlsZERpcmVjdGVkVHJlYXRtZW50OiBub29wdGhpc2ZuLAoJCWNsZWFyVGFyZ2V0aW5nOiBub29wdGhpc2ZuLAoJCWNvbGxhcHNlRW1wdHlEaXZzOiBub29wZm4sCgkJZGVmaW5lT3V0T2ZQYWdlUGFzc2JhY2s6IGZ1bmN0aW9uKCkgeyByZXR1cm4gbmV3IFBhc3NiYWNrU2xvdCgpOyB9LAoJCWRlZmluZVBhc3NiYWNrOiBmdW5jdGlvbigpIHsgcmV0dXJuIG5ldyBQYXNzYmFja1Nsb3QoKTsgfSwKCQlkaXNhYmxlSW5pdGlhbExvYWQ6IG5vb3BmbiwKCQlkaXNwbGF5OiBub29wZm4sCgkJZW5hYmxlQXN5bmNSZW5kZXJpbmc6IG5vb3BmbiwKCQllbmFibGVTaW5nbGVSZXF1ZXN0OiBub29wZm4sCgkJZW5hYmxlU3luY1JlbmRlcmluZzogbm9vcGZuLAoJCWVuYWJsZVZpZGVvQWRzOiBub29wZm4sCgkJZ2V0OiBub29wbnVsbGZuLAoJCWdldEF0dHJpYnV0ZUtleXM6IG5vb3BhcnJheWZuLAoJCWdldFRhcmdldGluZzogbm9vcGZuLAoJCWdldFRhcmdldGluZ0tleXM6IG5vb3BhcnJheWZuLAoJCWdldFNsb3RzOiBub29wYXJyYXlmbiwKCQlyZWZyZXNoOiBub29wZm4sCgkJc2V0OiBub29wdGhpc2ZuLAoJCXNldENhdGVnb3J5RXhjbHVzaW9uOiBub29wdGhpc2ZuLAoJCXNldENlbnRlcmluZzogbm9vcGZuLAoJCXNldENvb2tpZU9wdGlvbnM6IG5vb3B0aGlzZm4sCgkJc2V0Rm9yY2VTYWZlRnJhbWU6IG5vb3B0aGlzZm4sCgkJc2V0TG9jYXRpb246IG5vb3B0aGlzZm4sCgkJc2V0UHVibGlzaGVyUHJvdmlkZWRJZDogbm9vcHRoaXNmbiwKCQlzZXRTYWZlRnJhbWVDb25maWc6IG5vb3B0aGlzZm4sCgkJc2V0VGFnRm9yQ2hpbGREaXJlY3RlZFRyZWF0bWVudDogbm9vcHRoaXNmbiwKCQlzZXRUYXJnZXRpbmc6IG5vb3B0aGlzZm4sCgkJc2V0VmlkZW9Db250ZW50OiBub29wdGhpc2ZuLAoJCXVwZGF0ZUNvcnJlbGF0b3I6IG5vb3BmbgoJfTsKCXZhciBTaXplTWFwcGluZ0J1aWxkZXIgPSBmdW5jdGlvbigpIHsKCQk7Cgl9OwoJcCA9IFNpemVNYXBwaW5nQnVpbGRlci5wcm90b3R5cGU7CglwLmFkZFNpemUgPSBub29wdGhpc2ZuOwoJcC5idWlsZCA9IG5vb3BudWxsZm47Cgl2YXIgU2xvdCA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CglwID0gU2xvdC5wcm90b3R5cGU7CglwLmFkZFNlcnZpY2UgPSBub29wdGhpc2ZuOwoJcC5jbGVhckNhdGVnb3J5RXhjbHVzaW9ucyA9IG5vb3B0aGlzZm47CglwLmNsZWFyVGFyZ2V0aW5nID0gbm9vcHRoaXNmbjsKCXAuZGVmaW5lU2l6ZU1hcHBpbmcgPSBub29wdGhpc2ZuOwoJcC5nZXQgPSBub29wbnVsbGZuOwoJcC5nZXRBZFVuaXRQYXRoID0gbm9vcGFycmF5Zm47CglwLmdldEF0dHJpYnV0ZUtleXMgPSBub29wYXJyYXlmbjsKCXAuZ2V0Q2F0ZWdvcnlFeGNsdXNpb25zID0gbm9vcGFycmF5Zm47CglwLmdldERvbUlkID0gbm9vcHN0cmZuOwoJcC5nZXRTbG90RWxlbWVudElkID0gbm9vcHN0cmZuOwoJcC5nZXRTbG90SWQgPSBub29wdGhpc2ZuOwoJcC5nZXRUYXJnZXRpbmcgPSBub29wYXJyYXlmbjsKCXAuZ2V0VGFyZ2V0aW5nS2V5cyA9IG5vb3BhcnJheWZuOwoJcC5zZXQgPSBub29wdGhpc2ZuOwoJcC5zZXRDYXRlZ29yeUV4Y2x1c2lvbiA9IG5vb3B0aGlzZm47CglwLnNldENsaWNrVXJsID0gbm9vcHRoaXNmbjsKCXAuc2V0Q29sbGFwc2VFbXB0eURpdiA9IG5vb3B0aGlzZm47CglwLnNldFRhcmdldGluZyA9IG5vb3B0aGlzZm47CgkvLwoJdmFyIGdwdCA9IHdpbmRvdy5nb29nbGV0YWcgfHwge307Cgl2YXIgY21kID0gZ3B0LmNtZCB8fCBbXTsKCWdwdC5hcGlSZWFkeSA9IHRydWU7CglncHQuY21kID0gW107CglncHQuY21kLnB1c2ggPSBmdW5jdGlvbihhKSB7CgkJdHJ5IHsKCQkJYSgpOwoJCX0gY2F0Y2ggKGV4KSB7CgkJfQoJCXJldHVybiAxOwoJfTsKCWdwdC5jb21wYW5pb25BZHMgPSBmdW5jdGlvbigpIHsgcmV0dXJuIGNvbXBhbmlvbkFkc1NlcnZpY2U7IH07CglncHQuY29udGVudCA9IGZ1bmN0aW9uKCkgeyByZXR1cm4gY29udGVudFNlcnZpY2U7IH07CglncHQuZGVmaW5lT3V0T2ZQYWdlU2xvdCA9IGZ1bmN0aW9uKCkgeyByZXR1cm4gbmV3IFNsb3QoKTsgfTsKCWdwdC5kZWZpbmVTbG90ID0gZnVuY3Rpb24oKSB7IHJldHVybiBuZXcgU2xvdCgpOyB9OwoJZ3B0LmRlc3Ryb3lTbG90cyA9IG5vb3BmbjsKCWdwdC5kaXNhYmxlUHVibGlzaGVyQ29uc29sZSA9IG5vb3BmbjsKCWdwdC5kaXNwbGF5ID0gbm9vcGZuOwoJZ3B0LmVuYWJsZVNlcnZpY2VzID0gbm9vcGZuOwoJZ3B0LmdldFZlcnNpb24gPSBub29wc3RyZm47CglncHQucHViYWRzID0gZnVuY3Rpb24oKSB7IHJldHVybiBwdWJBZHNTZXJ2aWNlOyB9OwoJZ3B0LnB1YmFkc1JlYWR5ID0gdHJ1ZTsKCWdwdC5zZXRBZElmcmFtZVRpdGxlID0gbm9vcGZuOwoJZ3B0LnNpemVNYXBwaW5nID0gZnVuY3Rpb24oKSB7IHJldHVybiBuZXcgU2l6ZU1hcHBpbmdCdWlsZGVyKCk7IH07Cgl3aW5kb3cuZ29vZ2xldGFnID0gZ3B0OwoJd2hpbGUgKCBjbWQubGVuZ3RoICE9PSAwICkgewoJCWdwdC5jbWQucHVzaChjbWQuc2hpZnQoKSk7Cgl9Cn0pKCk7.

**Comment by ghostwords** [comment]
Thanks for letting us know! This shouldn't cause any actual problems, but should be fixed with our next update.
