### ISSUE TITLE
Use Codecov

### ISSUE THREAD

**Issue by bcyphers** [EFForg/privacybadger#1908]
[Codecov](https://codecov.io/) is useful for getting both high-level snapshots of and fine-grained data about the test coverage of a project. It's used in lots of other open-source projects, including [HTTPS everywhere](https://github.com/EFForg/https-everywhere). It shouldn't be too much work to set up.

**Comment by bcyphers** [comment]
Looks like a duplicate, and like this is not high-priority right now.

**Comment by ghostwords** [comment]
If you are curious to see what's covered now, see https://github.com/EFForg/privacybadger/issues/1169#issuecomment-308251022. You could configure QUnit to not run tests automatically (by setting [`config.autostart`](https://api.qunitjs.com/config/QUnit.config) to `false`), start coverage reporting in Chrome dev tools, and run `QUnit.start()` to exercise the code.
