### ISSUE TITLE
TypeError: can't access dead object

### ISSUE THREAD

**Issue by BigNickBurgess** [EFForg/privacybadger#1909]
Privacy badger extension on FF keeps telling me to report this error

TypeError: can't access dead object

Gives no other details on it aside from that.

**Comment by ghostwords** [comment]
Does restarting Privacy Badger (by restarting the browser) make the error go away?

Do you know what might have caused this error to start happening? Is this the same problem as #1429?

**Comment by BigNickBurgess** [comment]
Yes id just reinstalled and imported my data.  I disabled and renabled
privacy badger to fix it).

**Comment by ghostwords** [comment]
It seems like this is the same issue as #1429.
