### ISSUE TITLE
cdn.pandacommerce.net blocked

### ISSUE THREAD

**Issue by flundstrom2** [EFForg/privacybadger#1910]
Hi,

cdn.pandacommerce.net is flagged as red, and completely blocked. This is not good, since this are servers belonging to the Pandacommerce shophosting service, affecting lots of webshops in Sweden by totally breaking them.

Manually marking it yellow, resolves the issue. Could you please yellow-list cdn.pandacommerce.net by default?

**Comment by ghostwords** [comment]
This seems related to #1824.

Could you run the following script in your Badger's background page console and share what it prints out? You could also send the output to alexei at eff dot org if you'd rather not post it here.
```javascript
(function () {
  const STR = "pandacommerce";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by flundstrom2** [comment]
Output from Chrome:

```
(function () {
  const STR = "pandacommerce";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
VM118:3 **** ACTION_MAP for pandacommerce
VM118:5 app.pandacommerce.net {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1521908635097,
  "userAction": ""
}
VM118:5 apps.pandacommerce.net {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1521752626233,
  "userAction": ""
}
VM118:5 cdn.pandacommerce.net {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1521567779656,
  "userAction": "user_block"
}
VM118:5 direct.pandacommerce.net {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1519578033778,
  "userAction": "user_block"
}
VM118:5 flutronic.pandacommerce.net {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1521433884255,
  "userAction": ""
}
VM118:5 pandacommerce.net {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
VM118:5 pandacommerce.reamaze.io {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1522060832205,
  "userAction": ""
}
VM118:5 www.pandacommerce.net {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1520036386128,
  "userAction": ""
}
VM118:7 **** SNITCH_MAP for pandacommerce
VM118:9 pandacommerce.net [
  "sexleksakeroutlet.se",
  "andromedaslust.com",
  "andromedaslust.se"
]
undefined
```

**Comment by flundstrom2** [comment]
And by the way, re #1824 : Yes, Klarna is *the* major payment broker in Sweden. I use them, too, in my pandacommerce-shop. My guess is, Klarna has 75-80% of the store checkout market. Or even more.

**Comment by ghostwords** [comment]
Does it make sense to yellowlist all `pandacommerce.net` domains? If we only yellowlist the "cdn" subdomain, shop pages will work but checkout pages will probably break.

Can you still place a PandaCommerce-powered order with all `pandacommerce.net` domains on the yellowlist? Yellowlisted domains get "cookieblocked", meaning Privacy Badger will deny getting or setting cookies and localStorage.

**Comment by flundstrom2** [comment]
All shops use individual subdomains of pandacommerce.net.

My shop's official adress is [www.andromedaslust.se](https://www.andromedaslust.se/), which is DNSed to flutronic.pandacommerce.net. Another shop, sexleksakeroutlet.se, is DNSed to dildokungen.pandacommerce.net, etc. 

Being in EU, all sites need to get cookie approval from the user ("This site uses cookie, bla bla bla"),  so the user has implicitly approved the use of cookies by using the shop.

I hope this gives a better clue to your questions, since I don't have enough knowledge to give unambiguous answers to your questions.

**Comment by ghostwords** [comment]
I just added `pandacommerce.net` to Privacy Badger's yellowlist. You should see this update get applied within the next day. You can also get it right away by restarting your browser.
