### ISSUE TITLE
Options menu sliders do not register when clicking at the bottom of the slider 

### ISSUE THREAD

**Issue by bcyphers** [EFForg/privacybadger#1912]
When manipulating sliders in the options menu, the sliders respond differently depending on where you click. If you click or click and drag in the middle of the slider, the mouse cursor turns into a hand, and the slider functions as you would expect. 
<img src="https://media.giphy.com/media/2dq8GH7IprzkSnC7Lu/giphy.gif" alt="functioning sliders">

If you click near the very bottom of the slider, the UI itself will react, but changes to tracker settings do not persist.
<img src="https://media.giphy.com/media/LWGmRVDFLl3uWUcLle/giphy.gif" alt="broken sliders">

This is not the case with the popup sliders; the cursor does switch between a hand and a cursor depending on where in the slider it is, but the slider functions either way.

**Comment by ghostwords** [comment]
Related to #1863.
