### ISSUE TITLE
Clicking on the Tracking domains tab makes the screen scroll down

### ISSUE THREAD

**Issue by jony0008** [EFForg/privacybadger#1918]
The screen scrolls down when clicking on the Tracking domains tab, this doesn't happen when clicking on any other tab.

**Comment by ghostwords** [comment]
This happens on any tab where the window is short enough to produce a scrollbar for that tab's contents. The Tracking Domains tab is likely to take up more vertical space than other tabs, so it's easiest to run into this quirk there.

**Comment by ghostwords** [comment]
This behavior is an unintended side effect of #1703.
