### ISSUE TITLE
Blocking Google Account Chooser Sign-in

### ISSUE THREAD

**Issue by benjaminpwarren** [EFForg/privacybadger#1925]
Privacy Badger seems to have just started blocking http://www.gstatic.com/accountchooser/client.js from executing properly, meaning no sign-in to sites that use it. (I'm using Firebase Auth UI on one of my projects, and I can't sign in unless I disable Privacy Badger.)

**Comment by ghostwords** [comment]
`gstatic.com` is on our yellowlist, which means Privacy Badger shouldn't learn to block `gstatic.com` entirely, only block its cookies ...

Could you run the following script in your Badger's background page console and share what it prints out?
```javascript
(function () {
  const STR = "gstatic";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by ghostwords** [comment]
Let me know if you have more information. I'm going to close this for now.
