### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by nbonnotte** [EFForg/privacybadger#1932]
```
Package is invalid. Details: 'Default locale is defined but default data couldn't be loaded.'.
```
Chromium version 63.0.3239.84 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)

**Comment by ghostwords** [comment]
Hello! This seems like a [Chrome bug where your Chrome has pending updates and needs to be restarted](https://bugs.chromium.org/p/chromium/issues/detail?id=57370#c105). Let me know if that is or isn't the case.
