### ISSUE TITLE
Bufferapp conflict

### ISSUE THREAD

**Issue by richards1052** [EFForg/privacybadger#1937]
I just installed PB both for Chrome and Firefox.  I also use the Bufferapp to post to my social media accounts.  In Firefox, Buffer still works fine.  But when I try to use Buffer in Chrome it just hangs and never connects to the Buffer server.  I tested this by disabling all my extensions and then re-enabling them.  When I got to re-enabling PB, that's when the same error recurred.

I've contacted Buffer to let them know about this.  But I wanted to let the PB developers know about it as well.

**Comment by ghostwords** [comment]
Do you see any Buffer-related domains if you search for "buffer" on the Tracking Domains tab of Privacy Badger's options page? Does adjusting their sliders to "green" fix the issue?

**Comment by ghostwords** [comment]
Previously: #337, #546.

**Comment by ghostwords** [comment]
Let me know if you have more information. Closing this for now.
