### ISSUE TITLE
api.luxgroup.com

### ISSUE THREAD

**Issue by joshuacullenlux** [EFForg/privacybadger#1945]
https://luxuryescapes.com/au website is being broken by the blocking of it's content api.

```
api.luxgroup.com
```

It will work if it's moved to yellow. Could we get the api domain added to the yellow list?

```
**** ACTION_MAP for api.luxgroup.com
VM656:5 api.luxgroup.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1523143480008
}
**** SNITCH_MAP for api.luxgroup.com

**Comment by ghostwords** [comment]
Hello! Could you rerun the [debugging code](https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b) but just for "luxgroup.com"?

**Comment by forkfork** [comment]
@ghostwords any suggested next steps? I'm having this issue too

**Comment by ghostwords** [comment]
@forkfork Could you run the following script in your Badger's background page console and share what it prints out?
```javascript
(function () {
  const STR = "luxgroup.com";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.
