### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by billadams176** [EFForg/privacybadger#1948]
I received the following when trying to do a lookup at whois.com :

IO error: .../000003.log: FILE_ERROR_NO_SPACE (ChromeMethodBFE: 3::WritableFileAppend::8)

**Comment by ghostwords** [comment]
I think this means your disk is running out of space. Please see #1866 for more information.

**Comment by ghostwords** [comment]
We are going to make this message more friendly in #1913.
