### ISSUE TITLE
An error but what does it mean?

### ISSUE THREAD

**Issue by mademoiselle90** [EFForg/privacybadger#1951]
I got told to report the following error by my privacy badger extension on Chrome, "O error: .../027441.log: FILE_ERROR_NO_SPACE (ChromeMethodBFE: 3::WritableFileAppend::8)" but I have no clue what it means or what it does for its functioning.

**Comment by ghostwords** [comment]
This means your disk is running out of space. Please see #1866 for more information. We are going to make this message more friendly in #1913.
