### ISSUE TITLE
File read fails for some reason.

### ISSUE THREAD

**Issue by NoLongerBreathedIn** [EFForg/privacybadger#1952]
Complete error:
IO error: .../056073.ldb: Could not perform read (ChromeMethodOnly: 2::RandomAccessFileRead)
You got me.
(Chrome 65.0.3325.181/OSX 10.12.3, mid-2012 MacBook Pro)

**Comment by ghostwords** [comment]
This is an error notification I added as part of #1848. It shows errors that happen while trying to save Privacy Badger state (your Badger's knowledge of who the trackers are, basically) to disk. Before #1848, the errors would still happen, but you wouldn't be notified in the UI.

Looks like "Could not perform read" errors happen when [Chrome tried to to and failed to read data from one of its LevelDB files](https://chromium.googlesource.com/chromium/src/+/2a9a8201b8c0b213aa41b6a390e9324113176f15/third_party/leveldatabase/env_chromium.cc#249). It doesn't seem like this error has anything to do with Privacy Badger ... This might be a Chrome bug, or it might be a problem with your disk drive.

**Comment by ghostwords** [comment]
Do you get this error again if you restart your browser?

**Comment by NoLongerBreathedIn** [comment]
Yep.
