### ISSUE TITLE
Privacy Badger breaks password-protected videos on Air Mozilla

### ISSUE THREAD

**Issue by ehsan** [EFForg/privacybadger#1969]
This happens due to mozillalives-i.akamaihd.net being yellowlisted on air.mozilla.org which breaks the video playback on Air Mozilla if the video is password protected.  Moving the slider for mozillalives-i.akamaihd.net to "green" fixes the issue.

**Comment by ghostwords** [comment]
If `mozillalives-i.akamaihd.net` is compliant with the [EFF Do Not Track policy](https://www.eff.org/dnt-policy), would it be possible to post the policy on that domain? This will tell Privacy Badger to always allow loading of resources from `mozillalives-i.akamaihd.net`.

**Comment by ehsan** [comment]
I asked from the team at Mozilla maintaining this site, here is their response:

"Unfortunately, we lack platfrom development resources or web dev for legacy AirMozilla. The new platform (airmo.mozilla.org) should not have this problem and we will be moving to the new platform nex month."

**Comment by ghostwords** [comment]
OK, thank you for following up with them! I'll close this then since there is no straightforward fix from our end, there is a workaround, and the site should change soon.
