### ISSUE TITLE
static.budgecovers.com

### ISSUE THREAD

**Issue by colinwphillips** [EFForg/privacybadger#1984]
Hi,

All of my static content, which are images (jpg/png,etc.) are being blocked by privacy badger.

How might we whitelist this (sub)/domain?

Thanks!

**Comment by ghostwords** [comment]
Could you run the following script in your Badger's background page console and share what it prints out?
```javascript
(function () {
  const STR = "budgecovers";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by ghostwords** [comment]
This might be the same kind of issue as #1995, but I can't say without more information.

**Comment by ghostwords** [comment]
I'm going to close this for now. Let me know if you have more information.

**Comment by colinwphillips** [comment]
I am no longer able to reproduce, even in incognito so I assume the issue
has otherwise been fixed. Thanks!
