### ISSUE TITLE
Picks up my own website as a tracker?

### ISSUE THREAD

**Issue by LiamDawe** [EFForg/privacybadger#1995]
Hi, recently came across an issue where Privacy Badger has been claiming my site https://www.gamingonlinux.com is a tracker and fully blocks any external content from it? 

RSS feeds for example, tested in both feedly and tiny tiny RSS - Privacy Badger set it to block the images from the feed.

How can I get this fixed? My site is not a tracker :+1:

**Comment by ghostwords** [comment]
My guess is that you are sending your login cookies along with requests to static resources.

Could you run the following script in your Badger's background page console and share what it prints out?
```javascript
(function () {
  const STR = "gamingonlinux.com";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by LiamDawe** [comment]
Not sure I'm doing this right:

> (function () {
>   const STR = "gamingonlinux.com";
>   console.log("**** ACTION_MAP for", STR);
>   _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
>     if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
>   });
>   console.log("**** SNITCH_MAP for", STR);
>   _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
>     if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
>   });
> }());
> **** ACTION_MAP for gamingonlinux.com 
> **** SNITCH_

MAP for gamingonlinux.com 
undefined

**Comment by ghostwords** [comment]
Did you run this in the browser with Privacy Badger that learned to block your domain? Did you run this in Badger's background page, and not anywhere else (like the popup)?

**Comment by LiamDawe** [comment]
Sorry, that was firefox, here's Chrome:

> (function () {
>   const STR = "gamingonlinux.com";
>   console.log("**** ACTION_MAP for", STR);
>   _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
>     if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
>   });
>   console.log("**** SNITCH_MAP for", STR);
>   _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
>     if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
>   });
> }());
> VM236:3 **** ACTION_MAP for gamingonlinux.com
> VM236:5 gamingonlinux.com {
>   "dnt": false,
>   "heuristicAction": "block",
>   "nextUpdateTime": 0,
>   "userAction": ""
> }
> VM236:5 www.gamingonlinux.com {
>   "dnt": false,
>   "heuristicAction": "block",
>   "nextUpdateTime": 1525075452272,
>   "userAction": "user_allow"
> }
> VM236:7 **** SNITCH_MAP for gamingonlinux.com
> VM236:9 gamingonlinux.com [
>   "joindiaspora.com",
>   "patreon.com",
>   "discordia.dyndns.tv"
> ]

**Comment by ghostwords** [comment]
Ah, OK, thanks. This says your Privacy Badger saw resources from `www.gamingonlinux.com` perform tracking on `joindiaspora.com`, `patreon.com`, and `discordia.dyndns.tv`. Are these sites where you would have come across `www.gamingonlinux.com` resources?

**Comment by LiamDawe** [comment]
Images from OpenGraph tags (to show rich media, like an image beside an article tagline) were being blocked by PB.

Patreon I don't believe pulls in any resources from us, since they host all stuff themselves. We have a Patreon page, but there's nothing on our site directly pulling anything from Patreon.

Same for Discord, we have a Discord channel, but the website isn't pulling anything from the Discord.

**Comment by ghostwords** [comment]
Do you have cookies or other storage from `gamingonlinux.com` in your Chrome? You can check by visiting `chrome://settings/siteData` and searching for "gamingonlinux". Please do not post the contents of cookies here.

**Comment by LiamDawe** [comment]
Updated my previous comment with more info.

As for cookies, yes:
"__cfduid" - required by cloudflare
And two others from our login system, like any other site where you login.

**Comment by ghostwords** [comment]
Yep, so it's what I thought. Your login cookies are being sent along with static resources. Anybody who logs into your site could run into this issue; other people should not.

To improve website performance/security, you would ideally avoid having login/session cookies be associated with static resources/API endpoints (by configuring a dedicated static resource domain that doesn't overlap with the login domain, for example).

If you don't perform any tracking and are otherwise compliant with the [EFF Do Not Track policy](https://www.eff.org/dnt-policy), you could post the policy on each affected domain, which will tell Privacy Badger to always allow loading of resources from the domain.

**Comment by LiamDawe** [comment]
As I'm sure you know, it's not a simple task to suddenly make a website use an entirely separate domain for all static resources, not really something a single-person run site can just do with limited resources.

We don't perform any tracking, we don't use google analytics or anything. Where would I post such a thing so it can pick it up? Do I just put it in a "dnt-policy-1.0.txt" file in my website root folder and the plugin would scan for that file?

**Comment by ghostwords** [comment]
You have to serve the **exact** contents of https://raw.githubusercontent.com/EFForg/dnt-policy/master/dnt-policy-1.0.txt at https://www.gamingonlinux.com/.well-known/dnt-policy.txt

**Comment by LiamDawe** [comment]
Okay, to be clear then, where it says this:

> This file will always
be posted via HTTPS at https://example-domain.com/.well-known/dnt-policy.txt
to indicate this fact.

I don't need to adjust that for my actual domain? Just so we're crystal clear as you say "exact contents"

**Comment by ghostwords** [comment]
Correct.

**Comment by LiamDawe** [comment]
Okay, great. I've now done that, hopefully this will be solved then :+1:

**Comment by ghostwords** [comment]
Looks good to me. If your Badger already checked the domain for DNT recently, it can take up to a week for the domain to get rechecked. You could run `badger.storage.touchDNTRecheckTime('www.gamingonlinux.com', 0)` in your Badger's background page to clear the cache and force rechecking with the next visit though.

**Comment by LiamDawe** [comment]
No probs.

I really appreciate you taking time to talk me through this. We're a Linux-based site so privacy is extremely important to us anyway :+1:

**Comment by ghostwords** [comment]
Resolving. Let me know if there is anything else.
