### ISSUE TITLE
coub.com clips are blocked

### ISSUE THREAD

**Issue by NovemberZulu** [EFForg/privacybadger#2004]
Privacy Badger debugging info: 
```
**** ACTION_MAP for coub 
coub.com {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1525832241592
} 
**** SNITCH_MAP for coub 
coub.com [
  "worldoftanks.ru",
  "habrahabr.ru",
  "vc.ru"
]
```
[Coub Privacy Policy](https://coub.com/privacy) seems to be complicated, and does not mention Do Not Track Policy.

This is HTML from where I noticed page breakage. 
```html
<div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.494%;">
    <iframe src="//coub.com/embed/17frlq?maxheight=361&amp;maxwidth=640" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;" allowfullscreen="" scrolling="no">
    </iframe>
</div>
```

Probably some Click-to-Play solution is required.

**Comment by ghostwords** [comment]
Yep, or we could just yellowlist the domain for now anyway.

Do you have any example pages that have these embeds? Seeing them on a few different sites would be great.

**Comment by NovemberZulu** [comment]
I am afraid I remember only the page where I noticed something was missing: https://geektimes.com/post/300631/ (in Russian, the clip somewhere in the middle of the page, search for "self-steering" to find it quickly).  HTML in my first post is taken from there.

I wonder why `geektimes.com` wasn't mention in the snitch map, though...

**Comment by bcyphers** [comment]
@NovemberZulu just for future reference, the snitch map only stores the first three sites where it sees a domain tracking, so you won't see all the sites where it appeared.
