### ISSUE TITLE
Ability to disable on a single machine would be helpful

### ISSUE THREAD

**Issue by gstar42** [EFForg/privacybadger#2008]
I use Privacy Badger in Chrome. It works on my home PC as well as the one at work. It would be nice if I could have it only work at home. I use the same account so perhaps a registry setting or some other way to prevent it from running on *this* PC.

**Comment by ghostwords** [comment]
Hello! I am not sure I understand your problem. Is this related to Chrome profiles being automatically synced?

**Comment by gstar42** [comment]
Yes, I guess so. Is there a way to sync selectively? In general syncing is a great idea but I don't want Privacy Badger enabled on my work PC.


________________________________

**Comment by ghostwords** [comment]
I don't think this is something Privacy Badger (or any other Chrome extension) can do something about. You could [disable syncing for all extensions](https://superuser.com/questions/528014/how-to-disable-chrome-extensions-without-disabling-them-across-multiple-synced-d/531510#531510) though. Doesn't look like there is a way to disable syncing for just one extension though; that's something you'll have to ask Chrome to fix.
