### ISSUE TITLE
iframes missing even when privacy badger is disabled

### ISSUE THREAD

**Issue by bryanlarsen** [EFForg/privacybadger#201]
http://jsfiddle.net/bhouston/RGQ8X/

Doesn't display the iframe.  Not completely surprising, but what is surprising is that the iframe doesn't display even with privacy badger disabled.

**Comment by StewAlexanderACC** [comment]
I can confirm that embedded html code with <iframe> and <script> type tags do not render when Privacy Badger is enabled
