### ISSUE TITLE
Overblocking of Contextly.com

### ISSUE THREAD

**Issue by rsingel** [EFForg/privacybadger#2011]
We provide content recommendations for publishers as a third-party working as a first-party. E.g. we set third party cookies but these are unique for every domain we work on. 

See the recommendations at the bottom of this article.
http://ww2.kqed.org/news/2015/01/13/trial-opens-for-alleged-silk-road-mastermind

Beyond that, we allow users to block our cookies and still get recommendations. So instead of blocking *.contextly.com, PB could simply block experience.contextly.com, still allowing readers to get to rest.contextly and assets.contextly, which are cookie-less domains.

**Comment by ghostwords** [comment]
Hello! I see the `contextly.com` domains but my Privacy Badger doesn't see any tracking from them. Is there something I need to do to get cookied?

I'm also not sure where on the page I should see the recommendations. I just get an infinite scroll of articles. Perhaps you could post a screenshot.

Do you have access to a browser with the Privacy Badger that learned to block `contextly.com`? Could you then run the following debugging code in that Badger's background page console?


```javascript
(function () {
  const STR = "contextly";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is enabled, click on the "background page" link in Privacy Badger's cell,  and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by ghostwords** [comment]
I'm going to close this for now. Let me know if you have more information.

**Comment by rsingel** [comment]
Hey Ghostwords,

I dropped the ball on this. In particular, rest.contextly.com is cookie-less and non-tracking but is blocked.

You can see it happen here:
https://citinewsroom.com/2019/05/16/concerned-mothers-chide-cid-boss-over-comments-on-kidnapped-girls/

**Comment by ghostwords** [comment]
Could you provide the debug output as per my reply above for "contextly"?
