### ISSUE TITLE
facebook link click tracking does not block `facebookcorewwwi.onion` click tracking

### ISSUE THREAD

**Issue by hairetikos** [EFForg/privacybadger#2012]
https://github.com/EFForg/privacybadger/blob/master/src/js/firstparties/facebook.js#L3
we need one for *.facebookcorewwwi.onion/l.php?
it is the official facebook tor/onion hidden service

for wider implementation in privacy badger functionality, the main onion domains & subdomains seem to be:

facebookcorewwwi.onion
fbcdn23dssr3jqnq.onion (the CDN equivalent)
m.facebookcorewwwi.onion (mobile)
l.facebookcorewwwi.onion (link)
lm.facebookcorewwwi.onion (link mobile)
www.facebookcorewwwi.onion

(see https://github.com/mozilla/contain-facebook/pull/147/commits/54bd0a67873f996b2aabfdaa9260efed13d9df8f)

**Comment by ghostwords** [comment]
cc @mgziminsky

**Comment by mgziminsky** [comment]
Thanks for the ping. I've opened a similar issue with my addon.

**Comment by hairetikos** [comment]
thanks for the quick response!

i made a quick fix in #2014, seems to work for me, though there may be a better way of implementing it
