### ISSUE TITLE
Breaks Feeder, Feedly, and other Web-based readers that use frames

### ISSUE THREAD

**Issue by ldexterldesign** [EFForg/privacybadger#2015]
Hey all,

Hope you're well

Thanks for software

![foo mov](https://user-images.githubusercontent.com/1715809/39941577-4bc557d2-555d-11e8-9e05-3075f768699e.gif)

Is there a legitimate reason for blocking http://cnet.com in this senario?:

If yes, what is it

If no, can we get this fixed

Let me know if you have any issues - happy to help

Hope this is clear/useful and to hear back

Yours faithfully

**Comment by ghostwords** [comment]
Hello!

I think what's happening is that Privacy Badger is confused by entire sites framed by some other site (in this case, Feeder). This is a bug: Privacy Badger doesn't realize the framed domain (`cnet.com`) is a first (and not third) party.

Sorry for not replying earlier!

**Comment by ldexterldesign** [comment]
NO REPLY NECESSARY

Thanks for reply

Good luck with the bug fix!

Let me know if you have any issues - happy to help

Regards

**Comment by ghostwords** [comment]
This [Reddit question where Privacy Badger broke parts of YouTube (by blocking `gstatic.com`) when browsed through Feedly](https://www.reddit.com/r/privacy/comments/8zv0q7/privacy_badgerfeedlyyoutube_help_which_google/) seems like the same issue. Privacy Badger [already knows `youtube.com` and `gstatic.com` belong to the same entity](https://github.com/EFForg/privacybadger/blob/4220585e9add6cfc167539887c2d4105d3c5e010/src/js/multiDomainFirstParties.js#L211-L221), but this information is only applied when `youtube.com` is the top-level site, not when `youtube.com` is a frame on some other site (`feedly.com`).

**Comment by mijiturka** [comment]
I'd like to work on this issue but haven't been able to reproduce it.  @ldexterldesign - could you let me know if you're still seeing the issue?


Cnet blank page when PB is enabled:

Cnet now seems to block feeder.co's Full view entirely with its Content Security Policy, so even with PB disabled, Firefox comes up with a "Blocked by Content Security Policy" page, and Chromium with an empty page.

![feeder-firefox-nopb](https://user-images.githubusercontent.com/1078993/47290772-f5f6d480-d5f8-11e8-9de8-66e439da5ca9.png)
![feeder-chromium-nopb](https://user-images.githubusercontent.com/1078993/47290739-cb0c8080-d5f8-11e8-8232-9339e4f61ca2.png)

On other random feeds feeder subscribed me to, I'm seeing a blank page, on both Firefox and Chromium, with PB disabled: http://www.theverge.com/rss/index.xml and https://www.reddit.com/r/technology/.rss - I wonder if feeder is just broken with newer browsers?

I can't find a way to open anything but a Cnet page preview (title + picture + second title) on Feedly.com. I can't see a difference between the previews with PB enabled vs disabled.

![feedly-cnet-with-pb](https://user-images.githubusercontent.com/1078993/47290785-07d87780-d5f9-11e8-921f-69242bd74ab8.png)


RSS feed I used: 
https://www.cnet.com/rss/news/


Embedded youtube video's "Watch Later" not working when browsed through frame (Feed.ly or Feeder.com):

I couldn't reproduce this issue on Firefox or Chromium.
The "Watch Later" button appears fine, and clicking it opens a popup to get me to sign into a Google account.

![yte-feeder-pb](https://user-images.githubusercontent.com/1078993/47290831-2c345400-d5f9-11e8-9060-8c460b6e4193.png)


RSS feed I used:
https://youtubevideoembed.com/feed/ in feeder.co and feed.ly
Article that has embedded video:
https://youtubevideoembed.com/guns-n-roses-biggest-80s-band-according-to-youtube/

PB doesn't block fonts.gstatic.com, but the "Watch Later" button works even if I manually tell PB to block it.


latest PB version on master (2018.10.3.1 / 44eba77)
Linux
Firefox Dev Edition 64.0
Firefox 62.0.3
Chromium 69.0.3497.81
(is it worth testing separately on Chrome?)

**Comment by ldexterldesign** [comment]
Hi @mijiturka,

Hope you're well

Thanks for looking into this

> Cnet now seems to block feeder.co's Full view entirely with its Content Security Policy, so even with PB disabled, Firefox comes up with a "Blocked by Content Security Policy" page, and Chromium with an empty page.

> I can't find a way to open anything but a Cnet page preview (title + picture + second title) on Feedly.com. I can't see a difference between the previews with PB enabled vs disabled.

Please try retesting with feeder[r] extension installed

I don't know why, with some websites (inc. cnet), but I can see the full view with the extension

Hopefully then you can create the PB fix

If you have any issues (e.g. questions/queries) happy to help

Hope this is clear/useful and to hear back

Regards

[r] https://chrome.google.com/webstore/detail/rss-feed-reader/pnjaodmkngahhkoihejjehlcdlnohgmp

**Comment by mijiturka** [comment]
Thanks - this did help. The Feeder plugin intercepts the response and strips the Content Security Policy from it.

Feeder uses a custom <x-iframe> element made with Web Components.
Which I think dynamically generates an <iframe> (because Developer Tools sees it), but in the source code it's just this:
```
<template id="screen#popup-consume" class="screen-with-topbar">
  ...
  <x-iframe
  sandbox="allow-forms allow-pointer-lock allow-popups allow-same-origin allow-scripts"
  allowfullscreen="true"
  webkitallowfullscreen="true"
  mozallowfullscreen="true"></x-iframe>
</template>
```

From my testing it looks like Privacy Badger does recognise websites with the same URL as coming from the same origin when they're inside the standard <frame> or <iframe> element.

I am probably out of my depth here, I'll look into it some more but would appreciate a nudge in the right direction from someone who knows more about dynamically generated elements and PB.

**Comment by ghostwords** [comment]
>Or do we want to add exceptions for a list of sites like these?

Yeah, probably ... Not entirely clear. Something like, when checking whether a domain is third-party, see if it's coming from inside a frame on one of these sites (Feedly, etc.), and if it is, consider the frame to be the top level document for the request? Seems messy ...

**Comment by ldexterldesign** [comment]
Unable to emulate my original problem now

Unsure about other use cases but with Feeder you must have the browser extension installed to enable full view with some feeds

Privacy Badger (PB) doesn't appear to affect this

NB I did "Remove/Reset[r] (all PB) tracking domains" in the extension options

Based on this I'm closing this issue but if you object then feel free to reopen

Hope this helps

Regards

r: chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/skin/options.html#tab-manage-data
