### ISSUE TITLE
Exception on Facebook domain (also when disabled for site)

### ISSUE THREAD

**Issue by arieljannai** [EFForg/privacybadger#2018]
This happens also if PrivacyBadger is disabled for the Facebook domain, and if it's the only enabled extension.

Exception at [`facebook.js:60`](https://github.com/EFForg/privacybadger/blob/d80bcebcefba28fc481b0203574b6696bf845f46/src/js/firstparties/facebook.js#L60)

    Uncaught TypeError: node.querySelectorAll is not a function
        at cleanMutation (facebook.js:60)
        at Array.forEach (<anonymous>)
        at MutationObserver.observe.childList (facebook.js:77)

Browser details: Chrome 66.0.3359.139

**Comment by ghostwords** [comment]
Hello! Do you need to be doing anything in particular to get this error? Does this break anything as far as you can tell?

**Comment by arieljannai** [comment]
Hi! The only thing I noticed it broke (and this is how I found it) was when I started using [this user script](https://github.com/tmiland/Play-YouTube-on-Facebook) to bring back embedded YouTube videos to Facebook.

I can try some things to test it if you have any testing ideas :)

**Comment by ghostwords** [comment]
I can reproduce the error w/o any other extensions. Looks like we should add some sort of check, maybe [`node.nodeType == Node.ELEMENT_NODE`](https://github.com/mgziminsky/FacebookTrackingRemoval/blob/587a540e6538b62eaeeac5ec4a34c57e8bad5166/src/app.js#L254) (I guess [text nodes](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType#Node_type_constants) don't come with `querySelectorAll`?).

**Comment by bcyphers** [comment]
This is an easy fix, but in general, do we want first-party scripts to run if PB is disabled?

**Comment by ghostwords** [comment]
Probably not, but I think OK to leave that alone for now.
