### ISSUE TITLE
Prevent longitudinal data collection

### ISSUE THREAD

**Issue by mhorowitz** [EFForg/privacybadger#2023]
This idea is a hybrid of several others, but I thought I'd throw it out there in case it interests someone.  I do recognize that it not simple, but I think it would add a lot of value.

One kind of data collection which is possible, and I expect first-party cookie sites do, is collect information about visitors over time.  For example, a news site might keep a log of all articles read by a given client, based on a persistent cookie returning over and over again, even if there's no account or login.  If at any time this record can ever be correlated with a real person, the whole history is now attributed.

On the other hand, if I have an account on a site, blocking cookies isn't going to help me much with privacy.  If I log into an account to access a news site or an online store, even if I aggressively block cookies (and the site still works...), the site can still use my account to collect data longitudinally.

So here's what I have in mind:
* Make most cookies session cookies to start with.
* Keep track of tabs which store first party cookies.  When the last tab for a cookie is closed, remove the cookies.  Outright blocking is problematic, as many sites will break if there are no cookies, but they don't need them any longer than the tabs are open.  For people like me who may leave a browser open for weeks, this prevents session cookies from being used for longitudinal tracking, too.
* If a site receives a password, then mark that site as being allowed to store persistent cookies, since people like being able to stay logged in, and there is little additional privacy benefit to deleting them.  This will probably require some heuristics similar to those used by password managers.  One likely heuristic is if the site has a <input type="password"> field in a form, and that form is ever submitted, then it should be marked.
* There should be a whitelisting option to mark sites for which the heuristics don't work right.  Maybe this can share the same whitelist which already exists.

I see two main benefits:
* This significantly limits the lifetime of cookies which may harm the user, while still allowing cookies which are more likely to benefit them, or at least aren't likely to create additional privacy risk.
* Since basically every site on the Internet saves cookies, the cookie database becomes a record of every site ever visited.  This can be a privacy concern in itself.  But people authenticate to only a small fraction of the sites they may visit; the above heuristics would automatically remove most of these sites from the cookie database.

Thanks!

**Comment by ghostwords** [comment]
Hello! Is [Cookie AutoDelete](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete) close to what you are looking for?

I think while it does make sense to eventually do something about first-party tracking (whether via cookies or other techniques), there is still so much Privacy Badger can do to better to protect against pervasive non-consensual third-party tracking.

Although, we have started offering certain first-party protections (removing outgoing link tracking on [Twitter](https://www.eff.org/deeplinks/2017/08/privacy-badger-makes-twitter-little-less-creepy) and [Facebook](https://www.eff.org/deeplinks/2018/05/privacy-badger-rolls-out-new-ways-fight-facebook-tracking)), when the first party in question is large enough to be worth spending time on. It's a question of prioritization.

Do you have any specific scenarios in mind where Privacy Badger falls short now?

**Comment by mhorowitz** [comment]
Cookie AutoDelete looks like the right idea, I'll look at it more closely.  Thanks!

Although it would be nice if PB was a one-install plugin for privacy, I do understand the need to prioritize.

I don't have any specific scenarios where PB falls short in third-party tracking case.  My concerns in this case are about first-party tracking.

**Comment by ghostwords** [comment]
Closing as first-party cookie management is too removed from Privacy Badger's areas of focus at this time.
