### ISSUE TITLE
Arcgisonline.com to be added to yellowlist

### ISSUE THREAD

**Issue by stephaniewilkinson** [EFForg/privacybadger#2034]
We're building an app that uses arcgis data. Privacy badger is blocking `arcgisonline.com` so it breaks our app. 

We see that `arcgis.com` is on the yellowlist (#341). Is there a way that `arcgisonline.com` could be added to the yellowlist as well?

[ArcGIS' privacy policy is here.](https://doc.arcgis.com/en/trust/privacy/privacy-tab-intro.htm)

**Comment by ghostwords** [comment]
Hello! My Privacy Badger doesn't see tracking from `arcgisonline.com`, at least for the examples I looked at (below). Is this a case of first-party login cookies being sent for third-party widget resources?

- http://app01.cityofboston.gov/VZSafety/
- https://generalmap.gis.saccounty.net/JSViewer/county_portal.html
- https://minneapolis2040.com/topics/land-use-built-form/

**Comment by ghostwords** [comment]
Could you run the following script in your Badger's background page console and share what it prints out?
```javascript
(function () {
  const STR = "arcgisonline";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by stephaniewilkinson** [comment]
thanks so much for the quick response @ghostwords. super helpful.

arcgisonline is no longer showing up in the list of domains. I think ArcGIS maybe has swapped things out on their side, the only domains listed now are arcgis.com domains.

That means I can't run these debugging steps you mention. I'll close the issue for now, and if arcgisonline.com enters the mix I'll reopen it and try the suggestions you mention.

Thanks so much for your help!

**Comment by ghostwords** [comment]
I do see other users running into problems caused by `arcgisonline.com` automatically getting blocked in our error report database.

You can run the debugging code above in the browser where Badger learned to block the domain(s) regardless of whether the website changed. It'll help us figure out where your Privacy Badger saw tracking from "arcgisonline" domains.

Do you see any cookies or HTML5 local storage set for `arcgisonline.com` in that browser?

**Comment by stephaniewilkinson** [comment]
I ran the code you included above in my browser console and get a JS error:

Input: 

```
(function () {
  const STR = "arcgisonline";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

Output:

```
VM247:4 Uncaught ReferenceError: _ is not defined
    at <anonymous>:4:3
    at <anonymous>:11:2
```

To your second question, the only cookies I have left are from arcgis.com. So if there was an arcgisonline.com cookie, it's gone by now.

**Comment by ghostwords** [comment]
Oh, sorry, you have to run the code in Privacy Badger's background page console.

To get to the background page console in Chrome, visit chrome://extensions, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit about:debugging, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by stephaniewilkinson** [comment]
Thanks for being patient with me! I realize you had mentioned that above and I glossed over it, sorry.

Here's the output:

```
**** ACTION_MAP for arcgisonline
VM687:5 arcgisonline.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
VM687:5 server.arcgisonline.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1527597306749,
  "userAction": ""
}
VM687:5 serverapi.arcgisonline.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1524942960594,
  "userAction": ""
}
VM687:5 utility.arcgisonline.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1522973248695,
  "userAction": ""
}
VM687:5 services.arcgisonline.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1527608216705
}
VM687:7 **** SNITCH_MAP for arcgisonline
VM687:9 arcgisonline.com [
  "esri.com",
  "blm.gov",
  "arcgis.com"
]
```
