### ISSUE TITLE
#Enhancement Fix http://streamable.com block #Mastodon #Twitter

### ISSUE THREAD

**Issue by ldexterldesign** [EFForg/privacybadger#2035]
NO REPLY NECESSARY

Hi,

Hope you're well

Thanks for software

As title[e]

Screen shot(s)/cast:

![untitled mov](https://user-images.githubusercontent.com/1715809/40511700-da4a39d0-5fa0-11e8-85a3-78b3f9b6ef76.gif)

If you're reading this and agree please up-vote and/or reply +1

Let me know if you have any issues - happy to help

Hope this is clear/useful

Regards

[e]
https://mastodon.social/@ldexterldesign/100081933061587215
https://twitter.com/ldexterldesign/status/999478934688489472

**Comment by bcyphers** [comment]
I was able to confirm this, accidentally. The streamable widget sets a lot of cookies. Might be a candidate for the yellowlist.

**Comment by ghostwords** [comment]
I was thinking this is a good candidate (video player, not too popular) for expanding widget replacement (#1467) to handle non-social button widgets.

**Comment by ghostwords** [comment]
I can't replicate the original problem at https://mastodon.social/@ldexterldesign/100081933061587215 with or without Privacy Badger as the video always opens in a new window upon click.

**Comment by ldexterldesign** [comment]
NO REPLY NECESSARY

Hi @ghostwords,

Apologies for delay

This does appear to be resolved

Keep up great work!

Regards
