### ISSUE TITLE
use.fontawesome.com blocked

### ISSUE THREAD

**Issue by conradj** [EFForg/privacybadger#2037]
Closed in [#1601](https://github.com/EFForg/privacybadger/issues/1601) but seems to have come back. See https://bulma.io/documentation/elements/icon/ for example.

I'm using Firefox on MacOS.

**Comment by ghostwords** [comment]
Hello! Could you run the following script in your Badger's background page console and share what it prints out?
```javascript
(function () {
  const STR = "fontawesome";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by conradj** [comment]
```
**** ACTION_MAP for fontawesome 
use.fontawesome.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1527840789124
} 
fontawesome.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1520253708356
} 
**** SNITCH_MAP for fontawesome 
fontawesome.com [
  "localhost",
  "conradj.co.uk",
  "fontpair.co"
]
```

**Comment by ghostwords** [comment]
I *still* can't reproduce tracking. Do you have any cookies or HTML5 local storage in your browser for `fontawesome.com`?

@bcyphers I see that our 10K site crawl also learned to block `fontawesome.com`: https://raw.githubusercontent.com/EFForg/badger-sett/9bed7a1449fbfa56ae8be245270f11ae356fda6a/results.json. Any ideas as to what's going on?

**Comment by ghostwords** [comment]
Ah! I can reproduce if I visit `fontawesome.com` directly first. This sets the Google Analytics cookie, which is then sent with requests to `fontawesome.com` on other people's websites, which Privacy Badger flags as tracking.
