### ISSUE TITLE
Add option to disable sending the Do Not Track (DNT) signal

### ISSUE THREAD

**Issue by ylluminarious** [EFForg/privacybadger#2038]
No website is obligated to comply with DNT headers, and they may even choose to profile users which have the DNT header in their requests. There's not much information they could glean from this alone, but surely the majority of users on the web don't have DNT headers in all requests so it certainly has the potential to set apart those users who do. I don't see any option to disable the sending of this header in Privacy Badger. How can I? Is it even possible?

**Comment by ghostwords** [comment]
Privacy Badger is a non-consensual tracking blocker. Step one is to clearly express the user's preference not to be tracked; step two is to enforce it. Sites are free to ignore this signal, and Privacy Badger is then free to block them. As Privacy Badger gains users, Do Not Track gains weight.

We don't have a setting to disable sending the DNT signal at this time. I agree with your observations. Perhaps we should have a setting for this, but I am not sure it's a good idea (since DNT is such a big part of Privacy Badger's mission).

**Comment by ylluminarious** [comment]
@ghostwords Thanks for the response. I understand that DNT is part of Privacy Badger's modus operandi and I appreciate that. I also understand that DNT would be a lot less fingerprint-able if more people used it. That would certainly be the ideal scenario, but sadly I don't think we're there yet. I think it would be a good idea for DNT to be optional, but enabled by default. You don't even need to advertise the existence of the option, but having it there would be nice. I doubt most users would turn it off anyway, so it would mostly be there for folks who have the same worries as myself (which is probably not many).

I'd be happy to help in even implementing the code for this, although I'm not sure about PB's licensing situation and haven't looked closely. I have lots of experience with JavaScript and many other languages so I'm sure that I wouldn't need an awful lot of help.

**Comment by ghostwords** [comment]
This is related to #474.

**Comment by ghostwords** [comment]
How would this setting interact with the existing "Check if sites comply with EFF's Do Not Track policy" setting? I mean, does it make sense to check for DNT compliance if you don't send the DNT signal? I am not sure.

**Comment by ylluminarious** [comment]
@ghostwords I'd say this option should automatically disable that option. You're right; it doesn't make sense to check for DNT compliance if you're not sending DNT to begin with. The compliance check would be automatically re-enabled if they turn the DNT signal back on. What I'm not sure about is whether the user should be allowed to manually re-enable the compliance check even while DNT-sending is off.

**Comment by ylluminarious** [comment]
@ghostwords @miketung Thanks a lot for fixing this issue! Sorry I couldn't help out with it; I haven't had much time to.
