### ISSUE TITLE
Broken Images in Google Docs

### ISSUE THREAD

**Issue by qkrengel** [EFForg/privacybadger#2041]
When I choose insert->Image->Upload from computer Privacy Badger causes the image to be displayed as a black triangle with an exclamation point.  Verified by disabling Privacy Badger (images appear) and re-enabling (images fail).  note that with Privacy Badger enabled on Chrome images uploaded vi Safari do not display either.
![gcss](https://user-images.githubusercontent.com/903243/40629131-016eb964-628f-11e8-9bf6-aa7789e3c2f9.gif)

This is happening on Chrome Version 66.0.3359.181 (Official Build) (64-bit) running on macOS 10.13.4

**Comment by ghostwords** [comment]
Hello! I think this is the same issue as #1889. I suggest disabling Privacy Badger on Google Docs until we get this fixed.

**Comment by ghostwords** [comment]
By the way, does Privacy Badger report blocking a blank domain on affected Google Docs pages?

**Comment by ghostwords** [comment]
Could you run the following script in that Badger's background page console and share what it prints out?
```javascript
(function () {
  console.log("**** ACTION_MAP for ''");
  console.log(JSON.stringify(badger.storage.getBadgerStorageObject('action_map')._store[""], null, 2))
  console.log("**** SNITCH_MAP for ''");
  console.log(JSON.stringify(badger.storage.getBadgerStorageObject('snitch_map')._store[""], null, 2))
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.
