### ISSUE TITLE
Reduce confusion around Whitelisted Domains

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#2045]
It seems that users sometimes mistake Whitelisted Domains for the place they need to enter domains they want Privacy Badger to allow to load. It may be that removing explanation of sliders from the new user intro page as well as moving the Tracking Domains tab out of the way (it used to be the default tab) contributes to this confusion.

We should be able to help by amending the description over the whitelisted domains form. I don't think it's clear the form is about turning Privacy Badger off entirely on sites you visit, not about allowing third-party domains to load. 

For example, see #2044, also this recent AMO review:
>Хорошее расширение, но почему-то не работает белый список. Вводишь в белый список домен radikal.ru, а изображения на других сайтах всё равно блокируются.

**Comment by ghostwords** [comment]
@bcyphers @andresbase How about the following replacement? Do you think it will help avoid the confusion we see in the above linked issue and AMO review?

Current intro:
>Privacy Badger is disabled for the domains listed below. You can add a domain either via the Privacy Badger icon in the browser toolbar, or by typing the domain in the box below and clicking the "Add domain" button.

Proposed replacement:
>Privacy Badger is disabled on the following sites. If you think Privacy Badger is breaking a page (a video doesn't play, for example), you can type that page's domain in the box below and click the "Add domain" button.
>
>If you are already on the page, you can just click on Privacy Badger's button in the browser toolbar and then click the "Disable" button inside Privacy Badger's popup.

<details><summary>Screenshot:</summary>

![screenshot from 2018-06-27 10 55 24](https://user-images.githubusercontent.com/794578/41982150-b0b4f854-79f8-11e8-8020-0f999d7fc349.png)
</details>
<br>

Not sure we need that second paragraph.

**Comment by ghostwords** [comment]
Should we also rename the "Whitelisted Domains" tab to "Whitelisted Sites"?

**Comment by ghostwords** [comment]
Previously: https://github.com/EFForg/privacybadger/pull/1669#issuecomment-329522602.

**Comment by andresbase** [comment]
I like the proposed text. I would keep the second paragraph in case people didn't know they could just do that. It seems to me that the flow should usually be disabling PB on that site by clicking the button rather than manually adding it.

How about "Whitelisted Domains" -> "Disabled Sites"
