### ISSUE TITLE
Ability to disable widget replacement for some widgets

### ISSUE THREAD

**Issue by theel0ja** [EFForg/privacybadger#2049]
Ability to block some icons completely (for example, someone would not want to see Facebook like buttons if he doesn't use Facebook) and show some icons as Privacy Badger ones.

**Comment by ghostwords** [comment]
Hello! I am not sure I understand your request. The way widget replacement should work is that it kicks in when relevant tracking domains get blocked. So if you don't use a service, great! Just ignore the replacement buttons. Are you asking for a way to hide buttons you are not interested in?

**Comment by theel0ja** [comment]
I mean that some of buttons could be hidden in the settings

**Comment by JacobHearst** [comment]
I'd like to work on this, I was thinking that these options should go under the existing "Replace social buttons" checkbox, but I wasn't sure what the best way to allow toggling of individual blocked elements would be. HTML's built in `select` has an option that allows selection of multiple values, but it requires you to ctrl+click or shift+click to select more than one option, and if an item is pre-selected it will become deselected when another option is selected (unless ctrl+click is used). Another option could be to just create a group of checkboxes with one checkbox for each social widget although I'm not sure how nice that would look. Does anybody else have some input on how this setting could look/work?
