### ISSUE TITLE
Issues when used with ublock

### ISSUE THREAD

**Issue by LiamDawe** [EFForg/privacybadger#2052]
I don't know why, but lately privacy badger in Chrome has been complaining of issues.

When loading the extensions page, all it tells me is this: https://pastebin.com/1ZNRHfBD

It's quite long, so using pastebin

**Comment by ghostwords** [comment]
This particular conflict will be fixed (by efdd168328acb7dbccfcddba5868c89cbc821c08) with the next Privacy Badger update. Note there is no actual bug in this case, just Chrome needlessly alarming its users.
