### ISSUE TITLE
Manifest: Error processing update_url

### ISSUE THREAD

**Issue by jaller94** [EFForg/privacybadger#2054]
Browser: Firefox Nightly 62
Extension: 2018.5.10

On the page `about:debugging#addons` I get the following error:
![Privacy Badger — Reading manifest: Error processing update_url: An unexpected property was found in the WebExtension manifest.](https://user-images.githubusercontent.com/10872136/41135562-0a179ab8-6a87-11e8-804c-c36d629c130d.png)

Where does `update_url` come from? It’s not documented on [MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_compatibility_for_manifest.json).

Why does it point to a Google URL? For a privacy-focused extension this seems suspicious.
https://github.com/EFForg/privacybadger/blob/7aa109e224a42c180b65aaffe2e351013a6cfd38/src/manifest.json#L117

**Comment by ghostwords** [comment]
This is because we use the same manifest for Chrome and Firefox. There is no actual problem, just a visual nit. Firefox could just ignore Chrome-specific fields.

**Comment by ghostwords** [comment]
See 0851983f57837ea97126f9678641107194e2ae2e and https://crbug.com/805755 for the gory details of why we need "update_url" in the manifest.
