### ISSUE TITLE
Breaks images in Google Slides

### ISSUE THREAD

**Issue by Chekote** [EFForg/privacybadger#2055]
When using Privacy Badger with Google Slides, the following problems occur:

1. Attempting to upload any image results in the image displayed as a white box with a black triangle warning symbol.
2. Attempting to open a powerpoint file in Google Slides results in all of the images being missing.

**Comment by ghostwords** [comment]
Hello! I think this is a duplicate of #1889. Does Privacy Badger report blocking a blank domain on Google Slides?

**Comment by Chekote** [comment]
Yes, that’s exactly it. Thanks!

**Comment by ghostwords** [comment]
Could you run the following script in that Badger's background page console and share what it prints out?
```javascript
(function () {
  console.log("**** ACTION_MAP for ''");
  console.log(JSON.stringify(badger.storage.getBadgerStorageObject('action_map')._store[""], null, 2))
  console.log("**** SNITCH_MAP for ''");
  console.log(JSON.stringify(badger.storage.getBadgerStorageObject('snitch_map')._store[""], null, 2))
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.
