### ISSUE TITLE
please add destinyitemmanager.com to yellowlist

### ISSUE THREAD

**Issue by jakibbe** [EFForg/privacybadger#2056]
This site is an inventory manager for a popular video game, Destiny 2. Users need to be able to login to this site through the game developers site (bungie.net). Site users often think that destinyitemmanager.com is broken since Privacy Badger blocks access. Please consider adding destinyitemmanager.com to your yellowlist.  Thanks!

**Comment by ghostwords** [comment]
One more:
```javascript
(function () {
  const STR = "bungie.net";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

**Comment by SunburnedGoose** [comment]
I'm swinging by from @ThisIsDIM on Twitter.  Our users can report that PrivacyBadger is blocking downloads of 3rd party content from Google, and Bungie.net.  Here's an example:

https://twitter.com/RickCasey/status/1001678558136291329
https://twitter.com/RickCasey/status/987508501856518144

I tried it myself today and it didn't block on the first load.  I'll keep using the extension and see if it triggers and blocks Bungie.net and Google for me.

**Comment by bcyphers** [comment]
I visited DIM, and PB does identify bungie.net as a potential tracker. I haven't visited any other domains that include Bungie as a third party, so it's not blocked for me. This may be a case of https://github.com/EFForg/privacybadger/issues/1545.

Can you check if dragging the "bungie.net" slider to cookieblock (yellow) fixes the issue?

**Comment by ghostwords** [comment]
I'm guessing this is a [`bungie.net` OAuth](https://github.com/Bungie-net/api/wiki/OAuth-Documentation) issue and as such falls under #137.

If Bungie doesn't actually track users on their authentication service domains, Bungie can fix this on their end by posting [EFF's Do Not Track policy](https://www.eff.org/dnt-policy) on each authentication domain. This will tell Privacy Badger to always allow loading of resources from those domains.

**Comment by ghostwords** [comment]
@jakibbe Does moving the slider for all `bungie.net` domains to "yellow" resolve the issue?

**Comment by ghostwords** [comment]
Error report counts by page domain and exact blocked `bungie.net` subdomain:
+-----------------------------+----------------+-------+
| fqdn                        | blocked_fqdn   | count |
+-----------------------------+----------------+-------+
| app.destinyitemmanager.com  | www.bungie.net |    13 |
| db.destinytracker.com       | www.bungie.net |     5 |
| destinysets.com             | www.bungie.net |     3 |
| beta.destinyitemmanager.com | www.bungie.net |     2 |
| destinytracker.com          | www.bungie.net |     2 |
| destinysets.com             | bungie.net     |     1 |
| destinytracker.com          | bungie.net     |     1 |
| www.destinylfg.net          | www.bungie.net |     1 |
| www.destinythegame.com      | www.bungie.net |     1 |
+-----------------------------+----------------+-------+

**Comment by dcaslin** [comment]
Just got a user report today that https://www.d2checklist.com/ is having calls back to the Bungie.net API blocked (first block is a legit ad/tracking block; second block is the API call that shouldn't be blocked) 
![image](https://user-images.githubusercontent.com/16437968/48382046-305e0980-e6ad-11e8-870b-7e58e5962314.png)

**Comment by ghostwords** [comment]
@dcaslin Does moving the slider for all `bungie.net` domains to "yellow" and reloading the site resolve the issue?

**Comment by dcaslin** [comment]
Unfortunately I wasn't able to reproduce the problem myself.

I was about to add in some logic to my code that detects status code zero and says "Do you perhaps have Privacy Badger installed?" but figured I'd check with you all first to see if  you could just whitelist bungie.net globally since it's been a recurring issue with 3rd party Bungie sites.

**Comment by ghostwords** [comment]
How to get `bungie.net` blocked:
- Visit https://www.d2checklist.com/ (this sets two cookies)
- Visit https://destinysets.com/
- Visit http://www.destinylfg.net/

Two `bungie.net` domains should now be set to "red" (blocked) under the Tracking Domains tab of Privacy Badger's options. Does sliding `bungie.net` to "yellow" and reloading your site fix the problem?

**Comment by ghostwords** [comment]
We can put `bungie.net` on our ["yellowlist"](https://github.com/EFForg/privacybadger/blob/master/doc/fixing-broken-sites.md#external-domains-too-complex-to-surrogate-or-replace-with-placeholders), which will instruct all Badgers to set `bungie.net` domains to "yellow", which means allow content to load but block cookies. I'll do this tomorrow morning.

**Comment by ghostwords** [comment]
Yellowlisting will not fix authenticating through `bungie.net` though (https://github.com/EFForg/privacybadger/issues/2056#issuecomment-422868561), if that's another issue our users run into. The issue for fixing authentication flows is #137.

**Comment by ghostwords** [comment]
I just added "bungie.net" to Privacy Badger's yellowlist.

You should see this update get applied to your Badger within the next day. You can also get it right away by restarting your browser.
