### ISSUE TITLE
Privacy Badger causes Corrupted Content Error when following links

### ISSUE THREAD

**Issue by skorokithakis** [EFForg/privacybadger#2062]
Following a link from [this search](https://duckduckgo.com/?q=site%3Awww.netlify.com&t=ffab&ia=web) to Netlify causes a corrupted content error on Firefox (any recent version) on Linux. Firefox doesn't even attempt to go to the network, which tells me that PB is blocking that site from being visited. Pasting the URL in a new tab works fine. Disabling PB also makes this work fine.

I have had this problem with [my own site](https://duckduckgo.com/?q=site%3Awww.stavros.io&t=canonical&ia=web) as well, which is not blocked in PB at all, so it's not blocking-related.

**Comment by ghostwords** [comment]
Could you post some screenshots of what this looks like, and of what Privacy Badger reports as blocked?

Are you able to reproduce this in a new Firefox profile? Are you able to reproduce this in a new Firefox profile after exporting and importing Privacy Badger data from your old profile? You can export/import Badger data on Privacy Badger's options page.

**Comment by skorokithakis** [comment]
Yes, I can reproduce this with a new profile and PB install. I didn't export/import the data because it was reproduced anyway.

I went on the Netlify site and clicked around a bit, as well as followed the links of the DDG search above, and this is the result:

![problem loading page](https://user-images.githubusercontent.com/23648/41300142-b5173510-6e6d-11e8-8291-452a5f030be5.png)

**Comment by ghostwords** [comment]
Could you run the following script in your Badger's background page console and share what it prints out?
```javascript
(function () {
  const STR = "netlify";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by ghostwords** [comment]
Also, are you able to reproduce in Chrome?

**Comment by skorokithakis** [comment]
```
**** ACTION_MAP for netlify debugger eval code:3:3
cdn.netlify.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1515365675447
} debugger eval code:5:36
www.netlify.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1529276647844
} debugger eval code:5:36
terminal-tutorial-experiments.netlify.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1515446336891
} debugger eval code:5:36
api.netlify.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1520636363578
} debugger eval code:5:36
**** SNITCH_MAP for netlify debugger eval code:7:3
cdn.netlify.com [
  "app.netlify.com",
  "www.netlify.com"
] debugger eval code:9:36
www.netlify.com [
  "netlifycms.org",
  "app.netlify.com",
  "duckduckgo.com"
] debugger eval code:9:36
terminal-tutorial-experiments.netlify.com [
  "www.netlify.com"
] debugger eval code:9:36
api.netlify.com [
  "app.netlify.com"
]
```

I don't have Chrome, sorry.

**Comment by ghostwords** [comment]
Visiting Netlify from a trivial HTML document (`<a href="https://www.netlify.com/docs/">https://www.netlify.com/docs/</a>`) in Firefox causes Privacy Badger to record `www.netlify.com` as a tracker on `localhost` due to a `netlify.com` cookie getting somehow mis-attributed to the page we click the link on.

This does not seem to happen in Chrome.

**Comment by ghostwords** [comment]
This seems to be the same issue as #1144.

**Comment by ghostwords** [comment]
As I wrote in https://github.com/EFForg/privacybadger/issues/1953#issuecomment-388645296, we can find similar cases in error reports by looking for reports where the one blocked domain is also the site domain.

The majority of reports are from Firefox, but some are from Chrome (a different bug?).

Here is a selection of site domains from such Firefox reports from the last few months:
```
+-----------------------------+----------+
| fqdn                        | count(*) |
+-----------------------------+----------+
| outlook.live.com            |        5 |
| help.nextcloud.com          |        3 |
| www.autoscout24.de          |        2 |
| outlook.office.com          |        2 |
| discuss.pytorch.org         |        2 |
| community.home-assistant.io |        2 |
| forum.fivem.net             |        1 |
| www.google.de               |        1 |
| www.autoscout24.com         |        1 |
| dev.to                      |        1 |
| www.autoscout24.nl          |        1 |
| www.sweetwater.com          |        1 |
| www.midwayusa.com           |        1 |
| forum.snapcraft.io          |        1 |
| www.tipp24.com              |        1 |
| www.sportsmansguide.com     |        1 |
| tntrip.pw                   |        1 |
| www.verkkokauppa.com        |        1 |
| forum.matomo.org            |        1 |
| www.stavros.io              |        1 |
+-----------------------------+----------+
```
<details><summary>Sample user messages:</summary>

forum.matomo.org
>After logging into this site, I get a big message that says "CANNOT LOAD APP". It's not great

outlook.office.com
>Corrupted content error

discuss.pytorch.org
>"Cannot load app" error

www.tipp24.com
>angeblich keine internetverbindung

www.sweetwater.com
>it looks like you are currently offline.
</details>
<br>
Definitely looks like some kind of Service Workers / WebExtensions APIs bug in Firefox.
