### ISSUE TITLE
[Firefox] PB Popup is cut when placed in Overflow Menu

### ISSUE THREAD

**Issue by imagoiq** [EFForg/privacybadger#2064]
Hi,

Not a big issue, but I think it could be fixed easily. When I put the shortcut of Privacy Badger under an Overflow Menu (a menu to organize shortcuts), the popup is cut horizontally as you can see it below:

![Example](https://i.imgur.com/pERm6qk.png)

Thanks in advance

**Comment by ghostwords** [comment]
Hello! Please subscribe to #1120 for updates. It does seem like there should be a quick fix, but we haven't figured it out yet.
