### ISSUE TITLE
Blocking valid resources for Schibsted messaging system

### ISSUE THREAD

**Issue by ncoelho** [EFForg/privacybadger#2069]
Hi there,

We are having many reports from users saying that our product is not working with this plugin. 
We use various domains to provide the service that are being blocked, such as schibsted.com and schibsted.io

We provide a messaging system for sites such as:
- finn.no
- leboncoin.fr
- willhaben.at

Can you provide us some visibility if there's a way to be white-listed?

<img width="1234" alt="screen shot 2018-06-18 at 14 34 49" src="https://user-images.githubusercontent.com/1238429/41536470-014d295c-7306-11e8-876c-30a0a5744148.png">

Thank you

**Comment by bcyphers** [comment]
Hi,
If websites need to make requests to your domains in order to function, you can open a pull request to add your domains to the [yellowlist](https://github.com/EFForg/privacybadger/labels/yellowlist).
