### ISSUE TITLE
Add a "share" button to the popup

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#2079]
As suggested via email:

>I had clicked on the Privacy Badger [toolbar button] while at a favorite web site and was admiring (in horror) how many sites it had stopped tracking me when I suddenly realized that I needed to send a link to Privacy Badger to [a friend] who is also a user of the site in question and who currently suffers (without knowing it) from this very problem too. This requires assembling some information, such as the link to PB, the web site involved, the details of the blocked trackers, a personal recommendation into an email etc. This takes time and effort which makes me less likely to do it as time goes by.

I am not sure about adding another big button to the bottom of the popup, three are already a bit much. Since "sharing" and donating are related, perhaps we should rework the donate button while we are at it. Should we split the "donate" button into two buttons in the same row? UX suggestions most welcome!

**Comment by ghostwords** [comment]
Sort of related to #1622 in that it's another situation where we have two related buttons that we may want to combine in some way.

**Comment by ghostwords** [comment]
Similar popup UI button challenge in #827.

**Comment by troy-lamerton** [comment]
To add a share button, it would need to be on a page that can be visited by anyone.

`mailto` can only include plaint text in the email body, so I don't think that is sufficient.

We could either:
1. Publicly host pages that users can share
2. Generate an image and upload it anonymously to a provider like [Imgur](https://apidocs.imgur.com/#c85c9dfc-7487-4de2-9ecd-66f727cf3139).

@ghostwords let me know what you think and if option 1 is possible. I would be happy to work on either option.

**Comment by troy-lamerton** [comment]
![screen shot 2018-09-09 at 20 36 25](https://user-images.githubusercontent.com/13446008/45267616-2121cc00-b470-11e8-872a-23deaab6bc72.png)

What about this?

**Comment by ghostwords** [comment]
Good idea! I like this button placement much more than adding a fourth button to the bottom of the popup.

How do you see the dropdown working? I was thinking something like the following mockup, but with a multi-row text area (prefilled with text about what Badger is and the trackers Badger found on the current page) instead of the single line URL input, and a "copy to clipboard" button instead of the link button.

![pb-share-results](https://user-images.githubusercontent.com/794578/45384339-c1e0ca80-b5db-11e8-974d-03c273ed0477.png)

**Comment by ghostwords** [comment]
Updated the above mockup.

**Comment by troy-lamerton** [comment]
I thought the dropdown would have buttons to do the same thing as those orange buttons in your mockups.
You would click the share button, dropdown opens, click on "Tweet about privacy badger" and then a twitter tab is opened with the tweet ready to tweet.

I like your mockups better though, I understand this would work similar to how the reporting a broken site replaces the whole popup interface.

**Comment by Jsnhlbr5** [comment]
I am working on this, but have run into an issue with the site share buttons: only Twitter lets you provide arbitrary text in a simple share link.  I haven't found anything better than linking to the G+/Facebook main page, hoping the user copied the text.

**Comment by ghostwords** [comment]
Hmm ... yeah, we can just omit those buttons for now. (Google+ is going away anyway ...) Or we could include them but make it clear that they work differently somehow. "Copy to clipboard" and "Share on Twitter" are on the same level of functionality, while "Share on Facebook" is just a link to `https://www.eff.org/privacybadger` and the text will have to come from "Copy to clipboard".

Are there sharing dialog examples from other extensions/apps/programs we could review?

**Comment by Jsnhlbr5** [comment]
I think generating the message so that it can be copied and subsequently pasted into the sharing medium of choice is enough (for now anyway).  If there are very many trackers, the message becomes too long for Twitter, and without using the Facebook API (which requires an app id, and probably invokes tracking) we can do at best a half-job of creating the post.
