### ISSUE TITLE
Add c1.neweggimages.com to whitelist

### ISSUE THREAD

**Issue by jjlook** [EFForg/privacybadger#2080]
**** ACTION_MAP for newegg debugger eval code:3:5
c1.neweggimages.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1530028954724
} debugger eval code:6:40
neweggimages.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 0
} debugger eval code:6:40
**** SNITCH_MAP for newegg debugger eval code:9:5
neweggimages.com [
  "newegg.com"
]

**Comment by ghostwords** [comment]
Hello and thanks for opening the issue! We fixed this in #2078, sorry I wasn't more clear. Everyone will get the fix with the next Privacy Badger update.
