### ISSUE TITLE
ideditor preview version is broken

### ISSUE THREAD

**Issue by theel0ja** [EFForg/privacybadger#2090]
url: http://preview.ideditor.com/master

![image](https://user-images.githubusercontent.com/5832930/42479545-190f021c-83e2-11e8-9f6e-2cd661c33dcc.png)

**Comment by bcyphers** [comment]
Related: #2066

**Comment by bcyphers** [comment]
I'd like to see how Privacy Badger learned to block those domains. 

Can you open up a console in the Privacy Badger background page and run the following code, then paste the output here?

```
(function () {
  const STR = "openstreetmap";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit chrome://extensions, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit about:debugging, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by ghostwords** [comment]
And #2067.

The debug output might be the same as in https://github.com/EFForg/privacybadger/issues/2065#issuecomment-397050689
