### ISSUE TITLE
Create issue template for broken sites

### ISSUE THREAD

**Issue by bcyphers** [EFForg/privacybadger#2091]
This seems to be the most common issue we get, and the process to resolve them is very formulaic. The first step is almost always to ask the user to run a command in their browser that will print out the `action_map` and `snitch_map` for the domain in question. We can streamline this process with an [issue template](https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/).

Let's create an issue template at `ISSUE_TEMPLATE/broken_site.md` that includes instructions for finding the culprit blocked domains and running [this script](https://github.com/EFForg/privacybadger/issues/2065#issuecomment-397045609). We can then link users to https://github.com/EFForg/privacybadger/issues/new?template=broken_site.md whenever we ask them to submit an issue for a broken site.

**Comment by ghostwords** [comment]
Oh nice, we can create a specialized template and then have that show up as a clear option when users click on "new issue": https://help.github.com/articles/about-issue-and-pull-request-templates/
