### ISSUE TITLE
Avoid opening a new window when clicking to open options from a Private Browsing window

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#2092]
Following up from https://github.com/EFForg/privacybadger/issues/2058#issuecomment-403180062.

We currently open the options page inside a new non-Private window when you click on the options button in the popup from a Private Browsing window in Firefox. We don't have to open a new window, however; we could fix our options page to work in Private windows and then revert b0dd2fa400a509bb3af85dfb5f4bffa0b1b5b733, which will then have options open in a new tab in the existing Private window.

This requires refactoring the options page to never rely on Privacy Badger background page objects directly (which are not accessible to Private windows in Firefox) and use messaging for everything (we already use messaging for saving options (#1911)).

This fix would be similar to what happened to the popup in #1899. I'll be happy to provide more guidance on request.

**Comment by 0pLuS0** [comment]
@ghostwords please let me know when this has been committed and released, so I can test it on my end to make sure?

Thanks

**Comment by ghostwords** [comment]
OK sounds good. This issue will be closed when the code is done, and after that this enhancement will be in the next update. We approximately know what needs to happen, but nobody is working on this yet. If somebody opens a pull request, I'll be happy to review though.

**Comment by 0pLuS0** [comment]
Thanks, hopefully this will be fixed soon.

**Comment by emsal1863** [comment]
Hi, I'm looking to contribute to Privacy Badger and I saw this had a 'good first issue' tag. ok to pick this up?

**Comment by ghostwords** [comment]
Hello and welcome! Yep, I'm not aware of anybody else working on this. Let me know if you have any questions. I suggest opening a PR with your in-progress code and asking questions/requesting feedback there.

**Comment by emsal1863** [comment]
@ghostwords I haven't actually yet started but I will shortly; here are just a few things I'd like to ask:

* I've only dabbled in extension development prior to this. Any essentials for setting up a dev environment?
* Can you point me to a relevant file/segment that uses the messaging mechanism used for saving options, as detailed in the issue post?

**Comment by ghostwords** [comment]
We have a work-in-progress [Privacy Badger developer guide](https://github.com/EFForg/privacybadger/blob/master/doc/develop.md). Right now it just tries to help you load Badger from source and run the linter (static analysis) against the code (so that you could address certain issues before even committing anything). So I would say do these things first.

Afterwards, see if you can get the tests to run locally. This should be documented in the [Privacy Badger automated testing guide](https://github.com/EFForg/privacybadger/blob/master/doc/tests.md).

The big idea here will be to stop relying on accessing anything on the background page directly (`chrome.extension.getBackgroundPage()`) and instead get the data you need by messaging the background page. We already use messaging for saving state in options, but not for getting the state yet.  The popup used to rely on the background page directly, but no longer does. Most of this works happened in #1899, so you can take a look at some of those commits to see what needed to happen.

**Comment by emsal1863** [comment]
Would this involve getting rid of every reference to `backgroundPage` in all of the code in `options.js`?

**Comment by ghostwords** [comment]
Correct, same as what we did with the popup. We [removed `getBackgroundPage()`](https://github.com/EFForg/privacybadger/pull/1899/files#diff-02253422d34d8e9ba25ec39d078fe277L22) and replaced all uses of background page objects ([for example](https://github.com/EFForg/privacybadger/pull/1899/files#diff-02253422d34d8e9ba25ec39d078fe277L291)) with [data we got from messaging](https://github.com/EFForg/privacybadger/pull/1899/files#diff-02253422d34d8e9ba25ec39d078fe277R541).

**Comment by emsal1863** [comment]
Thanks! I'm fairly sure I'm proceeding well. What do you do to replace the references to `log`, which was originally defined as `backgroundPage.log`? Would I just use `console.log` in that case?

**Comment by ghostwords** [comment]
Generally speaking, if you need to use a function that was available through the background page object, you would see where that function is defined (`log()` is defined in `bootstrap.js`), and then see if you need to include that file in `options.html` so you can keep using the function (updating the way you reference it if needed).

In this particular case, yeah, `console.log` is fine.

**Comment by ghostwords** [comment]
@bcyphers I realized thanks to your HTTPS Everywhere link above that we can't open `chrome-extension://` resources in Chrome Incognito windows because Privacy Badger is a ["spanning" mode](https://developer.chrome.com/extensions/manifest/incognito#spanning) extension. Firefox seems to not care; Badger's options page can be opened in a Private window (we just have to make it work there by removing all background page object references).

So I guess we'll have to keep custom options page opening logic for Chrome (switching to "split" mode just for this enhancement doesn't seem worth it). Refactoring the options page to use messaging for everything is still a good thing as it helps us organize code better and avoid weird bugs like #1429.

**Comment by ghostwords** [comment]
This should also fix opening options from a [temporary container](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) in Firefox.

>Ever since Version 9.20.2018, when i click the Settings Gear/Cog icon in the Pop-Up Panel it doesn't work, it just opens a blank page, and i've figured out why, it's because it opens in a Temporary Container because of the extension Temporary Containers. Temporary Containers hasn't been updated in awhile so i know it's not because of that, as this problem never existed for me before Privacy Badger version 9.20.2018. i don't know who has to fix that problem, EFF or the Developer of Temporary Containers. A work around is going to about:addons and find Privacy Badger and clicking Options and it won't open in a Temporary Containers.

**Comment by ghostwords** [comment]
@0pLuS0 This is now live as part of Privacy Badger version 2018.12.5

**Comment by 0pLuS0** [comment]
@ghostwords it's been fixed?

**Comment by 0pLuS0** [comment]
@ghostwords we have a bigger problem now, the ```Options``` won't even open now for me on Linux using Firefox ESR 52.9.0

I click on it and nothing happens... :(

hmm


![options](https://user-images.githubusercontent.com/36190223/49616234-0ba53b00-f9a8-11e8-948e-dd93449e8a21.jpg)

**Comment by ghostwords** [comment]
Which version of Firefox do you have?

**Comment by ghostwords** [comment]
It looks like Firefox 52 is no longer supported as of September 2018 (as per https://en.wikipedia.org/wiki/Firefox_version_history). Are you able to upgrade?

**Comment by 0pLuS0** [comment]
@ghostwords I know I'm on an older version but because of the WebExtensions change, an addon I use won't work in the latest versions...

**Comment by ghostwords** [comment]
OK, I can put in a workaround for the next Privacy Badger update. In the meantime, you should be able to get to Badger's options by going to `about:addons`, clicking on the Extensions tab and then clicking on the Preferences button for Privacy Badger.

**Comment by 0pLuS0** [comment]
@ghostwords personally between you and me, I surf all over the web on this version of Firefox and it works just fine everywhere I go. I also like the idea I have greater control over it, since Mozilla has us locked out of newer versions, at least it's my understanding.

I see nothing wrong with using older versions, and I've never run across a site that didn't work, or something broke...

**Comment by ghostwords** [comment]
The problem is that unsupported browsers no longer receive security updates. So as time goes on, you expose yourself to more and more known vulnerabilities. I don't know how likely it is for you to, say, get locked up with ransomware, but you should be aware the more out-of-date is your browser and/or OS, the more you expose yourself to that kind of thing.

**Comment by 0pLuS0** [comment]
I'm not on Windows or Apple, I'm on the safest OS known to man.... I don't worry about this, I just use it for some of the so called privacy/tracking support is all...

But then you also use different Networks/Servers for the IP and GEO, as in all the many ways one can, and then, well, the tracking is never going to come back to you anyway...

**Comment by ghostwords** [comment]
@0pLuS0 The options page should be working again for you as of today's update (Privacy Badger version 2018.12.17).

**Comment by 0pLuS0** [comment]
@ghostwords it works in FF ESR 52.9.0! :)

FF 52.9.0 the last best version that lets you still be in the control!

pfff to newer firefox....
