### ISSUE TITLE
Network Request Redirect Failed

### ISSUE THREAD

**Issue by dicicch** [EFForg/privacybadger#2101]
Hello,
I am running MacOS High Sierra 10.13.5 with Chrome 67.0.3396.99 (Official Build) (64-bit)
I have Privacy Badger with another tracking deterrent extension called Disconnect.
While browsing, I suddenly got the following extension error from Privacy Badger:
> "This extension failed to redirect a network request to data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJd2luZG93LkNPTVNDT1JFID0gewoJCXB1cmdlOiBmdW5jdGlvbigpIHsKCQkJX2NvbXNjb3JlID0gW107CgkJfSwKCQliZWFjb246IGZ1bmN0aW9uKCkgewoJCQk7CgkJfQoJfTsKfSkoKTs= because another extension (Disconnect) redirected it to about:blank."

Thanks!

**Comment by ghostwords** [comment]
Please see https://github.com/EFForg/privacybadger/issues/2095#issuecomment-404250534 for an explanation of what's happening. The tracker in question here isn't Google Analytics, but the underlying situation is the same. Let me know if you have any questions.
