### ISSUE TITLE
Verkkokauppa.com is broken

### ISSUE THREAD

**Issue by theel0ja** [EFForg/privacybadger#2103]
url: https://www.verkkokauppa.com/fi/catalog/3603c/NAS-palvelimet

had to make new tab and reload

![image](https://user-images.githubusercontent.com/5832930/42879667-1a8cff9a-8a9a-11e8-91d8-d6e6f7939a16.png)

**Comment by theel0ja** [comment]
This has happened more than 1 time on even different machines...

**Comment by ghostwords** [comment]
This looks like the same Firefox bug as #1144 (see #2062 for a similar scenario). Privacy Badger reports blocking the same domain as the site domain; the site says something to the effect of "you appear to be offline". Does this seem right?
