### ISSUE TITLE
Prevents Login To Vonage

### ISSUE THREAD

**Issue by ynaftali** [EFForg/privacybadger#2104]
Users with the Privacy Badger Chrome/Firefox/Opera extension can't log into our app at app.vonage.com.

**Comment by ghostwords** [comment]
Hello! Could you provide the debugging information requested in https://github.com/EFForg/privacybadger/blob/1cac5ba752517802d0596645c464ffd55a60c9d0/.github/ISSUE_TEMPLATE/broken-site-report.md?

**Comment by ghostwords** [comment]
Is the problem domain in question `app.vonagebusiness.com`?

**Comment by ynaftali** [comment]
The problem is with the domain app.vonage.com.
Here's the debugging information:
VM139:3 **** ACTION_MAP for vonage.com
10:31:45.905 VM139:5 api.vonage.com {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1531939819958,
  "userAction": ""
}
10:31:45.905 VM139:5 vonage.com {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 0,
  "userAction": ""
}
10:31:45.905 VM139:5 www.vonage.com {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1531910187067,
  "userAction": ""
}
10:31:45.905 VM139:7 **** SNITCH_MAP for vonage.com
10:31:45.906 VM139:9 vonage.com [
  "vocal-dev.com",
  "vonagebusiness.com"
]
10:31:45.921 undefined

**Comment by ghostwords** [comment]
Would it be possible to ask a customer whose Badger learned to block "vonage" to run the same debugging code in their Badger, and share the output here?

My guess at this time is that we should tell Privacy Badger `vonage.com` and `vonagebusiness.com` belong to the same entity, but I don't know if there is more to this problem than just these two domains.

**Comment by ynaftali** [comment]
It happens to others at the office, no need to ask a customer. If you can
ignore app.vonage.com it’ll be great.

**Comment by ghostwords** [comment]
Could you have somebody who is experiencing this issue run the debugging code in their Badger and share the output with us?

**Comment by ynaftali** [comment]
<img width="1669" alt="screen shot 2018-08-16 at 10 24 53" src="https://user-images.githubusercontent.com/34687181/44194657-5112d380-a13f-11e8-9972-c68b35564c29.png">

**Comment by ghostwords** [comment]
And what if you do the same thing, but for `app.vonagebusiness.com` instead of `app.vonage.com`?
