### ISSUE TITLE
cdn.plot.ly

### ISSUE THREAD

**Issue by gamer01** [EFForg/privacybadger#2105]
Privacy badger blocks this cdn to download plotly.js, a open source statistical and plotting library based on d3.

It schould be in the yellow list in my opinion.

**Comment by ghostwords** [comment]
Hello! Could you provide the debugging information requested in https://github.com/EFForg/privacybadger/blob/1cac5ba752517802d0596645c464ffd55a60c9d0/.github/ISSUE_TEMPLATE/broken-site-report.md?

**Comment by gamer01** [comment]
Acutally i dont know other sites that are broken, but i am web developer on a non public project.

Here is a jsfiddle to reproduce the issue: https://jsfiddle.net/b4fyj8nh/1 

Its simply blocking the mandatory javascripts source as stated in the issue.

```
(function () {
  const STR = getBaseDomain("https://jsfiddle.net/b4fyj8nh/1");
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
**** ACTION_MAP for https://jsfiddle.net/b4fyj8nh/1 debugger eval code:3:3
**** SNITCH_MAP for https://jsfiddle.net/b4fyj8nh/1 debugger eval code:7:3
undefined
[SW] on message <unavailable>
js/lib/push_worker.js:85:3
Security Error: Content at moz-extension://86b1f8fa-a012-4843-9e4c-eeeff9793f4a/ may not load data from blob:null/7093786e-12bc-4fb1-b4d6-3232abe560d9.
[Show/hide message details.] sender.page is undefined MessageChannel.jsm:964
Security Error: Content at moz-extension://86b1f8fa-a012-4843-9e4c-eeeff9793f4a/ may not load data from blob:null/0a09b121-7e96-42e9-9b49-6c492519120a.
[Show/hide message details.] sender.page is undefined MessageChannel.jsm:964
Loading failed for the <script> with source “https://crbsrv.jsfiddle.net/ads/CKYIEKQ7.json?segment=placement:jsfiddlenet&callback=_carbonads_go”. 1:1
Loading failed for the <script> with source “https://cdn.plot.ly/plotly-latest.min.js?_=1532029398263”. show:1 
```

**Comment by ghostwords** [comment]
You have to run the debug code in your Badger's background page for the domain that Privacy Badger learned to block but that it perhaps shouldn't have. The point is to help learn why Privacy Badger decided to start blocking a given domain.

**Comment by gamer01** [comment]
Ok, i didnt know that there is learning involved. The output code you see above was generated by pasting the functions in this additional window that shows up when i click on the debug button for the extension in `about:extensions` in firefox. Did i do something wrong or can you elaborate what you need instead. (i tried to follow the description in the link you provided, but perhaps i didnt understand it properly)

Is the learning independent of the website the script is loaded or does it depend on it? Acutally there was one site where it worked sometimes http://mathjs.org/examples/browser/plot.html

**Comment by ghostwords** [comment]
I think you got to the background page OK (since there weren't any errors in the output). The problem is that you ran the debug code for a page URL, but we want to run the debug code for the domain that Badger blocked but perhaps shouldn't have. It sounds like that domain is `cdn.plot.ly` in this case.

We need to explain what "blocked domain" means in the [debug output instructions](https://github.com/EFForg/privacybadger/blob/1cac5ba752517802d0596645c464ffd55a60c9d0/.github/ISSUE_TEMPLATE/broken-site-report.md).

**Comment by gamer01** [comment]
```
(function () {
  const STR = getBaseDomain("https://cdn.plot.ly");
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
**** ACTION_MAP for plot.ly debugger eval code:3:3
cdn.plot.ly {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1532441223852
} debugger eval code:5:36
plot.ly {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
} debugger eval code:5:36
community.plot.ly {
  "userAction": "",
  "dnt": true,
  "heuristicAction": "",
  "nextUpdateTime": 1532345432466
} debugger eval code:5:36
**** SNITCH_MAP for plot.ly debugger eval code:7:3
plot.ly [
  "mathjs.org",
  "jsbin.com",
  "codepen.io"
]
```

Those domains are all domains where i played arround with the CDN. So it seems to be that the issue is not general, but mostly related to me. If you still consider it a bug, than let me know if i can assist any further. Otherwise i would be ok, if you close the issue.

Initially i was afraid that everyone using my website that has privacy badger installed, would not be able to use the website properly, which seems not to be the case, when i interpret the log correctly.

**Comment by ghostwords** [comment]
I see cookies getting set by `cdn.plotly.com` when I visit http://mathjs.org/examples/browser/plot.html
```
plotly_sess_pr=LONG_HEX_STRING; plotly_csrf_pr=DIFFERENT_LONG_HEX_STRING; plotly_anoncsrf_pr=THIRD_LONG_HEX_STRING
```
We should probably add `plot.ly` (or is just `cdn.plot.ly` enough?) to our [yellowlist](https://github.com/EFForg/privacybadger/blob/master/doc/fixing-broken-sites.md#external-domains-too-complex-to-surrogate-or-replace-with-placeholders).

**Comment by gamer01** [comment]
I cannot fully answer this question. To solve my specific issue, yellowlisting `cdn.plot.ly` is definetly enough (https://plot.ly/javascript/getting-started/#plotlyjs-cdn)

**Comment by ghostwords** [comment]
I see that Plotly also provides embedded widgets such as the ones on http://blog.interviewing.io/we-looked-at-how-a-thousand-college-students-performed-in-technical-interviews-to-see-if-where-they-went-to-school-mattered-it-didnt/ and http://on-the-t.com/2018/05/27/nadal-patterns/. These are frames from `plot.ly` (no "cdn").
