### ISSUE TITLE
please add *.epoq.de to yellow list

### ISSUE THREAD

**Issue by rgrFromEpoq** [EFForg/privacybadger#2108]
Our company offers 1st party services like shop search to the shop owners.
We only work for the single shop. We don't mix data from different shops. Please add us to the list of the "good ones" :-)

Feel free to ask if there are any questions.

**Comment by ghostwords** [comment]
Could you provide the debugging information requested in https://github.com/EFForg/privacybadger/blob/1cac5ba752517802d0596645c464ffd55a60c9d0/.github/ISSUE_TEMPLATE/broken-site-report.md?

**Comment by rgrFromEpoq** [comment]
**** ACTION_MAP for asmc.de 
www.asmc.de {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1532679985043
} 
asmc.de {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 0
}
**** SNITCH_MAP for asmc.de 
asmc.de [
  "asmc.com"
]

**Comment by ghostwords** [comment]
Sorry for the late reply. I see that it wasn't clear in our instructions what the "blocked domain" is. We are not interested in the domain of the site where the issue occurred; we are interested in the third-party domain that breaks the site when blocked. Does our new ["Find out why Privacy Badger is blocking a domain" wiki page](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) make this more clear?

**Comment by ghostwords** [comment]
Would your service be by any chance compliant with [EFF's Do Not Track policy](https://www.eff.org/dnt-policy). If you are willing and able to abide by the policy's requirements on your service domains, posting the policy on each domain will tell Privacy Badger to always allow loading of resources from the domain.
