### ISSUE TITLE
Implement Chrome/Firefox Sync for the list of disabled sites 

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#2110]
We only want to sync the list of disabled sites, not any other settings nor Badger's tracker database. See https://github.com/EFForg/privacybadger/issues/645#issuecomment-406706330 for the rationale.

This replaces #645 and #1115.

**Comment by Jsnhlbr5** [comment]
I am interested in working on this.  It would be my first code contribution to an open source project.

**Comment by ghostwords** [comment]
Hello and welcome! Let me know if you have any questions. I suggest opening a pull request from your in-progress branch and continuing any discussion there.

**Comment by ghostwords** [comment]
This is being implemented in #2150 as a manual process to begin with (to remove data overwriting issues and reduce implementation complexity, see https://github.com/EFForg/privacybadger/pull/2150#pullrequestreview-150182344 for more information). We are getting two new buttons under the Manage Data page; one to upload the list of disabled sites to the cloud (using Firefox/Chrome Sync), and the other to import the list from the cloud.

We may add other pieces of Badger user data to cloud uploading/downloading in the future, and we may switch to automatic cloud syncing, but I hope that the buttons will be enough for now.

**Comment by ghostwords** [comment]
Fixed by 733c04d9b97d16ee5937eeb93bc1415719730929.
