### ISSUE TITLE
Not filtering requests in Firefox Mobile + Android in one particular use case

### ISSUE THREAD

**Issue by rnavaneethan** [EFForg/privacybadger#2118]
Normally when I open Firefox Mobile browser and navigate to any site, Privacy badger is filtering the requests based on heuristics and everything works fine as expected similar to desktop. However, the extension is not doing anything in the below case.

- Set Firefox Mobile as default browser
- Go to any application and click on a link
- This should launch Firefox mobile and load the URI.
- Click on Firefox menu and select Privacy badger
- This displays "No trackers detected"

In this case, Privacy badger is not filtering any requests. Not sure, it's just me or anyone else have the same problem.

Firefox Mobile v61.0 (latest stable)
Privacy badger v2018.7.18.1 (stable)

**Comment by ghostwords** [comment]
Is this the same issue as #1845, just on Android?

**Comment by rnavaneethan** [comment]
It is indeed. :) Though the repro steps are little different, underlying issue seems to be same. Can this be closed as duplicate?

**Comment by ghostwords** [comment]
Yep. Thanks for providing the steps for Android!
