### ISSUE TITLE
broken shops hosted by plentymarkets.eu

### ISSUE THREAD

**Issue by Kobajashi** [EFForg/privacybadger#2129]
Hey,

it seems that the badger is blocking our content delivery network for our customers.

We offer three generic CDN URLs for our customers
* cdn01.plentymarkets.com
* cdn02.plentymarkets.com
* cdn03.plentymarkets.com

These URLs are used in more than 3000 Online Shops to deliver images in a fast way.
A short time ago we also started to deliver all static content through our cdn including css and javascript files so the problem getting bigger.

Here is an snitch for cdn02 as example

```
**** ACTION_MAP for cdn02.plentymarkets.com
VM255:5 cdn02.plentymarkets.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1533825355154
}
VM255:7 **** SNITCH_MAP for cdn02.plentymarkets.com
```

Would it be possible to add the CDN of use to yellowlist?
* cdn01.plentymarkets.com
* cdn02.plentymarkets.com
* cdn03.plentymarkets.com

This is a high priority issue for use cause we receive a lot of tickets regarding broken shops.

If you have further question so let me know. 
I'm one of the Architects for the CDN Project.

Regards
Timo

**Comment by ghostwords** [comment]
Hello!

Why does Privacy Badger learn to block these CDN domains? I could see for myself if you provide a few examples of plentymarkets-powered shops.

If you don't track anyone using these CDN domains, they may be a good match for [EFF's Do Not Track policy](https://www.eff.org/dnt-policy). If you are willing and able to abide by the policy's requirements on the affected domains, posting the policy on each domain will tell Privacy Badger to always allow loading of resources from the domain.

**Comment by Kobajashi** [comment]
Hey,

I've no idea why these things getting blocked.

These domains are only CNAMEs in front of an AWS CloduFront CDN Distribution.
So I don't think is would be an easy job to implement the DNT policy cause I don't know how I should return different results depending on header tracking status here.

I looked into the yellow list and saw an entry for CloudFront, the only difference is the CNAME that we use in front of the generic CloudFront URL string.

**Comment by Kobajashi** [comment]
example shops:

* https://www.delife.eu/
* https://www.gasprofi24.de/
* https://www.naturdrogerie.de/

These there shops make us of cdn02 distirbution.

**Comment by ghostwords** [comment]
>So I don't think is would be an easy job to implement the DNT policy cause I don't know how I should return different results depending on header tracking status here.

There is no need to return different results ... If the domain is compliant with EFF's DNT policy, you just post the verbatim policy text at the canonical path and you should be all set.

**Comment by ghostwords** [comment]
Regarding `cloudfront.net` being the yellowlist: Looks like it was added as part of the original "example" yellowlist (cfe3cf95e141f161071bfb0930692ca37e3fd32c). We may want to remove it at some point (#1593), although its frequently reports as being "cookieblocked" in our error reports, which means some Badgers do see tracking from it.

**Comment by ghostwords** [comment]
I'm going to close this for now. Let me know if you have more information.
