### ISSUE TITLE
Allow users to view snitch_map data through the UI

### ISSUE THREAD

**Issue by bcyphers** [EFForg/privacybadger#2130]
It would be nice to be able to see data about _why_ a specific domain was blocked without having to open up the Privacy Badger console. I think this could be implemented in a box in the Tracking Domains tab, to the right of the long domain list. Something like the following: 
![snitch-map-example](https://user-images.githubusercontent.com/4840035/43793132-85cf7a7c-9a2f-11e8-958f-65eef4431dff.png)

This is low priority, but it would make it easier for users to help us debug broken site issues, and it would be a nice feature for users like me who are curious about where certain trackers were found. This is a "nice to have," not a "need to have," but it should be relatively simple to build.

**Comment by ghostwords** [comment]
I guess I filed this already under #1289. But your mockup is good to have. Let's close this one and continue in #1289.
