### ISSUE TITLE
National Car Rental: important/non-tracking cookie blocked causing site to break

### ISSUE THREAD

**Issue by hzoells** [EFForg/privacybadger#2138]
Hello Privacy Badger,
The national car rental website is losing critical functionality because privacy is blocking necessary cookies.

### What is broken and where?
The location search function of www.nationalcar.com will not function:
![image](https://user-images.githubusercontent.com/41125609/44354227-e3341800-a46e-11e8-9a5c-00a638452741.png)

### What are the domains that cause the breakage when blocked?
This problem is caused when `prd.location.enterprise.com` is blocked. It seems that Privacy Badger identifies this cookie as a tracker when the National Car Rental website is visited on different regional domains (see below). Given that National is an international car rental company, this is an important use case.
This cookie is used by a service which is shared between these three websites, its purpose is website functionality, not tracking users.
### Output from the wiki page:
```
**** ACTION_MAP for enterprise.com
VM991:5 prd.location.enterprise.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1535369289544
}
VM991:5 enterprise.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
VM991:5 smetrics.enterprise.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1535224948810
}
VM991:7 **** SNITCH_MAP for enterprise.com
VM991:9 enterprise.com [
  "nationalcar.com",
  "nationalcar.ca",
  "nationalcar.de"
]
```
Please ask for any further information that might be needed to solve this problem.
Best regards,

**Comment by ghostwords** [comment]
Thanks for the report!
