### ISSUE TITLE
Autodesk.com sites broken 

### ISSUE THREAD

**Issue by galiat** [EFForg/privacybadger#2143]
### What is broken and where?
Its probably more than this, but I noticed that www.autodesk.com & www.autodesk.com/content/boston are broken.

### What are the domains that cause the breakage when blocked?
privacy badger was blocking damassets.autodesk.net & static-dc.autodesk.net

### Please paste the output from the wiki page:
I'm not sure what wikipage output you are looking for. I did notice this commit: https://github.com/EFForg/privacybadger/commit/415eb2cce4d6fb536ded9d73948b3533fb965fe2 which adds autodesk.net & other things to the mdfp list.  Does that mean the next release of privacy badger will fix this?

**Comment by ghostwords** [comment]
Hello! Thanks for letting us know. Yep, this was recently fixed by #2123, which will be part of the next release.

**Comment by ghostwords** [comment]
The wiki page in question is https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain. Sorry this wasn't clear; feel free to suggest better wording for the [broken site issue template](https://github.com/EFForg/privacybadger/blob/master/.github/ISSUE_TEMPLATE/broken-site-report.md).
