### ISSUE TITLE
messd up GUI in the overflow menu

### ISSUE THREAD

**Issue by DJCrashdummy** [EFForg/privacybadger#2146]
i'm not sure, but it may be related to #1252...

at least in firefox if you move privacybadger into the overflow menu and open its menu from there, the GUI is messed up:
![bildschirmfoto](https://user-images.githubusercontent.com/26110463/44512296-55e50380-a6ba-11e8-8225-8dfc14411475.png)

- the table with the domains is completely screwed
- and also if you scroll down completely, the last button/link ("donate to EFF") is hardly shown.

**Comment by ghostwords** [comment]
Is this a duplicate of #1120?

**Comment by DJCrashdummy** [comment]
@ghostwords yes, it is at least a duplicate of https://github.com/EFForg/privacybadger/issues/1120#issuecomment-329969739.

sorry for creating this duplicate, but i haven't found the original because in the whole issue there is not even once mentioned the "overflow menu" like it is called... :slightly_frowning_face:

**Comment by ghostwords** [comment]
No problem! I'll edit the issue title.

This bug is quite prominent, many people seem to run into it. No clear quick fix yet though.
