### ISSUE TITLE
Broken site: dev.to

### ISSUE THREAD

**Issue by philnash** [EFForg/privacybadger#2151]
### What is broken and where?

The site [dev.to](https://dev.to) is blocked. Though weirdly this only happens when navigating to the site from another site, not when visiting directly. Privacy Badger's blocking then manifests itself through the offline page supplied by the service worker. Hard refreshing allows access to the site again.

There is more detail in this [issue on the dev.to source](https://github.com/thepracticaldev/dev.to/issues/456).

### What are the domains that cause the breakage when blocked?

dev.to

### Please paste the output from the wiki page:
```
**** ACTION_MAP for dev.to debugger eval code:3:3
dev.to {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1535875720338
} debugger eval code:5:36
**** SNITCH_MAP for dev.to debugger eval code:7:3
dev.to [
  "reddit.com",
  "t.co",
  "cloudinary.com"
]
```

**Comment by ghostwords** [comment]
I think this is the same Firefox bug as #1144. Privacy Badger reports blocking the same domain as the site domain; the site says something to the effect of "you appear to be offline". Does this seem right?

**Comment by philnash** [comment]
@ghostwords That may be the same yes. dev.to has a service worker that fields failed responses with an offline page, which is what I was seeing when navigating from another site to dev.to.

**Comment by ghostwords** [comment]
OK, thank you, I'll mark this as a duplicate then.
