### ISSUE TITLE
Invalid Error State error

### ISSUE THREAD

**Issue by TheRealMoleman** [EFForg/privacybadger#2156]
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.

![image](https://user-images.githubusercontent.com/30929795/44983343-d4f1fb80-af46-11e8-94e6-b913b95a58e0.png)

Unsure why this error is happening on my laptop or what info you need. Running Firefox x64 Nightly Build.

**Comment by WPFilmmaker** [comment]
I update to 66.0.2 (64-bit Linux) and this popped up again, what can be done?

**Comment by ghostwords** [comment]
Not sure yet, see also https://github.com/uBlockOrigin/uBlock-issues/issues/141

**Comment by WPFilmmaker** [comment]
Little update: the pop-up is now gone...
