### ISSUE TITLE
Whitelist payments.amazon.com

### ISSUE THREAD

**Issue by davidhedlund** [EFForg/privacybadger#2169]
### What is your browser and browser version?
Firefox ESR 60.2.1 (64-bit) for GNU/Linux

### What is broken and where?
Privacy Badger blocked cookies from payments.amazon.com. I had to whitelist it to order from swansonvitamins.com

### What is the domain that causes breakage when blocked? What is your debug output for this domain?
https://www.swansonvitamins.com/, just place a sample order, click on your Cart, click on Amazon Pay.

> To complete the Amazon Pay checkout you must accept third-party cookies in the options/settings of your internet browser. After you have accepted third-party cookies please refresh this page to continue check out.

**Comment by ghostwords** [comment]
Does setting the slider for `payments.amazon.com` to "yellow" also resolve the problem, or does the slider have to be "green"?

**Comment by davidhedlund** [comment]
@ghostwords Thank you.
