### ISSUE TITLE
Add: What is your Privacy Badger version?

### ISSUE THREAD

**Issue by davidhedlund** [EFForg/privacybadger#2170]
> 

### What is your Privacy Badger version?
Can you please add this to https://github.com/EFForg/privacybadger/issues/new?template=broken-site-report.md ?

> 
> ### What is your browser and browser version?
> 
> ### What is broken and where?
> 
> ### What is the domain that causes breakage when blocked? What is your debug output for this domain?
> ```
> Please follow the instructions on
> https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain
> and paste the output here.
> ```
>

**Comment by ghostwords** [comment]
I think it's OK not to ask this upfront since thanks to how browsers handle extension updating, most users are on the latest Privacy Badger. The more text we have in the new issue template, the more we complicate opening issues for our users.

What led you to make this suggestion?

**Comment by davidhedlund** [comment]
> Does setting the slider for payments.amazon.com to "yellow" also resolve the problem, or does the slider have to be "green"?

Suggestions:
What is your Privacy Badger version? (optional)

What is the color indication? (optional)

**Comment by ghostwords** [comment]
The issue template is meant to help with the most common case: a blocked domain (we ask which one) breaks something on the page. I don't recall the version of Privacy Badger ever coming up (again, most users are on the latest). For contrast, the browser version does matter: Firefox and Chrome differ in major ways and there often browser bugs in some but not other versions of the same browser. I think there is no need to ask questions (optional or not) until we actually need the information.
