### ISSUE TITLE
Monzo (UK Bank) SecureCode page gets blocked

### ISSUE THREAD

**Issue by dovys** [EFForg/privacybadger#2175]
Hey 👋 

We've had several reports from our customers that they were unable to pay online as our SecureCode page was stuck in `307 Internal Redirect`. We've narrowed it down to the Privacy Badger extension that they had installed. Once disabled they were able to make the payments again. 
Our SecureCode domain https://verify.monzo.com does no tracking whatsoever and does not send out cookies. 

### What is your browser and browser version?
Chrome 69.0.3497.92

### What is broken and where?
Customers entering Monzo's SecureCode page get stuck in `307 Internal Redirect`

### What is the domain that causes breakage when blocked? What is your debug output for this domain?
Unfortunately we don't have the debug information as it happened on our customer's browsers.

**Comment by ghostwords** [comment]
Hello! Could you provide an example or two (or ideally three) of pages where this happens? I'm interested in seeing what happens and how Privacy Badger learns to block your domain.

**Comment by dovys** [comment]
Hey @ghostwords

One of our staff managed to reproduce it. Hope this helps:

![3ds_screenshot](https://user-images.githubusercontent.com/1223251/46402420-90997d00-c6f7-11e8-82c4-3311d9b863a6.png)

![action_map_verify](https://user-images.githubusercontent.com/1223251/46402428-94c59a80-c6f7-11e8-9eee-7bed74c55fe6.png)

![action_map_servingsys](https://user-images.githubusercontent.com/1223251/46402429-95f6c780-c6f7-11e8-96f6-d83749457167.png)

```
VM100:3 **** ACTION_MAP for verify.monzo.com
VM100:5 verify.monzo.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1538672479585,
  "userAction": ""
}
VM100:7 **** SNITCH_MAP for verify.monzo.com


VM173:3 **** ACTION_MAP for bs.serving-sys.com
VM173:5 bs.serving-sys.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1538813629582,
  "userAction": ""
}
VM173:7 **** SNITCH_MAP for bs.serving-sys.com
```

Cheers

**Comment by ghostwords** [comment]
Yep, this is super helpful, thank you!

Does setting all `monzo.com` domains to "yellow" resolve the problem? You'll probably need to restart the checkout process.

**Comment by ghostwords** [comment]
Hi, just looking to confirm that "yellowlisting" fixes the issue with Monzo. Let me know if it does and we'll get this closed out.

**Comment by ghostwords** [comment]
>Our SecureCode domain https://verify.monzo.com does no tracking whatsoever and does not send out cookies.

Also, if you don't track anyone using `verify.monzo.com`, it may be a good match for [EFF's Do Not Track policy](https://www.eff.org/dnt-policy). If you are willing and able to abide by the policy's requirements on the affected domain(s), posting the policy on each domain will tell Privacy Badger to always allow loading of resources from the domain.

**Comment by ghostwords** [comment]
I'm going to close this for now. Let me know if you have more information.
