### ISSUE TITLE
breaks google search setting to open new tab immediately on click of search result link

### ISSUE THREAD

**Issue by scottstensland** [EFForg/privacybadger#2181]
firefox nightly 64.0a1 (2018-10-04) (64-bit)
on ubuntu 16.04

I have been using ff nightly for years and your privacybadger for a long time too and its only started failing the other day ... I have google search setting to 

    Where results open
    Open each selected result in a new browser window

which works fine when your addon is disabled ... now when addon enabled 
browser fails to open google search result link in a new tab, now link is opened in same tab
 ... here is such a link

https://www.google.com/search?q=Where+results+open+Open+each+selected+result+in+a+new+browser+window+++fails+to+open+new+tab+or+window&ie=utf-8&oe=utf-8&client=firefox-b-1-ab

**Comment by jleedev** [comment]
It is also causing the "Accessibility help" in the top left corner to become visible, for the same reason.

**Comment by ghostwords** [comment]
Hello and thanks for letting us know! I'm guessing this is an unintended consequence of #2016.

**Comment by ghostwords** [comment]
You can work around this problem for now by disabling Privacy Badger just on Google Search. This will disable outgoing link tracking protection (which appears to cause these side effects) on Google Search.

To do so, click on the "Disable Privacy Badger for This Site" button in Badger's popup while on any `google.com` page.

**Comment by ghostwords** [comment]
Getting a good amount of error reports as well, for example:
>Privacy Badger makes a link that is hidden visible ("accessibility help"). This seems to be a side effect of rewriting the links as it adds focus to a link that is not one I actually added focus to.

>When searching for movies, on the right-hand sidebar where it reveals more info about the movie, the IMDB,  Rotten Tomatoes, and Metacritic scores appear all smushed together. So their layout is collapsing, like some of the CSS is not being applied.

>Clicking search results will not open in new tab

This one is on an event edit screen for Google Calendar (`calendar.google.com`):
> Als ik op een knop wil klikken wordt het niet verwerkt.

**Comment by ghostwords** [comment]
Looks like stripping the `class` attribute creates the various style issues ("accessibility help"/messed up news tab layout), while stripping `target` breaks the "open results in new browser windows" option.

**Comment by ghostwords** [comment]
This is fixed in Privacy Badger version 2018.10.3.1, now live in Firefox and Chrome.
