### ISSUE TITLE
Time.com gets blocked from Europe

### ISSUE THREAD

**Issue by Yoric** [EFForg/privacybadger#2185]
### What is your browser and browser version?
Firefox Nightly 64.0a1 (2018-10-02) (64-bit)

### What is broken and where?
Going to http://time.com from Europe displays a GDPR compliance page. Clicking on "Continue" displays the following error (look at the developer tools in the screenshot for more details).

![](https://webcompat.com/uploads/2018/10/ca34c6b7-ad2a-4709-b0e5-f9f44cf74b82.jpg)

### What is the domain that causes breakage when blocked? What is your debug output for this domain?
```
Please follow the instructions on
https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain
and paste the output here.
```

Sorry, I only saw this instruction after having fixed the issue. Now, some cookie sidesteps the GDPR compliance page, so I can't reproduce anymore.

**Comment by ghostwords** [comment]
Hello and thanks for letting us know!

**Comment by Yoric** [comment]
I forgot to mention: asking Privacy Badger to deactivate itself for time.com solved the issue. Otherwise, I wouldn't have filed this here :)

**Comment by ghostwords** [comment]
This may no longer be an issue. Closing for now.
