### ISSUE TITLE
Break m.youku.com

### ISSUE THREAD

**Issue by ivysrono** [EFForg/privacybadger#2187]
### What is your browser and browser version?
Firefox 62.0.3 x64

### What is broken and where?
https://m.youku.com/video/id_XMzc3MDg3MDIzNg==.html?ishttps=1

### What is the domain that causes breakage when blocked? What is your debug output for this domain?
```
huodong.m.taobao.com
```

**Comment by ghostwords** [comment]
I needed to move `taobao.com` and `gm.mmstat.com` to "yellow" in order to get the video to play.

**Comment by ghostwords** [comment]
Could you provide the [debug information](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) for `taobao.com`?

**Comment by ivysrono** [comment]
youku.com and taobao.com are ali‘s sites.
 in order to get the video to play, I need to move `m.taobao.com` to yellow only, while gm.mmstat.com is red.
