### ISSUE TITLE
break images from gss0.baidu.com 

### ISSUE THREAD

**Issue by ivysrono** [EFForg/privacybadger#2192]
### What is your browser and browser version?
Firefox: 62.0.3
Addon: 2018.10.3.1

### What is broken and where?
All imgs from gss0.baidu.com in any pages, for example:
https://gss0.baidu.com/9vo3dSag_xI4khGko9WTAnF6hhy/zhidao/pic/item/7a899e510fb30f245bf01772c895d143ad4b035c.jpg

**Comment by ghostwords** [comment]
Hello! Could you follow the instructions in https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain and paste the debug information here? I am looking for example pages of where `gss0.baidu.com` gets blocked and also why Privacy Badger decided to block `gss0.baidu.com`.

**Comment by ghostwords** [comment]
Closing for now.
