### ISSUE TITLE
Privacy Badger significantly slows website loading time

### ISSUE THREAD

**Issue by kuba-orlik** [EFForg/privacybadger#2199]
Perhaps that's unavoidable, but recently during some performance benchmarks I've noticed that Privacy Badger adds ~250-300ms delay to asset loading time, negatively impacting my browsing experience. I love the security benefits of Privacy Badger, but I didn't know they come at such a significant performance hit.

I've disabled all other add-ons and measured load times of the same locally-hosted website, and here are the results:

* with Privacy Badger disabled:
    ![image](https://user-images.githubusercontent.com/2697916/47286016-5bdd5f00-d5ed-11e8-9ad4-a1a4c1e4e042.png)

* with Privacy Badger enabled:
    ![image](https://user-images.githubusercontent.com/2697916/47286000-46683500-d5ed-11e8-9a86-1b485c874657.png)

**Comment by ghostwords** [comment]
This might just be the overhead of WebExtensions (network interception probably) APIs in Firefox. Could you compare with other add-ons that block requests? I think I see the same outcome with uBlock Origin, for example. If so, this is indeed a performance issue, but one for [Firefox's Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi#h=dupes%7CWebExtensions).

**Comment by ghostwords** [comment]
Closing for now. Let me know if you have any updates.
