### ISSUE TITLE
Square payment API is blocked

### ISSUE THREAD

**Issue by lacutah** [EFForg/privacybadger#2209]
### What is your browser and browser version?
Firefox 63 64bit

### What is broken and where?
Square payment form javascript is blocked, specifically privacy badger is blocking:
<script type="text/javascript" src="https://js.squareup.com/v2/paymentform"></script>
This script DOES work fine with cookies blocked (yellow setting) but by default it's red.

### What is the domain that causes breakage when blocked? What is your debug output for this domain?
https://test.indianapupandtrainer.org/Store/Checkout

### Other info
To utilize Sqare's API, they REQUIRE us to load the javascript from their website and not self-host it.

**Comment by ghostwords** [comment]
Hello and thanks for the report! Could you provide the [debug output](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) for "squareup"?

**Comment by ghostwords** [comment]
Let me know if you have any questions about the [debug instructions](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) please.

**Comment by lacutah** [comment]
Thanks for bugging me, had problems initially with debugging.

**** ACTION_MAP for squareup.com debugger eval code:3:3
api.squareup.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1540403968395
} debugger eval code:6:36
squareup.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1524221390866
} debugger eval code:6:36
js.squareup.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1541855484335
} debugger eval code:6:36
docs.connect.squareup.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1540611934712
} debugger eval code:6:36
pci-connect.squareup.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1541246777383
} debugger eval code:6:36
**** SNITCH_MAP for squareup.com debugger eval code:9:3
squareup.com [
  "indianapupandtrainer.org",
  "leatherarchives.org",
  "localhost"
]
