### ISSUE TITLE
slashdot.org

### ISSUE THREAD

**Issue by GianniGi** [EFForg/privacybadger#2212]
### What is your browser and browser version?
63.0.1
the previous versions had the same problem

### What is broken and where?

on slashdot.org and on all the subdomains (it, news etc), the site is completely broken (it shows only the text, no color at all)

**Comment by ghostwords** [comment]
Hello! Were you able to follow the [debug instructions](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) to find the domain that breaks the site when blocked, and to get the debug output for that domain?

**Comment by GianniGi** [comment]
The problem arises on slashdot.org and on all the subdomains...

Il giorno mar 6 nov 2018 alle ore 14:16 Alexei <notifications@github.com>
ha scritto:

**Comment by ghostwords** [comment]
Which domains does Privacy Badger block on Slashdot sites for you?

**Comment by GianniGi** [comment]
Yes

**Comment by ghostwords** [comment]
I wasn't yet able to reproduce but I see that other users run into the same problem when their Privacy Badger somehow learns to block "a.fsdn.com". So you should be able to fix this for yourself by toggling "a.fsdn.com" to "green" in Privacy Badger's popup.

Could you run the following JavaScript code in your Privacy Badger's background page console and let us know what it shows?

```javascript
(function () {
  const STR = getBaseDomain("a.fsdn.com");
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging (if it gets shown), and enter the above script into the console after the >>.

**Comment by ghostwords** [comment]
This might be related to #1538.

**Comment by GianniGi** [comment]
**** ACTION_MAP for fsdn.com debugger eval code:3:3
a.fsdn.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1542118021702
} debugger eval code:6:36
fsdn.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
} debugger eval code:6:36
**** SNITCH_MAP for fsdn.com debugger eval code:9:3
fsdn.com [
  "slashdot.org",
  "sourceforge.net",
  "virtuallyfun.com"
] debugger eval code:12:36
undefined

**Comment by GianniGi** [comment]
after running that I removed the fsdn data, but slashdot is still broken

**Comment by ghostwords** [comment]
How did you remove the fsdn data? Did you reload Slashdot afterwards?

I can reproduce breakage when `a.fsdn.com` is blocked. I cannot reproduce breakage otherwise.

**Comment by ghostwords** [comment]
Error report counts by page domain and exact blocked "fsdn.com" subdomain:
```
+----------------------------+--------------+-------+
| fqdn                       | blocked_fqdn | count |
+----------------------------+--------------+-------+
| slashdot.org               | a.fsdn.com   |    97 |
| sourceforge.net            | a.fsdn.com   |    62 |
| news.slashdot.org          | a.fsdn.com   |    14 |
| tech.slashdot.org          | a.fsdn.com   |    10 |
| science.slashdot.org       | a.fsdn.com   |     9 |
| yro.slashdot.org           | a.fsdn.com   |     9 |
| hardware.slashdot.org      | a.fsdn.com   |     6 |
...
```

**Comment by GianniGi** [comment]
I still have the same problem on
https://entertainment.slashdot.org/story/18/11/28/1757205/nike-and-boeing-are-paying-sci-fi-writers-to-predict-their-futures

I had to enable the webdomain
a.fsdn.com

**Comment by ghostwords** [comment]
Yep, that makes sense. We haven't released the fix yet, only finished it, so this won't be fixed automatically for all Badger users until the next release, which should be early next week.
