### ISSUE TITLE
[MDFP] mtvuutiset.fi

### ISSUE THREAD

**Issue by theel0ja** [EFForg/privacybadger#2213]
### What is your browser and browser version?
firefox on windows

### What is broken and where?

mtv.fi is blocked on mtvuutiset.fi (the page i tried to visit), hosted by the same company.

**Comment by ghostwords** [comment]
Hello! Could you provide the [debug output](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) for "mtv.fi"?
