### ISSUE TITLE
Preferences not working on nightly

### ISSUE THREAD

**Issue by CircleCode** [EFForg/privacybadger#2218]
when opening PB preferences, I get a blank page, and the console shows this error:
```
TypeError: backgroundPage is null; can't access its "require" property (options.js:34:5)
```

**Comment by ghostwords** [comment]
Hello! I am unable to reproduce this with Nightly version 65.0a1 (2018-11-21) on Linux. Is this still an issue? Does this happen in a fresh profile with a new Privacy Badger installation? Does this happen with [Privacy Badger installed from source](https://github.com/EFForg/privacybadger/blob/master/doc/develop.md#install-from-source)?

**Comment by ghostwords** [comment]
Let me know if you have any more information. Closing for now.

**Comment by CircleCode** [comment]
@ghostwords does not seem to be reproducible on an empty profile… so seems perfect to close it for now
