### ISSUE TITLE
Yandex Maps broken

### ISSUE THREAD

**Issue by theel0ja** [EFForg/privacybadger#2219]
### What is your browser and browser version?
firefox 63

### What is broken and where?

https://yandex.com/maps/
<img width="418" alt="screen shot 2018-11-25 at 0 18 51" src="https://user-images.githubusercontent.com/5832930/48973432-c730ab80-f047-11e8-8717-8fcb05a1246a.png">

### What is the domain that causes breakage when blocked? What is your debug output for this domain?
```
**** ACTION_MAP for yandex.com debugger eval code:3:3
**** SNITCH_MAP for yandex.com debugger eval code:7:3
undefined
```

**Comment by ghostwords** [comment]
Could you provide the debug output for `yastatic.net`? Sorry for the misunderstanding; I wonder how we could make this more clear in the [instructions](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain).
