### ISSUE TITLE
Blocked submitting form to act.coworker.org

### ISSUE THREAD

**Issue by kaganjd** [EFForg/privacybadger#2221]
### What is your browser and browser version?
Chrome Version 70.0.3538.77

### What is broken and where?
Can't POST to act.coworker.org from a form on the homepage (form is currently only in Staging)

### What is the domain that causes breakage when blocked? What is your debug output for this domain?
act.coworker.org

```
**** ACTION_MAP for coworker.org
VM244:5 about.coworker.org {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1540388906802,
  "userAction": ""
}
VM244:5 coworker.org {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
VM244:5 home.coworker.org {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1531890711947,
  "userAction": ""
}
VM244:5 www.coworker.org {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1534835366752,
  "userAction": ""
}
VM244:5 act.coworker.org {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1543654357993
}
VM244:7 **** SNITCH_MAP for coworker.org
VM244:9 coworker.org [
  "wpengine.com",
  "mycoworker.org",
  "wework.com"
]
```

**Comment by ghostwords** [comment]
Hello! I'm having trouble finding examples of this form ... Do you have any besides the one that's staging-only? I'm also looking for any other example pages that embed `coworker.org` resources.

**Comment by kaganjd** [comment]
http://coworker.staging.wpengine.com/

I assumed it was the act. part, but maybe that's wrong- maybe it is the WP Engine hosting? Here's another page that's hosted by ActionKit: https://act.colorofchange.org/signup/signup/ Our form is basically that one, embedded within a Wordpress site hosted by WP Engine.

**Comment by ghostwords** [comment]
I haven't been able to get Privacy Badger to learn to block `coworker.org` (such as by seeing tracking from `home.coworker.org` resources, which is what happened to your Privacy Badger). I also don't have any other reports of problems with `coworker.org`. The form on ColorOfChange.org submits to the same (first-party) domain, so it wouldn't run into issues with Privacy Badger.

I think we can address problems of this sort by always allowing form submissions initiated by the user (previously: https://github.com/EFForg/privacybadger/issues/1539#issuecomment-319235313). This is related to #137 and OAuth flow detection. For example, [in Ghostery](https://github.com/cliqz-oss/browser-core/blob/455c180688de4c188489edcc953d5b419de76f3a/modules/antitracking/sources/steps/oauth-detector.es#L127-L136), a request is part of an OAuth flow if the request's URL contains "/oauth", the user recently visited the request's (?) domain, and the user recently clicked in the tab. We probably want to implement some version of this to fix OAuth breakages in Privacy Badger. We should probably also reuse the same infrastructure to always allow form submissions. Something like, "a request is a user-initiated form submission if its domain matches the action domain of a form the user just clicked on the page".

These are just some thoughts though, I am not sure what's going to happen and when. I suggest telling your Badger to forget about  `coworker.org` domains (by Xing them out under the Tracking Domains tab on Privacy Badger's options page), and then seeing if the problem crops up again.

**Comment by kaganjd** [comment]
thanks for digging into this
