### ISSUE TITLE
rxlist.com: Cannot search

### ISSUE THREAD

**Issue by davidhedlund** [EFForg/privacybadger#2224]
### What is your browser and browser version?
Firefox ESR 60.3.0esr (64-bit) binary

### What is broken and where?
PrivacyBadger prevents the search button on rxlist.com to display the search field showed on the screenshot.

![screenshot at 2018-11-27 05 38 56](https://user-images.githubusercontent.com/6416073/49058964-c4c88000-f206-11e8-964b-b55f7065936f.png)

### What is the domain that causes breakage when blocked? What is your debug output for this domain?
rxlist.com

**Comment by ghostwords** [comment]
I think the search is powered by `webmd.com`. Does setting some (or all) of the `webmd.com` domains to "yellow" work around the breakage?

**Comment by davidhedlund** [comment]
Thanks in advance.
