### ISSUE TITLE
webRequest header access changes in Chrome 72

### ISSUE THREAD

**Issue by clarkduvall** [EFForg/privacybadger#2235]
It looks like Privacy Badger is accessing and modifying headers that will not be available by default in Chrome 72 (currently on the dev channel). These include:

Request headers:
- Accept-Language
- Accept-Encoding
- Cookie
- Referer

Response headers:
- Set-Cookie

To access these headers you will need to add 'extraHeaders' in the extraInfoSpec of the relevant webRequest listeners.

See the post on the chromium-extensions Google Group for more info: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/vYIaeezZwfQ

**Comment by ghostwords** [comment]
Hi @clarkduvall Privacy Badger users may be running into Chrome 72 browser crashes after our `extraHeaders` release last night: #2249.
