### ISSUE TITLE
Suggestion: Alert feature

### ISSUE THREAD

**Issue by clfaulkner** [EFForg/privacybadger#2237]
Often I get moving quickly from site to site and forget to look up at my address bar to see Badger's status report. Would it be possible to add a feature that throws am alert when a site has red items?

Thanks for considering this.

**Comment by ghostwords** [comment]
Hello! Did you have any particular implementation in mind (such as Ghostery's purple box)?

**Comment by clfaulkner** [comment]
No, just something to get me to pay more attention.

Thanks for looking into this.

**Comment by ghostwords** [comment]
Since we work towards making Privacy Badger more and more of an "install and forget" tool, we are not likely to work on this any time soon.
