### ISSUE TITLE
Breaks Spotify player embeds

### ISSUE THREAD

**Issue by davidhedlund** [EFForg/privacybadger#2254]
#### What is your browser and browser version?
Firefox ESR: 60.4.0esr (64-bit) GNU/Linux binary

#### What is broken and where?
http://mendelkaelen.com/experience.html

These elements
> <iframe src="https://open.spotify.com/embed/user/kybtarhq4n84xiyacpbuapck4/playlist/

example:

> <iframe src="https://open.spotify.com/embed/user/kybtarhq4n84xiyacpbuapck4/playlist/2mT6LpOU4ipJ0BkoCigAiw" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>

#### What is the "culprit" domain?
https://open.spotify.com/embed/

**Comment by ghostwords** [comment]
Thanks for the report!
