### ISSUE TITLE
Ticket purchase via Ticketbutler.io iframe blocked

### ISSUE THREAD

**Issue by benjaoming** [EFForg/privacybadger#2258]
#### What is your browser and browser version?

Thanks for protecting my privacy!

Am using Firefox 64

#### What is broken and where?

The iframe from djangocon.ticketbutler.io is blocked

#### What is the "culprit" domain?

`djangocon.ticketbutler.io`

#### What is your debug output for this domain?

We just opened ticket sales from DjangoCon Europe. The widget wasn't originally blocked but seemed to get picked up and blocked only hours after the announcement.

https://2019.djangocon.eu/tickets/

Note: We might have a solution presented on the above page. Meanwhile, here's also a screenshot in case you navigate to the page in a few days and find we have done a workaround:

![image](https://user-images.githubusercontent.com/374612/50567885-94668b00-0d4a-11e9-96c5-6d9752d2c17b.png)

Tracking from: https://github.com/djangocon/2019.djangocon.eu/issues/40

**Comment by ghostwords** [comment]
Hello! Sorry for not responding earlier. Could you post your (or whoever's Privacy Badger learned to block `ticketbutler.io`) [debug output](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) for "djangocon.ticketbutler.io"?

It looks like Privacy Badger sees a "csrftoken" cookie as well as a "google_experiment_mod" localStorage entry from `djangocon.ticketbutler.io` resources, which Privacy Badger considers to be tracking.

**Comment by ghostwords** [comment]
If Ticketbutler doesn't actually mean to track users through its embedded frames, it may be a good match for [EFF's Do Not Track policy](https://www.eff.org/dnt-policy). If they are willing and able to abide by the policy's requirements on the affected domains, posting the policy on each domain will tell Privacy Badger to always allow loading of resources from the domain.

**Comment by benjaoming** [comment]
Thanks for digging into this @ghostwords - pinging @emilkjer that maybe the Ticketbutler iframe can either adapt a DnT setup, or otherwise I think it's fine to close the issue and conclude that Privacy Badger works as intended.

**Comment by benjaoming** [comment]
This is an issue with the provider, I will close this, thanks for clarifying the problem @ghostwords !
