### ISSUE TITLE
Allow blocking of arbitrary domains in the "Tracking Domains" tab

### ISSUE THREAD

**Issue by bcyphers** [EFForg/privacybadger#2259]
If I think "malicious.com" is a tracker, but Privacy Badger does not, right now there's no way for me to preemptively block all content from malicious.com. This can be an issue when a tracking site serves all its content from subdomains and sub*domains, so that the user has a chance to set sliders for "x.malicious.com" but never the TLD+1.

We could add a text box under the search bar, or integrate this feature into the search bar itself.

Thoughts? I think some people would find this useful, especially for sites that use tracking techniques Privacy Badger can't identify yet.

**Comment by ghostwords** [comment]
This might be a "wontfix", as per https://github.com/EFForg/privacybadger/issues/2248#issuecomment-448408143 ...

**Comment by bcyphers** [comment]
I don't see this as necessarily the same. This would be a feature hidden behind a couple of dialogs that dedicated users can use to fill in the gaps, not fundamentally change what Privacy Badger does. For example, you could use this to block Google Analytics (or equivalent) while we figure out the best way to update our heuristics around it. Or you could use this to block a sketchy site that you know to be doing audio fingerprinting.

I don't think many people would use it, but for those who want to, it would be frustrating to have to install a whole new tool to block a specific site.

**Comment by EnderClan** [comment]
Seems like a good idea considering Privacy Badger "learns". Being able to add your own data for it to work off of would be useful especially for links that redirect you too fast.
