### ISSUE TITLE
[Feature] Support Pale Moon

### ISSUE THREAD

**Issue by gjhklfdsa** [EFForg/privacybadger#2263]
**Description**: Add Official Extension for [Pale Moon](https://addons.palemoon.org/)

**Comment by ghostwords** [comment]
According to https://www.palemoon.org/roadmap.shtml, Pale Moon neither supports nor plans on supporting WebExtensions. I don't think it makes sense for the Privacy Badger core team to dedicate time to building a custom extension just for Pale Moon, sorry. I suggest installing uBlock Origin instead, if it's still available for Pale Moon.
