### ISSUE TITLE
Breaking CodeSandbox

### ISSUE THREAD

**Issue by CompuIves** [EFForg/privacybadger#2277]
#### What is your browser and browser version?
Firefox 65.0

#### What is broken and where?
The preview of CodeSandbox doesn't work.

#### What is the "culprit" domain?
CodeSandbox hosts user projects on their subdomain (eg. new.codesandbox.io), it seems like this domain is blocked by Privacy Badger, which causes the preview to break.

CodeSandbox is often embedded in other websites. We do follow DNT though, we don't track any data if we detect that `navigator.doNotTrack` is `"1"`.

#### What is your debug output for this domain?
```
**** ACTION_MAP for codesandbox.io
codesandbox.io {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1549235919173
}
**** SNITCH_MAP for codesandbox.io
codesandbox.io [
  "reach.tech"
]
```

Related issue: https://github.com/CompuIves/codesandbox-client/issues/1335

**Comment by ghostwords** [comment]
Hello! Looking at the following two examples, Privacy Badger sees localStorage tracking from `q76x8x3046.codesandbox.io` and `wjrn8wy3r.codesandbox.io` (key `"__test__"` set to `"\ud800"`):
- https://react-table.js.org/#/story/server-side-data
- https://lossendae.github.io/vue-table/examples/#simple-table

**Comment by ghostwords** [comment]
If `codesandbox.io` don't actually mean to track users and are in fact compliant with [EFF's Do Not Track policy](https://www.eff.org/dnt-policy), you could post the policy on each compliant domain, which will tell Privacy Badger to always allow loading of resources from that domain.

**Comment by ghostwords** [comment]
Closing for now, let me know if you have any questions.
