### ISSUE TITLE
Permission error to push branch and pull request

### ISSUE THREAD

**Issue by adyrcz** [EFForg/privacybadger#2278]
I am attempting to submit a pull request to add domains to the MDFP list.
When attempting to `git push origin branch` I get the following.  Am I doing something wrong?

```$ git push origin linkfiretld-mdfp
ERROR: Permission to EFForg/privacybadger.git denied to adyrcz.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

**Comment by ghostwords** [comment]
Hello! I think what you want to do is [make a pull request from a fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/). Let me know if you have any questions/issues with that.
