### ISSUE TITLE
MDFP Issue: Static Content domains are being blocked linkstorage & st .linkfire.com

### ISSUE THREAD

**Issue by adyrcz** [EFForg/privacybadger#2288]
#### What is your browser and browser version?
Chrome Version 71.0.3578.98
#### What is broken and where?
When visiting lnk.to domains, our static content domains are being blocked.  linkfire.com

#### What is the "culprit" domain?
I'd like to open this issue as a MDFP issue, as I can tell its our first party domain that is getting blocked.  

The following are the 2 culprit domains
linkstorage.linkfire.com
st.linkfire.com

#### What is your debug output for this domain?
To get the debug output, please see the instructions link above.
```
**** ACTION_MAP for linkfire.com
authentication-beta-internal-api.linkfire.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1540168498572,
  "userAction": ""
}
authentication-internal-api.linkfire.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1548111122929,
  "userAction": ""
}
authentication-test-internal-api.linkfire.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1540653290737,
  "userAction": ""
}
build.linkfire.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1541031264780,
  "userAction": ""
}
druid-test-broker.linkfire.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1541645220712,
  "userAction": ""
}
frontpagegui.linkfire.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549020940027,
  "userAction": ""
}
guibeta.linkfire.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1540864945281,
  "userAction": ""
}
guiproduction.linkfire.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1540642552036,
  "userAction": ""
}
guitest.linkfire.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1540922134163,
  "userAction": ""
}
help.linkfire.com {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1545233682181,
  "userAction": ""
}
linkfire.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1530134460761,
  "userAction": ""
}
linkstorage.linkfire.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549621584967,
  "userAction": ""
}
services.linkfire.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1532022582670,
  "userAction": ""
}
st.linkfire.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1549329542518,
  "userAction": ""
}
styleguide.linkfire.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542022015280,
  "userAction": "user_allow"
}
**** SNITCH_MAP for linkfire.com
linkfire.com [
  "lnk.to",
  "zendesk.com",
  "strm.to"
]
```

**Comment by ghostwords** [comment]
Hello! You have to make a pull request from a fork instead (previously: #2278). I wonder if we should add this info to our [developer guide](https://github.com/EFForg/privacybadger/blob/master/doc/develop.md).

**Comment by ghostwords** [comment]
Could you provide a few (three would be great) examples of pages from different sites that run into this problem? I'd like to see why Privacy Badger learns to block `linkfire.com` domains.

**Comment by adyrcz** [comment]
https://demo.lnk.to/qxdnnh6g
https://arianagrande.lnk.to/sweetener
https://tix.to/MiriamRgiraIN
https://drake.lnk.to/SHGodsPlan

**Comment by adyrcz** [comment]
corrected issues in PR https://github.com/EFForg/privacybadger/pull/2289

**Comment by ghostwords** [comment]
Ah I see, I can reproduce if I visit linkfire.com first.

This is another set of broken sites caused by Badger not auto-learning to block Google Analytics (#367). When you visit linkfire.com directly, GA sets a first-party cookie, which is then sent in seemingly third-party situations. Updating the MDFP list will help Badger treat `linkfire.com` resources as first-party on `lnk.to` URLs, and fixing #367 will eliminate this entire type of problem in the future.
