### ISSUE TITLE
Official DNT policy has trailing whitespace

### ISSUE THREAD

**Issue by bcyphers** [EFForg/privacybadger#2291]
The reference policy at src/data/dnt-policy.txt has trailing whitespace after several of the lines. 
e.g.
![trailing-whitespace-dnt](https://user-images.githubusercontent.com/4840035/52440209-57707f80-2ad2-11e9-8429-b5fcac712826.png)

This makes it easy for other DNT policies that *look* identical to fail hash matching against our own. For example, the policy at https://scroll.com/.well-known/dnt-policy.txt has had the trailing whitespace stripped and fails to match.

We should probably (1) strip the trailing whitespace from the reference files and update the reference hashes in src/data/dnt-policies.json and (2) strip whitespace from newly-discovered DNT policy files before running the hash match.

**Comment by ghostwords** [comment]
Places the policy is referenced:
- The (copy-and-pasteable) text on https://www.eff.org/dnt-policy (contains the same trailing whitespace)
- Hotlinked to https://github.com/EFForg/dnt-policy as https://raw.githubusercontent.com/EFForg/dnt-policy/master/dnt-policy-1.0.txt
    - https://github.com/EFForg/dnt-policy/blob/master/dnt-policies.json
    - https://github.com/EFForg/dnt-policy/blob/master/dnt-policy-1.0.txt
- Hardcoded into `dntscan/main.py`
- Bundled with Privacy Badger:
   - https://github.com/EFForg/privacybadger/blob/master/src/data/dnt-policies.json
   - https://github.com/EFForg/privacybadger/blob/master/src/data/dnt-policy.txt
- Remote update endpoint at https://www.eff.org/files/dnt-policies.json

Anywhere else?

**Comment by ghostwords** [comment]
Places the matching happens:
- Privacy Badger
- `dntscan/main.py`
- third-party implementations?

**Comment by ghostwords** [comment]
I'd rather not complicate the matching in any way. I'm OK with updating the 1.0 policy (should we increment the version number?) and add a new acceptable hash to the hashes JSON.

One risk though is that we haven't updated the hashes JSON before, so this is uncharted waters. If we go ahead with this, we should manually test all the moving pieces before making any changes live.

**Comment by ghostwords** [comment]
The 1.0-without-trailing-spaces hash should be `5b8972a0e8df8236bb28061ddc462767d4366218`.

**Comment by ghostwords** [comment]
I added [two new DNT hashes](https://github.com/EFForg/privacybadger/issues/2291#issuecomment-462407763) to the [various places the hashes are used/hosted](https://github.com/EFForg/privacybadger/issues/2291#issuecomment-462404504).

I think we can close this for now and revisit as new issues arise.

**Comment by ghostwords** [comment]
Adding another variant for https://github.com/EFForg/privacybadger/pull/2649#issuecomment-659054174:

1.0-no-eof-newline: `7861462d500fbb6ccb74c614782f4937377bec76`
