### ISSUE TITLE
static.ratemyagent.com.au blocked on .com & .co.nz sites (OK on .com.au site)

### ISSUE THREAD

**Issue by AirEssY** [EFForg/privacybadger#2292]
Hey was after some help/guidance on why our static content is getting blocked by privacybadger on some of our sites. Thanks in advance!

#### What is your browser and browser version?
Google Chrome - Version 72.0.3626.81 (Official Build) (64-bit)
Privacy Badger - Version 2019.1.30

#### What is broken and where?
The static images served from our cloudfront domain (static.ratemyagent.com.au) get blocked when you visit one of our non-au sites.
https://www.ratemyagent.com/
https://www.ratemyagent.co.nz/

(however https://www.ratemyagent.com.au/ works fine)

#### What is the "culprit" domain?
https://static.ratemyagent.com.au
e.g. https://static.ratemyagent.com.au/assets/images/home/confident.png

#### What is your debug output for this domain?
To get the debug output, please see the instructions link above.
```
**** ACTION_MAP for ratemyagent.com.au
ratemyagent.com.au {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
static.ratemyagent.com.au {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1550152505107,
  "userAction": ""
}
devapi.ratemyagent.com.au {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1550459826471
}
**** SNITCH_MAP for ratemyagent.com.au
ratemyagent.com.au [
  "ratemyagent.com",
  "localhost",
  "ratemyagent.co.nz"
]
```

**Comment by ghostwords** [comment]
Hello! Sure, what happens is that when you visit https://www.ratemyagent.com.au/, you get a bunch of cookies set on the base domain (`.ratemyagent.com.au`). Looks like some of them are from Google Analytics, not sure if all of them are. Then, when you visit one of your international sites, Privacy Badger sees those cookies (for example, "_vwo_uuid_v2") being sent along with requests for `static.ratemyagent.com.au` resources and considers that tracking.

You can avoid this by using a dedicated, cookie-less domain for your static resources, or by posting the [EFF Do Not Track policy](https://www.eff.org/dnt-policy) on the `static.ratemyagent.com.au` domain (assuming the domain is in fact compliant with EFF's DNT). Posting the policy on the domain will tell Privacy Badgers to always allow loading of resources from that domain.

**Comment by ghostwords** [comment]
Let me know how the above sounds.

**Comment by ghostwords** [comment]
Resolving for now. Let me know if there is anything else I can help with.
