### ISSUE TITLE
Two Privacy Badgers appearing in Firefox 65 w/ Firefox Sync.

### ISSUE THREAD

**Issue by rogerharkavy** [EFForg/privacybadger#2297]
I am running Firefox 65 with Privacy Badger on multiple machines and use Firefox Sync.

Yesterday, on a Linux machine, I set up Firefox and connected it with Firefox Sync. I noticed that PB was not listed in the add-ons there, so I added it manually.

Today, when I use Firefox on my Windows machine, the PB welcome page appeared, and there are two PB buttons on the toolbar. When I check the Add-ons manager, it is listed there twice.

Attached is a screen shot.

![privacybadgerx2](https://user-images.githubusercontent.com/31863155/52723765-1c5fc780-2f7c-11e9-8c87-6a42b725dd58.png)

**Comment by ghostwords** [comment]
Hello!

You can install Privacy Badger from [eff.org/pb](https://www.eff.org/privacybadger), or from [AMO (addons.mozilla.org)](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/). Both instances of Privacy Badger are published by the EFF. Both should always offer the same functionality. However, they happen to be distinct extensions. Although you could have both installed, there is no reason to do so.

I see that it's easy to run into scenario using Firefox Sync. Sorry for the confusion! I know this isn't intuitive. I would just pick one of them to keep and remove the other one. You can see which is which by clicking on the extension name. The one installed from AMO will have more information (such as the star rating) shown than the other.

Previously: #1979.
