### ISSUE TITLE
"video unavailable" for some embedded youtube videos

### ISSUE THREAD

**Issue by danadam** [EFForg/privacybadger#2305]
#### What is your browser and browser version?
Firefox 65.0.1

#### What is broken and where?
Many (but not all) embedded youtube videos (e.g. on forums) show "video unavailable". Here's an example: http://danadam.pl/tmp/privacy.badger.youtube.embedded.html . The first video shows "Video unavailable", the second plays fine. After changing the Privacy Badger slider for "www.youtube.com" from yellow to green both videos play fine.

#### What is the "culprit" domain?
www.youtube.com

#### What is your debug output for this domain?
```
**** ACTION_MAP for youtube.com
youtube.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
www.youtube.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1550702514544
}
**** SNITCH_MAP for youtube.com
youtube.com [
  "google.com",
  "mozilla.org",
  "nih.gov",
  "audiosciencereview.com"
]
```

**Comment by ghostwords** [comment]
Hello! [This](https://github.com/EFForg/privacybadger/issues/188#issuecomment-461234283) might be the same sort of problem as the one with [private Vimeo videos](https://github.com/EFForg/privacybadger/issues/188#issuecomment-44871253). In which case the solution might be to add a replacement widget for YouTube (#2280) and remove YouTube domains from the yellowlist. We want to be sure our widget is good enough first since embedded YouTube videos are everywhere (while only some of them run into this bug).

**Comment by quezak** [comment]
I'm also experiencing this. Indeed, not all videos are unavailable, even on the same page -- maybe it depends on embed settings, or video parameters (maybe its monetization settings?)

Example going through a music reviews site:
 * here embeds show "video unavailable": http://everythingisnoise.net/reviews/hexvessel-all-tree/
 * here embeds work normally: http://everythingisnoise.net/reviews/saor-forgotten-paths/

**Comment by bcyphers** [comment]
I have been noticing this more and more recently; Youtube might be pushing out this feature more aggressively. It should definitely be fixed by #2280.

**Comment by SteveALee** [comment]
I've also been having this a lot recently and spent ages on it as assumed it was YouTube or a locally hosted problem. At least moving the slider works for me too! Phew.

**Comment by ghostwords** [comment]
Counts of reports that mention "video" in the message and cookieblock a "youtube" domain grouped by month and exact blocked "akamaihd" subdomain:
```
...
| 2019-05 | www.youtube.com          |    38 |
| 2019-05 | fcmatch.youtube.com      |     5 |
| 2019-04 | www.youtube.com          |    30 |
| 2019-04 | fcmatch.youtube.com      |     3 |
| 2019-04 | img.youtube.com          |     3 |
| 2019-03 | www.youtube.com          |    49 |
| 2019-03 | fcmatch.youtube.com      |     3 |
| 2019-03 | www.youtube-nocookie.com |     1 |
| 2019-02 | www.youtube.com          |    30 |
| 2019-02 | img.youtube.com          |     2 |
| 2019-02 | fcmatch.youtube.com      |     1 |
| 2019-02 | gaming.youtube.com       |     1 |
| 2019-02 | www.youtube-nocookie.com |     1 |
| 2019-01 | www.youtube.com          |    36 |
| 2019-01 | www.youtube-nocookie.com |     2 |
| 2019-01 | fcmatch.youtube.com      |     1 |
| 2019-01 | img.youtube.com          |     1 |
| 2019-01 | youtube.googleapis.com   |     1 |
| 2018-12 | www.youtube.com          |    35 |
| 2018-12 | img.youtube.com          |     2 |
| 2018-11 | www.youtube.com          |    49 |
| 2018-11 | img.youtube.com          |     3 |
| 2018-10 | www.youtube.com          |    43 |
| 2018-10 | img.youtube.com          |     2 |
| 2018-09 | www.youtube.com          |    35 |
| 2018-09 | fcmatch.youtube.com      |     5 |
| 2018-09 | img.youtube.com          |     2 |
| 2018-08 | www.youtube.com          |    28 |
| 2018-08 | img.youtube.com          |     2 |
| 2018-08 | fcmatch.youtube.com      |     1 |
| 2018-08 | youtube.com              |     1 |
...
```

**Comment by markfilan** [comment]
There are several issues causing this problem. A few of the reasons why you might get such error include:

- There is a possibility that the video violates YouTube policy.
- The cache got corrupted and needs to be cleared.
- There may be a reason for the poor quality of the video.
- There may be an issue with the internet speed.

You can try out some options to avoid such situations of non-availability of your favorite videos. A few recommended options include:

- Try to reinstall your web browser.
- You can try a different browser to play the desired [youtube](http://net-informations.com/q/mis/youtube.html) video.
- Enable Flash and JavaScript.
- Deleting Cookies
- Update GPU drivers.
