### ISSUE TITLE
Breaks geoportail.gouv.fr

### ISSUE THREAD

**Issue by Yvan-Masson** [EFForg/privacybadger#2308]
Hi,

By default Privacy Badger blocks wxs.ign.fr. However, it is needed on geoportail.gouv.fr (official French government map website) to display the topographic map (which is probably the most viewed map on this website). Cookies from this domain do not seem to be needed.

You can check directly using this URL for example: https://www.geoportail.gouv.fr/carte?c=4.4709261518597945,45.60137119690336&z=15&l0=GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN25TOUR.CV::GEOPORTAIL:OGC:WMTS(1)&permalink=yes

It is possible that others maps are affected on this website but I did not check.

Regards,
Yvan

**Comment by ghostwords** [comment]
Hello! Could you share the debug output for "wxs.ign.fr" as per https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain?

**Comment by ghostwords** [comment]
@Yvan-Masson Would you agree that `ign.fr` and `geoportail.gouv.fr` are "first party" to each other? That is, they belong to the same entity.

**Comment by Yvan-Masson** [comment]
@ghostwords Yes, I suppose we can consider it is the same entity. Here is the relevant part of the Wikipedia definition: 

> IGN is a French public state administrative establishment

Regards,
Yvan
