### ISSUE TITLE
Disable first run page

### ISSUE THREAD

**Issue by juju4** [EFForg/privacybadger#2309]
is there an option to disable first run welcome+configuration page when installing privacy badger?
like https://issues.adblockplus.org/ticket/206

for example, when using a VM/container template.
either through a dedicated file or through prefs.js, can we set up settings in advance.

**Comment by ghostwords** [comment]
Yep! Please see the [admin deployment document](https://github.com/EFForg/privacybadger/blob/master/doc/admin-deployment.md) for details. Let me know if you have any questions about it.

**Comment by juju4** [comment]
Thanks!
