### ISSUE TITLE
Facebook first-party script should also run on messenger.com

### ISSUE THREAD

**Issue by mgziminsky** [EFForg/privacybadger#2316]
Just had this opened in my extension the other day, figured you would want to do the same.

See: https://github.com/mgziminsky/FacebookTrackingRemoval/issues/27 and https://github.com/mgziminsky/FacebookTrackingRemoval/commit/36eefd76a457864c580b8d63157b90c54f3935d2

**Comment by bcyphers** [comment]
Thanks! Yup, adding this to the to-do list.

**Comment by jalcine** [comment]
LGTM!

(Originally published at: https://v2.jacky.wtf/post/ba2c909f-236f-4207-ac67-355500a29378)
