### ISSUE TITLE
How to Build a crx file from tar.gz file for chrome browser.

### ISSUE THREAD

**Issue by laokong911** [EFForg/privacybadger#2319]
As a newbie , I dont know how to make a crx file ,but my ungoogle chrome can not download , please help me build a crx file manually ! thanks ,god bless you.

**Comment by pipboy96** [comment]
I can't find this information either.

**Comment by ghostwords** [comment]
Hello! We use [Chrome (Chromium) to build the CRX3 package for Privacy Badger](https://github.com/EFForg/privacybadger/blob/bb5c85d4c5fcc952f6caa7b2ae9160f1cbcbeee6/release-utils/chromium-release.sh#L23). There are now also third-party tools for creating CRX3 packages, for example: https://github.com/pawliczka/CRX3-Creator.

I suggest using the [Chromium Extensions Google group](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-extensions) for any non-Privacy Badger-specific Chrome extensions questions.
