### ISSUE TITLE
videos stored on apa.at-servers do not load/play (as soon as embedded in other sites like orf.at)

### ISSUE THREAD

**Issue by DJCrashdummy** [EFForg/privacybadger#2321]
#### What is your browser and browser version?
Firefox 65.0.1 (64-Bit)

#### What is broken and where?
every embedded video in articles at orf.at do not load/play.
e.g. https://orf.at/stories/3113226/

#### What is/are the "culprit" domain(s)?
apasfiis.sf.apa.at
varorfvod.sf.apa.at

#### What is your debug output for this domain?

<details>
<summary>apasfiis.sf.apa.at & varorfvod.sf.apa.at</summary>

```
**** ACTION_MAP for apa.at
apasfiis.sf.apa.at {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1551390411596
}
apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
apasfiisl.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1551422922246
}
apasfoe24l.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1549558254056
}
vs-pd10.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1540703741640
}
uvp-test.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1540499868182
}
uvp.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1540641290900
}
mp3stream7.apasf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542061140193
}
uvp-heuteat.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549061851323
}
apasfpd.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542148972389
}
www.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542823680987
}
apasense01.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542767628087
}
uvp-profil.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542650003261
}
uvp-kleinezeitung.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1543277097652
}
uvp-vg-news.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549602417749
}
oe24.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549899281525
}
vs-pd-oe24.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549943111084
}
varorfvod.sf.apa.at {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1551778477963
}
**** SNITCH_MAP for apa.at
apa.at [
  "orf.at",
  "oklivetv.com",
  "oe24.at"
]
```

</details>

**Comment by bcyphers** [comment]
Since orf.at and apa.at are owned by the same company, this looks like a job for the multi-domain first party list. Do you have other examples of sites owned by either APA or ORF?

**Comment by DJCrashdummy** [comment]
general explanation:
the APA (= Austria Press Agency) is owned by the ORF (= Austrian Broadcasting Corporation) and a bunch of austrian newspapers (listed at https://de.wikipedia.org/wiki/Austria_Presse_Agentur#Genossenschafter).

they use the apa-servers to save and exchange their content resp. especially videos.

---

i've looked a little bit around and found at least 2 other domains (owned by the apa) with the "same" problem:

## apa-defacto.at
#### What is broken and where?
all videos (and thumbnails) at http://www.apa-defacto.at/Site/Videos.de.html

#### What is/are the "culprit" domain(s)?
kf-apa-at.sf.apa.at (thumbnails)
uvp.sf.apa.at (video-player)
apa-at.sf.apa.at (video)

#### What is your debug output for this domain?

<details>
<summary>kf-apa-at.sf.apa.at & uvp.sf.apa.at & apa-at.sf.apa.at</summary>

```
**** ACTION_MAP for apa.at
apasfiis.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1551390411596
}
apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
apasfiisl.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1551422922246
}
apasfoe24l.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1549558254056
}
vs-pd10.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1540703741640
}
uvp-test.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1540499868182
}
uvp.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1551874258835
}
mp3stream7.apasf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542061140193
}
uvp-heuteat.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549061851323
}
apasfpd.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542148972389
}
www.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1552138549192
}
apasense01.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542767628087
}
uvp-profil.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542650003261
}
uvp-kleinezeitung.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1543277097652
}
uvp-vg-news.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549602417749
}
oe24.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549899281525
}
vs-pd-oe24.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549943111084
}
apa-at.sf.apa.at {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1552080736196
}
kf-apa-at.sf.apa.at {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1551999767622
}
uvp.sf.apa.at {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1552140756632
}
**** SNITCH_MAP for apa.at
apa.at [
  "orf.at",
  "oklivetv.com",
  "oe24.at"
]
```

</details>

## apa-it.at
#### What is broken and where?
all videos (and thumbnails) at https://www.apa-it.at/Site/DMB/Quellen.de.html and https://www.apa-it.at/Site/DMB/Video.de.html

#### What is/are the "culprit" domain(s)?
kf-apa-at.sf.apa.at (thumbnails)
uvp.apa.at (video-player)
apa-at.sf.apa.at (video)
*yes, just the (sub)domain for the player is different!*

#### What is your debug output for this domain?

<details>
<summary>kf-apa-at.sf.apa.at & uvp.apa.at & apa-at.sf.apa.at</summary>

```
**** ACTION_MAP for apa.at
apasfiis.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1551390411596
}
apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
apasfiisl.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1551422922246
}
apasfoe24l.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1549558254056
}
vs-pd10.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1540703741640
}
uvp-test.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1540499868182
}
uvp.apa.at {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1551874258835
}
mp3stream7.apasf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542061140193
}
uvp-heuteat.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549061851323
}
apasfpd.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542148972389
}
www.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1552138549192
}
apasense01.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542767628087
}
uvp-profil.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1542650003261
}
uvp-kleinezeitung.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1543277097652
}
uvp-vg-news.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549602417749
}
oe24.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549899281525
}
vs-pd-oe24.sf.apa.at {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1549943111084
}
kf-apa-at.sf.apa.at {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1551979449878
}
apa-at.sf.apa.at {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1552247775236
}
**** SNITCH_MAP for apa.at
apa.at [
  "orf.at",
  "oklivetv.com",
  "oe24.at"
]
```

</details>

---

i'm not sure if it helps, but i've looked at Privacy Badger for several other apa-domains... i've no idea what domain is used for what purpose but FWIW

<details>
<summary>apa.at-domains i came across (so far):</summary>

```
apa.at
apasense01.apa.at
mp3stream7.apasf.apa.at
apasfiisl.apa.at
apasfiis.sf.apa.at
apasfoe24l.sf.apa.at
apasfpd.sf.apa.at
oe24.sf.apa.at
uvp-heuteat.sf.apa.at
uvp-kleinezeitung.sf.apa.at
uvp-profil.sf.apa.at
uvp-test.sf.apa.at
uvp-vg-news.sf.apa.at
vs-pd-oe24.sf.apa.at
vs-pd10.sf.apa.at
www.apa.at
```
</details>

**Comment by bcyphers** [comment]
Thanks @DJCrashdummy. I'll put together a pull request for this.

**Comment by bcyphers** [comment]
This case is kind of odd because it looks like APA is a cooperative venture jointly owned by the ORF (Austria's largest media company) and about a dozen other media and newspaper companies. In turn, the APA controls all or part of several other organizations, including https://www.dpa-digitalservices.com/, https://www.keystone-sda.ch/, and http://www.epa.eu/. Following the chain of ownership it seems like this MDFP list would grow to consume all media companies in Europe. I'll create a small MDFP entry for now to address this problem, then we can expand on it in the future if more issues pop up.

**Comment by DJCrashdummy** [comment]
i can confirm a more or less direct connection to https://www.dpa-digitalservices.com/ (a subsidiary of the *German Press Agency* together with the *Austria Press Agency*) and also somehow to http://www.epa.eu/ (EPA = *European Press Agency*) as a shareholder of it...
but i doubt a serious connection relating to this topic to other european press agencies - like https://www.keystone-sda.ch/ - because they are all also just shareholders of the EPA. before tieing them together you must e.g. rather do so for [all microsoft brands](https://www.allbrands.markets/brand/price-share-stock-market-microsoft-20350082400-us5949181045/other-brands-microsoft/) and there associated domains and probably also for [facebook](https://www.allbrands.markets/brand/price-share-stock-market-facebook-21287398100-us30303m1027/other-brands-facebook/) etc.

...so IMHO i would just tie the APA and the austrian newspapers/broadcaster together (like you did :+1:) and wait for other issues to occur, which i doubt.

**Comment by DJCrashdummy** [comment]
:confused: strange: today i noticed some videos on `orf.at` not playing again. i had a look at privacy badger and found `apasfiis.sf.apa.at` & `varorfvod.sf.apa.at` being blocked. after manually "greylisting" them, everything worked fine again.
isn't/shouldn't [`apa.at` be whitelisted by default](https://github.com/EFForg/privacybadger/blob/master/src/js/multiDomainFirstParties.js#L246)? i assume this includes all subdomins.

so does anybody have a clue what is going on here?

**Comment by ghostwords** [comment]
We haven't released the fix yet, sorry!

**Comment by DJCrashdummy** [comment]
ok... so the whitelist is hardcoded and can't be updated without a release?

if yes, i'm beginning to doubt myself... :thinking: until now i was pretty sure the videos worked on other systems/profiles without manually white-/graylisting these domains, but well... if so, it is more or less impossible! :confused:

**Comment by ghostwords** [comment]
Yes, the MDFP domains list is hardcoded.
