### ISSUE TITLE
TypeError: callSite.isEval is not a function

### ISSUE THREAD

**Issue by Andrew-Cottrell** [EFForg/privacybadger#2323]
>Privacy Badger: version 2019.2.19
>Chrome: version 72.0.3626.119 (Official Build) (64-bit)
>Error: TypeError: callSite.isEval is not a function at getOriginatingScriptUrl (<anonymous>:151:20)
>Source: https://github.com/EFForg/privacybadger/blob/release-2019.2.19/src/js/contentscripts/fingerprinting.js
>Reference: https://v8.dev/docs/stack-trace-api

The function `getStackTrace` (line 116) returns a string, which is assigned to local variable `trace` in function `getOriginatingScriptUrl` (line 167). The character at index 2 is assigned to local variable `callSite` (line 174). The call to `callSite.isEval` fails (line 176) as `callSite` is a string and does not have an `isEval` method.

**Comment by Andrew-Cottrell** [comment]
After further investigation: this error only occurs when `globalThis.Error` has been frozen. As the `fingerprinting.js` script is in sloppy mode, rather than strict mode, the monkey-patching of `Error.prepareStackTrace` (line 122) fails without warning.

Perhaps the implementation of function `getStackTrace` (line 116) could be more defensive by running in strict mode, and/or checking if `globalThis.Error` has been frozen before attempting to monkey-patch it.

**Comment by Andrew-Cottrell** [comment]
A work-around for those who wish to defensively freeze `globalThis.Error` is to first execute the following

    Error.prepareStackTrace = function (_, structuredStackTrace) {
        return structuredStackTrace;
    };

This is successful because Privacy Badger runs `getStackTrace` in sloppy mode. If Privacy Badger switches to strict mode, please ensure it checks that `globalThis.Error` is not frozen before applying the monkey patch.

**Comment by ghostwords** [comment]
Hi, thanks for the report, and sorry for the delay in responding. Could you provide an example page (or code) that triggers this problem?

**Comment by Andrew-Cottrell** [comment]
Hi. Sorry, I encountered this issue on an pre-released, in-development page. The page uses the proprietary JavaScript charting library, AmCharts 3.21.0, and the error occurs when attempting to _print_ a chart.

    TypeError: callSite.isEval is not a function
        at getOriginatingScriptUrl (<anonymous>:151:20)
        at CanvasRenderingContext2D.fillText (<anonymous>:187:17)
        at i._renderChars (fabric.min.js:6)
        at i._renderTextLine (fabric.min.js:6)
        at i._renderTextFill (fabric.min.js:6)
        at i._renderText (fabric.min.js:6)
        at i._render (fabric.min.js:6)
        at i.render (fabric.min.js:7)
        at i.render (fabric.min.js:5)
        at i._renderObjects (fabric.min.js:2)

At the call to `CanvasRenderingContext2D.fillText` the arguments are

    CanvasRenderingContext2D.fillText("2.5", -8.993896484375, 2.4706)

The first argument is a `string` value and the other two are `number` values. Just before the line above executes, the `CanvasRenderingContext2D` instance looks like

    {
        canvas: canvas.lower-canvas
        direction: "ltr"
        fillStyle: "#000000"
        filter: "none"
        font: "11px Verdana"
        globalAlpha: 1
        globalCompositeOperation: "source-over"
        imageSmoothingEnabled: true
        imageSmoothingQuality: "low"
        lineCap: "butt"
        lineDashOffset: 0
        lineJoin: "miter"
        lineWidth: 1
        miterLimit: 10
        shadowBlur: 0
        shadowColor: "rgba(0, 0, 0, 0)"
        shadowOffsetX: 0
        shadowOffsetY: 0
        strokeStyle: "#000000"
        textAlign: "left"
        textBaseline: "alphabetic"
        __proto__: CanvasRenderingContext2D
    }

Sorry I didn't deploy a example page.

**Comment by Andrew-Cottrell** [comment]
Actually, the issue only occurs when the first argument to `CanvasRenderingContext2D.fillText` has a length greater-than or equal to `5`. The following call triggers this issue

    CanvasRenderingContext2D.fillText("JS chart by amCharts", -59.54931640625, 2.4706)

The Chrome debugger takes me to 

    /**
     * Monitor the writes in a canvas instance
     * @param item special item objects
     */
    function trapInstanceMethod(item) {
      var is_canvas_write = (
        item.propName == 'fillText' || item.propName == 'strokeText'
      );

      item.obj[item.propName] = (function (orig) {

        return function () {
          var args = arguments;

          if (is_canvas_write) {
            // to avoid false positives,
            // bail if the text being written is too short
            if (!args[0] || args[0].length < 5) {
              return orig.apply(this, args);
            }
          }

          var script_url = (...

At that line, the state is

    msg: undefined
    script_url: undefined
    this: CanvasRenderingContext2D
    orig: ƒ fillText()
    is_canvas_write: true
    item: {objName: "CanvasRenderingContext2D...
    V8_STACK_TRACE_API: true
