### ISSUE TITLE
Document served by Service Worker does not trigger context change

### ISSUE THREAD

**Issue by sascha-sl** [EFForg/privacybadger#2327]
#### What is your browser and browser version?

Vivaldi 2.3.1440.60 (Chromium/72.0.3626.122)

Reproduces with latest Firefox.

#### What is broken and where?

When navigating from any URL to a site where the main document is served by a service worker, PB does not detect a navigation event, resulting in API calls to that site being blocked as if they originated from the previous site. This requires a hard refresh or navigation from a fresh tab to fix.

As an example, this can be reproduced with any instance of tootsuite/mastodon.

#### What is the "culprit" domain?

Any.

#### What is your debug output for this domain?

N/A

**Comment by sascha-sl** [comment]
In addition, I should mention that it allowed a websocket connection to go through, just no HTTP api calls...

**Comment by ghostwords** [comment]
Hello and thanks for the report! This is a WebExtensions bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1499523. This issue is being tracked in #1144.

**Comment by ghostwords** [comment]
I'm a bit confused though by your mention of Vivaldi. Can you reproduce this in Chrome as well?

**Comment by sascha-sl** [comment]
No, the mentioned Chromium version is the base for my Vivaldi build, where this does reproduce.

**Comment by sascha-sl** [comment]
My apologies, this *does* reproduce in Chrome.

https://files.deadinsi.de/deadinside-media/media_attachments/files/000/904/046/original/24a068013aea0d10.png

**Comment by ghostwords** [comment]
OK, thank you for confirming. We will look into what's going on in Chrome ... Perhaps they introduced a similar bug to Firefox's in the last few updates (72?).

**Comment by ghostwords** [comment]
https://crbug.com/931588 seems related if not the same issue.

@sascha-sl Could you see if this is fixed in Chrome Beta?

**Comment by ghostwords** [comment]
So this is indeed a new, Service Worker-related issue in Chrome that we are tracking in #2335. Here is the Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=946908
