### ISSUE TITLE
documentcloud.org blocked on latimes.com and sandiegouniontribune.com

### ISSUE THREAD

**Issue by standyro** [EFForg/privacybadger#2328]
#### What is your browser and browser version?

`Chrome 72.0.3626.119`

#### What is broken and where?

On Los Angeles Times (`http://latimes.com`) and San Diego Union Tribune (`https://sandiegouniontribune.com`) pages, documents uploaded to the site do not load because Privacy Badger blocks it - as they are loaded through `documentcloud.org`, an open source software as a service platform for journalists to upload primary source documents such as FOIA (Freedom of Information ACT) Requests and other documents of public interest.

#### What is the "culprit" domain?
Please follow the debug instructions to identify which domain breaks stuff when blocked:
https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain
`http://documentcloud.org`

#### What is your debug output for this domain?
To get the debug output, please see the instructions link above.
```
Paste debug output here.
```

**Comment by bcyphers** [comment]
Hi, thanks for reporting this. It looks like DocumentCloud sets identifying cookies on anonymous users automatically, which Privacy Badger classifies as a tracking action. (the cookie is called `document_cloud_session`, see https://blog.documentcloud.org/blog/2011/02/https-by-default/comment-page-1/)

The easiest way to resolve this would be for Document Cloud to adopt DNT. I'll try to reach out to them and see if that's an option. In the mean time, you can fix the problem for yourself by dragging the sliders next to `documentcloud.org` over to green (allow).

**Comment by ghostwords** [comment]
@bcyphers Any response from DocumentCloud? We could also add `documentcloud.org` to the yellowlist.

Error report counts by date, page domain and exact blocked "documentcloud" subdomain:
```
+---------+--------------------------+----------------------------+-------+
| ym      | blocked_fqdn             | fqdn                       | count |
+---------+--------------------------+----------------------------+-------+
| 2019-05 | assets.documentcloud.org | www.cnn.com                |     2 |
| 2019-05 | assets.documentcloud.org | immigrantjustice.org       |     1 |
| 2019-05 | www.documentcloud.org    | immigrantjustice.org       |     1 |
| 2019-05 | www.documentcloud.org    | www.cnn.com                |     1 |
| 2019-04 | assets.documentcloud.org | www.cnn.com                |     1 |
| 2019-04 | assets.documentcloud.org | www.muckrock.com           |     1 |
| 2019-04 | www.documentcloud.org    | www.muckrock.com           |     1 |
| 2019-02 | documentcloud.adobe.com  | documentcloud.adobe.com    |     1 |
| 2019-02 | s3.documentcloud.org     | www.usatoday.com           |     1 |
| 2019-02 | www.documentcloud.org    | www.axios.com              |     1 |
| 2019-01 | assets.documentcloud.org | apps.npr.org               |     1 |
| 2018-12 | assets.documentcloud.org | www.axios.com              |     1 |
| 2018-12 | www.documentcloud.org    | www.axios.com              |     1 |
| 2018-11 | assets.documentcloud.org | apps.washingtonpost.com    |     1 |
| 2018-11 | assets.documentcloud.org | bangordailynews.com        |     1 |
| 2018-11 | www.documentcloud.org    | bangordailynews.com        |     1 |
| 2018-10 | www.documentcloud.org    | www.axios.com              |     1 |
| 2018-10 | www.documentcloud.org    | www.newyorker.com          |     1 |
| 2018-09 | assets.documentcloud.org | apps.washingtonpost.com    |     1 |
| 2018-09 | assets.documentcloud.org | edition.cnn.com            |     1 |
| 2018-09 | assets.documentcloud.org | www.washingtonpost.com     |     1 |
| 2018-09 | www.documentcloud.org    | apps.washingtonpost.com    |     1 |
| 2018-09 | www.documentcloud.org    | edition.cnn.com            |     1 |
| 2018-09 | www.documentcloud.org    | hillreporter.com           |     1 |
| 2018-09 | www.documentcloud.org    | www.cnn.com                |     1 |
...
```
