### ISSUE TITLE
National Car Rental Website: Non-tracking cookie blocked, causing missing vehicle images

### ISSUE THREAD

**Issue by smcnulty0227** [EFForg/privacybadger#2330]
Hi Privacy Badger Team -

The National Car Rental website is missing vehicle images critical to the site's functionality because Privacy Badger is blocking necessary cookies.

**What is broken and where?**
The vehicle select feature on the National Car Rental web properties is missing images of vehicles. See below image for reference:
![image](https://user-images.githubusercontent.com/16279672/54392596-1857c000-4676-11e9-8d44-29af1aa67194.png)

**What is the "culprit" domain?**
This problem is caused when assets.gcs.ehi.com is blocked. It seems that Privacy Badger identifies this cookie as a tracker when the National Car Rental website is visited on different regional domains. Given that National is an international car rental company, visiting different international domains is an important use case. This blocked cookie is used specifically for service-driven vehicles images which are needed to allow users to select vehicles when renting a car from National Car Rental on the web. This cookie is NOT used for tracking users.

**What is your debug output for this domain?**
```
ACTION_MAP for ehi.com
assets.gcs.ehi.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1552712938283
}
ehi.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
assets-pqa.nonprod.gcs.ehi.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1553159845875
}
**** SNITCH_MAP for ehi.com
ehi.com [
  "nationalcar.com",
  "natcar-np.com",
  "nationalcar.fr"
]
```

Please feel free to reach out if further information is needed!

**Comment by bcyphers** [comment]
Thanks for your report. This looks like an MDFP issue, so it should be simple enough to fix.

**Comment by smcnulty0227** [comment]
Thank you @bcyphers !

**Comment by patteerah** [comment]
We still see the same issue in Firefox. Can you please reopen this ticket and investigate?

**Comment by ghostwords** [comment]
Which version of Privacy Badger do you have? What site do you run into problems on?

**Comment by patteerah** [comment]
Private Badger version 2019.7.1.1
Website: Nationalcar.com
Firefox Version 67.0

Patteera Hengboriboonpong | Senior Functional Analyst

Isobar | 300 E Randolph Street | Suite 4000 | Chicago | IL | 60601
T +1 312-529-2508 | M +1 585-358-5098 | E pattera.h@isobar.com
isobar.com | @IsobarUS | facebook.com/isobar

**Comment by ghostwords** [comment]
What is broken, and what domains does Privacy Badger report on the page?

You can get the list of domains in an easy-to-copy text format by clicking on the Share button in Privacy Badger's popup (in the upper right, directly to the left of the Options button).

**Comment by patteerah** [comment]
**What is broken?**
The vehicle select feature on the National Car Rental web properties is missing images of vehicles. Please see screenshot below. 
![FireFox](https://user-images.githubusercontent.com/52793130/61069856-dc89f880-a3d2-11e9-9b0e-7d9d79c3a661.png)


**Domains that Privacy Badger reported on the page:** 

> Privacy Badger found 12 potential trackers on www.nationalcar.com:
> 
> assets.adobedtm.com
> bat.bing.com
> cdnssl.clicktale.net
> dpm.demdex.net
> googleads.g.doubleclick.net
> lasteventf-tm.everesttech.net
> www.facebook.com
> gateway.foresee.com
> ssl.google-analytics.com
> c.lytics.io
> enterpriseholdingsin.tt.omtrdc.net
> s3.amazonaws.com

Please let me know if that is what you are looking for.

**Comment by ghostwords** [comment]
That is what I was looking for, thank you, but I am unable to reproduce the problem. It looks like the images are served from `ehi.com`, which at this point Privacy Badger should be ignoring on Enterprise sites. And it isn't in your list of trackers, so that's good. But why are the images still broken?

Does reloading by holding down <kbd>Shift</kbd> and clicking the reload button in the browser toolbar resolve the issue?

**Comment by patteerah** [comment]
I just tried what you suggested, but the issue still persists. I tried with Firefox private browser (disabled Private Badger there), and the images are showing as they should.

**Comment by ghostwords** [comment]
Does this happen in Chrome? Does this happen with a new installation of Privacy Badger?

**Comment by patteerah** [comment]
The issue went away now for Chrome and Firefox. Thanks for the help!
