### ISSUE TITLE
Add replacement widget for third-party embedded videos from YouTube

### ISSUE THREAD

**Issue by michaelpeeri** [EFForg/privacybadger#2337]
Many pages embed youtube videos, causing calls to 3rd party sites from throughout the web.

These players should be optionally blocked until the user requests to play the video.

I realise this will degrade the page's appearance, so should be optional.

Example of web pages embedding youtube players:
https://www.theverge.com/2019/3/25/18280588/no-mans-sky-vr-steam-ps4-psvr
https://spaceflightnow.com/2019/03/21/vega-vv14-mission-status-center/

**Comment by ghostwords** [comment]
Thanks for the suggestion! YouTube is being worked on in #2280.

**Comment by michaelpeeri** [comment]
Amazing, thanks!

p.s. I tried to find a duplicate but didn't use the proper terminology -
now I know it's called a widget!

**Comment by bcyphers** [comment]
@michaelpeeri Would the Youtube widgets satisfy this ticket, in your mind? If so I'll close it.

**Comment by michaelpeeri** [comment]
Hi,
Yes, having a widget would address my need perfectly. It might be good to
have the option of toggling it because some users might find it too
disruptive.

Thanks again!

**Comment by ghostwords** [comment]
We should probably reopen this since we don't have an issue for YouTube, just a PR.

Right now you can disable replacement globally by toggling "Replace social widgets" on the options page. For more granular controls, please see #2049.

**Comment by ghostwords** [comment]
Adding a replacement widget for YouTube, and then removing YouTube domains from the yellowlist will fix the "Watch later" feature, currently broken (probably because of our cookie blocking) for all Privacy Badger users.

**Comment by ghostwords** [comment]
Adding a replacement widget for YouTube, and then removing YouTube domains from the yellowlist will fix the "Watch later" feature, currently broken (probably because of our cookie blocking) for all Privacy Badger users.
