### ISSUE TITLE
Can't open gmail

### ISSUE THREAD

**Issue by ghost** [EFForg/privacybadger#235]
Today is the first I've noticed it, Privacy Badger is listing mail.google.com as a tracker and prevents it from loading unless you use exclude the domain.

**Comment by VojtechDostal** [comment]
This issue seems to have resurfaced. I am a new user of Privacy Badger extension in Google Chrome and I have not been able to open Gmail with PB on.

**Comment by ghostwords** [comment]
Hi @VojtechDostal, which browser do you use? Would you mind opening a new issue describing the problem in more detail? Please feel free to include screenshots.
