### ISSUE TITLE
MDFP domains are marked as tracking in the snitch map

### ISSUE THREAD

**Issue by bcyphers** [EFForg/privacybadger#2351]
I was investigating #2334, and realized one of my assumptions is wrong. When a third-party domain sets high-entropy cookies, Privacy Badger doesn't check to see whether the domain is on the MDFP list before updating the snitch map. As a result, even though Wikimedia domains are on the list, the seed dataset still has a full `snitch_map` entry for wikimedia.org. See https://github.com/EFForg/privacybadger/blob/master/src/data/seed.json#L10633.

This is because `heuristicBlockingAccounting` doesn't contain any MDFP checks. I think this is a bug because every other place `_recordPrevalence` is called does -- Privacy Badger won't record MDFP domains as trackers when they do fingerprinting or set localstorage cookies.

The fix should be pretty easy, but it will also require a migration (as talked about [here](https://github.com/EFForg/privacybadger/issues/2334#issuecomment-476269021).)

**Comment by ghostwords** [comment]
I have a fix in progress as part of #2198 (I think ... that part may not be pushed to GH yet). It didn't seem worth fixing by itself.

**Comment by ghostwords** [comment]
Do we need a migration? As in, what does having MDFP'd domains in snitch map break?

**Comment by bcyphers** [comment]
The main reason I want to fix it is for issues like https://github.com/EFForg/privacybadger/issues/2334#issuecomment-485116573. Right now MDFP domains have "false strikes" against them; if wikimedia.org is ever used in a third-party context on a domain outside the MDFP list, it will be blocked, even if it's never been seen tracking outside of the Wikimedia ecosystem. It also makes it harder to debug issues around MDFP domains when their snitch maps are full of other supposedly first-party domains.

**Comment by ghostwords** [comment]
The migration would go something like, for every site domain in snitch map (which passed [the less-strict third-partyness check in heuristicblocking.js](https://github.com/EFForg/privacybadger/blob/099d79753e1547606d6ca858b4720e09eda6760d/src/js/heuristicblocking.js#L117-L120)), see if the site domain is in fact third-party to the tracker domain (the [correct third-partyness check in webrequest.js](https://github.com/EFForg/privacybadger/blob/099d79753e1547606d6ca858b4720e09eda6760d/src/js/webrequest.js#L345-L360)). If it's not, oops, it's a mistake, we should remove it. If this brings snitch map for the tracking domain below `PREVALENCE_THRESHOLD`, oops, we should undo the blocking. (What goes into undoing blocking?)
