### ISSUE TITLE
xopia.cc

### ISSUE THREAD

**Issue by eddiejibson** [EFForg/privacybadger#2353]
#### What is your browser and browser version?
Firefox 67
#### What is broken and where?
https://xopia.cc - Both the CDN (for images) and the API are blocked site-wide. None of which do any tracking on the client side
#### What is the "culprit" domain?
https://api.xopia.cc and https://cdn.xopia.cc

**Comment by jalcine** [comment]
Hm, I've visited this site and don't see those domains you've provided being blocked.

**Comment by jalcine** [comment]
@eddiejibson can you provide the snitch map for the site when you visit it?

**Comment by ghostwords** [comment]
Closing for now.

@eddiejibson If this is still a problem, could you explain where exactly (on what sites) `xopia.cc` domains get blocked? It would also help to provide the [debug output](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) as requested.
