### ISSUE TITLE
"Privacy Badger could not be verified for use in Firefox and has been disabled"

### ISSUE THREAD

**Issue by toups** [EFForg/privacybadger#2356]
#### What is your browser and browser version?
Firefox Quantum 66.0.3 (64-bit)

#### What is broken and where?
Privacy Badger is disabled by Firefox
Privacy Badger version 2019.2.19

Firefox message is "Privacy Badger could not be verified for use in Firefox and has been disabled" and Privacy Badger shows up as a "Legacy Extension"

**Comment by mckea** [comment]
I also experience this, and the same with uBlock Origin; but only on my Ubuntu system.  No problems on my Fedora machine.

This started happening today.

**Comment by pcrooker** [comment]
I have it when my Ubuntu (xenial and bionic) systems upgraded to FF 66.03 64bit. Oddly, this didn't happen with the same FF version on Windows 10.

A work-round is to go into about:config, scroll to the bottom, then change xpinstall.signatures.required to false. Beware, this applies to all browser plugins so be careful what you install.

**Comment by Digital-K** [comment]
Same. I'm using Firefox Quantum 66.0.3
Privacy Badger and Adblock are disabled and I can't download new versions - says they are corrupt

**Comment by exploide** [comment]
This is not a PrivacyBadger issue. Apparently a certificate on Mozilla's side expired.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1548973
and https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by toups** [comment]
Looks like Mozilla has fixed it.  Working again, evidently was not a Privacy Badger issue.

**Comment by ghostwords** [comment]
Thanks for letting us know, and thanks for the followup!

You can also see the ["Add-ons disabled or failing to install in Firefox" Mozilla blog post](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/) for more information.

**Comment by ghostwords** [comment]
See also the [release notes for Firefox 66.0.4](https://www.mozilla.org/en-US/firefox/66.0.4/releasenotes/).

**Comment by ghostwords** [comment]
This should at this point be fixed for all current and some older versions of Firefox. Please see the ["Add-ons disabled or failing to install in Firefox" Mozilla blog post](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/) for more information.

**Comment by PJTraill** [comment]
This suddenly cropped up for me today, in Firefox 102.6.0esr (64-bit) on Open Suse Leap 15.3, although that version is dated December 2022.

**Comment by ghostwords** [comment]
Hello! It looks like ESR is up to 102.11 at this point, so you could upgrade and see if this [add-on signing](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox) issue is fixed there. If it's not, I suggest reaching out to [Firefox support](https://support.mozilla.org/en-US/questions/new/desktop). Let us know how it goes please!

**Comment by PJTraill** [comment]
This suddenly cropped up for me today, in Firefox 102.6.0esr (64-bit) on Open Suse Leap 15.3, although that version is dated December 2022.

Edit: 2023-05-25: Privacy Badger is active again, and listed as recommended.
