### ISSUE TITLE
Blocking Replug

### ISSUE THREAD

**Issue by davidneedham** [EFForg/privacybadger#2360]
I don't know if this it the right place, I recently came across [Replug](https://replug.io/) and was surprised PrivacyBadger didn't do anything to block it.

TLDR: When I open the [Replug demo URL](https://rplg.co/demo) and view PrivacyBadger, Replug is on the list of "The domains below don't appear to be tracking you". That seems like an oversight since you're viewing a third party site through their frame and your data is being actively collected.

Replug is a service that allows you to generate short URL's (like bit.ly). But rather than a full redirect, it loads up the intended site in a frame (or something), keeps the short URL, and gives you the option of popping up your own information in front of the visitor while simultaneously collecting data about what visitors do there.

Here's an example of how it could work. 

1. You find a link to an article you want to share, [such as this one](https://www.searchenginejournal.com/how-to-do-content-curation-for-seo-your-starter-guide). 
2. You create a short URL and design a popup on the page to sell your services. The finished product looks like this [https://rplg.co/demo](https://rplg.co/demo).
3. You share on social media and any random passerby could easily be misled into thinking you have an ad on the site, or perhaps even that the site is directly associated with your business.

When I open the demo URL and view PrivacyBadger, Replug is on the list of "The domains below don't appear to be tracking you". That can't be right.

**Comment by bcyphers** [comment]
When I load up the demo (https://rplg.co/demo), my Privacy Badger does show "replug.io" in the top section (sites identified as trackers). Is this something that happens every time you load the domain, or is it nondeterministic? Do you have any other extensions installed or browser features turned on that might be blocking cookies?

**Comment by bcyphers** [comment]
Privacy Badger starts blocking a domain by default after it's seen it tracking in three different first-party contexts. So if you visit three different sites with Replug, it should start blocking replug.io automatically. Otherwise, you can drag the slider next to replug.io over to the left side, and it will be blocked on your device from now on.

**Comment by davidneedham** [comment]
> Privacy Badger starts blocking a domain by default after it's seen it tracking in three different first-party contexts. So if you visit three different sites with Replug, it should start blocking replug.io automatically. Otherwise, you can drag the slider next to replug.io over to the left side, and it will be blocked on your device from now on.

Oh, I didn't realize Privacy Badget worked like that automatically. I thought there was a list being maintained. Is that not the case? (If I see something like this again, should I report it here or just trust that it's monitoring and learning?)
