### ISSUE TITLE
api.meetup.com is blocked

### ISSUE THREAD

**Issue by microcosm** [EFForg/privacybadger#2362]
#### What is your browser and browser version?
Chrome 74.0.3729.131 (Official Build) (64-bit)

#### What is broken and where?
https://novacodecoffee.com/
http://akronwit.org/

#### What is the "culprit" domain?
api.meetup.com

#### What is your debug output for this domain?
The debug output seems to show api.meetup.com as allowed, but it is consistently blocked by default in practice on my machine.
```
**** ACTION_MAP for meetup.com
api.meetup.com {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1558371157051,
  "userAction": ""
}
meetup.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
www.meetup.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1558091237344,
  "userAction": ""
}
**** SNITCH_MAP for meetup.com
meetup.com [
  "localhost",
  "webpreview.herokuapp.com",
  "stackoverflow.com"
]
```

**Comment by ghostwords** [comment]
Looks like if you visit meetup.com before going to either of the example sites, you get a "x-mwp-csrf" cookie, which is then sent along with requests for `api.meetup.com` resources on the example sites. Privacy Badger sees this as tracking. Once it sees this happen on three different sites, it starts blocking all `meetup.com` domains.

**Comment by ghostwords** [comment]
I don't see any "Did Privacy Badger break this site?" user error reports where "meetup.com" is blocked at this time.

**Comment by microcosm** [comment]
Seems to be OK now
