### ISSUE TITLE
Signed version in the making?

### ISSUE THREAD

**Issue by bachlipp** [EFForg/privacybadger#2367]
Hi,
I was really happy with this add on. Sadly, since Mozilla forces add ons to be signed, Firefox disabled this plugin. Of course, there are workarounds like resorting to a Firefox Extended Support Release with special configuration, but it was really great if you could provide a signed update to your add on.
Cheers
Philipp

**Comment by bachlipp** [comment]
Hi,
after having been pointed to https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/ this issue turned out to be a non-issue.
Sorry for reporting it at all.
Cheers
Philipp

**Comment by ghostwords** [comment]
No problem! Glad you found the answer.

**Comment by ghostwords** [comment]
Duplicate of #2356.
