### ISSUE TITLE
Blocking cdns.gigya.com Breaks AirCanada.com 

### ISSUE THREAD

**Issue by Alanfar** [EFForg/privacybadger#2368]
Privacy Badger breaks the Air Canada subscription center (where you choose which emails you received for your signed-in account). After disabling several filters it seems as though the following filters break the site:

cdns.gigya.com
cdns.eu1.gigya.com
accounts.eu1.gigya.com

The site url is: 
https://www.aircanada.com/ca/en/aco/home/email-pref-center/subscription.html

Edit: updated URl and added additional Gigya script

**Comment by ghostwords** [comment]
Previously: #1045

We currently only replace the Gigya script with a dummy version for `cdn.gigya.com` and `cdns.gigya.com` domains.

<details><summary>Blocked "gigya" subdomains from error reports:</summary>

```
accounts.au1.gigya.com
accounts.eu1.gigya.com
accounts.gigya.com
accounts.us1.gigya.com
cdn1.gigya.com
cdn2.gigya.com
cdn3.gigya.com
cdn.gigya.com
cdn.gigya-ext.com
cdns1.gigya.com
cdns2.gigya.com
cdns3.gigya.com
cdns.au1.gigya.com
cdns.eu1.gigya.com
cdns.gigya.com
cdns.ru1.gigya.com
cdns.us1.gigya.com
comments.eu1.gigya.com
comments.us1.gigya.com
counters.gigya.com
ds.eu1.gigya.com
ds.us1.gigya.com
fidm.eu1.gigya.com
gm.us1.gigya.com
gscounters.au1.gigya.com
gscounters.eu1.gigya.com
gscounters.us1.gigya.com
socialize.au1.gigya.com
socialize.eu1.gigya.com
socialize.us1.gigya.com
```
</details>

Of the above domains, the following seem to return Gigya JS:
```
accounts.gigya.com
accounts.us1.gigya.com
cdns1.gigya.com
cdns2.gigya.com
cdns3.gigya.com
cdns.au1.gigya.com
cdns.eu1.gigya.com
cdns.gigya.com
cdns.us1.gigya.com
comments.us1.gigya.com
ds.us1.gigya.com
gm.us1.gigya.com
gscounters.us1.gigya.com
socialize.us1.gigya.com
```

**Comment by ghostwords** [comment]
Hi @Alanfar, thanks for the report!

Could you see if my planned fix will work? The steps to confirm:
1. Revert the two Gigya domains you customized back to Badger control (by clicking the "undo" arrow, the slider should go back to "red").
2. Open Badger's background page as per step two of https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain.
3. Enter the following code into the console tab on the background page:
```javascript
require('surrogatedb').hostnames['cdns.eu1.gigya.com'] = ['/js/gigya.js', '/JS/gigya.js', '/JS/socialize.js'];
```
4. Reload the problem page and see if the problem is fixed despite all Gigya domains being blocked.

**Comment by Alanfar** [comment]
I've tried your suggestion and it doesn't fix the problem. I'm happy to try any other solutions. I've also edited my original incident report to include an additional Gigya domain, as well as updating the Air Canada URL.

Thank you for your help with this!

**Comment by Alanfar** [comment]
I am using Firefox V. 67.0

**Comment by ghostwords** [comment]
I see, thank you for the clarification. This is different from what I was thinking of; the entire form is powered by Gigya. Surrogates aren't a good fit for this problem probably.
