### ISSUE TITLE
AbortError: A request was aborted, for example through a call to IDBTransaction.abort. error

### ISSUE THREAD

**Issue by m4lk4** [EFForg/privacybadger#2379]
AbortError: A request was aborted, for example through a call to IDBTransaction.abort.

**Comment by ghostwords** [comment]
Hello and thanks for letting us know! This is some sort of Firefox bug that Privacy Badger will stop pestering you about after our next update.

**Comment by ghostwords** [comment]
Closing as a duplicate of #2156.
