### ISSUE TITLE
Breaks cartoradio.fr

### ISSUE THREAD

**Issue by Yvan-Masson** [EFForg/privacybadger#2397]
#### What is your browser and browser version?
60.7.0esr (64bits)

#### What is broken and where?
cartoradio.fr is a French governmental website that shows antennas (point-to-point, 3G, 4G…) on a map. This map is from another French governmental website (ign.fr) that is blocked by PrivacyBadger.

#### What is the "culprit" domain?
wxs.ign.fr should be allowed, with cookies, so that the map is shown.

#### What is your debug output for this domain?
```
**** ACTION_MAP for ign.fr
piwik.ign.fr {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1550560622641
}
ign.fr {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
www.ign.fr {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1560358964762
}
wmts-remonterletemps.ign.fr {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1550606733496
}
wxs.ign.fr {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1561357955665
}
**** SNITCH_MAP for ign.fr
ign.fr [
  "geoportail.gouv.fr",
  "geoportail-urbanisme.gouv.fr",
  "ignrando.fr"
]

```

Do no hesitate to ask if I can provide more information.

Regards,
Yvan

**Comment by ghostwords** [comment]
Hello and thanks for the report!

Sounds like we should add `cartoradio.fr`, `geoportail-urbanisme.gouv.fr`, and `ignrando.fr` to the list of French government mapping sites.

Previously: #2308
