### ISSUE TITLE
Math formulas break on multiple sites with privacy badger

### ISSUE THREAD

**Issue by karypid** [EFForg/privacybadger#2400]
#### What is your browser and browser version?
Firefox 67.0

#### What is broken and where?
Multiple web sites, which render math equations.

Prominent examples:

- https://math.stackexchange.com/
- https://www.quora.com/How-can-you-prove-that-e-i-pi-1

I suspect they are using some library to formulate text between $$ signs as mathematical equations. I would expect this to be something like jquery (sorry, not familiar with the technicals) so I don't think such a "shared web library" would set tracking cookies. It's quite possible this is an issue with Privacy Badger.

#### What is the "culprit" domain?
Please follow the debug instructions to identify which domain breaks stuff when blocked:
https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain

From the list of domains shown, the problem goes away when I make "cdnjs.cloudflare.com" yellow (instead of red). Thisi s likely where this libary is loaded from.

#### What is your debug output for this domain?
To get the debug output, please see the instructions link above.
```
**** ACTION_MAP for cloudflare.com
cloudflare.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
cdnjs.cloudflare.com {
  "userAction": "user_block",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1551529358088
}
ajax.cloudflare.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1555749608699
}
**** SNITCH_MAP for cloudflare.com
cloudflare.com [
  "nginx.com",
  "springer.com",
  "sciencemag.org",
  "skai.gr",
  "tweaktown.com"
]
```

**Comment by ghostwords** [comment]
Hello!

Cloudflare.com domains should already be set to "yellow" by default as [`cloudflare.com` is on our "yellowlist"](https://github.com/EFForg/privacybadger/blob/d8e7d7e41b88b0a6dc4eaf701bf6913fe080ea1b/src/data/yellowlist.txt#L101). Your debug output says that Privacy Badger learned to block cookies for some cloudflare.com domains, and that you told Privacy Badger to block `cdnjs.cloudflare.com`.

Could it be that you manually blocked some domains at some point before you ran into this issue?

**Comment by karypid** [comment]
Hello @ghostwords 

Thank for your immediate reply. It is in fact very likely I did that.

Is there a way to switch anything I have manually configured back to defaults? I found a "Reset tracking domains" and a "Remove all tracking domains" button under "Manage Data" of preferences. Both however would discard my history. I would prefer to keep what Privacy Badger has "learned" but simply undo any manual sliders I might have changed?

**Comment by ghostwords** [comment]
Yes! You can visit the Tracking Domains tab and filter to show only "user-controlled"-type domains. You can then review your modifications and undo them one by one if you wish.

Closing, but let me know if you have any other questions.

This issue is related to #2021.
