### ISSUE TITLE
Breaking media hosted by sdn.szn.cz

### ISSUE THREAD

**Issue by finwe** [EFForg/privacybadger#2410]
Trying to whitelist CDN subdomains *.sdn.szn.cz (loaded eg. on https://www.televizeseznam.cz/sluzba/stream) and the media are still being blocked and have to be allowed manually.

Version is 2019.2.19

**Comment by ablanathtanalba** [comment]
HI @finwe thanks for the report! When you say the media is blocked, do you mean the embedded video content on that site is prevented from playing entirely? If so, this is definitely a problem that needs to be addressed.

However, I'm unable to recreate a problem with media content being blocked on https://www.televizeseznam.cz/sluzba/stream . I spent some time training a new badger by navigating through a dozen or more different Czech media sites with the .cz top level domain, and still the embedded video content on this site loads ok for me.

I'll take a closer at this tomorrow, but if this is does turn out to be a reproducible bug, I suspect it will be a widget replacement issue.

**Comment by finwe** [comment]
The content from the CDN is blocked entirely unles I manually allow the subdomain.

On subsequent loads, sometimes the subdomain of the CDN changes, and subdomains that I haven't yet allowed manually are being blocked despite the whitelist entry.

![shot_190701_082124](https://user-images.githubusercontent.com/195675/60414800-8e5a4580-9bd9-11e9-883c-6d847f4ed646.png "not loaded static content")
*not loaded static content*

![shot_190701_082125](https://user-images.githubusercontent.com/195675/60414801-8e5a4580-9bd9-11e9-953e-dd998fcc2a2f.png "sliders for the CDN")
*badger sliders for the CDN*

![shot_190701_082259](https://user-images.githubusercontent.com/195675/60414802-8e5a4580-9bd9-11e9-806b-e01c8771e7bc.png "whitelist screenshot")
*whitelist screenshot*

It is possible that I am missing something.

**Comment by ghostwords** [comment]
Hi @finwe! Privacy Badger's whitelist is for sites, not trackers. So whatever you put in there applies to sites you visit directly (such as https://www.televizeseznam.cz/), not (potential) trackers within the sites such as all the `sdn.szn.cz` subdomains.

If you know there are many different subdomains of a single domain you would like to tell Privacy Badger to cookieblock (or allow), visit Privacy Badger's options page, click on the Tracking Domains tab, search for the part of the domain all the subdomains have in common ("sdn.szn.cz"), find the entry for it, and not for any of the subdomains, and move the slider for that entry to "yellow" (or "green"). This will automatically move the slider for all of its subdomains.

Let me know if this helps or not.

**Comment by ghostwords** [comment]
We consistently get reports of breakages for "sdn.szn.cz", so we probably want to fix this for all Privacy Badger users.

Error report counts by date, page domain and exact blocked "sdn.szn.cz" subdomain:
```
+---------+----------------------+----------------------------+-------+
| ym      | blocked_fqdn         | fqdn                       | count |
+---------+----------------------+----------------------------+-------+
...
| 2019-06 | d11-a.sdn.szn.cz     | www.televizeseznam.cz      |     4 |
| 2019-06 | d27-a.sdn.szn.cz     | www.seznam.cz              |     3 |
| 2019-06 | d32-a.sdn.szn.cz     | www.seznam.cz              |     3 |
| 2019-06 | d39-a.sdn.szn.cz     | www.seznamzpravy.cz        |     3 |
| 2019-06 | d48-a.sdn.szn.cz     | www.seznam.cz              |     3 |
| 2019-06 | d50-a.sdn.szn.cz     | www.seznamzpravy.cz        |     3 |
| 2019-06 | d53-a.sdn.szn.cz     | www.seznam.cz              |     3 |
| 2019-06 | d53-a.sdn.szn.cz     | www.televizeseznam.cz      |     3 |
| 2019-06 | login.szn.cz         | www.novinky.cz             |     3 |
| 2019-06 | login.szn.cz         | www.seznam.cz              |     3 |
| 2019-06 | login.szn.cz         | www.seznamzpravy.cz        |     3 |
| 2019-06 | login.szn.cz         | www.televizeseznam.cz      |     3 |
...
```

**Comment by ghostwords** [comment]
@finwe Could you provide the debug output for "sdn.szn.cz" by following the instructions in steps 2 and 3 of https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain?

**Comment by finwe** [comment]
Oh, that's what I was missing! Sure, I'll get to the debugging once I have a spare moment.

**Comment by finwe** [comment]
Setting on the Tracking Domains tab seems to have helped, thanks!

The debug for d11-a.sdn.szn.cz is as follows.

```
**** ACTION_MAP for szn.cz
szn.cz {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1492917591953
}
d11-a.sdn.szn.cz {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1562328923036
}
s12.cdn.szn.cz {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1496866312025
}
d49-a.sdn.szn.cz {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1562114693143
}
**** SNITCH_MAP for szn.cz
szn.cz [
  "stream.cz",
  "aktualne.cz",
  "novinky.cz",
  "seznam.cz"
]
```

**Comment by ghostwords** [comment]
This seems like a job for [MDFP](https://github.com/EFForg/privacybadger/blob/master/doc/fixing-broken-sites.md#domains-that-are-part-of-the-site-but-dont-look-like-it). Do the following domains all belong to Seznam? Is `aktualne.cz` also part of Seznam?
```
firmy.cz
garaz.cz
kupi.cz
lide.cz
mapy.cz
novinky.cz
prozeny.cz
sauto.cz
sbazar.cz
sdovolena.cz
seznam.cz
seznamzpravy.cz
sport.cz
sreality.cz
stream.cz
sweb.cz
super.cz
televizeseznam.cz
volnamista.cz
zbozi.cz
zive.cz

szn.cz
```

This doesn't seem like a good fit for our widget replacement system because the breakage isn't limited to one particular kind of widget but rather all sorts of resources (images, etc.), and the breakages don't happen all over the Web but rather on a small set of sites (that happen to belong to the same entity).

**Comment by finwe** [comment]
Listed domains all belong to seznam.cz, aktualne.cz does not.

**Comment by ghostwords** [comment]
OK, thank you. We'll fix this issue across the above sites with the next Privacy Badger release.

**Comment by finwe** [comment]
Oh, zive.cz also does not belong to Seznam, but others should.

**Comment by finwe** [comment]
Thanks!
