### ISSUE TITLE
Google OAuth blocked on our web app

### ISSUE THREAD

**Issue by ddomonkos** [EFForg/privacybadger#2412]
#### What is your browser and browser version?
Google Chrome 74.0.3729.169

#### What is broken and where?
User is not able to sign in via the Google OAuth. Once they enable cookies for accounts.google.com, it works.

#### What is the "culprit" domain?
present.sli.do

To get to the login screen, you need to specify a presentation id though. You can try this one:
https://present.sli.do/?presentationId=1brK-nGfAOWjFKgGpwQHC-vBE6gM9xUDRhD2cmfVMhZo

#### What is your debug output for this domain?
```
**** ACTION_MAP for sli.do
assets.sli.do {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1562671544658,
  "userAction": ""
}
sli.do {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 0,
  "userAction": ""
}
stream.stage.sli.do {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1562400503298,
  "userAction": ""
}
**** SNITCH_MAP for sli.do
sli.do [
  "google.com",
  "slido-staging.com"
]
```

#### Other info
I noticed thread #137 which seems to have a similar culprit but hasn't been touched in a while.

**Comment by ghostwords** [comment]
Hello and thank you for your report! This problem does fall under #137, and is indeed one of Privacy Badger's long-outstanding issues. We do have an idea as to how approach this, and it is one of our main pain points, but we haven't started on it yet.
