### ISSUE TITLE
AMO still showing February version

### ISSUE THREAD

**Issue by michaelblyons** [EFForg/privacybadger#2416]
It's been over a week since the latest release, but Firefox still shows [the old one](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/). I noticed that there were two releases this month, and one specifically mentions AMO. Is that related?

What is the normal lag time between release and availability? Does downloading the XPI directly from [EFF.org](https://www.eff.org/privacybadger) work seamlessly and support future automatic updates?

**Comment by ghostwords** [comment]
We are at the mercy of AMO's reviewers, and yes, we've been waiting over a week now.

Installing from https://www.eff.org/pb: yes and yes. See https://github.com/EFForg/privacybadger/issues/2297#issuecomment-463277129 for a bit more information.

Let me know if you have any questions about any of this.

**Comment by ghostwords** [comment]
Aaand we're live on AMO!
