### ISSUE TITLE
QuotaExceededError: The current transaction exceeded its quota limitations.

### ISSUE THREAD

**Issue by stuartlangridge** [EFForg/privacybadger#2417]
PB is showing an "exclamation mark" icon in Firefox, and there is a box in its popup saying:

Please tell us about the following error:
QuotaExceededError: The current transaction exceeded its quota limitations.

**Comment by ghostwords** [comment]
Hello and thanks for the report! This might be another one of those Firefox IndexedDB-powered extension storage errors that Privacy Badger can't do anything about except ignore. Previously: #2156.

Which version of Firefox do you have? Does this problem come back after restarting the browser and browsing around for a bit?

**Comment by ghostwords** [comment]
Asked Mozilla about this on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1555491#c10

**Comment by ghostwords** [comment]
@stuartlangridge Could you tell us how much space Privacy Badger's storage takes up in your Firefox? To do so, visit Privacy Badger's background page, and copy and paste the following code into the console:
```javascript
chrome.storage.local.get(null, r=>console.log(
  parseFloat(JSON.stringify(r).length / 1024 / 1024).toFixed(2), "MB"));
```
Please see [step 2 of our debugging page](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain#2-open-privacy-badgers-extension-background-page) for instructions for opening the background page.

**Comment by stuartlangridge** [comment]
Certainly.

```
chrome.storage.local.get(null, r=>console.log(
  parseFloat(JSON.stringify(r).length / 1024 / 1024).toFixed(2), "MB"));

2.11 MB
```

**Comment by stuartlangridge** [comment]
Interestingly, in about:debugging, in the privacy badger part, it also says this:

Reading manifest: Error processing storage: An unexpected property was found in the WebExtension manifest.

For reference, this is Firefox Quantum 67.0.4 (64-bit) on Ubuntu 18.04.

**Comment by ghostwords** [comment]
Could you post a screenshot?

Does this problem come back after restarting the browser and browsing around for a bit?

**Comment by stuartlangridge** [comment]
Sure thing:

![image](https://user-images.githubusercontent.com/4356350/61000328-17e5e200-a355-11e9-8ced-c2a165b39702.png)

(I don't really want to restart the browser right now; I'm in the middle of stuff, and rearranging all the windows after a restart is really annoying. If that's what I need to do to test it, I'll try to get to it tomorrow and then report back.)

**Comment by ghostwords** [comment]
OK, great, sounds good, thank you!

**Comment by ghostwords** [comment]
I think the "error processing storage" error is unrelated, by the way. It does sound relevant, but it's something else (https://github.com/EFForg/privacybadger/issues/1774#issuecomment-473539483).

**Comment by stuartlangridge** [comment]
I can now confirm that restarting the browser cleared the error and PB is no longer showing that error.

**Comment by Darxus** [comment]
I am also seeing this, on firefox 68.0 (64-bit), Ubuntu 18.04.2 LTS.
