### ISSUE TITLE
Blocking WebSockets even when disabled?

### ISSUE THREAD

**Issue by stevospinks** [EFForg/privacybadger#2418]
I've been using this website https://websocketstest.com/ to try to diagnose an issue with WebSockets in Google Chrome.

When all extensions are disabled the "WebSockets (Port 443, SSL)" section loads and shows green ticks and the server time.
When I enable the Privacy Badger extension the "WebSockets (Port 443, SSL)" section does not load, even though Privacy Badger says it isn't blocking anything.
If I disable privacy badger for the site the section still doesn't load.

This is true of other websites that use WebSockets, like https://miro.com/app and any Microsoft chatbot

**Comment by ghostwords** [comment]
Which version of Chrome, and which version of Privacy Badger do you have?

Is this still a problem if you try it in a new browser profile?

Unable to reproduce at this time:
![Screenshot from 2019-07-11 11:48:51](https://user-images.githubusercontent.com/794578/61065540-e2cba500-a3d1-11e9-8ec2-73a74b083f92.png)

**Comment by stevospinks** [comment]
Chrome version is 75.0.3770.100 (64-bit)
Privacy Badger version is 2019.7.1

It's still an issue in a new profile:
![pb](https://user-images.githubusercontent.com/11633557/61066181-f2141800-a3fc-11e9-8cdf-3d429194f6a1.png)

**Comment by ghostwords** [comment]
Are there any errors in the developer console on the page?

If you switch over to the Network pane in developer tools and reload the page, do you see any requests blocked (besides Google Analytics)?

**Comment by stevospinks** [comment]
Looks like there's a proxy error (this is on my company managed laptop).
![pb-console](https://user-images.githubusercontent.com/11633557/61067806-55ec1000-a400-11e9-86f8-470514f96dd8.png)
When Privacy Badger is disabled I still see the first two errors, but not the 'handshake timed out' error.

Here's the network pane before the 3rd 'service' timeout:
![pb-network](https://user-images.githubusercontent.com/11633557/61067813-58e70080-a400-11e9-91f5-302791bbd05c.png)
Here's the network pane after the timeout:
![pb-network-after-timeout](https://user-images.githubusercontent.com/11633557/61068117-1ffb5b80-a401-11e9-8eff-062ba48af8f9.png)

**Comment by ghostwords** [comment]
OK, thank you. I don't know what's going on at this point though. Privacy Badger shouldn't even be intercepting WebSockets yet (#1010).

Is this an issue in Firefox?

**Comment by stevospinks** [comment]
Firefox has a different issue behind the proxy that my company uses, meaning that Web Sockets don't work at all:
https://bugzilla.mozilla.org/show_bug.cgi?id=1541911

I'll try to reproduce in both browsers at home over the weekend and let you know anything I find.

**Comment by ghostwords** [comment]
Does this happen with other Chrome content blockers, or only Privacy Badger?

**Comment by stevospinks** [comment]
Privacy Badger works perfectly fine in Chrome at home, so it must be related to the proxy in some way.

I've tested a few Chrome content blockers today.
Adblock, Adblock Plus, Adblocker Ultimate, Disconnect, Fair Adblocker and uBlock Origin are all fine.
AdGuard AdBlocker and Ghostery seem to have the same issue as Privacy Badger (including when sites are whitelisted).

**Comment by ghostwords** [comment]
Interesting, thanks for testing! Would be good to make a minimally reproducible test case and open a crbug.com issue.
