### ISSUE TITLE
Privacy Badger not working :(

### ISSUE THREAD

**Issue by JnJsph** [EFForg/privacybadger#2424]
Privacy Badger no longer works with Chrome 75.0.3770.142 on my desktop Mac running OS 10.11.6 ... get message saying "Privacy Badger is disabled. Would you like to enable it?" click on the link to enable and the same message ("Privacy Badger is disabled. Would you like to enable it?") re-appears. Boo! Help?

**Comment by ghostwords** [comment]
Does removing and then reinstalling Privacy Badger help?

**Comment by dotproto** [comment]
@JnJsph, could you provide a screenshot of the message you're seeing?

**Comment by ghostwords** [comment]
Closing for now. Let us know if you have more information.
