### ISSUE TITLE
Privacy Badger doesn't learn when privacy.firstparty.isolate is enabled in Firefox

### ISSUE THREAD

**Issue by lucaStronks** [EFForg/privacybadger#2426]
Firefox users can isolate cookies to first parties, by setting `privacy.firstparty.isolate` to `true` in about:config. When this is enabled, Privacy Badger can't identify tracking cookies because it finds that cookies set on one website can't / won't be accessed by other websites.

**Comment by ghostwords** [comment]
Hi, thanks for reporting this. It looks like Privacy Badger still learns ... It may learn less, but I do see both cookie and localstorage-based learning. You can see for yourself but installing Privacy Badger into a new profile, enabling `privacy.firstparty.isolate`, clearing Badger's tracker database ("Remove all" button on the bottom of the Manage Data options page tab), and then browsing around for a bit.

It looks like we do have a cookie sharing detection bug with first-party isolation that we should fix:

- "cookies is undefined" on [heuristicblocking.js:157](https://github.com/EFForg/privacybadger/blob/6843899a29a36bc132420aa2ff1d3ee2da0c0477/src/js/heuristicblocking.js#L157)
- "Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set." on [heuristicblocking:154](https://github.com/EFForg/privacybadger/blob/6843899a29a36bc132420aa2ff1d3ee2da0c0477/src/js/heuristicblocking.js#L154)

**Comment by ghostwords** [comment]
If I understand first-party isolation correctly, it shouldn't impact Privacy Badger's learning at all, as the cookies/other storage will still be set, it's just that they will be keyed to the first-party domain. This means the third-party cookies won't be seen by their setters on other first-party domains.

But yeah, we've got an edge case bug here that breaks cookie sharing detection.
