### ISSUE TITLE
PrivacyBadger version 2019.7.1 Chrome based Extension issues

### ISSUE THREAD

**Issue by milldogtjm** [EFForg/privacybadger#2428]
I have found a few errors with in your wonderful Google Chrome based browser extension. Here is the code that sprang up; This is for line 2-6 Unrecognized manifest key 'applications'.
  "applications": {
      "gecko": {
         "id": "jid1-MnnxcxisBPnSXQ@jetpack"
      }
   }

The second error found was on line 527 Error in event handler for webRequest.onResponseStarted/5: TypeError: Cannot read property 'heuristicBlockingAccounting' of undefined        return badger.heuristicBlocking.heuristicBlockingAccounting(details);

 The third error is on line 90 "Can't initialize cache from getBadgerStorageObject. You are using this API improperly" Mentioned twice!
    console.error("Can't initialize cache from getBadgerStorageObject. You are using this API improperly");
The fourth error is on line 611 "Error in event handler for tabs.onUpdated: TypeError: Cannot read property 'getItem' of undefined"
    var disabledSites = settings.getItem("disabledSites");
The fifth error is on line 508 "Error in event handler for webRequest.onBeforeSendHeaders/4: TypeError: Cannot read property 'heuristicBlockingAccounting' of undefined"
      return badger.heuristicBlocking.heuristicBlockingAccounting(details);
The sixth error is on line 611 "Error in event handler for runtime.onMessage: TypeError: Cannot read property 'getItem' of undefined"
    var disabledSites = settings.getItem("disabledSites");
A Stack Trace showed that these errors appeared in  2 js files.
The first is 
js/background.js:611 (Badger.isPrivacyBadgerEnabled)
 The second is 
js/webrequest.js:662 (dispatcher)
Thats all I found hope this helps to lead you to a new version of this wonderful addon, and thanks for making it. I found these errors for the extension by using the collect errors checkbox on the extensions page. from a IT newbie

**Comment by ghostwords** [comment]
Hello! Where are you seeing these errors? Feel free to post screenshots. When do these errors happen?

**Comment by ghostwords** [comment]
Also, which browser and browser version do you have?

**Comment by ghostwords** [comment]
Do let me know how to reproduce these errors. Closing for now.
