### ISSUE TITLE
Chrome: Some urls not being filtered ?

### ISSUE THREAD

**Issue by lemonsqueeze** [EFForg/privacybadger#2429]
Hi,

Playing with Privacy Badger extension in Chromium i noticed the following:

- enable "Show domains that don't appear to be tracking you" in PB preferences.
- open https://www.leboncoin.fr/recherche/?text=dreamcast&locations=r_22 and block everything.
- reload
- static.criteo.com doesn't show up in the list of 3rd parties  although it looks like it should 
  (shows up in developer tools -> sources)

Bug or evading privacy badger somehow ?

Privacy Badger version 2019.7.1
Chromium 74 on Ubuntu

**Comment by lemonsqueeze** [comment]
Looks like they're using a weird url scheme in html source:

```
<script data-react-helmet="true" type="text/javascript" src="//static.criteo.net/js/px.js?ch=1"></script>

**Comment by lemonsqueeze** [comment]
Firefox extension isn't affected, looks like this is a chrome issue.

**Comment by ghostwords** [comment]
I think neither. The resource is loading from cache, and extensions don't see cached resources (as there is no network request).

![Screenshot from 2019-08-13 09:22:24](https://user-images.githubusercontent.com/794578/62945081-05bfef00-bdac-11e9-8762-8413a94bb30a.png)

**Comment by ghostwords** [comment]
By the way, Privacy Badger is meant to be a no-configuration-necessary, install-and-forget kind of extension. Generally speaking, you should leave the sliders alone and let Privacy Badger do its job automatically.

Let me know if you have any other questions.

**Comment by lemonsqueeze** [comment]
Good to know, thanks.
Would you advise clearing cache on a regular basis so that these get blocked ?

**Comment by ghostwords** [comment]
No, I think that's too much trouble. I'd leave the cache management to the browser.

If you do want to get deeper into exactly what is and isn't allowed on a page, I recommend uMatrix (or uBlock Origin in advanced mode).
