### ISSUE TITLE
Alamo Website: Non-tracking cookie blocked, causing the missing the location search results

### ISSUE THREAD

**Issue by nokisobar** [EFForg/privacybadger#2430]
#### What is your browser and browser version?
Chrome latest official version on Windows 7 Professional Edition (desktop)

#### What is broken and where?

![QA_5330 Aug  14 19 40](https://user-images.githubusercontent.com/53952688/63063878-870ea300-becc-11e9-93c9-8c034fd7aff6.jpg)

#### What is the "culprit" domain?

int1.location.enterprise.com

Privacy Badger somehow identifies this cookie as a tracker when the Alamo website is attempting to pull the information of the locations on its location search result list. This blocked cookie is used specifically for service-driven location search of Solr which is an open-source enterprise-search platform that we have implemented and used in many enterprise-level websites.

The other variance of the *.location.enterprise.com domains is the followings:
xqa1.location.enterprise.com
int2.location.enterprise.com
xqa2.location.enterprise.com
int3.location.enterprise.com
xqa3.location.enterprise.com

#### What is your debug output for this domain?

```
**** ACTION_MAP for enterprise.com
enterprise.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
int1.location.enterprise.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1566236400109,
  "userAction": "user_block"
}
smetrics.enterprise.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1565902339363,
  "userAction": ""
}
xqa1.author.enterprise.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1565955586850,
  "userAction": ""
}
xqa1.location.enterprise.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1566105306999,
  "userAction": ""
}
xqa2.location.enterprise.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1566094330303,
  "userAction": ""
}
**** SNITCH_MAP for enterprise.com
enterprise.com [
  "alamo-usability.com",
  "enterpriseholdings.com",
  "natcar-np.com"
]

```

Please let me know if further information is needed to resolve this blocker for us. Thanks in advance!

**Comment by nokisobar** [comment]
Please whitelist all of these domains for us

```
int1.location.enterprise.com
xqa1.location.enterprise.com
int2.location.enterprise.com
xqa2.location.enterprise.com
int3.location.enterprise.com
xqa3.location.enterprise.com
```

**Comment by ghostwords** [comment]
Previously: #2330.

Looks like we should add a few more domains to the [list for Enterprise Holdings](https://github.com/EFForg/privacybadger/blob/a1621a791605f3b626cc9fe5098dc1afb638d672/src/js/multiDomainFirstParties.js#L539-L609).

**Comment by nokisobar** [comment]
The culprit domain of #2432 (which is the closed ticket) is assets-xqa.nonprod.gcs.ehi.com.
The culprit domain of #2430 (which is this ticket) is *.location.enterprise.com.

**Comment by ghostwords** [comment]
Looks like we should add the following domains to the MDFP list for Enterprise Holdings:
```
alamo-np.ca
alamo-np.com
alamo-np.co.uk
alamo-np.de
alamo-np.es
alamo-np.fr
alamo-np.ie
```

Privacy Badger already knows that `ehi.com` and `enterprise.com` domains belong to the same entity.

**Comment by nokisobar** [comment]
@ghostwords  The domain list of alamo-np is correct! :) Thanks!

**Comment by ghostwords** [comment]
These breakages will be fixed with the next Privacy Badger update.

**Comment by nokisobar** [comment]
@ghostwords  When is the next release of the Privacy Badger? Can you please give me a timeline so that we can look out for it and test it on our Alamo Web as well? Thanks!

**Comment by ghostwords** [comment]
In the next few weeks. Sorry I can't be more specific at this time.

**Comment by nokisobar** [comment]
@ghostwords  Ok. We'll keep checking the site with the Privacy Badger from time to time for the next few weeks then. We really appreciate your prompt reply and quick fix on our issue! Thanks again!

**Comment by ghostwords** [comment]
I suggest subscribing to [Privacy Badger's mailing list](https://lists.eff.org/mailman/listinfo/privacybadger). We send an email to the list after every Privacy Badger update.

**Comment by nokisobar** [comment]
@ghostwords  I just subscribed to the mailing list per your suggestion. Thanks!
