### ISSUE TITLE
Separator characters aren't ignored when estimating entropy for pixel cookie sharing

### ISSUE THREAD

**Issue by ablanathtanalba** [EFForg/privacybadger#2436]
~~At first glance, the pixel tracking heuristic and specifically the `estimateMaxEntropy(str)` function can be optimized. The O(n) notation can definitely be improved upon, and at least one of the helper mechanisms in the algorithm doesn't work as expected.~~ While writing tests for it (#2425) I discovered that the portion for ignoring separator characters `._-` doesn't behave as expected, making strings that should estimate to the same entropy value `'google.analytics/123' , 'google.ana.lytics/123'` actually compute to different entropy values.

**Comment by ghostwords** [comment]
> The O(n) notation can definitely be improved upon

Could you go more into how you would improve it?

**Comment by ghostwords** [comment]
Having discussed this we decided to avoid updating the entropy estimation logic at this point as it isn't clear there is actually a problem to resolve.

Let's just [finish adding test coverage for the entropy estimation function](https://github.com/EFForg/privacybadger/pull/2425#discussion_r315364030).
