### ISSUE TITLE
Conflict with Virtru

### ISSUE THREAD

**Issue by enqacknak** [EFForg/privacybadger#2439]
There is a conflict between privacy badger 2019.7.1 and Virtru 7.11.1.0. If Privacy Badger is enabled, sending an _unencrypted_ attachment can fail. Encrypted attachments work fine. Virtru support indicated that they have seen the conflict before.

**Comment by ghostwords** [comment]
Hello! Is Virtru a website, or an extension? Could you explain how to reproduce this problem?

**Comment by enqacknak** [comment]
Virtru is an extension. Virtru is a commercial product to implement end-to-end encryption in Gmail. Reproduction is simple: have both Virtu and PrivacyBadger installed in Chrome. Attempt to send an email with an attachment of any kind. I was unable to do so. The send process hangs. Encrypted operations, including attachments, work as expected. Disabling  the Privacy Badger extension permits proper operation of Gmail with an unencrypted attachment. Note that I was unable to resolve the problem by turning Privacy Badger off for mail.google.com. I had to disable the Privacy Badger extension in Chrome.

**Comment by ghostwords** [comment]
Does Privacy Badger report blocking any domains in its popup on Gmail after this happens?

**Comment by ghostwords** [comment]
You should be able to work around this problem by visiting Privacy Badger's options page, clicking on the Tracking Domains tab, searching for "virtru.com" and moving the slider for that domain to "green". This will move the slider for any `virtru.com` subdomains.

**Comment by enqacknak** [comment]
There is no visible popup or other indication that Privacy Badger is the source of the conflict. I'll attempt the work-around.

**Comment by ghostwords** [comment]
When I say popup, I mean Privacy Badger's window that opens when you click on the Privacy Badger icon in your browser toolbar.

Would you mind sharing the debugging code output for "virtru.com" by following the instructions on https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain ?

**Comment by enqacknak** [comment]
Workaround did not work. Send still fails. The two screen shots were taken as the send button spun in another window. 
![Screen Shot 2019-08-22 at 10 24 09 AM](https://user-images.githubusercontent.com/54411840/63535808-29c7b280-c4c7-11e9-848c-681bb4575a03.png)
![Screen Shot 2019-08-22 at 10 21 10 AM](https://user-images.githubusercontent.com/54411840/63535815-2d5b3980-c4c7-11e9-8e46-8d29d5f002a0.png)

**Comment by enqacknak** [comment]
Pardon me, another tab...

**Comment by ghostwords** [comment]
Is the above a screenshot of Privacy Badger's popup on Gmail?

Could you share the debugging code output for "virtru.com" by following steps 2 and 3 on https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain ?

**Comment by enqacknak** [comment]
This is with virtru.com and *.virtru.com in the disabled sites list

**** ACTION_MAP for virtru.com
acm.virtru.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1550960650748,
  "userAction": ""
}
apps.virtru.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1566678525967,
  "userAction": ""
}
virtru.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
www.virtru.com {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1528627677181,
  "userAction": ""
}
**** SNITCH_MAP for virtru.com
virtru.com [
  "google.com",
  "ucsb.edu",
  "youtube.com"
]

**Comment by ghostwords** [comment]
OK, thank you. Why would Virtru be seen tracking by Privacy Badger on ucsb.edu and youtube.com? I thought Virtru is a Gmail-specific extension. The answer may quite possibly be a Privacy Badger bug with Gmail (#2335).

>This is with virtru.com and *.virtru.com in the disabled sites list

The Disabled Sites tab isn't the right place to allow `virtru.com`, as Disabled Sites is for disabling Privacy Badger on a site that you visit directly (such as Gmail), and you want to allow a potential tracker to load instead.

You should go to the Tracking Domains tab. Please see [my above comment](https://github.com/EFForg/privacybadger/issues/2439#issuecomment-523994066) again.

**Comment by enqacknak** [comment]
In doing some more research, I am now seeing slightly different behavior. With PB disabled, I can send an unencrypted message, though there is a several second delay. Messages fail to send with PB enabled regardless of whitelisting virtru.com.

**Comment by ghostwords** [comment]
When you say "whitelisting", do you mean moving the slider for virtru.com domains to "green"/allow?

**Comment by enqacknak** [comment]
Thank you for your patience. I did move the sliders for 4 specific tracking sites in the virtru.com domain to green. It did not change the behavior. I apologize for not following the instructions correctly. They were clear, I just didn't read them properly.

**Comment by enqacknak** [comment]
Virtru is a plugin that integrates with the Gmail screen. Note the "V" slider on the top right and the (spinning) indication where the send button normally is. I opened a ticket with Virtru. They claim that Privacy Badger is blocking an action. As to why there appears there may be tracking information for the other sites: ucsb.edu is my work email address. My Gmail account is in the ucsb.edu address so Gmail knows that as the sender. It also ties to my encryption key in the Virtru system. This is speculation. Google I could also speculate as having some nexus to the problem. Youtube? I have no idea why that's showing up.

To summarize:
Though it may not help I added virtru.com and *.virtu.com to the disabled sites list. I searched the  tracking domains tab and found 4 sites in the virtru.com domain and moved the slider for all 4 to green. Neither of these changed the behavior. I can send messages with Privacy Badger disabled as an extension (it does not need to be uninstalled as I previously thought). If you wish to engage with Virtru (and I hope that you do because I value both products) the ticket number to reference is 77879. I'm happy to try additional testing if you would like.

![Screen Shot 2019-08-22 at 2 19 06 PM](https://user-images.githubusercontent.com/54411840/63551026-e1b98780-c4e8-11e9-8766-9dd51e34e7a4.png)

**Comment by ghostwords** [comment]
OK, thank you. Could you rerun the debugging JavaScript again? I want to make sure `virtru.com` was successfully allowed.

**Comment by enqacknak** [comment]
**** ACTION_MAP for virtru.com
acm.virtru.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1550960650748,
  "userAction": ""
}
apps.virtru.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1566678525967,
  "userAction": ""
}
virtru.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": "user_allow"
}
www.virtru.com {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1528627677181,
  "userAction": ""
}
**** SNITCH_MAP for virtru.com
virtru.com [
  "google.com",
  "ucsb.edu",
  "youtube.com"
]

**Comment by ghostwords** [comment]
It looks like the slider modifications weren't applied for whatever reason (probably #1912). We could try this again:

1) Open Badger's options page.
2) Click on the Tracking Domains tab.
3) Search for "virtru".
4) Move the slider for `virtru.com` to "green". Not for any of the subdomains, just for `virtru.com`. If it worked, the sliders for the subdomains should also move to green.
5) Verify it worked by reloading the options page and checking that the slider for `virtru.com` (and all of its subdomains) are green.
6) Reload Gmail and try again.

**Comment by enqacknak** [comment]
I went to do what you asked. Here's what I found.
<img width="856" alt="Screen Shot 2019-08-22 at 3 36 06 PM" src="https://user-images.githubusercontent.com/54411840/63554562-b9cf2180-c4f2-11e9-881c-821fe4ae6c7d.png">

**Comment by ghostwords** [comment]
OK, but reloading Gmail and trying to send with Virtru still doesn't work?

**Comment by enqacknak** [comment]
I tried quitting Chrome completely. I opened GMail and tried to send. The send failed. All the sliders were green when I took the last debug script.

**Comment by enqacknak** [comment]
https://support.virtru.com/hc/en-us/articles/115004987954-Virtru-required-endpoints
