### ISSUE TITLE
`getLocalStorageItems` can throw exception in Firefox

### ISSUE THREAD

**Issue by robertknight** [EFForg/privacybadger#2446]
We've been receiving error reports for our browser extension ([Hypothesis](https://github.com/hypothesis/client)) caused by inline scripts that Privacy Badger injects into iframes to do with supercookie reporting.

The `getLocalStorageItems` function in Privacy Badger tests whether `localStorage` is accessible by just trying to [access the `window.localStorage` property](https://github.com/EFForg/privacybadger/blob/22f4b26bf308d00651e6b2ba797ce326a1985200/src/js/contentscripts/supercookie.js#L33). It seems that in Firefox there are scenarios where this property is readable but returns `null`. This causes errors later on when `getLocalStorageItems` tries to access this value as an object. One way to force this is to happen is to set the `dom.storage.enabled` flag in `about:config` to false.

Sentry report from our app: https://sentry.io/share/issue/4ee0ff95023445d4b427f598f8d2cd9d/

We're just going to ignore/suppress the error on our end to avoid distracting from errors that actually cause problems for users, but I thought this might be useful for the Privacy Badger team to be aware of.

**Comment by hichamelkaddioui** [comment]
Indeed! When local storage is disabled, Firefox returns `null` while Chrome/Safari would raise an Exception.

I created #2447, the fix is based [on this article](http://diveintohtml5.info/detect.html#storage).

**Comment by ghostwords** [comment]
Thank you for the report! I see, this looks like the Firefox version of the "access to localStorage is denied by the browser itself" problem we previously addressed in Chrome (#1739).
