### ISSUE TITLE
Hatena social button is not blocked 

### ISSUE THREAD

**Issue by mdlsr** [EFForg/privacybadger#2448]
Please go to the [page](https://ytnt650.hatenablog.com/entry/2018/04/25/211752):

See social buttons. All buttons seem to be blocked except Hatena (on the left, blue one with B! (satans characters))
This contradicts with my paranoia and I want to fix it. But should I?

**Comment by ghostwords** [comment]
Hello!

Privacy Badger is meant to be a no-configuration-necessary, install-and-forget kind of extension. Generally speaking, you should leave the sliders alone and let Privacy Badger do its job automatically.

I see what you mean though, it is kind of strange that Privacy Badger replaces Twitter and Facebook buttons but doesn't do anything about the button for Hatena.

The direct reasons are that (A) Privacy Badger doesn't see tracking from the button, and that (B) Privacy Badger doesn't know to replace Hatena buttons like it [knows to replace Twitter](https://github.com/EFForg/privacybadger/blob/bf3ab542804f7a23b1de74401df2e17bb6616fa9/src/data/socialwidgets.json#L182-L195) and Facebook. Also, this is a Hatena button on a Hatena-powered blog, which suggests to me we should indeed leave the button alone as the button and the page belong to the same entity/party (Hatena).

Now if we saw that Hatena buttons tracked their users across the Web (not just on Hatena properties), **and** that users still wanted to use these buttons sometimes, we would want to look into adding a Hatena button replacement.

Let me know if you have any questions.
