### ISSUE TITLE
Exported 1800+ trackers, import resulted in 1500

### ISSUE THREAD

**Issue by rugabunda** [EFForg/privacybadger#2449]
Tested with firefox. Every time I export trackers, the number imported  always less than exported, as shown where it says "Privacy Badger has detected # potential tracking domains so far. These sliders let you control how Privacy Badger handles each tracker."

**Comment by rugabunda** [comment]
I then exported the 1500 trackers, the resulting size of the file went from 230, to 200 k or so.

**Comment by ghostwords** [comment]
The counts are different because importing discards any domains that don't make a difference to Privacy Badger's behavior. There shouldn't be any actual problem though. This is related to #1864.
