### ISSUE TITLE
graphitedocs.com broken

### ISSUE THREAD

**Issue by eddiejibson** [EFForg/privacybadger#2450]
#### What is your browser and browser version?
Firefox 70.0b2
#### What is broken and where?
The whole of graphite docs (https://app.graphitedocs.com)

#### What is the "culprit" domain?
core.blockstack.org
hub.blockstack.org
gaia.blockstack.org (Most important, data is stored here)

These shouldn't be broken nor are they trackers, blockstack is a decentralized network which are essential for apps like these to function.

**Comment by ghostwords** [comment]
Hello! Could you provide the debug info for "blockstack.org"? Please see steps 2 and 3 of https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain

**Comment by ghostwords** [comment]
Also, does setting all `blockstack.org` to "yellow" work around the problem?

**Comment by eddiejibson** [comment]
Yes, setting to yellow does.


9 Sep 2019, 16:45 by notifications@github.com:
