### ISSUE TITLE
nahvus.com blocked, my CDN

### ISSUE THREAD

**Issue by NAHVUSdev** [EFForg/privacybadger#2453]
#### What is your browser and browser version?
Firefox, v68.0.2

#### What is broken and where?
Privacy Badger is blocking the domain, and the domain provides stylesheets and scripts to my websites

#### What is the "culprit" domain?
nahvus.com

#### What is your debug output for this domain?
```


**** ACTION_MAP for nahvus.com
nahvus.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1567609353626
}
**** SNITCH_MAP for nahvus.com
nahvus.com [
  "localhost",
  "travislawrencestudios.com",
  "newtonasi.com"
]

```

**Comment by ghostwords** [comment]
Hello and thanks for filing an issue.

I don't know what exactly is happening as your sites seem to be down for maintenance at this time. My guess is that this is a case of (session?) cookies being sent along CDN requests. Previously-set cookies for `nahvus.com` are sent along with requests for static resources from `nahvus.com`. Privacy Badger sees the cookies in this third-party context and considers it to be an instance of tracking.

You could work around this issue by avoiding sending cookies along with requests for static resources, perhaps by using a different domain for your CDN (one that doesn't get or set cookies), and/or by changing the scoping for the (what should probably be exclusively first-party) cookies.

Let me know if you have any questions.
