### ISSUE TITLE
Breaks widgets from windy.com

### ISSUE THREAD

**Issue by StewAlexanderACC** [EFForg/privacybadger#2458]
Embedded html "widgets" from twitter, windy.com and darksky.com do not render with Privacy Badger enabled.

My website: https://stewalexander.com/weather.html with the Privacy Badger extension enabled using Chrome version 76.0.3809.132 (Official Build) (64-bit) looks like this:

![image](https://user-images.githubusercontent.com/48565067/64624834-3bf78b00-d3b9-11e9-8a57-fecbfbea5ab0.png)

With Privacy Badger disabled it looks like this (while still using Google Chrome):

![image](https://user-images.githubusercontent.com/48565067/64624934-63e6ee80-d3b9-11e9-88b6-ee42a08bcaf6.png)

**Comment by StewAlexanderACC** [comment]
The widgets use <iframe> and <script> tags

**Comment by StewAlexanderACC** [comment]
Another page of mine:
https://www.stewalexander.com/nuevovallarta.html

With Privacy Badger Disabled:
![image](https://user-images.githubusercontent.com/48565067/64625243-d788fb80-d3b9-11e9-831c-10ef6de64a36.png)

With Privacy Badger Enabled:
![image](https://user-images.githubusercontent.com/48565067/64625319-f1c2d980-d3b9-11e9-9db3-8e54c6202366.png)

**Comment by ghostwords** [comment]
Hello and thanks for letting us know about this problem! Looks like we should do something about weather widgets from windy.com.

**Comment by ghostwords** [comment]
I just added `windy.com` to Privacy Badger's yellowlist (list of domains that Privacy Badger will allow to load while blocking access to things like cookies). You should be able to test this for yourself now by restarting your browser.

**Comment by StewAlexanderACC** [comment]
Yep, the windy widgets load now correctly thank you
