### ISSUE TITLE
trustedform.com

### ISSUE THREAD

**Issue by mrjuicebox** [EFForg/privacybadger#2468]
#### What is your browser and browser version?
Google Chrome
Version 77.0.3865.90 (Official Build) (64-bit)

#### What is broken and where?
The trustedform.com domain being blocked. The TrustedForm script is added by site owners to document legal compliance with the Telephone Consumer Protection Act (TCPA). The TCPA requires that companies document that they have prior express written consent to contact consumers on their mobile phones via text or auto-dialing systems. You will only see the TrustedForm script on pages with a web form, as it is there to document that the consumer consented to the legal disclosures present on that page. When TrustedForm is blocked, the site owner is not able to document consumer consent. As a result, the consumer who is requesting to be contacted by the company might not be contacted due to TCPA compliance risk. Please note that the Trustedform script doesn’t cookie users, share data with third parties, or engage in any cross-site tracking. 

For this reason, we respectfully ask that you add it to the yellow list. If you need more information about TrustedForm to complete your review, I am happy to discuss it in more detail.

#### What is the "culprit" domain?
trustedform.com

#### What is your debug output for this domain?
```
**** ACTION_MAP for trustedform.com
api.trustedform.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1569602146873
}
trustedform.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
api.staging.trustedform.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1569488013584
}
**** SNITCH_MAP for trustedform.com
trustedform.com [
  "activeprospect.com",
  "mrjuicebox.github.io",
  "activeprospect.github.io"
]
```

**Comment by ghostwords** [comment]
Hello! It looks like Privacy Badger is picking up canvas fingerprinting from `api.trustedform.com` on https://activeprospect.com/.

Here is a slightly cleaned-up version of the script in question: https://gist.github.com/ghostwords/dab9d8728a20d4eabf37b1e140a9f6da

Could you explain what's going on there?

**Comment by ghostwords** [comment]
Let me know if you have more information. Closing for now.
