### ISSUE TITLE
Privacy Badger breaks sorting on online store (gigantti.fi)

### ISSUE THREAD

**Issue by Kadioc** [EFForg/privacybadger#2472]
#### What is your browser and browser version?

Firefox 69.0.1, 64bit

#### What is broken and where?

`https://www.gigantti.fi/catalog/gaming/fi-pelikannettavat/pelikannettavat` - the sorting options on this site don't work when Privacy Badger is enabled, but they work the moment I disable it. Here's screenshots to explain the issue:

`https://imgtc.ws/FKtY7Q1` (from expensive to cheap)
`https://imgtc.ws/2ZPfOIJ` (from cheap to expensive)

#### What is the "culprit" domain?
Possibly `cdn-eu.dynamicyield.com`, but I can't check any further since there isn't a debug button in about:debugging anymore.

#### What is your debug output for this domain?
Can't find any debug output, due to aforementioned debugger problem. The only button is the Inspector and I don't know how to use it. I've looked through almost the entire Inspector, but I just can't seem to find any way to debug an addon.

**Comment by ghostwords** [comment]
Hello and thanks for the report! It sounds like we need to update our debugging instructions. The new instructions are something like the following:
1. Visit `about:debugging`
2. Click on "This Firefox"
3. Find Privacy Badger and click the Inspect button for Privacy Badger
4. Select the Console tab. (I think Inspector is selected by default.)
5. The copying, pasting, editing and running the code step should be the same.

**Comment by ghostwords** [comment]
Possibly related: #1218.

**Comment by Kadioc** [comment]
Here we go, I got the Action Map stuff, in case it will help anymore.

**** ACTION_MAP for dynamicyield.com
dynamicyield.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
rcom-eu.dynamicyield.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1570705127709
}
st-eu.dynamicyield.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1570387228632
}
cdn-eu.dynamicyield.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1570526316813
}
**** SNITCH_MAP for dynamicyield.com
dynamicyield.com [
  "cnbc.com",
  "barnesandnoble.com",
  "bild.de"
]
