### ISSUE TITLE
"Why does Privacy Badger allow all these trackers?"

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#2477]
There seems to be a good deal of confusion caused by domains that Privacy Badger "allows by default":

- From a [Reddit thread](https://www.reddit.com/r/privacytoolsIO/comments/d2y9ta/why_privacy_badger_allow_some_tracking_domains_as/) (with no good answers):

  >After I first installed Privacy Badger, I seen that it includes more than 1000 predefined domains in Tracking Sites tab in its settings but most of them are allowed:
  >
  >I understand that all of these tracking sites must be blocked as default. Is this OK?
- From an AMO review:

  >As default, Privacy Badger allows more than 1000 tracking domains. Why? So I do not use it!
- From a support email:

  >I have noticed that Privacy Badger is keeping domains that are green 
("Allowed") in the "Options", "Tracking Domains" list.
  >
  >I thought only those that tracked a user around the Internet and needed 
either their cookies or domains blocked (yellow or red) would be included 
in this list?
- From another email:

  >I was surprised to look at the list of tracking domains in the plugin settings 
  >showing many marked as green despite being known trackers (including some 
  >domains with the word "track" in their names. It took me a long time to go 
  >through the list of 1000+ domains and marking them individually as yellow or 
  >red...

The answer is that Privacy Badger's list is not fixed; Privacy Badger learns from your browsing. When you first install Privacy Badger, it comes with a [pre-trained](https://www.eff.org/deeplinks/2018/08/giving-privacy-badger-jump-start) list of tracking domains. Privacy Badger starts blocking a domain once it sees it track on three separate sites. The idea is to automatically stop tracking across the Web while reducing breakage. So, all the "allowed" domains are actually just not-yet-blocked domains.

This is related to #1374, which was mostly (but as we can see not entirely) addressed by #1891.

Related to #1675 and #2021.

**Comment by 3esmit** [comment]
but why allow them at anytime if you already know them?

**Comment by ghostwords** [comment]
The idea behind the current "three strikes" system is to stop tracking across the Web while reducing breakage. Not all domains that look like trackers are actual trackers.

**Comment by 3esmit** [comment]
I understand the idea of "three strikes" and I find it awesome! 

However. for me, the confusion with Privacy Badger is:
1. Having that list in first place. If the system automatically detects, why having the list? 
2. If the list contains websites that are actual trackers, why don't have them blocked from start, or at least in "cookie blocked"?
3. If the list contained only "resource"-like domains and that domains could be automatically blocked in case used for tracking, awesome, but the list contains things that are obviously trackers marked as green.
4. If the user set something to green, it can be striked?

**Comment by ghostwords** [comment]
I'm not sure I understand ... The list is the output of Privacy Badger's rules.

Are you asking why we don't just take a list of "known trackers" and plug it into Privacy Badger? Privacy Badger was specifically created to be a privacy tools that works without manually-assembled blacklists. Please see the [FAQ](https://www.eff.org/privacybadger/faq) for more.

User slider settings override Privacy Badger's decisions. Users frequently end up breaking the Web for themselves (#2021).
