### ISSUE TITLE
Indicate when first-party protections are active

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#2482]
>Besides automatic tracker blocking, Privacy Badger removes outgoing link click tracking on [Facebook](https://www.eff.org/deeplinks/2018/05/privacy-badger-rolls-out-new-ways-fight-facebook-tracking) and [Google](https://www.eff.org/deeplinks/2018/10/privacy-badger-now-fights-more-sneaky-google-tracking), with more privacy protections on the way.

The thing is that we don't advertise that this happens anywhere in the UI. But we should! We should inform the user when Privacy Badger is actively removing tracking from outgoing links on Facebook and Google.

**Comment by 82ba10b5e8dc** [comment]
@ghostwords I can try to help on this one, were you imagining this would be something that added additional styling to the link itself that showed it's being sanitized or rather displayed in the extension popup?

**Comment by ghostwords** [comment]
Definitely in the popup. Let's not mess with webpages any more than we have to.

**Comment by 82ba10b5e8dc** [comment]
Sounds good, I'll give it a try and post back with what I have.
