### ISSUE TITLE
Privacy Badger Missing A Lot of Tracking Links

### ISSUE THREAD

**Issue by HURSSGH** [EFForg/privacybadger#2483]
Hi,

Recently, it seems as though PB is missing more tracking links associated with social buttons than it is blocking.

For example, on the BBC, PB does not flag any of the tracking buttons at the bottom of the story ("Share this story" section). Here is one story where FB Container blocks FB, but PB misses all the other tracking buttons.
https://www.bbc.com/news/disability-49584591

Note: I have been reporting some pages with issues using the PB "break this site" tool, but thought I would open a case to facilitate dialog if so required.

Thanks for the great tool!

**Comment by ghostwords** [comment]
Hello! Are you talking about these social sharing buttons?

![Screenshot from 2019-10-19 10:48:41](https://user-images.githubusercontent.com/794578/67146928-25690d00-f25e-11e9-9895-fd1a664c020c.png)

The reason Privacy Badger doesn't do anything about them is that these aren't actually the official buttons that track you by default, but rather some sort of custom implementation that doesn't seem to contact facebook.com (or any other social domains). Does this help?

I can see how this is confusing, but I'm not sure what Privacy Badger can do about it.

**Comment by HURSSGH** [comment]
Hi,
I'm sorry, but I totally disagree with your analysis of the buttons.
When you click on one of those buttons, the social site clicked DOES
track that you visited that site and it becomes a part of your
history. The buttons are no different than a "Like" button in the
amount of information they collect about you. They are simply another
means of tracking you, and as trackers, they should be disabled.
Please either reconsider your position on this issue, or update your
Privacy Badger documentation to explain that you allow sites to track
you when you share a story. The documentation of what PB does verses
the reality of the share buttons provides users a false assurance that
their sharing of stories will not be tracked, whereas reality is that
it only adds to the user's history.
What should you do? You should set the links to "RED" by default and
if the user leaves them at "RED" anything but "GREEN", then you should
disable the link to that site.

Thank you for reconsidering.
JRK
On 10/19/2019 at 10:51 AM, "Alexei"  wrote:

	Hello! Are you talking about these social sharing buttons? 
	The reason Privacy Badger doesn't do anything about them is that
these aren't actually the official buttons that track you by default,
but rather some sort of custom implementation that doesn't seem to
contact facebook.com (or any other social domains). Does this help? 

	I can see how this is confusing, but I'm not sure what Privacy Badger
can do about it.

**Comment by ghostwords** [comment]
The "share on Facebook" button on the BBC page is an [image](https://static.bbc.co.uk/news/1.295.03454/img/sprite-sharetools.png), served by the same domain as the site itself, that links to `facebook.com`. This is essentially the same as a text link that points to some page on Facebook. Neither one tracks you by default.

Whereas the official Facebook Share button is served by Facebook itself but is directly embedded into other websites. This does allow Facebook to track you by default.

**Comment by ghostwords** [comment]
>The documentation of what PB does verses the reality of the share buttons provides users a false assurance that their sharing of stories will not be tracked

Could you point to where you think Privacy Badger makes this claim? We may be confusing Facebook Container and Privacy Badger's functionality ...
