### ISSUE TITLE
Privacy Badger causing Kayak.com links to crash

### ISSUE THREAD

**Issue by andyboza** [EFForg/privacybadger#2494]
I would like to report that the Privacy Badger extension on Chrome is making Kayak.com links to crash. I have to disable the extension and reload the link again in order to view the content.

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch! Could you describe what you mean in more detail please? Feel free to include screenshots.

**Comment by ghostwords** [comment]
By the way, did you know you can disable Privacy Badger on specific websites, while leaving it enabled elsewhere? To do this, click on the "Disable Privacy Badger for This Site" button in Badger's popup while on the problem site.
