### ISSUE TITLE
Privacy badger crashed on https://rust-lang.github.io/rustfmt/

### ISSUE THREAD

**Issue by jyn514** [EFForg/privacybadger#2495]
Browser: `Mozilla Firefox 70.0`
Privacy Badger version: `2019.10.28`
Other extensions installed:
- uBlock origin
- uMatrix
- HTTPS Everywhere
- Regex search
- foxyproxy
- Firefox Containers

I enabled a few things in uMatrix and it worked when I reloaded the page. I don't know where to find a stack trace or anything like that, if you know how to find that I'm happy to post it.

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch!

- When you say, Privacy Badger crashed, what do you mean? Feel free to attach screenshots.
- Could you post a sequence of steps starting in a new Firefox profile for reproducing this behavior?

**Comment by jyn514** [comment]
It showed a little exclamation mark in the toolbar and when I clicked on the icon it said that it crashed. Unfortunately I'm having trouble reproducing the behavior.

**Comment by ghostwords** [comment]
OK, thank you. Please let us know if you find steps to reproduce from a new Firefox profile.

**Comment by ghostwords** [comment]
Closing for now.
