### ISSUE TITLE
Badger crashes Microsoft Edge Chromium

### ISSUE THREAD

**Issue by toinevl** [EFForg/privacybadger#2500]
When I have activated the Badger in Edge Chromium, any URL will crash Edge Chromium. Deactivating the extension will restore normal operation of the browser. Edge Chromium Version 80.0.320.4 (Official build) dev (64-bit) / Privacy Badger version 2019.10.28

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch!

Does this happen with a similar version of Chromium? When did this start happening (was it a Edge update or a Privacy Badger update)?

An extension should never be able to crash the browser. If this is indeed Edge-specific, could you open an issue with Edge, and link to it here, if you can?

**Comment by toinevl** [comment]
Hi,
What do you mean with a “similar version of Chromium”? I noticed this behavior already a few dev releases earlier of Edge Chromium so I don’t think it’s triggered (solely) by an update of Badger. I’ll file an issue with the Edge team in parallel.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ghostwords** [comment]
>What do you mean with a “similar version of Chromium”?

I mean, is this Edge-specific, or does it also happen in the version of Chromium your Edge build is based on?

**Comment by ghostwords** [comment]
Closing for now as I haven't seen any other reports.
