### ISSUE TITLE
"version null" PB completely broken on firefox 70.0.1

### ISSUE THREAD

**Issue by lucidsleepy** [EFForg/privacybadger#2504]
#### What is your browser and browser version?

Firefox 70.0.1

#### What is broken and where?

Dipslays "verion null" and doesnt work, non of the buttons work either.

**Comment by ghostwords** [comment]
Hello and thanks for writing! Do you know if this happened following a Firefox update?

Could you open Privacy Badger's background page and share the contents or a screenshot of the Console tab?

To open Privacy Badger's background page in Firefox:

- Navigate to `about:debugging`
- Click on "This Firefox"
- Scroll down to find the entry for Privacy Badger and click "Inspect"
- Select the Console tab

**Comment by lucidsleepy** [comment]
I resolved it by reinstalling firefox, apperantly uBlock Origin also stopped working.

**Comment by ghostwords** [comment]
OK, thanks for the update. This looks to be a Firefox bug, probably one where extension storage gets corrupted, probably on browser update.
