### ISSUE TITLE
broken site: vanguard.com

### ISSUE THREAD

**Issue by ftobin** [EFForg/privacybadger#2507]
Vanguard's site for personal investors (https://investor.vanguard.com) breaks.  It's hard to tell from the main page (https://investor.vanguard.com) since you have to login for it to break, but it's easy to see that the alternative login page https://personal.vanguard.com/us/hnwnesc/nesc/LoginPage is broken:

![Screenshot_2019-11-13 Log on to vanguard com - personal investors(1)](https://user-images.githubusercontent.com/3298600/68826533-56294000-066c-11ea-97a2-0be7d398ddd0.png)

It should look like this:
![Screenshot_2019-11-13 Log on to vanguard com - personal investors(2)](https://user-images.githubusercontent.com/3298600/68826572-7822c280-066c-11ea-9b7e-62994856eb69.png)

**Comment by ghostwords** [comment]
This seems like something that should have been fixed by #2485. Which version of Privacy Badger do you have? What does Privacy Badger report as blocked on the site?

**Comment by ftobin** [comment]
I have version 2019.10.8.  #2485 would have been after that date and from the commentary looks like it would be applicable, but for some reason Firefox isn't updating to version 2019.10.28 (something I need to look into separately).  I'm closing this bug since I don't have the latest version and it probably would be fixed in it.

Additionally, unfortunately I can't reproduce anymore because I told Privacy Badger to disable itself on the site, and re-enabling doesn't reproduce -- there must have been an internal state change in Privacy Badger by disabling.

**Comment by ghostwords** [comment]
Could you let me know how upgrading works out? Wondering if there is some sort of Firefox bug here.

Disabling and re-enabling on a site shouldn't change anything about Badger's state outside of whether to act or not on a site ... I'm guessing the resources Badger would have blocked otherwise are being loaded from the browser cache. You should be able to reproduce the problem with a ["hard" reload](https://stackoverflow.com/questions/14969315/whats-the-difference-between-normal-reload-hard-reload-and-empty-cache-a).

**Comment by ftobin** [comment]
I noticed I had a bunch of addons not updating. On a hunch, I disabled Firefox Private Network and that allowed them to update immediately.  I send feedback to FPN about it (will likely post on r/Firefox too, since that's a pretty serious bug).  

Privacy Badger had gotten updated in the process to 2019.10.28. Doing a hard-reload now doesn't break the page, so most likely it got fixed.

**Comment by ftobin** [comment]
I noticed I had a bunch of addons not updating. On a hunch, I disabled Firefox Private Network and that allowed them to update immediately.  I send feedback to FPN about it (will likely post on r/Firefox too, since that's a pretty serious bug).  

Privacy Badger had gotten updated in the process to 2019.10.28. Doing a hard-reload now doesn't break the page, so most likely it got fixed.
