### ISSUE TITLE
Narrowness when constrained to the menu in Waterfox Classic on Mac OS X Lion

### ISSUE THREAD

**Issue by grahamperrin** [EFForg/privacybadger#2508]
Edge case, spun off from https://redd.it/dwk7yw

No problem with home-built [Waterfox Classic](https://www.waterfox.net/releases/) 2019.10 (20191103135811) on FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/68924416-b4dbe000-0778-11ea-98b3-2cd9ab46e2e0.png)

- there's a vertical scroll bar ☑

Inset – Mac OS X 10.7.5: 

![image](https://user-images.githubusercontent.com/192271/68924571-0ab08800-0779-11ea-8f3f-1bf9bec7ca56.png)

- where the array of three items should be horizontal, it's vertical
- and (I guess) a vertical scroll bar is, or will be, invisible. 

I'm relaying information; I'm not the affected user. 

Any possibility of a fix? Or are systems such as Lion out of scope?

I assume that it'll be not easy to fix for so narrow a menu. 

TIA

**Comment by grahamperrin** [comment]
Mac OS X 10.7.5 and Privacy Badger aside, for a moment … 

A few months ago, I experimented with `chrome/userChrome.css` alteration of the menu for a more obscure use case: 

- [Shifting the Firefox Sync icon to the left : FirefoxCSS](https://www.reddit.com/r/FirefoxCSS/comments/7zdxsc/shifting_the_firefox_sync_icon_to_the_left/)

----

Back to the Mac: might `userChrome.css` be a solution in this Privacy Badger case?

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch!

Previously: #1120 fixed by #2158

It seems like regular Firefox no longer forces extension popups into narrow menus.

If somebody were to offer a popup CSS tweak that improves display in this scenario, I'll be happy to review it, but really we shouldn't spend much time on a cosmetic issue with a workaround (don't move Privacy Badger to the menu) for an unsupported browser.

**Comment by grahamperrin** [comment]
Thanks. 

I don't have a Mac to verify this but other workarounds _probably_ include legacy extensions such as Vertical Toolbar and Puzzle Bars. Respectively: 

![image](https://user-images.githubusercontent.com/192271/68984759-e18c0800-0809-11ea-814d-e09a40561a50.png)

![image](https://user-images.githubusercontent.com/192271/68984913-c40b6e00-080a-11ea-907c-b637acf3f376.png)

Or the bookmarks toolbar: 

![image](https://user-images.githubusercontent.com/192271/68985011-688db000-080b-11ea-8c22-d67a98a3d184.png)
