### ISSUE TITLE
Fix feeds.soundcloud.com for podcast apps (e.g. player.fm)

### ISSUE THREAD

**Issue by ldexterldesign** [EFForg/privacybadger#2509]
https://player.fm/series/fright-club-podcast-2424170/fc-167-frightful-travels-abroad
http://feeds.soundcloud.com/stream/714388138-frightclub-fc-167-frightful-travels-abroad.mp3

Hi all,

Hope you're well

Thanks for software

Privacy Badger is blocking my podcast today

I assume this should be handled by adding a feeds.soundcloud.com rule, rather than a player.fm one?:

* If true then would it be a good idea to add one
* If false then can someone direct me to the rule(s) in the codebase so I can improve my codebase knowledge

If you have any issues (e.g. questions/queries) then happy to help

Keep up great work!

Yours hopefully

**Comment by ghostwords** [comment]
Hello and thanks for the report! I just added `feeds.soundcloud.com` to Privacy Badger's yellowlist (list of domains that Privacy Badger will allow to load while blocking access to things
like cookies). You should be able to test this for yourself now by restarting your browser.
