### ISSUE TITLE
Link cleaning not working on messenger.com

### ISSUE THREAD

**Issue by vari** [EFForg/privacybadger#2513]
I could be misunderstanding how the extension is supposed to work, but from what I can tell, if the extension is enabled, then links on messenger.com should not contain tracking. However, after installing and enabling the privacy badger extension, when I click on a link sent by a friend on messenger.com, I still see a tracking url redirect. 

Is this expected behaviour? If not, let me know what information I should provide to help debug.

**Comment by ghostwords** [comment]
Hello and thanks for letting us know!

It looks like link cleaning is not working on `messenger.com` as we look for `www.messenger.com/l.php?` links while the actual wrapped links start with `l.messenger.com/l.php?`.

We should update our [wrapped Facebook link discovery](https://github.com/EFForg/privacybadger/blob/8d4eedaf9eddc1f2b221e013345d765c74c0ec83/src/js/firstparties/facebook.js#L5) (perhaps to something like [that in FacebookTrackingRemoval](https://github.com/mgziminsky/FacebookTrackingRemoval/commit/36eefd76a457864c580b8d63157b90c54f3935d2#diff-bd9c9dcd314f2d7df52935b3a6a4d504)).

**Comment by ghostwords** [comment]
Previously: #2316

**Comment by vari** [comment]
Is a fix currently being worked on for the broken link cleaning? If not, I can probably look into it over the weekend.

**Comment by ghostwords** [comment]
@vari Sounds good!
