### ISSUE TITLE
if Matomo is on server installed, all content from this server will blocked

### ISSUE THREAD

**Issue by supervisitor** [EFForg/privacybadger#2517]
#### What is your browser and browser version?
Opera for Mac OS X 64.0.3417.92, 65.0.3467.62

#### What is broken and where?
if PB detects the Matomo script, it will not block only the tracking-script and/or the 1pixel-pict, PB blocks all from this server by default?! (all CSS, pics, etc.)
https://mailr.eu/ , https://webn.eu/ , ...
(I found the bug at the intranet, rebuild it at my private extranet, so you can see it at a public site)

#### What is the "culprit" domain?
https://cdn.goetze.it

#### What is your debug output for this domain?
... this debug output I don't find at Opera...

**Comment by ghostwords** [comment]
Hello!

Accessing Privacy Badger's background page console on Opera should be similar to doing it on Chrome. You start by going to `opera:extensions`, and then click "Developer Mode".

Matomo (formerly Piwik) is a self-hosted analytics platform. My question is why does Privacy Badger learn to block it in the first place? Could you give me some steps that will let me reproduce this problem if I start with a fresh Privacy Badger install?

**Comment by supervisitor** [comment]
Hi & sorry for this long latency...

I don't know why PB is blocking the Matomo host? But what I can report: I've test it from some different systems (at the office I pick 4 of different networks/departments/configurations) and always the same: PB broke all public pages at https://mailr.eu/ , https://webn.eu/ , ... all the sites which host some special content at https://cdn.goetze.it .

One more you should look for: this https://cdn.goetze.it has some special protection mechanisms to enforce privacy rules. For example: the css file for webn.eu is hosted at the cdn.goetze.it, this file will exported to the browser when you visit the page, but you are not allowed to have a look to the css directly. You can not open: https://cdn.goetze.it/pics.We/anim.css , this request will be redirect to your outside IP. 🤓 This is wanted and working with all OSes/Browsers... could be that PB deletes the HTTP referer from the request? If so, this could be the reason... and there should be a solution for, because this is not the only one host who has this implemented.

Cheers...

**Comment by supervisitor** [comment]
... since then I had the problem one or the other time. But now I found a workaround (and don't see the problem since about 6 months):
1. open PB options
2. choose the "Manage Data" tab
3. first "Remove all tracking domains"
4. then "Reset tracking domains"
5. now restart Browser... all working fine since then...

it looks like it was a initial problem when generating the default rules, I guess...
