### ISSUE TITLE
Broken UI in Android

### ISSUE THREAD

**Issue by finn0** [EFForg/privacybadger#2519]
#### What is your browser and browser version?
OS: Android
Browser: Firefox 
Version: 68.3.0
Privacy Badger version: 2019.11.18

#### What is broken and where?

Dashboard UI is broken.

<img alt="privacy-badger" src="https://user-images.githubusercontent.com/28824347/70415239-1c254100-1a54-11ea-908b-7832ee623bfd.png" width=400px>

Fig 1: **allow** icon is in next line.

<img alt="privacy-badger" src="https://user-images.githubusercontent.com/28824347/70416030-f8fb9100-1a55-11ea-9062-a76504d4cf4d.png" width=400px>

Fig 2: Cannot click on **reset** icon and some part of UI is striped.

### Steps to reproduce
- Open any website which might contain tracker(s). For example: https://discourse.org.
- Click on triple dot icon present in action bar.
- Select **Privacy Badger**.

Look into the dashboard, **allow** icon is in next line, cannot click on **reset** icon etc. Seems like problem is with CSS rule.

**Comment by ghostwords** [comment]
Hello and thanks for the report!

It looks like we need to make some tweaks to support narrow displays better.

A recent somewhat related report: #2508

**Comment by brampitoyo** [comment]
@ghostwords Hi, Bram here from Mozilla add-ons UX.

I’m proposing some CSS tweaks for Privacy Badger’s mobile layout (360dp width), as follows:

    /* Set width to 360dp and reduce paddings a little */

    body {
    width: 360px;
    padding: 8px;
    }

    /* Options, Share and Help icons should have more padding, so they’re easier to tap */

    #options {
        padding-top: 8px;
    } 
    #share, #help {
        padding-right: 10px;
        padding-top: 8px;
    }

    /* Instructional text size can be made smaller, to allow more space for controls */

    #pbInstructions {
        font-size: 14px;
    }

    /* Fix key tooltip images so they fit 360dp width */

    .key {
        padding-left: 216px;
    }

    .key img {
        margin-left: 14px;
    }

    /* Fix switch container box size */

    .switch-container {
        width: 100px;
        margin-left: 220px;
    }

    /* Enlarge switch toggles so they’re easier to tap */
    /* They look overly inflated! Is there a better height? 24px, 32px or 36px? */

    .switch-toggle {
        height: 40px;
    }

    /* Fix font size of “Not yet blocked” text to fit 360dp width */

    #not-yet-blocked-header, #non-trackers-header {
        font-size: 12px;
    }

I might have overlooked some things. Let me know if this is a useful start towards fixing this issue?

**Comment by ghostwords** [comment]
Thanks @brampitoyo! This gave me some ideas. We'll start by fixing the obvious display defects; may do a followup later (to improve tap targets, etc.).

**Comment by brampitoyo** [comment]
Thanks @ghostwords. I hope the tweaks can easily be made responsive. Let me know if I can help further – would be happy to!
