### ISSUE TITLE
logos.com family of sites broken

### ISSUE THREAD

**Issue by markbarnes** [EFForg/privacybadger#2523]
Periodically, logos.com and its sister sites periodically get broken, I think because of a multi-domain first party issue.

*.faithlifecdn.com and *.logoscdn.com should be treated as first-party domains for logos.com, verbum.com, faithlife.com and others.

I'm happy to help with further diagnostics if you give me instructions. Most recently the issue I encountered was on a page only available to authenticated users.

**Comment by ghostwords** [comment]
So far I got the following first-party domains for Faithlife:
```
faithlife.com
logos.com
verbum.com
biblia.com
```
Does Privacy Badger actually learn to block the CDN domains?

**Comment by markbarnes** [comment]
> So far I got the following first-party domains for Faithlife:
Those are the main ones, and the ones I've experienced trouble with. They do own dozens of other domains for various microsites. I'll link this issue with the one I've created with the Faithlife web devs in case they want to add some input.

> Does Privacy Badger actually learn to block the CDN domains?
Yes. I _think_ it's only been doing so since the new heuristic update in July. Happy to help with any diagnostics you need.

**Comment by markbarnes** [comment]
Other important domains include:
reftagger.com, proclaimonline.com, biblescreen.com, ministrytracker.com, faithlifetv.com, lexhampress.com, biblestudymagazine.com, didaktikosjournal.com, kirkdalepress.com

I've also found they've got a third cdn at faithlifesitescdn.com
