### ISSUE TITLE
Privacy Badger breaks blitz.gg

### ISSUE THREAD

**Issue by NatoBoram** [EFForg/privacybadger#2525]
URL : https://blitz.gg/lol/match/na1/WhiteStarPhD/3235840166

Without : 

![image](https://user-images.githubusercontent.com/10495562/70866526-ddeabe80-1f38-11ea-81af-8ac7b1d88115.png)

With : 

![image](https://user-images.githubusercontent.com/10495562/70866532-efcc6180-1f38-11ea-8635-d6e1cc23162d.png)

If you need more info, it'd be nice to add an issue template!

**Comment by bcyphers** [comment]
At a glance, it looks like the issue might be with "ddragon.leagueoflegends.com". Is that blocked on your browser? And if so, does dragging the slider to cookieblock (yellow) fix the issue?

**Comment by NatoBoram** [comment]
Yes! I opened the website with multiple browsers, and they all showed this issue because I installed Privacy Badger everywhere. After I manually checked Privacy Badger's config, I saw that it blocked ddragon.leagueoflegends.com, so I whitelisted it and now it works.
