### ISSUE TITLE
URL cleanup

### ISSUE THREAD

**Issue by Avamander** [EFForg/privacybadger#2529]
There's https://github.com/EFForg/privacybadger/issues/681 but it doesn't really solve the issue, even if there are plugins out there that try to solve this. Primarily because plugins that have to get access to every page are a security risk, I'd appreciate a trustworthy entity developing such a plugin, and for Chromium and Firefox both. So I kindly request this is reconsidered to be added as an experimental feature to PB.

Tracking ID cleanup from URLs seems to me as important as blocking tracking scripts and seems like a fitting addition to PB. Not to mention that all the plugins and scripts I've currently tried fail on more obscure sites and that's primarily a popularity issue - PB would get more contributions.

**Comment by ghostwords** [comment]
Hello! I don't understand, isn't #681 about the same thing, removing tracking parameters from URLs?

**Comment by Avamander** [comment]
Yes, but the tracking issue still exists and it should be reevaluated if this functionality is to be added to PB.

**Comment by ghostwords** [comment]
OK, well, I'll close this as a duplicate then.

This feature is still indeed on the table of potential future improvements.
