### ISSUE TITLE
[Partly not working] Strip "fbclid" from Facebook outgoing links

### ISSUE THREAD

**Issue by iVoka** [EFForg/privacybadger#2531]
The function of Privacy Badger that strips "fbclid" parameter from outgoing links is only half working.
It is being stripped from the link that is in the post's text, but not from the preview image link.

Steps to reproduce:
(1) Find a random news post/youtube video/whatever.
(2) Create a new FB feed post containing the link of the above object.
(3) Make sure a preview is fetched from the object (news article image/youtube thumbnail/etc.)
(4) Post it and then view the result: fbclid is missing from the link in the text, but it's there in the preview.

**Comment by ghostwords** [comment]
Hello and thanks for the report! Does this happen consistently, or only on some page loads?

**Comment by iVoka** [comment]
It happens always.

**Comment by iVoka** [comment]
The issue got fixed for a period of time, but now I'm once again seeing fbclid on facebook outgoing links, when I visit them I see this parameter in the url.

**Comment by omichalek** [comment]
Using Chrome, I have **fbclid** present in facebook-outgoing links as well. Cannot say with certainty for Firefox as I don't use my main browser for Facebook but when I paste the same link into Firefox it does get cleaned.

**Comment by ghostwords** [comment]
Thanks for the nudge! We should have this fixed in the next update.
