### ISSUE TITLE
Unsplash integrations are broken

### ISSUE THREAD

**Issue by socksy** [EFForg/privacybadger#2538]
#### What is your browser and browser version?
Firefox 69.0.2

#### What is broken and where?
Any Unsplash images and XHR calls to the unsplash API

#### What is the "culprit" domain?
images.unsplash.com
```

**** ACTION_MAP for unsplash.com
unsplash.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
api.unsplash.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1579308994504
}
images.unsplash.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1579408886368
}
**** SNITCH_MAP for unsplash.com
unsplash.com [
  [XXX],
  "localhost",
  "anildash.com"
]

debugger eval code:26:13
```

(`[XXX]` being the internal domain in which this appeared)

#### What is your debug output for this domain?
This was happening to me on an internal site, but since that is invite only I'm not 100% sure how to share a way to recreate it.

console.log said this:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.unsplash.com/photos/ezJhm4xrHAM/download?client_…d8dbb117efd05fa48e6df05cd1178fc7413c01a06bc4d31db2d1a0a97327. (Reason: CORS request did not succeed).

TypeError: NetworkError when attempting to fetch resource.
Error: Failed to load image.
```

I tried using the unsplash integration on typeform.com to see if it had the same issue, but I could see it fine there, maybe because they're using a `images.unsplash.com` instead of a `api.unsplash.com`... Or is it because I already enabled unsplash on `[XXX].com` earlier? (I can't tell if that's a global setting or a per domain one)

**Comment by ghostwords** [comment]
Hello and thanks for the report! Does setting the slider for each `unsplash.com` subdomain to "yellow" and reloading the page work around the problem?

**Comment by socksy** [comment]
@ghostwords yes, that is correct
