### ISSUE TITLE
PrivacyBadger breaks the login button on www.academicwork.se

### ISSUE THREAD

**Issue by Dyras** [EFForg/privacybadger#2544]
#### What is your browser and browser version?
Latest Edge Beta

#### What is broken and where?
The login button on academicwork.se breaks when the extension is enabled.
Allowing "apiv2.imbox.io" to set a cookie fixes it.
https://www.academicwork.se/

#### What is the "culprit" domain?
Please follow the debug instructions to identify which domain breaks stuff when blocked:
https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain
apiv2.imbox.io

**Comment by ghostwords** [comment]
Thanks for letting us know!
