### ISSUE TITLE
Privacy Badger blocks RadioFrance live streaming

### ISSUE THREAD

**Issue by Yvan-Masson** [EFForg/privacybadger#2546]
Hi,

Privacy Badger prevents live streaming from RadioFrance's websites:

- www.francetvinfo.fr: PB should allow stream.radiofrance.fr and api.radiofrance.fr (cookies for both domains are not required, api.radiofrance.fr only shows description of what is being played)
- www.franceculture.fr, www.francebleu.fr, www.franceinter.fr, www.francemusique.fr, www.mouv.fr: PB should allow stream.radiofrance.fr (cookies are not required)
- www.fip.fr: PB should allow stream.radiofrance.fr and cdn.radiofrance.fr (cookies for both domains are not required, cdn.radiofrance.fr only shows album cover)

Regards,
Yvan

**Comment by ghostwords** [comment]
Thanks for the report!
