### ISSUE TITLE
Does Privacy Badger have the same privacy bug as reported for Apple's ITP?

### ISSUE THREAD

**Issue by sanjayen** [EFForg/privacybadger#2548]
I came across the following article
https://www.schneier.com/blog/archives/2020/02/apples_tracking.html

Curious to know if Privacy Badger works the same way as Apple's Intelligent Tracking Prevention (ITP) and thereby have the same privacy bug?

**Comment by ghostwords** [comment]
Hello! Privacy Badger is likely affected by similar attacks. We are investigating the practicality and the severity of these attacks now, and should have fixes/mitigations in the next Privacy Badger update.

**Comment by ghostwords** [comment]
Please see https://www.eff.org/badger-evolution for the account of our response.
