### ISSUE TITLE
XHR requests for at least "box.com" and "portail.infolegale.fr" blocked

### ISSUE THREAD

**Issue by jeanbruder** [EFForg/privacybadger#2554]
Browser : Google Chrome (Version 80.0.3987.100 (Build officiel) (64 bits)).

Broken : XHR requests made from at least "box.com" and "portail.infolegale.fr" are finished with err:NET_FAILED in Google Chrome, with a size of 0 byte received.

Example of bad XHR request :
![image](https://user-images.githubusercontent.com/7450442/74448528-6de6af00-4e7b-11ea-8e9b-25ccca8267b5.png)

**Comment by ghostwords** [comment]
Hello! On what site/page is this happening, and what does it break? Is Privacy Badger blocking `box.com` and `portail.infolegale.fr`? Could you provide the debugging information ([steps 2 and 3](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain)) for these two domains?

**Comment by ghostwords** [comment]
Let me know if you have more information.
