### ISSUE TITLE
Add reload page button to Badger's popup

### ISSUE THREAD

**Issue by finn0** [EFForg/privacybadger#2559]
Like other privacy friendly extensions, it would be nice if Privacy Badger also has a "Reload Page" button in its popup.

Sometimes PB breaks websites, and to fix those issues, I've to do some adjustments in "domain slider"; but after adjustments I've to either click on browser's reload icon or press `ctrl+R`, it would be nice if I can reload page directly from PB popup.

This would be especially useful in case of mobile environment.

**Comment by ghostwords** [comment]
Hello and thanks for the suggestion!

>Sometimes PB breaks websites

Why not use the "Disable Privacy Badger for this site" button?

**Comment by finn0** [comment]
> Why not use the "Disable Privacy Badger for this site" button?

Didn't realize that, PB has this button, thanks. Usually, those websites broken due slider is at block (`red colored block icon`) for some domains, but sliding them to center (`block cookie`) will fix the issue which what I wants, for momentarily. But if I would disable PB, I won't have control over those nasty domains behavior.
For example, I always like to block `google.com` but problem happens when website requires a `ReCAPTCHA`, for some functionality like signup etc; for which sliding it to `center` will fix the issue, momentarily (after verification, I want back it to block mode). I can give some more use cases, but now couldn't come-up with good one. Is this use case enough for FR?

**Comment by ghostwords** [comment]
For reCAPTCHA, please subscribe to #1542. We plan to fix this problem with a replacement widget in the next few releases. To help with testing, could you provide some example URLs where Privacy Badger breaks reCAPTCHA for you?

**Comment by ghostwords** [comment]
The reload button makes sense if we wanted to focus on enhancing Privacy Badger's manual control capabilities. However, Privacy Badger is meant to be an install-and-forget kind of tool. (If Privacy Badger breaks something somewhere, use the Disable button, and if you'd like to help, report the problem to us in some way.)

We are going to move the sliders behind an "advanced mode/show more" link by default in the next update or two. This will make Privacy Badger's nature more clear: the buttons we want you to use will stay and get more usable, the sliders will get further de-emphasized.

**Comment by finn0** [comment]
> could you provide some example URLs where Privacy Badger breaks reCAPTCHA for you?

Sorry for delay response, here are some examples, most registration process required to solve reCAPTCHA (right now I don't remember all links but I'll try to expand it):

- Register an account on 
    - https://gitlab.com - https://gitlab.com/users/sign_in#register-pane
    - https://spotify.com - https://www.spotify.com/us/signup/
    - https://reddit.com - https://www.reddit.com/register/

- https://discord.com (each sign-in attempt requires to resolve reCAPTHA).

**Comment by ghostwords** [comment]
@finn0 Privacy Badger version 2020.5.12 comes with a replacement widget for Google reCAPTCHA. So if you chose to block `www.google.com`, reCAPTCHA will be replaced by a Privacy Badger placeholder on many (but not yet all) pages that use reCAPTCHA. Could you take a look and let me know what you think?

**Comment by finn0** [comment]
@ghostwords Sorry about not directly commenting (https://github.com/EFForg/privacybadger/issues/2559#issuecomment-624568685) on issue #1542; I think, it would be good idea to discuss about reCAPTCHA, on issue https://github.com/EFForg/privacybadger/issues/1542.

**Comment by ghostwords** [comment]
I am going to close this for now for as per https://github.com/EFForg/privacybadger/issues/2645#issuecomment-657233821.

Please do let us know what other breakages Privacy Badger causes in your (mobile) browsing so that we could work on fixing them for all Privacy Badger users.

**Comment by ghostwords** [comment]
If we do come back to this in the future, it would make sense to add some sort of "reload page" overlay that appears when a slider has been modified. We should then also stop auto-reloading the page when restoring control for a slider to Privacy Badger. (But then we would also want to dynamically update any dependent sliders, similarly to what we do on the options page.)
