### ISSUE TITLE
Button for Privacy Badger invisible if uBlock Origin is active

### ISSUE THREAD

**Issue by GwenDragon** [EFForg/privacybadger#2560]
**Description**

After installation of uBlock Origin the button for Privacy Badger disappears and only the number badge for detected tracker is visible. 

**Steps to reproduce**

1. Install extension uBlock Origin 
2. Install extension uBlock Origin Extra
3. Install extension Privacy Badger
4. Visit page
5. Privacy Badger button is invisible
6. Disable uBlock Origin in Extension Manager
7. Privacy Badger button is visible now

**Additional**
uBlock Origin version: 1.24.4
Privacy Badger: 2020.2.19
Browser Name and version: Chrome 80.0.3987.122 and Vivaldi 2.11.1811.44
Operating System and version: Linux, Debian 10.3 x64 KDE 5.54 & Ubuntu 19.10 x64 GNOME 3.34.2

**Comment by ghostwords** [comment]
Hello! Could you post a screenshot to illustrate what you mean? I'm not sure what "the button for Privacy Badger disappears and only the number badge for detected tracker is visible", or at least I haven't been able to reproduce.

**Comment by GwenDragon** [comment]
Sees to be a issue with acvtivated 2D-Canvas in Chromium codebase :( 
chrome://flags/#disable-accelerated-2d-canvas

So it is a chromium issue.

**Comment by ghostwords** [comment]
I see, thank you. Could you report this to crbug.com and link to the issue here?
