### ISSUE TITLE
Incorporate DuckDuckGo Tracker Radar list

### ISSUE THREAD

**Issue by superusercode** [EFForg/privacybadger#2564]
DuckDuckGo recently wrote a blog article where they scrape detected trackers on websites and they seem to have the largest one:
https://spreadprivacy.com/duckduckgo-tracker-radar/

Any plan in adding DuckDuckGo list of trackers to privacy badger?
The code is open source and the list is available to download.
* https://github.com/duckduckgo/tracker-radar
* https://github.com/duckduckgo/tracker-radar-detector

**Comment by ghostwords** [comment]
Thanks the pointer! We'll take a look to see if there are improvements we should make to [our crawler](https://github.com/EFForg/badger-sett).

>they compare lists of trackers on websites and they seem to have the largest one

Could you point to where they make this claim?

**Comment by superusercode** [comment]
@ghostwords sorry, i meant to quote this instead
```
most common cross-site trackers and includes detailed information about their tracking behavior, including prevalence, ownership, fingerprinting behavior, cookie behavior, privacy policy, rules for specific resources (with exceptions for site breakage), and performance data.
```
that probably came from a template I use for github issues.

**Comment by superusercode** [comment]
site breakage to me is the most important point, since it's the primary reason I uninstall badger after it makes bad assumptions about sites (blocking spotify status on discord for one) and end up depending on the built in tracker prevention on firefox/edge.

I understand that I can just adjust the settings myself, but after doing it for a while it gets annoying when I can just let my browser take the wheel.

**Comment by ghostwords** [comment]
You shouldn't have to disable Badger completely. When you run into something not working, you could try telling Privacy Badger to leave the site alone by clicking the "Disable Privacy Badger for this site" button inside Privacy Badger's popup.

You can also let us know when a site is broken by clicking on the "Did Privacy Badger break this site? Let us know!" button. This helps us figure out which site fixes we should work on next.

**Comment by ghostwords** [comment]
Related to #2114
