### ISSUE TITLE
GitLab broken if "assets.gitlab-static.net" is disabled

### ISSUE THREAD

**Issue by aha999** [EFForg/privacybadger#2565]
#### What is your browser and browser version?
Mozilla Firefox 73.0.1 (64-bit)
#### What is broken and where?
Any gitLab project page is broken by default when one tracker is enabled, example [link](https://gitlab.com/Ashpex/android-FOSS-apps)

I found out that After enabling the "assets.gitlab-static.net" in the privacybadger, the website works normally again.

Screenshots:
**tracker enabled** (all other addons disabled):
![unwoWnxmEx](https://user-images.githubusercontent.com/50620416/76154217-11249000-60d9-11ea-9e71-44dc190a8afe.png)

**tracker disabled** (all other addons still disabled):
![Nq3XT5GvcT](https://user-images.githubusercontent.com/50620416/76154221-141f8080-60d9-11ea-969f-29c7f7ba5555.png)

Privacy badger in debugging (maybe that helps):
![hr2kmFVsHP](https://user-images.githubusercontent.com/50620416/76154135-7d9e8f80-60d7-11ea-8fcc-67109072ee67.png)

**Comment by ghostwords** [comment]
Hello! Could you share the [debug output](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) for "gitlab-static"?

**Comment by aha999** [comment]
@ghostwords i don't know where to copy this at the third point.

> Copy the following JavaScript and paste it into the background page console

**Comment by ghostwords** [comment]
> > Copy the following JavaScript and paste it into the background page console
> 
> Where and what background console? I opened a console as mentioned in foutrh step. but next i don't understand.

When you select the Console tab of Privacy Badger's background page, there is a text input at the bottom. You can paste into that text input, edit what you pasted, and press the "Enter" key to run your input.

> Do i paste in the tracker or the website link at the xxx ?

The "tracker" domain, or a part of it. So here you would replace "XXX" with "gitlab-static".

Here is a screenshot of what the background page console looks like after I pasted and edited the debug code, but before I pressed the "Enter" key:

![Screenshot from 2020-03-10 12:42:46](https://user-images.githubusercontent.com/794578/76336623-aa67c800-62cc-11ea-873e-ce1e0038e9e7.png)

**Comment by ghostwords** [comment]
Looking again at your screenshot, it looks like you blocked `assets.gitlab-static.net` for yourself. I can't tell whether and where your Privacy Badger learned to block `assets.gitlab-static.net` without having the debugging output, however.
