### ISSUE TITLE
Blocks Images from Project Website

### ISSUE THREAD

**Issue by lbussy** [EFForg/privacybadger#2569]
I wrote and maintain [Brew Bubbles](https://www.brewbubbles.com) which is a micro-controller based device for Home Brewers.  The controller has an onboard web server, however, to reduce the load on the webserver, I host some of the images on the main website.  Specifically [this image](https://www.brewbubbles.com/support/mstile-144x144.png).

It's white on a transparent background so if you try to load it you might get the impression it's intended to be a "pixel" used to track people.  I assure you that's not the case and is used in the embedded web page as an icon against a colored background.

Is there any process by which this can be whitelisted?  I am currently tracking this as issue [#12 on my issue tracker](https://github.com/lbussy/brew-bubbles/issues/12).

**Comment by ghostwords** [comment]
Hello!

Privacy Badger automatically learns to block a domain if it thinks it sees tracking from that domain on three separate websites. My guess is that you have (login?) cookies set on your `brewbubbles.com` domain, and these cookies are being sent when requesting `brewbubbles.com`-hosted images on other websites.

Privacy Badger then sees this happen and thinks there is tracking going on (a non-trivial cookie being sent in third-party contexts). Does that seem right?

**Comment by ghostwords** [comment]
If this is caused by session cookies, I have a couple of suggestions:

- To improve website performance/security, your service should avoid having session cookies be associated with static resources/API endpoints (perhaps by configuring a dedicated static resource (sub)domain).

- If you don't actually track users via `www.brewbubbles.com`, this domain might be compatible with the [EFF Do Not Track policy](https://www.eff.org/dnt-policy)'s requirements. In that case, posting the policy on the domain will tell Privacy Badger to always allow loading of resources from that domain.

**Comment by lbussy** [comment]
Interesting ... I'll bet it's because that site also hosts a Wordpress site?

Would it get around the issue if I created a new subdomain and hosted it from that?

**Comment by ghostwords** [comment]
Yes, that's what I mean to suggest in my first bullet point above.

**Comment by ghostwords** [comment]
Assuming the cookies weren't set for the entire base domain (`brewbubbles.com`) and won't get sent on the new subdomain (say, `static.brewbubbles.com`).

**Comment by lbussy** [comment]
I have created the subdomain and instantiated the [no-tracking assertion](http://resources.brewbubbles.com/.well-known/dnt-policy.txt).  Even though I [cloned and copied the DNT repo](https://github.com/EFForg/dnt-policy), I am unable to change the condition via Privacy Badger.  I thought maybe that was because I could not achieve the same [checksum](https://github.com/EFForg/dnt-policy/blob/master/dnt-policies.json) indicated in the [Implementation Guide](https://github.com/EFForg/dnt-guide#eff-how-to-implement-dnt-guide).

Any guidance?

**Comment by ghostwords** [comment]
Yes, exactly, it's the checksum:

```
 $ shasum <(curl -s "https://resources.brewbubbles.com/.well-known/dnt-policy.txt") <(curl -s "https://raw.githubusercontent.com/EFForg/dnt-policy/master/dnt-policy-1.0.txt")
c09f71363bb29d0250a1f5524eef36f9ab07669b  /dev/fd/63
a18e8dba6848d3fc241b03b88291cb75a3cfec3b  /dev/fd/62
```

The declaration needs to match exactly, whitespace included. (We've got an outstanding issue to fix this usability problem: #2291).

**Comment by lbussy** [comment]
I'd say it's currently improbable that a mere human adhere to the sha checksum.  I curled the [source(https://www.eff.org/.well-known/dnt-policy.txt) and uploaded to my host.  The source checksummed (correctly) at a18e8dba6848d3fc241b03b88291cb75a3cfec3b and once I uploaded it was c09f71363bb29d0250a1f5524eef36f9ab07669b.

I hope you are able to come up with a means t o determine our intent - we appreciate and support the mission you have.  I am just hopeing for a means to show it.

**Comment by ghostwords** [comment]
OK, `c09f71363bb29d0250a1f5524eef36f9ab07669b` should now be recognized as a valid DNT policy. You should see this take place after you restart your browser.

**Comment by lbussy** [comment]
Loosk good I think - I tested by browsing directly to an image as my project is currently broken.  That should work, right?

**Comment by ghostwords** [comment]
Privacy Badger doesn't do anything when you load a resource directly. If you have a page on a different domain from `resources.brewbubbles.com`, and that page loads something from `resources.brewbubbles.com`, Privacy Badger should check `resources.brewbubbles.com` for DNT policy and show that one was found with an icon next to the domain in Privacy Badger's popup.

**Comment by lbussy** [comment]
I guess that does make sense.  {forehead-slap}

It works!  Thank you so much for your assistance.
