### ISSUE TITLE
ProSiebenSat.1 channel sites are broken

### ISSUE THREAD

**Issue by DJCrashdummy** [EFForg/privacybadger#2570]
#### What is your browser and browser version? 
Firefox 73.0.1 (64-Bit)

#### What is broken and where?
nearly everything (except the text) on all channel sites of [ProSiebenSat.1](https://en.wikipedia.org/wiki/ProSiebenSat.1_Media):
- https://www.kabeleins.at/livestream
- https://www.kabeleinsdoku.at/livestream
- https://www.prosieben.at/livestream
- https://www.prosiebenmaxx.at/livestream
- https://www.sat1.at/livestream
- https://www.sat1gold.at/livestream
- https://www.sixx.at/livestream

#### What is the "culprit" domain?
- s.p7s1.io (site)
- config.player.p7s1.io (player)
- component.player.p7s1.io (player)

#### What is your debug output for this domain?
<details>

```
**** ACTION_MAP for p7s1.io
component.player.p7s1.io {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1585772988809
}
p7s1.io {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
magellan-api.p7s1.io {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1585525032949
}
s.p7s1.io {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1585592488691
}
config.player.p7s1.io {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1585896311716
}
**** SNITCH_MAP for p7s1.io
p7s1.io [
  "kabeleinsdoku.at",
  "prosieben.at",
  "prosiebenmaxx.at"
]
```
</details>

#### PS:
- you have to delete cookies/localstorage to start the stream more than once
- though at least the streams may be geoblocked

**Comment by ghostwords** [comment]
Thank you for the report! Let me know how #2572 looks.
