### ISSUE TITLE
an unexpected error occured in firefox 74

### ISSUE THREAD

**Issue by noodlesatgithub** [EFForg/privacybadger#2571]
privacy badger (which I love) Is now showing me a error on every single site that says An unexpected error occurred. How do I fix this bug?

**Comment by ghostwords** [comment]
Hello! Is your disk low on space? Does uninstalling and reinstalling Privacy Badger fix this problem?

**Comment by ghostwords** [comment]
Possibly related: #2474.

Let me know if you have more information. Closing for now.
