### ISSUE TITLE
Settings lost when upgrading to Firefox 74.0.1 (64-bit)

### ISSUE THREAD

**Issue by Marmotian** [EFForg/privacybadger#2575]
Don't know if this is a PB issue or a FF issue, but all my PB settings vanished when Firefox automatically upgraded to 74.0.1 (64-bit) on Windows10.

**Comment by ghostwords** [comment]
Hello! Could you describe the problem in more detail? Did Privacy Badger act as if it was just installed and show the "Thank you for installing Privacy Badger" page?

**Comment by ghostwords** [comment]
This sounds like a Firefox bug, but it would help to have more information to better say what happened.

**Comment by ghostwords** [comment]
Let me know if you have more information. Closing for now.

**Comment by Marmotian** [comment]
On Sun, Apr 5, 2020 at 7:46 AM Alexei <notifications@github.com> wrote:

> Hello! Could you describe the problem in more detail? Did Privacy Badger
> act as if it was just installed and show the "Thank you for installing
> Privacy Badger" page?
>

Sorry I didn't reply earlier, this isn't my primary account. I will add a
forwarding filter for github.

Yes, it acted as if it were a fresh install.

>

**Comment by ghostwords** [comment]
Do you use any history cleaning tools, or did you (set up Firefox to) reset browser data? Possibly related: https://bugzilla.mozilla.org/show_bug.cgi?id=1313401

We previously filed this Firefox bug under #2344, but we never got anywhere helpful, unfortunately.

**Comment by Marmotian** [comment]
On Tue, Apr 14, 2020 at 1:27 PM Alexei <notifications@github.com> wrote:

> Do you use any history cleaning tools, or did you (set up Firefox to)
> reset browser data? Possibly related:
> https://bugzilla.mozilla.org/show_bug.cgi?id=1313401
>
> We previously filed this Firefox bug under #2344
> <https://github.com/EFForg/privacybadger/issues/2344>, but we never got
> anywhere helpful, unfortunately.
>

I use FF as my "secure" browser. I have it set to always use private
windows and I almost always use the "Forget about some browsing history"
button before I exit (probably redundant, I know).

**Comment by ghostwords** [comment]
>I almost always use the "Forget about some browsing history" button before I exit

I think we found the problem then. Forgetting browsing history in Firefox can inadvertently remove extensions settings. This is tracked under https://bugzilla.mozilla.org/show_bug.cgi?id=1313401 on Mozilla's bug tracker.

**Comment by Marmotian** [comment]
On Tue, Apr 14, 2020 at 2:07 PM Alexei <notifications@github.com> wrote:

> I almost always use the "Forget about some browsing history" button before
> I exit
>
> I think we found the problem then. Forgetting browsing history in Firefox
> can inadvertently remove extensions settings. This is tracked under
> https://bugzilla.mozilla.org/show_bug.cgi?id=1313401 on Mozilla's bug
> tracker.
>

OK, thanks. I guess I'll h ave to train myself to stop using that feature.

>
