### ISSUE TITLE
Is there a way to add domains manually?

### ISSUE THREAD

**Issue by tx9191** [EFForg/privacybadger#2576]
an extension in Firefox has compatibility issues with privacy badger when handling certain domains, but after I reported the bug to the author, he found that he could not add the domains to privacy badger manually which makes it difficult for him to reproduce the bug.
Thanks.

**Comment by ghostwords** [comment]
Hello!

Not through the UI, but we could add domains for Privacy Badger to block using developer tools. Let me know if you would like more information on this.

You could also try recreating the problem by asking the extension author to visit the sites that Privacy Badger learned to block the domain on in their browser with Privacy Badger. You can get these site domains by following the debugging instructions in https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain

Related: #2259
