### ISSUE TITLE
Please yellowlist our CDN media.appycouple.com

### ISSUE THREAD

**Issue by mastre** [EFForg/privacybadger#2577]
#### What is your browser and browser version?
Chrome `80.0.3987.163`, macOS (doesn't matter tho, not browser related)

#### What is broken and where?
One of our product offerings is wedding websites, for which we provide the option of using a custom domain; all of the media is served off our CDN which is on the main domain. PB blocks this CDN when a custom domain is used to access a wedding website.

#### What is the "culprit" domain?
`media.appycouple.com`

Note: in the interest of not betraying the privacy of our customers as this page might get indexed, the domains in the SNITCH_MAP are internal QA/test domains.  However, they are set up exactly how an actual customer would set them up, with real custom domains.

#### What is your debug output for this domain?
To get the debug output, please see the instructions link above.
```
**** ACTION_MAP for appycouple.com
appycouple.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1496299402134,
  "userAction": ""
}
media.appycouple.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1586636326768,
  "userAction": ""
}
**** SNITCH_MAP for appycouple.com
appycouple.com [
  "vivekr.work",
  "vivekratkalkartech.com",
  "appylife.com",
  "webratkalkar.com"
]
```

#### Additional
We also use FileStack for inline image transformations.  Normally I'd think (and like to see) the vendor take care of things like this, but I figured I'd report it while at it, since PB breaks some functionality on our platform (even when not using custom domains as above).  Here's the debug on it
```
**** ACTION_MAP for filestackapi.com
api.filestackapi.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1586393533838,
  "userAction": ""
}
filestackapi.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1495949307488,
  "userAction": ""
}
process.filestackapi.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1579624650830,
  "userAction": "user_cookieblock"
}
static.filestackapi.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1579672784233,
  "userAction": ""
}
**** SNITCH_MAP for filestackapi.com
filestackapi.com [
  "appycouple.com",
  "appylife.com",
  "vivekratkalkartech.com"
]
```

**Comment by ghostwords** [comment]
Hello and thank you for the excellent bug report!

I don't see any tracking from `media.appycouple.com` when I visit the sample sites. So I don't know why Privacy Badger learns to block your media CDN domain.

If `media.appycouple.com` does not actually track users, it may be compliant with the [EFF Do Not Track policy](https://www.eff.org/dnt-policy). If you posted the DNT policy on the `media.appycouple.com` domain, the policy file will tell Privacy Badgers to always allow resources from `media.appycouple.com`.

**Comment by ghostwords** [comment]
Oh OK, if I visit `appycouple.com` first, I get a "atbgdid" cookie set. This cookie is then sent along with `media.appycouple.com` requests when visiting the sample sites.

**Comment by mastre** [comment]
As well, I appreciate the quick response!

> Oh OK, if I visit `appycouple.com` first, I get a "atbgdid" cookie set. This cookie is then sent along with `media.appycouple.com` requests when visiting the sample sites.

Yes, we do not restrict cookies to hosts on `appycouple.com`, one side effect is that cookies will be sent to the CDN media.appycouple.com (which is straight AWS CloudFront with custom hostname & SSL cert).  `media.appycouple.com` should not be setting any cookies itself other than anything AWS CF would set, if anything.

**Comment by ghostwords** [comment]
Yep, I suggest posting the EFF DNT policy as a workaround.

**Comment by mastre** [comment]
> Yep, I suggest posting the EFF DNT policy as a workaround.

While I can throw the EFF DNT up on our CDN, according to this page
https://github.com/EFForg/dnt-guide#9-dnt-compliant-cloud-service-providers
AWS CloudFront is not compliant, and there is obviously nothing I can do about that.  Please advise.

**Comment by ghostwords** [comment]
I am not sure why our EFF guide lists Cloudfront as non-compliant because of cookies. I don't see any cookies from `media.appycouple.com` (outside of the one set in the first party context by `appycouple.com` itself). @andresbase?

**Comment by mastre** [comment]
I added the DNT to the CDN host and seems to work, I did have to reset my PD's data tho.  Thanks for your help!
