### ISSUE TITLE
Yellowlist Trustpilot and Kualo CDN

### ISSUE THREAD

**Issue by kualozach** [EFForg/privacybadger#2578]
#### What is your browser and browser version?

Firefox 76.0b1

#### What is broken and where?

Trustpilot widget, background images, and cart AJAX on our [main site](https://www.kualo.co.uk). https://widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js fails to load, background images from cdn.kualo.com fail to load, and AJAX queries to my.kualo.com (our billing system) fail to go through.

#### What is the "culprit" domain?

widget.trustpilot.com
cdn.kualo.com
my.kualo.com

#### What is your debug output for this domain?

For widget.trustpilot.com:

```
**** ACTION_MAP for trustpilot.com
trustpilot.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
widget.trustpilot.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
**** SNITCH_MAP for trustpilot.com
trustpilot.com [
  "kaspersky.com",
  "lulu.com",
  "yumpu.com",
  "kualo.co.uk"
]
```

For cdn.kualo.com:

```
**** ACTION_MAP for kualo.com
my.kualo.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 0
}
kualo.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
cdn.kualo.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
images.kualo.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
status.kualo.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 0
}
**** SNITCH_MAP for kualo.com
kualo.com [
  "kualo.net",
  "kualo.co.uk",
  "nafgh.org",
  "head2toecharity.org.uk"
]
```

For my.kualo.com:

```
**** ACTION_MAP for kualo.com
my.kualo.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 0
}
kualo.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
cdn.kualo.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
images.kualo.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
status.kualo.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 0
}
**** SNITCH_MAP for kualo.com
kualo.com [
  "kualo.net",
  "kualo.co.uk",
  "nafgh.org",
  "head2toecharity.org.uk"
]
```

**Comment by ablanathtanalba** [comment]
Thanks for reporting this issue! This is very similar to a recent issue: #2577 

Testing a fresh instance of privacy badger on `kualo.com` it does pick up on `cdn.kualo.com` and 
`my.kualo.com` as potential trackers. If these domains aren't actually tracking users, one way you could prevent breakages with Privacy Badger or other tracker blocker extensions would be to implement a [DNT policy](https://www.eff.org/dnt-policy). A technical walkthrough [can be found here](https://github.com/EFForg/dnt-guide#eff-how-to-implement-dnt-guide).

**Comment by ghostwords** [comment]
I just added all `trustpilot.com` domains to the yellowlist.

As for `cdn.kualo.com` and `my.kualo.com`, let me know whether the [EFF Do Not Track policy](https://www.eff.org/dnt-policy) is an appropriate solution or not.
