### ISSUE TITLE
cartoradio.fr is broken with PrivacyBadger

### ISSUE THREAD

**Issue by Yvan-Masson** [EFForg/privacybadger#2580]
Hi,

The website https://cartoradio.fr is made by ANFR, a French governmental agency. When navigating on this website, PrivacyBadger completely blocks domain `api-adresse.data.gouv.fr` (also owned by the French government), which breaks the main functionality of the website (searching a location to display antennas).

Could you allow `api-adresse.data.gouv.fr` so that the website works with default configuration? Note that allowing cookies is not required.

Best regards,
Yvan

**Comment by ghostwords** [comment]
Thanks for the report!

Previously: #2397.
