### ISSUE TITLE
Broken: /\w+.photo.store.qq.com/i

### ISSUE THREAD

**Issue by ivysrono** [EFForg/privacybadger#2584]
#### What is your browser and browser version?
Firefox 75
#### What is broken and where?
https://bbs.kafan.cn/thread-2102542-1-1.html
#### What is the "culprit" domain?
/\w+.photo.store.qq.com/i
![图片](https://user-images.githubusercontent.com/2649544/79064811-96095780-7cde-11ea-9800-b47cc2fc5478.png)
I have added `photo.store.qq.com` to yellowlist at #2583 .
However, it has unlimited subdomain, for example:
```
b400.photo.store.qq.com
s25.photo.store.qq.com
……
```
They are QQ, the biggest Chinese site's images, which should not be broken.

**Comment by ghostwords** [comment]
If we were to yellowlist `photo.store.qq.com`, this would yellowlist any domains under `photo.store.qq.com` such as `s25.photo.store.qq.com`. Does this answer your question?

**Comment by ivysrono** [comment]
Thx
