### ISSUE TITLE
Consider using Weblate for translations

### ISSUE THREAD

**Issue by tjhietala** [EFForg/privacybadger#2591]
Privacy Badger has still a project on Transifex, even though it's not mentioned anymore in the translation guide. So I wonder if it's going away at some point?

If there is still interest in providing an environment similar to Transifex, I would recommend [Weblate](https://weblate.org/), which has the following advantages:

- It's free and open source, can be self-hosted.
- It's easier to use than Transifex (IMO), in particular I like the search better.
- It automatically credits the translators in git commits.
- It's being actively developed.

**Comment by andresbase** [comment]
Hi! We are evaluating different platforms to do our translations and that does include Weblate. For the time being you can continue making translations through the available tools or through Github. 

When we are closer to something more concrete we'll let you know and will give everyone time to give their input and prepare for changes if those happen.

**Comment by ghostwords** [comment]
Just an update, we again mention Transifex in the [Privacy Badger translation guide](https://github.com/EFForg/privacybadger/blob/master/doc/Translation.md), and we are now set up with Weblate for [translating Privacy Badger's homepage](https://github.com/EFForg/privacybadger-website#translating). We may move everything to Weblate in the future, but for now we are on two platforms, one for the extension and one for the website.
