### ISSUE TITLE
"Trackers" link in popup needs styling

### ISSUE THREAD

**Issue by ablanathtanalba** [EFForg/privacybadger#2594]
The trackers link displayed in the popup text could use some styling beyond the default that it is now. It needs to draw attention to itself as a link, yet fit within the current theme of the popup's style.

Here is how it looks on pages with and without any detected trackers:
<img width="432" alt="Screen Shot 2020-04-24 at 2 57 57 PM" src="https://user-images.githubusercontent.com/25778052/80263203-bc1aea00-8644-11ea-93dc-456f13ca64fa.png">
<img width="431" alt="Screen Shot 2020-04-24 at 2 57 35 PM" src="https://user-images.githubusercontent.com/25778052/80263205-bf15da80-8644-11ea-8e72-2232e01aee79.png">

Here is how it looks after it's been clicked (the default purple):
<img width="433" alt="Screen Shot 2020-04-24 at 3 34 26 PM" src="https://user-images.githubusercontent.com/25778052/80263230-d654c800-8644-11ea-94c7-2729eac04b57.png">

And here in its hover state:
<img width="431" alt="Screen Shot 2020-04-24 at 3 34 35 PM" src="https://user-images.githubusercontent.com/25778052/80263248-e40a4d80-8644-11ea-87de-e09a6ba29fc9.png">

**Comment by afanick10** [comment]
Hi @ghostwords . I'd like to work on this as a good first issue to gain experience with the code base. Can you add me as a collaborator so I can create a branch for this issue?

**Comment by ghostwords** [comment]
Hello and welcome! No need, anyone can fork this repository, create a branch there and [open a pull request here from your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by afanick10** [comment]
Opened pull request #2600 for this issue.
