### ISSUE TITLE
PrivacyBadger identify Infura as a tracker

### ISSUE THREAD

**Issue by lildata** [EFForg/privacybadger#2599]
PrivacyBadger learn, identify & after some time blocks all infura.io requests (like ipfs.infura.io or mainnet.infura.io).
Its unfortunate because Infura is not a tracker but an API access to the Ethereum and IPFS networks. 

Example of web site where the main feature is broken (search for an Ethereum address) : https://lite-explorer.aleth.io/

**Comment by ghostwords** [comment]
Hello! Could you provide the [debugging information](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) for "infura"?

**Comment by ghostwords** [comment]
Let me know if you have more information. Closing for now.
