### ISSUE TITLE
Outgoing link tracking is not cleaned on Facebook in Firefox

### ISSUE THREAD

**Issue by spencermathews** [EFForg/privacybadger#2605]
#### What is your browser and browser version?
Firefox 76.0

#### What is broken and where?
When I hover a link on Facebook the URL in the status bar is still prefaced with `https://l.facebook.com` instead of seeing the actual link. This only occurs in Firefox, and appears to be working properly on Chrome.

I understand that Privacy Badgers link handling is based off of the **Tracking & Ad Removal for Facebook** extension. The expected behavior is observed when using that extension.

#### What is the "culprit" domain?
N/A

#### What is your debug output for this domain?
N/A

**Comment by ghostwords** [comment]
Thank you for the report!

**Comment by iraleigh** [comment]
When trying to reproduce this, I noticed the same behavior, but it does not seem to be from the plugin.

I noticed the first time hovering over a link, the browser status bar displayed the link prefixed with `https://l.facebook.com/l.php?u=https://www.example.com` as described. The second time hovering over, the  status bar displayed the link `https://www.example.com`

I noticed this same behavior with:
 - the extension installed and enabled
 - with the extension installed and disabled
 - without the extension installed

**Comment by spencermathews** [comment]
As described in [Privacy Badger Rolls Out New Ways to Fight Facebook Tracking](https://www.eff.org/deeplinks/2018/05/privacy-badger-rolls-out-new-ways-fight-facebook-tracking) (the blog post introducing this feature), this is part of Facebook's trickery and is the normal, unmodified, behavior. So you observations confirm that Privacy Badger is not doing its job.

**Comment by ablanathtanalba** [comment]
I've tried reproducing this issue in both Firefox (v 76.01) and Chrome ( v 81.0.4044.138) and at first glance the behavior is like you describe, but then after a few seconds it corrects itself and the link has been properly scrubbed. I've noticed it happens in both Chrome and Firefox, though Chrome is usually much quicker at making the changes visible. This leads me to suspect that it's not actually an issue with Privacy Badger, but rather a timing thing with Firefox.

Here's the I/O of the `cleanLink()` function in the `facebook.js` file that PB runs:
![Screen Shot 2020-05-13 at 6 14 36 PM](https://user-images.githubusercontent.com/25778052/81881811-fbeb3800-9545-11ea-8324-6bbcc769ba79.png)

**Comment by spencermathews** [comment]
I loaded FB and let it sit for several minutes. Even then I noticed a large number of links that were not cleaned. This would be enough of a delay to render the feature effectively useless even if it did ultimately clean the links at that point—which it still didn't. I can't speak to what exactly is causing the problem, but it seems clear that there is one.

@ablanathtanalba if you could explain the debug process you used I can test it out on my browser.

**Comment by bcyphers** [comment]
hi, it looks like this is an issue with our link filter, which currently looks for links that look like `facebook.com/l.php?` but do not contain an `aria-label` attribute. The second half of that filter was added [here](https://github.com/EFForg/privacybadger/commit/44d3e6942c3c37422dd81d7b7dc4b031d06ea5c4) in response to https://github.com/EFForg/privacybadger/issues/2214. Back then, embedded photos in Messenger for Web contained `aria-label` attributes and regular links did not; now, regular links do, so most of them aren't being replaced.

Here's what a link in the newsfeed looks like for me, note the label: 
![facebook-nyt-link-5 14 20](https://user-images.githubusercontent.com/4840035/81983726-acaa1380-95e8-11ea-9d21-fddad03fa8e7.png)

To fix, we'll have to find another way to differentiate between regular links and embedded photos.

**Comment by bcyphers** [comment]
It looks like we might be able to do it by filtering `data-lynx-mode="async"`. At a glance, this captures all of the links in my news feed, and excludes messenger images (which have `data-lynx-mode="hover"` instead)

**Comment by spencermathews** [comment]
@bcyphers perhaps the link filter needs updating, but how does that resolve the qualitative difference in behavior between Chrome and FF? In terms of this issue the behavior in Chrome seems to be adequate.

**Comment by ablanathtanalba** [comment]
> @ablanathtanalba if you could explain the debug process you used I can test it out on my browser.

@spencermathews -- Sure thing:

I wasn't really doing any fancy footwork as far as testing this out: First I would hard refresh Facebook, find the link I'm testing on, then hover my mouse over it to view the preview URL in the browser info bar at the bottom left of my window. Since that showed up as the bad "l.facebook.com.l/php" tracking link, I would right click the link and inspect the element to view it in the developer console. There it would show me the element with the bad link in the DOM tree, and a moment or two later it would update (which would also be shown by a flash of color in the developer console) to the freshly cleaned link. If I don't move my mouse from hovering over the link, the preview URL shown in the info bar at the bottom left will continue to show the bad "l.facebook.com" even though it had changed to the freshly cleaned one in the developer console. If I move my mouse off the link, then hover it back over it again, the new cleaned link would appear in the popup info bar.

I also added some `console.log()` statements in the `cleanLink()` method in `src/js/firstparties/facebook.js` file so that I could view the input and output of each link and its attributes as it got cleaned in real time. This is only viewable in the console of the badger's background page, which is a little bit more tricky to get to than the description I gave above. I'm happy to walk you through that as well if you think it would be helpful.

**Comment by ablanathtanalba** [comment]
Bad news on this front: Facebook rolled out a massive update over the weekend that makes this part of our codebase irrelevant. Although it will still work in "classic mode" as facebook is calling it, the "new mode" no longer has any of these attributes on the offending links. 

Now each link is no longer the typical `<a>` tag, but instead a `<div>` nested within other divs and spans, none of the attributes we scrub are present, and instead each element is given just a `class=` attribute with a string value of cryptic 8-digit hex sequences separated by spaces. All the hyperlinking and plaintext attributes now seem to all be obfuscated and dynamically generated behind the scenes.

Here's an example screenshot of what's visible in the dev panel (the link tag is what's highlighted):
![Screen Shot 2020-05-17 at 10 19 32 PM](https://user-images.githubusercontent.com/25778052/82176870-d1beb080-988c-11ea-9847-b73ddbaa4ede.png)

**Comment by mgziminsky** [comment]
Chiming in a bit late here, and not sure if it's relevant, but this may not just be related to your `cleanLink()` and link filter. I had to make a change in Feb. 2019 to fix an issue with FB resetting links that had already been cleaned which may be what you are seeing here sometimes as well. See: https://github.com/mgziminsky/FacebookTrackingRemoval/commit/25340f431f4c6d3567717918c08346d8dfe8ad36

It didn't happen all the time, but seemed to be a race condition between the async link cleaning and the FB js that processed the links to add their click handlers. If the cleaning happened first, the link would get reset later when the FB code ran.
