### ISSUE TITLE
login at Huobi is broken

### ISSUE THREAD

**Issue by DJCrashdummy** [EFForg/privacybadger#2606]
#### What is your browser and browser version?
firefox 75.0 (64-bit)

#### What is broken and where?
a login at https://www.huobi.com/ resp. https://www.huobi.me/ is impossible and always fails with *"Failed to connect to the network. Please try again."*.

#### What is the "culprit" domain?
api-www.huobiasia.vip

#### What is your debug output for this domain?
```
**** ACTION_MAP for huobiasia.vip
huobiasia.vip {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
api-www.huobiasia.vip {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1589575874687
}
file.huobiasia.vip {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1589678165111
}
**** SNITCH_MAP for huobiasia.vip
huobiasia.vip [
  "hbg.com",
  "huobi.com",
  "huobi.me"
]
```

**Comment by ghostwords** [comment]
Thanks for the report!
