### ISSUE TITLE
PB stops Harvest add-in from popping up on Asana

### ISSUE THREAD

**Issue by j0nn0** [EFForg/privacybadger#2608]
#### What is your browser and browser version?
Chrome Version 81.0.4044.138 (Official Build) (64-bit)
#### What is broken and where?
Harvest App on Asana (app.asana.com) pages
#### What is the "culprit" domain?
`platform.harvestapp.com` (presumably, but it happens on `app.asana.com` dynamic pages) There is also `cache.harvestapp.com` -- both need to be disabled to work
#### What is your debug output for this domain?
```
**** ACTION_MAP for harvestapp.com
harvestapp.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
housemathews.harvestapp.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1589556490127,
  "userAction": ""
}
platform.harvestapp.com {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1589792644023,
  "userAction": "user_allow"
}
cache.harvestapp.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1589930588430
}
**** SNITCH_MAP for harvestapp.com
harvestapp.com [
  "asana.com",
  "clickup.com",
  "getharvest.com"
]
```

**Comment by ghostwords** [comment]
Thanks for the report! Does setting the sliders for required `harvestapp.com` domains to "yellow" (block cookies) also work?

**Comment by ghostwords** [comment]
Let me know if you have more information. Closing for now.

**Comment by j0nn0** [comment]
Apologies for missing your reply. I get an error with the sliders on yellow:

[image: image.png]

*Jon Pienaar*

*================*
Writer. Journalist. Making words work

*.*
Phone: +27 82 572 9696

Website: www.thewriters.co.za
Skype:  jonpienaar
Twitter:  @j0nn0 <https://twitter.com/j0nn0/>

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
20/06/01,
16:12:30

**Comment by ghostwords** [comment]
Hi @j0nn0, I can't see the screenshot you tried to send via email. Could you follow the "view it on GitHub" link in the GitHub notification and post the screenshot directly here as part of a comment? You can drag and drop images into GitHub comments.
