### ISSUE TITLE
Tracking Domains aren't removed

### ISSUE THREAD

**Issue by SiounGekio** [EFForg/privacybadger#2609]
After I installed the windows I installed Firefox with Privacy Badger. 
When I checked the Tracking Domains tab from settings, all of my trackers (around 1000) before reinstallation were there. 
I'm using Windows 10 and Firefox 76.
Q1: Is this normal or is a bug? 
Q2: How can I "start fresh" without any domain listed?

**Comment by ghostwords** [comment]
This is normal: you are looking at the [pre-trained list](https://www.eff.org/deeplinks/2018/08/giving-privacy-badger-jump-start).

To "start fresh", go to Privacy Badger options, select the Manage Data tab, click the Remove All button. Why do you want to start fresh?

**Comment by SiounGekio** [comment]
I messed up wtih some trackers and some pages won't work anymore and I guesses I could fix it just by reinstall the browser and PB. 
Thanks for your explanation. Now is more clear.
But I installed PB on other laptop too on the same network as mine and the same trackers were there. This mean PB works on LAN-connection?

**Comment by ghostwords** [comment]
You can reset the tracking domains list to defaults by clicking the Reset button on the Manage Data tab. No need to remove all in your case.

The same list of domains shows up for all new Privacy Badger installations; the pre-trained list is included in the Privacy Badger package.

Let me know if you have any other questions.
