### ISSUE TITLE
UI improvement: make the "replace widget"-tab easier to understand & handle

### ISSUE THREAD

**Issue by DJCrashdummy** [EFForg/privacybadger#2612]
because of a misconception on my side (https://github.com/EFForg/privacybadger/issues/1542#issuecomment-629123066) i thought a little bit more about the *"replace widget"*-tab:

although i thought it just replaces widgets from social media (IIRC this was initially the only function some time ago), also a new user may not really have a clue what things will get blocked.
beside that, if you want to except more than one or two widgets, it gets pretty tedious.
...and moreover, why using the conceptual roundabout that the user has to list the exception of the replacement?!? :dizzy_face: 

IMHO the much easier way for understanding & handling would be **a list with all possible widgets** and simply use **check-boxes to activate their replacement** (since the tab is called *"replace widget"*).
if you want to preserve the current behavior of en-/disabling the whole function with one click, i would maintain the current checkbox and simply deactivate the other boxes if the main one is unchecked.

- [x] activate replacement of the following widgets:
  - [x] facebook
  - [ ] google
  - [x] twitter
  - [x] ...

the only thing to take care of would be, that the main checkbox should also get automatically unchecked if the user unchecks all single items... and perhaps if he checks the main checkbox again, all singe items should be automatically checked again.
probably using a bullet for the main switch (active | inactive) may be reasonable.

**Comment by DJCrashdummy** [comment]
**but** if the "original" widgets are blocked by default like it is the case for reCAPTCHA (i have no clue about the rest, because i block the whole unnecessary nonsense via uBlockO), i would kind of turn the tables regarding the naming and call the tab "use/show PB-widget"... because if a widget it is blocked anyway, it isn't really replaced from a users point of view!
further i would make it more clear in the short description, that if the user deactivates this function the "original" widget may be blocked and he probably won't notice.

PS: yes i know, that there is no default in PB, but for the vast majority of this widgets it is very likely to appear on more than 3 sites.

**Comment by ghostwords** [comment]
Thanks for the suggestions!

We want the widget replacement to be on by default, and we want to replace all widgets and social buttons by default, including ones added in the future.

Given the above, that there is no need to do anything for most users, I don't think there is any need for us to tweak this UI. If it's not clear there is a problem, why do anything?

I'll be happy to revisit this feedback once we do get indications that the Widget Replacement tab UI/wording is indeed causing problem.

**Comment by DJCrashdummy** [comment]
**for sure the replacement should be on by default, i never suggested to turn it off!!!**

i just suggested to...
- use **a list to easily see** immediately **what gets** actually **replaced** and what not... *(i had no clue what gets replaced until i more ore less accidentally hit the exceptions field)*
- combined with **a solution to make settings** (if needed) **less tedious**
- and perhaps additionally rephrase the whole process, to make it easier for users or even non-techies to grasp it.

- - -

> I don't think there is any need for us to tweak this UI. If it's not clear there is a problem, why do anything?

IMHO most of the time, there can be something improved... but that's getting philosophical: *"a rolling stone gathers no moss."* :wink: 

> [...] once we do get indications that the Widget Replacement tab UI/wording is indeed causing problems.

that's also partly my point:
- a techie user would sooner or later get how PB is working and what the replacement does, because he knows how things do or don't work.
- a tech-unsavvy user will have a hard time understanding how PB (see problems with the general description) and replacement works... but if he notices PB is causing his issues - this doesn't have to be a bug, it may just be something that doesn't work as he expects it - it is likely that he just uninstalls PB, instead of fiddling around with it and opening issues in a bugtracker.
btw: the vast majority of the noobs don't even know what github is, nor how to report/open issues or that this is even possible.

**Comment by ghostwords** [comment]
I hear you and I agree that the UI could be better. It's just a matter of prioritization. Is it a clear problem? How important is the problem? Is there a clear solution? How hard is the solution to implement? We should only work on clear problems with (reasonably) clear solutions that are either easy to implement or are important enough to justify the time commitment.
