### ISSUE TITLE
Randomly generated subdomains dodges PB blocking

### ISSUE THREAD

**Issue by megascrapper** [EFForg/privacybadger#2616]
#### What is your browser and browser version?
Edge Chromium 81.0.416.77

#### What is broken and where?
Some trackers put a random subdomain every time so that even though privacy badger detects the tracker, it won't block them since it hasn't passed the 3 site threshold.

#### What is the "culprit" domain?
Example site: https://www.kompas.com/
If you go there, you'll see something like `11ofswt.umzzaftkqgx.com`, `15elon9.umzzaftkqgx.com` or just `<random characters>.umzzaftkqgx.com` in general in the 'Your Badger hasn't yet learned to block these domains' section. There are a whole bunch of these and it changes every time you refresh the page.

#### What is your debug output for this domain?
```
**** ACTION_MAP for umzzaftkqgx.com
umzzaftkqgx.com {
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 0,
  "userAction": ""
}
**** SNITCH_MAP for umzzaftkqgx.com
umzzaftkqgx.com [
  "kompas.com"
]
```

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch! `umzzaftkqgx.com` looks like some kind of anti-adblocking domain specific to Kompas. Have you seen this happen on any other site? As it is, I am not sure there is anything for us to do here as [Privacy Badger is not an ad blocker](https://privacybadger.org/#Why-doesn%27t-Privacy-Badger-block-all-ads).

**Comment by megascrapper** [comment]
I haven't seen anything like this before (not that I remember), or even if there are similar things the domain is matched properly (ie. under a single entry). 

Would `umzzaftkqgx.com` still be blockable if they do track users? I mean that's what PB is for.

**Comment by ghostwords** [comment]
Privacy Badger is primarily meant to catch non-consensual third-party tracking across the Web. Here we have what appears to be some sort of anti-adblocker obfuscation on a single site. Which we might want to do something about depending on the site's popularity, but it's just not our focus. (If we saw other, similarly randomized domains on unrelated-to-Kompas sites, that would be something for Privacy Badger to look into.)

You can tell Privacy Badger to block all of `umzzaftkqgx.com` for yourself, but that appears to break the site's appearance and functionality.

If first-party tracking on Kompas is a problem for you, I suggest installing an ad blocker such as uBlock Origin.
