### ISSUE TITLE
rai.it

### ISSUE THREAD

**Issue by urfausto** [EFForg/privacybadger#2617]
#### What is your browser and browser version?
Vivaldi 3.0.1874.38 (Stable channel) (a 32 bit)

#### What is broken and where?
https://www.raiplayradio.it
https://www.raiplay.it
https://www.rainews.it (eg https://www.rainews.it/dl/rainews/media/intervista-in-esclusiva-Monica-Maggioni-presidente-siriano-Bashar-al-Assad-cbb4acd8-5af8-45e3-815b-3cc5d05eda4d.html)

video and audio blocked. website can't load resources.

#### What is the "culprit" domain?
mediapolisvod.rai.it

#### What is your debug output for this domain?
**** ACTION_MAP for rai.it
execution-ci360.rai.it {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1591068573147,
  "userAction": ""
}
icestreaming.rai.it {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1584383161046,
  "userAction": ""
}
mediapolisvod.rai.it {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1590692069998,
  "userAction": "user_allow"
}
rai.it {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
secure.rai.it {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1590653361577,
  "userAction": "user_block"
}
www.educational.rai.it {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1582094447414,
  "userAction": ""
}
www.petrolio.rai.it {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1588005385944,
  "userAction": ""
}
www.rai.it {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1590935071808,
  "userAction": ""
}
www.raiscuola.rai.it {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1581840976951,
  "userAction": ""
}
**** SNITCH_MAP for rai.it
rai.it [
  "rainews.it",
  "raiplay.it",
  "google.it",
  "raiplayradio.it"
]

**Comment by ghostwords** [comment]
Thank you for the report!
