### ISSUE TITLE
Amazon incognito Domain at "dn1f1hmdujj40.cloudfront.net" and has been known to contact Amazon services at IP address "13.249.94.198"

### ISSUE THREAD

**Issue by Pokerguy365** [EFForg/privacybadger#2618]
Main issue: Amazon incognito Domain at "dn1f1hmdujj40.cloudfront.net" and has been known to contact Amazon services at IP address "13.249.94.198" and has not been flagged to be disabled.

"The domains below don't appear to be tracking you" section of the latest version of privacy badger allows dn1f1hmdujj40.cloudfront.net to remain tracking indefinitely. Disabling it manually forces the pop-up "blocking this domain is known to break websites." How is this allowed to continue being the default setting if this domain allows amazon to track? Additionally, I tried searching for this issue in GitHub privacy badger and came up with zero results. Moreover, I could not find any help formatting issues anywhere(anywhere!) and the "contributing guidelines" page was of no help by leading me to this blank page: https://github.com/EFForg/privacybadger/labels/good%20first%20issue

(“Help wanted” was filled with nonsensical nonsense at https://github.com/EFForg/privacybadger/labels/help%20wanted)

(Don't disregard this pressing issue because I do not know how to correctly format please! I have everything needed to report issues on most other application GitHub)

[- [MDFP] issues trackers] No labels because it looks like too often that issues are left unchecked and left disregarded such as in the "heuristic" label which I was going to use! Consequently, labels like "high priority" have small tiny issues that users are freaking out about when many hard-hitting issues are being left high and dry. This issue tracking system for this application of privacy browser need a definitive cleaning. 

I'll be using the label MFDP (if I'm able to get it working...) for this issue. Although that is highly unlikely because I don't know how to add it to my issue post directly because there is no user-friendly tutorial!

Sources: https://www.hybrid-analysis.com/sample/9c06e05b2c70669eca18fd27bf79f8f9ee47a14251ced0a93bd3a9d1bdaf38d5#

https://ipinfo.io/13.249.94.198

![Free Automated Malware Analysis Service - powered by Falcon Sandbox - Mozilla Firefox (Private Browsing) 5_26_2020 11_37_24 PM (Cropped to hide personal  ID details)](https://user-images.githubusercontent.com/64293894/82986308-78e8c980-9faa-11ea-9d10-44996cd691fe.png)
![Free Automated Malware Analysis Service - powered by Falcon Sandbox - Mozilla Firefox (Private Browsing) 5_26_2020 11_39_24 PM (Cropped to hide personal ID details)](https://user-images.githubusercontent.com/64293894/82986319-7d14e700-9faa-11ea-87a5-9f80265cbfda.png)

**Comment by ghostwords** [comment]
Hi, and thanks for writing.

[CloudFront](https://en.wikipedia.org/wiki/Amazon_CloudFront) is a content delivery service CDN product provided by Amazon. It shouldn't be a surprise that a cloudfront.net domain comes from Amazon as CloudFront is a part of Amazon.

CloudFront domains are currently on Privacy Badger's "yellowlist". Domains on that list are allowed to load but without access to cookies or local storage. This is a compromise between privacy and usability. Blocking cookies is more private than not doing anything, but less private than blocking the domain outright. The reason Privacy Badger makes this compromise for CloudFront is to avoid breaking too much of the Web for you.

Privacy Badger is meant to be an install-and-forget tool. Generally speaking, you should leave and the sliders alone and let Privacy Badger do its job automatically.

Let me know if you have any other questions.

**Comment by ghostwords** [comment]
By the way, you can also always email `extension-devs@eff.org` to get help with Privacy Badger. I am going to add this info to the README now.

**Comment by Pokerguy365** [comment]
> By the way, you can also always email `extension-devs@eff.org` to get help with Privacy Badger. I am going to add this info to the README now.

Thank you for clarifying and the succinct easy to understand response. I am quite embarrassed at how I went about proceeding with this post and can now see the emotion within the post was giving off very negative energy. Although this is true I greatly appreciate that you handled this very formally and appreciate the swiftness of your actions. In the future if I find and item out of place or odd I will research it thoroughly and use a template to format my future posts if provided with one.

With sincere apologies,

Pokerguy365

**Comment by ghostwords** [comment]
No need to apologize and glad I could help!
