### ISSUE TITLE
Privacy Badger breaks Boomla logins

### ISSUE THREAD

**Issue by zupa-hu** [EFForg/privacybadger#2619]
#### What is your browser and browser version?
Chrome 81

#### What is broken and where?
[Boomla](https://boomla.com/) is a free website builder and web development platform. Each website/project runs on a custom domain, and most users end up having lots of websites very quickly. Boomla uses a central login system to avoid having to log in to every website, which is implemented by a central cookie on boomla.com.

#### What is the "culprit" domain?
boomla.com

#### What is your debug output for this domain?

```
**** ACTION_MAP for boomla.com
boomla.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1590892334605
}
**** SNITCH_MAP for boomla.com
boomla.com [
  "boomla-theme.boomla.net",
  "zupa.hu",
  "checkerr.org"
]
```

**Comment by ghostwords** [comment]
Hello and thanks for the report!

Would Boomla be able and willing to abide by the [EFF Do Not Track policy](https://www.eff.org/dnt-policy)'s requirements on `boomla.com`? Posting the policy on each affected domain will tell Privacy Badger to always allow loading of resources from that domain.

**Comment by zupa-hu** [comment]
I'm sorry, I'm a 1-person team, bombarded with feature requests for a free product and there are several extensions out there which break the login system, I learned about 2 in 2 days. I just don't have the bandwidth to deal with it.

I understand if you don't want to whitelist domains simply based on a request. I thought I'd ask anyway.

**Comment by ghostwords** [comment]
Privacy Badger automatically learns to block domains by watching which domains appear to track you on multiple sites. You can learn more by visiting [our FAQ](https://privacybadger.org/#faq).

We don't currently have a way to "whitelist" domains entirely. I could add your domain to our "yellowlist", but that will block your domain's cookies and that doesn't help us here since you use the domain for login.

Can you use a dedicated subdomain for the central login system? It should be straightforward to post the EFF DNT policy on that subdomain then (since you wouldn't be using it for anything else).

**Comment by ghostwords** [comment]
In any case, I understand what you're saying. You have to prioritize, right. For now you can just advise your users who also use Privacy Badger to either move the slider for `boomla.com` to "green", or to disable Privacy Badger on their sites.

**Comment by zupa-hu** [comment]
Thanks for the input. For now, I'll put this back on my TODO list for later. Unfortunately, `boomla.com` won't appear in the drop-down for allowing it on the Privacy Badger UI as it is only sent on the first request which will also cause a reload if you are logged in as content may change. I understand it's fairly easy to whitelist it anyway but the user who reported it removed the extension instead and declared the issue fixed.

Thanks for your time, I'm closing this for now.

**Comment by ghostwords** [comment]
OK, thanks for the feedback! I see that it's still too easy to miss the "Disable Privacy Badger for this site" button for some reason.
