### ISSUE TITLE
google-analytics is not blocked

### ISSUE THREAD

**Issue by rshumsky** [EFForg/privacybadger#2626]
I blocked google-analytics com domain in extension but extension not blocking it.

Request to g-analitics ends with status 307 and contains header `Location` with tracking script in base64 format.
![image](https://user-images.githubusercontent.com/3874585/84079104-ac801680-a9e2-11ea-8842-25d66bb3b3c1.png)

**Comment by ghostwords** [comment]
Hello! What you see is Privacy Badger redirecting the request `analytics.js` to Privacy Badger's built-in ["surrogate script" for Google Analytics](https://github.com/EFForg/privacybadger/blob/ea12d50f70958117ae96a2db4fad63133c318e13/src/data/surrogates.js#L362-L413). Surrogate scripts are a [compatibility improvement](https://github.com/EFForg/privacybadger/blob/master/doc/fixing-broken-sites.md#javascript-errors) over simply blocking certain script requests. (You can base64-decode the location string to verify it matches Privacy Badger's dummy script.)

Let me know if you have any other questions.

**Comment by ghostwords** [comment]
By the way, Google Analytics should be blocked by default, [thanks to pre-training](https://www.eff.org/deeplinks/2018/08/giving-privacy-badger-jump-start). Was it not for you?

**Comment by rshumsky** [comment]
@ghostwords, sorry for bothering you. I was in a little panic when saw this. Probably ga domain was blocked but I didn’t understand that yesterday.
