### ISSUE TITLE
Can't use 'comment' section in Facebook-moderated online comment space.

### ISSUE THREAD

**Issue by sisjon912** [EFForg/privacybadger#263]
I go online to the Auburn Journal (www.auburnjournal.com). Commenting there requires being signed in to Facebook. When Privacy Badger is protecting me on a 'story' page, it is observing 28 (!) parasites and I cannot comment. When I try, a dialog opens for 1/10 sec and vanishes.
It would be nice if PB could detect this activity and tell me which of its blocks is preventing me from commenting. As it is I have to disable PB and then re-enable it.

**Comment by SwartzCr** [comment]
Hi @sisjon912 could you attach an image of the domains being blocked and their statuses to this issue?
Are you still having this problem, or has something happened in the intervening months?

**Comment by sisjon912** [comment]
Hello

The problem persists. I comment at the Auburn Journal (www.auburnjournal.com) in the opinion section. When I enable PB, I am unable to post the comment. The first attempt asks me what I want to use and I select Facebook; the second attempt puts up a dialog that lasts for 1/10 sec and which I can’t read; the third attempt just does nothing.  As soon as I disable PB for that site and refresh the page I can comment.

 

I have attached a screen shot of the AJ and a montage of the sites that PB is working on.

 

There are several other sites that behave this way, I just prefer to run PB and not comment there at all. I am running win 8.1 and Chrome.

 

Thanx

John S

**Comment by cooperq** [comment]
We should see if we can use social widget replacement for this.

**Comment by sisjon912** [comment]
Hi

I now run Win 10 and Chrome and just retested the situation. The problem does still persist. It is more explicit in that when PB is enabled for the Auburn Journal the comment entry dialog is no longer even visible. There are of course 24 trackers on this site and PB blocks 20 of them and restricts the others.

Glad your team has the space to address this!

Thanks

John S

**Comment by cooperq** [comment]
So the problem is that if you can use facebook comments then facebook can track you. Anything I do that allows facebook comments everywhere also lets facebook track you everywhere. 
But, it is possible that i can replace the facebook comments section with a click to play button. This would let you decide when it is okay for facebook to track you so that you can see and post comments. This may not in fact be possible, but I will look into it.

**Comment by sisjon912** [comment]
I use facebook and have PB enabled there, so I guess it tracks me when I post etc and really I don’t care too much; it’s those other sites with 40 or 50 other parasites that bother me.

John S
