### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Kreuger** [EFForg/privacybadger#2630]
Hey guys i was just wondering if it would be possible to add a setting for a dark theme. I use PB on Firefox and have most of my settings set to dark however the box that pops up when you click on PB is glaringly bright. So it would be great if we could have a setting to change it.

**Comment by ghostwords** [comment]
Hello and thanks for the suggestion!

Hmm, interesting, we may be able to make use of the [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/) media query. Would you happen to know if this will work for your setup?

Have you looked into getting [ShadowFox](https://github.com/overdodactyl/ShadowFox) to support Privacy Badger?

**Comment by Kreuger** [comment]
I have not. I had some issues with ShadowFox on my laptop. I'm currently using the Dark Reader extension along with some custom CSS to theme Firefox itself. But I did not create the code so I'm not sure how to do it for PB.

**Comment by Kreuger** [comment]
There's some CSS code [here](https://www.reddit.com/r/FirefoxCSS/wiki/index/uubo) for adding a dark theme to the UBlock Origin extension. Maybe this would help you?

**Comment by ghostwords** [comment]
@Kreuger How did you enable dark theme in Firefox? Did you have to change any `about:config` settings?

**Comment by Kreuger** [comment]
> @Kreuger How did you enable dark theme in Firefox? Did you have to change any `about:config` settings?

The next version of Firefox for Android has support for some add-ons including one called Dark Reader.

**Comment by ghostwords** [comment]
I'm sorry, I don't understand. The reason I asked how you set up your browser (Firefox) to prefer dark mode/themes, is that I'm trying to confirm that my (WIP) solution (#2648) will work for you.

**Comment by Kreuger** [comment]
I don't follow. I didn't change any flags for the dark theme. I just enabled the addon. Maybe it changed it for you?

**Comment by ghostwords** [comment]
OK, I think I see. You're saying you installed Dark Reader in Firefox, and that's it. Do I understand you right?

From what I can tell though Dark Reader is just for changing the appearance of websites, not Firefox itself, and not other extensions installed in Firefox.

Is your Firefox UI still set to the default theme? Have you configured your OS to use a dark theme?

**Comment by Kreuger** [comment]
Ah yes, now I see the confusion. Firefox itself is dark because of the setting in the app itself. Under settings - > Customize you can pick a theme. I imagine it just changes the flag you mentioned. 

That's on mobile though. On my laptop, I've changed the theme via the userChrome.css/userContent.css. I can't remember which one is for web pages and which one is for the UI of Firefox itself.
