### ISSUE TITLE
"Prevent WebRTC from leaking local IP address" blocks ALL IP addresses

### ISSUE THREAD

**Issue by Ambyjkl** [EFForg/privacybadger#2632]
#### What is your browser and browser version?
Broken on:
Chromium 83.0.4103.97 on Arch Linux
Brave 1.9.80 (Chromium 81.0.4044.138) on Arch Linux

Works on Firefox

#### What is broken and where?
The "Prevent WebRTC from leaking local IP address" option blocks all IP addresses, even the public ISP IP address. Testing ICE candidates at https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

Setting enabled:
![image](https://user-images.githubusercontent.com/19406708/85044781-1b383f00-b15c-11ea-961f-9d0fcef0a703.png)

Setting disabled:
![image](https://user-images.githubusercontent.com/19406708/85044799-22f7e380-b15c-11ea-9019-ce4367dca825.png)

Related reddit post: https://www.reddit.com/r/uBlockOrigin/comments/hbea3z/prevent_webrtc_from_leaking_local_ip_address/

Related fix commit in Ublock Origin:
https://github.com/gorhill/uBlock/commit/64cfc5779d87612f87bd5f9bd5581704d5795b64

**Comment by ghostwords** [comment]
Hello! Thanks for letting us know and thanks for the excellent bug report!
