### ISSUE TITLE
Breaks HomeToGo sites (x2)

### ISSUE THREAD

**Issue by DonatasUziela** [EFForg/privacybadger#2635]
#### What is your browser and browser version?

Chrome, Version 83.0.4103.106

#### What is broken and where?

Javascript and css files are not being served at:

- https://www.hometogo.com
- https://www.tripping.com
- https://www.wimdu.com
- https://www.feries.com
- https://www.casevacanza.it
- (and other top level domains for given sites)

#### What is the "culprit" domain?
cdn2.hometogo.net

#### What is your debug output for this domain?
```
**** ACTION_MAP for hometogo.net
cdn.hometogo.net {
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0,
  "userAction": ""
}
cdn2.hometogo.net {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1593398549150,
  "userAction": "user_block"
}
hometogo.net {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
tc.hometogo.net {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1593199841240,
  "userAction": ""
}
**** SNITCH_MAP for hometogo.net
hometogo.net [
  "wimdu.com",
  "wimdu.de"
]
```

#### Additional information
Same issue was already solved for `cdn.hometogo.net` domain with this: https://github.com/EFForg/privacybadger/issues/2440 . Would be great if `cdn2.hometogo.net` domain would also be added same way to the yellow list. Thanks in advance

**Comment by ghostwords** [comment]
Thanks for the report!
