### ISSUE TITLE
PB blocked my CDN address

### ISSUE THREAD

**Issue by erolj** [EFForg/privacybadger#2638]
#### What is your browser and browser version?
Firefox 78.0.1

#### What is broken and where?
kawanua.id
And, every site using my CDN resources from the URL address below.

#### What is the "culprit" domain?
static.my.id

#### What is your debug output for this domain?
```
**** ACTION_MAP for static.my.id
img.static.my.id {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1593587805919
}
static.my.id {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1593805808787
}
**** SNITCH_MAP for static.my.id
static.my.id [
  "kawanua.id",
  "127.0.0.1",
  "localhost"
]
```

**Comment by ghostwords** [comment]
Hello!

Privacy Badger sees a "PHPSESSID" cookie getting set by `static.my.id` resources and so picks it up as a tracker. Is there a reason for setting cookies from CDN domains? If you can keep your CDN domains cookie-free, Privacy Badger won't learn to block them in the future.

Alternatively, if `static.my.id` does not actually track users, it may be compliant with [EFF's Do Not Track policy](https://www.eff.org/dnt-policy). If you posted EFF's DNT policy on the `static.my.id` domain, the policy file will tell Privacy Badgers to always allow resources from `static.my.id`.

Let me know if you have any questions.

**Comment by ghostwords** [comment]
Related: #817.

**Comment by erolj** [comment]
> 
> 
> Privacy Badger sees a "PHPSESSID" cookie getting set by `static.my.id` resources and so picks it up as a tracker. Is there a reason for setting cookies from CDN domains? If you can keep your CDN domains cookie-free, Privacy Badger won't learn to block them in the future.
> 
The `static.my.id` domain is cookie-free. Apparently `img.static.my.id` that actually causes this "PHPSESSID" cookie issue, and I'm going to move all resources from that subdomain. Hopefully, this will resolve the issue.

> Alternatively, if `static.my.id` does not actually track users, it may be compliant with [EFF's Do Not Track policy](https://www.eff.org/dnt-policy). If you posted EFF's DNT policy on the `static.my.id` domain, the policy file will tell Privacy Badgers to always allow resources from `static.my.id`.
> 
I will consider doing this as well.

Thanks for the enlightenment.
