### ISSUE TITLE
utteranc.es domain blocked

### ISSUE THREAD

**Issue by jdanyow** [EFForg/privacybadger#2640]
#### What is your browser and browser version?

Chrome

#### What is broken and where?

https://github.com/utterance/utterances/issues/341

https://utteranc.es

#### What is the "culprit" domain?

`utteranc.es`

**Comment by ghostwords** [comment]
Hello and thanks for reaching out!

Could you provide some example pages that use the utterances comments widget?

If utterances doesn't actually track its users, it may be compliant with [EFF's Do Not Track policy](https://www.eff.org/dnt-policy). If you were to post EFF's DNT policy on each compliant utterances subdomain, it will tell Privacy Badgers to always allow resources from those subdomains.

Let me know if you have any questions.

**Comment by alexandru** [comment]
Some websites that use this are in this list: https://github.com/utterance/utterances/blob/master/SITES.md#sites-using-utterances

The privacy policy is here, which I believe corresponds to EFF's DNT policy, as they say they do not track users or log data, the only functional piece being a cookie being set storing the GitHub token used for authentication: https://github.com/utterance/utterances/blob/master/PRIVACY-POLICY.md

Personally I've bumped into this issue trying to integrate this on my personal website and [I'm very privacy concious](https://alexn.org/docs/privacy-policy.html). Would appreciate if you whitelisted this service.

Thanks,

**Comment by ghostwords** [comment]
@alexandru Is the problem that Privacy Badger learns to block `api.github.com`? Could you share your [debugging information](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) for the "culprit" domain?

**Comment by alexandru** [comment]
@ghostwords it blocks access to `utteranc.es` or more specifically it blocks the request to: https://utteranc.es/client.js

I did as you asked and here's what I got:

```
**** ACTION_MAP for utteranc.es
api.utteranc.es {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
utteranc.es {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1594566988025
}
**** SNITCH_MAP for utteranc.es
utteranc.es [
  "danyow.net",
  "phil-opp.com",
  "winterland.me"
]
```

Just for good measure, here's the result from `api.github.com`, it appears a cookie is being blocked:

```
**** ACTION_MAP for github.com
github.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 0
}
api.github.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1582438144677
}
gist.github.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "cookieblock",
  "nextUpdateTime": 1582709876414
}
**** SNITCH_MAP for github.com
github.com [
  "fontawesome.com",
  "flurry.com",
  "visualstudio.com",
  "medium.com"
]
```

Note that `utteranc.es` wasn't blocked at first on my website.

1. with a clean browser, I went to my website — commenting widget was fine at first (Privacy Badger was reported `utteranc.es` with yellow), it wasn't blocked
2. I then visited multiple websites from that [sites using utteranc.es](https://github.com/utterance/utterances/blob/master/SITES.md#sites-using-utterances)

It worked for 2 or 3 websites, but then the blocking started happening.

**Comment by ghostwords** [comment]
Thank you! It seems like this problem can be solved by posting EFF's DNT Policy on all compliant and required domains (`utteranc.es` and `api.utteranc.es`?) as per my [above suggestion](https://github.com/EFForg/privacybadger/issues/2640#issuecomment-654354386).

>Note that utteranc.es wasn't blocked at first on my website.

[Privacy Badger starts blocking once it sees a domain perform tracking on three separate sites](https://privacybadger.org/#How-does-Privacy-Badger-work).

**Comment by ghostwords** [comment]
Closing for now. @jdanyow Let me know if you have any questions.
