### ISSUE TITLE
Enable/Disable Privacy Badger without refresh

### ISSUE THREAD

**Issue by kaovilai** [EFForg/privacybadger#2645]
User Story: I am not sure if the site is retrying to connect to something privacy badger is blocking but I would like to let in extra connections if it retries without losing form data etc that I have already put in earlier.

Todo
- add checkbox in settings if user wanted auto-refresh
- another button below / besides disable signaling a non-refreshing disable button.

**Comment by ghostwords** [comment]
Hello and thanks for the suggestion. Could you talk more about the specific case that prompted this idea? What did Privacy Badger break and where? Feel free to provide the relevant [debugging information](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain).

**Comment by kaovilai** [comment]
@ghostwords I am not sure if it broke it or not but I was shopping flights from airlines which seems to want to connect to many external sources whether for tracking or etc. It just loaded much faster after disabling but it appears that while PB is enabled, the site is retrying a few of the requests. Pausing/Disabling without refresh allows many sites to use the retry technique without losing form data. 
I believe it was klm.co.th which connects to klm.com and many other third parties.
I love the culture of let's fix it for everyone before we add a manual advanced feature. KISS ic.

**Comment by kaovilai** [comment]
I would love to see advanced features as an option though so it will be easier to test, and then you can later report success if it worked, whether it is a MDFP problem or not, can be tested easier before forking a new version and making PRs.

**Comment by ghostwords** [comment]
The thing is that we want Privacy Badger to be a general audience tool where no action is necessary most of the time. Our development resources are limited. Every feature has a development cost, followed by a perpetual maintenance cost. These have to be balanced against the potential benefits. How many users would benefit from the additional complexity?

I'll look into broken sites reports for KLM next week.

**Comment by ghostwords** [comment]
Related to #2559.

**Comment by kaovilai** [comment]
> I'll look into broken site reports for KLM next week.
Try to navigate to https://www.klm.co.th/trip with PB enabled. The site works when  www.static-kl.com is added to local yellowlist. By default it is blocked.
from the [debug script](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain)
This is the output
```


**** ACTION_MAP for static-kl.com
www.static-kl.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1594796482155
}
static-kl.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
img.static-kl.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1594816450129
}
**** SNITCH_MAP for static-kl.com
static-kl.com [
  "klm.co.uk",
  "klm.co.th",
  "klm.com",
  "klm.nl"
]
```
