### ISSUE TITLE
Rename yellowlist

### ISSUE THREAD

**Issue by kaovilai** [EFForg/privacybadger#2646]
Curious if EFF would be interested in following Linux removing color from labels.
["Linux team approves new terminology, bans terms like 'blacklist' and 'slave' | ZDNet"](https://www.zdnet.com/article/linux-team-approves-new-terminology-bans-terms-like-blacklist-and-slave/)

Colors aren't descriptive in itself anyways. This might save a few lookups in the future.

**Comment by ghostwords** [comment]
The "yellow" in "yellowlist" corresponds to the yellow color of Privacy Badger sliders. The slider colors correspond to traffic light colors: red for stop, yellow for caution and green for go. Does this help?

**Comment by kaovilai** [comment]
> The "yellow" in "yellowlist" corresponds to the yellow color of Privacy Badger sliders. The slider colors correspond to traffic light colors: red for stop, yellow for caution and green for go. Does this help?

Yes I know. That's not the point. Same can be said of blacklists.

**Comment by ghostwords** [comment]
>Same can be said of blacklists.

I'm sorry, I don't understand.

**Comment by kaovilai** [comment]
> 
> I'm sorry, I don't understand.

This is just a proposal for discussion. If it's not in the best interest to make a change then that's fine too.

I know you are genuine @ghostwords 
Thanks for your service to the community. 🤗

**Comment by ablanathtanalba** [comment]
I totally understand why the term 'blacklist' is being removed as a titling convention, because it unnecessarily casts a value judgment as black being a bad thing, and white being a good thing. I'm not sure the idea applies here in the same way, and I suspect that the "traffic light" color coding analogy is still useful in describing how Privacy Badger thinks about requests being made from potential trackers:

Green = not affected and requests flowing at regular speed, Yellow = requests are slowed down and restricted but not stopped entirely, Red = requests are stopped.

I might be missing how the traffic light analogy is upholding white supremacist social mores like the whitelist/blacklist convention is... If so, I'm all ears!

**Comment by kaovilai** [comment]
>I might be missing how the traffic light analogy is upholding white supremacist social mores like the whitelist/blacklist convention is... If so, I'm all ears!

I didn't register it as a traffic light at first. Just thought it is just arbitrary colors. AFAIK traffic light colors have not been involved in the same ways black and white colors has been. But consider that certain races/tribes have been described by color; red and yellow at least. It could be abused. Maybe someone's culture relate to red as being a lucky thing. Maybe their national color is yellow. Colors have very different meanings to different people and they can feel mixed signals from having lists be named after a color. Political parties have been described by the traffic light colors. Just thinking in terms of potential harm colors could caused.

Could we add a background to these symbols so it resembles the traffic light enclosure?
![image](https://user-images.githubusercontent.com/11228024/87379087-9c4af080-c5b9-11ea-8b20-f71e7cad8aeb.png)

**Comment by kaovilai** [comment]
Rounding the squares would also work I think

**Comment by ghostwords** [comment]
Note that we don't use the term "yellowlist" anywhere in Privacy Badger's UI. (We do use it (and explain it) in [our FAQ](https://privacybadger.org/#faq).) The average Privacy Badger user is unlikely to come into contact with the term.

**Comment by ghostwords** [comment]
I am still not clear on the need to stop using "yellowlist". However, I am fairly certain we have not run into any confusion with the term, or with the colors we use for slider values. It is not important to know the colors are traffic light colors as long as you understand how the sliders work.

As per above, I'm closing this issue for now. I'm happy to reconsider if we get more feedback in the future.
