### ISSUE TITLE
Privacy Badger breaks text on Canvas charting software

### ISSUE THREAD

**Issue by STRML** [EFForg/privacybadger#2657]
#### What is your browser and browser version?
Chrome 84.0.4147.89, MacOS, 2020 Macbook (HiDPI)

#### What is broken and where?
The chart at https://www.bitmex.com/app/trade/XBTUSD ([full screen](https://www.bitmex.com/chartEmbed?symbol=XBTUSD)) has broken text labels and a broken X axis. They appear to be rendering at half width/height, suggesting Privacy Badger is breaking HiDPI somehow.

With Privacy Badger enabled, notice incorrect render output on X axis and on text labels on both axes:

<img width="556" alt="Screen Shot 2020-07-30 at 10 16 20 AM" src="https://user-images.githubusercontent.com/1197375/88981493-13f46d00-d294-11ea-83a9-57c2d932d1d3.png">

With it disabled, notice correct output and readable text on labels and X axis:

<img width="554" alt="Screen Shot 2020-07-30 at 10 17 50 AM" src="https://user-images.githubusercontent.com/1197375/88981500-18208a80-d294-11ea-8ee0-a1c6268785ac.png">

#### What is the "culprit" domain?
No trackers blocked. I believe something the canvas fingerprinting protection is doing is causing this breakage.

#### What is your debug output for this domain?
No debug output.

Possibly related to #1226

**Comment by STRML** [comment]
Figured it out. Going to close this as a dupe of #1226 and explain it there.

**Comment by ghostwords** [comment]
Also #1854.
