### ISSUE TITLE
GitHub Codespaces beta is blocked from launching

### ISSUE THREAD

**Issue by jakejarvis** [EFForg/privacybadger#2667]
#### What is your browser and browser version?

Chrome 84.0.4147.125 on macOS 10.15.6

#### What is broken and where?

Launching an instance of [GitHub Codespaces](https://github.com/features/codespaces) (in beta). Seems to be because they're really just a skin on top of Visual Studio Online and subsequently all of the third-party VS domains..?

#### What is the "culprit" domain?

1. Unblocking `online.visualstudio.com` allowed me to spin up and open a Codespace.
2. Unblocking `prod.liveshare.vsengsaas.visualstudio.com` allowed it to properly run once open.

Codespaces are launched as a subdomain on `github.dev`, if that helps.

#### What is your debug output for this domain?

```
**** ACTION_MAP for visualstudio.com
visualstudio.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
online.visualstudio.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1597702882279
}
prod.liveshare.vsengsaas.visualstudio.com {
  "userAction": "user_allow",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1597727528950
}
**** SNITCH_MAP for visualstudio.com
visualstudio.com [
  "dior.com",
  "seriouseats.com",
  "github.dev"
]
```

Thanks! 😊

**Comment by ghostwords** [comment]
Hello and thanks for letting us know! Seems like we should be able to fix this by teaching Privacy Badger that `visualstudio.com` and `github.dev` [belong to the same entity](https://github.com/EFForg/privacybadger/blob/master/doc/fixing-broken-sites.md#domains-that-are-part-of-the-site-but-dont-look-like-it) (Microsoft).

**Comment by ghostwords** [comment]
I wonder why Privacy Badger thought that it saw `visualstudio.com` track on `dior.com` and `seriouseats.com`.  Another case of #1997?
