### ISSUE TITLE
Disqus widgets not always replaced

### ISSUE THREAD

**Issue by tjhietala** [EFForg/privacybadger#2668]
The recently added Disqus widget replacement feature does not seem to always work. For example here: https://9to5linux.com/ubuntu-20-10-groovy-gorilla-artwork-by-sylvia-ritter-looks-astonishing-made-with-krita

Tested on PB 2020.7.21 on Firefox & Chrome.

**Comment by ghostwords** [comment]
Hello and thanks for the report! This should be fixed in #2653 by 678ad1ab807530763cb88f8b6635a5c16b9a4bac.
