### ISSUE TITLE
Request adding Calendly to Yellowlist

### ISSUE THREAD

**Issue by hwhelchel** [EFForg/privacybadger#2670]
#### What is your browser and browser version?
Chrome 84.0.4147.135
#### What is broken and where?
I have a calendly embed on my website here https://usevouch.com/chat
When Privacy Badger is on, the calendly inline embed doesn't show up for me.
#### What is the "culprit" domain?
calendly.com

Please follow the debug instructions to identify which domain breaks stuff when blocked:
https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain

#### What is your debug output for this domain?
To get the debug output, please see the instructions link above.
```js
**** ACTION_MAP for calendly.com
assets.calendly.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1598026800395,
  "userAction": ""
}
calendly.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1598353594993,
  "userAction": ""
}
**** SNITCH_MAP for calendly.com
calendly.com [
  "validately.com",
  "convopanda.com",
  "postperk.com",
  "usevouch.com"
]
```

<img width="323" alt="Screen Shot 2020-08-21 at 5 43 42 PM" src="https://user-images.githubusercontent.com/4792375/90937952-e8b5f700-e3d5-11ea-8a77-355324f47c43.png">

**Comment by ghostwords** [comment]
Thanks for getting in touch!

**Comment by hwhelchel** [comment]
Just curious when will this likely be in production?

**Comment by hwhelchel** [comment]
Just wanted to know if I needed to do anything to see the update in my browser. Thank you!
