### ISSUE TITLE
Privacy Badger breaks websites using cdn.snipcart.com by blocking the domain completely

### ISSUE THREAD

**Issue by daltimus11** [EFForg/privacybadger#2674]
#### What is your browser and browser version?
Firefox 80.0.1 (64-bit)

#### What is broken and where?
My website (currently in development), and any other sites using Snipcart. This is an embedded e-commerce platform, please see https://snipcart.com/ for information. When changing Privacy Badger to the middle slider, everything works fine. Here is a site that is an example shared on the Snipcart blog that can demostrate: https://kinderkamerposters.com/

#### What is the "culprit" domain?
Both cdn.snipcart.com and app.snipcart.com are blocked completely by default.

#### What is your debug output for this domain?
Tested both, same output for each:
```
**** ACTION_MAP for snipcart.com
cdn.snipcart.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1599202980375
}
snipcart.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
app.snipcart.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1599448060324
}
**** SNITCH_MAP for snipcart.com
snipcart.com [
  "snipcart-hugo-forestry.netlify.app",
  "flambette.com",
  "localhost"
]
```
####
I do not work for Snipcart, I am just a customer wishing to use it on my site. So I do not know for sure if there is a good reason it is blocked and I don't understand the debug output. The only thing that I expect to be happening here is that websites embedding Snipcart are exchanging necessary information with the Snipcart domain in order to operate the e-commerce software.

Please let me know if an adjustment can be made. Or if there is a reason snipcart.com should be entirely blocked instead of set to the center slider.

Thank you very much

**Comment by ghostwords** [comment]
Thanks for getting in touch!

**Comment by ghostwords** [comment]
You can either restart Privacy Badger/your browser to see the update right away, or wait a day or so for it to happen automatically.

**Comment by JeanSebTr** [comment]
Wow that was quick!

Thanks @daltimus11 for opening the issue and @ghostwords for adding us to the list. We've recently received a few reports from merchants but had trouble triggering the block in our tests.

In case you're wondering, Snipcart doesn't do any tracking across merchant websites. We suspect our endpoint that preloads merchant settings or our load balancer's cookies to be what triggered the block.

**Comment by JeanSebTr** [comment]
Further reviews would be required, but I believe we can comply without much trouble. We already limit what we log on the setting preload endpoint (when no cart has been started by customers) and I believe we're covered by _Exception 2 Transactions_ (customer adding items to a cart) but we could still implement _Exception 1.c_ for the sake of being explicit when a cart session is started even though those cookies are only tied to the merchant's domain.

**Comment by ghostwords** [comment]
Nice! You could then post the policy on each relevant domain. This will tell Privacy Badgers to always allow loading of resources from those domains (and show a DNT indicator in the UI).

The cookie-blocking yellowlist is a compromise, and could still result in breakage (if something served by one of your domains were to depend on cookies but cookies were blocked). Although @daltimus11 reported above that moving the slider to "yellow" does seem to restore functionality.

**Comment by ghostwords** [comment]
Let me know if you have any questions (alexei at eff dot org).

**Comment by JeanSebTr** [comment]
> The cookie-blocking yellowlist is a compromise, and could still result in breakage (if something served by one of your domains were to depend on cookies but cookies were blocked)

Noted! We should be fine with this, but I'll see if we can prioritize, this seems worth going the extra mile to get the indicator.
