### ISSUE TITLE
Missing Walmart tracker

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [EFForg/privacybadger#2677]
Badger detects nothing on [walmart.com](https://www.walmart.com/).

But NoScript detects beacon.walmart.com.

![Walmart beacon](https://user-images.githubusercontent.com/15519219/92434244-d9cd9380-f18e-11ea-964d-1198c5bd42f1.jpg)

Ghostery also detects a tracker, but only lists it as www.walmart.com.

**Comment by ghostwords** [comment]
Hello!

#### Regarding `beacon.walmart.com`:

Privacy Badger automatically stops non-consensual third-party tracking. If Walmart were to track you across the Web without your permission, Privacy Badger would try to stop it.

Privacy Badger [doesn't generally concern itself with tracking by sites you choose to visit directly](https://privacybadger.org/#What-about-tracking-by-the-sites-I-actively-visit%2c-like-NYTimes.com-or-Facebook.com) (first party tracking). Walmart tracking you on Walmart.com is different from Walmart tracking you on non-Walmart sites.

#### Regarding not finding any trackers on Walmart.com:

Privacy Badger reports 14 trackers out of the box (in a new browser profile) when I went to Walmart.com just now. If you use other blockers (like NoScript), your blockers might stop most trackers before Privacy Badger ever gets to see them. This is fine!


Let me know if you have any questions.
