### ISSUE TITLE
Webrtc leak can't work

### ISSUE THREAD

**Issue by Alampdow** [EFForg/privacybadger#2678]
Seems prevent WebRTC from leaking local ip address can't work properly.

I have used this website to test, https://webbrowsertools.com/test-webrtc-leak/

Hope it can be fixed.

**Comment by ghostwords** [comment]
Hello!

I believe this is working as intended. Privacy Badger sets WebRTC IP handling policy to `"default_public_interface_only"` when the protection is enabled. This corresponds to [WebRTC behavior mode 3](https://tools.ietf.org/html/draft-ietf-rtcweb-ip-handling-01#page-5), which says your private IP is not provided. This is what we mean by "local IP address".

Setting WebRTC behavior to mode 4 breaks all WebRTC applications when you don't have a proxy configured.  See #2632 for this very problem. If you do have a proxy, and you would like to force WebRTC to use it, I suggest installing a dedicated extension that does switch WebRTC to mode 4.

Let me know if you have any questions.
