### ISSUE TITLE
Add Queue-it cookie to  yellowlist.

### ISSUE THREAD

**Issue by betcheco** [EFForg/privacybadger#2680]
#### What is your browser and browser version?
Any Browser.  Tested in Google Chrome is up to date
Version 85.0.4183.102 (Official Build) (64-bit)

#### What is broken and where?
Queue-it provides companies with a virtual waiting room.
Queue-it JavaScript solution works by creating a cookie on the website and this is needed for the solution to work.
Please refer to https://github.com/queueit

#### What is the "culprit" domain?
queue-it.net

#### What is your debug output for this domain?

```
**** ACTION_MAP for queue-it.net
static.queue-it.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 0
}
queue-it.net {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 0
}
**** SNITCH_MAP for queue-it.net
queue-it.net [
  "ninetronics.com",
  "ticketania.com"
]

```

**Comment by ghostwords** [comment]
Hello!

If a cookie is required, adding `queue-it.net` to the yellowlist won't help as yellowlisted domains have their cookies blocked.

Might Queue-it be compatible with [EFF's DNT policy](https://www.eff.org/dnt-policy)? If Queue-it is compatible, posting the policy on each Queue-it domain will tell Privacy Badger to always allow resources (with cookies) from those domains.

**Comment by betcheco** [comment]
Hi! Thanks for the response. The sites which integrate Queue-it couldn't load properly, as I understand be yellowlisted will still block cookies but can load other elements from the domain.

**Comment by ghostwords** [comment]
Correct, resources belonging to a domain with its slider set to "yellow" will be allowed to load but without access to cookies.

>Queue-it JavaScript solution works by creating a cookie on the website and this is needed for the solution to work.

I was responding to your statement that cookies are required for Queue-it.

**Comment by betcheco** [comment]
Perfect! Thanks again. Is it possible to add the domain to the yellowlist?

**Comment by ghostwords** [comment]
I'm a bit confused. Are `queue-it.net` cookies required for Queue-it to function?

**Comment by betcheco** [comment]
Sorry for the confusion. In some cases, cookies are not required, so adding the domain in the yellowlist should fix the issue. In other cases, cookies from the same domain as the site are required but not from queue-it.net.
