### ISSUE TITLE
Privacy Badger breaks ktor.io

### ISSUE THREAD

**Issue by dmitry---k** [EFForg/privacybadger#2682]
#### What is your browser and browser version?
Firefox 80.0.1 (64-bit), macOS 10.15

#### What is broken and where?
https://ktor.io/docs/quickstart-index.html (page will not render correctly)

#### What is the "culprit" domain?
`resources.jetbrains.com`

#### What is your debug output for this domain?
```
**** ACTION_MAP for jetbrains.com
jetbrains.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
resources.jetbrains.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1600319686290
}
account.jetbrains.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1583627272547
}
**** SNITCH_MAP for jetbrains.com
jetbrains.com [
  "kotlinconf.com",
  "kotlinlang.org",
  "intellij.net"
]
```

#### Details
The [ktor.io page](https://ktor.io/docs/quickstart-index.html) will not render correctly, since it requires `https://resources.jetbrains.com/storage/help-app/v3/app.js` to load, whereas resources.jetbrains.com is blocked by the PrivacyBadger.

**Comment by rock3r** [comment]
Can confirm the same happens to me. Privacy Badger on Chrome (same computer) does not block the domain and the page renders correctly.

**Comment by ghostwords** [comment]
Thanks for the report!
