### ISSUE TITLE
Can't log in to our app; add rest.growinginteractive.com to yellowlist or MDFP list please

### ISSUE THREAD

**Issue by user24** [EFForg/privacybadger#2691]
#### What is broken and where?
Logging in to our garden planner fails as Privacy Badger blocks our API, which is hosted on another domain. To reproduce you do not need an account, simply try to log in as anything at all and you will see the message "We were unable to complete your request at this time, please try again or contact us." e.g. on this url: https://www.growveg.co.uk/account/login

Domains affected are ourselves and our white-label clients:

- growveg.com
- growveg.co.uk
- growveg.com.au
- growveg.co.za
- bigbughunt.com
- our client sites all have "gardenplanner" as their subdomain, e.g. https://gardenplanner.example.com/. If possible to allow based on that pattern that would be best as we add new clients fairly regularly. If not I can supply the current full list of our clients over email/PM, and we'll open new issues as other clients come on board.

Alternatively, I think simply globally yellowlisting would also work for us if that's better/easier than setting up MDFP exceptions for gardenplanner.* subdomains.

#### What is the "culprit" domain?
- rest.growinginteractive.com

#### What is your debug output for this domain?

```
**** ACTION_MAP for growinginteractive.com
rest.growinginteractive.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1601577602630
}
growinginteractive.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
widgets.growinginteractive.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "allow",
  "nextUpdateTime": 1601282266873
}
**** SNITCH_MAP for growinginteractive.com
growinginteractive.com [
  "growveg.co.uk",
  "bigbughunt.com",
  "growveg.com"
]

```

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch! I'll take a look next week, but in the meantime, might the affected domains be compatible with [EFF's DNT policy](https://www.eff.org/dnt-policy)? Declaring your compliance on each compatible domain will tell Privacy Badger to always fully allow loading of resources from that domain.

**Comment by user24** [comment]
Thanks, I will raise the idea of posting the DNT policy compliance on our domains. I think we already pass most of these requirements already but I'll need to check up on a few of the points.

Would I be right in thinking that adding the DNT policy file to rest.growinginteractive.com would allow resources from rest.growinginteractive.com to be loaded from any 3rd party, even if that party is not themselves DNT compliant?

**Comment by ghostwords** [comment]
It looks like Privacy Badger learns to block `growinginteractive.com` domains because of an Azure platform [ARRAffinity cookie](https://stackoverflow.com/questions/50741024/does-arraffinity-cookie-always-set-on-azure-web-application).

**Comment by ghostwords** [comment]
>Would I be right in thinking that adding the DNT policy file to rest.growinginteractive.com would allow resources from rest.growinginteractive.com to be loaded from any 3rd party, even if that party is not themselves DNT compliant?

Yes, although to clarify, I think you say "3rd party" to refer to the site that includes resources from `rest.growinginteractive.com`. To Privacy Badger, the site you choose to visit directly is the first party, and `rest.growinginteractive.com` is a third party.

Also please note the policy only applies to the domain it is posted on. So other `growinginteractive.com` 
 domains (`widgets.growinginteractive.com`) would still get blocked, unless they are compliant as well, and also declare that compliance.

Let me know if you have any other questions.

**Comment by user24** [comment]
> It looks like Privacy Badger learns to block growinginteractive.com domains because of an Azure platform ARRAffinity cookie.

I'll see if we can disable that, thanks for looking into this. If we are able to stop that cookie being sent, would that alone solve the problem of Privacy Badger users being unable to use our service?

> Also please note the policy only applies to the domain it is posted on. So other `growinginteractive.com`
> domains (`widgets.growinginteractive.com`) would still get blocked, unless they are compliant as well, and also declare that compliance.

Thanks, yes, I'm less concerned about widgets as that is not directly affecting people, and arguably should be blocked anyway; if someone's visiting example.com, who embed our widget, I think it's understandable if that's blocked as the visitor has no explicit relationship with us here. But in the case of `rest.growinginteractive.com` the only time a site will make a request to that domain is if a visitor is actually explicitly trying to use our service, which is why I though this might fall under MDFP.

**Comment by ghostwords** [comment]
>If we are able to stop that cookie being sent, would that alone solve the problem of Privacy Badger users being unable to use our service?

Going forward, yes.

**Comment by user24** [comment]
ok, thanks. We do run a geoip service on that subdomain too (in order to know where the user's garden is, so we can direct users to country-appropriate versions of the site, and disambiguate locations of reported garden pest sightings) so I would expect Privacy Badger to block that.

For the moment therefore, can you please add `rest.growinginteractive.com` as a yellowlisted domain, or as an MDFP for any domain with 'gardenplanner' as the subdomain, plus the domains listed above please?
