### ISSUE TITLE
The New GPC Signal not work

### ISSUE THREAD

**Issue by minutesinch** [EFForg/privacybadger#2695]
after update to 2020.10.7 i see its send GPC signal(The Global Privacy Control) by going to https://globalprivacycontrol.org/ and saw its not send GPC signal in top of site

**Comment by ghostwords** [comment]
Hello! Which browser and browser version do you have?

**Comment by ghostwords** [comment]
Is sending DNT/GPC signals enabled in your Privacy Badger options page?

**Comment by minutesinch** [comment]
Firefox 81.0.1 and DNT/GPC signals enabled in Privacy Badger's options.

**Comment by bcyphers** [comment]
If you visit the test page (https://global-privacy-control.glitch.me/), does it say whether the browser header is disabled, or the javascript, or both?

**Comment by ghostwords** [comment]
Let me know if you have more information.

**Comment by minutesinch** [comment]
> If you visit the test page (https://global-privacy-control.glitch.me/), does it say whether the browser header is disabled, or the javascript, or both?

the site return 

 _GPC signal not detected.
 Please download a browser or extension that supports it._

**Note that  in fenix version(Android-Mobile) its working well but in desktop version not  working!**

**Comment by ghostwords** [comment]
You repeated what https://globalprivacycontrol.org/ says when it doesn't detect the GPC signal. What does https://global-privacy-control.glitch.me/ say though?

**Comment by ghostwords** [comment]
Also, can you reproduce this problem on desktop if you disable your other extensions?

**Comment by minutesinch** [comment]
yes i disabled but even when disabling same issue occur

**Comment by minutesinch** [comment]
> You repeated what https://globalprivacycontrol.org/ says when it doesn't detect the GPC signal. What does https://global-privacy-control.glitch.me/ say though?>

https://global-privacy-control.glitch.me return (when Send websites the "Global Privacy Control" and "Do Not Track" signals enable)

Header present
Sec-GPC: "1" 

DOM signal present
navigator.globalPrivacyControl: false 

.well-known/gpc present

**Comment by ghostwords** [comment]
What happens if you open a [JavaScript console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console) on that page, type `navigator.globalPrivacyControl` and press <kbd>Enter</kbd>?

**Comment by ghostwords** [comment]
I'd like to figure out what's going on here, but I can't without more information. Let me know if anything is confusing or unclear.

**Comment by minutesinch** [comment]
> I'd like to figure out what's going on here, but I can't without more information. Let me know if anything is confusing or unclear.

i saw the notification but i forgot to respond because im busy, however  it do your steps navigator.globalPrivacyControl in that page and return false

**Comment by ghostwords** [comment]
Did `navigator.globalPrivacyControl` return `false` or did it return `undefined`? Just confirming.

**Comment by minutesinch** [comment]
return false

**Comment by ghostwords** [comment]
So this tells us that something overwrites `navigator.globalPrivacyControl` to `false` (Privacy Badger sets it to `"1"`). My first guess is that this is another extension of yours. I know you wrote you tried disabling all other extensions already, but ... I'm not sure what else this could be.

**Comment by ghostwords** [comment]
Can you reproduce the problem if you install Privacy Badger into a new [Firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)?

**Comment by ghostwords** [comment]
Again, it seems at this point that something else (another extension?) updates the value of `navigator.globalPrivacyControl` to `false`. I can't say more than this without more information.
