### ISSUE TITLE
odysee.com - breaking sometimes/for some users

### ISSUE THREAD

**Issue by tzarebczan** [EFForg/privacybadger#2698]
We've had a ton of complaints that privacy badger would block odysee.com or lbry.tv (this one has some ads, but could be unrelated). Would be great to have more information on why this may be happening. 

Learn more about LBRY/Odysee: https://lbry.com/about / https://lbry.tech

**Comment by ghostwords** [comment]
Hello!

Could you provide the [debugging information](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) for the affected domains?

Note you should run the debugging code on a Privacy Badger that learned to block your domain(s), or the output won't be so helpful.

**Comment by tzarebczan** [comment]
I tried the plugin with a fresh VM and it didn't block the page, but we get many reports that it does and they need to allow/disable. How else can we debug this? 

Could not get anything to run from the link as it's supposed to be used to debug the affected sites once they are blocked. 

```
(function () {
  const STR = getBaseDomain("https://odysee.com");
  let out = [],
    actionMap = badger.storage.getStore('action_map'),
    snitchMap = badger.storage.getStore('snitch_map');…
undefined
```

**Comment by ghostwords** [comment]
Could you ask the reporters to provide this information?

**Comment by ghostwords** [comment]
Let me know if you have more information please.

**Comment by tzarebczan** [comment]
Does this help at all? Looks like it's cookie related? 
![iB6C1CxV](https://user-images.githubusercontent.com/8120721/96661613-7cdf0480-131a-11eb-829b-be267d2af102.jpg)

**Comment by ghostwords** [comment]
What is the relationship between `odysee.com` and `lbry.com`/`lbry.tv`? Are these domains owned by the same entity?

**Comment by tzarebczan** [comment]
Yes, they are. LBRY is the parent company of odysee.com

**Comment by tzarebczan** [comment]
Thank you so much! If I had some extra time, I probably could have submitted a PR myself but didn't get a chance to scan the code :)
