### ISSUE TITLE
flyerservices.com blocked

### ISSUE THREAD

**Issue by hisomu** [EFForg/privacybadger#270]
Hello,

Could you add flyerservices.com to the greylist? It is a third party flyer solution which is used by many customers and is being blocked by Privacy Badger.

Here are some sites using the Flyer solution:
- http://www.superc.ca/fr/circulaire.html
- http://www.metro.ca/home.en.html
- http://www.londondrugs.com/Store-Flyer/eflyer,default,pg.html

The flyerservices.com only hosts our flyer solution, it does not have a parent website. We use the website in the following format:
- London Drugs: http://local.flyerservices.com/LDR/LDNRX
- Super C: http://local.flyerservices.com/MTR/SUPRC
- Shoppers Drug Mart: http://local.flyerservices.com/SDM/SDM

Our parent website is located here: http://tctranscontinental.com/en/services/execution/interactive-and-digital-channels/digital-promotions-marketing
Our privacy policy is located here: http://tctranscontinental.com/en/privacy-policy

Thank you

**Comment by BrokenSyntax** [comment]
I'm thinking this thing needs to not be allowed by anyone ever.
My office365 programs have started giving me cert warnings about name mismatches, when I look. Everything is getting filtered to ca.flyerservice.com's certificate.
Now I have some serious debugging to do >.> Damn malware.
