### ISSUE TITLE
Rename 'white list' for inclusive language

### ISSUE THREAD

**Issue by fridobox** [EFForg/privacybadger#2700]
Hi, using 'whitelist' is outdated, you should replace with 'allow list'.

See for example https://www.ncsc.gov.uk/blog-post/terminology-its-not-black-and-white

**Comment by ghostwords** [comment]
Hello. This should already be the case. Where do you see "whitelist"?

**Comment by ghostwords** [comment]
Let me know if you have more information.

**Comment by fridobox** [comment]
I have plugin 2020.10.7.

I see it in plugin options : in french I see 'Liste blanche'.

Look in source code for 'whitelisted'.
Mainly :
https://github.com/EFForg/privacybadger/blob/8c3cd8b934046b0160ba746f012a9a524f4cb95b/src/skin/options.html#L72

**Comment by fridobox** [comment]
Also found a 'blacklisted' : 
https://github.com/EFForg/privacybadger/blob/0eb52704ebce773ea094d3e4402934569e054e9f/src/lib/vendor/underscore-1.9.1.js#L1135

**Comment by ghostwords** [comment]
>I see it in plugin options : in french I see 'Liste blanche'.

Does the same concern exist in the French language?

>Also found a 'blacklisted'

That's a third-party library.

**Comment by ghostwords** [comment]
Our French translator writes:

>Unlike in english, i've never heard any concerns about this subject in french before. Certain expressions do use colours, but they have not been related to race so far. Therefore, i see no reason to change this, especially considering the very specific meaning that they carry.

**Comment by fridobox** [comment]
I mean even source code should not contain "whitelist", like i18n_whitelisted_domains in https://github.com/EFForg/privacybadger/blob/8c3cd8b934046b0160ba746f012a9a524f4cb95b/src/skin/options.html#L72
