### ISSUE TITLE
Privacy Badger opens a new tab in every "sync install" on Firefox stealing focus

### ISSUE THREAD

**Issue by IlgazC** [EFForg/privacybadger#2702]
On Firefox when you login to your Firefox account, it syncs extensions and installs them. Every time I setup a new Firefox or Re/Login Privacy badger pops up in a tab saying I just installed Privacy Badger stealing focus. It isn't just Privacy Badger but Privacy Badger is the largest/most popular extension doing this.

Mozilla developers say an extension can figure out a new install and behave based on that. It would set a great example to other extension developers.

**Comment by ghostwords** [comment]
Hello! Exactly, the welcome page should only come up for new installs.

>Mozilla developers say an extension can figure out a new install and behave based on that

Could you link to this discussion? It would be good to know how extensions should differentiate between regular new installs and new installs driven by Firefox Sync.

Do you know of any add-ons that handle this well? As in, show a welcome page upon manual installation but not Firefox Sync installation?

How often does this happen for you? As in, how much of a hassle is this? Knowing would help prioritize this issue.

**Comment by IlgazC** [comment]
> Hello! Exactly, the welcome page should only come up for new installs.
> 
> > Mozilla developers say an extension can figure out a new install and behave based on that
> 
> Could you link to this discussion? It would be good to know how extensions should differentiate between regular new installs and new installs driven by Firefox Sync.
> 
> Do you know of any add-ons that handle this well? As in, show a welcome page upon manual installation but not Firefox Sync installation?
> 
> How often does this happen for you? As in, how much of a hassle is this? Knowing would help prioritize this issue.

Hello and thanks for quick response.

I actually have video captures of "the experience" at my bug report showing other extensions (not all) doing the same thing, you can see on https://bugzilla.mozilla.org/show_bug.cgi?id=1671769 (check files).
Also Chromium seems to just install extensions without any windows opening etc (it has a video too)

Here is the comment of Mozilla developer on their official chat:
https://matrix.to/#/!xhdLwUuqqCVTczofof:mozilla.org/$_VIj4LgmQURJnarOJMW_rkUOyq0jyeBBFT7omyeBSe8?via=mozilla.org&via=matrix.org&via=ungleich.ch

I must say it is very annoying.

**Comment by ghostwords** [comment]
>Here is the comment of Mozilla developer on their official chat
Could you paste the comment here?

>I must say it is very annoying.
How often does this happen to you?

**Comment by dannycolin** [comment]
Not a Mozilla developer, but I talked with @IlgazC on Matrix.

A solution could be to use `storage.sync` at [line 756](https://github.com/EFForg/privacybadger/blob/092e76f1619ba8294b041cd83d67db87dc9025e0/src/js/background.js#L756) in `/src/js/background.js` to store an object like `firstInstall: [true | false]`. So next time the user installs the addon you just retrieve that value before opening the new install window. 

Of course, you can go further by syncing the version and date, so you could open the window if there was a major change that the user should know about even if it already installed the addon.

**Comment by ghostwords** [comment]
This is blocked by [extension sync storage getting synced after the extension itself](https://bugzilla.mozilla.org/show_bug.cgi?id=1671769#c9) (sync storage should instead sync before).

**Comment by ghostwords** [comment]
>Also Chromium seems to just install extensions without any windows opening etc (it has a video too)

I wonder what Chrome does different. Does it sync all extension data kept regular (non-sync, `storage.local` vs. `storage.sync`) extension storage upon sync-initiated extension installation? If that is so, it seems like a good idea and something that Firefox should look into, as this provides a better user experience by default.

**Comment by ghostwords** [comment]
On further reflection, I don't think merely syncing the state of whether we've already shown the welcome page or not is the right approach. If you see the welcome page, it means your Privacy Badger just got installed anew and is set to all defaults. If you customized any settings, your customizations will not be present in this new installation. If we sync only the state of the welcome page, it will hide the fact that no other settings were synced.

**Comment by ghostwords** [comment]
The right thing for Privacy Badger would be to sync all settings, most likely excluding local learning (due to storage size limits of sync storage). However, from what I know, automatic browser settings sync is hard to do right, possibly due to bugs in Firefox. Your newer settings may get overwritten by older settings, for example. This is why our current browser sync support is limited and manual (see the Manage Data tab on Badger's options page). Getting everything synced automatically feels like  a lot of effort for uncertain benefit.

Closing for now, but happy to continue the conversation.
