### ISSUE TITLE
KIProtect Consent Manager Is Being Blocked

### ISSUE THREAD

**Issue by adewes** [EFForg/privacybadger#2703]
#### What is your browser and browser version?

Fireox 81.0.2 (Linux)

#### What is broken and where?

We provide a hosted open-source consent manager (Klaro! - https://github.com/kiprotect/klaro) that is included in a website using a script tag loading JS from our backend (`https://api.kiprotect.com/v1/privacy-managers/[manager ID for website]/klaro.js`), currently that endpoint redirects to a CDN-hosted version of Klaro. We do not attempt to set any tracking cookies (except the Cloudflare cookie) when loading Klaro.

I can't figure out why our request is getting blocked, is it because of the redirect or the CDN cookie? We don't perform any tracking and only store information on the client that is necessary to document the consent choice of a user, by default this does not include any user-identifiable data.

We're a compliance tool that tries to improve privacy, so we don't think we should be blocked by the badger :)

We allow self-hosting of the script btw, most of our customers prefer the CDN/API integration though as it gives them (anonymous) statistics and as we're able to automatically publish minor fixes and improvements without the customers / users having to manually change their script tag. In the future we will also deliver the Klaro consent configuration via this endpoint bundled with the JS code.

#### What is the "culprit" domain?

https://api.kiprotect.com

Our consent manager can be seen in action e.g. on https://kiprotect.com, the problem isn't visible there though as it's hosted on the same domain as the API.

#### What is your debug output for this domain?

There's no debug output as the request gets blocked.

**Comment by ghostwords** [comment]
Hello!

Could you provide an example or two of your consent manager in use by an external website? I'd like to see a couple of different domains where your consent manager is included as a third-party resource so I could figure out why Privacy Badger eventually learns to block it.

If you have access to a Privacy Badger that learned to block `kiprotect.com`, it would also be helpful to provide the relevant [debugging information](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain).

**Comment by ghostwords** [comment]
Let me know if you have more information.

**Comment by adewes** [comment]
I'll install Klaro on a third-party domain of ours. Please don't close this issue, it's not resolved.

**Comment by ghostwords** [comment]
Sure, it's just that I need more information first.

**Comment by adewes** [comment]
Hi @ghostwords, sorry for the delay, we now installed Klaro on an external domain that we can share here:

https://algoneer.org/

If I return control of `api.kiprotect.com` to Privacy Badger it blocks the API request to `https://api.kiprotect.com/v1/privacy-managers/afcbd2c52b98ab6c69071810dfa3c10d/config.json?name=default`. The response does not contain any `Set-Cookie` headers or other tracking measures. The API is not using Cloudflare or other intermediaries that would set cookies, and the response is just a simple JSON object.

I don't have any idea why PrivacyBadger is blocking this and would appreciate some pointers on how we can ensure the API call works, as Klaro is a core service on many websites and used to ask visitors for consent in compliance with GDPR, so we really don't think it should be blocked.

**Comment by ghostwords** [comment]
My Privacy Badger doesn't see any tracking from `kiprotect.com` on https://algoneer.org/, either before or after accepting the notice.

Could you share the [debugging information](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) for `"kiprotect"` from a Privacy Badger that learned to block it?

**Comment by adewes** [comment]
Hi @ghostwords, thanks for the reply, here's the data:

```
**** ACTION_MAP for algoneer.org
algoneer.org {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1590288944569
}
**** SNITCH_MAP for algoneer.org
algoneer.org [
  "localhost",
  "algoneer.net",
  "github.com"
]
```
Is PrivacyBadger blocking this due to the fact that it sees requests to `api.kiprotect.com` from multiple domains? I regularly visit pages where Klaro is installed for debugging and monitoring so I imagine PB could think this might be a tracking domain, but again the API call does not set any tracking information or cookies (and never has in the past). Until two months ago we were still using Cloudflare as a CDN, which set the `__cfuid` cookie on all requests, might that have to do with the blocking behavior?

**Comment by ghostwords** [comment]
This is debugging information for "algoneer". Is the problem that Privacy Badger learns to block `kiprotect.com` or `algoneer.org`?

**Comment by ghostwords** [comment]
>Is PrivacyBadger blocking this due to the fact that it sees requests to api.kiprotect.com from multiple domains?
Yes, please see https://privacybadger.org/#How-does-Privacy-Badger-work and other FAQ entries for more information.

**Comment by adewes** [comment]
Thanks for the reply, the domain that is getting blocked is `api.kiprotect.com`, from where we load the Klaro script and config via a REST API call / Ajax call.

I read the FAQ and I understand this, it's just that we don't attempt to set any third-party cookies and we surely don't using fingerprinting or other tracking techniques. Is there anything we can do to make sure we don't get affected by the heuristic matching?

**Comment by adewes** [comment]
Hi @ghostwords, sure I'll do that, please give me a day or two. Thanks for the info about the DNT policy, seems interesting!
