### ISSUE TITLE
Unable to undo creating exceptions for widget replacement

### ISSUE THREAD

**Issue by CubeTheThird** [EFForg/privacybadger#2705]
While browsing a site which was using the widget replacement for Discus, I accidentally pressed the button to Always allow Discus on this site. Unfortunately, I cannot seem to figure out how to undo this action. While I understand that this is not explicitly displayed within the settings UI, I even attempted to remove the exception from the configuration JSON file. Unless there is something I am missing, or perhaps the changes I've tried making are not formatted correctly, uploading the modified file does not seem to have any effect on this property.

If there is a way to do this that I have not tried, or other advice, it would be most appreciated.

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch!

Editing your widget replacement exceptions isn't implemented yet. Until we add a UI for this, you could edit your exceptions manually using developer tools. To do so:

1. [Open the background page console](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain#2-open-privacy-badgers-extension-background-page) for Privacy Badger.
5. Type in the following (and press <kbd>Enter</kbd>) to see your widget site exceptions:

```javascript
JSON.stringify(badger.getSettings().getItem("widgetSiteAllowlist"))
```

This returns something like:

```json
"{"example.com":["YouTube","Disqus","Facebook Video"],"example.net":["Disqus"]}"
```

6. You can then edit the output, first removing the `"` quote marks from the start and the end. You can then use it to replace your widget replacement exceptions:

```javascript
badger.getSettings().setItem("widgetSiteAllowlist", NEW_LIST_OF_EXCEPTIONS_GOES_HERE)
```

For example:

```javascript
badger.getSettings().setItem("widgetSiteAllowlist", {"example.net":["Disqus"]})
```

Here I removed all exceptions for `example.com`. Again, your new list of exceptions should begin with `{` and end with `}`, not `"` and `"`. All new Privacy Badgers have an empty list of exceptions, which is `{}`.

Let me know if you have any questions.

**Comment by CubeTheThird** [comment]
Perfect! Exactly what I needed. Thanks!
