### ISSUE TITLE
Privacy Badger fails to unblock domains with DNT policy until after reload

### ISSUE THREAD

**Issue by Hainish** [EFForg/privacybadger#2708]
Related: https://github.com/EFForg/panopticlick/issues/49

When local learning is enabled, presence of the Do Not Track policy is not checked after a domain is initially added.  In this example, no request is made to `do-not-tracker.org`:

![pb](https://user-images.githubusercontent.com/156137/97761477-0634ca80-1ac3-11eb-807e-6970292d728e.png)

After reloading the page, Privacy Badger unblocks `do-not-tracker.org` and allows the request to proceed:

![pb2](https://user-images.githubusercontent.com/156137/97761552-37ad9600-1ac3-11eb-99c8-003fa3de839f.png)

**Comment by ghostwords** [comment]
Privacy Badger [no longer checks DNT policies after first strike](https://github.com/EFForg/privacybadger/pull/2561#issue-382653293), rather only after fully learning to block the domain.

**Comment by ghostwords** [comment]
I wonder if we broke the DNT test with release 2020.5.12 that included the above PR.

**Comment by ghostwords** [comment]
If that's the case, the solution then is to either add a DNT preload list to Privacy Badger, or to update Panopticlick to retry once for the DNT test. I greatly prefer and ask that Panopticlick simply retry the test for now.

**Comment by Hainish** [comment]
I think it should be possible to ensure DNT is checked on the Panopticlick side before displaying the results.

**Comment by Hainish** [comment]
Fixed in https://github.com/EFForg/panopticlick/commit/2b2c49175cb808abef9a8c0c8c6f6c052af29814

**Comment by Hainish** [comment]
This still seems to be an issue when JavaScript is disabled, where I don't see Privacy Badger blocking any trackers.
