### ISSUE TITLE
feature request: button to open iframe URL in new tab without sending referer header

### ISSUE THREAD

**Issue by wis** [EFForg/privacybadger#2710]
![iframe](https://user-images.githubusercontent.com/9993663/97801553-41133b80-1c46-11eb-90b0-6adf3a2da9db.png)
Right now the only option is to allow the iframe to load and send the refering URL/site to the tracker, there should be an option to open the iframe's URL in new tab without sending a referer header, the button's anchor tag should be `<a href="<iframes_URL>" rel="noreferrer" target="_blank">` in order to open in new tab and not to send referer header.

**Comment by ghostwords** [comment]
Hello and thanks for the suggestion! Is this the same idea as #2384? If it is, please :+1: that issue.

**Comment by ghostwords** [comment]
Thanks again!
