### ISSUE TITLE
Ublock Origin/Privacy Badger combo returns a 1004 error when accessing the echo test on bigbluebutton (BBB)

### ISSUE THREAD

**Issue by lelibreauquotidien** [EFForg/privacybadger#2711]
Hello.
The Ublock Origin/Privacy Badger combo returns a 1004 error when accessing the echo test on bigbluebutton (BBB).
I'm sure it's the fault of these 2 extensions, all my other extensions were disabled.
Deactivating one but leaving the other activated doesn't change anything.
I would like to specify that disabling tracing in the extensions menu is not enough, you have to disable the extension to have an effect.
My OS is Manjaro Linux and my browser is Firefox 82.0.2.
Also published on [BigBlueButton Repo](https://github.com/bigbluebutton/bigbluebutton/issues/10777) and [Ublock Origin Repo](https://github.com/uBlockOrigin/uBlock-issues/issues/1327)

**Comment by ghostwords** [comment]
Hello! Which version of Privacy Badger do you have? Have you enabled "Prevent WebRTC from leaking local IP address" in Privacy Badger's options?

**Comment by lelibreauquotidien** [comment]
> Which version of Privacy Badger do you have? 
2020.10.7
> Have you enabled "Prevent WebRTC from leaking local IP address" in Privacy Badger's options?
Yes

**Comment by ghostwords** [comment]
Well, I think we found the issue. Unfortunately, as you noticed, disabling Privacy Badger on the site doesn't help, as this switch controls a browser-wide setting.

**Comment by ghostwords** [comment]
Enabling this setting can and does break (video conferencing) websites, which is why this setting is disabled by default and lives in the Advanced section.

**Comment by lelibreauquotidien** [comment]
I disabled this option, it's work !
There is an equivalent option in ublock origin.
I also had to disable it for it to work.
