### ISSUE TITLE
GPC not set in chrome

### ISSUE THREAD

**Issue by shaitand** [EFForg/privacybadger#2717]
![image](https://user-images.githubusercontent.com/8183779/99690561-23631600-2a3d-11eb-9950-1dd5ef2e4b05.png)

Google Chrome is up to date
Version 87.0.4280.66 (Official Build) (64-bit)

**Comment by ghostwords** [comment]
Hello!

Is sending DNT/GPC signals enabled in Privacy Badger's options?

What do you see when you visit https://global-privacy-control.glitch.me/?

Previously: #2695

**Comment by ghostwords** [comment]
Let me know if you have more information.

**Comment by shaitand** [comment]
It is enabled and the page you indicated times out.

**Comment by ghostwords** [comment]
What other extensions do you have installed?

Can you reproduce the problem if you (temporarily) disable your other extensions and reload the test pages?

**Comment by shaitand** [comment]
> Which other extensions do you have installed?
> 
> Can you reproduce the problem if you (temporarily) disable your other extensions and reload the test pages?

This was an extension issue. The conflict was with DuckDuckGo Privacy Essentials 2020.10.21, disabling resolves and so does enabling GPC in both apps.

Thank you!

**Comment by ghostwords** [comment]
Thanks for letting us know!
