### ISSUE TITLE
On Firefox, getting "Privacy Badger failed to set navigator.globalPrivacyControl, probably because another extension set it in an incompatible way first."

### ISSUE THREAD

**Issue by KoenDG** [EFForg/privacybadger#2725]
As the title/error message says, "probably another extension".

I do have over 20 extensions, so this is perfectly possible.

That being said, the error comes from this place: https://github.com/EFForg/privacybadger/blob/master/src/js/contentscripts/dnt.js#L39

So, I've made both the following booleans:

 * navigator.globalPrivacyControl
 * window.navigator.globalPrivacyControl

Yet the error keeps coming back. From the code flow I assumed creating the variable would no longer go to the error.

I only noticed this recently, this could have been going on for a while now. It's been a good amount of time since I last installed an addon.

Is there's a particular way I can investigate this? Or is something more general wrong that I can't do anything about?

Finally, with the situation being what it is: does this impact the working of the addon?

**Comment by ghostwords** [comment]
Hello!

This error is just what it says: Privacy Badger is unable to set the [Global Privacy Control](https://globalprivacycontrol.org/) signal in JavaScript. The rest of Privacy Badger is fine.

To find the problem extension, review the [list of privacy tools that support GPC](https://globalprivacycontrol.org/#download). If the conflict is with Duck Duck Go, it should be fixed [in the next update of their extension](https://github.com/EFForg/privacybadger/pull/2722#issuecomment-748352852).

Once you find the responsible extension, you can manually resolve the conflict by enabling Global Privacy Control in that extension's settings.

Let me know if you have any questions.

Previously: #2717

**Comment by KoenDG** [comment]
Aha, I'm going to assume it's DuckDuckGo then. I'll wait and see for the first week of January to pass.
