### ISSUE TITLE
privacy badger breaks extension 'shinigami eyes'

### ISSUE THREAD

**Issue by hollowsbest** [EFForg/privacybadger#2726]
shinigami eyes highlights trans-friendly, and anti-trans links when browsing the web, and after installing privacy badger the icon is now greyed out and doesn't function
https://shinigami-eyes.github.io - link to the extension page

using privacy badger on opera, and shinigami eyes through the 'install chrome extensions' extension

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch! I am not sure how to reproduce this conflict exactly. The icon always looks sort of gray and clicking it doesn't do anything except open Chrome's built-in default extension menu (the one that comes up on right-click for Privacy Badger).

Could you provide the exact steps for reproducing this problem? For example:

1. Install Shinigami Eyes
2. Visit example.com
3. Verify that such and such is true
4. Install Privacy Badger
5. Reload example.com
6. Verify such and such is no longer true

**Comment by ghostwords** [comment]
Let me know if you have more information.
