### ISSUE TITLE
Privacy Badgers local learning not working

### ISSUE THREAD

**Issue by Andreas-Mag** [EFForg/privacybadger#2736]
When reactivating the local learning modus of Privacy Badger, it didn't learn anything.

When browsing the web with activeted "local learning modus" it seems, that PB didn't learn anything. So I tested by using the following setup:

- Firefox 84.0.2 (desktop and mobil)
- Activate the "local learning checkbox" in settings
- "Remove all tracking domains" in settings/manage data
- Browsing some websites with known trackers (for example google-analytics), so that more then 3 sites with the trackers should be in history

After a while I checked Privacy Badger settings again:
- When showing the settings/tracking-domains, there was no trackers listed
- When using settings/manage data -> export user data: in the *.json file no data is collected. "action_map" and "snitch_map" is empty!

So my conclusion is, that the "local learning modus" of Privacy Badger is still not working, also wenn it is activated!

**Comment by ghostwords** [comment]
Hello! It sounds like your other blockers may be interfering with Privacy Badger's ability to learn. What are other content blocking extensions do you have installed? Is [Firefox's Tracking Protection](https://privacybadger.org/#Is-Privacy-Badger-compatible-with-Firefox%27s-built-in-content-blocking) enabled? Do you have a DNS blocker or any other blocking tools?

**Comment by ghostwords** [comment]
I just launched Firefox 84 into a new profile, installed Privacy Badger, removed all tracking domains, enabled local learning, and visited `cnn.com`, `nytimes.com`, `foxnews.com` and `wsj.com`. My Privacy Badger learned to block various `demdex.net`, `doubleclick.net` and `google.com` domains, despite Tracking Protection being enabled (I left all Firefox settings at defaults).

**Comment by ghostwords** [comment]
Google Analytics is discovered using pixel cooking sharing detection, which [we've had to remove from local learning for now](https://www.eff.org/deeplinks/2020/10/privacy-badger-changing-protect-you-better):

>Because of the way Privacy Badger checked first-party cookie strings against outgoing third-party request URLs, it would have been possible in certain circumstances for an attacker to extract first-party cookie values by issuing thousands of consecutive requests to a set of attacker-controlled third-party domains. We immediately removed the first-to-third-party cookie heuristic from Privacy Badger’s local learning in order to patch the vulnerability. (We have continued using that heuristic for pre-training in Badger Sett, where it does not expose any sensitive information.)

We plan to replace pixel cookie sharing detection with a similar but safe-for-local learning heuristic in the future.

**Comment by ghostwords** [comment]
Let me know if you have any questions.

**Comment by Andreas-Mag** [comment]
Thanks for your help ghostwords.

I tested again with new profiles and the heuristic works.
So my first post was a fail, sorry.

Searching the reason for my mistake bring up the follow:
Using the Addon "uBlock Origin" from Raymond Hills with strict settings and all privacy, add and annoyances list blocks the most of the trackers, so Privacy Badger couldn't see them. When setting the Firefox settings for security to user defined and block there third party cookies, fingerprinters and so on, then Privacy Badger see no trackers on the four example sites from your test above.

**Comment by ghostwords** [comment]
All good, thanks for confirming!

Related FAQ entries:
- https://privacybadger.org/#Is-Privacy-Badger-compatible-with-other-extensions%2c-including-other-adblockers
- https://privacybadger.org/#Is-Privacy-Badger-compatible-with-Firefox%27s-built-in-content-blocking
- https://privacybadger.org/#Does-Privacy-Badger-still-work-when-blocking-third-party-cookies-in-the-browser
