### ISSUE TITLE
Revert control arrows are not themed appropriately for dark mode

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [EFForg/privacybadger#2738]
I just discovered the darkmode and I find it really nice! But enabling the dark mode also brought me the little bug, that the revert arrows, are still displayed in a dark font color at dark mode. I clipped you a picture about this to the issue. 

Browser: Firefox on MacOS

## preview
![Bildschirmfoto 2021-02-03 um 12 45 16](https://user-images.githubusercontent.com/47633893/106742720-aef04a00-661d-11eb-9c3a-da34450fe552.png)

**Comment by ghostwords** [comment]
Hello! Glad you like it, and thanks for bringing this bug to our attention!

**Comment by KashyapPavra** [comment]
@ghostwords If the issue is unassigned, I would love to help out.

**Comment by ghostwords** [comment]
@KashyapPavra Sounds good!

**Comment by KashyapPavra** [comment]
@ghostwords Great, can you assign me this issue?
