### ISSUE TITLE
CBS All Access (soon to be Paramount+) videos fail to load ad and breaks video

### ISSUE THREAD

**Issue by colinje** [EFForg/privacybadger#2747]
#### What is your browser and browser version?

Firefox 86

#### What is broken and where?

Video on `www.cbs.com` fails because `adservice.google.com` needs to be yellow-listed

**Comment by colinje** [comment]
Now with the launch of Paramount+, it appears video playback is completely broken by anything blocking doubleclick. womp womp. I played around with a bunch of different things like Ghostery, uBlock Origin, DDG, Brave and FF built in blocking, and nothing seems to work.

Should I just close this, saying allowing tracking is the only way currently to circumvent the broken site?

**Comment by ghostwords** [comment]
Hi, thanks for getting in touch!

It would be good for Privacy Badger to do something about this, just not sure what yet.

This seems related to #1596.

**Comment by colinje** [comment]
After some more experimenting, I found DDG's extension allows the video to play, but blocks the ads. I can see in the network traffic that some known trackers are being let through. Maybe I can step through DDG extension to see how these domains are being filtered and why. (Could they be anonymizing/randomizing the request being sent to the tracker?) I think depending on the strategy used there, PB could adopt

**Comment by ghostwords** [comment]
>I think depending on the strategy used there, PB could adopt

Sounds good!
