### ISSUE TITLE
Obsolete Copyright notice?

### ISSUE THREAD

**Issue by Mtillmann** [EFForg/privacybadger#2749]
I randomly stumbled upon this notice and was very confused because It suggests that PB is somehow related to that company

https://github.com/EFForg/privacybadger/blob/6a0a948a79c06a04ad49e0de2e3a7b299105a5db/src/skin/options.html#L4

**Comment by ghostwords** [comment]
Hello! Privacy Badger was originally built on top of Adblock Plus, as a bootstrap to speed development. Then most of ABP code was removed (when the main request processing engine got rewritten) in 2016. Parts of Privacy Badger like the options page were never replaced, rather gradually evolved. I'll update these file headers to clarify status.
