### ISSUE TITLE
an unexpected error

### ISSUE THREAD

**Issue by Pancakes0** [EFForg/privacybadger#2750]
so i downloaded an extension called youtube audio and when i was reading i saw this 
![Screen Shot 2021-03-15 at 7 59 44 PM](https://user-images.githubusercontent.com/73923883/111150724-6ab37a80-85c9-11eb-8cae-716daa6db807.png)
i dont know if it did this before i downloaded because i just noticed it after so i dont know if it has anything to do with it. 
 macos mojave 10.14.6 
 firefox 86.0 ( just saw i need to restart firefox when i checked ver. dunno if that has anything to do with this)

**Comment by Pancakes0** [comment]
okay i just restarted and its fixed somehow 
![Screen Shot 2021-03-15 at 8 25 10 PM](https://user-images.githubusercontent.com/73923883/111153204-9edc6a80-85cc-11eb-9e83-b0d181221c35.png)
tnx

**Comment by ghostwords** [comment]
Hi and thanks for getting in touch! Is your disk low on space by any chance?
