### ISSUE TITLE
AdGuard Extra fails to hide ads on Facebook if Privacy Badger is enabled

### ISSUE THREAD

**Issue by jbionic2016** [EFForg/privacybadger#2751]
Hi there,

This is a user from Russia. Just letting you know that we've identified an abnormal behavior of PrivacyBadger while opening Facebook feeds from Facebook Messenger page on a Windows 10 computer in Chrome browser.

This issue has been discussed in below correspondence with Adguard in Russian language 
https://github.com/AdguardTeam/AdGuardExtra/issues/171

In short, if a user is switching from Facebook Messenger screen (by clicking the Home button as shown on attached picture) to the main Facebook page, then provided that PrivacyBadger is enabled,  Ads start penetrating the screen (as shown on the second screen on the right side):

![679217f54c3ab558937db8f43597f19a](https://user-images.githubusercontent.com/794578/111672643-88165d80-87f0-11eb-9249-26f2377758b5.jpg)

![8494537cf5b7b758f5435bb9df9febf4](https://user-images.githubusercontent.com/794578/111672646-8a78b780-87f0-11eb-924e-116b2bd2fc75.jpg)

We've confirmed this strange behaviour by disabling all other extensions one by one.

Your comments and recommendations will be very appreciated.

#### What is your browser and browser version?
Browser: Chrome Version 89.0.4389.90 (Official Build) (64-bit) for Windows 10 Home computer

**Comment by ghostwords** [comment]
Hello and thanks for the report!

Just to be clear, is the problem that AdGuard Extra's ad blocking/hiding on Facebook doesn't work when you click on the Home button on Facebook but only when Privacy Badger is installed?

Are you able to reproduce this problem in a new browser profile?

Does the issue go away when Privacy Badger is disabled on Facebook? To disable Privacy Badger on Facebook while keeping it enabled elsewhere, click on the "Disable Privacy Badger for this site" button in Privacy Badger's popup while on Facebook.

**Comment by ghostwords** [comment]
Also, can you reproduce this problem in a new browser profile with AdGuard Extra and [Facebook™ Tracking & Ad Removal](https://github.com/mgziminsky/FacebookTrackingRemoval)?

**Comment by jbionic2016** [comment]
<< Does the issue go away when Privacy Badger is disabled on Facebook? >>

It does. I am 100% certain. I have even disabled Privacy Badger as result.
Adguard Extra doesn't affect the result, which means that when Privacy Badger is enabled, then Ads will penetrate anyway no matter if Adguard Extra is enabled or not.

**Comment by jbionic2016** [comment]
> Also, can you reproduce this problem in a new browser profile with AdGuard Extra and [Facebook™ Tracking & Ad Removal](https://github.com/mgziminsky/FacebookTrackingRemoval) (no other extensions)?

Sorry. I dont want to install another doubtful extension just because its author swears on the Bible that he won't  collect or send any data to myself or any third parties...

**Comment by ghostwords** [comment]
>It does. I am 100% certain. I have even disabled Privacy Badger as result.

There shouldn't be any need to disable Privacy Badger globally for the whole browser. You can disable Privacy Badger just on Facebook while keeping Privacy Badger enabled and protecting you elsewhere by clicking on the "Disable Privacy Badger for this site" button in Privacy Badger's popup while on Facebook.

**Comment by ghostwords** [comment]
I think this is a conflict between Privacy Badger's [link tracking protection on Facebook](https://www.eff.org/deeplinks/2018/05/privacy-badger-rolls-out-new-ways-fight-facebook-tracking) ([source code](https://github.com/EFForg/privacybadger/blob/70b161cfcd5f5d981cf07333eed558f95463e230/src/js/firstparties/facebook.js)) and AdGuard Extra.

Privacy Badger looks for outbound tracking links on Facebook and removes tracking attributes. AdGuard Extra looks for ad containers and hides the ads. It's possible that Privacy Badger sometimes removes tracking attributes from ads before AdGuard Extra, and then AdGuard Extra ends up missing those ads because the attributes AdGuard Extra looks for are no longer present. I haven't yet been able to reproduce this, however.

I recommend to disable Privacy Badger on Facebook so that AdGuard Extra can successfully hide ads there.

**Comment by jbionic2016** [comment]
Understood. Thanks.

**Comment by Denise611** [comment]
- [ ]

**Comment by Denise611** [comment]
- [ ]
