### ISSUE TITLE
Add Transifex Support to Translation Guide

### ISSUE THREAD

**Issue by urbalazs** [EFForg/privacybadger#2753]
Transifex support is missing from the [Translation Guide](https://github.com/EFForg/privacybadger/blob/master/doc/Translation.md). Please consider to add this information.

**Comment by ghostwords** [comment]
Thanks for the suggestion! Let me know if you have any thoughts about the [updated document](https://github.com/EFForg/privacybadger/blob/master/doc/Translation.md#translating-privacy-badger).
