### ISSUE TITLE
Tengo instalado Privacy Badger y de pronto el ícono quedó en gris y no funciona

### ISSUE THREAD

**Issue by Daniel8522** [EFForg/privacybadger#2754]
Estaba usando Privacy Badger normal y funcionaba muy bien, bloqueaba perfectamente a google youtube y otros, el ícono tenía color y ahora está en gris, sin bloquear nada. El navegador es Yandex Browser. 
Lo eliminé y reinstalé pero no hay cambio. Tienen alguna sugerencia? Gracias
Daniel
PD.: esto es lo único que se ve al hacer click en el ícono
Privacy Badger
Deshabilitar Privacy Badger en este sitio
¿Ha roto Privacy Badger este sitio? ¡Háganoslo saber!
 Donar a la EFF

**Comment by ghostwords** [comment]
Hello!

Which version of Yandex Browser do you have?

If you open Privacy Badger's background page console, what error messages do you see? [Here are the instructions for opening Privacy Badger's background page console in Chrome](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain#2-open-privacy-badgers-extension-background-page). I don't know how to open Privacy Badger's background page in Yandex Browser, but the process may be similar to Chrome.

**Comment by Daniel8522** [comment]
Hola tengo Yandex Browser (beta) y esta con actualización automática. En Extensiones no aparece modo desarrollador. 
Ayer ingresé a propiedades de Yandex y desactive el uso para otros, hoy está nuevamente habilitado. Lo mismo pasa con Privacy que en las extensiones lo habilite para usar de incognito y otra opción que tiene y hoy estan deshabilitados.
Creo que google esta interfiriendo porque hace tiempo que bloquea accesos a páginas, youtube, aparecen páginas ampliadas que hacen imposible leerlas.
Gracias por las ayudas.
Daniel
-- 
 Enviado con Tutanota, el correo seguro y sin publicidad: 
 https://tutanota.com


23 de mar. de 2021 15:13 por ***@***.***:

**Comment by ghostwords** [comment]
Could you post a screenshot of your [Yandex Browser's extension management page](https://yandex.com/support/browser-beta/personalization/extension.html#what)?

**Comment by Daniel8522** [comment]
-- 
 Enviado con Tutanota, el correo seguro y sin publicidad: 
 https://tutanota.com


24 de mar. de 2021 13:42 por ***@***.***:

**Comment by ghostwords** [comment]
If you trying to post a screenshot, you may have to visit this issue in a browser and drag and drop the screenshot into a new comment as it doesn't seem that posting an image through email is working.

**Comment by ghostwords** [comment]
Let me know if you have more information. Closing for now.

**Comment by Daniel8522** [comment]
Alexei, muchas gracias, ya funciona normal. Problema resuelto, muy agradecido.
Daniel-- 
 Enviado con Tutanota, el correo seguro y sin publicidad: 
 https://tutanota.com


29 de mar. de 2021 14:18 por ***@***.***:
