### ISSUE TITLE
I'm a screen-reader user and I can't read the tracker management radio buttons in Chrome.

### ISSUE THREAD

**Issue by Simon818** [EFForg/privacybadger#2764]
I'm using [NVDA](https://nvda-project.org) with Chrome-dev on Windows. When clicking on the extension on a page that has blocked trackers, I'm given a set of 3 radio buttons for each tracker. it's apparent that these change what Privacy Badger does when encountering their respective tracker, but there is no text label on them and not even a text label above the list of domains that would give me a clue as to what the options are, or which option is which. I haven't asked someone to look this over and am not sure how to examine the HTML code of an extension, so I have no idea why this isn't reading, unfortunately. The only thing my screen-reader knows about these controls is that they are radio buttons that are either checked or not checked.

**Comment by ablanathtanalba** [comment]
Thanks for bringing this to our attention! This is definitely an issue I'd like to address sooner rather than later. I'm happy to start working on it, as similar concerns were recently raised in issue #2748. I'm sure there are several ways we could make Privacy Badger more accessible for screen readers and similar technologies.

**Comment by Simon818** [comment]
So far, that's the biggest concern i've found. Those controls are even keyboard-accessible; I just have no idea what they are. Are they colour-coded or something?

Wow, nice discussion on accessibility in #2748. I always appreciate that kind of concern being brought up. Unfortunately making a generic element like a <div> or a <span> accessible is not a one-step process; I wish we were at a point where we could just stop using them and make everything a <button> or whatever control type most suits it.

**Comment by ablanathtanalba** [comment]
Yes, the controls you are encountering are actually meant to configure how Privacy Badger decides to block, soft block, or allow individual trackers on a webpage, and they are color coded to signify each. However, we actually don't advise using those controls, and the pull request we previously mentioned above (#2748) is working to hide them under a collapsible menu by default. As much as possible we aim for Privacy Badger to be an "install and forget" kind of tool that you shouldn't have to interact with much for it to do its work.

All that said, you've raised an important concern here and it would be a great improvement to Privacy Badger for us to incorporate a solution. I'll reference this issue in an upcoming pull request to fix it. Thanks!

**Comment by Simon818** [comment]
It was actually an instal-and-forget tool for a really long time, just FYI. The main thing that changed this for me was [HCaptcha](https://hcaptcha.com), which lets you bypass visual captchas by adding a cookie from their site. Visual captchas are a tiny bit impossible when I'm using a computer program to interpret screen output, so I have to do this. Their cookie counts as a third-party tracker, so Privacy Badger blocks it. This led me to discover the buttons and their missing labels. Is there a better, more permanent fix than just allowing HCaptcha.com? Or is this one of those edge cases where I *should* be using that interface?

**Comment by ablanathtanalba** [comment]
That's good to know about the difficulties you're facing with HCaptcha; I can open a separate issue to keep track of fixing that for all users that might be using HCaptcha with Privacy Badger. It's a sort of graceless solution in the meantime, but you could temporarily turn Privacy Badger off on a website where you're facing difficulties bypassing a captcha with HCaptcha. At the bottom of the popup there is a button labeled "Disable Privacy Badger for this site" which is keyboard accessible. Select that and it will refresh the page with Privacy Badger turned off for this site entirely. It's only turned off for that site and will stay that way until you press the same button to re-enable it.

**Comment by Simon818** [comment]
That's probably good enough since most captchas are sign-up only. I think figuring out the keyboard order of the radio buttons would also work though.

If you think it's worth opening an issue about that specific site, go for it. That would be a great problem to just not have anymore. They are working on a better, more private solution, but I have no idea when that will actually be available.

**Comment by ghostwords** [comment]
Hi @Simon818! We are working on labeling the radio buttons in #2772.

I have a question: Do we need to have the domain as part of each button's label? Meaning, is it enough for the label to say "Click here to block this domain from setting cookies" (because you already know this radio button is for `example.com` given information provided elsewhere)? Or does the label need to say, "Click here to block example.com from setting cookies"?

**Comment by Simon818** [comment]
Hi,

Thanks for asking! Right now the domain name shows up as a static piece of text above the radio buttons. If that could be a level 3 heading so that it falls below the main Privacy Badger heading, it would be easy to use the next/previous heading commands to move through the various cookie domains and then continue to the radio buttons below them. But regardless, I think that having the domains as part of the label would be overly verbose. Even having "click here" labels is overly verbose. We don't visually label buttons with instructions like that because you can visually see that it's a button you can click. Similarly, screen-readers read the control type (radio button) and whether it is "checked" or "not checked", so users already know how to use the control; we just need to know what it does. 

* Allow Cookies
* Block cookies

**Comment by ablanathtanalba** [comment]
Thanks again for raising this issue, @Simon818 . Since this main issue is closed (and now rolled out in the most recent release of Privacy Badger), I opened a following issue to keep track of the problem with HCaptcha.

**Comment by Simon818** [comment]
@ablanathtanalba Thanks, subscribed. Since it isn't immediately obvious to a non-technical user that Privacy Badger is the problem here, a fix could be nice. I appreciate yours and everyone's work on both of these.
