### ISSUE TITLE
Can't share on Facebook

### ISSUE THREAD

**Issue by CapnBlaze** [EFForg/privacybadger#2777]
#### What is your browser and browser version?

Chrome 91.0.4472.106

#### What is broken and where?

Facebook. When I try to share it won't load the sharing buttons. It just appears as a blank grey area or there is a loading circle that never goes away

![Screenshot_2](https://user-images.githubusercontent.com/41491976/122622950-5d92a580-d068-11eb-86d3-945a87556ced.png)
![Screenshot_3](https://user-images.githubusercontent.com/41491976/122622951-5e2b3c00-d068-11eb-8bfa-8aad1faa1b03.png)
![Screenshot_4](https://user-images.githubusercontent.com/41491976/122622952-5e2b3c00-d068-11eb-9958-1fb850ec0ec7.png)

**Comment by ghostwords** [comment]
Hello!

Where on Facebook does this happen exactly? You could post a screenshot if it helps.

Is the bug absent if you disable all browser extensions and reload Facebook?

Does the bug come back if you re-enable Privacy Badger alone and reload Facebook?

**Comment by CapnBlaze** [comment]
At first I thought it was a Facebook issue. But it went away as soon as I
disabled privacy badger.

**Comment by CapnBlaze** [comment]
I apologize for the double reply, but I hit send too soon. The answer to
your other questions are, I did not disable all other extensions, just
privacy badger. The problem disappears when it is disabled and reappears
when it is re-enabled. And yes, I must refresh the page.

And thank you for the quick response! I actually wasn't expecting any
response.

**Comment by ghostwords** [comment]
I see. Just a note, you could use the "Disable Privacy Badger for this site" button in Privacy Badger's popup while on Facebook to disable Privacy Badger just on Facebook, while keeping it enabled and protecting you elsewhere.

Does this bug happen to all share buttons on Facebook? Could you post a screenshot of what it looks like?

**Comment by CapnBlaze** [comment]
I didn't see a pop-up anywhere for Privacy Badger but can look into it. And
I would prefer not to disable it entirely for Facebook in any case because
FB tracks a lot of stuff which I am sure you are aware of. Last, I did send
you screenshots in the email before last but will include them again in
this one.

**Comment by ghostwords** [comment]
It doesn't look like you can send screenshots as attachments via email to post them on GitHub. You can visit [this issue](https://github.com/EFForg/privacybadger/issues/2777) and post them directly via GitHub's Web UI though.

To open Privacy Badger's popup, click on Privacy Badger's button in your browser toolbar.

**Comment by CapnBlaze** [comment]
Update. It looks like PB is not the culprit. At least not directly.
Something else is going on because I am now getting the issue
intermittently  :/

I will upload the screenshots there anyways just in case they prove useful
somehow.

In regards to the pop up - I don't see PB listed there.

[image: image.png]

**Comment by ghostwords** [comment]
Your Privacy Badger toolbar icon may be hidden inside Chrome's "puzzle piece" extensions menu. [Here is an article](http://help.sendspark.com/en/articles/4292727-how-to-pin-google-chrome-extensions) that describes with screenshots how to reveal hidden extension icons in Chrome.

**Comment by ghostwords** [comment]
Let me know if I can help with anything else.
