### ISSUE TITLE
Block email send to GMAIL with Thunderbird 

### ISSUE THREAD

**Issue by Garfieldfr59** [EFForg/privacybadger#2789]
#### What is your browser and browser version?
Privacy Badger is installed on Firefox 90.0.2
Thunderbird 78.12.0 (Windows 64bits) - the mailer from Mozilla

#### What is broken and where?
Send email with Thunderbird to an adress in @gmail is blocked. Sometimes the email arrived after more than an hour, sometimes it doesn't arrive at all.
To another domain, email arrived after 2/3 minutes (normal)

I desactivate PB in Firefox and send email with Thunderbird : it's work
I add *.orange.fr in domaines I don't want to block and send email with Thunderbird, it work. (Orange is my ISP - France )

Is the interaction between Firefox and Thunderbird normal ?

**Comment by ghostwords** [comment]
Hello! I'm not sure Privacy Badger has anything to do with this problem. Privacy Badger is a standard browser extension. Browser extensions do not have the power to change anything outside of the browser they are installed in. Firefox and Thunderbird are separate programs; Privacy Badger installed in Firefox should have no effect in any way on Thunderbird.

**Comment by ghostwords** [comment]
Let me know if you have any more information.
