### ISSUE TITLE
Where is the Chromium version of privacybadger?

### ISSUE THREAD

**Issue by Ryu945** [EFForg/privacybadger#2800]
Where is the Chromium version of privacybadger?

**Comment by ghostwords** [comment]
Hello! Does https://privacybadger.org/#Can-I-download-Privacy-Badger-directly-from-eff.org answer your question?

**Comment by Ryu945** [comment]
> Hello! Does https://privacybadger.org/#Can-I-download-Privacy-Badger-directly-from-eff.org answer your question?

Thankyou, that worked.
