### ISSUE TITLE
"An unexpected error occurred"

### ISSUE THREAD

**Issue by schet** [EFForg/privacybadger#2804]
Stopped working and I first noticed it when I was on 1337x. It prompts me to "tell us" about "An unexpected error occurred" and says "No trackers blocked", once dismissed, even though I've had it for ages. My other addons are: PrivacyBadger, UBlock Origin, Decentraleyes, LASER CAT, KeepassXC-Browser and I don't care about cookies. I'm using Mozilla Firefox 92.0.1 on Artix Linux and PrivacyBadger version 2021.8.17.

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch!

So "An unexpected error occurred" seems to happen when extensions try saving something to extension storage. Saving doesn't work for some reason, and the extension receives this error. Most likely all your extensions have this problem; it's just that only Privacy Badger lets you know about it.

Things to try to fix this problem:
1.Is your disk low on space? Firefox stops letting extensions update storage at some low free space threshold. To fix, you have to first free up some storage and then restart Firefox.
2. If your disk isn't low, restarting Firefox could still help. Try restarting and browsing around a bit. Does the error come up?
3. If the error comes back, you might have to [refresh your Firefox profile](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings). This means you'll have to reinstall all your extensions.

Let me know how it goes please.

**Comment by schet** [comment]
I restarted the system and the error's disappeared. Thank you so much for your help :)

**Comment by ghostwords** [comment]
You're welcome!

**Comment by FoxGamingYTCR** [comment]
I had the same problem and I had to restart my computer, still unsure what caused the problem in the first place but I guess it doesn't matter now.
