### ISSUE TITLE
Private Badger donate message

### ISSUE THREAD

**Issue by AV115** [EFForg/privacybadger#2817]
We are a primary primary education school. We have (Google Chromebooks) installed the PrivacyBadger. Only now the children get the "Donate" webpage every time they log in. For privacy reasons, the chromebooks must be set to "reset after logout". Is there a way to block the DonateAdd?

Thank,
Teacher Primary school in the Netherlands

**Comment by ghostwords** [comment]
Hello!

You can indeed disable showing Privacy Badger's new user welcome page via enterprise policies. For more information, see our [enterprise deployment and configuration document](https://github.com/EFForg/privacybadger/blob/master/doc/admin-deployment.md).

Let me know if you have any questions.
