### ISSUE TITLE
How to Install Privacy Badger

### ISSUE THREAD

**Issue by wbak1102** [EFForg/privacybadger#2820]
How to Install Privacy Badger 2021.11.23.1.
it does not go ? -Make to installake

**Comment by ghostwords** [comment]
To install Privacy Badger, visit https://privacybadger.org/ and click on the big orange INSTALL button. This will begin installation, or take you to the right page to begin installation of the latest available version of Privacy Badger for your browser.

Privacy Badger version 2021.11.23.1 has been submitted to all stores, but has not yet been approved everywhere. This part is mostly out of our hands. We all just have to wait for approval to happen.

Your copy of Privacy Badger should get automatically updated to the latest version soon after the new version gets approved and published.

Let me know if you have any other questions.
