### ISSUE TITLE
Remove "spm/scm/pvid" tracking parameter in *.taobao.com,*.tmall.com,*.aliexpress.com,*.1688.com

### ISSUE THREAD

**Issue by zhoujian-official** [EFForg/privacybadger#2827]
The "spm/scm/pvid" parameter used widely by Alibaba Inc.(including *.taobao.com,*.tmall.com,*.aliexpress.com,*.1688.com and more) is a tracking parameter. 

For example: `https://item.taobao.com/item.htm?spm=a21bo.jianhua.201876.2.5af911d9iQAwPx&id=665627275775&scm=1007.34127.211940.0&pvid=38a55e6a-8c87-463d-9ae3-42d0f1a9a72d`

The actually valid url is just `https://item.taobao.com/item.htm?id=665627275775`

Currently PrivacyBadger didn't remove those tracking parameters. Thanks!

**Comment by zhoujian365** [comment]
I think [ClearUrls](https://gitlab.com/KevinRoebert/ClearUrls) or [NeatUrl](https://github.com/Smile4ever/Neat-URL) can do this, but they also try to remove tracking in some way which PrivacyBadger also do, and that might cause conflict. Thanks for reply!
