### ISSUE TITLE
Getting a blocklist based on the browser's extension data for dnsmasq

### ISSUE THREAD

**Issue by CherMet90** [EFForg/privacybadger#2828]
I’d like to make a **blocklist** based on the Privacy Badger’s data for my **dnsmasq**. But I couldn’t understand the logic of json exported from the browser extension. There are domain names with some keys: _dnt_, _heuristicAction_, _nextUpdateTime_ and _userAction_. I thought to use all domains with value _block_ for key _heuristicAction_, but I saw that there are domains such as _yandex.ru_ that I mustn’t block of course. And I’m sure the extension doesn't block this domain because it’s available and I can open the _yandex.ru_ webpage.

And furthermore, I see that some domains in the json file haven’t got the _dnt_ key. How do they differ from each other?

Thanks.

**Comment by ghostwords** [comment]
Hello and welcome!

See our [design document](https://github.com/EFForg/privacybadger/blob/master/doc/DESIGN-AND-ROADMAP.md#data-structures) for explanation of Privacy Badger data formats.

As for converting Privacy Badger findings to domain block lists, please see [my previous reply](https://github.com/EFForg/privacybadger/discussions/2786#discussioncomment-1021999) to a similar request.

Let me know if you have any followup questions.
