### ISSUE TITLE
CNN Site Constantly Refreshes

### ISSUE THREAD

**Issue by gwilliams99** [EFForg/privacybadger#2836]
Version 100.0.4896.88 (Official Build) (64-bit)

CNN.com is constantly refershing. Sometimes on the entry page, it works correctly, and the problem starts when I click on a page link. Sometimes the constant refresh occurs on the main cnn page. 
CNN.com
I also have these extensions installed:
AutoplayStopper
1.9.5
Grammarly for Chrome
14.1056.0
Hello, Goodbye
1.5.13
Privacy Badger
2021.11.23.1
uBlock Origin
1.42.4

The problem goes away if I disable Privacy Badger. The site works correctly wothout Privacy Badger

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch! I haven't yet been able to reproduce the reloading. Are you able to reproduce if you [launch Chrome in a new profile](https://www.chromium.org/developers/creating-and-using-profiles/) and install Privacy Badger there?

**Comment by gwilliams99** [comment]
Thank you ghostwords. The strange thing is, after enduring this problem for a couple of weeks, the problem mysteriously disappeared after you said you could not reproduce it.
I didn't do anything to fix the problem. I simply enabled Privacy Badger and tested CNN. Out of an abundance of caution, I tested links on CNN and also rebooted the computer to make sure the problem didn't come back.
When the problem was previously going on, I had tried to disable/ enable/ restart the computer multiple times to no avail.

Thank you for looking into this issue.

**Comment by gwilliams99** [comment]
I have found something that has changed on my system that may have fixed the issue.
Chrome has auto-updated to this version:

Chrome is up to date
Version 100.0.4896.127 (Official Build) (64-bit)

**Comment by ghostwords** [comment]
You're welcome! Let me know if the problem comes back.

By the way, whenever you suspect Privacy Badger might be breaking a site, you can always disable Privacy Badger on that site alone, while leaving Privacy Badger enabled and protecting you everywhere else. To do so, click on Privacy Badger's icon in your browser toolbar and then click on the "Disable for this site" button. Let me know if you have any questions.

**Comment by tjanke42** [comment]
I'm experiencing exactly this same issue.  CNN main page is stable, but article pages constantly refresh, about once every two seconds or so.

Disabling PB for the site does indeed cure this behavior, and it remains so.

Disabling and re-enabling PB in the chrome extensions page also stops the behavior, but only for a time.  NOTE that it is the re-enabling that stops the refreshing; disabling thru the extensions page does not stop the refreshing, but subsequently re-enabling does.  But with this method the behavior eventually returns.

Using a new chrome profile with PB installed (as suggested above) CNN articles do *not* constantly refresh.  Yay!  But, obv, I don't want to have to use a completely different profile just to read CNN.


Chrome  Version 106.0.5249.62 (Official Build) (64-bit)

**Comment by ghostwords** [comment]
@tjanke42 Thanks for the info!

You wrote that you do not experience refreshing with a new Chrome profile. Are you able to reproduce refreshing if, in your usual Chrome profile, you download your user data from the Manage Data tab on Privacy Badger's options page, and then launch Chrome a new profile, install Privacy Badger, and import the data from your regular profile?

**Comment by tjanke42** [comment]
I'll give that a try and report back (may take a few days).

**Comment by gwilliams99** [comment]
Okay- as others have pointed out- the CNN constant refresh problem has came back.
Privacy Badger is definitely causing this. However I can verify that it's not just PB that has this issue. DuckDuckGo Privacy Essentials is causing the constant refresh also. 
I can disable either individually and the problem continues. If I disable both the refresh stops.
Chrome Build 105.0.5195.127 (Official Build) (64-bit) 
I just updated to :
Version 106.0.5249.91 (Official Build) (64-bit)

The problem still exists in the latest Chrome build- Both PB and DuckDuckGo Privacy Essentials have to be disabled to stop the refresh- either disabled individually won't stop the refresh.

**Comment by tjanke42** [comment]
I've installed the PB data in the new profile, and the problem does not recur.  However! the problem _also_ does not recur in my original chrome profile with PB re-enabled.  It looks like CNN may have made some changes that eliminated the trigger for the issue?  

Since I can't reproduce the issue in the original chrome profile at this time, not having the issue in the new profile doesn't mean anything.  If the problem re-occurs in the original profile, I'll re-import the PB data to the new profile and try again to reproduce there.

So, the issue is moot.  For now.

**Comment by tjanke42** [comment]
The issue is back!  CNN is repeatedly refreshing every few seconds in the main profile, but *not* in the alternate profile, with the PB data freshly copied over.

**Comment by Fish-Git** [comment]
_**FYI:**_ The following seems to workaround the problem:

Create a [bookmarklet](https://www.freecodecamp.org/news/what-are-bookmarklets/#:~:text=Bookmarklets%20are%20browser%20bookmarks%20that,browsers%20like%20Chrome%20or%20Brave.) called "STOP AUTO REFRESH" using the following javascript as the URL:

           javascript:window.setInterval(function() {window.stop()},10)

Then when you visit a web page (such as CNN) where the problem starts occurring, simply open the "STOP AUTO REFRESH" bookmark. &nbsp; _**Voilà! &nbsp; Problem solved!**_

Manually refreshing the page of course causes the problem to immediately reoccur, but simply opening the "STOP AUTO REFRESH" bookmark instantly stops it again.

This of course is _not_ a "fix", but rather just a workaround. The actual fix requires either CNN to stop doing whatever it is they're doing on their web pages to cause the problem to occur, or else Chrome to stop doing whatever _it's_ doing to allow the problem to occur. _(Yes, the problem only started happening after a recent Chrome update.)_

And yes, you're right: the Privacy Badger extension is somehow involved. Disabling PB does indeed prevent the problem from occurring, but I prefer to leave PB enabled so I simply use my "STOP AUTO REFRESH"  bookmarklet instead.

Try it! &nbsp;It works a treat!

**Comment by tjanke42** [comment]
Fish-Git, thanks for the workaround!  It does indeed stop the refreshing, for that individual page.  
  
Still hoping for a permanent solution, though.  :)

**Comment by Norjak** [comment]
Greetings, I'm having the same problem in Firefox. But it goes away if I disable PB. The problem seemed to go away for a few weeks, but now it has returned.

**Comment by tjanke42** [comment]
Yeah, still have the same problem.  Goes away, comes back.

Cheers,
Tim

--
Tim Janke
408.472.1294

**Comment by errorlifeisnull** [comment]
I went into cnn.com's source code, I'm a bit busy so I can't unminify things, but there's quite a few calls to `location.reload` inside some of the home page's `<script>` tags. Privacy Badger seems to be triggering something that causes the site to reload, maybe because of an error that occurred, but I'm unsure. Is this reproducible if you use only something like uBlock Origin, where they block and replace specific functions and URLs, instead of domains? If not, they might have blocked the specific culprit here or something.

**Comment by tjanke42** [comment]
> Is this reproducible if you use only something like uBlock Origin

Short answer: no.  Long answer:  I use AdBlock, uBlock Origin and Privacy
Badger together.  If I turn off PB, the problem goes away, but if I turn
off the others (and leave PB on) it remains.

Cheers,
Tim

--
Tim Janke
408.472.1294

**Comment by errorlifeisnull** [comment]
I'll see if uBlock fixed this some time. Thanks for the information.

**Comment by ghostwords** [comment]
We stopped receiving reports about this problem sometime shortly before January 2023.
