### ISSUE TITLE
Enhancement idea: LibreJS support.

### ISSUE THREAD

**Issue by dertuxmalwieder** [EFForg/privacybadger#2842]
It *potentially* exceeds the goals of the Privacy Badger, but, given that there is no [LibreJS](https://www.gnu.org/software/librejs/manual/librejs.html#Setting-Your-JavaScript-Free) extension for Chrome/Chromium (thus, Vivaldi which I use) yet, I wonder whether it could get another checkbox to block all non-free JavaScript files. (Disabled by default, as very few JavaScript files are "free" right now.)

That would, at least, match the goal of improving the privacy on the web, as *libre* JavaScript files are unlikely to breach the users' privacy,

**Comment by ghostwords** [comment]
Hello and thank you for the suggestion!

Yep, this doesn't seem to fit into [Privacy Badger's core mission](https://privacybadger.org/#How-is-Privacy-Badger-different-from-Disconnect%2c-Adblock-Plus%2c-Ghostery%2c-and-other-blocking-extensions) of automatically learning to block non-consensual tracking. Also, as all features come with implementation and maintenance costs, we should try to avoid off-by-default features.
