### ISSUE TITLE
Tenor.com can't Sign in with Google account

### ISSUE THREAD

**Issue by Tiagoquix** [EFForg/privacybadger#2844]
#### What is your browser and browser version?
Google Chrome 103.0.5060.53 64 bits
Privacy Badger 2021.11.23.1

#### What is broken and where?
`http://tenor.com/` - can't Sign in with Google account.

#### What is the "culprit" domain?
`accounts.google.com`.
This is cookie-blocked on other sites too, but it works normally. Only on Tenor it does not.

#### What is your debug output for this domain?
Default settings: `https://pastebin.com/raw/JbBM36ks`
`accounts.google.com` allowed (green) in Privacy Badger: `https://pastebin.com/raw/7yNNUkCG`

The above links will expire in 6 months.

**Comment by ghostwords** [comment]
Hello and thanks for reaching out!

To sign in via Google, you can move the slider for `accounts.google.com` to "green" and reload the page, or you can click on the "Disable for this site" button in Privacy Badger's popup. Either one will let you sign in; the difference is between allowing all tracking on a single site vs. keeping Privacy Badger active on the site but allowing `accounts.google.com` to track you everywhere on the Web.

We plan to make this more intuitive in the future in #137.

Let me know if you have any questions.
