### ISSUE TITLE
teamfortress.com facebook like button

### ISSUE THREAD

**Issue by Tiagoquix** [EFForg/privacybadger#2846]
`https://www.teamfortress.com/?tab=updates`

Privacy Badger doesn't replace the "Like" button from Facebook, but it does block its cookies.

**Comment by ghostwords** [comment]
Hello again!

Privacy Badger [doesn't replace widgets from cookieblocked domains](#2267), as replacing no longer offers a real benefit once a domain is allowed to load. We plan to [remove `www.facebook.com` from the yellowlist](#1593) and start fulling blocking its resources at some point after we provide a more complete [surrogate-based replacement](#2805) for the various Facebook widget APIs.

Let me know if you have any questions.
