### ISSUE TITLE
Twitter Google Login Infinitely Loads When Extension Enabled

### ISSUE THREAD

**Issue by Facel3ss** [EFForg/privacybadger#2854]
Browser - Firefox 105.0.3 (64-bit)

#### What is broken and where?
Twitter Google login infinitely loads. 

#### What is the "culprit" domain?
accounts.google.com

#### What is your debug output for this domain?

The javascript code returned this, I'm not sure what is broken but it doesn't seem right.

```
Uncaught ReferenceError: getBaseDomain is not defined
    <anonymous> debugger eval code:2
    <anonymous> debugger eval code:28
debugger eval code:2:15
    <anonymous> debugger eval code:2
    <anonymous> debugger eval code:28
```

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch!

To sign in via Google, you can move the slider for `accounts.google.com` to "green" and reload the page, or you can click on the "Disable for this site" button in Privacy Badger's popup. You may want to move the slider if you want to use Google Login on many different sites. We plan to make this more intuitive in the future (#137).

Let me know if this helped.

**Comment by ghostwords** [comment]
Closing as a duplicate for now.
