### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by FoxGamingYTCR** [EFForg/privacybadger#2856]
I have no idea what happened, today It shows the 'An unexpected error occurred' message and doesn't seem to block trackers. Could someone please look into this and try to fix it? This is the only time I have had any problems with the add-on.

**Comment by ghostwords** [comment]
Hello! Is your disk low on space? Please see my reply in https://github.com/EFForg/privacybadger/issues/2804#issuecomment-927890007, and let me know if you have any questions.
