### ISSUE TITLE
My PDF hosting service is incorrectly blocked

### ISSUE THREAD

**Issue by joepie91** [EFForg/privacybadger#286]
I've recently started using Privacy Badger instead of DNT, but it seems that (my installation of) Privacy Badger has started to incorrectly block embedded documents from https://pdf.yt/, which is a PDF hosting service I run.

I'm not really sure why it's doing this - PDFy doesn't track users at all, and the only cookie sent is a standard PHPSESSID cookie for functional purposes. It's effectively completely breaking embeds at this point.

**Comment by davidmckenzie** [comment]
I'm seeing this on a number of sites, notably: http://forecasts.bsch.com.au/stormcast.html?ops=gfs::::ts:null

This includes static assets from http://stormcast.com.au/ and includes the PHPSESSID cookie. Perhaps the PHPSESSID cookie should be whitelisted?
