### ISSUE TITLE
No Youtube widget on Scroll.in

### ISSUE THREAD

**Issue by etanot** [EFForg/privacybadger#2864]
**Type:** Bug report

#### Description
When **youtube.com** domain is blocked (i.e. PB's slider is at left hand side), there is no Youtube widget for videos which are hosted on Youtube.

#### Steps to reproduce
- Find any web page which embedded a Youtube video on [Scroll.in](https://scroll.in). For example, go to [Eco India](https://scroll.in/topic/56120/eco-india) documentary section and choose any story ([Eco India, Episode 205: The world's finite resources are depleting. How can we reverse this trend?](https://scroll.in/video/1038375/eco-india-episode-205-the-world-s-finite-resources-are-depleting-how-can-we-reverse-this-trend)).
- Move the slider for **youtube.com** domain to the left hand side to block the domain.
- Now reload the page to reflect the changes.

#### Expected behavior
Video's placeholder should be replaced with PB's Youtube widget.

#### Actual behavior
Video's Youtube thumbnail is present at the placeholder with a play icon at center. Also nothing happens when we click on play icon.

![Scroll.in](https://user-images.githubusercontent.com/28824347/205455601-0fffd6a9-8b83-4ede-81ea-45e5e0e2b5e9.png)

#### What is your browser and PB version?
Browser: Mozilla Firefox, 102.5.0esr (64-bit)
PB: 2022.9.27

**Comment by ghostwords** [comment]
I just added a workaround where our replacement placeholder appears and clicking allow reloads the page (rather than activate the widget in-place).

We may revisit this in the future to fix in-place activation (more broken examples in #2852).
