### ISSUE TITLE
Privacy Badger blocks Yandex Browser's built-in translation services

### ISSUE THREAD

**Issue by mredrake** [EFForg/privacybadger#2872]
Errors while attempting to translate text on the page or video using Yandex Browser. This is not reproduced if the following hosts added to yellowlist:
`browser.translate.yandex.net` - for page translation
`vtrans.s3-private.mds.yandex.net` - for video translation

[Screenshot 1 - video translation](https://user-images.githubusercontent.com/23695078/218987325-309c62a1-20fa-4329-b258-c5e38899a2fa.png)
[Screenshot 2](https://user-images.githubusercontent.com/23695078/218987336-c710a735-d9f9-4cc0-9b79-4b2897332ea4.png) and [Screenshot 3](https://user-images.githubusercontent.com/23695078/218987339-8dc47705-70ea-4081-b71e-ac38994764d6.png) - page translation

**Comment by mredrake** [comment]
Thank you for attention to this issue

Sure.

https://www.youtube.com/watch?v=c0KYU2j0TM4 - there is the page with available video translation (en->ru)
https://en.wikipedia.org/wiki/Main_Page - and this one with translation of the page text (en->ru)

Because page/video translation are built-in Yandex Browser features you need to install it to reproduce the problem (https://browser.yandex.ru)

Or you can watch the demos of its use cases below
https://user-images.githubusercontent.com/23695078/219076562-5d2dd655-484c-4312-9956-97b47e68c591.mov
https://user-images.githubusercontent.com/23695078/219076570-90bb25c1-02c5-4d83-b4c1-56a189e64d89.mov

If needed these features can be disabled through settings page
[Screenshot](https://user-images.githubusercontent.com/23695078/219078409-569eaea3-5e22-4a05-9c84-d346f5b0e792.png)

**Comment by ghostwords** [comment]
Ah, I see, this is a Yandex Browser feature.
