### ISSUE TITLE
CentralAuth login cookies

### ISSUE THREAD

**Issue by thecutefinder** [EFForg/privacybadger#2881]
For context:
* MediaWiki powers 6,006 independent Miraheze wikis
* Fandom (one of the largest wiki hosts) uses MediaWiki
* MediaWiki powers Wikipedia, Wikimedia Commons, and all Wikimedia Foundation domains

Now, the Wikimedia Foundation created an extension called CentralAuth that almost every wiki hosting provider except for Fandom uses. Wikipedia and its various wikis also uses CentralAuth, but this is fixed by a multi-domain first party change. However, on sites such as Miraheze, where independently administrated wikis on the same free infrastructure are permitted to add the custom domains they bought, `miraheze.org` is entirely required for login, but due to the excessive cookies implemented by the Wikimedia Foundation in their CentralAuth extension, `login.miraheze.org` gets detected as a tracker.

One of the largest wikis where the login infrastructure gets detected as a tracker is, for example, https://rosettacode.org/wiki/Rosetta_Code, a wiki with a custom domain that has coverage in reliable sources and a Wikipedia article about it.

The problem here is that these domains can't be added to the multi-domain first party list because they aren't owned by the same people (Miraheze does not own the wikis hosted on it beyond technical infrastructure), and there are way too many domains, and they'd have to be updated frequently every time there's another wiki that asks for a custom domain.

CentralAuth domains *could* just be whitelisted (see #2879), but this seems like it would get to a very long list of login cookies in the heuristic files very fast.

**Comment by ghostwords** [comment]
Thank you for filing this!

**Comment by thecutefinder** [comment]
Upon further investigation, this is no longer an issue, because CentralAuth domains usually do not share cookies across multiple domains. If you went to publictestwiki.com while logged into meta.miraheze.org, even with Privacy Badger disabled, you would still have to log in again there. Adding the Miraheze CDN domains to the yellowlist is all that is needed to fix it on Miraheze, and probably all that is needed for other sites as well.
