### ISSUE TITLE
https://ave9858.github.io/msdl/ is broken by privacy badger.

### ISSUE THREAD

**Issue by ave9858** [EFForg/privacybadger#2884]
#### What is your browser and browser version?
Tested on Firefox, version 110.0.1, but I can reproduce the issue on all recent Firefox versions.
#### What is broken and where?
https://ave9858.github.io/msdl/ fails to download any ISOs because connections to the Microsoft API are blocked.
#### What is the "culprit" domain?
www.microsoft.com has the main API needed to generate ISO links, but h-microsoft.online-metrix.net (CNAME of vlscppe.microsoft.com) is needed to allow new session IDs.

#### What is your debug output for this domain?
Not sure what I did wrong, but I get `Uncaught ReferenceError: getBaseDomain is not defined` when pasting in the [code](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain) to the extension debug console.

**Comment by ghostwords** [comment]
Hello and thank you for reporting!

`h-microsoft.online-metrix.net` was added in 3f0ee014a90740b8b804bb1e1f8961368a553f3d

>I get Uncaught ReferenceError: getBaseDomain is not defined when pasting in the code

The debugging code  [should work now](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain/_compare/456423d92aeb73c0d0911e9de250c0b91aff1fe4...b55a64f61700f36e4f610c1d9ab41c0f1c94e8d0).
