### ISSUE TITLE
Microsoft Edge crashes when Privacy Badger is installed

### ISSUE THREAD

**Issue by VulpesSARL** [EFForg/privacybadger#2897]
I got an update for 113.0.XXX.XXX (tried with multiple).
I've Privacy Badger installed via Group Policy, with default configuration. (Time of writing: Privacy Badger 2023.5.10 is installed)

When going to (for example) https://www.deviantart.com/notifications/ with a valid account, you notice that the whole Edge, with all Tabs, PWA, running Download closes.

In the crashdump, it crashed in MSEDGE.DLL. (but no stacktrace can be properly build)

I tried on multiple machines (Windows 10 Enterprise, and Windows Server 2019 Standard), and did a rollback to version 112.X.XXX.XXX of Microsoft Edge.

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch! Could you report this bug to Microsoft? Perhaps [through channels documented here](https://github.com/w3c/webextensions/issues/155#issuecomment-1029956000) or [directly in their GitHub forum](https://github.com/microsoft/MicrosoftEdge-Extensions/discussions).

**Comment by ghostwords** [comment]
Is this still an issue? I haven't gotten any other reports.

**Comment by VulpesSARL** [comment]
Actually, since Version 114.0.1823.43 (and one earlier), that problem won't happen anymore.

**Comment by ghostwords** [comment]
Excellent, thanks for updating!
