### ISSUE TITLE
Google search link unwrapping doesn't work with endless scroll

### ISSUE THREAD

**Issue by hyder365** [EFForg/privacybadger#2900]
When I do a google search, privacy badger prevents google from changing the links at the last second (upon clicking or right-clicking) to their tracking version. This works fine until you scroll down past a certain point.

Nowadays google search results use an "endless scrolling" type of feature where more results are loaded when you scroll down past a certain point. All the links past the first group of results are using the tracking links, so privacy badger isn't fixing them.

**Comment by ghostwords** [comment]
Thank you for reporting this issue! This is similar to and should have the same fix as #2866.
