### ISSUE TITLE
Spotify embed does not work on specific site

### ISSUE THREAD

**Issue by purplux** [EFForg/privacybadger#2904]
#### What is your browser and browser version?
Brave, running Version 1.56.14 Chromium: 115.0.5790.114 (Official Build) (64-bit)

#### What is broken and where?
For context, "https://feds.lol" is a site where you can make your own account, and upload a bio to it. The spotify embed does not work at all if privacy badger is enabled on it. For example, my bio: https://feds.lol/ppurplux

#### What is the "culprit" domain?
The culprit domain is https://feds.lol, specifically https://feds.lol/ppurplux

Please follow the debug instructions to identify which domain breaks stuff when blocked:
https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain

#### What is your debug output for this domain?
```
**** ACTION_MAP for spotify.com
api.spotify.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1691077567639,
  "userAction": ""
}
apresolve.spotify.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1691442948907,
  "userAction": ""
}
embed-standalone.spotify.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1691376835643,
  "userAction": "user_allow"
}
embed.spotify.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
gae2-spclient.spotify.com {
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1691508767592,
  "userAction": ""
}
open.spotify.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1691509611808,
  "userAction": ""
}
podcasters.spotify.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
spotify.com {
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0,
  "userAction": ""
}
api-partner.spotify.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1691529888538
}
spclient.wg.spotify.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1691519733641
}
**** SNITCH_MAP for spotify.com
spotify.com [
  "indiatoday.in",
  "pagesix.com",
  "nypost.com"
]

```

**Comment by ghostwords** [comment]
Hello and thanks for the report!

I just updated Privacy Badger's replacement placeholder for Spotify to properly handle this variant of the Spotify widget. This fix will be part of Privacy Badger's next update.

**Comment by purplux** [comment]
Thank you for the extremely speedy process! ♥
Starring this!
