### ISSUE TITLE
Privacy Badger extension "broken" in Vivaldi

### ISSUE THREAD

**Issue by MaravicMarko** [EFForg/privacybadger#2911]
Hello,

For the last week or so, Privacy Badger extension is "broken" in Vivaldi. 
I am using Vivaldi on three systems: Windows 11 22H2 (Vivaldi v6.3.3134.3), Windows 10 LTSC 2021 (Vivaldi v6.3.3134.3) and Linux Mint 21.2 (Vivaldi v6.2.3105.48), and on all three, I have the same issue, as seen on attached screenshots. 
I have tried to remove the extension and install it again from Chrome store, but the issue remained.
I refuse to use Chrome, Edge or Opera (as representatives of Chromium based browsers), so am not able to check there. At least, it works OK on Firefox. 

Let me know if there are some logs that I can extract, that could help with troubleshooting of the issue.

Thank you in advance.

Best regards,
Marko

![Screenshot 2023-09-19 105828](https://github.com/EFForg/privacybadger/assets/72248348/487bc8d5-bf0b-4a4d-a603-48a67b7a4f3e)
![Screenshot 2023-09-19 105840](https://github.com/EFForg/privacybadger/assets/72248348/b6ac6a54-5f18-4371-bee7-d238adceac8f)
![Screenshot 2023-09-19 105846](https://github.com/EFForg/privacybadger/assets/72248348/3f6dcac9-250c-4a78-b2b3-fe0d7173b4ff)

**Comment by ghostwords** [comment]
Hello! Have you already [reported this issue to Vivaldi](https://vivaldi.com/bugreport/)?

**Comment by ghostwords** [comment]
This appears to be some kind of Vivaldi bug, although I'm not sure why I don't see recent [reports in Vivaldi forums](https://forum.vivaldi.net/search?in=titlesposts&term=ERR_FILE_NOT_FOUND&matchWords=all&by=&categories=&searchChildren=false&hasTags=&replies=&repliesFilter=atleast&timeFilter=newer&timeRange=&sortBy=timestamp&sortDirection=desc&showAs=posts). I would think more Vivaldi users would have run into it by now. Is this still an issue?

**Comment by MaravicMarko** [comment]
Hi @ghostwords,

Sorry for late reply. I didn't manage to open a bug report on Vivaldi side. Chronic lack of time T_T
The extension is still "broken" on my two Windows machines, but it (magically) started working again on a Linux Mint machine.
I will try to find time to report on the Vivaldi side.
Thank you for time and effort.

Cheers 🖖🏼
