### ISSUE TITLE
Suggest the use of developer tools for finding the broken site

### ISSUE THREAD

**Issue by rugk** [EFForg/privacybadger#2914]
I have an idea for https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain#1-find-the-culprit-domain.

You can suggest to (also) use the developer network tools to find what domain is actually blocked by PrivacyBadger at some step. At least in Firefox you can see it this way:
![grafik](https://github.com/EFForg/privacybadger/assets/11966684/07f8e95c-c689-4950-b58c-0fba921dec62)

from https://github.com/EFForg/privacybadger/issues/2912

**Comment by ghostwords** [comment]
Thanks for the suggestion! Where exactly do you see browser developer tools helping?

While it is nice that Firefox reports "Blocked by Privacy Badger", Chrome does not. I also think opening and making sense of dev tools is much harder than opening Privacy Badger's popup and reviewing the blocked domains listed there.
