### ISSUE TITLE
Easylist syntax blocklist

### ISSUE THREAD

**Issue by TotalImportance8529** [EFForg/privacybadger#2921]
I am a uBlock Origin user and I want to add Privacy Badger's pre-trained list as a custom filterlist , because Privacy Badger's list is very special,  it is not maintained by human like other adblocker filterlist. So, can Privacy Badger team convert it into Easylist syntax ?

I know the FAQ said you can use Privacy Badger with adblockers , but uBO specifically told people don't use any other content blocker with it.
https://github.com/gorhill/uBlock#all-programs

**Comment by ghostwords** [comment]
Thanks for reaching out!

Unfortunately, it's not as simple as taking the domains that Privacy Badger learns to block and making a block list out of them. See the following link for more information, and let me know if you have any followup questions.

https://github.com/EFForg/privacybadger/discussions/2786#discussioncomment-1021999

uBlock Origin is an excellent privacy tool. You're doing well if:

- You use uBlock Origin by itself
- You use Privacy Badger by itself
- You use Privacy Badger with uBlock Origin

I use Privacy Badger by itself.
