### ISSUE TITLE
Ability to filter domain list to only domains that Local Learning has detected

### ISSUE THREAD

**Issue by ghost** [EFForg/privacybadger#2929]
Hello! I don't believe this feature exists, I've looked around for it but I could not find it.

I'd like to request the ability to sort the domain list to list only domains that have been detected as tracking by Local Learning when the feature is enabled. 

Currently there is the option "Show domains your Badger hasn't decided yet to block", but this only adds those to the existing list, which due to the size of the list, it is difficult to tell which domains Local Learning has found, and which were already in the list before.

**Comment by ghostwords** [comment]
Would a "Show domains not present in the latest pre-trained list" checkbox be good enough?

The difference between this and "Show domains that your Badger learned from your browsing" is that diffing against the latest pre-trained list won't necessarily show you only domains you learned locally. It will also show domains you got from a past pre-trained list that are no longer present in the latest pre-trained list for whatever reason.

The reason I ask is that there is currently no way to tell a locally learned domain from a pre-trained domain in Privacy Badger data. I'm also not sure we want to add metadata to mark domains one way or another.

**Comment by NiaTheCat** [comment]
> Would a "Show domains not present in the latest pre-trained list" checkbox be good enough?

Yes, I think that'd get about the same effect, thank you for the fast reply!

**Comment by sanjayen** [comment]
I have NOT enabled local learning. However, after using PB for more than 2 months now, the tracking domains has increased from the default 2171 to 2173. I can never find what these 2 new domains are using the drop-downs provided. Any chance a similar filter can be provided in the drop-down stating - "New tracking domains added not present in the latest pre-trained list"

**Comment by ghostwords** [comment]
Hello! If you like, you can send me (alexei at eff dot org) your Privacy Badger data so that I can tell you what's different, and perhaps find a bug to fix.

**Comment by sanjayen** [comment]
I have emailed the JSON file. To see if I could compare the difference, I installed PB in Firefox nightly. It started with 2171 domains. But after some time, it increased to 2173. Is PB finding some trackers or getting updated?
