### ISSUE TITLE
Need more control over notifications

### ISSUE THREAD

**Issue by Dan-Essin** [EFForg/privacybadger#2931]
Hello,
There are certain web sites that I visit regularly such as my email, pandora, etc.
It does not benefit me to see the warning popup every time I open one of those sits. PB has already notified me and I have accepted the risk. Repeated notifications won't change my behavior and are distracting, especially the chime. 

How about an option to turn off repeating notifications for a specific site after I have seen the first one?

**Comment by ghostwords** [comment]
Hello and thanks for getting in touch!

What warning popups or notifications do you mean? Feel free to include a screenshot if that helps explain.

**Comment by ghostwords** [comment]
Are these notifications coming from another extension?

**Comment by ghostwords** [comment]
Let me know if you have more information.
