### ISSUE TITLE
Out of date information displayed when extension is first installed

### ISSUE THREAD

**Issue by ToddDTaft** [EFForg/privacybadger#2936]
When Privacy Badger is first installed, it opens a tab that displays information about the extension.  Some of this information is out of date and no longer correct (with default settings).  For example, it displays information stating that Privacy Badger "Learns automatically: Instead of keeping lists of what to block, Privacy Badger automatically discovers trackers based on their behavior."  This has not been default behavior of the extension for a long time for the reasons described in https://www.eff.org/deeplinks/2020/10/privacy-badger-changing-protect-you-better.

If you are attempting to describe how the site list is generated to highlight differences from the method that is used by some other extensions, the statement should be re-worded, as the current wording implies that the learning is done by each individual installation, which is no longer default behavior.

**Comment by ghostwords** [comment]
Hello!

I agree that we should update the welcome page and clean up the wording. See https://github.com/EFForg/privacybadger/issues/2781#issuecomment-941187755 for some of my past thoughts on this matter.

However, Privacy Badger does in fact still automatically learn to block invisible trackers. From https://privacybadger.org/#How-does-Privacy-Badger-work:

>By default, Privacy Badger receives periodic learning updates from [Badger Sett](https://github.com/EFForg/badger-sett), our Badger training project. This “remote learning” automatically discovers trackers present on thousands of the most popular sites on the Web. Privacy Badger [no longer learns from your browsing](https://www.eff.org/deeplinks/2020/10/privacy-badger-changing-protect-you-better) by default, as “local learning” may make you more identifiable to websites. You may want to opt back in to local learning if you regularly browse less popular websites. To do so, visit your Badger’s options page and mark the checkbox for learning to block new trackers from your browsing.

Let me know if this helps.

**Comment by ghostwords** [comment]
Also, you may want to check out [our recent blog post](https://www.eff.org/deeplinks/2023/10/privacy-badger-learns-block-ever-more-trackers) about the evolution of Privacy Badger's learning.
