### ISSUE TITLE
CSP injectScript warning

### ISSUE THREAD

**Issue by bravecrayon** [EFForg/privacybadger#2941]
In FireFox 123.0b1 on a site with CSP `script-src` set to `'self'` I see this in the console:

```
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:42:10
```
That is [this line](https://github.com/EFForg/privacybadger/blob/master/src/js/contentscripts/utils.js#L42). Why is it trying to inject a `<script>` tag? Also, could a site easily evade whatever PrivacyBadger is trying to do here with a specifically crafted CSP?

**Comment by ghostwords** [comment]
Thanks for reaching out!

This is a [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) where the browser fails to override site CSPs for page context ("main world") scripts injected by extension content scripts.

This will be fixed when Firefox fixes their bug, or when we will change the way we inject into page contexts.

Privacy Badger injects page context scripts for things like [click-to-activate widget placeholders](https://www.eff.org/deeplinks/2024/01/privacy-badger-puts-you-control-widgets), DNT/[GPC](https://globalprivacycontrol.org/) in JavaScript and blocking JavaScript access to cookies for cookie-blocked ("yellowlisted") domains. Core tracker blocking functionality is not affected.

Closing as a duplicate of #1793.
