### ISSUE TITLE
Blocking ChatGPT

### ISSUE THREAD

**Issue by paccerdk** [EFForg/privacybadger#2949]
There's currently a bunch of messages on the OpenAI discord as of today, 

They all seem to have the same problem in common, and it seems like more or less everyone using ChatGPT + Privacy Badger is not getting any responses on the site.

I've confirmed the issue and a solution,
Changing the "chatgpt-async-webps-prod-eastus-23.webpubsub.azure.com" from a domain block to a cookie block resolves the issue.

**Comment by ghostwords** [comment]
Thank you for opening an issue!

This should be automatically fixed within the next 24 hours by e5fa9499d90db250f07c77881823e5087de285f7.

Let me know if you have any questions.

**Comment by paccerdk** [comment]
Thanks for the quick response and providing a good service!
