### ISSUE TITLE
Anti adblocker wall on loot-link.com

### ISSUE THREAD

**Issue by DogancanYr** [EFForg/privacybadger#2952]
#### What is your browser and browser version?
Firefox developer latest version.

#### What is broken and where?
pagead2.googlesyndication.com
It thinks it's an ad blocker if it gets blocked.

**Comment by ghostwords** [comment]
Hello and thanks for opening an issue!

Could you link to an example page where you see this happen?

**Comment by DogancanYr** [comment]
My mistake I forgot to give the link .
https://loot-link.com/s?p7do

**Comment by ghostwords** [comment]
The thing is that Privacy Badger is not an adblocker, and it's not clear whether we should try to circumvent anti-adblocker walls or not. Since we don't yet a good response to this class of nuisance, it's a shortcoming for sure, but I don't think it merits a one-star review. It is clearly something for us to improve in the future though.

We got a bunch of information on what makes Privacy Badger special [on the homepage FAQ](https://privacybadger.org/#faq). Let me know if you have any questions.

**Comment by DogancanYr** [comment]
Privacy Badger is only using static filters by
default, which provides no real benefit over uBlock Origin. It
used to "learn" about trackers, but this was turned
off as a default because of security and
fingerprinting concerns and since uBlock Origin blocks domains, blocked domains would also be blocked from setting cookies.

**Comment by ghostwords** [comment]
While there is likely to be overlap between the various advertising/tracker lists and Privacy Badger, regardless of whether you enable learning locally, Privacy Badger can [automatically discover new trackers](https://www.eff.org/deeplinks/2023/10/privacy-badger-learns-block-ever-more-trackers) that list-based blockers don’t know about.

Besides automatic tracker blocking, Privacy Badger comes with privacy features like [click-to-activate replacements](https://www.eff.org/deeplinks/2024/01/privacy-badger-puts-you-control-widgets) for potentially useful trackers (video players, comments sections like Disqus, etc.), and link cleaning on [Facebook](https://www.eff.org/deeplinks/2018/05/privacy-badger-rolls-out-new-ways-fight-facebook-tracking) and [Google](https://www.eff.org/deeplinks/2023/09/new-privacy-badger-prevents-google-mangling-more-your-links-and-invading-your).

Privacy Badger is also a political tool. By using Privacy Badger, you support the [Electronic Frontier Foundation](https://www.eff.org/). Privacy Badger sends the [Global Privacy Control](https://globalprivacycontrol.org/) signal to opt you out of data sharing and selling, and the [Do Not Track](https://www.eff.org/issues/do-not-track) signal to tell companies not to track you. If trackers ignore your wishes, Privacy Badger will learn to block them. The idea isn't to block all advertising but rather to promote a better Web.

uBlock Origin is an excellent privacy tool, but just as Privacy Badger is not a replacement for uBlock Origin, uBlock Origin is not a replacement for Privacy Badger.

**Comment by DogancanYr** [comment]
I think these will be the Disqus tracker cookies.
![resim](https://github.com/EFForg/privacybadger/assets/90002969/6424d805-c159-4799-bbae-56c8747cd1de)

**Comment by ghostwords** [comment]
I'm not sure what your point is. If uBlock Origin blocks some Disqus tracking requests, great! That is not at all the same as [what Privacy Badger does](https://www.eff.org/deeplinks/2024/01/privacy-badger-puts-you-control-widgets) for Disqus and a whole bunch of other widgets.
