### ISSUE TITLE
Privacy Badger on Chrome on Linux consuming high CPU

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#2954]
### Discussed in https://github.com/EFForg/privacybadger/discussions/2953

How does one debug (to see if it is related to a specific tab)?

<div type='discussions-op-text'>

<sup>Originally posted by **nhed** March  6, 2024</sup>
Seen it happen several times (over several PB versions).  Laptop fans spinning up, `htop` showing high cpu taken by chrome, chrome's task manager shows PB as highest CPU user.

![image](https://github.com/EFForg/privacybadger/assets/513759/13cd85fc-a7c1-4549-b881-4bcdc9565feb)

- `uname -r`:  `6.5.10-200.fc38.x86_64`
- `rpm -q google-chrome-stable`:  `google-chrome-stable-120.0.6099.224-1.x86_64`
- PB version: `2024.2.6`

Disabled & Re-enabled and things quieted down

Did not see any discussion re CPU usage (is this the right place to have this convo?)</div>

**Comment by ghostwords** [comment]
@nhed Are you able to reproduce this bug? For example, does this happen regularly while using Google Meet or some other specific website?

**Comment by nhed** [comment]
![image](https://github.com/EFForg/privacybadger/assets/513759/8416bde8-b353-4d37-a60f-695703162aa3)

Seeing this also after re-installing.

**Comment by nhed** [comment]
well - _maybe_ uninstalling extension and restarting chrome would have done the trick - not sure

When I checked underlying storage to see which `LOCK` file was attempted - I noticed there were two - one under `Local Extension Settings` and one under `Managed Extension Settings`  (is the latter because my browser is managed by my org?)

Noticed that teh date on the LOCK file was old and renamed whole dir while reinstalling ext - but only then noticed with `lsof` that chrome was holdingi on to said renamed dir even when the ext was uninstalled.

after forcing restart of chrome - things came back ok (ext is now responsive)

I will now monitor for the CPU issues and come back here if it recurs


Thanks

**Comment by ghostwords** [comment]
Sounds good, thank you!

**Comment by ghostwords** [comment]
Looks like the Chrome IO lock error means that Chrome extension storage is broken, which would break pretty much all browser extensions. Restarting Chrome should fix it though. Not sure why or when this happens though.

**Comment by nhed** [comment]
Just started seeing it again today.   Seeing the same LOCK issue - not sure if there is a point in doing the performance recording but did anyway and sent while awaiting disabled the extension (I think it will recreate as long as I do not restart browser - and guarantee proper cleanup in between)

**Comment by ghostwords** [comment]
Thanks for the performance recording!

It looks like the CPU is maxed out because while Privacy Badger failed to properly initialize, probably because of JS errors, maybe [the one above](https://github.com/EFForg/privacybadger/issues/2954#issuecomment-1981956984), Privacy Badger still injected "content scripts" into the page (for example to help remove tracking from some links inside Gmail) and the content scripts want to know whether they should proceed but Privacy Badger isn't ready to respond to them yet but it will never be ready because of the JS errors and we get [an infinite loop at this point](https://github.com/EFForg/privacybadger/blob/c8e513dba74cf8334d8e3cc46c604fd3061c1d4a/src/js/webrequest.js#L1192).

So ... I should be able to fix the infinite loop, which will fix the CPU issue. However, Privacy Badger will still break now and then for you, where it will fail to finish initializing because something is badly wrong with browser extension storage.

It would be good to figure out what to do to fix the underlying extension storage Chrome issue. Will removing your Chrome profile and starting from scratch do it? Do other people run into this problem? It doesn't seem Privacy Badger-specific.

**Comment by nhed** [comment]
Would your fix have any visual indications that the extension failed to initialize? 
Let me know if you want me to test - I intentionally left the browser going and just disabled the extention.  I cloned your PR branch and I think I'm supposed to "load unpacked" while pointing to the `src` dir but not sure if there is some prep step to run on the local repo

**Comment by ghostwords** [comment]
Sure, testing would be really nice! We could also then [take another look at the errors](https://github.com/EFForg/privacybadger/issues/2954#issuecomment-1981902835) that cause Privacy Badger to fail on initialization.

There are no extra steps, no build process, just load from `src/`. Let me know here or over email if you have any questions.

**Comment by nhed** [comment]
unfortunately since offering to test my browser did crash so it will probably be a while before I run into the lock/local-storage issues
