### ISSUE TITLE
Twitter share button broken on firstRun.html

### ISSUE THREAD

**Issue by WilliamKeating** [EFForg/privacybadger#2958]
The Twitter share button on firstRun.html does not auto-populate a tweet with the intended message and link instead it just redirects to the Twitter timeline homepage.

**Comment by ghostwords** [comment]
Hello and thank you for the issues and pull requests! By the way, it would be great to add a Share on Mastodon button, either instead of or in addition to the Twitter button.

**Comment by WilliamKeating** [comment]
Hello, I am excited to start helping contribute to this project! I created a share on Mastodon button and added it to the linked pull request. I can also update the Twitter button to X if we feel it's important to be in spec with their brand guidelines although I think the original logo is more commonly recognizable.
