### ISSUE TITLE
Bilibili’s external videos cannot be played

### ISSUE THREAD

**Issue by DeepChirp** [EFForg/privacybadger#2962]
#### What is your browser and browser version?
Firefox 124.0.2

#### What is broken and where?
`https://zh.moegirl.org.cn/%E5%87%A0%E4%BD%95%E5%86%B2%E5%88%BA`
The video from Bilibili cannot be played.

#### What is the "culprit" domain?
`api.bilibili.com` and `www.bilibili.com`. If I set these two domains to yellowlist, then the external videos can be played normally.

#### What is your debug output for this domain?
```jsonc
**** ACTION_MAP for bilibili.com
bilibili.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
player.bilibili.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
data.bilibili.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1713075032526
}
broadcast.chat.bilibili.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1713149962658
}
api.bilibili.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "",
  "nextUpdateTime": 1713139174436
}
**** SNITCH_MAP for bilibili.com
```

**Comment by ghostwords** [comment]
Thanks for the report!

We already have a Bilibili widget replacement (e465878) but only for static (not JavaScript API) widgets. The static replacement should continue to work after this fix as we will continue to block `player.bilibili.com`.
