### ISSUE TITLE
Conflicts between the Privacy Badger extension and other extensions

### ISSUE THREAD

**Issue by lunamoth** [EFForg/privacybadger#2969]
If you use the Privacy Badger extension, you can't use the DeepL Pro Translation extension web translation feature. 

This was working fine until recently, but it seems to have been caused by Privacy Badger version 2024.5.30.  

If I disable the Privacy Badger extension, DeepL works fine.

I'm wondering what changes were made that caused this side effect. It would be nice to be able to undo these changes or selectively disable them. 

I want to use both Privacy Badger and DeepL, but I'm forced to choose one. 

DeepL Translate extension
https://chromewebstore.google.com/detail/cofdbpoegempjloogbagkncekinflcnj

#### What is your browser and browser version?

Google Chrome 127.0.6510.4 dev

**Comment by lunamoth** [comment]
It was a mistake on my part.

I enabled the DeepL related domain in Privacy Badger and the problem was solved.

Developers, please don't worry about this issue.

**Comment by ghostwords** [comment]
Hello and thanks for opening an issue!

Unfortunately, I think we should worry. It looks like MV3 content blockers in Chrome can break other extensions. I'll mark this as a duplicate of #2968.
