### ISSUE TITLE
Widget-replacement fails

### ISSUE THREAD

**Issue by M1Aston** [EFForg/privacybadger#2972]
#### What is your browser and browser version?
Firefox
#### What is broken and where?
Rumbe and Disqus widget replacements are working. But I always wan;t these to work normally, so I added them to the permanent exceptions in the Privacy Badger options. But after that the Rumble and Disqus elements are gone.

https://www.thegatewaypundit.com/2024/06/are-you-sad-youre-3-spot-murdering-people/

**Comment by ghostwords** [comment]
Hello!

When you write that you "added them to the permanent exceptions" do you mean that you added those widgets to the list of widgets under "Don't replace the following widgets"? If yes, that just means those widgets will still be blocked but won't ever get replacement placeholders.

Instead, I suggest using the "Always allow on this site" button for the widgets you always want to use on a particular site.

If you really do want a certain widget to always load, you have to search for the relevant domain (or domains) for that widget under the Tracking Domains tab on Privacy Badger options page, and then set the toggles for the widget's domains to yellow or green (if you want the widget to have access to cookies such as for logging in to post new comments).

Let me know if this helped, and if you have any other questions.

**Comment by M1Aston** [comment]
Thank you for your reply.
Yes, it appears I completely misunderstood the PB options.
But I only installed it yesterday, if that's an excuse.  :-)

**Comment by M1Aston** [comment]
ruamopr.com
widget.adcovery.com

I'm trying to block these ads, but they don't show up in the PB list of website trackers..

**Comment by ghostwords** [comment]
All good, welcome to Privacy Badger!

>I'm trying to block these ads, but they don't show up in the PB list of website trackers..

Privacy Badger is meant to be a set-and-mostly-forget privacy extension. It's not ad blocker, and it's not a full featured control panel for everything that gets to load in your browser.

Having written that, if you want, you can enable the "Learn to block new trackers from your browsing" and the "Show domains that don't appear to be tracking you" advanced options in Privacy Badger's settings. You should then see the domains you're looking for in Privacy Badger's popup.

**Comment by M1Aston** [comment]
Alright, I have enabled that option. Lets see what it does.

Thanks again for your help.
