### ISSUE TITLE
Reading manifest: Warning

### ISSUE THREAD

**Issue by TeaganXXX** [EFForg/privacybadger#2987]
Hello PrivacyBadger team, 

So, in Debug Add-ons (about:debugging#/runtime/this-firefox), I came across this (attached screenshot) and was wondering.  

- **What does it mean?** 
- **Is there a fix for this?**
- **Should I be concerned?**  

"Reading manifest: Warning processing storage: An unexpected property was found in the WebExtension manifest."

![Screenshot 2024-06-17 at 21-11-42 Debugging - Runtime _](https://github.com/EFForg/privacybadger/assets/25473141/fbf7846d-2bc6-43ab-ac5f-bf685973b497)

**Comment by ghostwords** [comment]
Hello! This is just a harmless warning, safe to ignore. It's because we use (nearly) the same extensions manifest in all browsers, and there is now way for us to tell Firefox to ignore "unexpected" properties.

Let me know if you have any questions or concerns..

**Comment by TeaganXXX** [comment]
@ghostwords   Okay, sounds good.  Thank you for replying.  👍🏼
