### ISSUE TITLE
Add Edge-specific steps to Open Privacy Badger's extension background page

### ISSUE THREAD

**Issue by marknoble** [EFForg/privacybadger#2993]
#### Description

Currently, our documentation includes specific instructions for setting up background pages for Chrome and Firefox extensions. However, Microsoft Edge, while similar to Chrome, has some differences that need to be addressed to ensure smooth development and deployment of extensions.

#### Rationale

Adding Edge-specific instructions will:
- **Enhance Developer Experience**: Clear, tailored instructions will help developers avoid common pitfalls and streamline the extension development process for Edge.
- **Ensure Compatibility**: Highlighting the differences and necessary adjustments for Edge will ensure that extensions function correctly across all supported browsers.
- **Maintain Consistency**: Providing comprehensive documentation for all major browsers will maintain the high standard of our documentation and support.

#### Proposed Changes

1. **Create a new section** in the documentation dedicated to Edge-specific background page instructions.
2. **Detail the differences** between Edge and Chrome, particularly focusing on any unique requirements or configurations needed for Edge.
3. **Provide examples** and with a screenshot to illustrate the correct setup for Edge.

**Comment by marknoble** [comment]
Here's the suggested code block to add to Find-out-why-Privacy-Badger-is-blocking-a-domain.md

`### In Edge: 
1. Navigate to `edge://extensions`
2. Enable "Developer mode" in the left Extensions pane
3. Click on the "background.html" link in Privacy Badger's box
![Accessing the Edge background page](https://i.imgur.com/vfBAkFf.png)
4. Select the Console tab
`

I wasn't clear on the process for submitting a pull request to the Wiki. It's deprecated, but the info still seems to be used for troubleshooting.

**Comment by ghostwords** [comment]
Thanks for opening an issue!

I recently updated GitHub to stop asking for debugging information (5ad2082c73bb5e48c861a6bd8697e8b4cb0e41a5), because the debug code no longer works in MV3 Chrome, and, more generally, because this information is just not that useful anymore. I don't think anything links to https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain at this point.

The next step here may be to delete the wiki entirely.

**Comment by ghostwords** [comment]
OK, I deactivated the wiki.
