### ISSUE TITLE
Chrome: "The extension failed to load properly. It might not be able to intercept network requests."

### ISSUE THREAD

**Issue by Truesh00ter** [EFForg/privacybadger#2997]
I'm getting a big 'error' message in Chrome (Version 126.0.6478.127 (Official Build) (64-bit)) in the top right corner. Which points towards: 
![chrome_2024-07-12_20-41-18](https://github.com/user-attachments/assets/e4908b69-4038-4973-b43f-ab6e172940ec)

If I then open the extension page and press 'reload', nothing happens:
![chrome_2024-07-12_20-42-30](https://github.com/user-attachments/assets/2900bc9e-8f2b-4136-bbfd-f9f88e97ead5)

<details><summary>I have the Developer mode on ON and if I check out the console of the service worker I see no errors whatsoever:</summary>

![chrome_2024-07-12_20-44-25](https://github.com/user-attachments/assets/97b67c1e-8862-4066-a4a3-8b68f1d2edf7)</details>

I think I've been having this issue for a week or so now, but since I'm lazy I was counting on it that someone else was facing the same issue and would report it ;) but so far this looks more like a Chrome (Chromium) issue than a Privacy Badger. 

If I lookup the error itself I find a broad spectrum of users with issues and 'tips' to solve it. If I specifically search for the error message and specify the last week the most relatable result is: https://www.bleepingcomputer.com/forums/t/798823/adblock-plus-in-google-chrome-failed-to-load-properly/ 

This issue probably gets closed (rightfully) but nevertheless I wanted to document it somewhere for future reference.

**Comment by ghostwords** [comment]
Hello and thank you for opening an issue!

This does sound like a Chrome bug. Does it help to visit `chrome://extensions` and then toggle Privacy Badger off and then back on?

**Comment by Truesh00ter** [comment]
> This does sound like a Chrome bug. Does it help to visit `chrome://extensions` and then toggle Privacy Badger off and then back on?

I've also tried that, but forgot to mention it.

**Comment by Truesh00ter** [comment]
The closest I'm coming to something relatable is this: https://forum.avast.com/index.php?topic=327980.msg1720566#msg1720566 which is also very recent. But that should've been solved by a new virus definition version of Avast which I also have applied. 
![AvastUI_2024-07-12_21-11-19](https://github.com/user-attachments/assets/796b6353-1f47-4137-b890-e7c422ba0ba3)

**Comment by ghostwords** [comment]
Do you have other blockers installed in the same browsers? Could you trying temporarily disabling them in `chrome://extensions` and then toggling Privacy Badger off and then back on?

**Comment by Truesh00ter** [comment]
> Do you have other blockers installed in the same browser as Privacy Badger? Could you try temporarily disabling the other blocker extensions in `chrome://extensions` and then toggling Privacy Badger off and then back on?

I'm also running _uBlock Origin 1.58.0_, I've tried turning it off and on again ;) (while testing PB in between) but that didn't help either.

**Comment by ghostwords** [comment]
Does uninstalling and [reinstalling](https://chromewebstore.google.com/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp) help?

**Comment by Truesh00ter** [comment]
> Does uninstalling and [reinstalling](https://chromewebstore.google.com/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp) help?

It does seem to remove the error (also exported/imported settings). I'll set a reminder and check back tomorrow and post results after a full system restart, thanks so far.

**Comment by Truesh00ter** [comment]
Seems fixed, no more errors. Solved by exporting settings, uninstalling, reinstalling and importing settings.

**Comment by ghostwords** [comment]
This might have been caused by https://issues.chromium.org/issues/342428027, fixed in Chrome 129.
