### ISSUE TITLE
Does PrivacyBadger removes Ping from the link?

### ISSUE THREAD

**Issue by Yawan-1** [EFForg/privacybadger#3001]
As there is a method of using `ping` attribute to `a` link tag to track the user activity of clicking URLs, and some links can contain `ping` attribute which used to create **hyperlink auditing**. Suddenly I went to check if Google does this tracking. But guess what I found, Google does create hyperlink auditing URL to track the clicks of user .
![Screenshot 2024-07-22 010020](https://github.com/user-attachments/assets/e775be40-feff-49cf-9171-c098ed03b871)

So, My question is that Does PrivacyBadger blocks the ping request? If yes, how? I mean, Clearly it does not remove the `ping` attribute from the Page/DOM. Does it block that particular request made specially for ping?(which I think that might be the case)

However, there is also an option in PrivacyBadger settings named `Prevent sites from tracking which links you click ("hyperlink auditing")` specially to block these nasty tricks to track user click activity. If Privacy Badger blocks these pings then **Big Thanks for Precious extension**.

**Comment by ghostwords** [comment]
Hello!

Exactly, [disabling "hyperlink auditing"](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites#hyperlinkauditingenabled) tells your browser to stop using the ping attribute.

Let me know if you have any other questions.
