### ISSUE TITLE
Chrome is blocking redirects?

### ISSUE THREAD

**Issue by o-sho-keh** [EFForg/privacybadger#3005]
chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/data/web_accessible_resources/redirect.html?url=https://any-URL-I-cilck-from-Google-Docs!

pkehgijcmpdhfbdbbnkijodmdjhbjlgp is blocked
This page has been blocked by Chrome
ERR_BLOCKED_BY_CLIENT

**Comment by ghostwords** [comment]
Hello! Which version of Chrome do you have? Is this in Chrome Dev, Beta, or stable?

**Comment by o-sho-keh** [comment]
I'm on Chrome Dev.

Sincerely,
Osioke Ojior, Co-Founder & CEO
One Percent Labs Ltd | Covenda AI
Calendar: https://calendly.com/covenda/ai-and-you

Signal
<https://signal.me/#eu/Zv6rOac-xt8fnSwb5oVdMTluMQHeuZuCbNkZ79oeRNRsBIwuk-RA8IJuXDRYikfr>
 | WhatsApp <https://wa.me/14049394282> | +1 404 939 4282 | +44 7481 006215
<http://voice.google.com/calls?a=nc,%2B2348099991082>
Meet/Skype/Zoom: ***@***.*** | www.covenda.ai

**Comment by ghostwords** [comment]
OK, thank you!

This is the same issue as #3000 and #2998. Either Chrome will fix the bug on their end, or we will release an update with a workaround.

Until then, you can switch to Beta or Stable channels. Or, as a workaround, if you try to navigate to the blocked URL (select the address bar and press Enter), it should load correctly.

Let me know if you have any questions.
