### ISSUE TITLE
Unrecognized manifest key 'browser_specific_settings' for Chromium Microsoft Edge extension

### ISSUE THREAD

**Issue by milldogtjm** [EFForg/privacybadger#3013]
I'm just a user of your extension so I didn't know what to do when I saw this
This issue is for lines 15-23.
 "browser_specific_settings": {
      "gecko": {
         "id": "jid1-MnnxcxisBPnSXQ@jetpack",
         "strict_min_version": "78.0"
      },
      "gecko_android": {
         "strict_min_version": "78.0"
      }
   },
The extension version is 2024.7.17
Microsoft Edge	127.0.2651.105 (Official build) (64-bit) 
Revision	e2354f41f843b7d54f64847c15428307924b774d
Chromium version	127.0.6533.120
Operating system	Windows 11 Version 23H2 (Build 22631.4037) x64
Reproduceable: Don't know cause All I did was enable collect errors on the extension page for the extension.

**Comment by ghostwords** [comment]
Hello! This is just a harmless warning, safe to ignore. You see it because we use (nearly) the same extension manifest in all browsers, and there is no way for us to tell Edge to ignore "unexpected" properties.

Let me know if you have any questions or concerns.

**Comment by milldogtjm** [comment]
Ok I see; then why is geko even showing cause the Edge's browser extensions cannot directly use the Gecko engine nor its modules, and so its browser manifest should have only useable settings or data in it that it can recognize and use.
That error must be showing due to the fact that it recognized the term geko and knows that its incompatible to the Edge browser.

**Comment by ghostwords** [comment]
It's just noise, there is no problem here. It would be better if browsers did not show warnings about unrecognized manifest keys to non-developers.
