### ISSUE TITLE
How to be allow listed?

### ISSUE THREAD

**Issue by Durss** [EFForg/privacybadger#3018]
Hello,
I made an app that consumes Twitch's API, it specifically connects to IRC, Pubsub and Eventsub sockets.
But all those connections are getting killed by privacy badger.

Is there a way to either allow those sockets URLs to pass globally _(would male sense to me)_ or to allow list my tool as it's completely broken because of this?

It's called [twitchat.fr](https://twitchat.fr), I saw that for BTTV you requested their Privacy policies so [here theyr are](https://twitchat.fr/privacyPolicy) just in case.
My app has no tracker, no analytics and no ads so it's a bit concerning everything gets blocked by this plugin.

Thankfully a user made a feedback to let me know that my app didn't work then we realized it was because of privacy badger, but chances are high others just quit it thinking it's just completely broken.

If anything could be done about it that would be much appreciated 🙏

Best regards!

**Comment by ghostwords** [comment]
Hello and thanks for opening an issue! Which Twitch API domains does https://github.com/Durss/Twitchat connect to?

**Comment by Durss** [comment]
Hello !
Here are the socket connections impacted:
wss://pubsub-edge.twitch.tv/
wss://eventsub.wss.twitch.tv/ws
wss://irc-ws.chat.twitch.tv/

**Comment by ghostwords** [comment]
Sounds good! We'll add these to our workaround list within the next few days. Will let you know when this happens.

**Comment by Durss** [comment]
Awesome thank you 🥳

**Comment by ghostwords** [comment]
I added the three twitch.tv subdomains to https://www.eff.org/files/cookieblocklist_new.txt. It takes up to 24 hours for all Privacy Badgers to receive this update. Let me know if you still experience problems afterwards.
