### ISSUE TITLE
Stripe payments seem to fail

### ISSUE THREAD

**Issue by kierank** [EFForg/privacybadger#3041]
Stripe (via shopify?) payments seem to hang because privacy badger blocks access to certain stripe subdomains. This is a bit hard to demonstrate without buying something.

**Comment by ghostwords** [comment]
Hello and thanks for opening an issue!

Which subdomains break functionality when blocked, and where did you run into this problem?

**Comment by kierank** [comment]
I didn't get a chance to save what subdomains were being blocked. But I
tried on numerous occasions to pay and I saw various stripe subdomains
being blocked. Only when disabling privacy badger did the payments go
through.

If I can find a low cost Shopify item to buy I can try again.

**Comment by ghostwords** [comment]
OK, thank you. I made it so that all `stripe.com` subdomains including `stripe.com` itself are now allowed to load, albeit without access to cookies. This should take care of the breakages, once the update makes its way to all Privacy Badger installations within the next 24 hours.
