### ISSUE TITLE
PB blocks nbcnews.com on msnbc.com

### ISSUE THREAD

**Issue by hypercleats** [EFForg/privacybadger#346]
Videos will not play on msnbc.com unless I go into Privacy Badger and manually change nbcnews.com from block (red) to block cookies only (yellow). Why is nbcnews.com considered a "tracker" on msnbc.com? That is where msnbc.com gets much of their content, including all videos.

**Comment by cooperq** [comment]
NBC News gets blocked in this case because it is a 'third-party' to your connection with MSNBC.com. Privacy badger has no way of knowing that these two domains are related, so when you visit msnbc.com and nbcnews loads assets and cookies it looks like a tracker to privacy badger, as it should. If you visit a couple of other domains that also include nbcnews.com  (like today.com for example) it will get blocked. 
I am not comfortable adding nbcnews.com to the greylist, I think this is a good case for users overriding default behavior themselves.

**Comment by hypercleats** [comment]
I respectfully disagree. Privacy Badger has erroneously flagged nbcnews as an unwanted tracker on one of its own websites. False positive. Period. If PB is unable to distinguish between a tracker violating your privacy and a legit content source, then it clearly isn't ready for prime time just yet. The more hassle it is to do simple things on the web like watch the news at a major national news website, the less Privacy Badger is helping. You say you like the idea of users having to manually change Privacy Badger in this case, even as you acknowledge that nbcnews and msnbc share assets as part of the normal functionality of those sites. Since when is PB not concerned with breaking the normal functionality of major websites (particularly when we can easily see that there is no unwanted tracker involved?)

**Comment by hypercleats** [comment]
I see. This issue has been closed. Do you want people to report false positives or not? Looking at this thread, it seems not, since even when you find one and know it is a false positive, you don't want to change anything. Interesting development style, I must admit. I'll check back in six months to see if Privacy Badger's development is continuing this course, or if it has come to its senses and decided that false positives are a bad thing.

**Comment by ghostwords** [comment]
Third-party examples (to help populate `snitch_map`):

- `http://hotair.com/archives/2017/08/14/charlottesville-victims-mother-trump-thank/`
- `https://www.today.com/parents/lady-antebellum-s-hillary-scott-dave-haywood-both-expecting-babies-t115254`

First-party examples:

- `http://www.msnbc.com/msnbc-live`
- `http://www.msnbc.com/all-in/watch/is-trump-s-agenda-already-dead-1014227523981`

Now fixable via #781 / #910.
