### ISSUE TITLE
Privacy Badger blocks the videos on some sites

### ISSUE THREAD

**Issue by Robert51** [EFForg/privacybadger#462]
Privacy Badger blocks the videos on sites such as http://www.france3.fr/direct. Privacy Badger has to be disabled entirely.

**Comment by SwartzCr** [comment]
hi @Robert51, I can't watch videos on that site because I am outside of france
would you be willing to submit a screenshot of the position of the sliders in Privacy Badger on this site (when Privacy Badger is enabled) so that I can debug this issue?

**Comment by KidPluto** [comment]
Not able to play videos on "http://www.france3.fr/direct", even with PB disabled.  Not able to reproduce. Thanks.

**Comment by ghostwords** [comment]
Let me know if this is still an issue. If it is, which browser do you use, and could you provide some specific example pages?
