### ISSUE TITLE
Set DNT:1 via Chrome setting rather than via request header modification?

### ISSUE THREAD

**Issue by qwertie** [EFForg/privacybadger#474]
I noticed right after installing PB that Do-Not-Track was unchecked in the advanced settings in Chrome. The FAQ seems to imply that PB only blocks sites that don't respect DNT, but it doesn't say how PB behaves in case DNT is off. If PB requires DNT to function, I think it should offer to turn on DNT when first installed. In any case, the FAQ should make it clear how PB behaves if DNT is off.

**Comment by pde** [comment]
Privacy Badger should be attaching the DNT: 1 header to outgoing requests separately from that Chrome setting.  If it isn't, that would be a serious bug.

However what we should probably do is set the Chrome DNT setting to "on", and write a hook such that if the user manually turns it off, we can pop up and say "hey, Privacy Badger's theory of relying on dnt-policy.txt to protect you doesn't work if you don't have DNT on".

**Comment by cooperq** [comment]
Chrome is attaching this header in the modify web request callback. We are not able to change the setting in chrome until this patch  lands:
https://codereview.chromium.org/902653002/
bug report for the issue:
https://code.google.com/p/chromium/issues/detail?id=455288

**Comment by cooperq** [comment]
Another interesting related issue: https://code.google.com/p/chromium/issues/detail?id=447978

**Comment by ghostwords** [comment]
The problem with using the WebExtensions API (https://github.com/EFForg/privacybadger/issues/1835#issuecomment-358138820) is that the API is less flexible than doing it ourselves. How would we disable sending DNT on whitelisted sites? How would we send DNT=0 signal if we implement the W3C DNT spec (#1230)? And does the browser API support `navigator.doNotTrack`?
