### ISSUE TITLE
DNT for first party sites

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadger#500]
If a first party site has posted dnt policy, privacy badger should turn off all blocking on that site.

**Comment by michael-oneill** [comment]
As long as the policy includes requirement that any embedded third-parties also comply with DNT policy (at least for the subrequests)

**Comment by rvaneijk** [comment]
@michael-oneill I guess we are talking EFF-DNT policy. This is a specialized policy, based on the EFF, Mozilla, Stanford compromize proposal.

**Comment by michael-oneill** [comment]
Sure, but when you visit a site you probably want tracking third-parties blocked, so its not enough to decide to turn off blocking if the TLBC says they won't track, The third-parties should comply (to at least the same DNT policy) also.

**Comment by rvaneijk** [comment]
The idea is as follows: The DNT policy is machine readable, PB uses a hash to verify the company representations. The company has to use the exact same DNT policy as the EFF-DNT policy otherwise the hash comparison failes

**Comment by michael-oneill** [comment]
I just read it again & it looks like it does (requires third-parties to comply - section 3) anyway, so that's fine. It still has the logical weirdness of calling for immediate discarding of identifiers even if the user is logged in (so they immediately get logged out?), but I pointed that out a while back.

**Comment by rvaneijk** [comment]
I think the project could use some test cases. Passive use of web services and Active use (login required) are very different scenario's.

**Comment by cooperq** [comment]
@michael-oneill It does indeed require that the first party posting this ensure that all third parties are compliant as well or that non-compliant third parties not be loaded for users sending DNT. 
@rvaneijk The project certainly use more test cases, if you want to help us write some we would appreciate it!

**Comment by cooperq** [comment]
@pde we should game out how this feature will work.

**Comment by dhowe** [comment]
I may have missed this elsewhere (apologies if so), but is there any work on verifying that these domains (and their 3rd-parties) are actually following the policy? 

This seems a crucial 2nd step for the mechanism, as now any dishonest site can simply post the policy and track DNT-senders (a sought-after demographic) completely freely, whether or not they may be in violation of law, which will likely depend on the jurisdiction. Potentially still more problematic is the fact that other tools which attempt to respect the EFF's DNT may well disable their usual protections for such sites.

At least (or in the meantime) there could be some way of reporting potential violations... if a user or a dev notices a DNT site (or its 3rd-parties) engaging in tracking

Also, PB itself could be a nice tool for doing some level of checking... For example, if PB notes tracking behavior from a DNT-site, it could 'report' this (with the users consent)

**Comment by michael-oneill** [comment]
It would be good to have a public list of sites that track, how they respond to DNT, whether they support  /.well-known/dnt and/or /.well-known/dnt-policy.txt. It should be easy for a scanner to check for persistent UIDs etc. as PB does. If their sites gets listed unfairly managers could explain how their use of UIDs does not constitute tracking and their explanation then linked to their entry. The FTC Act will enforce honesty in the US as would EU DP law in Europe.

 

There should be a small fee associated with that to cover the costs of running the resource. 

 

If properly done this could become the de-facto compliance spec.

**Comment by rvaneijk** [comment]
@cooperq, @pde, @dhowe could you please post a note here on the status? It would be great to have privacybadger aligned with the w3c .well-known URI.

Best regards,
Rob

**Comment by dhowe** [comment]
The DNT option is now included in AdNauseam >= v3.0 (enabled by default), though it did take a fair bit of engineering to get it all working correctly...

![screen shot 2017-01-14 at 11 25 56 am](https://cloud.githubusercontent.com/assets/737638/21952020/5ccf4872-da4c-11e6-8831-82c2525c3f79.png)

**Comment by cooperq** [comment]
@dhowe that is excellent news! I still need to finish our DNT list implementation based on your feedback so that it has everything needed. Sorry for the delay on this.

**Comment by dhowe** [comment]
No worries -- also happy to give feedback on our process to other adoptees... Here's a bit of press as well: https://freedom-to-tinker.com/2017/01/24/adnauseam-google-and-the-myth-of-the-acceptable-ad/

**Comment by ghostwords** [comment]
Hi @dhowe! I would love to learn more about your process adopting DNT in AdNauseam. A short writeup would be great, or we could have a (Jitsi) call sometime. Let me know what's more convenient.

**Comment by dhowe** [comment]
@ghostwords, not sure how this slipped through the cracks... but still happy to chat whenever
ping me at daniel-at-rednoise-org
