### ISSUE TITLE
Problem with www.n-tv.de and script.ioam.de

### ISSUE THREAD

**Issue by KommX** [EFForg/privacybadger#519]
1. Visit http://www.n-tv.de/
2. For me "script.ioam.de" is blocked.
3. When I want to open some "Bilderserie" (something like a series of images) like "So viel verdienen die reichsten Schauspieler" or "Deutschlands billigste Neuwagen" (see attached screenshot)
   then there appears a dark box, but no content is loaded.
4. Unblocking script.ioam.de solves the problem.

![n-tv de](https://cloud.githubusercontent.com/assets/7859245/9084420/e0d32c7a-3b73-11e5-8ed0-8e17cc28cb8a.png)

**Comment by ghostwords** [comment]
Fixed with 5d7bfb8cb9d9c427e62644cf2a6421aae1a76f6e.
