### ISSUE TITLE
Blocking assets.ubuntu.com breaks https://jujucharms.com

### ISSUE THREAD

**Issue by cmars** [EFForg/privacybadger#612]
I use Privacy Badger and work on Juju... assets.ubuntu.com seems to be getting blocked by default. We're only using it to serve CSS, this degrades our landing site (https://jujucharms.com) pretty bad.

If there's a legitimate privacy concern about assets.ubuntu.com, I'd like to know so that I can improve the situation.

Thanks!

**Comment by cmars** [comment]
FWIW yellow-listing it seems to be fine.

**Comment by KidPluto** [comment]
Going to "https://jujucharms.com/" I see assets.ubuntu.com as a green slider.  So this issue is resolved?  Thanks.

**Comment by cmars** [comment]
Appears to be yellow for https://jujucharms.com/store -- which is fine, it doesn't break our site. I'm happy to close this, thanks for letting me know!
