### ISSUE TITLE
User Filter Setting and Whitelist domains still not working

### ISSUE THREAD

**Issue by ZhuDaHai** [EFForg/privacybadger#617]
I wrote about this bug a few weeks ago and my thread was replied to and closed without me being able to counter. So here it is, again:
I have taobao.com Whitelisted and set to green in User Filter Settings, but it still breaks i.taobao.com

Please, let me know if I'm doing something wrong and let me test and reply before summarily dismissing me as a PEBKAC and closing the thread - like you did last time.

Privacy Badger needs to be able to let the user set a domain (or subdomain) to Ignore and allow all tracking to occur in that domain and its valid subdomains (ie: x.domain.com or y.x.domain.com, not xdomain.com), otherwise people will be disabling hundreds of subdomains on broken sites - or just give up and throw is utility away (like I'm about to do).

![untitled](https://cloud.githubusercontent.com/assets/14084743/10183224/da5af4a0-675f-11e5-8a5c-fe3eb4a7b0e2.png)
![untitled1](https://cloud.githubusercontent.com/assets/14084743/10183225/da5e3dd6-675f-11e5-80e5-e9a9f59a6fab.png)

**Comment by SwartzCr** [comment]
Oh I'm really sorry about that, let's see if we can get it fixed.
first, the whitelisted domains deal with what sites privacy badger works on when you load them as a first party. In short this is the same as the button that says 'disable privacy badger on this site'
So, if you're adding taobao.com subdomains to the whitelist settings, they likely won't do anything unless you're loading those sites directly. Additionally whitelisted domains won't propagate to unspecified subdomains, so setting the top-level taobao.com probably isn't very useful. Again this should have no effect on privacy badger's behavior when they're loaded as third parties.
As for the User Filter Settings, the user override for taobao.com in the options menu should propogate to subdomains. If it's not that's definitely a bug.
Could you do me a favor and let me know what website you're loading where i.taobao.com is being loaded as a third party?
Additionally what version of chrome and privacy badger are you running?

**Comment by ZhuDaHai** [comment]
Here's one I've not yet overridden and so its broken by PB:
https://ju.taobao.com

Chrome: Version 45.0.2454.101 m
Privacy Badger: 2015.8.14

Let me know if you need anything else.

Thanks.

**Comment by narcolepticinsomniac** [comment]
Sounds similar to the issue I posted a week and a half ago: https://github.com/EFForg/privacybadgerchrome/issues/610. It was happening on quite a few sites so I  finally disabled PB. I came to check back hoping I missed a notification, but no such luck. Subdomains that use tons of prefixes are a problem. You could at least allow for manual third party regex url whitelisting.

**Comment by SwartzCr** [comment]
@ZhuDaHai what third party is it that Privacy Badger is blocking there? I don't see any loads from other taobao sites. is it tbcdn?
@narcolepticinsomniac PB does allow you to whitelist for whole domains, if you go to the options menu (the gear icon in the drop down) you can make user settings for the for the toplevel (x.com) instead of specific subdomains (y.x.com) Is that what you wanted?

**Comment by ZhuDaHai** [comment]
Here are two screen prints: taobao.com and ju.taobao.com. You can see what sites PB is blocking in ju.taobao.com even though I have disabled PB for taobao.com (as seen in the first screen shot and the original screen shots from my first post). Now why, after having set the options as I have, does PB still block sites on taobao.com and its sub-domains??
![untitled](https://cloud.githubusercontent.com/assets/14084743/10298000/f4f380b0-6c0b-11e5-8b0d-c615cc2ff84d.png)
![untitled1](https://cloud.githubusercontent.com/assets/14084743/10298007/02d0069a-6c0c-11e5-9ec5-65ffa4776ca5.png)

**Comment by SwartzCr** [comment]
It seems that there are two issues here.
One is that alicdn is getting blocked breaking the page. The other is that there is no way to global whitelist for basedomains.
Problem 1 is solved in PR #630, and problem two was solved in PR #624
once those two PRs are merged, this issue should be resolved. Until then I suggest you go into your settings (click the gear icon) and set alicdn.com to green on the User Filter Settings panel

**Comment by ZhuDaHai** [comment]
Thank you. 
I await the next release so I can whitelist the base domain. :)
I will try green-lighting alicdn.com and report back how that goes.

**Comment by ghostwords** [comment]
I'm going to close this issue as it seems finished; let me know if that's not the case.
