### ISSUE TITLE
Allow rulesets for specific sites

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadger#622]
as referenced in #620 it might be nice to set site specific rules for privacy badger. For example on one site you might want a third party to be set to green, where as on another you might want it to be set to red,

**Comment by sylerner** [comment]
Often, a tracking domain will break only a few - often just one - website.

When viewing a broken web page, clicking on the PrivacyBadger toolbar icon and changing a problematic domain's behavior (e.g., from red to yellow or green) may fix this one web page, but it then globally allows the tracking domain to track activity for all websites that use it, even though the vast majority of them were not broken when the tracking domain was blocked.

Either the default behavior of changing a tracking domain's behavior needs to be limited to the website being viewed, or there needs to be an option whether the change is local the the current website or global to all websites.

Not realizing the current behavior of editing a web pages tracking domain list, I accidentally enabled several heavily used tracking domains to be globally active for my browser until I recently discovered this.

**Comment by ghostwords** [comment]
We should focus on making Privacy Badger an install-and-forget extension. Customizing sliders is already a non-mainstream/power user feature. Empowering slider customization seems like going down the wrong track. Closing as "wontfix".
