### ISSUE TITLE
PrivacyBadger shows IDs of other installed Google Chrome extensions, and can block them.

### ISSUE THREAD

**Issue by BbaassTMH** [EFForg/privacybadger#625]
I originally wrote up a bug report about PrivacyBadger messing with AdBlockPlus.
However, with some more testing, I came to the conclusion that I simply (manually) blocked a "tracker" I shouldn't have.
## Original bug report:

_**PrivacyBadger prevents ABP's "block element" from working correctly**_

_I use AdBlockPlus to block more than just ads._
_I have had problems with it for a long time, but since I just got a new laptop, I installed Chrome and extensions including Privacy Badger and ABP._
_Still the same problem I had on my old laptop: I can't use ABP's "Block element" function anymore.
I can still click the ABP icon and click "Block element", but when I click on an element on the page, the confirmation popup doesn't appear._

_After some trial and error, I found out that if I set Privacy Badger to "Disable for this site", ABP's "Block element" function worked correctly._

_Chrome version 44.0.2403.157_
_ABP version 1.9.3_
_Privacy Badger version 2015.8.14_

---

As I was about to click "Submit new issue", I thought of one more thing I could try: try to block an element on a website that I know has no trackers that Privacy Badger can interact with.
As soon as I clicked the element I wanted to block, ABP's confirmation popup briefly flashed on the screen, and suddenly Privacy Badger found a tracker it then blocked: cfhdojbkjhnklbpkdaibdccddilifddb.
Which is Google Chrome's extension ID for AdBlockPlus.

I assume I accidentally blocked that "tracker" at some point, because it didn't look like a proper URL.

The reason I am still submitting a bug report is because I think PrivacyBadger shouldn't be able to block other Chrome extensions: it probably shouldn't even list them in the dropdown menu.
Even if there is another extension that somehow tracks things, it would have been manually added to Google Chrome by the user, no?

**Comment by cooperq** [comment]
I agree, privacy badger shouldn't be blocking other chrome extensions. We should look into making sure that this doesn't happen.
