### ISSUE TITLE
https://www.adultswim.com/login/

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#634]
https://www.adultswim.com/login/

gigya prevents login form from loading...
This is getting out of hand.

**Comment by cooperq** [comment]
I'm pretty uncomfortable with putting gigya on the cookie block list. They are absolutely a tracker. 
On the other hand preventing logins on sites is pretty bad. I wonder how common it is that gigya is a requirement for logging in to a site.

**Comment by terrorist96** [comment]
I don't disagree with your sentiment. It didn't require gigya for the last 12 years of its existence, but now it does. I made a complaint about it:
http://boards.adultswim.com/t5/AdultSwim-Com-and-Site-Support/Login-requires-being-tracked-by-Gigya/m-p/71556945#U71556945

Hopefully they'll consider removing it.

**Comment by terrorist96** [comment]
Why is this bring closed? Was a resolution reached?

**Comment by terrorist96** [comment]
@cooperq

**Comment by cooperq** [comment]
I closed it because we are unlikely to add gigya to the whitelist so there is nothing we can do about it. I think that the workaround is for users to allow gigya individually if they want to log into adult swim.

**Comment by terrorist96** [comment]
A suggestion would be to offer a pop up notification when a user accesses that login page (similar to the notification given for being tracked by Disqus.
Thanks!

**Comment by terrorist96** [comment]
So any thoughts on how we can prevent tracking without leaving people confused as to why they can't log in?

**Comment by cooperq** [comment]
I think that your above suggestion is a great one (having a popup). I will try to get to it soon.

**Comment by terrorist96** [comment]
The website has been updated. Now, the login button isn't even visible. Have to make all of gigya green to be able to log in.

**Comment by cooperq** [comment]
I have assigned this to myself and will work on adding gigya to the list.

**Comment by terrorist96** [comment]
Anything new?

**Comment by terrorist96** [comment]
#400 ?

**Comment by ghostwords** [comment]
The login form itself is powered by Gigya ... I don't think surrogates can help here.

**Comment by terrorist96** [comment]
Boards have been shut down. This issue is moot.
