### ISSUE TITLE
kimsufi.com payment page depends on ovh.com resources

### ISSUE THREAD

**Issue by geofft** [EFForg/privacybadger#636]
I think you can reproduce this publicly without logging in (and without actually paying, of course):
- Visit https://us.kimsufi.com/cgi-bin/order/renew.cgi
- Enter `ns504970.ip-198-27-64.net` (my server)
- Select some renewal period
- Look for the icons under "Payment by card"

Privacy Badger, for me, has a red slider for www.ovh.com, but it seems at least images from that site need to be loaded so I can click on the links. Kimsufi is a brand of OVH (same organization), so there's no loss to privacy in allowing cross-origin requests between kimsufi.com and ovh.com.

I'd imagine the same thing is true of soyoustart.com, which is also an OVH brand. They also have a payment page at the corresponding URL.

**Comment by michael-oneill** [comment]
This why there is a same-party property (array of domain names) in the DNT Tracking Status Resource. It allows a site to declare what embedded “third-parties” are in face managed by the same Data Controller as the first-party. Not that anyone implements it yet, but if PB supported that then they might start to.

 

Mike

**Comment by cooperq** [comment]
@geofft moving the slider to yellow or green for the blocked domain should solve this issue. 
@michael-oneill it seems like the same-party property could be pretty easily abused by advertising partners (requiring first parties to add them to the same party array, etc) What provisions are in place to stop this?

**Comment by theel0ja** [comment]
Kimsufi and SoYouStart are OVH's brands, so this should be in MDFP list.
