### ISSUE TITLE
Privacy Badger website indicates that Avast does not work with it

### ISSUE THREAD

**Issue by nitrocalcite** [EFForg/privacybadger#720]
I have both the Avast antivirus extension and PrivacyBadger installed, and have never had any issues with it.  Are others still having issues?  

Per the last question on this link: https://www.eff.org/privacybadger

**Comment by cooperq** [comment]
Not sure, but there were some issues installing privacy badger on firefox when people had the avast browser extension. Leaving it up for now.

**Comment by ghostwords** [comment]
We should remove the Avast reference from the FAQ, as I haven't heard anything about this in the past year.

**Comment by ghostwords** [comment]
Removed as of today.
