### ISSUE TITLE
Handle privacy related settings in a more holistic manner

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadger#740]
Via @sjalex re: cb8ddfdfcf019d600e68e67b76cb1839731c34a1

> This commit closed #243 but there are a number of concerns raised there that it doesn't address.
> It made no change to how alternateErrorPagesEnabled setting is handled, nor provided any option to toggle it in the preferences. There are a handful of other settings #243 mentioned that also aren't addressed here.
> To me, it makes a lot of sense to override these settings by default. Without having some inbuilt means of modifying the overridden settings, though, I lose a lot of control over how I want my browser to behave.
> Could you please revisit this issue with a holistic approach to managing all the privacy-related settings centrally, and with a particular eye to giving users some control over PB's behavior around chrome settings?
> Thanks very much!

**Comment by cooperq** [comment]
>

**Comment by ghostwords** [comment]
From a support email:
> I noticed that I cannot activate web services to resolve navigation errors
> in chrome and that the extension is blocking it.
>
> Is there any way to activate it without removing the extension? If not I
> think I will remove it.
