### ISSUE TITLE
UX: Missing Regex/Wildcard Support

### ISSUE THREAD

**Issue by Exagram** [EFForg/privacybadger#741]
I blacklist "a.spambot.net" but when I visit another site I have to blacklist "b.spambot.net". Is there a way to have finer granularity (such as with regex/wildcards)?

**Comment by cooperq** [comment]
You should be able to just blacklist spambot.net in the options page. Does that not work?

**Comment by Exagram** [comment]
Now I wish I could have saved some screenshots. No, because Privacy Badger lists a.spambot.net, b.spambot.net, but never the root domain. Otherwise, do let me know how.

**Comment by cooperq** [comment]
if you click the gear icon in privacy badger it should list the root domain of spambot.net

**Comment by Exagram** [comment]
You mean Gear Option > User Filter Settings? I only see rules like: "secure.adnxs.com". There is no ability to set "adnxs.com" anywhere. Can you provide a screenshot?

**Comment by cooperq** [comment]
Hmm, that is strange indeed! I definitely see a rule for adnxs.com in User Filter Settings in my copy of privacy badger. Can you send me a screenshot of the relevant section of your Filter Settings? Are there any top level domains in there, or is it all subdomains?

**Comment by Exagram** [comment]
Screenshot: https://i.imgsafe.org/b9b5d25.png. Entries without roots listed are: 6sc.co, adnxs.com, adroll.com, etc.

**Comment by cooperq** [comment]
hmm interesting. I suspect that this is in some way related to the fact that you manually blocked those subdomains, perhaps privacy badger never was able to put adnxs.com into its database. You will notice that some top level domains are there though adzerk for example.
I think that the proper enhancement here is to make sure that the base domain always shows up in the list of options.

**Comment by ghostwords** [comment]
Closing as stale.
