### ISSUE TITLE
Increasing number of CDNs blocked

### ISSUE THREAD

**Issue by blitzd** [EFForg/privacybadger#746]
I'm finding that privacy badger is blocking an increasing number of CDNs. Some specific instances:

shell-s2-portal.azurecomcdn.net (breaks https://portal.azure.com/)
cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css

The bootstrap CSS one is one that I have used for a while in my own development, and one day privacy badger just started blocking it. I know that I can go in and set the slider for this specific domain, but this seems to be a problem that I am running into with more and more CDN domains and I'm wondering if there's not a bigger issue here. 

Issue https://github.com/EFForg/privacybadgerchrome/issues/326 could be related.

**Comment by cooperq** [comment]
So a cdn could get blocked if it is setting cookies keyed to the cdn domain, setting local storage keyed to the cdn domain or if it is doing things that look like canvas fingerprinting. It's possible that these CDNs are configured in such a way that they look to privacy badger like they are tracking. It's hard to tell without testing though. Can you give me an example page where rawgit cdn is blocked?

**Comment by blitzd** [comment]
@cooperq Sorry for the slow response. An example is the starter project for react/redux here:

https://github.com/StephenGrider/ReduxSimpleStarter

It uses bootstrap from the 2nd url above in the index.html [here](https://github.com/StephenGrider/ReduxSimpleStarter/blob/master/index.html#L5)

Some additional examples,

assets.rfdcontent.com (breaks css on http://forums.redflagdeals.com/)
assets0.uvcdn.com (breaks css on any uservoice subsite)
assets1.uvcdn.com (breaks css on any uservoice subsite)

I'm basically finding that privacy badger is becoming unusable due to all of these things being detected as issues and the lack of a method to clear the User Filter Settings list.

**Comment by cooperq** [comment]
@blitzd I will look into these, you can always unblock specific CDNs as a temporary measure. I'm not sure I understand how clearing the User Filter Settings list would help in this situation. Could you clarify that for me?

**Comment by ghostwords** [comment]
At least some of the CDNs in this report should have been fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into similar issues again with the new version.
