### ISSUE TITLE
Blocking chat script

### ISSUE THREAD

**Issue by jvenema** [EFForg/privacybadger#752]
Hey guys!

We just encountered the fact that privacybadger is blocking our script (www.apexchat.com, www.apexchat.net, livechat.us). We do set cookies, but using JS and for the current domain only - no tracking across domains. We just need to know who the visitor is to a) determine the state of the "would you like to chat" functionality and b) determine (only for the specific site) if the visitor is returning so we can pick up the discussion where it left off. Seems like we're still being blocked though.

We would like to be privacy minded here, so if there's a change we need to make to ensure we're in line with your privacy guidelines, or if we can be added to your yellow list, please let me know!

Thanks.

**Comment by ghostwords** [comment]
Hi @jvenema, would your company be interested in adopting the [EFF Do Not Track policy](https://www.eff.org/dnt-policy) on its chat widget domains?

**Comment by ghostwords** [comment]
Closing for now.
