### ISSUE TITLE
Fasterize FEO/CDN is blocked

### ISSUE THREAD

**Issue by stefounet** [EFForg/privacybadger#774]
Hi,

First, thank you for this tool.
[Fasterize](http://www.fasterize.com) is a FEO/CDN tool ala Cloudflare (FEO = Front End Optimization). When using our service, websites HTML code is rewritten on the fly to apply webperf best practices (inlining, lazyloading, defering, sharding, etc...). For easier configuration, sharded domains for every website are all using the same frz.io suffix.
We also have a beacon on this domain that will collect navigation timing for each page (RUM=Real User Monitoring). We do not track users and it'll never be our business model.

We have users complaining that Privacy Badger is blocking our domain and it breaks some pages.
We don't use cookie on such domains as this is one of webperf rules, using cookieless domain, so we're quite surprised.
Should we submit a PR to be in the yellow list as other CDN?

**Comment by cooperq** [comment]
hi,
Sorry that we are blocking your cdn. Please do submit a pull request. 

It is indeed suprising that your domain is being blocked if it is not setting cookies. Perhaps it is using local storage or doing something with the canvas that looks like tracking to privacy badger? Could you send me an example domain that uses fasterize so I can look into this?

**Comment by stefounet** [comment]
We didn't succeed in repeating the case seen by one of our user although we've installed Privacy Badger and surfed on fasterized websites.
Here's the website where the issue arose: http://www.yellowkorner.com

We submit a PR asap.

**Comment by ghostwords** [comment]
Hi @stefounet, would Fasterize be interested in adopting the [EFF Do Not Track policy](https://www.eff.org/dnt-policy) on its CDN domains? Privacy Badger's cookie block list is more of a workaround for when nothing else applies.

**Comment by stefounet** [comment]
Let me read this quietly even if we agree on the fact!
