### ISSUE TITLE
Make widget replacement and MDFP (multi-domain first parties) definitions remotely updateable (same as yellowlist and DNT  hashes)

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadger#795]
We should store the social widget list online so it can be quickly updated, we should also inform all of our partners when this change is completed.

**Comment by ghostwords** [comment]
Can't/shouldn't do this to surrogate script definitions though, as those are executable code (extra security risks, violates extension store policies).

**Comment by cowlicks** [comment]
@ghostwords What part of the policy does it violate? There is the "make as much of your code visible in the package as you can" ([link](https://developer.chrome.com/webstore/program_policies#content_policies)), but I think we would meet this requirement if we keep the surrogates public and bundle them with the extension.

And it should be secure, as long as we update surrogates over https from eff.org.

**Comment by ghostwords** [comment]
It's just my experience from Ghostery, I don't have a link/reference handy.

**Comment by ghostwords** [comment]
I think the security risks part is from the perspective of Chrome Web Store/AMO. Surrogate script definitions are executable code. If surrogate scripts are allowed to be updated outside of the normal extension update process, it means allowing remote executable code updates, which compromises the extensions gallery's review process. Again, my experience from the past, but I don't see why this would change.

**Comment by ghostwords** [comment]
Can revisit when this becomes more important.

**Comment by ghostwords** [comment]
For more on script surrogates and AMO, see the following uBlock Origin commit: https://github.com/gorhill/uBlock/commit/126110c9a0a0630cd556f5cb215422296a961029
