### ISSUE TITLE
The problem with wired.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#804]
As of right now, the following cause wired to throw an anti-adblock message:

`pagead2.googlesyndication.com`

I'll expand on this as I find more. Due to the nature of Privacy Badger blocking different things on different Chrome profiles (since it hasn't learned yet), tracking down everything that triggers the warning will take some time.

**Comment by cooperq** [comment]
I think that the real solution here involves talking to wired and figuring it out together.

**Comment by terrorist96** [comment]
Good luck with that. They seem deadset to ruin the experience of anyone with any adblocker or privacy related extension.

**Comment by terrorist96** [comment]
Did you try talking to wired?

**Comment by cooperq** [comment]
These things take time...

**Comment by ccoenen** [comment]
Thanks for documenting this, putting `pagead2.googlesyndication.com` on "no cookie" solved the problem for me, too! I don't mind them showing me ads (after all, they have some of the less annoying ads) I _do_ mind 22 tracking systems watching me reading their article.

**Comment by cooperq** [comment]
Nice workaround! Thanks for catching that. It makes sense why wired would block something blocking that. I wonder if this could be solved with #400? We should look into it.

**Comment by floe** [comment]
Hm, any news on that? I don't actually have `pagead2.googlesyndication.com` in my block list, but Wired still annoys me with the blocker...

**Comment by Q11x** [comment]
@floe I changed `securepubads.g.doubleclick.net` to no cookie and it worked after a site refresh.

**Comment by floe** [comment]
Thanks, that did the trick.

**Comment by cooperq** [comment]
Hmm, perhaps I should consider a way to give the user an option to automatically do that when they visit wired.com, would have to consider how best to implement this. Any ideas?

**Comment by terrorist96** [comment]
#400?

**Comment by ghostwords** [comment]
Let me know if this is still an issue.

**Comment by terrorist96** [comment]
@ghostwords It's still an issue. Please reopen.

On a test profile with only PB active (I also sent the error report via the "did pb break this site" button just a few minutes ago; can you take a look?):
![image](https://cloud.githubusercontent.com/assets/12802056/25687740/f665b606-3046-11e7-9465-9b0f1e3aa108.png)

**Comment by alanton** [comment]
I have tried to reproduce this without success. Is it possible that this message is being triggered by another extension?

**Comment by terrorist96** [comment]
Yeah I'm having trouble reproducing it now too. Though it was confirmed earlier that having only PB was enough to trigger it (see the post above yours). Something must have changed on wired's side.

**Comment by ccoenen** [comment]
Yes, it's no longer an issue for me, too.
They still use a ton of trackers and ad networks (and other third party technologies), but I don't get the overlay any more.
