### ISSUE TITLE
cityam.com anti-adblock

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#822]
http://www.cityam.com/239921/labour-party-accused-of-becoming-a-home-for-vicious-anti-semites

`ad.crwdcntrl.net`
`securepubads.g.doubleclick.net`
and
`partner.googleadservices.com`
need to be on the yellowlist, otherwise you get an anti-adblock detection, which blocks the article.

**Comment by cooperq** [comment]
I'm not yellowlisting tracking ad servers just to fix anti adblock messages. That would compromise the core principal of privacy badger. These companies instead need to stop showing tracking ads.

**Comment by terrorist96** [comment]
You can't do the surrogate thing where you just give it fake info? EasyList/EasyPrivacy filter lists in adblock plus have worked around the issue.

**Comment by terrorist96** [comment]
@cooperq no script surrogate?

**Comment by cooperq** [comment]
No script surrogates yet, they will be tracked in #400

**Comment by terrorist96** [comment]
@ghostwords

**Comment by ghostwords** [comment]
This one requires a site-level surrogate, in order to counter an inline script. Similar to #1044 in this way.

**Comment by ghostwords** [comment]
Sounds related to #1596.

**Comment by andresbase** [comment]
I can't duplicate this, are you still getting the message?

**Comment by terrorist96** [comment]
Nope.
