### ISSUE TITLE
http://www.recipe.com broken by gigya

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#823]
http://www.recipe.com/

`cdns.gigya.com`

yellowlist, otherwise no images load.

**Comment by terrorist96** [comment]
@ghostwords still need to move gigya to yellow to fix it.

**Comment by terrorist96** [comment]
I have the December 8 update though.

![capture](https://cloud.githubusercontent.com/assets/12802056/21151272/dbd1380a-c12f-11e6-8d4f-245faa3ca8b3.PNG)

Also, the new update is causing conflicts with Ghostery.

`Warning:
This extension failed to redirect a network request to data:application/javascript;base64,dmFyIHVyY2hpblRyYWNrZXI9ZnVuY3Rpb24oKXt9LF9nYXE9e3B1c2g6ZnVuY3Rpb24oKXt0cnkge2lmKGFyZ3VtZW50c1swXVswXT09J19saW5rJyl3aW5kb3cubG9jYXRpb24uaHJlZj1hcmd1bWVudHNbMF1bMV19Y2F0Y2goZXIpe319fSxfZ2F0PXtfY3JlYXRlVHJhY2tlcjpmdW5jdGlvbigpe30sIF9nZXRUcmFja2VyOmZ1bmN0aW9uKCl7cmV0dXJue19fbm9TdWNoTWV0aG9kX186ZnVuY3Rpb24oKXt9LF9saW5rOmZ1bmN0aW9uKG8pe2lmKG8pbG9jYXRpb24uaHJlZj1vO30sX2xpbmtCeVBvc3Q6ZnVuY3Rpb24oKXtyZXR1cm4gdHJ1ZTt9LF9nZXRMaW5rZXJVcmw6ZnVuY3Rpb24obyl7cmV0dXJuIG87fSxfdHJhY2tFdmVudDpmdW5jdGlvbigpe319fX07Y3hBcGk9e3NldENvb2tpZVBhdGg6ZnVuY3Rpb24oKXt9LGNob29zZVZhcmlhdGlvbjpmdW5jdGlvbigpe319dmFyIF9nYXQ9e19nZXRUcmFja2VyQnlOYW1lOiBmdW5jdGlvbigpe190cmFja0V2ZW50OiBmdW5jdGlvbigpe319fTs= because another extension (Privacy Badger) redirected it to data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIG5vb3BmbiA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CgkvLwoJdmFyIEdhcSA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CglHYXEucHJvdG90eXBlLk5hID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5PID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5TYSA9IG5vb3BmbjsKCUdhcS5wcm90b3R5cGUuVGEgPSBub29wZm47CglHYXEucHJvdG90eXBlLlZhID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fY3JlYXRlQXN5bmNUcmFja2VyID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fZ2V0QXN5bmNUcmFja2VyID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fZ2V0UGx1Z2luID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5wdXNoID0gZnVuY3Rpb24oYSkgewoJCWlmICggdHlwZW9mIGEgPT09ICdmdW5jdGlvbicgKSB7CgkJCWEoKTsgcmV0dXJuOwoJCX0KCQlpZiAoIEFycmF5LmlzQXJyYXkoYSkgPT09IGZhbHNlICkgewoJCQlyZXR1cm47CgkJfQoJCS8vIGh0dHBzOi8vdHdpdHRlci5jb20vY2F0b3ZpdGNoL3N0YXR1cy83NzY0NDI5MzAzNDUyMTgwNDgKCQkvLyBodHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9hbmFseXRpY3MvZGV2Z3VpZGVzL2NvbGxlY3Rpb24vZ2Fqcy9tZXRob2RzL2dhSlNBcGlEb21haW5EaXJlY3RvcnkjX2dhdC5HQV9UcmFja2VyXy5fbGluawoJCWlmICggYVswXSA9PT0gJ19saW5rJyAmJiB0eXBlb2YgYVsxXSA9PT0gJ3N0cmluZycgKSB7CgkJCXdpbmRvdy5sb2NhdGlvbi5hc3NpZ24oYVsxXSk7CgkJfQoJCS8vIGh0dHBzOi8vZ2l0aHViLmNvbS9nb3JoaWxsL3VCbG9jay9pc3N1ZXMvMjE2MgoJCWlmICggYVswXSA9PT0gJ19zZXQnICYmIGFbMV0gPT09ICdoaXRDYWxsYmFjaycgJiYgdHlwZW9mIGFbMl0gPT09ICdmdW5jdGlvbicgKSB7CgkJCWFbMl0oKTsKCQl9Cgl9OwoJLy8KCXZhciB0cmFja2VyID0gKGZ1bmN0aW9uKCkgewoJCXZhciBvdXQgPSB7fTsKCQl2YXIgYXBpID0gWwoJCQknX2FkZElnbm9yZWRPcmdhbmljIF9hZGRJZ25vcmVkUmVmIF9hZGRJdGVtIF9hZGRPcmdhbmljJywKCQkJJ19hZGRUcmFucyBfY2xlYXJJZ25vcmVkT3JnYW5pYyBfY2xlYXJJZ25vcmVkUmVmIF9jbGVhck9yZ2FuaWMnLAoJCQknX2Nvb2tpZVBhdGhDb3B5IF9kZWxldGVDdXN0b21WYXIgX2dldE5hbWUgX3NldEFjY291bnQnLAoJCQknX2dldEFjY291bnQgX2dldENsaWVudEluZm8gX2dldERldGVjdEZsYXNoIF9nZXREZXRlY3RUaXRsZScsCgkJCSdfZ2V0TGlua2VyVXJsIF9nZXRMb2NhbEdpZlBhdGggX2dldFNlcnZpY2VNb2RlIF9nZXRWZXJzaW9uJywKCQkJJ19nZXRWaXNpdG9yQ3VzdG9tVmFyIF9pbml0RGF0YSBfbGluayBfbGlua0J5UG9zdCcsCgkJCSdfc2V0QWxsb3dBbmNob3IgX3NldEFsbG93SGFzaCBfc2V0QWxsb3dMaW5rZXIgX3NldENhbXBDb250ZW50S2V5JywKCQkJJ19zZXRDYW1wTWVkaXVtS2V5IF9zZXRDYW1wTmFtZUtleSBfc2V0Q2FtcE5PS2V5IF9zZXRDYW1wU291cmNlS2V5JywKCQkJJ19zZXRDYW1wVGVybUtleSBfc2V0Q2FtcGFpZ25Db29raWVUaW1lb3V0IF9zZXRDYW1wYWlnblRyYWNrIF9zZXRDbGllbnRJbmZvJywKCQkJJ19zZXRDb29raWVQYXRoIF9zZXRDb29raWVQZXJzaXN0ZW5jZSBfc2V0Q29va2llVGltZW91dCBfc2V0Q3VzdG9tVmFyJywKCQkJJ19zZXREZXRlY3RGbGFzaCBfc2V0RGV0ZWN0VGl0bGUgX3NldERvbWFpbk5hbWUgX3NldExvY2FsR2lmUGF0aCcsCgkJCSdfc2V0TG9jYWxSZW1vdGVTZXJ2ZXJNb2RlIF9zZXRMb2NhbFNlcnZlck1vZGUgX3NldFJlZmVycmVyT3ZlcnJpZGUgX3NldFJlbW90ZVNlcnZlck1vZGUnLAoJCQknX3NldFNhbXBsZVJhdGUgX3NldFNlc3Npb25UaW1lb3V0IF9zZXRTaXRlU3BlZWRTYW1wbGVSYXRlIF9zZXRTZXNzaW9uQ29va2llVGltZW91dCcsCgkJCSdfc2V0VmFyIF9zZXRWaXNpdG9yQ29va2llVGltZW91dCBfdHJhY2tFdmVudCBfdHJhY2tQYWdlTG9hZFRpbWUnLAoJCQknX3RyYWNrUGFnZXZpZXcgX3RyYWNrU29jaWFsIF90cmFja1RpbWluZyBfdHJhY2tUcmFucycsCgkJCSdfdmlzaXRDb2RlJwoJCV0uam9pbignICcpLnNwbGl0KC9ccysvKTsKCQl2YXIgaSA9IGFwaS5sZW5ndGg7CgkJd2hpbGUgKCBpLS0gKSB7CgkJCW91dFthcGlbaV1dID0gbm9vcGZuOwoJCX0KCQlvdXQuX2dldExpbmtlclVybCA9IGZ1bmN0aW9uKGEpIHsKCQkJcmV0dXJuIGE7CgkJfTsKCQlyZXR1cm4gb3V0OwoJfSkoKTsKCS8vCgl2YXIgR2F0ID0gZnVuY3Rpb24oKSB7CgkJOwoJfTsKCUdhdC5wcm90b3R5cGUuX2Fub255bWl6ZUlQID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5fY3JlYXRlVHJhY2tlciA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUuX2ZvcmNlU1NMID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5fZ2V0UGx1Z2luID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5fZ2V0VHJhY2tlciA9IGZ1bmN0aW9uKCkgewoJCXJldHVybiB0cmFja2VyOwoJfTsKCUdhdC5wcm90b3R5cGUuX2dldFRyYWNrZXJCeU5hbWUgPSBmdW5jdGlvbigpIHsKCQlyZXR1cm4gdHJhY2tlcjsKCX07CglHYXQucHJvdG90eXBlLl9nZXRUcmFja2VycyA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUuYWEgPSBub29wZm47CglHYXQucHJvdG90eXBlLmFiID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5oYiA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUubGEgPSBub29wZm47CglHYXQucHJvdG90eXBlLm9hID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5wYSA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUudSA9IG5vb3BmbjsKCXZhciBnYXQgPSBuZXcgR2F0KCk7Cgl3aW5kb3cuX2dhdCA9IGdhdDsKCS8vCgl2YXIgZ2FxID0gbmV3IEdhcSgpOwoJKGZ1bmN0aW9uKCkgewoJCXZhciBhYSA9IHdpbmRvdy5fZ2FxIHx8IFtdOwoJCWlmICggQXJyYXkuaXNBcnJheShhYSkgKSB7CgkJCXdoaWxlICggYWFbMF0gKSB7CgkJCQlnYXEucHVzaChhYS5zaGlmdCgpKTsKCQkJfQoJCX0KCX0pKCk7Cgl3aW5kb3cuX2dhcSA9IGdhcS5xZiA9IGdhcTsKfSkoKTs=.`

**Comment by ghostwords** [comment]
Right, so this and all the other [recent fixes](https://github.com/EFForg/privacybadger/compare/release-2016.12.8...master) will be in the next update.

**Comment by ghostwords** [comment]
As far as the redirect conflict, please see https://github.com/EFForg/privacybadger/issues/1032#issuecomment-265774776. I updated our Google Analytics surrogate (the encoded string you pasted) to exactly match uBlock's, but Ghostery uses yet another definition.

**Comment by cooperq** [comment]
Yep nothing we can do about that other than file a bug with chrome for their bad UI
