### ISSUE TITLE
files.barcelonastream.com breaks layout

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#831]
files.barcelonastream.com needs to be on yellowlist. Having it on the redlist will break the page.

http://motorsports-stream.com/live/formula1-live-stream/channel-1/
http://nba-stream.com/live/wizards-live-stream/channel-1/

**Comment by KidPluto** [comment]
"files.barcelonastream.com" gives me a 403.  The other two links work for me.  Thanks.

**Comment by terrorist96** [comment]
`files.barcelonastream.com` is the tracker that PB blocks on the two mentioned sites, not the site with the issue itself.

**Comment by terrorist96** [comment]
http://nba-stream.com/next-games/

`files.barcelonastream.com` breaks images
