### ISSUE TITLE
Privacy Badger gets full reset every time I clear the browser cache

### ISSUE THREAD

**Issue by vestkystdreng** [EFForg/privacybadger#840]
Every time I clear the browser cache, in fact at every when closing the browser, all Privacy Badger data/settings are getting deleted too. This happens because Privacy Badger is storing it settings in the cache alongside with ordinary cache data AND cache persistent tracking methods.

The cache has to be deleted regularly to ensure privacy, otherwise it would make no sense to talk about privacy/tracking protection at all.

So please, change the location for the settings, otherwise Pricacy Badger makes no sense to install.

Cheers, Peter

**Comment by ghostwords** [comment]
Hi Peter, is this still an issue for you? If so, which browser do you use and which other addons do you have installed? I am particularly interested in any addons or programs that clear caches/histories.

**Comment by ghostwords** [comment]
Closing, but let me know if this is still an issue.
