### ISSUE TITLE
Remove outbound link tracking on Google, Facebook, Twitter, and other major origins

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadger#85]
When they track outbound link-clicks, Google and Facebook are violating the DNT principle that they shouldn't collect your reading history on unrelated sites.  We should fix this for the user.  There are some existing scripts/extensions to do this:

For Google:
http://userscripts.org/scripts/review/98394
https://chrome.google.com/webstore/detail/remove-google-redirects/ccenmflbeofaceccfhhggbagkblihpoh
https://addons.mozilla.org/en-US/firefox/addon/google-no-tracking-url/

For Facebook:
https://chrome.google.com/webstore/detail/facebook-link-tracking-di/omkknlonjipnallbpmboackchhnocedb

We can incorporate code from these extension(s).

**Comment by cowlicks** [comment]
From offline discussions, the first part will unwrapping twitter links. Specifically those in tweets.  Here is an example element:
```
<a
    href="https://t.co/U4YMYoAUCK"
    rel="nofollow noopener"
    dir="ltr"
    data-expanded-url="https://www.supremecourt.gov/opinions/16pdf/16-341_8n59.pdf"
    class="twitter-timeline-link" target="_blank"
    title="https://www.supremecourt.gov/opinions/16pdf/16-341_8n59.pdf"
>
  <span class="tco-ellipsis"></span>
  <span class="invisible">https://www.</span>
  <span class="js-display-url">supremecourt.gov/opinions/16pdf</span>
  <span class="invisible">/16-341_8n59.pdf</span>
  <span class="tco-ellipsis"><span class="invisible">&nbsp;</span>…</span>
</a>
```
So we can pull the real url (`https://www.supremecourt.gov/opinions/16pdf/16-341_8n59.pdf`) from either the `data-expanded-url` or `title` attribute. It sounds like the former is more appropriate. Then swap it with the link in the `href` attribute.

**Comment by pde** [comment]
Another relevant project:

https://github.com/diegocr/CleanLinks

**Comment by jawz101** [comment]
fwiw, in regards to example add-ons and compatibility with FFox for Android:
I don't know if this is relevant to url cleaning techniques but

Wladimir Palant's Google Search Link Fix add-on does not clean Google links from the mobile browser
https://github.com/palant/searchlinkfix

Don't Track Me Google add-on does strip the google url code out
https://github.com/Rob--W/dont-track-me-google

**Comment by ghostwords** [comment]
Twitter being worked on in #1392.

**Comment by ghostwords** [comment]
Facebook in #1993.

**Comment by ghostwords** [comment]
Google in #2016.

**Comment by yy6677** [comment]
Y como hacer esto?

**Comment by ghostwords** [comment]
@yy6677 Twitter and Facebook components have already been released, Google should be next.
