### ISSUE TITLE
my-netdata.io should not be blocked

### ISSUE THREAD

**Issue by ktsaou** [EFForg/privacybadger#850]
Hi,

I am the founder of firehol.org.

[netdata](https://github.com/firehol/netdata/) is a distributed real-time monitoring solution we develop. The project is using the domains:
- my-netdata.io
- mynetdata.io
- firehol.org
- netdata.rocks

for providing its users with features that depend on assigning permanent cookies on the users browsers. For example, the netdata registry provides a personalized list of netdata servers each user uses, and works like this:

![image](https://cloud.githubusercontent.com/assets/2662304/15268669/2990d818-19ef-11e6-831f-4328c8484424.png)

More information about the netdata registry: https://github.com/firehol/netdata/wiki/mynetdata-menu-item

The result of this function is that each user gets a personalized list of netdata servers it uses, like this:

![image](https://cloud.githubusercontent.com/assets/2662304/15653074/6664f3ea-2693-11e6-8514-74c308f0a8a6.png)

This is a feature our users expect to use to have the full functionality of netdata. The menu option `What is this?` sends the users to the link I posted above, that describes how this works. You can check a netdata dashboard yourself, by navigating to these urls, in this order:
1. http://london.netdata.rocks (the my-netdata menu on the dashboard will show only london)
2. http://atlanta.netdata.rocks (the my-netdata menu on the dashboard will show both london and atlanta)

Is there anything we can do to have the netdata permanent cookies whitelisted?

**Comment by cooperq** [comment]
Hi @ktsaou 
please read the following FAQ items. And see if that answers your question. 
https://www.eff.org/privacybadger#faq-How-does-Privacy-Badger-work?
https://www.eff.org/privacybadger#faq-Does-Privacy-Badger-contain-a-"black-list"-of-blocked-sites?
https://www.eff.org/privacybadger#faq--I-am-an-online-advertising-/-tracking-company.--How-do-I-stop-Privacy-Badger-from-blocking-me?

If this does not help, I wonder if #781 would be the solution that would work.

**Comment by ghostwords** [comment]
Hi @ktsaou, did you end up adopting the [EFF Do Not Track policy](https://www.eff.org/dnt-policy) on any of your domains?

**Comment by ktsaou** [comment]
Hi,

I have added DNT support in netdata, but it is optional and not enabled by default.
As I see it, DNT is about respecting the policy and not attempt to use cookies at all.

In netdata case however, this will not help. netdata is a distributed application. It relies on cookies  and CORS to offer its features. Users need to allow tracking to get the full functionality out of it. 

My domains are demo sites for the application, so I don't see how DNT will help in this case.
