### ISSUE TITLE
connect.facebook.net breaks dictionary.com, axios.com, etc.

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#862]
http://www.dictionary.com/browse/test

Strangely, `connect.facebook.net` needs to be on yellow for the Word of the Day, Difficulty Index, and Spell/Syllables buttons to function. This used to work.

Previously, blocking doubleclick (with Ghostery) would break these functions, but that was fixed by Ghostery's script surrogate feature. Now it's Facebook that's causing the breakage.

Would this be a good candidate for #400?

**Comment by terrorist96** [comment]
It also breaks the `Examples` and `Word Origin`links.

**Comment by cooperq** [comment]
yea might be a good candidate for #400 I bet a lot of things depend on facebook connect.

**Comment by terrorist96** [comment]
Don't wanna be that guy... but this has been broken for over a year now.

**Comment by ghostwords** [comment]
Sorry! I started on creating a surrogate for Facebook Connect a few months ago but ran into some issues, need to check what happened exactly.

We'll be going through and fixing broken site reports in the coming weeks, now that the yellowlist incidents have hopefully been put behind us.

**Comment by terrorist96** [comment]
https://www.axios.com/

Article category blocked:
![image](https://user-images.githubusercontent.com/12802056/28985357-275895c6-7930-11e7-8316-bb5eeeffe7b0.png)

Also, if you scroll to the end, it will never load more articles.

Culprit: `connect.facebook.net`

**Comment by ghostwords** [comment]
Unable to reproduce at this point.
