### ISSUE TITLE
Lidl Reisen broken

### ISSUE THREAD

**Issue by KommX** [EFForg/privacybadger#880]
Blocking "www.lidl-onlinenewsletter.de" breaks http://www.lidl-reisen.de/newsletter

**Comment by KidPluto** [comment]
I see "https://www.lidl.de/", and this "https://www.lidl.de/de/newsletter" now.  I don't see any "*newsletter*" in the selections.  Can't reproduce the issue.  Thanks.

**Comment by KommX** [comment]
I don't get why you can't reproduce this.

Go to the site http://www.lidl-reisen.de/newsletter
It loads "external" content via
`<iframe id="newsletter_include" src="https://www.lidl-onlinenewsletter.de/forms/travel/de/newsletter_form.html" frameborder="0"></iframe>`
When privacy badger blocks loading content from www.lidl-onlinenewsletter.de, which it does for me, then the site is broken.

**Comment by KidPluto** [comment]
Going here: "http://www.lidl-reisen.de/newsletter", I get the same result.  Regardless of PB being enabled or disabled.

**Comment by KidPluto** [comment]
I am getting "www.lidl-onlinenewsletter.de" with a green slider by default.  When I move it to red the page doesn't load.

**Comment by KommX** [comment]
The thing is that PB "learned" to block it because "www.lidl-onlinenewsletter.de" is included by different Lidl domains. And blocking it breaks the including site.
