### ISSUE TITLE
Tiny social integration (Twitter) button replaced by Privacy Badger, is now HUGE

### ISSUE THREAD

**Issue by eilamg** [EFForg/privacybadger#890]
Small Twitter button replaced by Privacy Badger turned gigantic.

Without Privacy Badger:
![image](https://cloud.githubusercontent.com/assets/4570254/17515986/6cac2d70-5e44-11e6-8f47-9176198c9c13.png)

With:
![image](https://cloud.githubusercontent.com/assets/4570254/17516002/91e17082-5e44-11e6-8910-bb0a32dff80b.png)

This happend [Here](https://zachholman.com/posts/documentation/), with Privacy Badger 2016.5.24, running in Chrome Version 52.0.2743.82 (64-bit) on Ubuntu 16.04.

**Comment by kmiyashiro** [comment]
Looks like instead of creating one huge badge, it now creates a duplicate badge.

![screen shot 2017-11-27 at 5 43 59 pm](https://user-images.githubusercontent.com/71852/33298373-d249132e-d39a-11e7-8f73-be06b15771ea.png)

**Comment by ghostwords** [comment]
Here is a different page where you can still see the huge replacement button bug in action: https://www.clalit.co.il/he/your_health/family/cancer/Pages/watching_signs_of_cancer.aspx.

The duplicate replacement button is another bug, tracked in #788.

**Comment by lemnis** [comment]
to lazy to make a pull, a higher specificity of the selector would fix this issue, e.g. for this particular case possible solutions

* selecting the pb class multiple times at `socialwidgets.css:46`, 3 classes would fix this particular issue resulting in `.privacyBadgerReplacementButton.privacyBadgerReplacementButton.privacyBadgerReplacementButton{}`
* targeting the element by ID
* inline all styles and keep `!important` on them.

The last solution is the most difficult to brake by a site.

**Comment by rak-phillip** [comment]
I would like to take a look at this one, can I get assigned to the issue?

**Comment by ghostwords** [comment]
Hello! I think what you want to do is [make a pull request from a fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

**Comment by rak-phillip** [comment]
Will do, thanks!
