### ISSUE TITLE
conflicts with checkvist

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadger#891]
Submitted via email:

>  It looks like your Privacy Badger extension conflicts with our Checkvist
> Bookmarklet https://chrome.google.com/webstore/detail/checkvist-bookmarklet/pheahjlflgbnajeilgglgcdlbkdckamf?hl=en chrome extension, used to post links to Checkvist https://checkvist.com  from Google Chrome. We got a report from our user who could not use our bookmarklet when
> Privacy Badger is installed.

**Comment by ghostwords** [comment]
There are no user error reports that mention Checkvist. Closing as stale.
