### ISSUE TITLE
Preconfiguring Privacy Badger effectively for an enterprise deployment

### ISSUE THREAD

**Issue by BigWax** [EFForg/privacybadger#914]
I want to create a custom localhosted file that holds exceptions all of my domain users get so as to fix an issue with Privacy Badger blocking Google Drive downloads and other similar issues. 
The aim of this is to be spread via a GPO and configured centrally.

Any hints on how to achieve this ?

**Comment by cooperq** [comment]
I am actually working on deprecating the domain exception list, however the latest version of privacy badger fixes the issue with google drive so that shouldn't be a problem any more. What other issues are you facing?

**Comment by BigWax** [comment]
Well a internal site isn't functioning properly as well, except when I whitelist it. It would still be a pain to apply that manually to the 500+ computers we have currently.
Thanks very much for the work by the way! I've put this extension on over 1k computers by now probably.

**Comment by cooperq** [comment]
oh interesting, so you you actually want ot whitelist a specific site...

hmmm could you distribute the files in the extension directory, specifically the storage database with a copy of privacy badger that is pre-seeded and has the site you need whitelisted?  

The other option would be to add an option to specify a url to download a whitelist from. 

The third option would be to post the EFF DNT policy to your internal site, this would stop it from being blocked by privacy badger!

**Comment by BigWax** [comment]
Whatever is easiest to implement for you, I guess. 
I could spread the storage database through a GPO if you let me know which file it is and where it is located.
Whitelist would work too if that's a viable option. 

As for putting the DNT policy, I don't control the content of the site itself, I just moderate it locally, so I cannot do that and I assume the guy in charge would be too incompetent/lazy to do it.

Thanks again!

**Comment by cooperq** [comment]
I think that spreading the seeded DB with the site whitelisted through a GPO is the easiest and best solution. 

The extension database can be found here:
`<Path/To/Chrome/Profile>/Default/Local Extension Settings/pkehgijcmpdhfbdbbnkijodmdjhbjlgp`

**Comment by ghostwords** [comment]
Closing for now; let us know if you have any more questions.

**Comment by ghostwords** [comment]
@BigWax Privacy Badger just got proper enterprise policy configuration support in #2215. This will be part of the next release.
