### ISSUE TITLE
"Report Broken Site" wording somewhat unclear

### ISSUE THREAD

**Issue by alexristich** [EFForg/privacybadger#919]
I've been talking to several people who are users of the extension, and many of them didn't understand the purpose of the "Report Broken Site" button. I think there is some room for improvement in the wording. The main source of confusion seems to stem from the ambiguity of what "broken" means in this case. Specifically, I offer up the suggestion, "Did Privacy Badger break this site? Let us know!"

Also, a stylistic suggestion - it would be nice if the font size was increased slightly for the text on these buttons.

**Comment by cooperq** [comment]
Seems like a good issue to make a patch for :wink:

**Comment by KidPluto** [comment]
Looks fixed, should be closed.  Thanks.

**Comment by alexristich** [comment]
Whoops, thanks for pointing this out! Will close it now :)
