### ISSUE TITLE
Move tests on third party sites to own servers

### ISSUE THREAD

**Issue by gunesacar** [EFForg/privacybadger#928]
The Travis tests that fail most often relies on third party sites like jsfiddle.net and rawgit.com.

We better move these tests to EFF's own servers (e.g. the ones used on pbtest.org) to improve reliability.  We could be hitting to rate limits for Travis IPs. Also jsfiddle.net adds tons of other scripts and cookies that we don't expect.

I extracted tests on third-party sites to following gists. We should move them to new servers and update the URLs in the super_cookie_test.py file.
- [jsfiddle.net/uon507ut](https://gist.githubusercontent.com/gunesacar/ca8edde306aa22ef214a70f5bbea3acc/raw/6118f814e0047d2c1bb0b202c85f4164c1cae9ae/frame_ls.html)
- [jsfiddle.net/21za32ve/1/](https://gist.githubusercontent.com/gunesacar/ebf1ea769f2b6cc457cc2bbea3fdc0fa/raw/ddfda290834af8fabdb65e2b431cd5d4ca6621d1/low_entropy_localstorage_from_third_party_script.html)
- [jsfiddle.net/gzehyh92/](https://gist.githubusercontent.com/gunesacar/1feea0c10286ba9d27948a0a827cb115/raw/552e1ee6cf5a81fbe6a2b7fd369d949e34927155/localstorage_from_third_party_script.html)
- [http://jsbin.com/soluqi/1/](https://gist.github.com/gunesacar/79aa14bac95694d38425d458843dacd6)
- [https://rawgit.com/gunesacar/43e2ad2b76fa5a7f7c57/raw/44e7303338386514f1f5bb4166c8fd24a92e97fe/set_ls.html](https://gist.githubusercontent.com/gunesacar/43e2ad2b76fa5a7f7c57/raw/44e7303338386514f1f5bb4166c8fd24a92e97fe/set_ls.html)
- [https://rawgit.com/gunesacar/aecff0fffefb24c26f4c/raw/90f94430a255303fd79f7227e7f128b8c8a7b86d/set_lo_entropy_ls.html](https://gist.githubusercontent.com/gunesacar/aecff0fffefb24c26f4c/raw/90f94430a255303fd79f7227e7f128b8c8a7b86d/set_lo_entropy_ls.html)

This is to partially address #924.

**Comment by cowlicks** [comment]
I think the proper way to do this would be to dockerize the tests, so they can be run entirely locally. We could also stand up some of the test endpoints on the public internet, in case someone wants to run the tests without docker.

If we open sourced pbtest we could start adding the code there.

**Comment by ghostwords** [comment]
Just to clarify, do you suggest to bundle serving test fixtures with the tests? And since setting up local serving might be complicated by things like having to fake hostnames (I think? what else?), Docker might be of use.

>pbtest

Tests on https://pbtest.org/?

**Comment by cowlicks** [comment]
@ghostwords yes I was suggesting this, you can set up a fake network with docker.  I think it should be discussed more, whenever we revisit this issue later. This isn't a priority, and I'm not convinced it would be worth the effort.

But I think https everywhere might do something like this already, and Panopticlick (which https://pbtest.org/ is based on) is already dockerized. I plan on chatting with @Hainish about it when I see him.

**Comment by ghostwords** [comment]
This is mostly no longer a problem thanks to retrying and other workarounds. We might still come back to this but we don't need to keep the issue open.

I think ideally the fixtures would live in this repo and be served as needed by a local server (for example, `self.serve(FIXTURE_URL)` in a test). We would simulate first- and third-party interactions via the hosts file. Docker would ease this setup but shouldn't be required.

**Comment by ghostwords** [comment]
All test fixtures have been moved to two sets of GitHub Pages ([1](https://github.com/EFForg/privacybadger-test-fixtures), [2](https://github.com/EFForg/privacybadger-test-fixtures-alt)) as of 8e589929a8935154ea75f734074b75c515747adc.
