### ISSUE TITLE
refactor social buttons to act more like surrogates

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadger#931]
We are async injecting social buttons every page load, this should be a replacement instead only when it was loaded. cc @ghostwords

**Comment by ghostwords** [comment]
Suggested approach should be more performant (social replacement only kicks in when needed instead of on every page load) and should resolve all outstanding race conditions such as #892 (replacement happens at the right time instead of possibly too late or too early).

**Comment by ghostwords** [comment]
Closing as too much work for unclear benefit (performance impact seems low; replacement race condition only affects yellowlisted widgets, yellowlisted widgets aren't blocked so this wouldn't help ...).
