### ISSUE TITLE
resources from CDNs getting blocked (vk.com)

### ISSUE THREAD

**Issue by Thorsten-Sick** [EFForg/privacybadger#965]
vk.com is using resources (images) from cs7064.vk.me (or better *.vk.me). Privacy Badger has the tendency to learn and block that.
Switching to "block cookies" fixes the displaying of images.
There seem to be more pages with similar issues (I'll add them as soon as I get good bug reports).

As our Scout browser - which is using Privacy Badger - is a consumer product we do not expect our users to be able to configure it properly.
suggestion:
Maybe have a way to fix the top100 pages where this happens by adding a JSON config like:
"main": "vk.com" {
"_.vk.me": yellow,
"_.vk.foo":green
}
To pre-seed the PB classification

**Comment by cooperq** [comment]
Seems like a good plan, could probably be done in conjunction with #121 
what would your ideal version of this look like? Do you have anyone with the extra cycles to submit a pull request?

**Comment by Thorsten-Sick** [comment]
Could be me who's coding it. I'll check with my boss for priorities.

**Comment by ghostwords** [comment]
If these are popular pages that pass Privacy Badger's [criteria for "yellow list" inclusion](https://github.com/EFForg/privacybadgerchrome/blob/master/doc/yellowlist-criteria.md), we should add them to the [yellow list](https://www.eff.org/files/cookieblocklist.txt) so that all users benefit.

**Comment by Thorsten-Sick** [comment]
I have a PR ready. It is much simpler than first suggested. I tested it with several domains but left only vk.me in. This is the one where I got the bug requests. Feel free to add other domains from other bug reports.

Fun fact: I was not able to reproduce the vk.me report. My PB never learned *.vk.me to "block" status. No matter how much of the Russian web I surfed.... So this specific fix is a shot in the dark. Maybe you have someone who has the issue on a PC where we can test on.

**Comment by cooperq** [comment]
@Thorsten-Sick sorry for the delay on getting back to you about this! We can put vk.me on the cookie block list without adding all of this extra infrastructure. Are you planning to ship a more comprehensive seed file with avira browser?

**Comment by Thorsten-Sick** [comment]
NEW: PB is not active in Scout default mode anymore (our own Anti-Tracker based on lists covers default alone). So the emergency is de-fused now....

I think: If we could find a way how we can contribute fixes to broken pages in the upstream PB we would cover the needs of more people. Scout users or non-Scout users. You would benefit from our bugfixes, we as Avira obviously would benefit from your feedback and experience :-)

Maybe we can find a simple process how we can contribute bug reports/fixes and have them released within weeks. Looking at the Issues site-bugs tend to stick around....

That said: We also do not get proper bug reports in this area. Seems hard to reproduce or test for average users if PB learns something wrong.

Maybe this is the first thing to solve. Getting better reports. And yes, I am reading the mailing list :-)

**Comment by cooperq** [comment]
Glad to hear the crisis is averted for now, I would still like to get PB so that it's not constantly breaking CDNs and it would be great to have assistance from you guys in this. I'm a little wary of the pre-seed file solution because I feel like it could look too much like we are shipping a black list with privacy badger which is something we most definitely do not want to do. We can already add domains to the cookie block list to unblock them (though not entriely). And I think that perhaps using the social widget replacement machinery is a better way to give users the ability to unblock certain tracker-y services that they enjoy such as facebook connect. Please tell me if you think my instincts are wrong in this case however. 

I would definitely welcome any help from your team looking into some of these site bugs. I try to fix many of them quickly but the numbers do get a bit overwhelming.

**Comment by Thorsten-Sick** [comment]
NEW: PB is not active in Scout default mode any more (our own Anti-Tracker based on lists covers default alone). So the emergency is de-fused now....

I think: If we could find a way how we can contribute fixes to broken pages in the upstream PB we would cover the needs of more people. Scout users or non-Scout users. You would benefit from our bugfixes, we as Avira obviously would benefit from your feedback and experience :-)

Maybe we can find a simple process how we can contribute bug reports/fixes and have them released within weeks. Looking at the Issues site-bugs tend to stick around....

That said: We also do not get proper bug reports in this area. Seems hard to reproduce or test for average users if PB learns something wrong.

Maybe this is the first thing to solve. Getting better reports. And yes, I am reading the mailing list :-)

**Comment by cooperq** [comment]
@Thorsten-Sick did you mean to repost the same comment?

**Comment by Thorsten-Sick** [comment]
No, we currently ship PB directly from the Chrome Web Store. We do not change anything and do not plan to do so in the future.
Should we open an issue for all broken pages reported to us ?

**Comment by Thorsten-Sick** [comment]
@cooperq : I did not mean to re-post. Something cached and did not re-load, it seems. Sorry

**Comment by cooperq** [comment]
@Thorsten-Sick it is my hope that between: cookie block list, script surrogates, multi-domain first parties, and widget replacement that we should be able to fix every broken website. If you guys can open issues for the broken sites you encounter that would be great! Even better if you guys wanted to help submit patches for your biggest problem sites that would be huge!

**Comment by cooperq** [comment]
Thanks! And I should have a fix for vk.com in #1152 which will go out today.
