### ISSUE TITLE
MS Edge & Multiprocess Firefox support (WebExtensions)

### ISSUE THREAD

**Issue by Artoria2e5** [EFForg/privacybadger#967]
Microsoft Edge and Multiprocess Firefox both support extensions written with [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) API, which is largely compatible with Chrome's Blink Extension API. As ABP is already available for MS Edge in Windows Store, I expect to see a version of Privacy Badger for Edge too. (Microsoft actually has a tool to do that porting for Edge.)

WebExtensions API is making XUL & Addon-SDK legacy in Multiprocess FF, so some support will be good for the future.

Edit: I mistook WebExtensions as a W3C TR like WebDriver.

**Comment by groovecoder** [comment]
This is done. This repo is now the single WebExtensions code-base for both Firefox and Chrome.

**Comment by alexristich** [comment]
Ah, indeed it is! This is one of the ones that I batch labeled; probably should have looked at it first :) Thanks!

**Comment by Artoria2e5** [comment]
Is there any plan to submit to Windows' Edge extension repo though?

**Comment by alexristich** [comment]
Likely in the near future, yeah. For now it looks like only a small handful of extensions are supported, and there is a "queue" for new extensions: https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/guides/packaging/. It seems they aren't yet done implementing the WebExtensions API and have decided to scale up slowly.

My guess is the submission will be done in tandem with HTTPS Everywhere.

**Comment by ghostwords** [comment]
Created #1290 to track Microsoft Edge support.
