### ISSUE TITLE
Implement WebRTC protection for Firefox

### ISSUE THREAD

**Issue by groovecoder** [EFForg/privacybadger#976]
Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1312802

**Comment by ghostwords** [comment]
We use feature detection (see below), so we shouldn't need to do anything at this point.

https://github.com/EFForg/privacybadger/blob/6aa91b2fb7169a9a53acca7f01f539875c85bbda/src/js/background.js#L74-L103
