### ISSUE TITLE
i.embed.ly breaks images

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#978]
`i.embed.ly` needs to be moved to yellow to fix the image in the third comment (Obama) and one of the images further down in the comments by JabariAyindeCummings (imgflip) [note I'm talking about his second post, the first one loads fine, the third one has an unrelated error].

http://genius.com/Lupe-fiasco-mural-lyrics

**Comment by cooperq** [comment]
fixed, thanks!
