### ISSUE TITLE
#.bp.blogspot.com breaks image

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#979]
`4.bp.blogspot.com` should be moved to yellow. It breaks the Chrome logo:

https://googlechromereleases.blogspot.com/

Shouldn't PB recognize that they are both blogspot.com and not block it as it's a first party, not third party?

`3.bp.blogspot.com` is also blocked, but I can't see it breaking anything at the moment, but it could and I just don't see it, or it could in the future.

**Comment by terrorist96** [comment]
https://motorola-blog.blogspot.com/2016/11/transform-smartphone-challenge-moto.html

`3.bp.blogspot.com` blocks image in upper left.

**Comment by terrorist96** [comment]
https://youtube-creators.googleblog.com/2016/11/new-tools-to-shape-conversations-in.html

`4.bp.blogspot.com` breaks image at bottom.

**Comment by terrorist96** [comment]
https://gsuiteupdates.googleblog.com/2016/08/a-new-google-hangouts-chrome-extension.html

3.bp.blogspot.com

Should be on yellow. Blocks image.

**Comment by terrorist96** [comment]
http://www.organicandhealthy.org/2016/11/aldi-goes-full-organic-bans-pesticides.html

Images hosted on `4.bp.blogspot.com`, being blocked.

**Comment by terrorist96** [comment]
http://crimeresearch.org/2013/12/murder-and-homicide-rates-before-and-after-gun-bans/

`2.bp.blogspot.com`

**Comment by terrorist96** [comment]
http://blog.erratasec.com/2016/10/yes-we-can-validate-wikileaks-emails.html

**Comment by cooperq** [comment]
fixed, thanks!
