### ISSUE TITLE
tv.xfinity.com 

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#985]
https://tv.xfinity.com 

`xtvapi.cloudtv.comcast.net`
`login.comcast.net`
`edge.myriad-gn-xcr.xcr.comcast.net`
`ccr.col-jitp2.xcr.comcast.net`
`mm.col-jitp2.xcr.comcast.net`
`odol-atsec-njs-31.col-jitp2.xcr.comcast.net`
`odol-atsec-njs-15.ip-ads.xcr.comcast.net`
`odol-atsec-njs-15.ip-ads.xcr.comcast.net`
`ccr.linear-nat-pil.xcr.comcast.net`
`odol-atsec-njs-01.linear-nat-pil.xcr.comcast.net`
`odol-atsec-njs-15.col-jitp2...` (can't find the full name for this since names are truncated in the settings page)
`odol-atsec-njs-08.cim-linear-nat-pil.xcr.comcast.net`
`odol-atsec-njs-09.cim-linear-nat-pil.xcr.comcast.net`
`odol-atsec-njs-17.cim-linear-nat-pil.xcr.comcast.net`

and there's probably a lot more....

should be moved to yellow (probably green else it keeps signing you out). It prevents you from using xfinity cloud dvr, blocks images, causes playback to randomly go back to the beginning (highly annoying when a certain program doesn't allow for skipping commercials), etc. and it's not a third party tracker because xfinity = comcast.

**Comment by cooperq** [comment]
fixed, thanks!
