### ISSUE TITLE
pcworld.com images broken

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#992]
http://www.pcworld.com/article/2972721/software-games/the-17-best-educational-games-of-the-70s-80s-and-90s.html

`core0.staticworld.net` and `images.techhive.com` need to be moved from red to yellow to fix article images.
There's a lot of other *.staticworld.net subdomains being blocked too. They might cause breakage of other stuff on other pages. IDK

Edit: yeah, `core4` and `csmb` block images at the bottom, core5 blocks the last image in the related slideshows section.
So can `*.staticworld.net` and `images.techhive.com` be moved to the cookieblock list? Or surrogate?

**Comment by terrorist96** [comment]
http://www.infoworld.com/article/3142197/microsoft-windows/users-should-avoid-microsofts-just-released-preview-windows-patches.html

Same deal

**Comment by cooperq** [comment]
fixed, thanks!

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.
