### ISSUE TITLE
www.googletagservices.com breaks images

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#993]
http://www.vice.com/en_us

Half the articles' image don't load cuz of `www.googletagservices.com`. Moving to yellow fixes it.

Applies on article pages too. Example:
http://www.vice.com/read/north-korea-is-stoned-all-the-time-which-explains-a-lot

**Comment by cooperq** [comment]
might be a good candidate for a script surrogate. @ghostwords

**Comment by terrorist96** [comment]
#400

**Comment by terrorist96** [comment]
@ghostwords still broken for me. :disappointed:

**Comment by ghostwords** [comment]
@terrorist96 Is this still an issue, or was it resolved when we released surrogates? [Previously](https://github.com/EFForg/privacybadger/issues/823#issuecomment-266750354).

**Comment by terrorist96** [comment]
It's been fixed for me.
