### ISSUE TITLE
Includes Mozilla-blacklisted jquery version

### ISSUE THREAD

**Issue by chipb** [EFForg/privacybadger#996]
I went the route of @willsALMANJ in https://github.com/EFForg/privacybadgerfirefox/issues/208#issuecomment-247767488 and tried self-signing a version of this extension for my own use through AMO.

Unfortunately, their automated linter balks at a blacklisted version of jQuery in my upload.
![amo-error](https://cloud.githubusercontent.com/assets/995144/20458571/a4f1f782-ae5d-11e6-865d-e33c1fa34bef.png)

I imagine this error will need to be resolved before this version of Privacy Badger can replace the legacy Firefox version.

**Comment by willsALMANJ** [comment]
Interesting. It looks like they banned JQuery 1.x shortly after I posted that comment:

https://github.com/mozilla/addons-linter/commit/2dcc2226e2ec9dea65708b0a1cc97a9cd593d82d

**Comment by cooperq** [comment]
fixed. Thanks!
