### ISSUE TITLE
The 7th slide in the tutorial has a grammatical error.

### ISSUE THREAD

**Issue by billywaite** [EFForg/privacybadger#997]
The error is in [this slide](https://github.com/EFForg/privacybadger/blob/94601ad62ca1c6b309d4b566f1624f657490eebe/src/icons/slideshow/PB-layouts-07.png).

Currently, the slide says: "If the slider is green that means that I can't tell if this domain is tracking you yet." 

It should say: "If the slider is green**,** that means that I can't tell if this domain is tracking you yet."

Just an added comma after green for consistency with the slide 5 and 6.

**Comment by ghostwords** [comment]
Related: #489.
