### ISSUE TITLE
jsDelivr CDN incorrectly blocked

### ISSUE THREAD

**Issue by gouch** [EFForg/privacybadger#998]
For me, Privacy Badger just decided cdn.jsdelivr.net requests need to be blocked entirely.

![jsdelivr](https://cloud.githubusercontent.com/assets/38445/20489166/9dd567ec-afd7-11e6-8d6b-970945856af8.png)

This doesn't make sense to me, though, since as a CDN, it doesn't set any cookies. Is this possibly a badger bug / can this CDN be whitelisted?

**Comment by ghostwords** [comment]
Hi gouch, sorry for the late response! I'd like to figure out how Badger decided to start blocking `jsdelivr.net`. Which browser do you use?

**Comment by gouch** [comment]
No problem. I don't privacy badger installed anymore, unfortunately, so I won't be able to show logs or settings. This happened in Chrome, though

**Comment by ghostwords** [comment]
This bug should be fixed in Privacy Badger version 2017.6.13.1 (by #1403 and #1428). Please let me know if you run into it again with the new version.
