### ISSUE TITLE
cdn(s).gigya.com blocks images

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadger#999]
http://www.dailystar.co.uk/news/latest-news/563846/twitter-child-sex-porn-ring-pizzagate-gamer-leaks-thousands-of-social-media-accounts

`cdn.gigya.com` and `cdns.gigya.com` block images for articles on right.

**Comment by cooperq** [comment]
wontfix thanks

**Comment by terrorist96** [comment]
#400 ?

**Comment by terrorist96** [comment]
Sorry to say, but the images still don't load unless I move cdn(s).gigya.com from red to yellow. @ghostwords

**Comment by ghostwords** [comment]
@terrorist96 Is this still an issue, or was it resolved when we released surrogates? [Previously](https://github.com/EFForg/privacybadger/issues/823#issuecomment-266750354).

**Comment by terrorist96** [comment]
It's fixed. Thanks!
